### ISSUE TITLE
input #+roam_tags: with the help of complete-symbol or something alternative

### ISSUE THREAD

**Issue by pengpengxp** [org-roam/org-roam#1001]
### Brief Abstract
input #+roam_tags: with the help of complete-symbol or something alternative

### Long Description
I input a lot of tags so that a can find a note very quickly by the help of ivy. But when I input tags in each file, I hope I can use complete-symbol or ivy to  read all tags that already exists. If match, exists tags is inserted, or what I acctually input is inserted.

### Proposed Implementation (if any)
A variable org-roam-all-tags that store all exists tags?  

### Please check the following:

- [Y] No similar feature requests

**Comment by zaeph** [comment]
We could have a command to set `roam-tags` à la `counsel-org-tag`.  We'd retrieve the tags used in the db to use them as a completion list.
