### ISSUE TITLE
org-roam--get-backlinks hangs if title contains a single quote

### ISSUE THREAD

**Issue by madalu** [org-roam/org-roam#1007]
### Description

If I call M-x org-roam in a file with a title that contains a single quote, emacs hangs, requiring a C-g to stop the process. The backlinks for the file are never displayed. In addition, once the backlinks buffer has been activated, any attempt to save the file will also cause emacs to hang.

I traced the problem to org-roam--get-backlinks. The sql statement that that function composes is incorrect because the single quote in the title is not escaped.

#### Steps to Reproduce

 Create an org-roam file with a title containing a single quote. E.g.,

 #+TITLE: ABC's

 Then call org-roam within that file. Notice how emacs hangs until you press C-g.

 The problem is that org-roam--get-backlinks is composing a sql statement that looks like this:

 SELECT "from", "to", "properties" FROM links WHERE "to" = '"ABC's"'

 Notice that the single quote in the title is not escaped.

#### Backtrace

To get this backtrace, I evaluated the relevant part of org-roam--get-backlinks in the buffer described above.

    Debugger entered--Lisp error: (emacsql-error "near line 315: near \"s\": syntax error")
      signal(emacsql-error ("near line 315: near \"s\": syntax error"))
      #f(compiled-function (conn) #<bytecode 0xfcdcc9>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection>)
      apply(#f(compiled-function (conn) #<bytecode 0xfcdcc9>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection> nil)
      emacsql-parse(#<emacsql-sqlite3-connection emacsql-sqlite3-connection>)
      #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x103068d>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection> "SELECT \"from\", \"to\", \"properties\" FROM links WHERE \"to\" = '\"ABC's\"'")
      apply(#f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x103068d>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection> "SELECT \"from\", \"to\", \"properties\" FROM links WHERE \"to\" = '\"ABC's\"'")
      emacsql(#<emacsql-sqlite3-connection emacsql-sqlite3-connection> "SELECT \"from\", \"to\", \"properties\" FROM links WHERE \"to\" = '\"ABC's\"'")
      org-roam-db-query("SELECT \"from\", \"to\", \"properties\" FROM links WHERE \"to\" = '\"ABC's\"'")
      (let ((targets (org-roam--extract-titles))) (org-roam-db-query (concat "SELECT \"from\", \"to\", \"properties\" FROM links WHERE " (string-join (mapcar (function (lambda (target) (concat "\"to\" = '\"" target "\"'"))) targets) " OR "))))
      eval((let ((targets (org-roam--extract-titles))) (org-roam-db-query (concat "SELECT \"from\", \"to\", \"properties\" FROM links WHERE " (string-join (mapcar (function (lambda ... ...)) targets) " OR ")))) nil)
      elisp--eval-last-sexp(nil)
      eval-last-sexp(nil)
      funcall-interactively(eval-last-sexp nil)
      call-interactively(eval-last-sexp nil nil)
      command-execute(eval-last-sexp)

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
 of 2020-05-19
- Framework: N/A
- Org: Org mode version 9.3.7 (release_9.3.7-691-g05fac0 @ /home/madalu/org-mode/lisp/)
- Org-roam: 1.2.1

**Comment by madalu** [comment]
My apologies. I think I had accidentally loaded an older version of org-roam-db.el. All is working fine in the most recent version. Closing.

**Comment by madalu** [comment]
The commit that introduced this issue was da6fdd752.

**Comment by jethrokuan** [comment]
Thanks for the investigation, should be fixed now
