### ISSUE TITLE
Note buffer narrowed to a subheading causes org-roam-find-file to catalog note incorrectly

### ISSUE THREAD

**Issue by togakangaroo** [org-roam/org-roam#1013]
## Example

1. Create a note with a series of subheadings. For example I have one for `Racket` and subheadings `Beautiful Racket`, `Fear of Macros`, and `Playground`. Save it.
2. Flip to another buffer, do `org-roam-find-file` to find your note under its note title
3. Narrow the buffer to just one subheader. 
4. Add some text, save your note.
5. Flip to another buffer 
6. Ty to `org-roam-find-file` again. Note that it doesn't appear under its title! It appears under the subheading title

## Expected Results

I would expect the note to always appear under the title of the *note* not of the heading I have things narrowed to. Worse this isn't even consistent. If you widen after saving (and before saving again) it will *still* appear under the subheading.

## Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
 of 2019-09-02
- Framework: Spacemacs
- Org: Org mode version 9.3.7 (9.3.7-15-gc9abb4-elpaplus @ /Users/gmauer/.emacs.d/elpa/develop/org-plus-contrib-20200727/)
- Org-roam: 1.2.1

**Comment by zaeph** [comment]
I'm not sure if I understand your point.  If you mean that the title of the note is replaced by the heading to which you're narrowed in the completion-list for `org-roam-find-file`, it's not the case on my end, and I don't see anything in the codebase that would cause it.

If you mean that `org-roam-find-file` brings you to the narrowed buffer of the note, it's expected.  We could force the buffer to be widened upon access, but that'd be going out of our way to fix a non-existing problem.  `org-roam-find-file` and `org-roam-switch-to-buffer` are meant to make you jump quickly between your notes, and if you narrowed one of them, chances are you had a good reason for doing so in the first place.  If you want to work on a narrowed version of a note, but want to preserve the original buffer when finding the file, consider using `org-tree-to-indirect-buffer`.

**Comment by togakangaroo** [comment]
If my note is titled "Racket", in order to navigate to it with
org-find-file I type "Racket" (or some part of that and select from helm of
course). However, in the above scenario let's say I'm narrowed to the
"Macros" sub heading. Searching "Racket" will not find it as it appears
under "Macros"

**Comment by zaeph** [comment]
I can reproduce this, and it's trivial to fix.  I'll address this tomorrow.

**Comment by togakangaroo** [comment]
Thank you. I really appreciate the project and do plan to get more involved
at some point

**Comment by zaeph** [comment]
Problem should be fixed now.  Make sure to update your package.  Thanks for reporting it!
