### ISSUE TITLE
Wrong backlink for todo.org

### ISSUE THREAD

**Issue by anildigital** [org-roam/org-roam#1015]
![image](https://user-images.githubusercontent.com/266/89723895-ec32a100-da19-11ea-8446-4285ccdf1604.png)

I wonder where is `../../org/notes` coming from. Here is my org config https://gist.github.com/7ffd741febc0f32bb10ae1124c32ad78

```
- Emacs: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G73))
 of 2020-07-29
- Framework: N/A
- Org: Org mode version 9.3 (release_9.3 @ /usr/local/Cellar/emacs-plus@27/27.0.91/share/emacs/27.0.91/lisp/org/)
- Org-roam: 1.2.1
```

**Comment by jethrokuan** [comment]
Fixed with #1099
