### ISSUE TITLE
graph not opening automatically with org-roam-graph

### ISSUE THREAD

**Issue by n14s** [org-roam/org-roam#1019]
### Description
When I run org-roam-graph the required files are created in the /tmp/ folder but they aren't opened automatically. I can tell firefox to open the svg file manually. After a lot of browsing I cannot find anybody with a similar issue.

One guess is that I'm running emacs as superuser and I need to change the opening rights of the privileged files before opening manually with firefox.

My org-roam config is the following:
(require 'org-roam)
(setq org-roam-directory "~/drive/org")
(setq org-roam-graph-executable "/usr/bin/dot")
(setq org-roam-graph-viewer "/usr/bin/firefox")
(add-hook 'after-init-hook 'org-roam-mode)

#### Steps to Reproduce

1. Load Emacs (as superuser)
2. Open org-file in roam folder
3. Run org-roam-graph

#### Backtrace

N/A

#### Expected Results

Creating graph files and opening graph with firefox.

#### Actual Results

Graph files created, but graph is not being opened.

Statusbar showing "(org-roam) building graph"

### Environment

- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2019-09-16
- Framework: Spacemacs
- Org: Org mode version 9.3.6 (9.3.6-43-gc77edd-elpaplus @ /home/mrpeanutbutter/.emacs.d/elpa/26.3/develop/org-plus-contrib-20200413/)
- Org-roam: 1.2.1

**Comment by jethrokuan** [comment]
A lot has changed, feel free to reopen if still an issue.
