### ISSUE TITLE
Defect in documentation: multiple org-roam page is underdefined

### ISSUE THREAD

**Issue by Trevoke** [org-roam/org-roam#1025]
### Description

The documentation for multiple org-roam directories https://www.orgroam.com/manual/How-do-I-have-more-than-one-Org_002droam-directory_003f.html#How-do-I-have-more-than-one-Org_002droam-directory_003f

should also talk about the custom location for the org-roam database.

#### Steps to Reproduce

1. Set a custom global org-roam database
2. Follow the instructions in the documentation https://www.orgroam.com/manual/How-do-I-have-more-than-one-Org_002droam-directory_003f.html#How-do-I-have-more-than-one-Org_002droam-directory_003f

#### Expected Results

I can do `org-roam-find-file` from any roam directory and get the subset of files from the current directory

#### Actual Results

I get whatever last database I built

**Comment by zaeph** [comment]
Thanks for reporting it!
