### ISSUE TITLE
"invalid-function org-with-wide-buffer" when saving files on latest build

### ISSUE THREAD

**Issue by sjrmanning** [org-roam/org-roam#1026]
### Description

When saving files on the latest build I'm getting an error I believe introduced by #1016 — the issue is fixed for me by reverting that change.

I'm using a weird setup (GCC Emacs native-comp branch) so this could be related to that, or the org-version I'm using (9.3.7), but as at least one other person in the org-roam Slack has run into this I figured I would open a ticket.

#### Steps to Reproduce

1. Load an org-roam file.
2. Modify it.
3. Save.

#### Backtrace

```
Debugger entered--Lisp error: (invalid-function org-with-wide-buffer)
  org-with-wide-buffer(nil)
  org-roam-db--update-file()
......
```

```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.4.0, NS appkit-1894.40 Version 10.15.4 (Build 19E287))
 of 2020-08-10
- Framework: N/A
- Org: Org mode version 9.3.7 (release_9.3.7-700-ga1e5be @ mixed installation! /Applications/Emacs.app/Contents/Resources/lisp/org/ and /Applications/Emacs.app/Contents/Resources/lisp/org/eln-x86_64-apple-darwin19.4.0-abff6ce99a055711/)
- Org-roam: 1.2.1
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/0318983cac2ae8e75eec37f234aac3e5b8d15e53
```

**Comment by sjrmanning** [comment]
FWIW `org-with-wide-buffer` looks like this on my system:

```elisp
(defmacro org-with-wide-buffer (&rest body)
  "Execute body while temporarily widening the buffer."
  (declare (debug (body)))
  `(save-excursion
     (save-restriction
       (widen)
       ,@body)))
```

**Comment by jethrokuan** [comment]
i'm not sure how gccemacs works yet, but did you reperform a byte-compilation and the gccemacs equivalent of it? The error message seems odd because `org-with-wide-buffer` is actually a macro, so that should get substituted into the function body during byte compilation.

**Comment by sjrmanning** [comment]
I did re-compile after testing that the revert worked. I just ran through a bunch of tests and can confirm that it is related to native compilation — if I remove the eln (native output) directory and prevent automatic native compilation it works as expected. I'm going to close this and will reach out to the maintainer of gccemacs to try work out what's causing this. Thanks!

**Comment by sjrmanning** [comment]
After looking into this more, I realized this isn't compiling correctly due to the asynchronous nature of native compilation, and the fact that this file (`org-roam-db.el`) references `org-with-wide-buffer` without requiring `org` or `org-macs` in which it is defined. I've opened a PR #1033 to fix this.

**Comment by jmay** [comment]
I'm experiencing this now in a freshly-built emacs 28.0.50, latest org-roam v2.
