### ISSUE TITLE
documentation section about the automatic properties drawer, with option to disable?

### ISSUE THREAD

**Issue by hraban** [org-roam/org-roam#1029]
### Brief Abstract

I'd like to request a short blurb in the docs about the ID property created on a section when `org-roam-insert` creates a new page.
### Long Description
When I `org-roam-insert` a link that doesn't exist yet, i.e. create a new page from within that call, a new properties drawer is automatically created in the section that my cursor was in:

```org
  :PROPERTIES:
  :ID:       FEFD4876-54ED-403C-96BA-B48AFB7542CD
  :END:
```

I can't find anything in the docs about what this is for, what happens if you remove it, and if there is an option to disable it. It's quite confusing behaviour especially as everything seems to work fine when I remove it. What does it do?

It sounds like it has something to do with headline links, but when I remove them it still works fine. Do I need this?

### Proposed Implementation (if any)

* docs explaining the what & why
* an option to turn it off?
### Please check the following:

- [x] No similar feature requests -- there's quite a few issues around more functionality of headline links, but I'm a simple man with simple needs and I'd like to just disable this :)

**Comment by TimQuelch** [comment]
> but when I remove them it still works fine. Do I need this?

I suspect that it is still working after they are removed as the value is cached in the db.

If however, you rebuild the database after removing the property drawer your headline links will no longer work.

This is the ID that is used as a globally unique identifier for headlines so that you can link to them even if there are other headlines with the same name/text

**Comment by hraban** [comment]
Is it a new behaviour that headline anchors are automatically added when you create outgoing links to other pages? So if I'm in a.org and I add a link to alphabet.org (creating that file because it doesn't exist), suddenly the heading I was at, in a.org, has a properties drawer with an ID. is that new? required? do backlinks need this, at all?

**Comment by cpbotha** [comment]
This is for org-roam to support links and backlinks to and from headings inside org-files.

This screencast by @zaeph demonstrates the headline linking functionality: https://youtu.be/oyEMlIxIHXs

FYI, I have made a PR that adds a config variable for those of us who would prefer to disable this specific functionality: https://github.com/org-roam/org-roam/pull/1030

**Comment by jethrokuan** [comment]
That PR is now merged. I'll work on the docs after the fuzzy links flow is settled.

**Comment by jethrokuan** [comment]
With #1155 , this behaviour is no longer enforced.

**Comment by hraban** [comment]
thanks!
