### ISSUE TITLE
Using an org capture template inserts an ID property drawer

### ISSUE THREAD

**Issue by ahristow** [org-roam/org-roam#1034]
### Description
Using a capture template defined in `org-capture-templates` (for example, something like this):
```
(setq org-capture-templates
        '(("t" "TODO" entry (file "")
           "* TODO %?\n%U\n")))
```
inserts an `ID` property drawer in whatever org element the cursor is in when the capture template is called. For example, if my cursor is in the following element when I invoke `org-capture`,
```
* TODO Try to take over the world
[2020-02-09 Sun 15:48]
```
a property drawer is inserted in the item, then a new frame opens with the capture template. The item then looks like this:
```
* TODO Try to take over the world
:PROPERTIES:
:ID:      124a7ddc-2b6a-4c04-afd1-cc21b56e1c07
:END:
[2020-02-09 Sun 15:48]
```
and an .org-id-locations file is created in my .emacs.d. This happens for any .org file in my `org-roam-directory`, not just those containing TODO items. For example, if I'm working on some text and want to capture something, I end up with something like this:
```
* Heading
:PROPERTIES:
:ID:      124a7ddc-2b6a-4c04-afd1-cc21b56e1c07
:END:
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non pharetra augue. Vestibulum a nibh eu dolor elementum sodales et quis enim.
```
When I revert to the v1.2.1 release version of org-roam (commit hash 89e9121f26cf03bb7820d257cd9d9106916cd1e9) the problem disappears.

#### Steps to Reproduce
1. Install a recent version of org-roam. I believe, but cannot confirm, that I was using commit 30bfab7 when I first noticed the issue. I know it occurs with 11aac39.
2. Run `org-capture` while the cursor is in an .org file.

#### Backtrace

None. I do not believe an error is triggered.
#### Expected Results
`org-capture` runs without inserting an unexpected and unwanted property drawer in the item where the cursor is positioned.

#### Actual Results
When `org-capture` is called, an unexpected and unwanted property drawer with an auto-generated ID is inserted in the item where the cursor is positioned.

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-w64-mingw32)
 of 2019-08-29
- Framework: N/A
- Org: Org mode version 9.3.7 (release_9.3.7-708-g5417e3 @ c:/Users/xxxx/AppData/Roaming/.emacs.d/straight/build/org/)
- Org-roam: 1.2.1
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/11aac39a1b438b130a8f07730c346f8ef8e10907

**Comment by jethrokuan** [comment]
Org-roam enforces the use of IDs for linking to headlines, internally it manages a database of IDs to files. 

Org-capture calls `org-store-link` internally, so it is able to populate a template. Because ID usage is enforced for files within the Org-roam directory, this creates an ID.

If you don't link to headlines, then #1030 should resolve this problem.

**Comment by ahristow** [comment]
Thanks for the explanation, I'll have a look at #1030, but since I can see where headline linking might also be useful I'll also consider narrowing the scope of my org-roam directory so it includes only my notes and not the files containing my TODO items. Leaving this functionality active for my TODO items is a non-starter for me, though -- that's going to generate way too much clutter.
