### ISSUE TITLE
Link to notes from outside of org-roam-directory

### ISSUE THREAD

**Issue by ahristow** [org-roam/org-roam#1039]
### Brief Abstract
Allow/provide an interface for linking to notes from .org files outside of `org-roam-directory`.

### Long Description
It can be useful to link to a note from outside of the org-roam-directory. For example, a TODO item in a non-note .org file stored in `org-directory`, but outside of `org-roam-directory`, might be used to give quick access to background information on the task. This can currently be done using orgmode's built-in linking capabilities, but this can be tedious, particularly in an org-roam setup where filenames are not an important part of the workflow (and therefore essentially random).

For example, if one knows the file name to be linked, one can simply add it manually using a `file:` link. Or one may open the desired file via deft, org-roam, etc., then use `org-store-link` to save the location, then switch back to the task and paste it.

Org-roam already provides `org-roam-insert` for working on files that are stored in `org-roam-directory`. I propose extending this command so links to org-roam notes may be inserted into any .org file, regardless of where it is saved.

### Proposed Implementation (if any)
I am not familiar enough with the internals of org-roam to propose an implementation.

### Please check the following:

- [X] No similar feature requests

**Comment by d12frosted** [comment]
It is already possible to create links to `org-roam` files outside `org-roam-directory` using `org-roam-insert`.

**Comment by jethrokuan** [comment]
`org-roam-insert` now inserts links to any file outside of the `org-roam-directory`, using the link-type specified by `org-roam-link-file-path-type`, which defaults to relative links.
