### ISSUE TITLE
Building org-agenda runs in endless loop when using org-roam with org-id

### ISSUE THREAD

**Issue by lordnik22** [org-roam/org-roam#1045]
### Description
When an Entry in org-agenda contains a org-id-link, then org-roam-id-find will run in an endless loop.
#### Steps to Reproduce

1. Load Spacemacs
2. Create a File test.org
```
* Test
  :PROPERTIES:
  :ID:       890e6ff3-bbae-42e3-a520-85f87fd49a9e
  :END:
** TODO [[id:b8994f15-7585-4af5-b5e7-d3dbc5a14635][Other]]
   DEADLINE: <2020-08-16 So>
```
3. Create a File other.org
```
* Other
  :PROPERTIES:
  :ID:       b8994f15-7585-4af5-b5e7-d3dbc5a14635
  :END:
```
4. Create agenda for current buffer `M-x org-agenda < a`
5. ERROR
Sacktrace on quit:
`Debugger entered--Lisp error: (quit)
  file-name-case-insensitive-p("/home/lordnik/")
  file-truename("/home/lordnik/system" (97) (nil))
  file-truename("/home/lordnik/system/files" (97) (nil))
  file-truename("~/system/files/")
  org-roam-db--get-connection()
  org-roam-db()
  org-roam-db-query([:select [file] :from headlines :where (= id $s1)] "b8994f15-7585-4af5-b5e7-d3dbc5a14635")
  org-roam-id-find("b8994f15-7585-4af5-b5e7-d3dbc5a14635")
  org-roam--id-link-face("b8994f15-7585-4af5-b5e7-d3dbc5a14635")
  funcall(org-roam--id-link-face "b8994f15-7585-4af5-b5e7-d3dbc5a14635")
  (let ((face val)) (funcall face path))`
#### Expected Results
Org-agenda displays content (without quitting `C-g`):
```
Monday     17 August 2020 W34
  test:        1 d. ago:  TODO [[id:b8994f15-7585-4af5-b5e7-d3dbc5a14635][Other]]
Tuesday    18 August 2020
Wednesday  19 August 2020
Thursday   20 August 2020
Friday     21 August 2020
Saturday   22 August 2020
Sunday     23 August 2020
```
### Environment
- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)
 of 2020-03-26, modified by Debian
- Framework: Spacemacs
- Org: Org mode version 9.3.7 (9.3.7-16-g521d7f-elpaplus @ /home/lordnik/.emacs.d/elpa/org-plus-contrib-20200803/)
- Org-roam: 1.2.1

**Comment by Silipwn** [comment]
Faced the same problem, running profiler, indicates a `org-roam--id-link-face` taking up lot of memory. 
```
- command-execute                                                                              2194  64%
 - call-interactively                                                                          2194  64%
  - apply                                                                                      2194  64%
   - explain-pause--wrap-call-interactively                                                    2194  64%
    - apply                                                                                    2194  64%
     - #<subr call-interactively>                                                              2194  64%
      - funcall-interactively                                                                  2194  64%
       - apply                                                                                 2194  64%
        - #<subr funcall-interactively>                                                        2194  64%
         - org-agenda                                                                          1953  57%
          - org-let                                                                            1939  57%
           - eval                                                                              1939  57%
            - let                                                                              1939  57%
             - org-agenda-list                                                                 1939  57%
              - org-agenda-finalize                                                            1850  54%
               - org-activate-links                                                            1841  54%
                - org-roam--id-link-face                                                       1331  39%
                 - org-roam-id-find                                                            1331  39%
                  - org-roam-db-query                                                          1149  33%
                   - org-roam-db                                                                770  22%
                    - org-roam-db--get-connection                                               756  22%
                     - file-truename                                                            744  21%
                      - file-truename                                                           503  14%
                       - file-truename                                                          386  11%
                        + file-truename                                                         273   8%
                    - emacsql-live-p                                                             13   0%
```

**Comment by Silipwn** [comment]
Turns out this issue is similar to #811 (There were couple of duplicate IDs that were creating the issue)
https://github.com/org-roam/org-roam/issues/811#issuecomment-643577761 was quite useful in solving the issue.

**Comment by lordnik22** [comment]
I have executed the linked code and I see some files that appear multiple times but with different IDs. 
For example:
``` 
/home/lordnik/files/test.org
* Test
  :PROPERTIES:
  :ID:       a
  :END:
** Questions
  :PROPERTIES:
  :ID:       b
  :END:
```
The code would display something like: `#s(hash-table ... ("a" "~/files/test.org" "b" "~/files/test.org"))`

I have read some stuff about org-roam, which say that it works in the background file-based.
Can org-roam handle different IDs which point to the same file but different locations?
