### ISSUE TITLE
Bringing Back Persistent Link Auto-Completion

### ISSUE THREAD

**Issue by mbosley** [org-roam/org-roam#1051]
### Brief Abstract

Before moving to the `[[` org-roam link implementation,  company-org-roam would automatically suggest existing org-roam links for completion. I found this to be very helpful for organically linking up dense networks of ideas, but this feature no longer exists in the current company-capf implementation. Is this something that can be brought back as an option?

**Comment by spacekitteh** [comment]
@jethrokuan how does #1062 fix this? It's nothing like the old behaviour at all.
