### ISSUE TITLE
Latex preview feature default in *org-roam* buffer

### ISSUE THREAD

**Issue by hokten** [org-roam/org-roam#1054]
Soryy for my English. Is there a way org-roam buffer always preview latex formules? Thanks for great package

**Comment by jethrokuan** [comment]
```
(add-to-list 'org-roam-buffer-prepare-hook (lambda () (org--latex-preview-region (point-min) (point-max))) t)
```

should do the trick.

**Comment by darcamo** [comment]
You might be interested in [org-fragtog](https://github.com/io12/org-fragtog). It works really well.
