### ISSUE TITLE
If text is in italics (between two "/") the first link inserted with org-roam-insert does not work and it also does not show up in the backlinks

### ISSUE THREAD

**Issue by rtrppl** [org-roam/org-roam#1058]
### Description

This is a weird one. As stated in the title, if text is in italics the first link that is inserted by invoking `org-roam-insert` will not work/open and this instance is also not showing up in the backlinks. Second time `org-roam-insert` is used and every time thereafter, everything works as expected.  

#### Steps to Reproduce

1. Set text in italics.
2. Invoke `org-roam-insert` on text in italics (set between two /) to add link a). (pic 1)
3. Try to open link a): it won't work.
4. Open link a) directly (for example through `org-roam-find-file`). Link a) won't show up in the backlinks. (pic 2)

![pic 1](https://user-images.githubusercontent.com/63909884/90979264-52f4a600-e554-11ea-95c7-7a03d14f78b2.png)

![pic 2](https://user-images.githubusercontent.com/63909884/90979273-5b4ce100-e554-11ea-8245-0d8b6f75a34c.png)

**Comment by jethrokuan** [comment]
I can't reproduce this either:

![image](https://user-images.githubusercontent.com/1667473/91274800-d19a4f00-e7b1-11ea-8fc3-e684cf387110.png)

**Comment by rtrppl** [comment]
Weird. I can reproduce it every time, must be something within my setup. One idea regarding the links: `org-roam-insert` inserts links such as "file:../../20200524195655-org_roam.org", which do not work (for me) when in italics. I use org-id and when I add links with `org-store-link` they strangely do work in italics.
