### ISSUE TITLE
sql syntax error when org-roam--get-backlinks is called with nil

### ISSUE THREAD

**Issue by goktug97** [org-roam/org-roam#1059]
Issue about org-roam-server.

`org-roam--get-backlinks` function, that is changed in  4f3668a1e3ccd6a91b61580be3c9a28652074f6e breaks `org-roam-server`. The problem is, it is committed in August 7th and I don't know why no one has opened an issue about it in `org-roam-server` yet.

I closed every function that calls `org-roam--get-backlins` in `org-roam-server` but for some reason `org-roam--get-backlinks` is executed on `org-roam` side everytime a request to the server is made. 
https://github.com/org-roam/org-roam-server/blob/832ba1ab6b3eea89da3355f7676626266a172adc/org-roam-server.el#L215
The function is called with nil when executed by `org-roam`. The old version returns nil when called with nil but the new function gives 
`error: (emacsql-error near line 419: near "ORDER": syntax error)` error. It can be fixed by adding `(when targets` to the `org-roam--get-backlinks` function but if there is something I can do in `org-roam-server`, I prefer that.
```elisp
(defun org-roam--get-backlinks (targets)
  "Return the backlinks for TARGETS.
TARGETS is a list of strings corresponding to the TO value in the
Org-roam cache. It may be a file, for Org-roam file links, or a
citation key, for Org-ref cite links."
  (when targets
    (unless (listp targets)
      (setq targets (list targets)))
    (let ((conditions (--> targets
                           (mapcar (lambda (i) (list '= 'to i)) it)
                           (org-roam--list-interleave it :or))))
      (org-roam-db-query `[:select [from to properties] :from links
                                   :where ,@conditions
                                   :order-by (asc from)]))))
```
 
```
- emacs: gnu emacs 26.3 (build 1, x86_64-pc-linux-gnu, gtk+ version 3.24.10)
 of 2019-08-29
- framework: n/a
- org: org mode version 9.3.7 (9.3.7-21-g47f26b-elpa @ /home/goktug/.emacs.d/elpa/org-20200817/)
- org-roam: 1.2.1
```

**Comment by jethrokuan** [comment]
Internally, `org-roam` only calls `org-roam--get-backlinks` within `org-roam-buffer.el`, when it is trying to render the org-roam side buffer.

I suppose that `org-roam-server` is calling it with `nil` as an argument, but I can't tell where. A stacktrace would be helpful

**Comment by goktug97** [comment]
I made debug-on-entry on org-roam--get-backlinks and found that issue is caused by an export preprocessor that I completely forgotten which calls backlinks function. That's why nobody has opened an issue yet.
