### ISSUE TITLE
`directory-abbrev-alist' will break backlinks

### ISSUE THREAD

**Issue by pRot0ta1p** [org-roam/org-roam#1063]
This is a follow up of #869 , while setting `directory-abbrev-alist` solve the issue in there, it cause broken backlinks on my setup.
I set the roam directory to a symlink and running Emacs 27.1 on msys2 windows10, 
setting `directory-abbrev-alist` will result in a blank backlink buffer, while the backlink in the graph works.

Also previously I encounter a bug that org-noter wont save annotaion if I dont set `directory-abbrev-alist` https://github.com/org-roam/org-roam-bibtex/issues/91, so I tried set directory-abbrev-alist to nil temporarily, but this wont help without rebuild database cache.  So I want to test if org-roam can automatically set directory-abbrev-alist to nil before update the database, how can I do this?

**Comment by jethrokuan** [comment]
this is possibly fixed with #1099 , could you check?

**Comment by pRot0ta1p** [comment]
yes, problem solved, thanks!
