### ISSUE TITLE
Problem retrieving contextual information?

### ISSUE THREAD

**Issue by bepolymathe** [org-roam/org-roam#1077]
Over the summer I improved my organization with org-roam. In addition to using the wonderful org-roam-bibtex for reading notes, I have also integrated all my journal notes with org-journal. My idea is eventually to approach as much as possible a kind of memex with all my data which includes elements of reflections (readings or analytical notes) but also notes of meetings or small everyday things. 

When I see something I'm interested in and want to keep, I tend to use org-protocol with the following capture template that inserts the link in the org-journal file of the day but with a format close to org-roam (and in the same folder). 

![image](https://user-images.githubusercontent.com/29939805/91645353-b004c600-ea44-11ea-901e-de7485f311ce.png)

That's what it looks like. 

![image](https://user-images.githubusercontent.com/29939805/91645372-c874e080-ea44-11ea-81e5-66c22224abd2.png)

My only problem is that if I go to see my "raspberry" tag (e.g.)... I have a backlink that is not really readable because it displays the title of the document and not the headline. Do you think there's a way to improve this ?

![image](https://user-images.githubusercontent.com/29939805/91645400-112c9980-ea45-11ea-8fd8-b9166dc329ec.png)

Thank you for your work and this great tool.

**Comment by zaeph** [comment]
Thanks for filing the issue.  I'll investigate next week.

**Comment by Wetlize** [comment]
Something is seriously broken with the preview content in the `org-roam` buffer. I'm experiencing the same issue + #1082, so they might be connected. Both of them go away if I pin the `org-roam` to #1068. Hope this data somehow helps.

**Comment by Wetlize** [comment]
Looks like #1084 fixes the preview content, but the outline hierarchy in the `org-roam` buffer will display all backlinks as `* Top` level entries, even when they being located under other headings within a file.

**Comment by bepolymathe** [comment]
Yes that solves the problem. "Top" means that there is no headline above what seems to me to be good behavior. Thank you for that.

**Comment by jethrokuan** [comment]
I believe this has been fixed.
