### ISSUE TITLE
Sqliterc '.timer on' causes org-roam-db-build-cache to fail with wrong-type-argument

### ISSUE THREAD

**Issue by ChrisDavison** [org-roam/org-roam#1080]
### Description

`org-roam-db-build-cache` fails with `wrong-type-argument arrayp Run`, as `Run` is passed as `file` to `org-roam-db--clear-file`. This only occurs in the final call to `org-roam-db--clear-file` inside `org-roam-db-build-cache`, when hash-keys is used ([Lines 553 to 556 of `org-roam-db`](https://github.com/org-roam/org-roam/blob/master/org-roam-db.el#L553-L556)).

This is because `Run time...` is added as a row from the `select` query in `org-roam-db--get-current-files`

```
...lots of my org-roam files...
 ("/home/davison/Dropbox/org/PATH_TO_ONE_OF_MY_FILES"
"44decba8ca8225225d820d4713cdf4a17ebf7b25"
  (:atime
    (24398 25517 704000 553000)
    :mtime
    (24395 64129 0 0)))
 ("/home/davison/Dropbox/org/PATH_TO_ANOTHER_FILE"
"58a82605577916047f599ff640644527ab075fd9"
  (:atime
    (24398 25516 640000 529000)
    :mtime
    (24395 63980 0 0)))
 (Run Time: real 0.001 user 0.000295 sys 0.0))
```

#### Steps to Reproduce

1. Have `.timer on` in `.sqliterc`
2. Load Emacs
3. Run `org-roam-db-build-cache`

#### Backtrace

```
  substring(Run 0 1)
  file-truename(Run)
  org-roam-db--clear-file(Run)
  org-roam-db-build-cache(nil)
  funcall-interactively(org-roam-db-build-cache nil)
  call-interactively(org-roam-db-build-cache record nil)
  command-execute(org-roam-db-build-cache record)
  counsel-M-x-action("org-roam-db-build-cache")

...ivy and command-execute stuff...
```

#### Expected Results

database generation succeeds

#### Actual Results

database generation fails

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
 of 2020-09-01
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/davison/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.1

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/cb10b16fc0383f199bc634ff700b2c5ae698d4ef

**Comment by jethrokuan** [comment]
This is now fixed upstream with https://github.com/cireu/emacsql-sqlite3/commit/87f1122326c57edb5683cb6acbea82063d8b8f28.
