### ISSUE TITLE
Feature request: Automatic Publishing with a template repo and github actions

### ISSUE THREAD

**Issue by bbigras** [org-roam/org-roam#1090]
### Brief Abstract

One cool thing about Neuron is that you can use their template repo and have a github page really quickly using github action. 

See:
https://neuron.zettel.page/778816d3.html

### Please check the following:

- [ ] No similar feature requests

**Comment by bphenriques** [comment]
👋  I think it falls outside the scope of the `org-roam` project.


If you want solely have `org-mode` files in the repo and have their published, you can look at my repo knowledge-base. 
Mind you that it includes a minimal emacs setup with `ox-hugo` and `org-roam`, hopefully it helps you. As expected, it largely depends on how you want to display your files through the web. If you do not want to use `ox-hugo` then you have to look to other custom solutions.

**Comment by bbigras** [comment]
Fair enough. Thanks.
