### ISSUE TITLE
Allow to always use id links instead of file links

### ISSUE THREAD

**Issue by d12frosted** [org-roam/org-roam#1091]
### Brief Abstract

Allow to configure default type of links to `org-roam` files.

### Long Description

Whenever you insert a link to `org-roam` file it has format `[[file:%s][%s]]`, but it would be nice to have an ability to use `[[id:%s][%s]]` by default.

### Proposed Implementation (if any)

Having a configuration variable with two possible values: `file` and `id`. No details yet 😸 

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
IDs point to specific headlines within a file, so the two aren't exactly interchangeable.

Are you looking for an analogous function like `org-roam-insert-id`? This would show all cached headlines in Org-roam that have IDs.

I realise that it is currently difficult to link to any cached headline. `[[*|]]` completions only show headlines in the current buffer, and `[[Foo*|]]` completions only show headlines in the file with title `Foo`. Perhaps I can add `[[#|]]` completions for linking to any headline.

**Comment by d12frosted** [comment]
> IDs point to specific headlines within a file, so the two aren't exactly interchangeable.

I also use IDs for files:

```
:PROPERTIES:
:ID:                     cf38556b-cddf-49af-8814-3b7e62f06d8c
:CUSTOM_ID:              9a4281c8-15f0-44b2-8961-56946beb83e1
:END:
#+OPTIONS: auto-id:t
#+TIME-STAMP: <2020-09-11 08:50:52 d12frosted>
#+TITLE: Index
#+ROAM_ALIAS: "some alias"
```

So when I link to this file I would love to use ids instead of relative file names. E.g (in some other file):

```
[[id:cf38556b-cddf-49af-8814-3b7e62f06d8c][Index]]
```

Org mode supports this. I understand that not everyone enforces ids on the file level, but I think id links are much more useful for those who generates ids even on file level 😸

**Comment by Whil-** [comment]
File properties are new in 9.4 so not yet available in any released version. With that said, I totally agree with your proposal/request d12frosted. Having the option to use ID links for both file references and heading references would be great!

**Comment by d12frosted** [comment]
@Whil- 🤔 I am on 9.3.8 and still have this feature.

**Comment by TimQuelch** [comment]
Out of curiosity, why do you want to use IDs for file links? What advantages do they give?

**Comment by d12frosted** [comment]
There are two situations where I prefer id links over relative path:

1. I use subfolders and sometimes move around my notes, meaning that all links to the moved note should be updated (usually works automatically, but sometimes I have to use `org-roam-doctor`). With `id` links there is no need for this at all and I can safely move around without double checking that everything is properly linked.
2. Sometimes I link `org-roam` files outside of `org-roam` directory and relative path depends on what computer I am using right now. So I have to manually convert them into `id` links. Which is not that hard, but would be lovely for `org-roam` to support it out of box.

And on a non-practical side, I just prefer using `id` links for everything in `org-mode`. I don't want links to duplicate information of how I organise notes on the disk. Once I create a file - I automatically generate `id` which doesn't change anymore, while location may change :) 

Not sure if I explained my point clearly. Let me know if you have questions 😸

**Comment by Whil-** [comment]
> @d12frosted: @Whil- 🤔 I am on 9.3.8 and still have this feature.

Hmm, interesting. Good if it works already on 9.3.8. I do believe the support for property-blocks before first headline in a file is intended for 9.4 (well... that was the intention when I added it to org-mode at least). And it's mentioned under the section for 9.4 in ORG-NEWS. But somehow maybe it has snuck out before that during the 9.3.8 release? Oh well, I won't complain! 9.4 feels overdue by quite some time already, anyhow ;)

> @TimQuelch: Out of curiosity, why do you want to use IDs for file links? What advantages do they give?

To add to what d12frosted mentioned, ID's are more robust. Change names of files. Move them around. It doesn't matter. The ID stays the same, and the link will continue to work. The benefit of ID-links is similar for file-links as it is for links to headings.

**Comment by TimQuelch** [comment]
Interesting. Thanks for answers

**Comment by spacekitteh** [comment]
Particularly relevant now that 9.4 has been released.

**Comment by leezu** [comment]
As an alternative to file properties, users may also adopt a convention of starting every file with a headline:

```
(org-roam-capture-templates '(("d" "default" plain (function org-roam--capture-get-point)
                                   "OPENED: %U\n\n%?\n%i\n"
                                   :file-name "%<%Y%m%d%H%M%S>"
                                   :head "* ${title}\n"
                                   :unnarrowed t)))
```

In that case I'd "expect"  `org-roam-insert` to insert the `id:` link to the first headline in the file. `org-roam` already appears to correctly index these headlines (at least they are shown in the autocompletion offered by `org-roam-insert`).

**Comment by jethrokuan** [comment]
@d12frosted this feature should be present in master now, if you'd like to test it out.

`org-roam-insert` and the `roam:` links resolve to ID links if the file has a drawer before the first headline, and that file has been processed by Org-roam.

**Comment by d12frosted** [comment]
Oh my. It's already implemented 🎉 I will test it today and will let you know.

**Comment by d12frosted** [comment]
Actually, couldn't wait to test it, so went ahead and downloaded the latest version of `org-roam`. Wonderful result. Would be also nice to have an ability to convert/update existing links :)

**Comment by jethrokuan** [comment]
here's a snippet that does what you want. It:

1. First creates IDs for every org-roam file if it does not yet exist
2. Update the database
3. Visit every org-roam file, and replace file links with ID links where possible
4. Update the database

Not sure I want to include these into the code-base...

```
(defun my/replace-file-with-id-link ()
  "Replaces file links with ID links where possible in current buffer."
  (interactive)
  (let (path desc)
    (org-with-point-at 1
      (while (re-search-forward org-link-bracket-re nil t)
        (setq desc (match-string 2))
        (when-let ((link (save-match-data (org-element-lineage (org-element-context) '(link) t))))
          (when (string-equal "file" (org-element-property :type link))
            (setq path (expand-file-name (org-element-property :path link)))
            (replace-match "")
            (insert (org-roam-format-link path desc))))))))

(dolist (file (org-roam--list-all-files))
  (with-current-buffer (or (find-buffer-visiting file)
                           (find-file-noselect file))
    (org-with-point-at 1
      (org-id-get-create))
    (save-buffer)))

(org-roam-db-build-cache)

(dolist (file (org-roam--list-all-files))
  (with-current-buffer (or (find-buffer-visiting file)
                           (find-file-noselect file))
    (my/replace-file-with-id-link)
    (save-buffer)))

(org-roam-db-build-cache)
```

**Comment by d12frosted** [comment]
@jethrokuan perfect! thank you very much!

**Comment by Whil-** [comment]
@d12frosted; Did you manage to get this to work with the backlinks-buffer as well?

I.e. in the following setup:
file1:
```
:properties:
:id: f1
:end:
```
file2:
```
:properties:
:id: f2
:end:
[[id:f1][file 1 link]]
```
Will you see the backlink from file2 when visiting file1?

**Comment by d12frosted** [comment]
I must say that right now something is terribly wrong with my db. I tried cleaning it multiple time and rebuilding, but most of org-roam functionality is dead :( Will dig :)

**Comment by tea4or2wo** [comment]
I think there should be a variable controlling this behavior if path to file is used for linking but some files have attachments assigned by an ID.

I personnaly use `<%Y%m%d%H%M%S>` filenames as unique identifiers for files and I don't want link to file `20201122231232.org` using ID instead if file `20201122231232.org` has an attachment and, therefore, an ID.

Let me know if I should open a new issue for this.

**Comment by deshmukhs** [comment]
> here's a snippet that does what you want. It:
> 
>     1. First creates IDs for every org-roam file if it does not yet exist
> 
>     2. Update the database
> 
>     3. Visit every org-roam file, and replace file links with ID links where possible
> 
>     4. Update the database
> 
> 
> Not sure I want to include these into the code-base...
> 
> ```
> (defun my/replace-file-with-id-link ()
>   "Replaces file links with ID links where possible in current buffer."
>   (interactive)
>   (let (path desc)
>     (org-with-point-at 1
>       (while (re-search-forward org-link-bracket-re nil t)
>         (setq desc (match-string 2))
>         (when-let ((link (save-match-data (org-element-lineage (org-element-context) '(link) t))))
>           (when (string-equal "file" (org-element-property :type link))
>             (setq path (expand-file-name (org-element-property :path link)))
>             (replace-match "")
>             (insert (org-roam-format-link path desc))))))))
> 
> (dolist (file (org-roam--list-all-files))
>   (with-current-buffer (or (find-buffer-visiting file)
>                            (find-file-noselect file))
>     (org-with-point-at 1
>       (org-id-get-create))
>     (save-buffer)))
> 
> (org-roam-db-build-cache)
> 
> (dolist (file (org-roam--list-all-files))
>   (with-current-buffer (or (find-buffer-visiting file)
>                            (find-file-noselect file))
>     (my/replace-file-with-id-link)
>     (save-buffer)))
> 
> (org-roam-db-build-cache)
> ```

@jethrokuan I am a newbie here. So the question may be basic.

I have about 400 files in org-roam. All links are file links. I wanted to convert these to id links so I can move files around --- in subdirectories using dired.

So, I copied the snippet into a test.el file in org-roam directory. Then:

eval-region for the defun
updated the db
eval-region for the first dolist
updated the db
eval-region for the second dolist
updated the db

This does not add file links to all files and certainly not convert all links to ID links.

Am I missing some point? Is this not how we are supposed to do this? What is the correct method?

**Comment by spacekitteh** [comment]
I just ran that code in the scratch buffer, and it worked perfectly for me.

**Comment by deshmukhs** [comment]
The first dolist creates an error for me. Here is the output produced by debug-on-error:

Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  puthash("8db83a93-b8b1-4563-9146-17c176cf23f5" "~/Documents/...20210129..." nil)
  (progn (if org-id-locations nil (org-id-locations-load)) (puthash id afile org-id-locations) (if (member afile org-id-files) nil (add-to-list 'org-id-files afile)))
  (if (and org-id-track-globally id) (progn (if org-id-locations nil (org-id-locations-load)) (puthash id afile org-id-locations) (if (member afile org-id-files) nil (add-to-list 'org-id-files afile))))
  (let ((afile (abbreviate-file-name file))) (if (and org-id-track-globally id) (progn (if org-id-locations nil (org-id-locations-load)) (puthash id afile org-id-locations) (if (member afile org-id-files) nil (add-to-list 'org-id-files afile)))))
  org-id-add-location("8db83a93-b8b1-4563-9146-17c176cf23f5" "/home/.../202101290...")
  (cond ((and id (stringp id) (string-match "\\S-" id)) id) (create (setq id (org-id-new prefix)) (org-entry-put pom "ID" id) (org-id-add-location id (or org-id-overriding-file-name (buffer-file-name (buffer-base-buffer)))) id))
  (let ((id (org-entry-get nil "ID"))) (cond ((and id (stringp id) (string-match "\\S-" id)) id) (create (setq id (org-id-new prefix)) (org-entry-put pom "ID" id) (org-id-add-location id (or org-id-overriding-file-name (buffer-file-name (buffer-base-buffer)))) id)))
  (save-restriction (widen) (goto-char (or --mpom (point))) (let ((id (org-entry-get nil "ID"))) (cond ((and id (stringp id) (string-match "\\S-" id)) id) (create (setq id (org-id-new prefix)) (org-entry-put pom "ID" id) (org-id-add-location id (or org-id-overriding-file-name (buffer-file-name (buffer-base-buffer)))) id))))
  (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (let ((id (org-entry-get nil "ID"))) (cond ((and id (stringp id) (string-match "\\S-" id)) id) (create (setq id (org-id-new prefix)) (org-entry-put pom "ID" id) (org-id-add-location id (or org-id-overriding-file-name (buffer-file-name ...))) id)))))
  (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (let ((id (org-entry-get nil "ID"))) (cond ((and id (stringp id) (string-match "\\S-" id)) id) (create (setq id (org-id-new prefix)) (org-entry-put pom "ID" id) (org-id-add-location id (or org-id-overriding-file-name ...)) id))))))
  (let ((--mpom pom)) (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (let ((id (org-entry-get nil "ID"))) (cond ((and id ... ...) id) (create (setq id ...) (org-entry-put pom "ID" id) (org-id-add-location id ...) id)))))))
  org-id-get(1 create)
  org-id-get-create()
  (save-restriction (widen) (goto-char (or --mpom (point))) (org-id-get-create))
  (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (org-id-get-create)))
  (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (org-id-get-create))))
  (let ((--mpom 1)) (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (org-id-get-create)))))
  (save-current-buffer (set-buffer (or (find-buffer-visiting file) (find-file-noselect file))) (let ((--mpom 1)) (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (org-id-get-create))))) (save-buffer))
  (while --dolist-tail-- (setq file (car --dolist-tail--)) (save-current-buffer (set-buffer (or (find-buffer-visiting file) (find-file-noselect file))) (let ((--mpom 1)) (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom ...)) (org-id-get-create))))) (save-buffer)) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- (org-roam--list-all-files)) file) (while --dolist-tail-- (setq file (car --dolist-tail--)) (save-current-buffer (set-buffer (or (find-buffer-visiting file) (find-file-noselect file))) (let ((--mpom 1)) (save-excursion (if (markerp --mpom) (progn (set-buffer ...))) (save-excursion (save-restriction (widen) (goto-char ...) (org-id-get-create))))) (save-buffer)) (setq --dolist-tail-- (cdr --dolist-tail--))))
  #<subr eval-region>(608 831 nil nil)
  apply(#<subr eval-region> (608 831))
  eval-region(608 831)  ; Reading at buffer position 831
  funcall-interactively(eval-region 608 831)
  call-interactively(eval-region record nil)
  command-execute(eval-region record)
  counsel-M-x-action("eval-region")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "eval-region" "org-roam-db-build-cache" "org-save-all-org-buffers" "org-roam-doctor" "list-packages" "org-roam-alias-add" "org-table-toggle-column-width" "org-habit-toggle-habits" "xx-marathi-characters" "org-roam-unlinked-references" "org-roam-mode" "ediff" "org-insert-link" "org-agenda-log-mode" "treemacs" "describe-char" "delete-blank-lines" "my/replace-file-with-id-link" "org-num-mode" "flyspell-mode" "yas/new-snippet" "org-roam-backlinks-mode" "org-sort" "org-id-store-link" "global-hl-line-mode" "flush-lines" "org-roam-graph" "org-agenda-list" "org-roam-diagnostics" "org-roam-random-note" "org-table-cut-region" "org-roam-jump-to-index" "yas-visit-snippet-file" "org-roam-buffer-activate" "shell" "ispell" "butterfly" "magit-diff" "doom/reload" "doom/upgrade" "hl-line-mode" "spell-fu-mode" "copy-directory" "text-scale-set" "org-table-align" "+org/remove-link" "+treemacs/toggle" "org-outdent-item" "org-roam-tag-add" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

**Comment by spacekitteh** [comment]
Have you set-up org-id? Have you run org-id-update-id-locations?

**Comment by deshmukhs** [comment]
@spacekitteh Thanks!! I guess I must have org-id set up (how does one check? I am using Doom Emacs and I am a newbie). But I ran org-id-update-id-locations before running that script and all is well. All my files have IDs now and all links are ID links.

While we are here, how do I ensure that all newly created roam files have an ID? This will kind of ensure that everything remains ID based and there are no file links.

**Comment by spacekitteh** [comment]
I have a capture hook which generates an ID when starting a new capture

**Comment by deshmukhs** [comment]
Do not know how to use capture hooks. But had some experience with capture templates. So, here is how I am doing it now.

```
(setq org-roam-capture-templates
      '(("d" "default" plain (function org-roam--capture-get-point)
         "%?"
         :file-name "%<%Y%m%d%H%M%S>-${slug}"
         :head ":PROPERTIES:\n:ID:  %(org-id-uuid)\n:TITLE: ${title}\n:END:\n"
         :unnarrowed t)))
```
