### ISSUE TITLE
open org roam file when source links are captured

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam#1095]
### Brief Abstract
When a specific or set of specific websites are captured through org-roam, open a corresponding org roam buffer.
### Long Description
This feature currently exists somewhat because org roam capture ref creates the same name for links when it creates corresponding org roam file. It also looks up if such file exists and opens it if it does.  but sometimes it fails. For example, if you capture this file while logged in, the name of the  file it creates is different than what it creates when signed out. Furthermore preserving data in the name of files is brittle because the user may change the name of the file without the intention of losing this feature. This is further exacerbated by the fact that names automatically generated by `org roam protocol open ref` are not palatable.
 A recent update to org roam added automatic renaming of files when the file title changes. This doesn't seem to work on files captured through `org roam protocol open ref`. It would be a sane system requirement to make features consistent across org roam.

### Proposed Implementation (if any)
Involves searching through files to check if such links exist. I will base it on  `- source ::` because that is what I have been using to keep source links but can make this another search term like `#+roam_tags:`. When capturing through org roam protocol open file, Search for this term within all org roam files and check if they contain the link, if so open it. If multiple files are found, pick the first one or open all. We can also display them and as the user to select. 
For the sake of preformace, add another column to the database that holds a list of source links and search the database instead, if there is an entry that holds the captured link. 
This can be abstracted to include ids or notmuch email entries as source links.
I will look if I can implement this feature this weekend.
### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
Org-roam's capture ref protocol uses the ref key to reopen a note. When you use the bookmarklet, it uses the URL of the current page as the key. Org-roam looks up if there are any files with the URL as its ref. If there is, it will reopen the note, if there isn't it will create a new one.

So I think either your setup is incorrect, or your example is slightly misleading. I don't think GitHub uses different URLs when logged in or not, so the capture protocol should end up opening the same note.

> A recent update to org roam added automatic renaming of files when the file title changes. This doesn't seem to work on files captured through org roam protocol open ref. It would be a sane system requirement to make features consistent across org roam.

This is not true. The file will be renamed if as long as it is part of the Org-roam ecosystem. I've just tested it to be working.

**Comment by natask** [comment]
@jethrokuan 
the url doesn't change but the name of the file created changes. 
for example, org-roam-capture-ref creates *`open_org_roam_file_when_source_links_are_captured_issue_1095_org_roam_org_roam.org`* when logged into github on this webpage. it creates *`open_org_roam_file_when_source_links_are_captured_issue_1095_org_roam_org_roam_github.org`* otherwise.

I looked into it and it happens because *`encodeURIComponent(document.title);`* adds on `github` when the page isn't logged in on Firefox.  I haven't checked chromium based browsers.

this leads me to believe that org-roam-capture-open-ref currently uses &title.

>This is not true. The file will be renamed if as long as it is part of the Org-roam ecosystem. I've just tested it to be working.

I agree. It works for me now as well.

**Comment by jethrokuan** [comment]
The lookup is still based on the ref key, not the title, so I still don't see an issue here. The title is not a necessary component of the capture protocol. If you don't want the title in the filename at all, you can change the ref capture template.

**Comment by natask** [comment]
your comment hinted that If I tried placing the url of the webpage under `#+roam_key:`, org-roam-capture-ref will open the file.
I tried it out and it worked. Thanks. I wasn't using `#+roam_key:` beforehand when capturing web pages.

I notice that it doesn't work with multiple urls like `#+roam_alias:` and `#+roam_tags:` so this feature request reduces to supporting multiple urls or keys for a org-roam file.

**Comment by natask** [comment]
My main use case for linking multiple urls to a file is I have a habit of reading information from multiple sites and then curating a summary into a single file. I then would keep the urls I curated from inside that file as links. When I then stumble onto such a site in the future, I would like to quickly know if I had curated from it. In the past I would first try to initiate `org-roam-capture-open-ref` on the url. because I didn't depend on `#+roam_key:` but the title of the org roam file, this wouldn't always work as discussed above. If I don't get a hit, I would then grep my org-roam directory looking for the link in a designated place in the file. this would be `- source ::`. If I find a matching file, I will open it, read a bit and maybe add more. if not, I create a new file linking that url. Although it doesn't happen often, If what I am going to note is different in content from the summary, I create a new file linking that url and write it there.

I am looking to modify the parser to look for more than one key in under `#+roam_key:`, in your view will this break org-roam?

later on, I will like to place a link in org-roam format under `#+roam_key:`. This will mean that key comparator in org-roam-capture-open-ref will need to be modified. I can pass the url in org-roam format in &href instead as well. It will be interesting to modify org-roam-capture-open-ref  such that links with different titles also link to different org-roam files.

Another thought I had was to have overlapping urls to a file. I checked and duplicate keys aren't allowed. removing this constraint will be cumbersome because it is currently an architectural guaranty.

The more I think of it, the more I think this isn't a good approach to support multiple urls to a file. A better approach would be to create a file for each url utilizing `#+roam_key:` and then link those files to into a master summary file, essentially mirroring how I am visiting and curating information. Then use back links to examine if I have created a summary file from a url. This may lead to a couple stub files but supports multiple urls to file and overlapped multiple urls to file mapping. 

Now I have to be diligent in creating files from urls because at times I curate from tens of urls that I have read but haven't cared to link and it is much easier to create files while reading (good too because now I wouldn't have excuse to forget to note down something) than it is when I am writing up a summary. I may implement software to extend automated creation of an org roam file from url to multiple urls.  I use surfing-keys to execute js but writing something in grease-monkey also should be trivial.

Thanks for our time. I am closing this issue.

**Comment by natask** [comment]
I am reopening this issue so that handling linking multiple urls to an org roam file is better supported in org-roam ecosystem.

urls can be kept as keys. The workflow of capturing to open a file and then checking it's backlinks verses using org-roam property  enables linking a url to multiple files out of the box. It is also possible to define a new org-roam property later on specifically for links because the constraint that a key must be unique doesn't apply to urls. This will serve as the difference between **- tags ::** and  **#+roam_tags**.

I currently am debating how to represent this in org-roam. With org 9.4 enabling headline like drawers for files, I am tempted to use a resources drawer. This has the added benefit that it can be headline specific and integrates well with org-brain.

There are a few functions that I will like to implement that facilitate a capture a url and check backlink workflow.
- org-roam-open-key-url
  opens the key property of a file. This should be a link (can check while opening).
- org-roam-open-resources-url 
  opens select urls of resource files linked inside a file.  if the resources are urls themselves, open those. The idea is to painlessly open multiple urls linked to a file that are hidden behind a file layer.
- org-roam-open-resources-url-at-point
  same as the above but directly opens the url of a file under point.
- org-roam-insert-multiple-resources
  @459 introduces the concept. The idea is to get the convenience of placing multiple urls for this workflow. Other tools can be used that transform urls into org-roam file links. The vision is to make this workflow as easy as selecting a couple of urls, running a function which transforms them to file links to files containing each of those urls as a key.

There is still the discussion between [tags vs links](https://org-roam.discourse.group/t/how-to-use-roam-tags-and-or-tags/190/21).

**Comment by natask** [comment]
quick implementation for **org-roam-open-key-url**. need to be extended to work directly of a file or id link.
```elisp
        (setq-local db (emacsql-sqlite3 (expand-file-name "org-roam.db" org-roam-directory)))
        (defun my/org-roam-find-file-url-key(input-file)
          (emacsql  db
                    [:select [ref]
                             :from refs
                             :where (like file $r1)] (format "%%%s%%" input-file)))

    (defun my/org-roam-open-file-url-key (input-file) 
    (let ((browser-link (car (car (my/org-roam-find-file-url-key input-file)))))
      (when (string-match-p (regexp-quote "http") browser-link)
              (browse-url-default-browser browser-link))))
```

**Comment by natask** [comment]
I realized that org-roam already parses http links and places them in the data base. We can totally use that and bring up a helm buffer to select from which can be bypassed with an extra flag if there is is no match.

I will also implement a sort of blacklist for files I don't want to be shown (I do website session management in emacs in an org roam buffer). I will move this up to org roam parsing so that the database isn't cluttered.

**Comment by natask** [comment]
I have this working well. It only works for urls at the moment but the query can be better formed to handle all other types of links.
