### ISSUE TITLE
org agenda and org roam incompatability: org agenda hangs

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam#1096]
### Description
running org agenda on an file that has a headline with a title that includes id links to a headline in another sometimes causes org agenda to hang. In the context that I have tested this, both the files are in my org roam directory. It also ends up consuming memory.
For now the solution is to disable org-roam before running org-agenda. Unfortunately, I haven't been able to reproduce consistently. I will do some more testing 

#### Example
file 1
``` org
#+title: file

* this is a headline
:PROPERTIES:
:ID:       01d2faff-a838-4c63-cd01-ce4081bd15e7
:END:
:LOGBOOK:

```

agenda file
```
#+title: agenda
* headline link [[id:01d2faff-a838-4c63-cd01-ce4081bd15e7][this is a headline]
```
running `org-agenda` and press 't' to list all todo tags. This hangs on some `file 1`'s.

#### Steps to Reproduce
- create two org roam files 
- set one of them as an org agenda file
- add a headline in each files
- create an id link in the title of the headline in the org agenda file that links to the headline in the other org roam file.
- run org-agenda. and list all todo tags (t).

#### Backtrace

This is the output of memory profiler. The bug is emanating from `org-roam--id-link-face`, `org-roam-id-find`, or `org-roam-db-query`.
``` org
      - org-todo-list                                   5,926,576,414  19%
       - org-agenda-finalize                            5,870,241,725  19%
        - org-activate-links                            5,852,330,797  19%
         - org-roam--id-link-face                       5,053,064,253  16%
          - org-roam-id-find                            5,053,064,253  16%
           - org-roam-db-query                          5,020,695,063  16%
            - apply                                     4,961,900,775  16%
             - emacsql                                  4,961,749,767  16%
              - apply                                   4,961,749,767  16%
               + #<compiled 0xaaa486f67e088ed>          4,961,670,567  16%
```
#### Expected Results
org agenda doesn't hang.

#### Actual Results
org agenda hangs.

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-20
- Framework: Spacemacs
- Org: Org mode version 9.3.7 (9.3.7-55-gba2405-elpaplus @ ~/spacemacs/elpa/develop/org-plus-contrib-20200907/)
- Org-roam: 1.2.1

**Comment by myshevchuk** [comment]
I can confirm it, although to reproduce the bug the headline must contain a todo keyword:

``` org
  #+title: agenda
* TODO headline link [[id:...][this is a headline]
```

**Comment by myshevchuk** [comment]
``` elisp
;;;; Entrypoint: (org-roam-db-query)
(defun org-roam-db-query (sql &rest args)
  "Run SQL query on Org-roam database with ARGS.
SQL can be either the emacsql vector representation, or a string."
  (if  (stringp sql)
      (progn (message "true")
             (emacsql (org-roam-db) (apply #'format sql args)))
    (message "false")
    (apply #'emacsql (org-roam-db) sql args)))
```

> Press key for agenda command (unrestricted):
false [7712 times]

**Comment by myshevchuk** [comment]
Probably `sql` is nil.

**Comment by myshevchuk** [comment]
No, it's:

> Press key for agenda command (unrestricted):
[:select [file] :from headlines :where (= id $s1)] [5853 times]

**Comment by myshevchuk** [comment]
It seems the third clause in `org-roam--id-link-face` causes an infinite recursion:

``` elisp
(defun org-roam--id-link-face (id)
  "Conditional face for id links.
Applies `org-roam-link-current' if ID corresponds to the
currently opened Org-roam file in the backlink buffer, or
`org-roam-link-face' if ID corresponds to any other Org-roam
file."
  (let* ((in-note (-> (buffer-file-name (buffer-base-buffer))
                      (org-roam--org-roam-file-p)))
         (custom (or (and in-note org-roam-link-use-custom-faces)
                     (eq org-roam-link-use-custom-faces 'everywhere))))

    (cond ((and custom
                (not (org-roam-id-find id)))
           'org-roam-link-invalid)
          ((and (org-roam--in-buffer-p)
                (org-roam--backlink-to-current-p))
           'org-roam-link-current)
          ((and custom
                (org-roam-id-find id))
           (message "org-roam--id-link-face custom")
           'org-roam-link)
          (t
           'org-link))))

(defun org-roam-id-find (id &optional markerp strict)
  "Return the location of the entry with the id ID.
When MARKERP is non-nil, return a marker pointing to theheadline.
Otherwise, return a cons formatted as \(file . pos).
When STRICT is non-nil, only consider Org-roam’s database."
  (let ((file (or (caar (org-roam-db-query [:select [file]
                                            :from headlines
                                            :where (= id $s1)]
                                           id))
                  (unless strict
                    (org-id-find-id-file id)))))
    (when file
      (message "org-roam-id-find")
      (org-id-find-id-in-file id file markerp))))
```

> Press key for agenda command (unrestricted):
org-roam-id-find [2 times]
org-roam--id-link-face third clause
org-roam-id-find [2 times]
org-roam--id-link-face third clause
org-roam-id-find [2 times]
org-roam--id-link-face third clause
org-roam-id-find [2 times]
org-roam--id-link-face third clause
org-roam-id-find [2 times]
org-roam--id-link-face third clause
org-roam-id-find [2 times]
org-roam--id-link-face third clause
org-roam-id-find [2 times]
org-roam--id-link-face third clause
org-roam-id-find [2 times]
org-roam--id-link-face third clause
org-roam-id-find [2 times]
org-roam--id-link-face third clause

And so on until `C-g` is pressed.

**Comment by jethrokuan** [comment]
Okay I can reproduce this too, but I can't figure out how to fix it. I've tried removing `org-agenda` related things from `org-roam-id-find`:

```
(defun org-roam-id-find (id &optional markerp strict)
  "Return the location of the entry with the id ID.
When MARKERP is non-nil, return a marker pointing to theheadline.
Otherwise, return a cons formatted as \(file . pos).
When STRICT is non-nil, only consider Org-roam’s database."
  (let ((file (or (caar (org-roam-db-query [:select [file]
                                            :from headlines
                                            :where (= id $s1)]
                                           id))
                  (unless strict
                    (unless org-id-locations (org-id-locations-load))
                    (and org-id-locations
                         (hash-table-p org-id-locations)
                         (gethash id org-id-locations)))))
        pos buf)
    (cond
     ((not file) nil)
     ((not (file-exists-p file)) nil)
     (t (with-current-buffer (setq buf (find-file-noselect file))
          (save-excursion
            (setq pos (org-with-wide-buffer (org-find-property "ID" id)))
            (when pos
              (if markerp
                  (move-marker (make-marker) pos buf)
                (cons file pos)))))))))
```

but the hang still remains. `org-roam-id-find` returns near instantly for me. @zaeph any ideas, can you look into this?

If this is not fixable, we might want to consider removing the invalid face for IDs. It requires 1 SQL query per ID link to font-lock anyway, not sure if it's worth it.

**Comment by myshevchuk** [comment]
@jethrokuan, @zaeph, Org Roam has nothing to do with all this. This is actually an Org mode bug. 

In `org-activate-links`, line 5146 of `org.el`

``` elisp 
((and (pred functionp) face) (funcall face path))
```

should be

``` elisp
((and (pred functionp) face) (save-match-data (funcall face path)))
```

Since it is possible that the called function, such as `org-roam--id-link-face` (and ultimately `org-id-find-id-in-file`), may manipulate the match data, it is necessary to save it before calling the function.

**Comment by myshevchuk** [comment]
What happens is that after creating the Agenda buffer, `org-activate-links` parses the buffer for links in a loop. However, after returning from `org-roam--id-link-face`, the match data (markers) have been manipulated and `org-activate-links` parses the same link again and again.

**Comment by jethrokuan** [comment]
Thanks for the investigation @myshevchuk, I think we can fix this temporarily in Org-roam by wrapping the id link face function with save-match-data.
