### ISSUE TITLE
Internal links to named locations and radio targets fail

### ISSUE THREAD

**Issue by chrpinedo** [org-roam/org-roam#1098]
### Description
There are problems with [internal links](https://orgmode.org/manual/Internal-Links.html#Internal-Links) and [radio targets](https://orgmode.org/manual/Radio-Targets.html#Radio-Targets) of org-mode.

#### Steps to Reproduce
Problem with named locations (tables, figures, source code blocks...):
1. Open one org-roam file
2. Create a table with a name:
```org
#+name: tab:example
| 1st | row |
| 2nd | row |
```
3. Try to link to the table with `[[tab:example]]`
4. Try to open the previous link

Problem with `<<target>>` locations:
1. Open one org-roam file
2. Create a table with a name:
```org
* <<sec:introduction>> Introduction
```
3. Try to link to the table with `[[sec:introduction]]`
4. Try to open the previous link

Problem with radio targets:
1. Open one org-roam file
2. Create a table with a name:
```org
* <<<sec:introduction>>> Introduction
```
3. Try to link to the table with `As it is shown in sec:introduction ...`
4. Try to open the previous link

#### Expected Results

Previous links should reference locations of the current file.

#### Actual Results

- Named locations when linked and opened the link: `org-roam-capture` is launched.
- `<<target>>` locations when linked and opened the link: `org-roam-capture` is launched.
- radio targets (f.e. `<<<my-target>>>`): future references of `my-target` are not directly converted to a link.

### Environment

I am running org-roam with doom-emacs.

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/chrpinedo/.emacs.doom/.local/straight/build/org-mode/)
- Org-roam: 1.2.1

**Comment by chrpinedo** [comment]
This bug has been initially discovered and discussed in the Org Roam forums: https://org-roam.discourse.group/t/problem-with-internal-links

**Comment by jethrokuan** [comment]
With #1105 , this is no longer an issue.
