### ISSUE TITLE
Promote headline to new file

### ISSUE THREAD

**Issue by spacekitteh** [org-roam/org-roam#1104]
### Brief Abstract
There should be a function equivalent to `org-brain`'s `org-brain-headline-to-file`. 
### Long Description
When expanding a note, if it becomes non-atomic, I wish to be able to select a region or a headline, create a new file, and move the contents there. Any links to the existing headline should then point to the new file.

NOTE: It is crucial to transform the headline's `:ID:` property to a file-level property to preserve existing `id:` links, as well as the workings of other packages.

### Please check the following:

- [x ] No similar feature requests

**Comment by TimQuelch** [comment]
I like this idea. I've had some notes go off on tangents and this would be useful in splitting them off into their own independant units.

> NOTE: It is crucial to transform the headline's :ID: property to a file-level property to preserve existing id: links.

I don't think this is necessarily the case. Because links are stored in the db, we can easily query for links pointing to the headline to be extracted. These links can then be changed into regular file links.

**Comment by spacekitteh** [comment]
It is crucial because `org-roam` is not the only thing that uses `:ID:` properties.

**Comment by TimQuelch** [comment]
That is true, good point

**Comment by lytex** [comment]
I'm currently doing something similar on my [config.el file](https://github.com/lytex/doom.d/blob/ef518fb09882880320305cf1019d6e3803ed8653/config.el#L307-L321), but it does not replace all id: links by file: links

I think using org-roam-capture is the right way to do this inside of roam

**Comment by mccordnate** [comment]
It would be great if this could also handle non-org-roam headlines as well. It feels like it'd be a special org-roam-refile command. One that would allow you to move the headline from one file to another, or to a new file (with or without the headline as the title). This would have the added benefit of using the legible title / aliases when doing the refile.
