### ISSUE TITLE
org-roam-insert sometimes creates new notes even though note exists with title

### ISSUE THREAD

**Issue by maciekk** [org-roam/org-roam#111]
This happens sometimes:
- I'm editing a note, and want to reference / link another note I created not too long ago
- C-c n i
- I start typing title of recent note, expecting to see it in list
- it quickly become clear org-roam doesn't seem to know of said title/page
- to finish current note, I'm forced to create new note with same title as expected one

Last step naturally results in multiple notes with same title. Really looking forward to https://github.com/jethrokuan/org-roam/issues/31 which seem it will help clean this up.

But issue remains: why does org-roam not seem to know of some notes? I take it this is a case of some cache being stale, or not updated yet. What can I do to update the cache?

The pages that I expect to link to were created in a normal(?) way, nothing special. While I learn org-roam I typically have a landing page start-here.org, with a "Recent" section, and under this I typically create new notes by org-roam-insert here titles of new notes in bullet list, then follow the link to fill out the new note...

I wonder: is the issue that I have either not visited the target page, and/or not yet saved its buffer to file?

If so, what is the right workflow when entering a bunch of notes and wanting to tag them all with a "topic" note (e.g., entering bunch of article summaries on learning, and wanting to tag them all with R:Learning note link, which does not as yet exist...)

**Comment by jethrokuan** [comment]
> I wonder: is the issue that I have either not visited the target page, and/or not yet saved its buffer to file?

Likely. Are you on latest `develop` branch? https://github.com/jethrokuan/org-roam/pull/107 was just merged in a few hours ago.

**Comment by maciekk** [comment]
> Likely. Are you on latest `develop` branch? #107 was just merged in a few hours ago. I think I had something in my init.el that autosaved all files that weren't in focus.

Oh, no, I'm probably using a version a couple days old. I will try that out, thanks!

**Comment by maciekk** [comment]
Finally got around to trying it out. Yup, that fixes the issue for me too.
