### ISSUE TITLE
:ID: tag added to heading or nearest parent heading when a new road link is created

### ISSUE THREAD

**Issue by ln0a** [org-roam/org-roam#1111]
This is more of an aesthetic bug than anything else, but as the title suggests, if a new roam link is created with eith the `default` or `immediate` templates, a `:PROPERTIES:` tag with custom `:ID:` is applied to the nearest heading.

What is the purpose of this `:ID:`, as it seems with a well named note there is no need to check against the ID.
Could I be pointed to the point in the code where this action is applied? Maybe the creation of the ID couls be given as a user configuration?

**Comment by TimQuelch** [comment]
`org-capture` automatically stores a link when capturing. This triggers an ID creation. This is part of `org` rather than `org-roam`

```elisp
  (interactive "P")
  (when (and org-capture-use-agenda-date
	     (eq major-mode 'org-agenda-mode))
    (setq org-overriding-default-time
	  (org-get-cursor-date (equal goto 1))))
  (cond
   ((equal goto '(4))  (org-capture-goto-target keys))
   ((equal goto '(16)) (org-capture-goto-last-stored))
   (t
    (let* ((orig-buf (current-buffer))
	   (annotation (if (and (boundp 'org-capture-link-is-already-stored)
				org-capture-link-is-already-stored)
			   (plist-get org-store-link-plist :annotation)
			 (ignore-errors (org-store-link nil))))   ;;; <----------------- HERE
	   (entry (or org-capture-entry (org-capture-select-template keys)))
	   initial)
      (setq initial (or org-capture-initial
...
```
It possibly could be avoided by `let` binding `org-capture-link-is-already-stored` to `t` but this could create other issues. (such as if we actually wanted the link

**Comment by TRSx80** [comment]
Doesn't `org-id-link-to-org-use-id` need to be set non-nil for that to happen?

**Comment by TimQuelch** [comment]
IIRC `org-roam-store-link` will always use IDs. See `org-roam-store-link` and https://github.com/org-roam/org-roam/blob/925d225f139525a854e97b1b19494af7cdd7f1c1/org-roam.el#L1726-L1729

**Comment by ln0a** [comment]
> `org-capture` automatically stores a link when capturing. This triggers an ID creation. This is part of `org` rather than `org-roam`
> 
> ```emacs-lisp
> (defun org-capture (&optional goto keys)
> ; ...
>   (interactive "P")
>   (when (and org-capture-use-agenda-date
> 	     (eq major-mode 'org-agenda-mode))
>     (setq org-overriding-default-time
> 	  (org-get-cursor-date (equal goto 1))))
>   (cond
>    ((equal goto '(4))  (org-capture-goto-target keys))
>    ((equal goto '(16)) (org-capture-goto-last-stored))
>    (t
>     (let* ((orig-buf (current-buffer))
> 	   (annotation (if (and (boundp 'org-capture-link-is-already-stored)
> 				org-capture-link-is-already-stored)
> 			   (plist-get org-store-link-plist :annotation)
> 			 (ignore-errors (org-store-link nil))))   ;;; <----------------- HERE
> 	   (entry (or org-capture-entry (org-capture-select-template keys)))
> 	   initial)
>       (setq initial (or org-capture-initial
> ;...
> ```
> 
> It possibly could be avoided by `let` binding `org-capture-link-is-already-stored` to `t` but this could create other issues. (such as if we actually wanted the link.
> 
> I agree, this is a little annoying though

Thanks for the responses, this solves the issue. I understand it's a little hacky but I think it'll do just fine for now!
