### ISSUE TITLE
Question about SQL usage / requirement?

### ISSUE THREAD

**Issue by TRSx80** [org-roam/org-roam#1115]
Hallo,

I read all the docs and searched Issues, but could not seem find an answer to my query (and apologies for bothering you if I missed it somewhere).

I really hope this does not come across the wrong way.  :smile:  I was initially very excited when reading about org-roam.  However I was quite disappointed when I read about the SQL requirement.  To me, personally, that disqualified it from consideration as I wanted to keep all my files strictly in plain text.

But then today, we were discussing org-roam (and related tools) in `#emacs` (on Freenode), and someone mentioned that SQL was only used for caching.  In other words, the real "source of truth" is always the plain text files themselves.  Is that true?

I suppose I come here today to get the word straight from the horse's mouth, so to speak, rather than fuel speculation on the Internet.  I hope it's alright!

**Comment by TimQuelch** [comment]
The cache is there so that links can be looked up quickly when the number of files is large. It is built directly from the plain-text notes. No extra information is stored in the database that is not found by inspecting the note text files directly.

**Comment by jethrokuan** [comment]
Yes that is correct, the SQL database is populated only with information from the text files, and that will always be the case.

**Comment by TRSx80** [comment]
Well, now I am really glad I asked then!

I cannot help but wonder if I was not the only person operating under such an (mistaken) assumption.  Even if incorrect, anyone holding such a viewpoint might similarly preclude org-roam from consideration.  Which would be a tragedy, as I think you guys are doing great work here.

Therefore, maybe it might be a good idea to clarify / explicitly make that point in the docs?

If such a point exists already, I could not find it.
