### ISSUE TITLE
`org-roam-db-build-cache` doesn't pick up vanilla tags

### ISSUE THREAD

**Issue by spacekitteh** [org-roam/org-roam#1119]
### Description
This is seemingly due to disabling `org-mode` functionality in `org-roam--with-temp-buffer`.
#### Steps to Reproduce
Add a tag to a file/headline with `org-roam` disabled. Then enable it, and build the cache.

#### Expected Results
The file has the tag.

#### Actual Results
The file does not have the tag.

**Comment by jethrokuan** [comment]
should be fixed by #1520
