### ISSUE TITLE
the message "database updated during idle:balabala" too frequently interrupt my work fluency

### ISSUE THREAD

**Issue by WaytrueDeng** [org-roam/org-roam#1126]
### Description
Thank you guys work, but it seems like I meet a problem which makes my experience awful.

When the "database updated during idle" show up, The whole emacs will freeze about 0.1s. and if when I was editing a file, it will show up nearly every 10s. the most important is that when I use the input method (system's not emacs-buitin) fcitx5-rime type pinyin to input Chinese when the freezing some letter will bypass the input method directly put into emacs, which makes so hard to type a whole sentence. 

Is there a option to make the database updated only when I save the buffer to the file? 

#### Expected Results

the emacs not freeze when database update, or database only update when I save buffer to file, or keep it not so frequently.

### Environment
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
- Framework: I don't know
- Org: Org mode version 9.3 (release_9.3 @ /usr/share/emacs/27.1/lisp/org/)
- Org-roam: 1.2.1
![深度截图_选择区域_20200922142647](https://user-images.githubusercontent.com/61548208/93852765-1a0a3700-fca2-11ea-9d68-2bf1b671ba7d.png)
![Uploading 深度截图_选择区域_20200922150513.png…]()

**Comment by jethrokuan** [comment]
With #1122 you can set `org-roam-update-db-idle-seconds` to a higher value.

**Comment by WaytrueDeng** [comment]
> With #1122 you can set `org-roam-update-db-idle-seconds` to a higher value.

Thank you for making org-roam better, I will try it.

**Comment by WaytrueDeng** [comment]
> With #1122 you can set `org-roam-update-db-idle-seconds` to a higher value.

I set that number to 10000000000 and restart. And it is still a trouble, do I have a way to disable the auto save buffer to file function then I can manual save it to file to trigger the db update.

**Comment by jethrokuan** [comment]
Org-roam does not auto-save files, that's probably something else in your config. DB updates do not trigger anymore if you set the variable to a large number like that, and you can run `org-roam-db-build-cache` manually to trigger the update.

**Comment by WaytrueDeng** [comment]
> Org-roam does not auto-save files, that's probably something else in your config. DB updates do not trigger anymore if you set the variable to a large number like that, and you can run `org-roam-db-build-cache` manually to trigger the update.

Thanks for your kind helping🙏，I use emacs only 4 days and just for org and org-roam👍

**Comment by muello** [comment]
I had this issue too. I thought it was org-roam because it only happened when I was editing org-roam files. Turns out it was deft, which was operating on just the same files. You can switch deft's auto-save function off with `(setq deft-auto-save-interval 0)`.
