### ISSUE TITLE
#+roam_ref: needs to omit http: to make the backlink appear ("#+roam_ref: //duckduckgo.com/" works)

### ISSUE THREAD

**Issue by nobiot** [org-roam/org-roam#1135]
### Description
Yout want to use `#+roam_key:` for a website. You expect `#+roam_key: http://duckduckgo.com/` to work. It seems it needs to be `#+roam_key://duckduckgo.com` (you would need to omit the protocl "https:"). See the image for illustration.

![image](https://user-images.githubusercontent.com/12507865/94272436-5a3c1480-ff43-11ea-935a-1b4901326c72.png)

Refer to this Slack [thread](https://orgroam.slack.com/archives/CV20S23C0/p1601040199011500?thread_ts=1601005076.006600&cid=CV20S23C0) as well

#### Steps to Reproduce

1. Create a new note (Note A)
2. Add #+roam_key: http://duckduckgo.com/
3. Create a new note (Note B), and insert a link to the website, "http://duckduckgo.com".

#### Backtrace
No backtrace

#### Expected Results
Open Note A in Org-roam; Ref Backlink appears from Note B
#### Actual Results
No backlink. 
You'd need to change #+roam_key: to "#roam_key://duckduckgo.com".

### Environment
- Emacs: GNU Emacs 27.1 (build 1, x86_64-w64-mingw32)
 of 2020-08-21
- Framework: N/A
- Org: Org mode version 9.4 (9.4-elpa @ c:/Users/nobiot/.emacs.d/elpa/org-9.4/)
- Org-roam: 1.2.1
- Org-roam commit: MELPA: org-roam-20200923.958

**Comment by jethrokuan** [comment]
Thanks for the report as always @nobiot, fixed with #1140
