### ISSUE TITLE
the backlinks buffer is blank.

### ISSUE THREAD

**Issue by flyingns** [org-roam/org-roam#1158]
### Description
When I update to the latest commit after `925d225`, the backlink buffer no longer displays anything. Rebuilding `org-roam.db`, nothing can be displayed in the backlink buffer. The settings have not been changed. Is the latest commit changed? (I'm sorry, I haven't updated org-roam for a while). After experimentation, `925d225` is a completely normal and usable commit, and all subsequent commits With the problem described above, even if it was updated to the latest `369753c`, the backlink buffer is blank.

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6)
 of 2020-08-12
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /Users/mls/.emacs.d.new/.local/straight/build/org-mode/)
- Org-roam: 1.2.1

**Comment by myshevchuk** [comment]
There is a number of issues involving an empty backlink buffer, both open and closed. Search through them maybe a solution or a hint to a solution is already there.

**Comment by myshevchuk** [comment]
Ok, I can partially confirm this. The backlinks are shown, but the ref backlinks are empty, although the number of the ref backlinks is shown in the headline. There's also an error thrown when opening the backlinks buffer: 

> Error in post-command-hook (org-roam-buffer--update-maybe): (wrong-number-of-arguments (1 . 2) 0)
