### ISSUE TITLE
org-roam shows two tags with the same name after renaming

### ISSUE THREAD

**Issue by searene** [org-roam/org-roam#1169]
### Description

After I rename a tag, `org-roam-find-file` shows two tags with the same name.

#### Steps to Reproduce

1. Open Emacs
2. Use `org-roam-find-file` to open the `Food` tag(which is also an org file).
3. Rename `Food` to `Delicious`.
4. Then press `org-roam-find-file` again, I notice that there are two `Delicious` tags on it.

Note that `org-roam` went back to normal(only one `Delicious` tag) after I ran `org-roam-db-clear` and restarted Emacs.

#### Expected Results

There should only be one `Delicious` tag on the `org-roam-find-file` list.

#### Actual Results

There are two `Delicious` tags on the `org-roam-find-file` list.

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-29
- Framework: N/A
- Org: Org mode version 9.3 (release_9.3 @ /usr/share/emacs/27.1/lisp/org/)
- Org-roam: 1.2.2

**Comment by jethrokuan** [comment]
This should not occur anymore, let me know if it still happens.

**Comment by searene** [comment]
> This should not occur anymore, let me know if it still happens.

Thanks, it didn't happen to me recently. I will close it for now.
