### ISSUE TITLE
org-capture-fill-template: Args out of range: 0, 1

### ISSUE THREAD

**Issue by flyingns** [org-roam/org-roam#1170]
#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam-find-file`

#### Backtrace

Debugger entered--Lisp error: (args-out-of-range 0 1)
  replace-match("\\1" nil nil "")
  org-capture-fill-template("%<%Y%m%d%H%M%S>-111")
  org-roam-capture--fill-template("%<%Y%m%d%H%M%S>-${slug}")
  org-roam-capture--new-file()
  org-roam-capture--get-point()
  org-capture-set-target-location(nil)
  org-capture(nil "d")
  org-roam-capture--capture()
  org-roam-find-file()
  funcall-interactively(org-roam-find-file)
  call-interactively(org-roam-find-file record nil)
  command-execute(org-roam-find-file record)
  counsel-M-x-action("org-roam-find-file")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "org-roam-find-file" "org-roam-db-build-cache" "org-roam-insert" "org-footnote-renumber-fn:N" "org-footnote-goto-definition" "org-footnote-normalize" "org-mode" "org-noter" "menu-bar-mode" "org-roam" "replace-string" "package-list-packages" "org-brain-visualize" "replace-regexp" "org-brain-update-id-locations" "load-theme" "elfeed" "pdf-tools-install" "elfeed-update" "package-install" "cnfonts-edit-profile" "writeroom-mode" "org-set-property" "org-journal-new-entry" "org-noter-insert-note" "magit" "org-roam-graph" "pamparam-drill" "eshell" "describe-mode" "org-agenda-filter" "centered-cursor-mode" "auto-save-visited-mode" "lsp-python-ms-update-server" "grip-mode" "lsp-ui-mode" "avy-goto-char" "emacs-lisp-mode" "auto-image-file-mode" "org-cycle" "linum-mode" "org-version" "org-insert-link" "org-noter-insert-precise-note" "lsp" "wttrin" "doom/info" "easy-hugo" "elfeed-org" ...) :predicate #f(compiled-function (x) #<bytecode 0x1fe42b49f945>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6)
 of 2020-08-12
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /Users/mls/.emacs.d.new/.local/straight/build/org-mode/)
- Org-roam: 1.2.2

**Comment by ksexton** [comment]
Getting the same error, although it only appears to happen if I am in a buffer not tied to a file, like `*scratch*` or `*Messages*`.   If I open up a new file `~/test.txt` I can run `M-x org-roam-find-file` and the command succeeds.

**Environment**

- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101)) of 2020-08-27
- Framework: None
- Org: Org mode version 9.4 (release_9.4-22-ge2bb60 @ /Users/kes/.config/emacs/straight/build/org/)
- Org-roam: 1.2.2

**Comment by shanyouli** [comment]
Getting the same error. Cannot use `org-roam-find-file` to create a new file in the current buffer is *scratch*.

## Environment
+ emacs-version 27.1
+ FrameWork: doom
+ Org-version: 9.4
+ Org-roam: 1.2.2

**Comment by jethrokuan** [comment]
> Cannot use org-roam-find-file to create a new file in the current buffer is scratch.

I can, though.

```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0)
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/jethro/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.2
```

**Comment by flyingns** [comment]
> Got this to go away, seemed to be tied to the version of org I was using. I removed / reinstalled org and the error disappeared.

What is your org commit id? I updated to commit `e2bb6058` and still reported this error.

**Comment by ksexton** [comment]
> > Got this to go away, seemed to be tied to the version of org I was using. I removed / reinstalled org and the error disappeared.
> 
> What is your org commit id? I updated to commit `e2bb6058` and still reported this error.

`Org mode version 9.4 (release_9.4-57-g8402c4 @ /Users/kes/.config/emacs/straight/build/org/)`

**Comment by vadimi** [comment]
it should be fixed in doom now: https://github.com/hlissner/doom-emacs/issues/4087

**Comment by flyingns** [comment]
Problem solved, thanks.
