### ISSUE TITLE
file and link renaming when title changes doesn't work consistently and doesn't close back files

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam#1171]
### Description
A recent org roam feature to rename files and associated links when title of a file changes has a couple of bugs. 

One is that file renaming doesn't work consistently. Changing the title of some files doesn't have impact on the file name. I am not sure what the criteria is but I have noticed it consistently enough to be an issue.

Another is that files whose org links are updated aren't closed afterwards.

related to #1129 and #1095.

#### Steps to Reproduce
1. open a org roam file that has backlinks
2. rename it

#### Expected Results
file name changes.
files that link to it are modified and close afterwards if they weren't open.

#### Actual Results
file name doesn't change.
files that link to it are modified and but remain open.

### Environment
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-20
- Framework: Spacemacs
- Org: Org mode version 9.4 (9.4-9-gab0052-elpaplus @ ~/spacemacs/elpa/develop/org-plus-contrib-20200928/)
- Org-roam: 1.2.2

**Comment by jethrokuan** [comment]
I need more info than this to look into it. What's the name of the file you're renaming? what are you expecting?

**Comment by natask** [comment]
For example a while ago,
I captured a website that had no title. so org roam created a file with no name ".org".
I then changed its title.
I then renamed the file because org roam didn't include it into the data base.
the renamed file name didn't match the file name org roam would have created given the current title of file.
update the database. 
changing the title of the file now doesn't modify the filename.

surprisingly, changing the title of the file to what org roam would have created given the file name enables this feature.
change the title of the file to match the filename
save and update database
now changing the title of the file also changes the filename.

My assumption is that org-roam currently doesn't modify the names whose titles and file names don't match. This explains why I have been having this problem because I have been using org roam before the release of this feature and almost always change the title of websites I capture.

**Comment by jethrokuan** [comment]
> My assumption is that org-roam currently doesn't modify the names whose titles and file names don't match. 

This is correct. This is because we cannot tell what file-name template was used to generate the original file name. For example, if someone uses just the timestamp for a file name, changing the title should not affect the filename. The smartest thing we can do is to slugify the new title and do a search and replace.

Let me know if you have better ideas.

**Comment by natask** [comment]
The feature with the least overhead is to provide a function that can be called manually on current buffer or all org-roam-buffers. Subsequent modifications will affect file name which is probably desired by the caller. It shouldn't affect links descriptions unless file name matched with description.

It is also possible to create a lookup table for each org-roam-file and query that instead of the current predicate. This has the benefit that this feature is decoupled  from file state and made more explicit.

**Comment by natask** [comment]
Personally speaking, I have it disabled now because of its inconsistencies, because it isn't a stateless operation (keeps files open that it should really close) and some other bugs I encountered. some fixed #1192 and such and some not. 
For example, I sometimes get a duplicate ref error.

I recommend disabling this feature by default.

**Comment by jethrokuan** [comment]
Closed with #1330.
