### ISSUE TITLE
The newest org-roam,when I C-c C-o [[foo]]  will not trigger the org-roam-capture ,it said 'No match - create this a new heading?'

### ISSUE THREAD

**Issue by WaytrueDeng** [org-roam/org-roam#1184]
As the caption said.

**Comment by jethrokuan** [comment]
Org-roam now no longer overrides fuzzy links. That functionality is moved to `roam:` links, i.e. `[[roam:foo]]` is the way you do it now.

**Comment by WaytrueDeng** [comment]
You mean if I want to make and link to a new page, I have to type [[roam:]]  this syntax?,  it is maybe not so convenient. The old  fuzzy way may be more fluent? or there is a better way in new style to make new page?

**Comment by WaytrueDeng** [comment]
oh, I read the new Document I now how to do it now , thank you
