### ISSUE TITLE
Support file properties drawer

### ISSUE THREAD

**Issue by d12frosted** [org-roam/org-roam#1185]
### Brief Abstract

Since Org 9.4, files also get properties drawer, which we can use to store things like `ROAM_KEY`, `ROAM_TAGS` and `ROAM_ALIAS`. 

### Long Description

Example of file:

```org-mode
:PROPERTIES:
:ID:                     cf38556b-cddf-49af-8814-3b7e62f06d8c
:CUSTOM_ID:              9a4281c8-15f0-44b2-8961-56946beb83e1
:ROAM_ALIAS:             "Some Alias"
:ROAM_TAGS:              Work "Long Tag"
:END:
#+TITLE: My Note
```

I see two reasons for this:

1. Org provides properties API, while `#+` must be supported by `org-roam` developers (not that hard, but why should someone maintain code that is out of project responsibility).
2. Consistency between file properties and outline properties. Less indirection is good.

Also see [this comment](https://github.com/org-roam/org-roam/pull/1183#discussion_r502894723).

### Proposed Implementation (if any)

Since Org 9.4. is pretty new, not sure if we can switch right meow. We should either wait for wider adoption or support two styles for a while. Or we could be the ones who push the adoption of new version of Org 😈 

Regardless, I believe that we need to cover following things:

1. Switch to properties drawer in all places.
2. Provide a mechanism to migrate notes (do it automatically?).

WDYT?

### Please check the following:

- [X] No similar feature requests

**Comment by spacekitteh** [comment]
>Org provides properties API, while #+ must be supported by org-roam developers (not that hard, but why should someone maintain code that is out of project responsibility).

Note that org /does/ support #+ through the org-element api - they are =keywords=.

**Comment by czikus** [comment]
I would just like to share my experience with keywords and properties. I actually like the fact that ROAM_ALIAS is a keyword. I keep my drawers folded, and use them for properties that should be hidden (e.g. ID). However, I would like to keep ROAM_ALIAS and _KEY visible when I open a file. So, I vote for retaining both possibilities.
