### ISSUE TITLE
Links using org-id are displayed as broken by org-roam

### ISSUE THREAD

**Issue by dimitar-petrov** [org-roam/org-roam#1191]
### Description
Current file is part of my agenda-files. The link is not broken, the issue is that in is displayed using org-roam-invalid-face.
![org-roam-link-with-id-unvalid-face](https://user-images.githubusercontent.com/4025446/96219364-54a87c00-0f8f-11eb-973f-10ae42082138.png)

Not sure if this is a bug or configuration issue on my part.
Any pointers reganding how to debug further are well appreciated.
Thanks.

### Environment
- Emacs: GNU Emacs 28.0.50 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.17.3)
 of 2020-09-04
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
does it go away? org-roam queues files for updates, it's possible that the ID has not been cached by Org-roam, so Org-roam thinks it is invalid.

**Comment by dimitar-petrov** [comment]
> does it go away? org-roam queues files for updates, it's possible that the ID has not been cached by Org-roam, so Org-roam thinks it is invalid.

No, it does not go away.
