### ISSUE TITLE
org-roam-rename-file-on-title-change messes up backlinks

### ISSUE THREAD

**Issue by oatmealm** [org-roam/org-roam#1192]
### Description

When I update a title and save the file while `org-roam-rename-file-on-title-change` is set to `t`, a link back to the changed file is inerted before the `#+TITLE` part of org-file.

Might be related to #1171?

#### Steps to Reproduce
1. org-roam-find-file Aa.org and save
2. org-roam-find-file Bb.org and save
3. In Aa.org org-roam-inset a link to Bb.org
4. [optional] In Bb.org insert a link to Aa.org
5. Change the document title in Aa.org and save

#### Backtrace
I see this happening often while changing or renaming documents:

```
org-roam--replace-link: Match data clobbered by buffer modification hooks
```

And when I turn on debug, I see:

```
```

#### Expected Results
On saving the title, I'd expect the file to be renamed and be linked back to correctly.

#### Actual Results
File is renamed but files that link to it get messed up.

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0)
 of 2020-08-20
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/uri/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.2

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/master origin/master 87d7c07

**Comment by jethrokuan** [comment]
Please check if #1189 has resolved this (latest master commit).

**Comment by oatmealm** [comment]
Hi! I'm on `a7cf48e` now, and it seem to have solved the problem. i.e. no clobbering of the title line.

BTW, this seems to also break backlinks. 

I've got `org-roam-rename-file-on-title-change` set to true, and the file name slug is recreated when I save the file after changing the title, though it looks  like the hook that re-links all references is  not triggred, so backlinks break... am I missing something? This works if I use `dired` to edit file names.

**Comment by oatmealm** [comment]
This seems to work now as far as I can tell.
