### ISSUE TITLE
 Query timeout error: "Query timed out", 30 

### ISSUE THREAD

**Issue by wxknxxzj** [org-roam/org-roam#1196]
1.The startup process is slower than before.
2.After boot, a message will appear in the mini buffer: Query timeout error："Query timed out",30
![图片](https://user-images.githubusercontent.com/69200664/96408097-5c795200-1215-11eb-9d31-2dccea3aec26.png)

**Comment by wxknxxzj** [comment]
It seems to have something to do with it：
Need maintainable Windows 10 install · Issue #682 · org-roam/org-roam: https://github.com/org-roam/org-roam/issues/682

**Comment by wxknxxzj** [comment]
There are two sqlite3 I have in the windows10, it's normal to delete one environment variable,

**Comment by aleneum** [comment]
I experienced some interferences of desktop save mode and roam. What you could try: If you have `(desktop-save-mode 1)` in your .emacs configuration, disable this line and restart emacs.

**Comment by herbertjones** [comment]
With desktop mode, I'm using this.  I'm not certain that it's the correct fix, but it prevents startup slowness.

```elisp
(with-eval-after-load 'desktop
      (defun hfj/org-roam-desktop-restore (buffer-locals)
        "Don't call org-roam-mode multiple times."
        (unless (bound-and-true-p org-roam-mode)
          (org-roam-mode))
        t)

      (add-to-list 'desktop-minor-mode-handlers
                   '(org-roam-mode . hfj/org-roam-desktop-restore)))
```

**Comment by nokiasonic** [comment]
I have the similiar problem. after emacs' long time startup. in "message" buffer. it shows "files--ensure-directory: Query timeout error: "Query timed out", 30". But no more information even using --debug-init.  I try to disable "desktop-save-mode". but no changes.

**Comment by agisga** [comment]
Just in case it's relevant for someone seeing this error message:
I experienced the same behavior and the same error message when org-roam was attempting to create org-roam.db on a remote disk (/home on that machine was automounted from a network drive). The solution was to manually specify org-roam-db-location to be saved at a local disk location, via `(setq org-roam-db-location "/some/local/disk/location/org-roam.db")` (similarly as discussed under issue https://github.com/org-roam/org-roam/issues/977).

**Comment by randomwangran** [comment]
Similar case on my side:

```
(org-roam) Processed 8598/120000 modified files...
Query timeout error: "Query timed out", 30
```

**Comment by jethrokuan** [comment]
A lot has changed in master, feel free to reopen if still an issue.

**Comment by jpretori** [comment]
I'm getting this problem in a QEMU VM running Mint 20.2.  The reason I have the VM, is that I'm trying to replicate my desktop environment so that I can experiment with e.g. upgrading to emacs 27 safely.

So I have a mostly set-up environment that is reasonably real-world, and can safely be experimented with.  So feel free to give me stuff to try :)

**Comment by jpretori** [comment]
In an attempt to fix this, I uninstalled org-roam using the package manager, which didn't seem to work.  so I deleted the folder in .emacs.d/elpa, deleted .emacs.d/org-roam.db and re-installed the package.  The package installed fine, but it didn't create org-roam.db and the startup problem remains.

Deleting it again in the package manager removes the folder in .emacs.d/elpa, and if I re-install it again using the package manager I get these error messages:

```Error (use-package): org-roam/:config: Query timeout error: "Query timed out", 30
Error (use-package): org-roam/:config: Selecting deleted buffer
Error (use-package): org-roam/:config: Selecting deleted buffer```

The folder gets created, but org-roam.db does not.

org-roam-version says `2.2.0`.

Calling org-roam-node-find gives me a message in the minibuffer: `Selecting deleted buffer`

**Comment by jethrokuan** [comment]
https://www.orgroam.com/manual.html#I_0027m-seeing-this-_0060_0060Selecting-deleted-buffer_0027_0027-error-What-do-I-do_003f

You need to make sure you have the sqlite binary built, maybe your VM doesn't have a C compiler, or see https://www.orgroam.com/manual.html#Customizing-Node-Caching for other DB options.

**Comment by jpretori** [comment]
I checked, it already had GCC installed by default (as part of OS installation).  I'll check out the other links, thanks!

Would it not have failed to install org-roam if the sqlite compilation didn't work?

**Comment by jpretori** [comment]
For future people coming across this issue:
 - You need to install `sqlite3` using your package manager.  There is a package in melpa, but it doesn't seem to be enough - I'm not sure if you need both
 - You need to `(setq org-roam-database-connector 'sqlite3)` in your .emacs file _before_ you initialize org-roam

**Comment by jethrokuan** [comment]
If you intend to use `sqlite3` instead of the Emacs-built sqlite binary, you'll need both `emacsql-sqlite3` from MELPA as well as the `sqlite3` binary from your system package manager, or however else you may choose to acquire it.

That said, in most cases with proper system setup the emacs-sqlite binary should compile correctly, and you don't need to do anything.

**Comment by chillja** [comment]
For other people who might have the same issue: I ran into this issue as I share the database across two different system via my nextcloud, with one of my machines (for some reason?) appears to automatically use sqlite3 and the other one not, maybe more up-to-date doom on one machine. @jpretori and @jethrokuan suggestions fixed it, thank you.
