### ISSUE TITLE
Co-existance with org-journal

### ISSUE THREAD

**Issue by aqua36** [org-roam/org-roam#1202]
(Please excuse my superficial knowledge of both org-roam and org-journal when considering the following)

Is the org-roam-daily-* functionality meant to provide an alternative to org-journal? 

I see people using org-roam and org-journal at the same time and I would like to know if the developers/contributors plan to provide similar features to those in org-journal in order to inform my decision of whether to use org-journal at all. (If similar functionality is provided already or is planned to be provided I would prefer using org-roam only)

**Comment by jethrokuan** [comment]
The exact same discussion can be found on Discourse:

https://org-roam.discourse.group/t/org-journal-vs-org-roam-dailies/384/4

What was meant to be a subset of org-journal seems to be turning into something more, but only @zaeph can answer that. You can see his demo here: https://www.youtube.com/watch?v=1q9x2aZCJJ4&feature=youtu.be (see #978)

**Comment by zaeph** [comment]
> What was meant to be a subset of org-journal seems to be turning into **something more**, but only @zaeph can answer that. You can see his demo here: https://www.youtube.com/watch?v=1q9x2aZCJJ4&feature=youtu.be (see #978) [emphasis added]

It's a future milestone, but in its current state, #978 has more-or-less feature-parity with `org-journal`, save from the TODO-carry-over between days.

> Is the org-roam-daily-* functionality meant to provide an alternative to org-journal?

Yes: `org-roam-daily` is meant to replicate `org-journal` behaviours, but for slip-box notes.  The problem I had with co-opting `org-journal` to do our bidding was that `org-journal` couldn't really be used for non-slip-box stuff.  Also, having a native rewrite allows us to better integrate those daily-notes with the Zettelkasten method, which is the 'something more' that @jethrokuan mentioned.

**Comment by aqua36** [comment]
Thank you both @zaeph and @jethrokuan for the thoughtful answers. My question has been answered and I will close this issue. Any further discussion could be continued on the Discourse link @jethrokuan provided
