### ISSUE TITLE
 org-roam--extract-links leaves files open

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam#1203]
### Description
 org-roam--extract-links leaves files open

#### Steps to Reproduce
1. create a file with an id link to some other file or file's headline.
2. Run `org-roam--build-cache`

#### Expected Results
closes linked file intelligently (if it wasn't already open).

#### Actual Results
keeps linked file open.

#### Solution
```diff
 -                          (list (car (org-roam-id-find path nil nil 'keep-buffer))))
 +                          (list (car (org-roam-id-find path nil nil))))
```
there are no instances where the buffer in question should be kept open.

#### test clause
we need a test for functions that have open buffer side effects. there have been quite a few that leave side effects unhandled.
most notably ##1171, #1129 and #1146.
something like
``` elisp
   (let (before after)
   (setq before (length (buffer-list)))
   (function)
   (setq after (length (buffer-list)))
   (assert (= before after))
```

**Comment by jethrokuan** [comment]
Closed with #1212
