### ISSUE TITLE
Broken company-org-roam after a4da8f32

### ISSUE THREAD

**Issue by aluuu** [org-roam/org-roam#1205]
### Description

In a4da8f32 `org-roam--format-link-title` function has been removed. This change breaks `company-org-roam`, because that package [depends](https://github.com/org-roam/company-org-roam/blob/master/company-org-roam.el#L92) on this function

#### Steps to Reproduce

1. Open a roam file.
2. Trigger `company-complete` invokation so that it would show a completion choices.
3. Attempt to select an option.
4. Error happens. 

#### Backtrace

```
Debugger entered--Lisp error: (void-function org-roam--format-link-title)
  org-roam--format-link-title("color-palettes")
  company-org-roam--post-completion("color-palettes")
  company-org-roam(post-completion "color-palettes")
  apply(company-org-roam (post-completion "color-palettes"))
  company-call-backend-raw(post-completion "color-palettes")
  apply(company-call-backend-raw (post-completion "color-palettes"))
  company--force-sync(company-call-backend-raw (post-completion "color-palettes") company-org-roam)
  company-call-backend(post-completion "color-palettes")
  company-cancel("color-palettes")
  company-finish("color-palettes")
  company-complete-selection()
  funcall-interactively(company-complete-selection)
  call-interactively(company-complete-selection nil nil)
  command-execute(company-complete-selection)
```

#### Expected Results

Link to a page is inserted in the buffer. 

#### Actual Results

Error `Company: backend company-org-roam error "Symbol’s function definition is void: org-roam--format-link-title" with args (post-completion color-palettes)` is raised.
`

### Environment

```
Copy info below this line into issue:
- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)
 of 2020-03-26, modified by Debian
- Framework: 
- Org: Org mode version 9.4 (9.4-elpa @ ~/.emacs.d/elpa/org-9.4/)
- Org-roam: 1.2.2
```

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/a7cf48ea895ee5aae93ad6d5b4550fb803f6ef8a

**Comment by aluuu** [comment]
Given that `company-org-roam` is actually archived (and probably deprecated), I actually found a decent replacement for this use-case.

1. Add to you `.emacs` the following lines 
```
(add-hook 'org-mode-hook
          (lambda ()
            (set (make-local-variable 'company-backends) '(company-capf))))
```
2. Auto-completion is triggered while you are typing `[[]]` first, get the cursor in the middle and start typing the title of the page you want to make link to.

Similar configuration is described here - [How to to get [[Title of the target note]] working with inline autocomplete in Org-roam](https://org-roam.discourse.group/t/how-to-to-get-title-of-the-target-note-working-with-inline-autocomplete-in-org-roam/782).

I have a feeling that the deprecation note should be added to the `company-org-roam` README file with extra mention on how `company-org-roam` package could be replaced (e.g. with the above mentioned method or any other way).

Feel free to close this ticket if you don't see any reason for maintaining backward compatibility for `company-org-roam` support.

**Comment by jethrokuan** [comment]
```
(setq org-roam-completion-everywhere t)
```

gets you the original company-org-roam behaviour. That is, company-org-roam's functionality is completely superceded by what is provided in this package via capf.

It's mentioned briefly here: https://www.orgroam.com/manual/Inserting-Links.html#Inserting-Links, but the docs are sparse.

**Comment by aluuu** [comment]
Considering that linking is essential part of the work in org-roam/zettelkast method, I think that `(setq org-roam-completion-everywhere t)` deserves to be a default behaviour.

**Comment by jethrokuan** [comment]
In the Zettelkasten method, linking should be a deliberate action. That is the direction org-roam is taking.

If you look at good examples of digital gardens, the note titles are well-crafted and unlikely to come up as-you-type anyway(e.g. https://notes.andymatuschak.org/).

**Comment by publicimageltd** [comment]
I think linking is a deliberate action and still completion should be enabled by default. Because if you have many pages, you simply don't always remember the precise title of the notes. So I use completion to get some feedback on what I have already written on: If I type a topic, I get immediate feedback on other notes. Sometimes I even find out that the topic I am writing about is already covered (yet with a slightly different wording). (Remember that links are not only to page titles, but also to headings within a page).

So +1 for making completion the default behavior.

**Comment by lgmoneda** [comment]
Wouldn't it make sense if the completion link follows the same format from `org-roam-insert`? 

It was the previous behavior I was used to when using org-roam-company. Now the completion uses `roam:[title]`, which breaks the text flow.

**Comment by lgmoneda** [comment]
☝🏻 nevermind, I see they are updated later.

**Comment by jethrokuan** [comment]
Closing with #1279
