### ISSUE TITLE
Option to disable the automatic display of the org-roam buffer

### ISSUE THREAD

**Issue by notevenaperson** [org-roam/org-roam#1206]
### Brief Abstract
The org-roam buffer is redisplayed every time a org document is loaded. I'm requesting an option to disable this behavior.
### Long Description
The org-roam buffer can occupy precious screen-space, especially on small screens. I'd rather have it hidden by default, and toggle the visibility of the buffer myself when necessary.
### Proposed Implementation (if any)
.
### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
This is a Doom thing, and does not ship with this repo:

https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/contrib/roam.el#L4
