### ISSUE TITLE
*org-roam* buffer crashes on while some org files opening

### ISSUE THREAD

**Issue by hokten** [org-roam/org-roam#1209]
When run `org-roam-find-file` command for some org files *org-roam* buffer loading properly but for some org files I got `wrong-type-argument: window-live-p` error. 

![output-2020-10-24-13:31:51](https://user-images.githubusercontent.com/7111/97079796-5e6d5780-15ff-11eb-8f0d-35264b128e04.gif)

**Comment by brianmcgillion** [comment]
I have run into this recently, it is quite hard to resolve. It appears to be a situation caused by having Property IDs and roam-links. It seemed that I was creating cyclical links i.e. I had a `-- tag ::` pointing to a roam-file but within that file a property linking to a specific heading. In one case, a file-level property ID was accidentally created above the Title and it caused the linked file to crash the OR buffer. I have not managed to drill down into it to find the exact cause or cleanly reproducible steps.

https://github.com/hlissner/doom-emacs/issues/4133#issuecomment-714899777

**Comment by Whil-** [comment]
Same issue here. I've traced it to the `org-roam-buffer--update-maybe` event that is activated 
when `org-roam-buffer--insert-ref-links` inserts backlinks.

Can't say I understand the interplay here, or that the functions I found to create this issue are the same for everyone. But maybe a breadcrumb that will trigger some thoughts of those more familiar with the code?

**Comment by brianmcgillion** [comment]
I just realized that if you are in an org-roam file and choose org-roam-find-file, it will automatically add a PROPERTIES_DRAWER with an ID to the nearest header. Not what was expected as it should be just creating an OR file and not linking.

**Comment by hokten** [comment]
I tried debug but the only thing i found this error : `(jit-lock-function 1) signaled (error "Selecting deleted buffer")`

**Comment by jethrokuan** [comment]
This seems to be caused by the org-roam buffer getting killed, while trying to be written into.

**Comment by jethrokuan** [comment]
been looking into this, but can't figure out why. For me it's the `org-roam-buffer--insert-backlinks` that's failing, because the `*org-roam*` buffer is getting killed, not sure by what.

**Comment by Whil-** [comment]
What I've found so far is that this error shows up when id-links are inserted into the org-roam-buffer... I.e. if the following modification is done:

```diff
modified   org-roam-buffer.el
@@ -199,20 +199,7 @@ ORIG-PATH is the path where the CONTENT originated."
                                    #'<
                                    bls))
             (dolist (props bls)
-              (insert "*** "
-                      (if-let ((outline (plist-get props :outline)))
-                          (-> outline
-                              (string-join " > ")
-                              (org-roam-buffer-expand-links file-from))
-                        "Top")
-                      "\n"
-                      (propertize
-                       (s-trim (s-replace "\n" " "
-                                          (org-roam-buffer-expand-links (plist-get props :content) file-from)))
-                       'help-echo "mouse-1: visit backlinked note"
-                       'file-from file-from
-                       'file-from-point (plist-get props :point))
-                      "\n\n")))))
+              (insert "id:20201012T015211.049865")))))
     (insert "\n\n* No backlinks!")))
```
I consistently get the `window-live-p` error. Further, If I change the ID in the above diff to an ID that doesn't exist in my setup the error goes away!

**Comment by Whil-** [comment]
I still get the same error

**Comment by Whil-** [comment]
One more step in the debugging; `org-roam-id-find` creates issues when it accidentally(?) kills the backlinks buffer. However, if the code is modified to not do that, as such:

```diff
modified   org-roam.el
@@ -1073,8 +1073,8 @@ When KEEP-BUFFER-P is non-nil, keep the buffers navigated by Org-roam open."
       (let ((existing-buf (find-buffer-visiting file))
             (res (org-id-find-id-in-file id file markerp)))
         (when (and (not keep-buffer-p)
-                   (not existing-buf))
-          (kill-buffer (find-buffer-visiting file)))
+                   existing-buf)
+          (kill-buffer existing-buf))
         res))))
```
I instead get some kind of infinite loop. :scratching head:

**Comment by Whil-** [comment]
Just FYI, as a temporary workaround I've modified my local org-roam to disable the custom org-roam face, like this:
```diff
modified   org-roam.el
@@ -1498,8 +1498,7 @@ M-x info for more information at Org-roam > Installation > Post-Installation Tas
     (advice-add 'delete-file :before #'org-roam--delete-file-advice)
     (advice-add 'org-id-new :after #'org-roam--id-new-advice)
     (when (fboundp 'org-link-set-parameters)
-      (org-link-set-parameters "file" :face 'org-roam--file-link-face)
-      (org-link-set-parameters "id" :face 'org-roam--id-link-face))
+      (org-link-set-parameters "file" :face 'org-roam--file-link-face))
```
Seems to get rid of this particular issue, for now.

**Comment by jethrokuan** [comment]
@Whil- did you have `org-roam-link-use-custom-faces` set to `'everywhere`?

**Comment by Whil-** [comment]
@jethrokuan It's unchanged from the default, i.e. value `t`

**Comment by jethrokuan** [comment]
This should also be gone now with #1263
