### ISSUE TITLE
OR-find-file creates a PROPERTIES drawer with ID in open OR file

### ISSUE THREAD

**Issue by brianmcgillion** [org-roam/org-roam#1214]
#### Steps to Reproduce

1. Open and OR file
2. org-roam-find-file
3. enter a name for the new file
4. when the minibuffer shows (the pre save buffer) a PROPERTIES drawer with ID will be added to the nearest HEADER
5. Not expected as it seems to cause a cyclical link. 

#### Backtrace
No BT - functional bug

#### Expected Results

No PROPERTIES drawer is created

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2020-09-19
- Framework: Doom
- Org: Org mode version 9.4 (nil @ $HOME/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.2

**Comment by jethrokuan** [comment]
This only occurs if you have `org-id-link-to-org-use-id` set to `t`. This is because `org-roam-find-file` calls `org-capture`, which calls `org-store-link`, which depending on whether this variable is set to `t`, creates a header at the current header or file.

**Comment by digizeph** [comment]
Found this issue too. The only relevant solution that i found is this: https://emacs.stackexchange.com/a/30884/15918. Is there a more elegant way to avoid doing store-link?

**Comment by digizeph** [comment]
Setting `org-id-link-to-org-use-id` to `create-if-interactive` will prevent `org-capture` from creating links, thus prevent creating the ID drawer.

```lisp
  (setq org-id-link-to-org-use-id 'create-if-interactive)
```
The documentation for `org-id-link-to-org-use-id` says:
```
create-if-interactive
      If org-store-link is called directly (interactively, as a user
      command), do create an ID to support the link.  But when doing the
      job for capture, only use the ID if it already exists.  The
      purpose of this setting is to avoid proliferation of unwanted
      IDs, just because you happen to be in an Org file when you
      call org-capture that automatically and preemptively creates a
      link.  If you do want to get an ID link in a capture template to
      an entry not having an ID, create it first by explicitly creating
      a link to it, using C-c l first.
```
