### ISSUE TITLE
Doesn't work with emacs 27.1

### ISSUE THREAD

**Issue by togakangaroo** [org-roam/org-roam#1219]
### Description

I just updated to emacs 27.1 and am getting an error where org-roam is not installable. Not seeing anything about it anywhere online so thought I'd come here.

Here is what `describe-package` gives me

```

     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa
    Version: 20201026.1625
     Commit: 0d235686f4b2cef9b6cded861edabf747e1d64e2
    Summary: Roam Research replica with Org-mode
   Requires: emacs-26.1, dash-2.13, f-0.17.2, s-1.12.0, org-9.3, emacsql-3.0.0, emacsql-sqlite3-1.0.2 (not available)
```

Emacs 27 has been out for some months now, and its kind of getting hard to properly run the toolchain without it since things like spacemacs develop branch are taking dependencies on emacs 27 functions.

Is lack of 27 support "official"? Any ideas?

**Comment by jethrokuan** [comment]
I'm running Emacs 28 just fine, I don't believe I've received anything on not being able to run on Emacs 27.

`describe-package` seems to suggest that `emacsql-sqlite3` 1.0.2 is not available for you. But it's right there on MELPA: https://melpa.org/#/emacsql-sqlite3

You may need to clear your MELPA cache and try again.

**Comment by d12frosted** [comment]
I have two installations - Emacs 27 and Emacs 28. Both work fine :) I think @jethrokuan is right, you need to refresh your packages.

**Comment by d12frosted** [comment]
> uhhh.how do I clear cache?

not sure that I've got your question, it depends on how you isntall your packages. Though in many cases, it's `package-refresh-contents`.

**Comment by togakangaroo** [comment]
Thanks a lot, that worked, closing now. 

Very strange to. It was showing me that `emacs-sqlite3` and that exact version was what was blocking its installation but when I clicked thorugh, that dependency was installed!
