### ISSUE TITLE
Error on database rebuilds: (error "Selecting deleted buffer")

### ISSUE THREAD

**Issue by Whil-** [org-roam/org-roam#1221]
### Description
When `org-roam-db-build-cache` is run it now and then (every second time for me atm) throws an error:

```
(error "Selecting deleted buffer")
```

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam-db-build-cache`
3. Run `org-roam-db-build-cache` again

--> On second try it crashes with error

#### Backtrace

<details>
  <summary>Click to expand!</summary>

```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  set-buffer(#<killed buffer>)
  (save-current-buffer (set-buffer (emacsql-buffer conn)) (save-excursion (goto-char (point-max)) (re-search-backward (rx-to-string (cons 'and (cons emacsql-sqlite3--cmd-end-mark '("\n" point)))) nil t)))
  (progn (save-current-buffer (set-buffer (emacsql-buffer conn)) (save-excursion (goto-char (point-max)) (re-search-backward (rx-to-string (cons 'and (cons emacsql-sqlite3--cmd-end-mark '...))) nil t))))
  (closure (t) (conn) (progn (save-current-buffer (set-buffer (emacsql-buffer conn)) (save-excursion (goto-char (point-max)) (re-search-backward (rx-to-string (cons ... ...)) nil t)))))(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004>)
  apply((closure (t) (conn) (progn (save-current-buffer (set-buffer (emacsql-buffer conn)) (save-excursion (goto-char (point-max)) (re-search-backward (rx-to-string (cons ... ...)) nil t))))) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004> nil)
  emacsql-waiting-p(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004>)
  (not (emacsql-waiting-p connection))
  (and (or (null real-timeout) (< (float-time) end)) (not (emacsql-waiting-p connection)))
  (while (and (or (null real-timeout) (< (float-time) end)) (not (emacsql-waiting-p connection))) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (accept-process-output (emacsql-process connection) real-timeout)) (set-match-data save-match-data-internal 'evaporate))))
  (let* ((real-timeout (or timeout emacsql-global-timeout)) (end (if real-timeout (progn (+ (float-time) real-timeout))))) (while (and (or (null real-timeout) (< (float-time) end)) (not (emacsql-waiting-p connection))) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (accept-process-output (emacsql-process connection) real-timeout)) (set-match-data save-match-data-internal 'evaporate)))) (if (emacsql-waiting-p connection) nil (signal 'emacsql-timeout (list "Query timed out" real-timeout))))
  (progn (let* ((real-timeout (or timeout emacsql-global-timeout)) (end (if real-timeout (progn (+ (float-time) real-timeout))))) (while (and (or (null real-timeout) (< (float-time) end)) (not (emacsql-waiting-p connection))) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (accept-process-output (emacsql-process connection) real-timeout)) (set-match-data save-match-data-internal 'evaporate)))) (if (emacsql-waiting-p connection) nil (signal 'emacsql-timeout (list "Query timed out" real-timeout)))))
  (closure (t) (connection &optional timeout) "Block until CONNECTION is waiting for further inpu..." (progn (let* ((real-timeout (or timeout emacsql-global-timeout)) (end (if real-timeout (progn ...)))) (while (and (or (null real-timeout) (< ... end)) (not (emacsql-waiting-p connection))) (let ((save-match-data-internal ...)) (unwind-protect (progn ...) (set-match-data save-match-data-internal ...)))) (if (emacsql-waiting-p connection) nil (signal 'emacsql-timeout (list "Query timed out" real-timeout))))))(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004>)
  apply((closure (t) (connection &optional timeout) "Block until CONNECTION is waiting for further inpu..." (progn (let* ((real-timeout (or timeout emacsql-global-timeout)) (end (if real-timeout (progn ...)))) (while (and (or (null real-timeout) (< ... end)) (not (emacsql-waiting-p connection))) (let ((save-match-data-internal ...)) (unwind-protect (progn ...) (set-match-data save-match-data-internal ...)))) (if (emacsql-waiting-p connection) nil (signal 'emacsql-timeout (list "Query timed out" real-timeout)))))) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004> nil)
  emacsql-wait(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004>)
  (let ((sql-string (apply #'emacsql-compile connection sql args))) (emacsql-clear connection) (emacsql-send-message connection sql-string) (emacsql-wait connection) (emacsql-parse connection))
  (progn (let ((sql-string (apply #'emacsql-compile connection sql args))) (emacsql-clear connection) (emacsql-send-message connection sql-string) (emacsql-wait connection) (emacsql-parse connection)))
  (closure (t) (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the..." (progn (let ((sql-string (apply #'emacsql-compile connection sql args))) (emacsql-clear connection) (emacsql-send-message connection sql-string) (emacsql-wait connection) (emacsql-parse connection))))(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004> [:select * :from files])
  apply((closure (t) (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the..." (progn (let ((sql-string (apply #'emacsql-compile connection sql args))) (emacsql-clear connection) (emacsql-send-message connection sql-string) (emacsql-wait connection) (emacsql-parse connection)))) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004> [:select * :from files])
  emacsql(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004> [:select * :from files])
  apply(emacsql #<emacsql-sqlite3-connection emacsql-sqlite3-connection-1b62004> [:select * :from files] nil)
  (if (stringp sql) (emacsql (org-roam-db) (apply #'format sql args)) (apply #'emacsql (org-roam-db) sql args))
  org-roam-db-query([:select * :from files])
  org-roam-db--get-current-files()
  org-roam-db-build-cache()
  (progn (org-roam-db-build-cache))
  eval((progn (org-roam-db-build-cache)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
</details>

#### Expected Results

Not error

#### Actual Results

Error

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-w64-mingw32)
 of 2020-08-21
- Framework: N/A
- Org: Org mode version 9.4 (release_9.4-80-ge75376 @ c:/Users/Gustav/.emacs.d/straight/build/org/)
- Org-roam: 1.2.2

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/0d23568

**Comment by Whil-** [comment]
By some magic the following millisecond sleep workaround solves the issue for me:
```diff
modified   org-roam-db.el
@@ -129,6 +129,7 @@ Performs a database upgrade when required."
 (defun org-roam-db-query (sql &rest args)
   "Run SQL query on Org-roam database with ARGS.
 SQL can be either the emacsql vector representation, or a string."
+  (sleep-for 0 1)
   (if  (stringp sql)
       (emacsql (org-roam-db) (apply #'format sql args))
     (apply #'emacsql (org-roam-db) sql args)))
```

But wanted to register it as an issue for a potential discussion of a better solution. Or potentially a push of exactly that to the repo...! Ugly though it might seem.

**Comment by jethrokuan** [comment]
Most of the emacsql-related code is inherited from [forge](https://github.com/magit/forge), and I occasionally see this issue pop up with forge too.

I suspect the real issue is upstream with emacsql, and the fix should be reported and applied there instead.

**Comment by jethrokuan** [comment]
Related: https://github.com/magit/forge/issues/204

I also see the error message for forge (I use nix):

```
/nix/store/jsl6dk813jxn54kd2s8cvb9fkk4jjrkj-emacs-gcc-20201025.0/bin/emacs: /home/jethro/.emacs.d/.local/straight/build/emacsql-sqlite/sqlite/emacsql-sqlite: No such file or directory
```

**Comment by Whil-** [comment]
Okay, understood. The workaround mentioned above, with adding a sleep, helped on my end so I'll be satisfied with that for now. Personally I would advocate to implement the sleep workaround in the repository if the positive effect can be reproduced. Waiting for a fix in emacsql will probably be in vain.

Feel free to close this or to deal with the sleep in any way you see fit. (I've actually increased it personally from 1ms to 10ms and have since then not hade any db read/write issues at all.)

**Comment by dansanduleac** [comment]
Same happens to me Spacemacs and Windows 10. The sleep hack doesn't help.
I made another issue in case it's different (e.g. I'm not hitting any errors where emacsql-sqlite couldn't be found), though it looks pretty similar otherwise.

**Comment by herop** [comment]
I have the following, quite similar, error-message on Windows with Emacs app 27.1 for month' now:
`Error running timer 'org-roam-db-update-chache-on-timer'`
Questions:
- Will there be a solution (pia now for at least 50 updates from org-roam
- Does it any harm  - like not updating some stuff or not showing or writing backlinks

**Comment by nobiot** [comment]
@herop, If the workaround @Whil- suggests above does not work for you, the approach I suggest in issue https://github.com/org-roam/org-roam/issues/1289 might help you (for Windows users). As the error is very likely Windows-only and coming from upstream, personally I would not expect the Org-roam project can address the problem quickly and easily (except @Whil- 's suggestion -- I haven't tried it myself).

**Comment by edgimar** [comment]
For the record, the workaround mentioned by @Whil- still works with the 20211027.1328 version of org-roam, and makes it functional in a MSYS2 setup. Without it, there's the every-other-call error, which apparently happens when the process sentinel gets called - presumably because the process has terminated? - and the buffer is deleted.

The current patch for the workaround is:
```diff
@@ -167,6 +167,7 @@
 (defun org-roam-db-query (sql &rest args)
   "Run SQL query on Org-roam database with ARGS.
 SQL can be either the emacsql vector representation, or a string."
+  (sleep-for 0 1)
   (apply #'emacsql (org-roam-db) sql args))
 
 (defun org-roam-db-query! (handler sql &rest args)
```

Please consider committing this benign change for the benefit of a large number of org-roam users (and to prevent naïve users from misjudging org-roam as being of poor quality because of this emacsqlite error).

**Comment by kotchwane** [comment]
I had a similar error on Arch Linux. It appears it was caused by the fact that I had two conflicting versions of emacsql and emacsql-sqlite installed in Melpa, namely `emacsql` and ’emacsql-sqlite` vs `emacsql3`and `emacsql-sqlite3`. 
Deleting the former (keeping only the "3" version) solved the issue for me.

**Comment by edgimar** [comment]
@kotchwane, not sure what effect conflicting versions have, as you mentioned, but in the case I was referring to, there were no conflicting versions, and it was running under MSYS2 / Windows.  Also I don't know what you mean by `emacsql3` -- I don't believe MELPA contains such a package.

Without the `sleep` patch, the every-other bug occurred when using either `emacsql-sqlite` or `emacsql-sqlite3`, and with the patch the bug does not occur with `emacsql-sqlite3` (didn't test with `emacsql-sqlite` and the patch).

**Comment by fleimgruber** [comment]
@jethrokuan would you reconsider adding the workaround mentioned in https://github.com/org-roam/org-roam/issues/1221#issuecomment-959871775? I (and I guess most Windows users affected) need to apply this after each MELPA update of org-roam by hand.

**Comment by jethrokuan** [comment]
@fleimgruber These sort of platform-specific hacks don't belong in the codebase. There's no need to do it manually either, advising should just work.

```
(defun my/sleep (_)
  (sleep-for 0 1))

(advice-add 'org-roam-db-query :before 'my/sleep)
```

**Comment by fleimgruber** [comment]
Thanks for your patience, frankness and the snippet. These things become so obvious in hindsight...

**Comment by Whil-** [comment]
FWIW, dismissing fixing this even if it's a hack is going to limit the usability of the program. Emacs is arcane enough. Expecting all windows users to use advices is a very disrespectful response to a quite large group of users. Or, would be users maybe.

Until better fixes are available I would suggest adding this ugly piece of code. Probably with a clear comment on the hackiness and a ref. to the issue, and within a block that only runs on windows.

Or amend the installation instruction to add info about how to manually do the advice, or just stating that windows is not supported.

best
G

**Comment by daraul** [comment]
I'm with jethro on this. At best I could see the workaround being documented where appropriate.

**Comment by fleimgruber** [comment]
I noticed that the advice workaround in https://github.com/org-roam/org-roam/issues/1221#issuecomment-1076601969 worked... until it didn't. AFAICS, `org-roam-db-query` gets called with one or two arguments. This seems to work

```
(defun my/sleep (_ &rest _)
  (sleep-for 0 1))

(advice-add 'org-roam-db-query :before #'my/sleep)
```

**Comment by nobiot** [comment]
I use Emacs and Org-roam in Windows daily, and have a different perspective.

1. The "Selecting deleted buffer" error is present regardless of the database connector, `sqlite3` or `sqlite` (I have been using `sqlite3` but just tried the default `sqlite` now); for the default connector, the error is present with my own binary that Jethro cites
2. The error has zero influence on my daily use of Org-roam; it only happens to me when I manually call `org-roam-db-sync` -- what I know is that you get the error message every second call to `org-roam-db-sync` and only this case. Since I never call it manually, I never see the error message (I can still cause it to occur by simply calling the db-sync command). The simple solution is to call it again
3. The advice workaround considerably slows `org-roam-node-find` (from less than a second to a few seconds for my 533 nodes today)

With this... for my usage, I'd prefer not to have this workaround. For me, I don't feel that not having this workaround is disrespectful to me as a Windows user (I'm one of the "large number of users"); but also I'm a power user who has been used to this error, which has been with Org-roam since V1. Saying this, I agree that we'd rather not have the error to begin with, if that were possible. 

My suggestion is to document this Windows-specific quark and the workaround with its performance issue in the user manual (and possibly in README) -- I'll be happy to do a draft, perhaps on the weekend...

Does anyone also experience the performance degradation when you implement the workaround?

**Comment by fleimgruber** [comment]
> For me, I don't feel that not having this workaround is disrespectful to me as a Windows user

I second this.

> Does anyone also experience the performance degradation when you implement the workaround?

No, I don't experience any perceptible performance degradation.

**Comment by kentbull** [comment]
This is not Windows specific. I have this on my M1 Mac. Things were working great for me until I did a `straight-pull-all` recently (I use the Straight package manager). The latest version of org-roam or another package must have broken something.

**Comment by kentbull** [comment]
Ok, I resolved the problem by deleting the ~/.emacs.d/org-roam.db file and then running `org-roam-db-sync`
