### ISSUE TITLE
sidebar comes up empty

### ISSUE THREAD

**Issue by J0ns4** [org-roam/org-roam#1223]
### Description
the sidebar is unpopulated (at all) - calling org-roam brings up an empty buffer names *org-roam* but nothing more.

following is the relevant lines of my config:

```
(use-package! org-roam
  :hook (org-load . org-roam-mode)
  :commands (org-roam-buffer-toggle-display
             org-roam-find-file
             org-roam-graph
             org-roam-insert
             org-roam-switch-to-buffer
             org-roam-dailies-date
             org-roam-dailies-today
             org-roam-dailies-tomorrow
             org-roam-dailies-yesterday)
  :preface
  :init
  :config
  (setq
   org-roam-db-location "~/org-roam/org-roam.db"
   org-roam-directory "~/google_drive/.notes/slip-box"
   org-roam-link-title-format "§:%s"
   org-roam-completion-system 'helm
   org-roam-index-file "~/google_drive/.notes/slip-box/index.org"

   org-roam-capture-templates
      '(("d" "default" plain (function org-roam-capture--get-point)
          "%?"
          :file-name "%<%Y-%m-%d>-${slug}"
          :head "#+TITLE: ${title}\n"
          :unnarrowed t))
))

```
### Environment

- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2019-09-16
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/jonathan/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.2

I'd really appreciate any help. it used to work, and somehow got broken :/

**Comment by dit7ya** [comment]
I am getting the same error in Spacemacs. Though sometimes it comes back just like that. This is one of the most mysterious bugs I have ever seen in any software. I haven't been able to pinpoint the cause or exact behavior yet.

**Comment by nsaritzky** [comment]
I had the same problem in version 20201030.623. Reverting to 20200711.2142 fixes it.

**Comment by J0ns4** [comment]
Hey, thanks!
how do I get the commit hash for a specific release?

**Comment by mplanchard** [comment]
I was running into this also. I took at look at the release notes for the most recent update [here](https://github.com/org-roam/org-roam/releases/tag/v1.2.2), which note:

> This change requires you to set org-roam-directory to the resolved path of a folder. That is:
> ```elisp
> (setq org-roam-directory (file-truename "/path/to/directory/"))
> ```

My `org-roam-direcrtory` was just set to the value of my `org-directory`, which was `~/org/`. Updating my config (doom emacs) to:

```elisp
(after! org-roam
  (setq org-roam-directory (file-truename org-directory)))
```

and restarting emacs fixed this for me 👍

**Comment by oatmealm** [comment]
Was this problem ever resolved? I'm still getting an empty sidebar more often then not, and sometime whith the error `Wrong type argument: window-live-p, #<window 9>`...
