### ISSUE TITLE
Is there a way to inhibt org-roam reading all of roam files to buffers when emacs startup?

### ISSUE THREAD

**Issue by WaytrueDeng** [org-roam/org-roam#1225]
### Brief Abstract
There are too many files in my buffers list.
### Long Description
Recently I move all my roam files to my Org/ directory(before they are in different sub directories),and every time I start up emacs, org-roam reads all of them to buffers. So I have a long long buffers list. And frankly, I don't like that  way and don't know how to modify it.
### Proposed Implementation (if any)
I want that org-roam loads the file to buffer when I open it, rather than load it at startup time before I open it.
### Please check the following:

- [ x] No similar feature requests

**Comment by d12frosted** [comment]
AFAIK, `org-roam` doesn't read anything upon being loaded. Maybe you call some function that does it? For example, `org-roam-db-build-cache`. Or maybe something else forces it. Hard to tell without seing how you load and configure `org-roam`, or better, your `.emacs.d` files.

> Recently I move all my roam files to my Org/ directory(before they are in different sub directories)

This makes me think that something else reads files from your org directory.

**Comment by iSeeU816** [comment]
If you're using `desktop.el` feature to preserve Emacs session to the next; then
you can defer loading buffers based on a value that you defined in the variable
I listed below:

``` emacs-lisp
(setq desktop-restore-eager 3)
```

Here I tell `desktop.el` to only load three buffers at the startup, and defer
the rest buffers until Emacs is in an IDLE state.

I think this is what you're looking after, if not then more details will help to
assist you.

**Comment by WaytrueDeng** [comment]
> AFAIK, `org-roam` doesn't read anything upon being loaded. Maybe you call some function that does it? For example, `org-roam-db-build-cache`. Or maybe something else forces it. Hard to tell without seing how you load and configure `org-roam`, or better, your `.emacs.d` files.
> 
> > Recently I move all my roam files to my Org/ directory(before they are in different sub directories)
> 
> This makes me think that something else reads files from your org directory.

Hi, thanks for your help, and here are some screenshots when I run emacs --damon(the same as when I run emacs), it seems like that org-roam will build the cache at the start up time, and when I open the the buffer list all my org files will be there. I am confused whether it is caused by org-roam or some other plugins I used.So I upload my init.el file here. Thanks again for your help.


![2020-10-31 08-59-42屏幕截图](https://user-images.githubusercontent.com/61548208/97767607-24003f00-1b58-11eb-9ef8-65554d145654.png)
![2020-10-31 09-00-49屏幕截图](https://user-images.githubusercontent.com/61548208/97767610-26fb2f80-1b58-11eb-95b2-a6ff039a98d3.png)

[init.el.txt](https://github.com/org-roam/org-roam/files/5468296/init.el.txt)

**Comment by d12frosted** [comment]
I think this is because you start `org-roam-mode` in `prog-mode-hook`. 

```lisp
      :hook
      (prog-mode . org-roam-mode)
```

Which in turn builds `org-roam` cache, because `org-roam-mode` calls `(org-roam-db-build-cache)` when enabled.

**Comment by WaytrueDeng** [comment]
> I think this is because you start `org-roam-mode` in `prog-mode-hook`. It seems that by default your scratch buffer is in `emacs-lisp-mode`, meaning that scratch buffer starts `org-roam-mode` as well.
> 
> ```lisp
>       :hook
>       (prog-mode . org-roam-mode)
> ```
> 
> Which in turn builds `org-roam` cache, because `org-roam-mode` calls `(org-roam-db-build-cache)` when enabled.

Oh, you are right, but I am confused that why build cache will read files to buffer rather than simply update info in db.

**Comment by d12frosted** [comment]
> Oh, you are right, but I am confused that why build cache will read files to buffer rather than simply update info in db.

Well, in order to build cache, files needs to be read 😸 But on the latest master they should be killed after the cache builds. So please try to upgrade `org-roam`. See https://github.com/org-roam/org-roam/issues/1203 as a reference for this issue.

**Comment by WaytrueDeng** [comment]
Oh, You guys have fixed that! I will update org-roam at once. thanks for your help.
