### ISSUE TITLE
Moving a file converts all absolute-path org-mode links to that file into relative-path org-mode links

### ISSUE THREAD

**Issue by mchowning** [org-roam/org-roam#1228]
### Description

If a file is moved to a different directory then any absolute-path org-mode links to that file are updated to be relative-path org-mode links. 

I believe this is related to org-roam because, in my testing, this does not occur when neither file is in the org-roam directory.

#### Steps to Reproduce

1. Create two files in the same directory (`file1`, `file2`) with an absolute-path org-mode link in `file2` to `file1` like this: `[[/home/me/notes/file1][link to file1]]`
2. From within emacs, move `file1` to a subdirectory
3. Ensure the `file2` buffer is up-to-date by either closing and reopining the buffer or running `revert-buffer`
4. Observe that the link to `file1` in `file2` is no longer an absolute-path link and is instead now a relative-path link (`[[subdirectory/file1][link to file1]]`)

#### Backtrace

n/a

#### Expected Results

When moving a file, absolute-path org-mode links to that file should remain absolute-path links.

#### Actual Results

When moving a file, absolute-path org-mode links to that file are converted to relative-path links.

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
 of 2020-08-26
- Framework: Spacemacs
- Org: Org mode version 9.4 (9.4-17-g9a6689-elpaplus @ /home/matt/.emacs.d/elpa/27.1/develop/org-plus-contrib-20201005/)
- Org-roam: 1.2.2
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/56c47fb

**Comment by oatmealm** [comment]
I see something that might be related. When I move a file which contains links to a subdirectory inside  of org-roam main directory, all the links in it messed up. Instead of a link I see a broken link with the path and name file partially expanded.
