### ISSUE TITLE
Choose linking method: path to file or org-ID

### ISSUE THREAD

**Issue by tea4or2wo** [org-roam/org-roam#1235]
### Brief Abstract

#1091 allows one to link files through IDs if file has an ID (files can have properties drawer such as any header from Org 9.4). There should be a variable controlling this behavior if path to file is preferred for linking but some files have attachments and, therefore, an ID assigned for retrieving their attachment.

### Long Description

I personally use `<%Y%m%d%H%M%S>` filenames as unique identifiers for files and I don't want link to file `20201122231232.org` using ID instead of path if file `20201122231232.org` has an attachment.

### Proposed Implementation (if any)

The idea would be to implement a new variable or to redesign `org-roam-link-file-path-type` to choose preferred linking method between `ID` and `org-roam-link-file-path-type` values.

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
Set `org-roam-prefer-id-links` to `nil` for this behaviour.
