### ISSUE TITLE
Autocomplete for org-roam file with name similar to existing

### ISSUE THREAD

**Issue by gloryVine** [org-roam/org-roam#1237]
### Description
I want to create a note with a title similar to an existing one. When I type the name of the new note with org-roam-insert or org-roam-find, then hitting Enter will open the existing similar note instead of creating a new one.
Is there some other key(-combination) I can use to create the new note?

#### Steps to Reproduce
Make a note called 'irreducible' and save it. Then try to create a new one called 'reducible' with org-roam-insert or org-roam-find.

#### Expected Results

Create new note.

#### Actual Results

Opens old note.

**Comment by jethrokuan** [comment]
The key to use depends on your completion framework.

See https://www.orgroam.com/manual/How-do-I-create-a-note-whose-title-already-matches-one-of-the-candidates_003f.html#How-do-I-create-a-note-whose-title-already-matches-one-of-the-candidates_003f

**Comment by gerrywastaken** [comment]
The link provided by @jethrokuan is outdated and there's unfortunately no "301 Moved Permanently" so here is the link for others ending up here:
https://www.orgroam.com/manual.html#How-do-I-create-a-note-whose-title-already-matches-one-of-the-candidates_003f
