### ISSUE TITLE
Documentation: Spacemacs Install?

### ISSUE THREAD

**Issue by jrmiller82** [org-roam/org-roam#1248]
I'm trying to install on spacemacs; I keep seeing references to instructions on readthedocs but every link seems to 404. I also don't see any spacemacs instructions on orgroam.com. Help? Thanks!

**Comment by jethrokuan** [comment]
This sort of documentation really belongs in the distros themselves. I see a snippet of it here:

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+emacs/org/README.org#org-roam-support

I suppose that's how you install it in Spacemacs.
