### ISSUE TITLE
"wrong-type-argument commandp org-roam-store-link"

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [org-roam/org-roam#1249]
# The problem

Whenever I try to store a link (`C-c n l)`, I get a `wrong-type-argument` error with the following backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument commandp org-roam-store-link)
  call-interactively(org-roam-store-link nil nil)
  command-execute(org-roam-store-
```

(And no `PROPERTIES` data is added to the file.)

# My environment

I was using NixOS 20.03 until this week, when I installed 20.09 from scratch. In 20.03 I had installed `org-roam` procedurally using `package-list-packages`, but this time I instead simply added "org-roam" to the package list in my Nix config. I copied the repository and the `.db` file from my previous system. 

I had also copied the `.emacs.d/elpa/org-roam` folder over. However, another issue here indicates that someone who was getting a similar type error (from `org-roam-find-file`) solved it by deleting that `org-roam` folder, so I tried doing that. It didn't help.

**Comment by kisaragi-hiu** [comment]
[The version on Nix (20200818.816)](https://search.nixos.org/packages?channel=20.09&show=emacs26Packages.org-roam&from=0&size=30&sort=relevance&query=org-roam) is outdated. Newer versions shouldn't have this issue, as `org-roam-store-link` has been removed in 93d8c477fe1800a26a41d60e6fbec56e29ab9894, which was released with org-roam 1.2.2.

**Comment by jethrokuan** [comment]
If you're on Nix and want to use it to manage packages from MELPA, please use https://github.com/nix-community/emacs-overlay

The Emacs packages in Nixpkgs are very outdated, and this overlay works well.

**Comment by JeffreyBenjaminBrown** [comment]
Awesome, thanks!

I once tried for a day to understand overlays. My head fell off and crumbled into dust, it was bad. Is there an example online of a full NixOS configuration that uses the Emacs overlay?

**Comment by JeffreyBenjaminBrown** [comment]
> `org-roam-store-link` has been removed in [93d8c47](https://github.com/org-roam/org-roam/commit/93d8c477fe1800a26a41d60e6fbec56e29ab9894)

What's it been replaced with? I see this at the top of the link you mention:

```
This is unnecessary. Org provides `org-id-store-link` instead for this
purpose. Instead, we advice `org-id-new`, to queue the file for a DB
update if an ID was created.
```

but I don't understand how to use it. Before, when I ran `org-roam-store-link`, it would both add some PROPERTIES data to the header under point, and add the ID it just created to some kind of queue, so that then next time I ran `org-insert-link` it would be among the options. If I run `org-id-store-link` it only does the first of those two things, and if I run `org-id-new` nothing happens.

**Comment by jethrokuan** [comment]
> Is there an example online of a full NixOS configuration that uses the Emacs overlay?

Here is my `home.nix`, it's just a matter of adding the overlay as per the README:

https://github.com/jethrokuan/nix-config/blob/e64cac3c0dfa271864cff532f40198e030ef6fc2/home.nix#L4-L8

> If I run org-id-store-link it only does the first of those two things, and if I run org-id-new nothing happens.

Hmm I'm seeing this too, feels like a bug in Org (I'm on 9.4). I have:

```
(setq org-id-link-to-org-use-id t)
```

in my config, so calling `org-store-link` creates an ID link for me which is available in `org-insert-link`.

**Comment by JeffreyBenjaminBrown** [comment]
I got it working! Your overlay passage worked like a charm! (Once I added sqlite to my list of installed packages.)

But I liked the old link behavior better :( It used to create PROPERTIES data containing a UUID. That meant even if I edit the header -- I edit headers frequently! -- links to it would keep working. Now they'll break.

But I guess this is a problem with org, not org-roam, right?

**Comment by jethrokuan** [comment]
The UUIDs are still created if you set

(setq org-id-link-to-org-use-id t)

**Comment by JeffreyBenjaminBrown** [comment]
I had set that. But, uh, now it's creating UUIDs like you describe. I didn't change anything, just restarted the computer. Oh well. I'll just hope it keeps doing that.

Thanks, Jethro!

**Comment by JeffreyBenjaminBrown** [comment]
Awwww yiss!
