### ISSUE TITLE
Org-Roam cannot parse `#foo` tag syntax

### ISSUE THREAD

**Issue by tea4or2wo** [org-roam/org-roam#1254]
### Description

I would like to use `#foo` and `##bar` tags for full-text search such as described in [here](https://zettelkasten.de/posts/three-layers-structure-zettelkasten/).

`#foo` tag is not processed by OR:  `(org-roam): Failed to parse tags for buffer: /home/2020-11-11_12-18.org. Skipping`

`##bar` is correctly processed by OR (although a weird `,bar` appearance in mini-buffer when calling `org-roam-find-file`)

I suppose #1185 (OR conversion to `:PROPERTIES:` drawer syntax) would be a long-term solution.

#### Steps to Reproduce

Example:

1. Run `org-roam-find-file` `file.org`
2. add `#foo` tag to `file.org`
3. wait for `org-roam-db-build-cache`

#### Expected Results

File with `#foo` tag is processed by Org-Roam.

#### Actual Results

File with `#foo` tag is skipped by Org-Roam.

### Environment

- Emacs: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2019-09-05
- Framework: N/A
- Org: Org mode version 9.4
- Org-roam: 1.2.2

- Org-roam commit: https://github.com/org-roam/org-roam/commit/c6797cbd755befb9c124a63f8f61d46b1bc5a24e

**Comment by jethrokuan** [comment]
That's the comment character in Org, so it's no surprise it failed.

To add the `#foo` tag, wrap it in quotes:

```
#+roam_tags: "#foo"
```
