### ISSUE TITLE
Unlinked references do not display text when the note has spaces

### ISSUE THREAD

**Issue by lytex** [org-roam/org-roam#1255]
### Description
See #1256 
I have a org-roam file with title e.g. "inbox" which is referenced in a org file named "Getting Things Done.org". Opening org-roam unlinked refs gives a sed error when parsing the file contents, because the shell splits by each space

```
* Unlinked References
- [[file:/home/julian/org/roam/Getting Things Done.org::588:28][[588:28] Getting Things Done]] :: sed: can't read /home/julian/org/roam/Getting: No such file or directory
sed: can't read Things: No such file or directory
sed: can't read Done.org: No such file or directory
```

#### Steps to Reproduce

1. Load Emacs
2. Create first a org-roam file named "inbox"
3. Create a second file with spaces on its filename and write "inbox" in it
4. Call `org-roam-unlinked-references` from the first file

#### Backtrace
```
* Unlinked References
- [[file:/home/julian/org/roam/Getting Things Done.org::588:28][[588:28] Getting Things Done]] :: sed: can't read /home/julian/org/roam/Getting: No such file or directory
sed: can't read Things: No such file or directory
sed: can't read Done.org: No such file or directory
```

**Comment by jethrokuan** [comment]
Thanks! Closed with #1256
