### ISSUE TITLE
emacs hangs when opening backlink buffer on a file that has a backlinked file that contains a file id

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam#1266]
### Description
emacs hangs when opening backlink buffer on a file with backlink to a file with a file id. saving a file with a file id also sometimes hangs.

#### Steps to Reproduce
1. create the following files
file_1.org
```
:PROPERTIES:
:ID:       b0f991c1-fc99-40c5-83eb-6dc2acf3753f
:END:
#+title:file 1
[[https://google.com/fastbee]]
```

file_2.org
```
#+title:file 2
#+roam_key: https://google.com/fastbee
```
2. open file_2.org

#### Expected Results
emacs doesn't hang.

#### Actual Results
emacs hangs.
after a (keyboard-quit), re-opening the same file doesn't cause emacs to hang. The reason is because it opens the backlinked file. The issue repeats if the backlinked file is closed and the steps above are repeated.

### Environment

- Org: Org mode version 9.4 (9.4-31-g49f4c3-elpaplus @ ~/spacemacs/elpa/develop/org-plus-contrib-20201109/)
- Org-roam: 1.2.2

**Comment by jethrokuan** [comment]
```
#+roam_key: https://google.com
```

you're missing a space here.

**Comment by natask** [comment]
My bad. I was trying to write up a minimal example. The file I am dealing with does have correct key setup.

It doesn't happen on all files with a ref backlinks. 

I checked a bit more and found that the issue stems from having file level ids.
I have updated the issue post with this info.

**Comment by natask** [comment]
I upgraded to the latest org-roam commit and issue solved. 

closing.
