### ISSUE TITLE
Roam DB not updated after saving note added with :no-save template

### ISSUE THREAD

**Issue by czikus** [org-roam/org-roam#1276]
### Description

When adding notes using the following template:

```
("n" "Note" plain #'org-roam-capture--get-point
           "%?"
           :file-name "Notes/${slug}"
           :head "#+TITLE:${title}\n#+DATE:%u\n"
           :no-save t :immediate-finish t :jump-to-captured t)
```

and saving the file, the newly added note is not added to the DB.

#### Steps to Reproduce

1. Load Emacs
2. Add a note using a template with :no-save t option
3. Save the new note
3. Run `org-roam-find-file`

#### Expected Results

The newly added note is present in the list. However, when the new note is never saved, it is also never added to the DB.

#### Actual Results

The newly added note is missing until `org-roam-db-build-cache` is run.

### Environment

- Emacs: GNU Emacs 27.1 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
 of 2020-09-08
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /home/user/.emacs.d/.local/straight/build-27.1/org-mode/)
- Org-roam: 1.2.3

**Comment by jethrokuan** [comment]
> However, when the new note is never saved, it is also never added to the DB.

This is expected behaviour though. The note shouldn't be added into the database until it is physically present as a file.

> and saving the file, the newly added note is not added to the DB.

This may be related to #1280 . The database is updated on idle timer by default. To change this, set `org-roam-db-update-method` to `'immediate`

**Comment by zaeph** [comment]
Could you let us know if that works for you?  If you have a particular workflow which makes use of `:no-save`, we might be able to suggest something.  As it stands, I agree with @jethrokuan that this is intended behaviour.

**Comment by czikus** [comment]
> This is expected behaviour though. The note shouldn't be added into the database until it is physically present as a file.
Yes, I agree. That's why I added this statement to the Expected Results section :)

> > and saving the file, the newly added note is not added to the DB.
> 
> This may be related to #1280 . The database is updated on idle timer by default. To change this, set `org-roam-db-update-method` to `'immediate`
So, interestingly setting `org-roam-db-update-method` to `immediate` solves the issue. However, I would expect that setting it to `idle-timer` should still update the db when a file is saved after `org-roam-db-update-idle-seconds` of idle time. This does not seem to happen.

**Comment by czikus** [comment]
> Could you let us know if that works for you? If you have a particular workflow which makes use of `:no-save`, we might be able to suggest something. As it stands, I agree with @jethrokuan that this is intended behaviour.

My workflow is simple. I'm using the following capture options: `:no-save t :immediate-finish t :jump-to-captured t`. My goal is to use the templates to simply create a new file and immediately jump to it. The file would then contain the initial template content. If this was done by mistake, I would like to have the option to not save the file. The file should then be added to the db on save.

**Comment by jethrokuan** [comment]
https://github.com/org-roam/org-roam/commit/a9fd6c0fc71d579357088adc66abd810817f927b should've fixed the behaviour you're seeing. Feel free to reopen if it doesn't.
