### ISSUE TITLE
Change the behaviour of prefix-key in `org-roam-insert`

### ISSUE THREAD

**Issue by mohkale** [org-roam/org-roam#1278]
### Brief Abstract
At the moment the prefix-argument for `org-roam-insert` is to downcase the entry being inserted. I believe it would be more useful/convenient if the prefix caused org-roam to update the db.

### Long Description
`org-roam-insert` is the command org-roam recommends for inserting links to org-documents. I don't believe the current application of the prefix argument for this command is very useful (mostly because all of my org-roam files are downcased anyways). I believe a better application of it would be to force the roam database to be updated before prompting you for a file to insert a link to. 

PR #1032 added an idle update mechanism. This makes it so that the org-roam DB is only updated after you stop writing anything for a few seconds (this is customizable). The issue in my case is that I'm often sporadically making new notes and org-roam doesn't offer them to me as possible completion targets in `org-roam-insert` until after it updates the DB. This means in the middle of writing I have to stop for a few seconds if I want to link to my new notes. This breaks my concentration.

For example:
1. `org-roam-find-file foo`
2. write some stuff
3. `org-roam-find-file bar`
4. write some stuff
5. `org-roam-insert-link foo`.... foo isn't in the database yet.
6. wait 2 seconds
7. wait 1-2 seconds for database write
8. `org-roam-insert-link foo`

I want to replace step 6-8 with: `C-g` and `C-u org-roam-insert-link foo`. The `C-u` triggers the database update so I don't have to stop writing.

**NOTE**: Another reason I'd prefer this behaviour is that it would match `ivy-bibtex`. If you edit your bib file outside of emacs and then try to reference a new entry ivy-bibtex will probably not show it. However if you supply a prefix arg ivy-bibtex will reload the bib-db and show it. Its become a habit of mine to rerun commands with unexpected behaviour with a prefix argument to fix them.

**NOTE**: While writing this issue I noticed #1264 made the delay itself optional so I think I might disable it altogether. I still feel this should be a feature though.

Thoughts?

### Please check the following:
- [x] No similar feature requests

**Comment by zaeph** [comment]
I was also not enthused by the idle mechanism, and #1264 was a step in the right direction.

I agree that the current first-arg for `org-roam-insert` is not very useful, but I had other plans in mind than what you're currently suggesting.

We'll consider it when we get to reworking the linking UX.

Thanks!

**Comment by mohkale** [comment]
@zaeph 

I'm interested in what you're plans are. Could you elaborate?

**Comment by zaeph** [comment]
You can browse some of them under the tag [linking-ux](https://github.com/org-roam/org-roam/labels/linking-ux).

We don't have a document detailing our plans yet, but it's something I'm hoping to address in the coming months.

**Comment by mohkale** [comment]
This probably isn't the right issue for this, but I'd also like if there was more actions for the ivy based `org-link-insert`.

For example I have a note file titled `frequency-domain-graph` but a lot of the time I'd like to insert it as `frequency-domain`. Org links have this annoying issue (on my config with evil) where if you insert the link and then try to remove the last character or word it ends up removing the `]]` at the end of the link. It'd be nice if there was an ivy-action which prompted you for the text the link will be inserted as.
