### ISSUE TITLE
enabling org roam update on idle timer requires setting org-roam-db-file-update-timer unnecessarly

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam#1280]
### Description
To enable org roam's feature to update, org-roam-db-file-update-timer needs to be set unnecessarily.
#### Steps to Reproduce
1. use the following as use-package
``` elisp
    (use-package org-roam
      :ensure t
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-db-update-method 'idle-timer)
      (org-roam-db-update-idle-seconds 0.5))
```
#### Expected Results
org roam updates on 0.5 second idle timer.

#### Actual Results
org roam doesn't update on timer at all.

### Solution
remove  org-roam-db-file-update-timer from
``` elisp
(if (and org-roam-db-file-update-timer
             (eq org-roam-db-update-method 'idle-timer))
```
in org-roam-mode.

or use
``` elisp
    (use-package org-roam
      :ensure t
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-db-update-method 'idle-timer)
      (org-roam-db-file-update-timer t)
      (org-roam-db-update-idle-seconds 0.5))
```

**Comment by jethrokuan** [comment]
Oof it should be `(and (not org-roam-db-file-update-timer`

**Comment by natask** [comment]
it maybe worth naming it something like `org-roam-db-filt-update-timer-enabled` or adding to its documentation that it is used to make sure there aren't duplicate timers for org-roam.

**Comment by jethrokuan** [comment]
That's not what it does. It contains the timer itself.

**Comment by natask** [comment]
@jehtrokuan then what is the point of checking that it has been set?

**Comment by jethrokuan** [comment]
so you spawn a maximum of one timer

**Comment by natask** [comment]
that is what I said as well. I didn't realize that it was used for that purpose until your first response to this thread. I think it should be made more explicit by adding documentation.

**Comment by jethrokuan** [comment]
Earlier I was pointing out that the rename of the variable does not make sense. The documentation for the variable states exactly what it does:

```
Timer for updating the database when dirty.
```

The fact that there is a nil check on the variable doesn't belong in the documentation of the variable.

**Comment by natask** [comment]
I understand what you mean. My point is that it wasn't clear to me why the variable was being used here. Given that the variable is only used for the purpose of limiting the number of timers within the whole code base and from a code maintenance and understandability point of view, It makes sense to me to clarify the usage either by renaming the variable or adding documentation. It is also possible to create another variable or a function that returns the necessary information for its usage here.

Anyhow, It is a very minor thing.

**Comment by d12frosted** [comment]
I think that current name and documentation is already clear. It is a common idiom in Emacs to store result of `run-with-idle-timer` and `run-with-timer` in variable named `xxx-timer`, because returned object is called timer. Aside from limiting amount of concurent timers, it also gives ability to stop the timer. Since the timer starts in `org-roam-mode` this check is mandatory there as minor mode body is executed each time it is enabled.
