### ISSUE TITLE
Option to only show backlinks buffer ("sidebar") on command 

### ISSUE THREAD

**Issue by dangirsh** [org-roam/org-roam#1286]
I'm loving the much snappier org-roam, thanks!

I feel like in past versions, I only had to close the sidebar once to avoid it re-appearing. Now it persistently re-appears. It would be great to add an option to have it hidden by default.

In many of my use-cases, the backlinks buffer is a distraction, so it's annoying to always have to manually hide it.

**Comment by jethrokuan** [comment]
Org-roam does not open the side-buffer for you, that's a Doom thing.

https://github.com/hlissner/doom-emacs/blob/aa02dc14a4f24fdf4e49e6572c56f78535a0bed2/modules/lang/org/contrib/roam.el#L65-L76

```
(setq +org-roam-open-buffer-on-find-file nil)
```

will turn it off.
