### ISSUE TITLE
Support YAML front matter with tags in org-roam

### ISSUE THREAD

**Issue by lieuzhenghong** [org-roam/org-roam#1296]
### Brief Abstract

I'd like org-roam to support tags, so I can do something like YAML front matter:

```
---
title: Something
date: 2020-11-05
layout: base
tags:
    - public
    - diary
---
```
Leo Vivier told me to send in a feature request.

### Long Description

> Leo Vivier Nov 11th at 15:33
That's an interesting structure for specifying tags.  With org-mode, we're stuck with what's in core, but I like this amount of flexibility that is offered by that implementation of md.  That being said, the different flavours of md sort-of nullifies this edge, but still, credit where credit is due.

Gustav on Slack said that the org mode implementation would look something like this:

```
:PROPERTIES:
:title:  My experience interviewing for OGP
:date:   2020-11-05
:layout: base
:tags:   public
:tags+:  diary
:END:
```

### Proposed Implementation (if any)

From Gustav on Slack:

> Org mode core supports property drawers, also at the file level since 9.4. The yaml frontmatter isn't too far of from that. Also, properties have a syntax to allow multiple rows as well, if needed for lists. With the :property+: syntax if I remember correctly. Just sayin' ;)

### Please check the following:

- [ X] No similar feature requests

**Comment by jethrokuan** [comment]
```
:PROPERTIES:
:title:  My experience interviewing for OGP
:date:   2020-11-05
:layout: base
:roam_tags:   public
:roam_tags+:  diary
:END:
```

should work with #1353.
