### ISSUE TITLE
when-let argument 1 vs 2

### ISSUE THREAD

**Issue by AndyChenW** [org-roam/org-roam#1298]
#### Steps to Reproduce

1. Load Emacs 27.0.50

#### Backtrace
![image](https://user-images.githubusercontent.com/2155462/99425088-5faf4d00-293d-11eb-8437-9567dc988e18.png)

### Environment

emacs 27.0.50  
Mac

Seem's like the bug is here: 
https://github.com/org-roam/org-roam/blob/master/org-roam.el#L367

I am quite confusing about the Macro when-let in the org-roam, if I change the code to something like this:

> (defun org-roam--org-roam-file-p (&optional file)
  "Return t if FILE is part of Org-roam system, nil otherwise.
If FILE is not specified, use the current buffer's file-path."
  (when-let (path (or file
  		      org-roam-file-name
  		      (-> (buffer-base-buffer)
  			  (buffer-file-name))))
    (save-match-data
      (and
       (org-roam--org-file-p path)
       (not (and org-roam-file-exclude-regexp
  		 (string-match-p org-roam-file-exclude-regexp path)))
       (f-descendant-of-p path (expand-file-name org-roam-directory))))))

which follows the Macro define here:
http://www.lispworks.com/documentation/lw60/LW/html/lw-943.htm

It works fine!

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by myshevchuk** [comment]
I cannot reproduce this. 

A possible reason is the `when-let` macro was redefined by the user or a package. See for example https://github.com/clojure-emacs/cider/issues/1349

Perhaps `when-let*` could be used instead of `when-let`? The former is less likely to be redefined by some rogue package.

**Comment by AndyChenW** [comment]
YES, it's my slime package error. thanks for your help :)
