### ISSUE TITLE
Extend `org-roam-link--get-headlines` to include all headlines of the DB

### ISSUE THREAD

**Issue by yangchenyun** [org-roam/org-roam#1299]
### Brief Abstract
In the [Roam Research UI](https://roamresearch.com/), the auto-completion for headlines(blocks in roam's UI) is global, and it is handy to create headline/block links.

### Proposed Implementation (if any)
Extend `org-roam-link--get-headlines` to have`org-roam-link--global-get-headlines` to return all headings in the database.

**Comment by randomwangran** [comment]
If you do not have too many files, breaking the big org file into small files could walk around this issue. You may check this out: https://org-roam.discourse.group/t/creating-an-org-roam-note-from-an-existing-headline/978
