### ISSUE TITLE
org-roam-buffer not updated after spacemacs/alternate-buffer call

### ISSUE THREAD

**Issue by leezu** [org-roam/org-roam#1305]
### Description
Switching between two org-roam buffers via `spacemacs/alternate-buffer` does not update the org-roam buffer.

One workaround is to manually re-add the `(add-hook 'post-command-hook #'org-roam-buffer--update-maybe nil t)` hook to the respective org-roam buffers, which is removed for all org-roam buffers in the minor mode implementation:

https://github.com/org-roam/org-roam/blob/d70198bba9f78c00a87f67ff9eb8846f9b0ebba3/org-roam.el#L1516-L1521

Could you elaborate why the local update hook is disabled by default for all org-roam buffers?

For reference, implementation of  `spacemacs/alternate-buffer` 
https://github.com/syl20bnr/spacemacs/blob/28a4baeea4abc2c55f728355ba2666e77ed78118/core/core-funcs.el#L319-L342

**Comment by TS-CUBED** [comment]
Confirm this issue and that it is fixed by commenting the line

`     (remove-hook 'post-command-hook #'org-roam-buffer--update-maybe t) `

in `org-roam.el`

**Comment by jethrokuan** [comment]
> Could you elaborate why the local update hook is disabled by default for all org-roam buffers?

It is only disabled when `org-roam-mode` is turned off, seems like a bug in spacemacs.

**Comment by TS-CUBED** [comment]
Hmm, I'm don't really speak lisp, 

> > Could you elaborate why the local update hook is disabled by default for all org-roam buffers?
> 
> It is only disabled when `org-roam-mode` is turned off, seems like a bug in spacemacs.

I don't really speak lisp, but it seems that the hook is removed at the end of this block, but never added at the beginning of the autoload block. If spacemacs toggles in and out of org-roam-mode a lot, then that may explain the error.

If I add the line

```
(add-hook 'post-command-hook #'org-roam-buffer--update-maybe t)
```
to org-roam.el

in the block below (starting from line 1463 in org-roam-20201121.842 on elpa - added line is on 1493):

```
;;;###autoload
(define-minor-mode org-roam-mode
  "Minor mode for Org-roam.

This mode sets up several hooks, to ensure that the cache is updated on file
changes, renames and deletes. It is also in charge of graceful termination of
the database connection.

When called interactively, toggle `org-roam-mode'. with prefix
ARG, enable `org-roam-mode' if ARG is positive, otherwise disable
it.

When called from Lisp, enable `org-roam-mode' if ARG is omitted,
nil, or positive. If ARG is `toggle', toggle `org-roam-mode'.
Otherwise, behave as if called interactively."
  :lighter " Org-roam"
  :keymap  (let ((map (make-sparse-keymap)))
             map)
  :group 'org-roam
  :require 'org-roam
  :global t
  (cond
   (org-roam-mode
    (unless (or (and (bound-and-true-p emacsql-sqlite3-executable)
                     (file-executable-p emacsql-sqlite3-executable))
                (executable-find "sqlite3"))
      (lwarn '(org-roam) :error "Cannot find executable 'sqlite3'. \
Ensure it is installed and can be found within `exec-path'. \
M-x info for more information at Org-roam > Installation > Post-Installation Tasks."))
    (add-to-list 'org-execute-file-search-functions 'org-roam--execute-file-row-col)
    (add-hook 'post-command-hook #'org-roam-buffer--update-maybe t)
    (add-hook 'find-file-hook #'org-roam--find-file-hook-function)
    (add-hook 'kill-emacs-hook #'org-roam-db--close-all)
    (add-hook 'org-open-at-point-functions #'org-roam-open-id-at-point)
    (when (and (not org-roam-db-file-update-timer)
               (eq org-roam-db-update-method 'idle-timer))
        (setq org-roam-db-file-update-timer (run-with-idle-timer org-roam-db-update-idle-seconds t #'org-roam-db-update-cache-on-timer)))
    (advice-add 'rename-file :after #'org-roam--rename-file-advice)
    (advice-add 'delete-file :before #'org-roam--delete-file-advice)
    (advice-add 'org-id-new :after #'org-roam--id-new-advice)
    (when (fboundp 'org-link-set-parameters)
      (org-link-set-parameters "file" :face 'org-roam--file-link-face)
      (org-link-set-parameters "id" :face 'org-roam--id-link-face))
    (org-roam-db-build-cache))
   (t
    (setq org-execute-file-search-functions (delete 'org-roam--execute-file-row-col org-execute-file-search-functions))
    (remove-hook 'find-file-hook #'org-roam--find-file-hook-function)
    (remove-hook 'kill-emacs-hook #'org-roam-db--close-all)
    (remove-hook 'org-open-at-point-functions #'org-roam-open-id-at-point)
    (when org-roam-db-file-update-timer
      (cancel-timer org-roam-db-file-update-timer))
    (advice-remove 'rename-file #'org-roam--rename-file-advice)
    (advice-remove 'delete-file #'org-roam--delete-file-advice)
    (advice-remove 'org-id-new #'org-roam--id-new-advice)
    (when (fboundp 'org-link-set-parameters)
      (dolist (face '("file" "id"))
        (org-link-set-parameters face :face 'org-link)))
    (org-roam-db--close-all)
    ;; Disable local hooks for all org-roam buffers
    (dolist (buf (org-roam--get-roam-buffers))
      (with-current-buffer buf
        (remove-hook 'post-command-hook #'org-roam-buffer--update-maybe t)
        (remove-hook 'before-save-hook #'org-roam-link--replace-link-on-save t)
        (remove-hook 'after-save-hook #'org-roam-db-update t))))))
```

then it works on spacemacs.

**Comment by TS-CUBED** [comment]
created a PR, please check if this fix will break other functionality. I don't see it doing that, but as I said, I don't really speak Lisp.

**Comment by jethrokuan** [comment]
#1321 closes this, but someone should really figure out why `org-roam-mode` is being toggled, it's not supposed to be the case.
