### ISSUE TITLE
org-roam-graph calls (file-name-directory nil) which throws (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by sornas** [org-roam/org-roam#1310]
### Description

Calling `M-x org-roam-graph` errors with `(wrong-type-argument stringp nil)`. I'm relatively new to emacs and normally use Doom so I hope I did the reproducing correct.

#### Steps to Reproduce

1. `$ emacs -Q`
2. Paste and evaluate the following.
```
(require 'package)
(setq package-load-list
      '((dash t)
	(f t)
	(s t)
	(emacsql t)
	(emacsql-sqlite3 t)
	(org-roam t)))
(package-initialize)
```
3. `M-x toggle-debug-on-error RET`
4. `M-x org-roam-graph RET`

I get the same results after `M-x org-roam-find-file` and opening a file.

#### Backtrace

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  org-roam-graph--dot([:select [file title] :from titles :group :by file])
  org-roam-graph--build(nil org-roam-graph--open)
  org-roam-graph(nil)
  funcall-interactively(org-roam-graph nil)
  call-interactively(org-roam-graph record nil)
  command-execute(org-roam-graph record)
  execute-extended-command(nil "org-roam-graph" "org-roam-graph")
  funcall-interactively(execute-extended-command nil "org-roam-graph" "org-roam-graph")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

#### Expected Results

Graph showing.

#### Actual Results

Above backtrace, nothing else.

### Environment

```
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
- Framework: None
- Org: Org mode version 9.3 (release_9.3 @ /usr/share/emacs/27.1/lisp/org/)
- Org-roam: 1.2.3
```
I am not aware of the commit hash.

This is running on Arch Linux. I assume something's wonky with my system but I don't know how to proceed.

**Comment by vritser** [comment]
same error

**Comment by ladykosha** [comment]
same error

**Comment by sornas** [comment]
Thanks!
