### ISSUE TITLE
placement of the org-roam.db

### ISSUE THREAD

**Issue by algon-ns** [org-roam/org-roam#1313]
### Description
Defult is the org-roam.db placed in the ~/.emacs.d directory, using the "org-roam-dp-location" set to the org directory does not have any effect.
I has by now set emacs custonimze to the rigt place, and it works.
#### Steps to Reproduce

just load org-roam, and create the database

### Environment
- Emacs: GNU Emacs 28.0.50 (build 4, x86_64-apple-darwin16.7.0, NS appkit-1504.84 Version 10.12.6 (Build 16G2136))
 of 2020-11-02
- Framework: Ownconfiguration
- Org: Org mode version 9.4 (release_9.4-131-g1a480e @ /Users/niels/.emacs.d/straight/build/org-agenda/)
- Org-roam: 1.2.3
- macOS High Sierra (10.12.6) ; iMac (27-inch, Mid 2011) ; iMac (27-inch, Mid 2011) ; 16 GB 1333 MHz DDR3

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
The value needs to be set before the database connection is created, i.e. before the loading of `org-roam-mode`.

**Comment by algon-ns** [comment]
thanks, it works
 <applewebdata://6C5F175A-C3BB-4859-85A7-5D7B7A04D411>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45 4052 2789>+45 4052 2789 niels@algon.dk <mailto:niels@algon.dk>
