### ISSUE TITLE
org-roam-graph (error or user error)

### ISSUE THREAD

**Issue by algon-ns** [org-roam/org-roam#1316]
### Description
unexpected (new) error in org-roam-graph

#### Steps to Reproduce

M-x org-roam-graph

#### Backtrace

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  org-roam-graph--dot([:select [file title] :from titles :group :by file])
  org-roam-graph--build(nil org-roam-graph--open)
  org-roam-graph(nil)
  funcall-interactively(org-roam-graph nil)
  call-interactively(org-roam-graph nil nil)
  command-execute(org-roam-graph)

#### Expected Results

a graph

#### Actual Results

wrong-type-argument stringp nil

### Environment
- Emacs: GNU Emacs 28.0.50 (build 4, x86_64-apple-darwin16.7.0, NS appkit-1504.84 Version 10.12.6 (Build 16G2136))
 of 2020-11-02
- Framework: https://github.com/algon-ns/nec.emacs.d
- Org: Org mode version 9.4 (release_9.4-131-g1a480e @ /Users/niels/.emacs.d/straight/build/org-agenda/)
- Org-roam: 1.2.3
- iMac (27-inch, Mid 2011)
- macOS Sierra version 10.12.6 (16G2136)

;;Set place of database (ns 20. november 2020)
(setq org-roam-db-location "/Users/niels/Dropbox/org/roam/org-roam.db")
  (use-package org-roam
    :straight t
    :hook
    (after-init . org-roam-mode)
;;    :custom
;;    (org-roam-directory "/Users/niels/Dropbox/org/roam")
    :bind (:map org-roam-mode-map
                (("C-c n l" . org-roam)
                 ("C-c n f" . org-roam-find-file)
                 ("C-c n j" . org-roam-jump-to-index)
                 ("C-c n b" . org-roam-switch-to-buffer)
                 ("C-c n g" . org-roam-graph))
      :map org-mode-map
      (("C-c n i" . org-roam-insert)))
    :config
    (setq org-roam-graph-node-extra-config '(("shape" . "ellipse")
                                             ("style" . "rounded,filled")
                                             ("fillcolor" . "#EFEFFF")
                                             ("color" . "#DEDEFF")
                                             ("fontcolor" . "#111111")))
    (setq org-roam-buffer-position 'left
          org-roam-buffer-width 0.25
          org-roam-index-file "index.org"
          org-roam-graph-extra-config '(("overlap" . "false"))
;;          org-roam-graph-exclude-matcher '("archive" "Beruf" "blog" "books" "init" "Journal" "regularly" "tasks" "work" "Einkaufen")
          org-roam-completion-system 'ivy))    
    

    (setq org-roam-directory "/Users/niels/Dropbox/org/roam/")
    (setq org-roam-graph-viewer nil)

    (setq org-roam-capture-templates `(("d" "default" plain #'org-roam-capture--get-point
                                              "%? "
                                                :file-name "%<%Y%m%d%H%M%S>-${slug}"
                                                :head "#+title: ${title}\n#+roam_key:  "
                                                :unnarrowed t)
                                         ("r" "ref" plain #'org-roam-capture--get-point
                                              "%?"
                                                :file-name "${slug}"
                                                :head "#+title: ${title}\n#+roam_key: ${ref}"
                                                :unnarrowed t)))
  (require 'org-roam-protocol)
#+end_src
=company-org-roam= provides completion for the links
#+begin_src emacs-lisp
(use-package company-org-roam
  :straight t
  :after company
  :config
  (push 'company-org-roam company-backends))
#+end_src
=org-roam-server= will start a web server on http://127.0.0.1:8080/ to see the nodes and their linking
#+begin_src emacs-lisp
(use-package org-roam-server
  :straight t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-export-inline-images t
        org-roam-server-authenticate nil
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by algon-ns** [comment]
Hello Jethro,
It has not worked, as org-roam does is not able to load without "org-roam-directory", as thes system thinks thar all my org files is in ~/.emacs.d.
Otherwise I can't figure out, where I set the default-directory....
with kind regards
Niels

**Comment by jethrokuan** [comment]
Your current configuration is fine, this was a bug in `org-roam`. You do not need to concern yourself with setting `default-directory` correctly.

The fix is to upgrade Org-roam to the latest commit, how to do that depends on how you have Org-roam installed.

**Comment by algon-ns** [comment]
Thanks, it’s working by now, by fork’ing org-roam/org-roam to my github algon-ns/org-roam….
so now I can use org-roam again…..


mvh
Niels
 <applewebdata://8BE755D8-3A02-4ACA-A9D3-FC92A86B7EA3>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45 4052 2789>+45 4052 2789 niels@algon.dk <mailto:niels@algon.dk>
