### ISSUE TITLE
Doubt about org-roam future behavior

### ISSUE THREAD

**Issue by lytex** [org-roam/org-roam#1317]
I'm using a certain behavior of org-roam, which I don't know if it's a known feature that will remain stable in the future.
Say you have a certain headline in a file named words.org with that structure:

```
* my heading
:PROPERTIES:
:GOAL: I want to be able to say [[file:something.org]]
:END:

:RELATED:
[[file:language.org]]
:END:
```

When showing the backlinks of language.org, this file words.org will appear, I suppose because the link it's on a drawer. However, when showing the backlinks of something.org, words.org will **not** be there, I suppose because it's is a property.

Is this expected org-roam behavior? Will it remain stable in the future?

**Comment by jethrokuan** [comment]
I don't know. This depends on whether Org's parser changes its behaviour.

Org-roam considers every link that Org considers a link. That seems to exclude property drawers.

If we do end up not using Org's official parser (e.g. using an external program for perf reasons), then this might change.

**Comment by lytex** [comment]
Thanks!

I will send a mail to the Org mailing list and link to the answer for future reference

**Comment by lytex** [comment]
Seems pretty stable, introduced back in 2012, no plans to change it

https://orgmode.org/list/87ft4y7yur.fsf@kyleam.com/
