### ISSUE TITLE
Option to have org roam buffer in separate frame

### ISSUE THREAD

**Issue by Whil-** [org-roam/org-roam#1322]
### Brief Abstract
The functionality for the org roam buffer is tied to it being visible as a sidebar, while I'd really like it to function also in other display settings.

### Long Description
I for example would like to have the option of it being open constantly in a separate frame. The issue with that at the moment is that it only refreshes when the sidebar also is active. If the org roam sidebar is closed the separate frame stops updating when switching active buffer.

This may be a minor nitpick, but I thought to add it here anyways as a feature request anyhow. It represents a 'grinding gear' for me personally but I haven't investigated if I'm alone with this feeling or not!

### Proposed Implementation (if any)
Potential solution would be to implement a `'frame` option for `org-roam-buffer-position`. Not sure if that is a _good_ solution though.

### Please check the following:

- [x] No similar feature requests (at least as I could see when scrolling through the issues-list and searching for frame.

**Comment by g4v4g4i** [comment]
I second that -- this would also fit my work-flow best.

**Comment by shlevy** [comment]
I'm ignorant of the implementation details here, but why should org-roam itself care where the buffer is? Can't it just keep the org-roam buffer up to date so long as it's open at all?

**Comment by jethrokuan** [comment]
I just tested and the buffer doesn't with another frame because a lot of the functions use window visibility, and that's frame dependent. It doesn't look simple to move to an implementation that is frame-independent, so I'm closing this. PR is otherwise welcome.
