### ISSUE TITLE
[Feature Request] Update side-buffer based on link under cursor

### ISSUE THREAD

**Issue by shombando** [org-roam/org-roam#1332]
### Brief Abstract
I would like for the side bar to update with the back-links for the linked page that is under my cursor (ideally in reverse chronological order) so I can quickly reference information/jog my memory.

### Long Description
In my work flow when I insert a link to an existing note I can visit the note and see the back-links in the side-buffer. However, this takes me out of my current scope and I have no mechanism to work on my current note while still being able to reference the related notes in the side-buffer. My only option is to visit the main link, then export the side buffer (with the back-links) into a new/scratch buffer, split windows to see that information, and finally return to the note I'm working on. This workflow can be significantly improved by being able to see the linked notes for the link under cursor (please see Extended Functionality request below).

### Proposed Implementation (if any)
None, will update if I'm able to grok how the side-buffer currently works.

### Please check the following:

- [x] No similar feature requests

---
Original feature request created without following template (sorry!)
### Motivation
As an user of org-roam I want the ability to see associated notes more seamlessly.

### ~Use case~ moved to: Long Description
~In my work flow when I insert a link to an existing note I can visit the note and see the back-links in the side-buffer. However, this takes me out of my current scope and I have no mechanism to work on my current note while still being able to reference the related notes in the side-buffer. My only option is to visit the main link, then export the side buffer (with the back-links) into a new/scratch buffer, split windows to see that information, and finally return to the note I'm working on.~

### ~Basic Functionality~ moved to: Brief Abstract
~I would like for the side bar to update with the back-links for the linked page that is under my cursor (ideally in reverse chronological order) so I can quickly reference information/jog my memory.~

### Extended Functionality 
- I would like the ability to freeze the sidebar with the back-links until freeze is toggled or I switch to another buffer.
- I would prefer to have the functionality scope to be exposed through variables so this function can be set globally, toggled per session, or toggled per buffer

I hope that I have articulated the feature request adequately, please ask for any clarifications. Thanks for suggesting I make a feature request.

**Comment by jethrokuan** [comment]
> I would like the ability to freeze the sidebar with the back-links until freeze is toggled or I switch to another buffer.

On master branch there are now two functions:

- `org-roam-buffer` launches a buffer for current node at point. This is frozen to the node.
- `org-roam-buffer-toggle` launches a buffer that tracks the node under cursor.

The combination of the two should help you achieve what you want.
