### ISSUE TITLE
Search for and link to subheadings

### ISSUE THREAD

**Issue by Jdude311** [org-roam/org-roam#1333]
Is there a way to search through subheadings? If not, can this be implemented?

**Comment by nobiot** [comment]
I can suggest some packages around `imenu`; e.g. `counsel-imenu` if you use Ivy as your completion framework. 
`consult-outline` is good if you use `selectrum`.

Here is an screen capture from `counsult-outline`. I am search for a headline that starts with an "o".
![image](https://user-images.githubusercontent.com/12507865/102690865-adeb9080-4208-11eb-947e-4572319ef7e5.png)

**Comment by jethrokuan** [comment]
You can use nodes in latest commit, that applies to headlines.
