### ISSUE TITLE
How to create a new note without having to write a filename?

### ISSUE THREAD

**Issue by in-in** [org-roam/org-roam#1334]
I want to create a new note, but instead `org-roam-find-file` forces me to come up with a filename. I absolutely do not care about the filename, I'm happy with the timestamp as the filename.

Is it possible to skip this step and go directly to the note?

**Comment by nobiot** [comment]
Depends on your completion framework. If you are using Ivy-mode, then `C-M-j` without entering any title will bring you to the capture screen with not title.
