### ISSUE TITLE
Generating and insert automatic index of files by tags/queries grouping

### ISSUE THREAD

**Issue by reyman** [org-roam/org-roam#1336]
### Brief Abstract

I search a little on the issue base,  but i don't found this feature.

I'm interested by generating an "indexed view" of `*.org` files based on  : 
- tags grouping, 
- query grouping (using/like org-ql for example)

For example, i want to maintain an index of pages related to :PROJECT: tag, or :HOME:, or :ANYCONCEPT: and inject this index anywhere in my org files.

The generated view would be inserted using some `#+begin / #+end` block like org-ql dynamic block of @alphapapa propose : https://www.reddit.com/r/orgmode/comments/jrh6k9/ann_orgql_dynamic_blocks_and_links/

In some way, this feature seems really similar to wikipedia explicit categorization, but in our way we choose to insert   : 
[https://en.wikipedia.org/wiki/Help:Categories](https://en.wikipedia.org/wiki/Help:Categories)

Also, this functionality is interesting during org export / publish process, generating as many index as user want in his website.

### Proposed Implementation (if any)

Using org-ql dynamic block to generate a view ?

**Comment by jethrokuan** [comment]
Not within the scope of Org-roam, but can be done by using the exposed `org-roam-db-query` interface in user-written functions.
