### ISSUE TITLE
Suggestion: Make it possible to ~~Strikethrough~~ text with double '~~'

### ISSUE THREAD

**Issue by marek-lach** [org-roam/org-roam#1338]
It is how Obsidian.md does it, it may be useful to have a similar functionality that's already familiar...

**Comment by PreciousPudding** [comment]
@marek-lach Strikethrough? Wouldn't you just strikethrough normally in org-mode with +EXAMPLE+

**Comment by marek-lach** [comment]
> @marek-lach Strikethrough? Wouldn't you just strikethrough normally in org-mode with +EXAMPLE+

Oh! I get how it works now! Sorry. And thanks!
