### ISSUE TITLE
respect org-link-frame-setup when opening links

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam#1340]
### Brief Abstract
use the variable ` org-link-frame-setup` to determine if links in which window/frame links should be opened.
### Long Description
org mode's default link opener can be made to open links in the same window, other window or frame by setting `org-link-frame-setup`. It would be convenient if org roam respected the variable. Change the behavior of `org-roam-id-at-point` and `org-roam-at-point` through `org-link-frame-setup` such that org-roam  open links in the same window, other window or frame. This is somewhat tied with #807 and  #790.

### Please check the following:

- [X] No similar feature requests

**Comment by natask** [comment]
For now, I am removing 
  https://github.com/org-roam/org-roam/blob/15d864a500d90c9dc2e16d888e93343528ec3941/org-roam.el#L1484
so that org opens links normally. This doesn't use org roams database for ids but I haven't had issues because all my files are found within org-id's internal database.

**Comment by jethrokuan** [comment]
This will all be addressed in the side-buffer revamp. The window management system is terrible now because the side-buffer is a side-buffer in Emacs terms, and there are a lot of restrictions that come with that.

**Comment by rtrppl** [comment]
I am not entirely sure the original post was about the side-buffer. I have the same issue in regular notes and asked around in the forums. @nobiot replied:


> If so, this looks like something the Org-roam project / Jethro can look at.
> Here is a result of my quick look. If it looks reasonable, you might like to report it to the project on GitHub to request a change.
> 
> Org-roam wraps the default `org-id-open` with its own `org-roam-id-open`.
> 
> `org-id-open` looks at `org-link-frame-setup`.
> 
> `org-roam-id-open` uses `org-goto-marker-or-bmk`, which calls `pop-to-buffer-same-window`. I do not see `org-link-frame-setup used` in this chain of functions.

**Comment by natask** [comment]
yes, I wasn't referring to the side-buffer although it affects the side-buffer as well.

**Comment by jethrokuan** [comment]
In v2 the org-roam buffer now respects `display-buffer-alist` and `org-link-frame-setup` when using `org-open-at-point`.

**Comment by joshcho** [comment]
I see `org-open-at-point-global` respects `org-link-frame-setup`, but `org-open-at-point` does not. Anyone else noticing this?
