### ISSUE TITLE
README.md points to the manual for Doom+Spacemacs install instructions, but seemingly no such instructions exist

### ISSUE THREAD

**Issue by JJJollyjim** [org-roam/org-roam#1349]
### Description

The README states:

> For more detailed installation and configuration instructions (including for Doom and Spacemacs users), please see the documentation.

But I cannot find such information in the manual.

Based on [this comment](https://github.com/org-roam/org-roam/issues/1248#issuecomment-725203416), it seems like those instructions have been removed in favor of docs in the distros themselves?

Ideally the README could be updated to link to those instructions (or tell users to go find them themselves).

**Comment by d12frosted** [comment]
Just for reference:

1. [Spacemacs](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+emacs/org/README.org#org-roam-support)
2. [Doom](https://github.com/hlissner/doom-emacs/tree/develop/modules/lang/org#module-flags) - the last line in this list
