### ISSUE TITLE
Insert link to future day

### ISSUE THREAD

**Issue by shlevy** [org-roam/org-roam#1350]
### Brief Abstract

Simple way to insert a link to a future daily entry.

### Long Description

Currently as far as I know I have to either `find` the future day or know the file format appropriately.

### Proposed Implementation (if any)

Probably a simple `interactive` to give you a date picker and insert the appropriate link. Perhaps with a special case for today, tomorrow, yesterday?

### Please check the following:

- [x] No similar feature requests

**Comment by shlevy** [comment]
I'd be happy to give a shot at implementing this if it's a desired feature.

**Comment by wakatara** [comment]
I think the tricky part here (I personally use a yyyy-mm-dd.org date for my dailies) is having the link insert under the `/dailies` directory more than anything. 

While I understand that may be desirable from a replicated roam research perspective, doesn't it make more sense here to use org-mode's `DEADLINE` and `SCHEDULED` and `TODO` functionality in conjunction with your agenda (that's what I do, in any case.). 

It's quite a bit more powerful than what you would get replicating Roam Research's (underwhelming) in-app task management system.)

**Comment by shlevy** [comment]
Yeah, after using org-roam more I'm realizing this is what I want, to better integrate with org-agenda. I think using the roam dir as my agenda dir would be too expensive, but at least having a todo.org in the roam dir might cut it.

**Comment by wakatara** [comment]
I use the "dailies" directory (or did, when I had a manual function to create those and it works fine. Towards end of year it might take a few seconds to generate the first agenda but when cached you're fine. I also have a sweeper function (which I'm realizing I should blog now this is going to be a common issue) that can move any files that have all `TODO`s completed/killed/closed and moves those files to an `.org_archive` extension so they are still searchable but do not get parsed for your agenda rollup.
