### ISSUE TITLE
org-roam-dailes-find-date deviates to "Select a capture template"

### ISSUE THREAD

**Issue by rakoenig** [org-roam/org-roam#1354]
### Description
Trying to open an exisiting dailies entry.

#### Steps to Reproduce

M-x org-roam-dailies-find date
The calendar appears, I see the dates that have entries and I selct one.

#### Expected Results
After selecting the date in the calendar the file should open directly without that step through "org capture". 

#### Actual Results

Instead of opening that entry, I end up in "Select a capture template" 
The strange thing is that this template just offers my one line:

[l] lab

above the usual [c] Customize and [q] abort.

 Pressing "l" then shows the entry for the selected date. 

This is kind of strange because org-roam-dailies-capture today shows

[l] lab
[j] journal

in the capture template.

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
Do you have anything in `org-roam-dailies-find-file-hook`?

Unfortunately I can't seem to reproduce. 

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101))
 of 2020-11-13
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /Users/jethrokuan/.emacs.d/.local/straight/build-28.0.50/org-mode/)
- Org-roam: 777f6d2

**Comment by rakoenig** [comment]
`org-roam-dailies-find-file-hook` was nil. 

Now I updated form Org 9.3.x (which came with the emacs 27.1 package for openSUSE) to Org 9.4.2 and the problem is gone.

**Comment by krummja** [comment]
I am also having this issue using emacs 27.1, using roam 1.2.3.

**Comment by maxmahlke** [comment]
I can confirm that upgrading Org from 9.3 to the [latest version](https://code.orgmode.org/bzg/org-mode.git) got rid of the erroneous capture buffer.

**Comment by meliache** [comment]
I have this issue again in the latest org-roam v2 [1] and the latest org [2] git revisions. My `org-roam-dailies-capture-templates` is quite complex, but I checked that I can reproduce the behaviour with 
``` elisp
  (setq org-roam-dailies-capture-templates
        '(("d" "default" entry "* %?" :if-new
           (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))
          ("t" "test" entry "* %?" :if-new
           (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))))
```
As other reported for previous org-roam/org versions, with `org-roam-dailies-find-today` I get the template select menu before the daily note is opened.

Should this issue be re-opened? Or is this covered by some other v2-related issue which I have overlooked? Or is this just something in my setup? I'm aware that I'm on shaky ground by using the latest git revisions instead of stable releases...

[1]: release `2.0.0`, commit `57ca8b6e` from 2021-07-12
[2]: release `9.4.6`, commit `fc273bfc` from 2021-07-11

**Comment by chip2n** [comment]
I'm having the same issue as @meliache - having at least two templates in `org-roam-dailies-capture-templates` seems to trigger the template select menu when calling `org-roam-dailies-find-today`.

**Comment by jethrokuan** [comment]
> having at least two templates in org-roam-dailies-capture-templates seems to trigger the template select menu when calling org-roam-dailies-find-today

@chip2n @meliache We don't have much of a choice here I think. Consider having 2 templates with different `file` specifications. How does `org-roam-dailies-find-today` know which file to pick?

**Comment by chip2n** [comment]
@jethrokuan That's a good point, didn't consider that. The current situation do feel like a bug in a pretty common case though (having a single daily file and multiple different templates for it).

For my use case, the ideal solution would be to get a list of all possible files for the templates, and if the length of this list is greater than one, ask the user which one to use (the "Select a template" prompt might be fine then, or using `completing-read` with the list of files).

Alternatively, an optional argument could be added to `org-roam-dailies-find-today` specifying which template key should be used for resolving the file name. That would make the behavior more clear when reading the function documentation, and pretty straightforward to bind to a keybinding.

**Comment by Wetlize** [comment]
I have an idea how to address this issue, where you will be able to easily specify the default template, based on the current capture context for any type of capture template, but it will come as part of a bigger PR for the capture system some time during the next week.
