### ISSUE TITLE
Unable to insert links from company-org-roam tooltip

### ISSUE THREAD

**Issue by ceblan** [org-roam/org-roam#1357]
### Description
When selecting a valid candidate from company-org-roam, company complaints about ```org-roam--format-link-title``` being void.

I've seen this function was removed in [a4da8f3](https://github.com/org-roam/org-roam/commit/a4da8f32bfe824a114163093917858d8b05cb983) regarding #1197  and #1199 , so this seems more likely to be a problem of mine rather than a bug. 

Basically, I'm asking for help: I've removed/rebuilt company-org-roam via straight, I've rebuilt org-roam as well but it's still happening. Any idea what the problem could be and how can I fix it?

#### Steps to Reproduce

1. Open an org-roam note/file
2. (while writing normaly) try to insert a link from company tooltip by selecting a valid known candidate (a note/ org-roam file) from company tooltip

#### Backtrace

	Debugger entered--Lisp error: (void-function org-roam--format-link-title)
		org-roam--format-link-title("Emacs")
		company-org-roam--post-completion("Emacs")
		company-org-roam(post-completion "Emacs")
		apply(company-org-roam post-completion "Emacs")
		company--multi-backend-adapter((company-org-roam company-dabbrev company-yasnippet company-ispell) post-completion "Emacs")
		apply(company--multi-backend-adapter (company-org-roam company-dabbrev company-yasnippet company-ispell) (post-completion "Emacs"))
		company-call-backend-raw(post-completion "Emacs")
		apply(company-call-backend-raw (post-completion "Emacs"))
		company--force-sync(company-call-backend-raw (post-completion "Emacs") (company-org-roam company-dabbrev company-yasnippet company-ispell))
		company-call-backend(post-completion "Emacs")
		company-cancel("Emacs")
		company-finish("Emacs")
		company-complete-selection()
		funcall-interactively(company-complete-selection)
		call-interactively(company-complete-selection nil nil)
		command-execute(company-complete-selection)

#### Expected Results

The link is auto-completed and hence inserted

#### Actual Results

See backtrace

### Environment
It happens in Linux and Macos Catalina:

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H2))
 of 2020-12-20
- Framework: N/A
- Org: Org mode version 9.4.3 (release_9.4.3-152-g713b3b @ /Users/carlos/.emacs.d/straight/build/org/)
- Org-roam: 1.2.3
- Org-roam commit: [be95b42](https://github.com/org-roam/org-roam/commit/be95b42d32d9707309ab373f1d8182c84db41c5c)

**Comment by ceblan** [comment]
My elisp is very poor but I believe the culprit is ```company-org-roam--post-completion```  calling ```org-roam--format-link```.  

Given the code below:

```
(defun company-org-roam--post-completion (title)
  "The post-completion action for `company-org-roam'.
It deletes the inserted TITLE, and replaces it with a relative
file link.

The completion inserts the absolute file path where the buffer
does not have a corresponding file."
  (let* ((cache (gethash (file-truename org-roam-directory) company-org-roam-cache))
         (path (gethash title cache))
         (current-file-path (-> (or (buffer-base-buffer)
                                    (current-buffer))
                                (buffer-file-name)
                                (file-truename)
                                (file-name-directory))))
    (delete-region (- (point) (length title)) (point))
    (insert (format "[[file:%s][%s]]"
                    (if current-file-path
                        (file-relative-name path current-file-path)
                      path)
                    ;;(org-roam--format-link-title title)
                    ;;(org-roam-format-link title)
		    title))))
```
Correct me if I wrong, but there is no need to call ```org-roam-format-link``` anymore (I've left commented both old and new format); now, just passing ```title``` to ```format``` would fix the problem. Is this right?

Should I open a ticket in [company-org-roam](company-org-roam)? I say it because it is flaged as *archived* (not sure what that means).

**Comment by jethrokuan** [comment]
company-org-roam is deprecated in favour of `completion-at-point`, which `company-capf` is the backend for.

https://www.orgroam.com/manual.html#Completions

**Comment by ceblan** [comment]
That makes sense; however, it seems that I'm still doing something wrongly:

As per the manual you linked, I've prepended ```company-capf``` to ```company-backends``` localy for org-roam buffers but  links does nor appears in the tooltip as I write it.

The value of ```company-backends```  in the org-roam buffer in which I'm trying is:

```
 Value:
((company-capf company-dabbrev company-yasnippet company-ispell))
Original value was 
(company-bbdb company-semantic company-cmake company-capf company-clang company-files
							(company-dabbrev-code company-gtags company-etags company-keywords)
							company-oddmuse company-dabbrev)
Local in buffer 20200411032016-emacs.org; global value is 
(company-gtags company-clang company-capf company-files)
``` 
 Is there something else I'm missing?

**Comment by jethrokuan** [comment]
You're probably looking for this setting:

https://www.orgroam.com/manual.html#Link-Completions-Everywhere

**Comment by ceblan** [comment]
Ohh, I missed that. 

I'll invest some time re-reading the manual, I did it back in March but org-roam is evolving fast (for good).

Thanks again @jethrokuan !
