### ISSUE TITLE
Using org-roam-insert within a captured template does not create new roam file

### ISSUE THREAD

**Issue by wakatara** [org-roam/org-roam#1361]
### Description

If you are editing within a new file triggered through `org-roam-insert` and then realize you need to link something in *that* file to a new idea, triggering `org-roam-insert` in the capture file launches a new capture buffer but does not create a new org-roam file. 

#### Steps to Reproduce

In standard org-mode file:
1. Trigger `org-roam-insert` (C-i in my setup) and create the new file "Notetaking"
2. In Notetaking (which is in a Capture buffer with C-C C-c and C-c C-k as options) start filling in content. Realize you forgot to mention the "Zeigarnik effect" ("open loops take up short term memory. Write stuff down. GTD works this way. Eases anxiety."). Trigger `org-roam-insert` within the capture buffer to create the new link.

#### Backtrace

n/a

#### Expected Results

1. A new buffer should open
2. A new org-roam file with standard template should be created 
3. Original capture buffer that spawned this one should be visible in split.

#### Actual Results

1. New buffer open in split
2. Blank org file is created *without* the org-roam template. 
3. Original capture buffer that spawned is visible in split.

### Environment

n/a

**Comment by jethrokuan** [comment]
@wakatara can you check if you have any custom hooks added to `org-capture`? Everything is working fine with the default template.

```
("d" "default" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "${slug}"
           :head "#+title: ${title}\n"
           ;; :immediate-finish t
           :unnarrowed t)
```

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0)
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /home/jethro/.emacs.d/.local/straight/build-28.0.50/org-mode/)
- Org-roam: 1.2.3

**Comment by wakatara** [comment]
Hmmmm... not that I'm aware of, though I have changed my template from the vanilla one (I think it was you that helped me with it preivously, actually.(. Relevant part of config follows:

``` elisp
     (org-roam-capture-templates
       '(("d" "default" plain (function org-roam--capture-get-point)
	  "%?"
	  :file-name "${slug}"
	  :head "#+TITLE: ${title}\n#+CREATED: %u\n#+Modified: %U\n#+ROAM_ALIAS:\n#+ROAM_TAGS:\n\n* ${title}\n"
	  :unnarrowed t)))
      :bind (:map org-roam-mode-map
               (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-graph))
              :map org-mode-map
              (("C-i" . org-roam-insert)))
      :config
      (defun org-roam--title-to-slug (title)
	"Convert TITLE to a filename-suitable slug. Uses hyphens rather than underscores."
	(cl-flet* ((nonspacing-mark-p (char)
                                  (eq 'Mn (get-char-code-property char 'general-category)))
               (strip-nonspacing-marks (s)
                                       (apply #'string (seq-remove #'nonspacing-mark-p
                                                                   (ucs-normalize-NFD-string s))))
               (cl-replace (title pair)
                           (replace-regexp-in-string (car pair) (cdr pair) title)))
	  (let* ((pairs `(("[^[:alnum:][:digit:]+]" . "-")  ;; convert anything not alphanumeric or plus <---
                      ("--*" . "-")  ;; remove sequential underscores
                      ("^-" . "")  ;; remove starting underscore
                      ("-$" . "")))  ;; remove ending underscore
             (slug (-reduce-from #'cl-replace (strip-nonspacing-marks title) pairs)))
            (s-downcase slug)))))

(setq org-roam-dailies-capture-templates '(("d" "daily" plain (function org-roam-capture--get-point) ""
    :immediate-finish t 
    :file-name "dailies/%<%Y-%m-%d>"
    :head "#+TITLE: %<%Y-%m-%d %a>\n\n* %<%Y-%m-%d %a>\n\n" )))
```

Note: It only happens intermittently and only when I am doing an org-roam-insert from a buffer, and then inserting again from that secondary buffer. Been waiting for it to happen again to grab the message though effectively it was something about the call being too deeply nested. Though just tried to replicate the problem again with 3 inserts into new templates and it did not trigger... :-/

**Comment by jethrokuan** [comment]
> Been waiting for it to happen again to grab the message though effectively it was something about the call being too deeply nested. Though just tried to replicate the problem again with 3 inserts into new templates and it did not trigger... :-/

Hmm, maybe it's the emacs-lisp eval depth thing. Doesn't seem like something Org-roam would cause though.

Feel free to reopen when it triggers again.
