### ISSUE TITLE
not working in wsl2 emacs

### ISSUE THREAD

**Issue by jacklisp** [org-roam/org-roam#1370]
### Description
I got a problem while using org-roam in my wsl2 emacs
```
Warning (org-roam): Skipping unreadable file while building cache: /mnt/f/testroam/20210104102645-test.org
```

#### Steps to Reproduce
1. Load Emacs
```
wsl emacs
```
2. Run `org-roam-db-build-cache`
`Warning (org-roam): Skipping unreadable file while building cache: /mnt/f/testroam/20210104102645-test.org`

3. Run `org-roam-find-file`
No file can be found 

#### Backtrace
Is it the problem? in the org-roam-db.el ?
 (file-error
           (setq error-count (1+ error-count))
           (org-roam-db--clear-file file)
           (lwarn '(org-roam) :warning
                  "Skipping unreadable file while building cache: %s" file)))))

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
 of 2020-09-15
- Framework: N/A
- Org: Org mode version 9.3 (release_9.3 @ /usr/share/emacs/27.1/lisp/org/)
- Org-roam: 1.2.3

**Comment by jacklisp** [comment]
The problem is locate in the org-roam-db.el
```
(condition-case nil
            (org-roam--with-temp-buffer file
              (setq modified-count (1+ modified-count))
              (setq link-count (+ link-count (org-roam-db--insert-links)))
              (setq tag-count (+ tag-count (org-roam-db--insert-tags)))
              (setq title-count (+ title-count (org-roam-db--insert-titles)))
              (setq ref-count (+ ref-count (org-roam-db--insert-refs))))
```
when the function org-roam-db–insert-links will cause a file-error
after comment this line, change to
```
(condition-case nil
            (org-roam--with-temp-buffer file
              (setq modified-count (1+ modified-count))
              ;; (setq link-count (+ link-count (org-roam-db--insert-links)))
              (setq tag-count (+ tag-count (org-roam-db--insert-tags)))
              (setq title-count (+ title-count (org-roam-db--insert-titles)))
              (setq ref-count (+ ref-count (org-roam-db--insert-refs))))
```
the db can be update normally by “M-x org-roam-db-build-cache”
I just wanna catch what does org-roam-db–insert-links function do in the programme?
And comment this line will cause no backlinks show in the buffer.

**Comment by nobiot** [comment]
As we discussed in Discourse, I cannot reproduce your error on my WSL 2 set up.
https://org-roam.discourse.group/t/problem-skipping-unreadable-file-while-building-cache/1141/16

Did upgrading Org change the behaviour by any chance?

**Comment by jacklisp** [comment]
> As we discussed in Discourse, I cannot reproduce your error on my WSL 2 set up.
> https://org-roam.discourse.group/t/problem-skipping-unreadable-file-while-building-cache/1141/16
> 
> Did upgrading Org change the behaviour by any chance?

There is no any effect by upgrading Org to 9.4.4,I change to use doom emacs for test, the problem disappear,May be disturbed by other packages.

**Comment by jacklisp** [comment]
It is hard for me to spend so much time to debug this problem, so I close this topic and use the doom emacs normal version org-roam now.

**Comment by jacklisp** [comment]
Finally, I downgrade the org-roam package to org-roam-20201001.430，that package solve the problem, thinks a lot!
at a glance,the method is difference compare with org-roam-1.2.3
```
(when-let (links (org-roam--extract-links file))
               (org-roam-db-query
                [:insert :into links
                 :values $v1]
                links)
               (setq link-count (1+ link-count)))
```
