### ISSUE TITLE
Org-roam-protocol on MacOS without Platypus

### ISSUE THREAD

**Issue by agzam** [org-roam/org-roam#1372]
_Not a bug, more like a queston_

#### Can't use Platypus. Is there an alternative way of setting org-protocol in OSX?

I wanted to set up org-protocol. While following the [documentation](https://www.orgroam.com/manual.html#Installation-_00281_0029) I tried installing Platypus, but the corporate malware detection software on my laptop won't allow it. I hit this issue https://github.com/sveinbjornt/Platypus/issues/149

Whitelisting the app would require jumping through bureaucracy hoops and I don't want to get into that. 

Does anyone know or tried an alternative, like using AppleScript Editor to create Emacsclient App container that would work?

**Comment by agzam** [comment]
So this is what I did:

- Launched Script Editor
- Entered the following script:

    on open location this_URL
	    set EC to "/usr/local/bin/emacsclient --no-wait "
	    set filePath to quoted form of this_URL
	    do shell script EC & filePath
	    tell application "Emacs" to activate
    end open location
- Saved that as an Application (not a script)
- Navigated to application bundle folder (Apps on Mac are just folders)
- Opened plist file `/Applications/OrgProtocolClient.app/Contents/Info.plist`
- Added this before last `</dict>` tag:

      <key>CFBundleURLTypes</key>
      <array>
	<dict>
	  <key>CFBundleURLName</key>
	  <string>org-protocol handler</string>
	  <key>CFBundleURLSchemes</key>
	  <array>
	    <string>org-protocol</string>
	  </array>
	</dict>
      </array>
- Saved the file, Clicked on the App in Finder (so it registers)

I think it works. At least it works with the roam-ref-protocol bookmarklet from the official docs. 
Now I need to test it with roam-server.

**Comment by alanz** [comment]
Should this issue be closed? Seems like this info should be captured in the documentation?

**Comment by d12frosted** [comment]
@agzam wonderful approach, which sounds easier than using Platypus. I second what @alanz says.

**Comment by agzam** [comment]
Yeah, this feel a bit more "hackety" also opens an opportunity to tweak it for different scenarios, e.g: open new Emacs frame for capture, but re-use the same frame for org-server. Perhaps we should update the docs for using this approach instead of Platypus.

**Comment by jethrokuan** [comment]
Happy to accept a PR, if at least one more can confirm this works.

**Comment by staticaland** [comment]
I have never used `org-protocol` before and seemingly got this to work by blindly following the instructions from @agzam! Thanks 👍 I have tried is opening links from the graph SVG inside Firefox as well as from `org-roam-server`.

Also while I am here: Thanks to all the contributors of this amazing package. It has been such a delight to use!

**Comment by anoopd** [comment]
After creating the script in script editor it is asking "Where is Emacs" and though i tried to point to /usr/local/bin  it is not working . What am i doing wrong ? What name should i give while saving the Application ?

**Comment by agzam** [comment]
> it is asking "Where is Emacs"

Check if Emacs.app (Cocoa UI) is properly installed. Try in terminal `open -a Emacs`.
