### ISSUE TITLE
Org-Roam dailies error for DB

### ISSUE THREAD

**Issue by biffbaxter** [org-roam/org-roam#1378]
I am running emacs 26.3 and org-roam 1.2.3 and ubuntu 20.10 and Doom v2.0.9 (and sqlite3 from the standard 20.10 repos) 

I have copied my emacs dir structure and .doom files verbatim across several computers (no sync or anything like that, just an old fashion offline copy when re-imaging a computer. I always then .doom sync and upgrade prior to doing anything. 

I have a new error I have not encountered before, and its only with the daily notes. 

When ever I open a daily I get - `Warning (org-roam): Attempted to recreate existing file: <then my correct path to my dailies folder> ` along with `This can happen when your org-roam db is not in sync with your notes.
Using existing file...` 

I then run what has worked in the past for me - `org-roam-db-clear` and `org-roam-db-build-cache` - then restart and the problem persists. 

Any additional ideas or steps? I have also completely deleted the DB and let it build again to no avail.

**Comment by jethrokuan** [comment]
Nothing wrong here, but the warning is falsely appearing for `org-roam-dailies`. You can ignore it for now while I push a fix.

**Comment by jethrokuan** [comment]
Closed by #1387
