### ISSUE TITLE
Normalized completion

### ISSUE THREAD

**Issue by oatmealm** [org-roam/org-roam#1379]
### Brief Abstract
Looking at `org-roam-completion-ignore-case` I was wondering if it'd be possible to allow searching for the normalized forms of Unicode strings.

### Long Description
When text is saved with accents/diacritics matching text for retrieval requires entering the exact forms... which is a nightmare for Hebrew/Arabic. 

### Proposed Implementation (if any)
I'm not sure if it was brought up here or elsewhere, but there seem to be normalization functions available for regex searches, as mentioned here: https://nullprogram.com/blog/2014/06/13/

### Please check the following:

- [ ?] No similar feature requests

**Comment by d12frosted** [comment]
I also encountered this and you actually need to configure your completion system to support char folding. In many cases it's enough to set `search-default-mode` to  `#'char-fold-to-regexp` somewhere in your `init.el` file:

```emacs-lsip
(setq search-default-mode #'char-fold-to-regexp)
```

(or via any other prefered way). You can verify if that's working by executing following code and typing `buna` as input:

```emacs
(completing-read
 "greeting: "
 '("Bună dimineața"
   "Buna dimineata"))
```

If you are using built-in completion, this should be enough. As well as for `ivy`, it [respects this setting][1]. If you are also using `prescient.el`, char folding is [supported][2] for `literal` filter. Now, for `helm` I don't know. 🤷 

Here is a screenshot of me using `org-roam-find-file` (using `ivy` + `prescient`):

<img width="949" alt="image" src="https://user-images.githubusercontent.com/6507913/104442730-22161b80-559e-11eb-8f11-3da1042233e7.png">

Hope that helps.

  [1]: https://github.com/abo-abo/swiper/issues?q=char+folding
  [2]: https://github.com/raxod502/prescient.el/pull/66

**Comment by oatmealm** [comment]
Wow! This is so helpful and seems to work both in Hebrew and Arabic. Some false positives, but this really solving the most pressing problem!
Thanks

![gnome-shell-screenshot-3HCSW0](https://user-images.githubusercontent.com/68159077/104473756-9d3afa00-55bd-11eb-9b9e-1bdad3fb60ca.png)

**Comment by jethrokuan** [comment]
Closing as mini-buffer completion is not really in the realm of Org-roam.

**Comment by d12frosted** [comment]
@jethrokuan you forgot to close 😸
