### ISSUE TITLE
When running org-roam-find-file all files that do not include #+roam_alias field are titled 'tags'

### ISSUE THREAD

**Issue by ln0a** [org-roam/org-roam#1380]
As the title suggests, when running org-roam-find-file, all files that do not include `#+roam_alias` field are titled as `tags`. The file specific tags are included however.

Version 1.2.3

<img width="396" alt="Screenshot 2021-01-13 at 16 33 06" src="https://user-images.githubusercontent.com/15690673/104480953-138b2c80-55bd-11eb-8a8b-474084760980.png">

<img width="394" alt="Screenshot 2021-01-13 at 16 32 09" src="https://user-images.githubusercontent.com/15690673/104480824-eb033280-55bc-11eb-8fed-73752b914bd8.png">

The `tags.org` `#+SETUPFILE` includes all agenda tags.

Thanks

**Comment by jethrokuan** [comment]
A lot has changed in Org-roam v2, feel free to reopen if this is still an issue.

**Comment by ln0a** [comment]
V2 has fixed that problem for me now, thanks for all the hard work!
