### ISSUE TITLE
org-roam--replace-link fails to replace titles of id: links

### ISSUE THREAD

**Issue by czikus** [org-roam/org-roam#1382]
### Description

`org-roam--replace-link` is meant to update a link path and description after file name/title change. This seems to work just fine, unless `org-roam-prefer-id-links` is set to `t` and id: links are used. In such a case, the id: would of course remain the same, yet the title should be updated.

#### Steps to Reproduce

1. Add an id: link to the org file X pointing to the org file Y.
2. Change the title of the org file Y.
3. Observe that the filename of the file is updated accordingly.
4. Observe that `org-roam--update-links-on-title-change` is correctly listing the file X in its variable `files-affected`
5. Observe that `org-roam--replace-link` ignores the links.

#### Expected Results

Title of the id: link in file X is updated.

#### Actual Results

Title of the id: link in file X is NOT updated.

### Environment

- Emacs: GNU Emacs 27.1.90 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
 of 2021-01-11
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /home/user/.emacs.d/.local/straight/build-27.1.90/org-mode/)
- Org-roam: 1.2.3
- Org-roam commit: https://github.com/org-roam/org-roam/commit/05a9bc44f2d158cc355c904382f2c7b079aeee15

**Comment by natask** [comment]
#1362 solves this bug.
