### ISSUE TITLE
Export graph to HTML

### ISSUE THREAD

**Issue by JonathanReeve** [org-roam/org-roam#1389]
### Brief Abstract

It'd be great to be able to export an org-roam note collection to HTML, so that it can be served on the web. You can *almost* do this with existing tools, yet it would be awesome to export the graph visualization, as well.

### Long Description

Other Zettelkasten software, like [Obsidian](https://obsidian.md/publish), allow you to export your notes to HTML, and shows you a nifty graph of how all the notes are connected. [Neuron](https://neuron.zettel.page/) is another such program, that is good at making web pages from a stack of notes. (paging @srid)  

Meanwhile, org-roam has some really great visualization tools, but they're local-only. For instance, org-roam-graph makes a nice graphviz graph that can then be visualized on the user's own computer. And org-roam-server (@goktug97) makes a stellar visualization, which is amazingly its own web server, but which can't be exported statically at the moment (see https://github.com/org-roam/org-roam-server/issues/38). 

All the pieces are *almost* there. For instance, [d3-dot-graph](https://github.com/gmamaladze/d3-dot-graph) allows one to make a D3 force-directed chart, in a beautifully interactive way, from a graphviz graph. So it seems like it would be relatively easy to make a web-facing D3 graph from an org-roam database.  

### Proposed Implementation (if any)

It'd be great if there were an ox-org-roam, which exported an org-roam tree, or optionally a subtree, and produced a static website which could immediately be served on the web. 

I imagine this with two panels: the left one would have a graph visualization, as in org-roam-graph, or org-roam-server. The right would have the text of whatever note was focused. 

A bonus could be the breadcrumbs that Neuron has. 

### Please check the following:

- [X] No similar feature requests

**Comment by flakyhermit** [comment]
How does https://braindump.jethro.dev/ work? @jethrokuan

**Comment by jethrokuan** [comment]
@flakyhermit I briefly describe the build process in the README for that repo: https://github.com/jethrokuan/braindump

**Comment by jethrokuan** [comment]
It looks like @rasendubi has built something very nice specifically around publishing notes from Org-roam. Mine is a little more like patchwork.

**Comment by rasendubi** [comment]
Yeah… You can check my braindump at https://braindump.rasen.dev.

I wrote [my own org-mode parser](https://github.com/rasendubi/uniorg) and plugged it into Next.js. There is a stripped-down version of my braindump as an example: https://github.com/rasendubi/uniorg/tree/master/examples/org-braindump

It does not rely on any of emacs tools, nor does it use org-roam database. It has backlinks though, but not graph. I imagine D3 wouldn't be too hard to plug in.

**Comment by jethrokuan** [comment]
I'd use it if it supported citations as well, but that might be much harder to implement ><

**Comment by rasendubi** [comment]
It's not—I have it in my version (Just published the full source at [rasendubi/braindump](https://github.com/rasendubi/braindump))

uniorg parses cite: links just fine, so the only thing left is to prescribe what they mean. I do that in [src/lib/processUrls.ts:36–63](https://github.com/rasendubi/braindump/blob/1369c883d0f8bb4c67a6e0c33f5d2cc4ce0e541f/src/lib/processUrls.ts#L36-L63).

All my bibliographical notes are at `/biblio/${bibtex_key}.org`, so I just change the link to point there. Backlinks are computed after that phase, so cite links are counted correctly.

I also change the text to be more referency: cite:ahrens2017-how-take-smart-notes → Ahrens<sub>2017</sub>, but that's optional.

**Comment by jethrokuan** [comment]
This is being tackled by the new `org-roam-ui` (currently private), closing as not within the scope of this project.
