### ISSUE TITLE
Org roam takes over original window after completion

### ISSUE THREAD

**Issue by paultopia** [org-roam/org-roam#1391]
### Description

Normally, when I use org-capture, saving and finalizing the capture closes the org-capture window and returns me to my prior window with the original buffer I had open in it.  I.e., if I have foo.txt open in a single window, when I'm done, foo.txt is still in the original window.

However, using org-roam, when I finalize the note, it closes the new window, but the note occupies my old window instead of the original buffer.  See below for an example of this behavior (assuming the animated gif works):

![org-wrong-window](https://user-images.githubusercontent.com/11756255/104978625-e4632980-59c7-11eb-8f31-8406f0c725f6.gif)

By contrast the following animated gif illustrates the ordinary behavior of org-capture, which I would have expected to carry over to org-roam

![correct_behavior](https://user-images.githubusercontent.com/11756255/104979008-e679b800-59c8-11eb-8cd7-40677a1047f7.gif)

I'm not sure if this is a bug or if it's just intended behavior.  If it's intended behavior, is there a setting to turn it off and get the normal org-capture behavior?

Caveats: 

1 I'm using evil

2. In the video/gifs I'm saving the buffer before finalizing/closing it with C-c C-c... not sure whether that's what one is supposed to do, or whether one should just close immediately.  HOWEVER, when I just finalize with C-c C-c without saving first, it does the same thing. 

#### Steps to Reproduce

1.  Create a new note with org-roam-find-file
2. Finalize the note

#### Backtrace

n/a no error given 

#### Expected Results

I'd land in my original buffer in my original window

#### Actual Results

the newly created note is in my original window

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, Carbon Version 162 AppKit 1894.6)
 of 2020-12-27
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4-186-g7fa817 @ /Users/paulgowder/.emacs.d/straight/build/org/)
- Org-roam: 1.2.3

**Comment by jethrokuan** [comment]
This is expected behaviour for `org-roam-find-file`, which captures, and finds the file. What you're looking for is `org-roam-capture`, which should behave like regular `org-capture`.

**Comment by paultopia** [comment]
Aaah, thank you!  Would you be interested in a PR to the docs to make that clear?

**Comment by jethrokuan** [comment]
Yes, please :)

**Comment by paultopia** [comment]
Awesome, will do :-)
