### ISSUE TITLE
Will it support markdown file?

### ISSUE THREAD

**Issue by ColorFuzzy** [org-roam/org-roam#1392]
### Brief Abstract

I have a lot of markdown files, it's hard to migrate to org.

### Long Description

Will org-roam both support markdown file and org file?

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
Not in this repo. Take a look at https://github.com/nobiot/md-roam for a compatibility layer, but no guarantees that it will continue to function as org-roam develops.
