### ISSUE TITLE
Readme images are not shown, orgroam.com can't be reached

### ISSUE THREAD

**Issue by duianto** [org-roam/org-roam#1395]
## Update
Not being able to reach orgroam.com might be by design.
Because the manual is accessible.
https://www.orgroam.com/manual.html

The images might just have been moved.

### Description
The two images (Logo and Screenshot) in the readme.md are broken:

![chrome_2021-01-20_12-34-12](https://user-images.githubusercontent.com/13420573/105169567-feae1c00-5b1b-11eb-91c5-1b2bf5d15a2f.png)

The urls to the images are:
https://www.orgroam.com/img/logo.svg
https://www.orgroam.com/img/screenshot.png

### Cause
http://orgroam.com/

Leads to a page that says:
>This site can’t be reached
Check if there is a typo in orgroam.com.
If spelling is correct, try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

It doesn't seem to be a local issue, because:
https://downforeveryoneorjustme.com/orgroam.com?proto=http

Says:
>Orgroam.com Status
Is orgroam.com down right now?
It's not just you! orgroam.com is down.

### Possible solution
Maybe the images should be hosted on GitHub.

**Comment by jethrokuan** [comment]
I noticed this as well. Looks like GitHub has resolved their networking issues, thanks for reporting though.
