### ISSUE TITLE
after a "cite:ref" any "roam:link" does not get formatted until the text is modified

### ISSUE THREAD

**Issue by wilya7** [org-roam/org-roam#1397]
### Description
When opening emacs and loading an org-roam file, any org-roam link after an org-ref link is not formatted. By modifying the text around it, e.g. inserting a new line right at the end of the link, the formatting gets applied correctly. However after quitting emacs and reloading, the link is again not formatted.
#### Steps to Reproduce
1) create an new org-roam file;
2) insert two links to some other org-roam files;
3) save;
4) close emacs;
5) open emacs and load the files, the links are formatted correctly;
6) now insert in between the two links an org-ref link, e.g. "cite:petzoldCodeHiddenLanguage2000";
7) save and quit;
8) start again emacs, load the file. Now the org-roam link above the org-ref link is formatted while the one below is not and if you cut and paste the link or add a new line to it, it gets formatted again, until you close emacs, reopen and reload.

#### Expected Results
I believe, regardless of the presence of an org-ref link, any org-roam link in whichever position should be properly formatted.
#### Actual Results
The links are properly formattend only when located before an org-ref link.
### Environment
- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G6042))
 of 2020-12-04
- Framework: N/A
- Org: Org mode version 9.4.4 (9.4.4-11-g9e8215-elpaplus @ /Users/.../.emacs.d/elpa/org-plus-contrib-20210118/)
- Org-roam: 1.2.3
- Org-roam commit: https://github.com/org-roam/org-roam/pull/1393

**Comment by jethrokuan** [comment]
Can you show a screenshot of exactly how it's broken? A brief test on my machine doesn't show any weird quirks.

Formatting Org-roam links is not handled by Org-roam, but by Org itself.

**Comment by wilya7** [comment]
> Can you show a screenshot of exactly how it's broken? A brief test on my machine doesn't show any weird quirks.
> 
> Formatting Org-roam links is not handled by Org-roam, but by Org itself.

This is when I create the org-roam file with the 3 links,

<img width="1920" alt="Screenshot 2021-01-21 at 11 20 11" src="https://user-images.githubusercontent.com/1757313/105337749-05e82f00-5bdb-11eb-853e-ab4cf4de9194.png">

After I save, close emacs, open aging and reload, I get this:

<img width="1920" alt="Screenshot 2021-01-21 at 11 20 59" src="https://user-images.githubusercontent.com/1757313/105337679-f1a43200-5bda-11eb-909a-2e9da94846d6.png">
