### ISSUE TITLE
Edit backlinked file in org-roam buffer 

### ISSUE THREAD

**Issue by ryjm** [org-roam/org-roam#14]
It would be nice if we could edit the backlinked org-mode file in the org-roam buffer, ala org-capture. I attempted something similar in this PR for org-brain: https://github.com/Kungsgeten/org-brain/pull/81/files - doesn't seem like it would be too hard to extend this to org-roam.

**Comment by jethrokuan** [comment]
The preview content can be out of date though (it's only periodically updated), so this must be accounted for if this were to be a feature.

**Comment by ryjm** [comment]
We could store the buffer position of the backlinked content in the hash table, and when you switch to the org-roam buffer we update the content/hash table just for that file.

**Comment by jethrokuan** [comment]
Yeah okay. If we can make this happen, happy to have it as a feature. Although I really want to see what Roam is doing with this first 🤔
