### ISSUE TITLE
Org roam files dont show up on startup

### ISSUE THREAD

**Issue by alphaQ314** [org-roam/org-roam#1400]
### Description
Org roam files dont show up on startup with `org-roam-find-file`. When I run `org-roam-find-file`, the list is emply. 
However, the files show up when I run `org-roam-db-build-cache`. I have to run this process every time I open emacs. Is there anyway to fix this?

#### Expected Results

Org roam files showing up without having to run `org-roam-db-build-cache` every time. 

### Environment

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
How long does org-roam-db-build-cache take? Are you enabling org-roam-mode on init?

**Comment by alphaQ314** [comment]
It takes a couple of seconds. 
How do I check if I'm enabling org-roam-mode on init ?

**Comment by jethrokuan** [comment]
> It takes a couple of seconds.

Then something must be trashing your db file. It should be near instant if no files are changed. Check the value of `org-roam-db-location`, and that the file there is present on startup.

**Comment by alphaQ314** [comment]
`org-roam-db-location` is in the ".emacs.d" folder. 
Is is weird that my db location is different from `org-roam-directory` ?

**Comment by ichor-xyz** [comment]
I have the same problem and can reliably reproduce in Doom Emacs:

1. Start up (Doom) emacs
2. `SPC n r f` (i.e. `M-x org-roam-find-file`)
3. List of files is blank
4. `M-x org-roam-db-build-cache`
5. `SPC n r f` (i.e. `M-x org-roam-find-file`)
6. Correct list of files displayed.
7. `SPC q q` (i.e. `C-x C-c`)
8.  Go back to step 1 and see it all happen again.

Note that the list of files is not always blank -- once in a while the list may contain a small number of random files.

In my `.doom.d/config.el`, I have
```
(setq org-directory "~/org/")

(after! org
  :init
  (setq org-roam-directory (file-truename "~/org/"))
)
```
Describing the variable `org-roam-db-location` yields value `"~/.emacs.d/.local/etc/org-roam.db"` and original value `"~/.emacs.d/org-roam.db"`. I can verify that the DB file exists at `"~/.emacs.d/.local/etc/org-roam.db"`. If I connect to this file with sqlite3 and do `select * from files;` before and after emacs start-up, I can see that something on startup is wiping all the entries from this table.

**Comment by ustcpxy** [comment]
I met the same issue

**Comment by phthhieu** [comment]
I met the same issue but it is solved after a workaround to set org-roam-db-location to a custom path. Eg

```elisp
(after! org-roam
  ;; ~/Dropbox/notes/roam/org-roam.db is my custom path, change to yours.
  (setq org-roam-db-location "~/Dropbox/notes/roam/org-roam.db")
)
```

**Comment by alphaQ314** [comment]
As mentioned by @phthhieu , setting `org-roam-db-location` to the db file, solved my problem.

**Comment by d12frosted** [comment]
It seems like doom emacs [sets the value][1] of `org-roam-db-location` too late. Maybe it's done for people to be able to override that value at different points of time. I think it worth bringing to doom emacs.

@phthhieu if you are working on multiple computers, sharing `org-roam-db` file might be error prone. IMHO It should stay in cache and built when needed.

  [1]: https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/contrib/roam.el#L54

**Comment by asheidan** [comment]
Has this issue been reported to doom-emacs?

I searched their repo for related issues but could not find anything.

**Comment by jethrokuan** [comment]
A lot has changed, feel free to reopen if it's still an issue on latest commit.
