### ISSUE TITLE
Add org headings to the database (or show me how to retrieve them via SQL)

### ISSUE THREAD

**Issue by publicimageltd** [org-roam/org-roam#1402]
### Brief Abstract

This is a database question: As far as I understand the database structure, there are two types of links: Links to files, and links to outline headings (i.e. `** Heading 1`). This forces me to do two separate queries when I want to retrieve all links and backlinks. I would like to abstract from this difference to have one query to rule them all. 

### Long Description

I have written a little tool called  [delve](https://github.com/publicimageltd/delve) which allows me to navigate between linked pages in a tree-view like manner. But as of now, outline links are not included, because they would require a separate, page-dependent query. I'd have to iterate on each page separately, which takes too long. So I cannot include these outline links in the overview. As a further consequence, links to outlines can only be presented as links to the page, not to the specific heading.

I am asking if it is possible to add these outline headings in such a way to the database that they can be treated like pages (using some IDs or whatever). 

Alternatively, if such an abstraction is already possible, I would be grateful for some explanation on how to do it.

Ultimately, I would opt for an improved documentation of the data structure so that plug-ins like mine have a reference.

Currently, `delve` is using the following SQL query to get all pages with all links:

```sql
 SELECT titles.file, titles.title, tags.tags, files.meta,
        (SELECT COUNT() FROM links WHERE links.[source]=titles.file) AS tolinks,
 	   (SELECT COUNT() FROM links WHERE links.[dest] = titles.file) AS backlinks
FROM  titles
LEFT JOIN files USING (file)
LEFT JOIN tags USING (file)
```

Is there a simply way to add outline links (as described in the abstract above) by only changing the query? If not, is it possible to extend the database structure to make this possible? 

### Proposed Implementation (if any)

No idea (yet).

### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
This will be much simpler in v2.

**Comment by publicimageltd** [comment]
So you seem to be working on something -- cool!

Two follow up questions:

 - Will v2 be in foreseeable future, so that I better do not waste my time finding some workaround?
 - Will v2 therefore also introduce a break, i.e., so that the SQL code above won't work? Is it possible to somehow announce that this break will come up, so that I can adjust the queries in delve (which is used by others)? 
 
BTW, I have seen that finally tests are back again (they have been gone for a while). So I figure I could write now some tests for my own queries against the files in the test directory.  Sound's great. I always hold my breath when I update `org-roam` since I am unsure whether the update breaks my queries.

**Comment by d12frosted** [comment]
@publicimageltd There is a discussion on [discourse][1]. And there is a PR - #1401. In short, your and many other queries will break 😸 In my libs I also do test agains some generated `org-roam-directory`, just to know if it's safe to upgrade 😅 

P. S. I love both dvelve and lister. 💯 

  [1]: https://org-roam.discourse.group/t/org-roam-major-redesign/1198

**Comment by publicimageltd** [comment]
Thanks for the links @d12frosted (and for being interested in `delve` and `lister`, cool!). v2 looks actually like a leap forward. So I guess I'll have to write some tests too :-)
