### ISSUE TITLE
org-roam-tag-add automatically deletes the double quotation marks of the tags that already exist.

### ISSUE THREAD

**Issue by Imymirror** [org-roam/org-roam#1403]
I use semicolons to indicate the hierarchy of notes tag.
when tag has semicolon, it will cause an error. 
![image](https://user-images.githubusercontent.com/52570325/105684888-77ecab00-5f30-11eb-90d2-7775c2168c7c.png)

so, I add the double quotation marks.
![image](https://user-images.githubusercontent.com/52570325/105685104-ac606700-5f30-11eb-9dc2-81e0a0ee0aaa.png)

but, When I try to add a tag using org-roam-tag-add, it automatically removes the double quotes.
![image](https://user-images.githubusercontent.com/52570325/105685677-4cb68b80-5f31-11eb-8834-12234a761875.png)

**Comment by d12frosted** [comment]
It seems like a bug to me. Not sure if it's tags formatting or parsing. In any case, tags parsing should be aligned with tags formatting (and vice versa). The quoting of all tags in `org-roam-tag-add` is intentional to prevent such issues 🤔 😅

**Comment by Imymirror** [comment]
[ #1404](https://github.com/org-roam/org-roam/pull/1404) not fixes this issue.

I try org-roam-tag-add, it deletes the double quotation marks as before.

**Comment by d12frosted** [comment]
The problem was not with the removal of quotes, but rather with how `org-roam` was parsing tags and aliases. We aligned both those paths and now quotes are added and removed automatically when needed.

Do you see erorrs after quotes are removed?

**Comment by Imymirror** [comment]
> Do you see erorrs after quotes are removed?
Yes, when I use org-roam-tag-add add an tag ";category", cause an error.

![image](https://user-images.githubusercontent.com/52570325/105807816-aa0a1580-5fe1-11eb-90d7-4fe298e8529e.png)
![image](https://user-images.githubusercontent.com/52570325/105807861-b9895e80-5fe1-11eb-9f2a-2a75dd52c332.png)

**Comment by d12frosted** [comment]
🤔 I have updated `org-roam` before answering you and I see that now I can add tags like `;category` and `org-roam` is happy:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/6507913/105807156-2551d400-5fae-11eb-8953-9398ba8d3a62.png">

Can you please check what commit are you on? Did you reload emacs after updating `org-roam`?

**Comment by d12frosted** [comment]
And btw, if you are upding from MELPA, you might need to wait for 3-4 hours before it gets available.

**Comment by Imymirror** [comment]
> Can you please check what commit are you on? Did you reload emacs after updating `org-roam`?

I use doom-emacs. 
1. I delete  `~/.emacs.d/.local/straight/repos/org-roam`
2. ./doom sync
3. restart doom-emacs
4. org-roam-tag-add add an tag ";category", cause an error.

![image](https://user-images.githubusercontent.com/52570325/105809374-885e5d80-5fe4-11eb-981a-cf90411aac3b.png)

**Comment by d12frosted** [comment]
Hey, I found another issue - https://github.com/org-roam/org-roam/pull/1406

If you haven't yet updated, I'd rather wait for that to land.

**Comment by Imymirror** [comment]
> If you haven't yet updated, I'd rather wait for that to land.

thank you. I will be here waiting for you.

**Comment by d12frosted** [comment]
#1406 is merged @Imymirror 

I am not using doom emacs, and I already [encountered][2] other users who could not update their packages due to doom pinning. For example, I see that by default doom emacs [pins org-roam][1] to `15d864a500d90c9dc2e16d888e93343528ec3941`. So are you unpinning it? 

  [1]: https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/packages.el#L76
  [2]: https://github.com/d12frosted/flyspell-correct/issues/83#issuecomment-737381897

**Comment by Imymirror** [comment]
@d12frosted, when i upgrade #1406, it work! 

this issue has been solved.

**Comment by d12frosted** [comment]
Cool. Happy to hear. Sorry for the breakage.
