### ISSUE TITLE
"Failed to parse aliases/tags for buffer"

### ISSUE THREAD

**Issue by asberk** [org-roam/org-roam#1408]
### Description

I don't know if this is an issue with `org-roam` or an issue with my own org configuration. When I am in an org file that would normally be tracked with org-roam and either: (1) make changes to the buffer and then save it; or (2) `use org-roam-db-build-cache`, I get an error message like the one below. Specifically, emacs hangs briefly and then intrudes my window configuration with a buffer containing the error messages — not conducive to the workflow. I am not adept enough with elisp to know where to look for a resolution to this. Unfortunately, `toggle-debug-on-error` does not produce a traceback when this happens. Any guidance you could provide would be greatly appreciated!

#### Steps to Reproduce

  1. Capture a new item to be filed in `tasks.org`; do: `C-c c <insert description> C-c C-c`
  2. Get the following output:
```
Error (org-roam): Failed to parse aliases for buffer: ~/tasks.org. Skipping
Error (org-roam): Failed to parse aliases for buffer: ~/tasks.org. Skipping
Error (org-roam): Failed to parse aliases for buffer: ~/tasks.org. Skipping
Error (org-roam): Failed to parse tags for buffer: ~/tasks.org. Skipping
Error (org-roam): Failed to parse aliases for buffer: ~/tasks.org. Skipping
```

#### Backtrace

I used `toggle-debug-on-error` but no window popped up with backtrace information.

#### Actual Results

So far as I can tell, everything seems to be working? The only issue is that the above-quoted text pops up in a buffer and is an interference.

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
 of 2019-09-02
- Framework: N/A
- Org: Org mode version  ( @ ~/.emacs.d/elpa/org-9.4.4/)
- Org-roam: 1.2.3

**Comment by d12frosted** [comment]
Hey

- Make sure you are on the latest version of org-roam. Yesterday we did some changes to parsing. 
- Share the value of ROAM_TAGS value in the failing buffer.

**Comment by asberk** [comment]
It appears to be resolved with the new update. Thank you!
