### ISSUE TITLE
Dailies to weeklies

### ISSUE THREAD

**Issue by dangom** [org-roam/org-roam#1411]
### Brief Abstract

A file a day is too much for me. I'd prefer to have a file per week. I am looking for suggestions on how to most organically implement this change on top of dailies.

### Long Description

Perhaps my workflow is just suboptimal, but the tasks I take care of usually extend for at least a couple of days. Working on a presentation or data collection setup, describing some ideas for data analysis, etc. Organizing them on a daily basis seems too much of an overkill because the same content gets split among multiple very related files. I also think that I conceptually organize my work in week terms, so I'm looking to have org-roam follow my mental model.
Also, weeklies would be nice because I could have a heading for "Meetings", and most of my meetings are weekly.

### Proposed Implementation (if any)

Add a defcustom with a multiple choice "dailies, weeklies, fortnightlies, monthlies".  Propagate the change to the folder name and capture templates. Implement a more generic "previous/next" function that could be used for moving between consecutive notes as currently done by "yesterday/tomorrow".

### Please check the following:

- [X] No similar feature requests (that I am aware of).

**Comment by TimQuelch** [comment]
org-journal has this functionality. Implementation inspiration could be taken from there

**Comment by dangom** [comment]
I don't have time to put together a PR right now, but here's an implementation that is working for me already: https://gist.github.com/dangom/a826a86218b967fc03f82aa734f29d18

**Comment by patbakdev** [comment]
I am trying to move from org-journal to org-roam and I go with monthlies. And I feel that this is almost there if I could get this to work:

```
(setq org-roam-dailies-capture-templates
      '(("d" "default" entry
         #'org-roam-capture--get-point
         "* %?"
         :file-name "%<%Y-%m>"
         :head "#+TITLE: %<%Y-%m>\n\n\n"
         :olp ("%<%Y-%m-%d>")
         )))
```
but ```:olp ("%<%Y-%m-%d>")``` doesn't expand.

**Comment by asheidan** [comment]
> but `:olp ("%<%Y-%m-%d>")` doesn't expand.

Are you sure you have a version where `:olp` is implemented? The reason I'm asking is that I had exactly the same issue and realised that I was running an old version of the package where this wasn't implemented yet. ;)

**Comment by patbakdev** [comment]
Thanks @asheidan for the hint, but no go. I am using Doom Emacs which I thought running closer to the edge, but it was in fact pined to org-roam commit 15d864a500d90c9dc2e16d888e93343528ec3941 (Thu Dec 31 23:48:20 2020 -0500). I unpinned and updated to the latest org-roam commit b0fd12647b94ba6e3cf82a2a5b1ee7655ac07760 (Thu Jan 28 14:41:42 2021 +0100), but it still did not work. I don't see a lot of examples for the `:olp ("%<%Y-%m-%d>")` syntax, so its possible, something is not right with the template expansion, but the `:file-name` and `:head` fields expand just fine. :man_shrugging:

**Comment by asheidan** [comment]
(After double checking my config I realized that my issue was that `:olp` wasn't used at all)

Could the issue be that `org-roam-capture-find-or-create-olp` doesn't do any expansion? My knowledge of the code (and elisp) is terrible, but it seems that the elements of olp is just used as is, without expansion.

```elisp
(defun org-roam-capture-find-or-create-olp (olp)
  ;....
  (dolist (heading olp)  ; Line 468 on 15d864a500d90c9dc2e16d888e93343528ec3941
   ;...
   ))
```

**Comment by patbakdev** [comment]
I think you are right. Maybe the expansion is expected to happen in `org-roam-capture--convert-template` or `org-roam-capture`, but I too am not familiar enough to tell. Oh well. I guess I'll stick with org-journal for moment. Thanks.

**Comment by jethrokuan** [comment]
These should be working now, with `olp` and `datetree` support in the capture templates. Maybe @Wetlize can provide an example template... I don't really use it.

**Comment by dangom** [comment]
Would be nice to have examples for daily/weekly/yearly/whateverly on the docs. Just migrated to v2 and don't really now how to implement that, otherwise I'd have contributed them.
