### ISSUE TITLE
Compiler-macro errors 

### ISSUE THREAD

**Issue by algon-ns** [org-roam/org-roam#1412]
### Description
I get thies lines in my *Messages* buffer, but Emacs debugger do not react

Compiler-macro error for cl--block-wrapper: (wrong-type-argument listp Fortnight-agenda)
Eager macro-expansion failure: (wrong-type-argument listp Fortnight-agenda)
Compiler-macro error for cl--block-wrapper: (wrong-type-argument listp Fortnight-agenda)
Eager macro-expansion failure: (wrong-type-argument listp Fortnight-agenda) [2 times]Compiler-macro error for cl--block-wrapper: (wrong-type-argument listp Fortnight-agenda)
Eager macro-expansion failure: (wrong-type-argument listp Fortnight-agenda)
Compiler-macro error for cl--block-wrapper: (wrong-type-argument listp Fortnight-agenda)
Eager macro-expansion failure: (wrong-type-argument listp Fortnight-agenda) [2 times]

#### Steps to Reproduce

I have no clues

#### Backtrace

does not react 

### Environment

 Emacs: GNU Emacs 28.0.50 (build 2, x86_64-apple-darwin16.7.0, NS appkit-1504.84 Version 10.12.6 (Build 16G2136))
 of 2021-01-30
- Apple iMAC (27-inch, Mid 2011)
              High Sierra 10.12.6
- Framework: nextstep
- Org: Org mode version 9.4.4 (release_9.4.4-199-gbc511b @ /Users/niels/.emacs.d/straight/build/org-agenda/)
- Org-roam: 1.2.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by algon-ns** [comment]
Starting emacs with --debug-init gives the attached backtrace, which looks like it have an error i org-agenda, but this alle dissapear, if I do not have org-roam in my configuration, so it might be a sideeffect, but org-roam is involved.
(beware the traceback i 70 kByte....
[BT-issue1412.txt](https://github.com/org-roam/org-roam/files/5917856/BT-issue1412.txt)

**Comment by nobiot** [comment]
In the backtrack, there is no `org-roam` appear. It seems to rather originates from `require(org-graph-view)`. Perhaps you could try removing this package and see what happens?

**Comment by algon-ns** [comment]
Right,
Sorry
closed
