### ISSUE TITLE
Add custom variable for choose between global properties (#+...) and :PROPERTIES: drawer

### ISSUE THREAD

**Issue by mithraen** [org-roam/org-roam#1415]
### Brief Abstract

org-roam can get tags and aliases from both types of global properties, but org-roam-(add|delete)-(tag|alias) use only #+... format now.

### Proposed Implementation (if any)

Change org-roam--set-global-prop function to check some custom variable, and set it using properties drawer or keywords.

### Please check the following:

- [ ] No similar feature requests

**Comment by d12frosted** [comment]
I belive with #1401 it makes sense to stop supporting `#+XXX` format, but instead switch to properties fully:

1. V2 is going to enforce existence of the ID on the file leve, meaning that each file will contain `:PROPERTIES:` drawer, so why not reuse it for everything?
2. Consistency with heading nodes (we use properties there).

This allows us to remove some code related to `#+XXX` values, as Org Mode doesn't provide API for them unlike properties drawers. 

I think we will need a migration phase, where we move `#+ROAM_ALIAS` and `#+ROAM_TAGS` to properties drawer and use only properties drawer in functions to manipulate aliases and tags. And the next step would be cleaning up the code base 😸 

@jethrokuan what do you think? Is it worth doing before V2? Should it be separate or maybe I should do it in your branch?

**Comment by mithraen** [comment]
I already (in V1) started to use property drawers for roam_* properties, and org-roam-(add|delete)-(tag|alias) just don't work at all.

Maybe custom variable don't needed, just read tags/aliases from properties and keywords, but on change -- remove keywords, and move it's content to properties.

**Comment by d12frosted** [comment]
> I already (in V1) started to use property drawers for roam_* properties, and org-roam-(add|delete)-(tag|alias) just don't work at all.

I see. I agree, those functions are biased towards the pre properties drawer flow. Now we have this indirection. If @jethrokuan is OK to eventually drop support of `#+XXX` style keywords we can process like this:

1. Before V2 we do an 'online' migration. E.g. we `org-roam-(add|delete)-(tag|alias)` reads from global property and from property drawer, merges data and stores in property drawers. 
2. With V2 we do a full migration to properties drawer (add IDs, move aliases and tags).
3. Once done, we remove a pile of redundant code 🎉

**Comment by jethrokuan** [comment]
Closing as v2 is opinionated on this.
