### ISSUE TITLE
Add optional argument to org-roam-(add|delete)-(tag|alias) functions

### ISSUE THREAD

**Issue by mithraen** [org-roam/org-roam#1416]
### Brief Abstract

Now functions for add/delete tags can be used only by user, not from scripts. Adding optional argument can add possibility for creating e.g. user defined hydra for set/unset some tags.

### Please check the following:

- [ ] No similar feature requests

**Comment by d12frosted** [comment]
Now it's in v2 - https://github.com/org-roam/org-roam/pull/1515

**Comment by jethrokuan** [comment]
Closed with #1401
