### ISSUE TITLE
How to change format of the newly created files?

### ISSUE THREAD

**Issue by AtomicNess123** [org-roam/org-roam#1418]
Is it the variable `org-roam-capture--file-name-default`?
Thanks!

**Comment by d12frosted** [comment]
@AtomicNess123 Could you please clarify what you mean by format of the newly created files? Are you talking about [templates][1]?

  [1]: https://www.orgroam.com/manual.html#The-Templating-System

**Comment by AtomicNess123** [comment]
I mean the file name format (YYYMMDD_title). The template would be the content, right?

**Comment by d12frosted** [comment]
@AtomicNess123 Ah, I see. Yes, you still need to change the capture template. See the documentation I've sent you. It describes how to setup template and how to configure file name.

In general, do not touch variables and function with double dashes in the name, e.g. `org-roam-capture--*`. They are considered private by convention in Emacs Lisp and they should be used only if you really understand what you are doing.

**Comment by AtomicNess123** [comment]
Excellent, thanks!
