### ISSUE TITLE
backlinks to locations withint orgmode files possible?

### ISSUE THREAD

**Issue by AtomicNess123** [org-roam/org-roam#1421]
IT's a basic question: whether org-roam could link or back-link to parts of an Orgmode file, i.e., a heading / subheading, and not necessarily a whole file. I may want to link to a specific place in a long Orgmode file, so the idea is that when clicking on the backlink, the specific location is at point, not the whole file. Hope this is clear!

**Comment by d12frosted** [comment]
@AtomicNess123 please read the [manual][1] 😸 All questions you are [asking][2] [lately][3] are covered by manual 😸 In this particular case, checkout [Inserting Links][4] section. That being said, it's possible to link only to headings and not to arbitrary elements of the org mode document. 

By the way, you might be interested in joining [Slack][5], a good place to ask this kind of questions and discuss them. For example, recently there was a conversation related to [supporting links/transclusions][6] not only to headings.

  [1]: https://www.orgroam.com/manual.html
  [2]: https://github.com/org-roam/org-roam/issues/80#issuecomment-772270458
  [3]: https://github.com/org-roam/org-roam/issues/1418
  [4]: https://www.orgroam.com/manual.html#Inserting-Links
  [5]: https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg
  [6]: https://orgroam.slack.com/archives/CTS32BB6J/p1612229824082000

**Comment by d12frosted** [comment]
BTW, I do understand how hard it might be at the beginning, when you only start to setup your `org-roam`, but I highly advice to read the manual to get the overview of what's possible and how different problems are approached :) 

And please, don't be disencouraged by my advice! Do ask questions when something is not clear. But please also spend some time on learning the documentation which is there for you ;)

**Comment by AtomicNess123** [comment]
Thanks so much and you are right, I apologize.
