### ISSUE TITLE
Slack invitation expired

### ISSUE THREAD

**Issue by 3Rafal** [org-roam/org-roam#1424]
### Description
When using Slack channel invitation from readme I get
![image](https://user-images.githubusercontent.com/22241847/107119322-1957f300-6887-11eb-8514-88552d38b8a3.png)

**Comment by jethrokuan** [comment]
Hmm the slack link works, and never expires... closing for now.

**Comment by elliottw** [comment]
When I try the link from orgroam.com I get `This link is no longer active` on the following page. I've been in the slack for a while and stepped out for a few months, are we still using the slack? Looks dead.
