### ISSUE TITLE
[[roam:title*headline]] should display as [[title -> headline]] after save

### ISSUE THREAD

**Issue by dit7ya** [org-roam/org-roam#1430]
### Brief Abstract

Currently if I have a file with title `Notes` and I have a headline `Notes` in another file called, say `Org-mode` , after using [[roam:Org-mode*Note]] and then saving, it displays as `Notes` making it impossible to visually know the difference between the headline difference and the file difference. (Or if there are headlines with same text in two different files the same confusion happens). 

### Proposed Implementation (if any)

I suspect this is due to `org-roam-format-link` and I can fix it with a PR but I am not sure if this will conflict with **v2** efforts. 

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
No longer relevant in v2, it will resolve to the node title.
