### ISSUE TITLE
Using thread while updating database?

### ISSUE THREAD

**Issue by jcguu95** [org-roam/org-roam#1431]
### Brief Abstract
Emacs by nature is single-threaded. While an operation takes too long, effectively it freezes emacs as that's the only thing that can operate at that time. Having more than 6000 nodes, significant freeze (3~10 seconds) happen to me. Threads might come to rescue.

### Proposed Implementation (if any)
Outsource interactions with the database to emacs threads (or other independent program).. so that the process can "run in the background" and don't interrupt the user front-end experience.

I **am willing** to implement this. But I hope there'd be more discussion before I start. So please throw in any concerns! Thank you :-)

### Please check the following:

- [X] No similar feature requests (searched: "thread", "concurrency".. etc)

**Comment by jcguu95** [comment]
Ah, this seems to have been addressed upstream by using async methods. See [here](https://github.com/org-roam/org-roam/pull/1345/commits/d9335f1f26db6df269cbbe44a8c58e1aecbf2380).

**Comment by AloisJanicek** [comment]
I must say I am confused. 

Last year there used to be database-building fn with `async` in its name and if I am not mistaken it was using [jwiegley/emacs-async](https://github.com/jwiegley/emacs-async), now there is asynchrony explicitly mentioned in the docs but how it is actually implemented if not by using using `emacs-async`?

From my personal experience emacs gets blocked for a few seconds when db gets marked dirty and I reach those `org-roam-db-update-idle-seconds`.

**Comment by jcguu95** [comment]
Not sure how that `async` went. But iirc the current method isn't yet published in the stable version. Hopefully they will have it added in the next major release soon.

**Comment by jcguu95** [comment]
@AloisJanicek I tried other branches, but found none either. Raised a question in that [PR](https://github.com/org-roam/org-roam/pull/1345).. hopefully they'll have an answer.
