### ISSUE TITLE
Minor documentation update for `executable-find`

### ISSUE THREAD

**Issue by codeluggage** [org-roam/org-roam#1436]
### Brief Abstract

As a new emacs user it is hard to understand exactly what is meant by "run" and the how + input + output of `exectuable-find` mentioned in the  manual. 

### Long Description

From the docs at https://github.com/org-roam/org-roam/blob/2a1c73c0a395ad166a86f3f7bde50b105c540482/doc/org-roam.org#post-installation-tasks

> Org-roam uses ~emacsql-sqlite3~, which requires ~sqlite3~ to be located on
> ~exec-path~. Please ensure that ~sqlite3~ is installed appropriately on your
> operating system. You can verify that this is the case by executing:
> 
> #+BEGIN_SRC emacs-lisp
>   (executable-find "sqlite3")
> #+END_SRC

How do I "execute executable-find"? Where would I expect to see this output? I've had a hard time finding clear answers to how to run that in emacs. I assume it's because it's such a core part of using emacs that it's not explained everywhere. Some kind of run command that can take a line of elisp, perhaps?

### Proposed Implementation (if any)

This part of the installation steps could be easier for a new user with a few extra details on how + input + output.

- Add a shortcut/command/steps for how to test/verify this
- Perhaps a link that explains how to "execute" something

### Please check the following:

- [x] No similar feature requests

**Comment by kisaragi-hiu** [comment]
How to evaluate Elisp code:

- Press `C-c C-c` with the cursor on that code block in Org mode. You should see a `#+RESULTS:` block showing up. Or
- Place the cursor after the closing paren and run `eval-last-sexp`. You should see the results showing up at the bottom of the window.

Perhaps the manual needs a section explaining Emacs and Org basics so confusion like this can be avoided.

**Comment by codeluggage** [comment]
> Perhaps the manual needs a section explaining Emacs and Org basics so confusion like this can be avoided.

I can imagine many coming to Emacs and/or Org-mode for Org-roam alone, so big :+1: from me on that one.
