### ISSUE TITLE
Open public access to wiki and discussions

### ISSUE THREAD

**Issue by agzam** [org-roam/org-roam#1438]
Can someone please enable Github Discussions and give public access to the Wiki, so people can freely add and modify pages?
 
Also, a sentence in the manual encouraging people to add a link in the wiki if the'd to publish something about Org-roam in their personal blogs.

Thanks!

**Comment by jethrokuan** [comment]
I've enabled Github Discussions just to see what it's about, but discussions primarily take place on Discourse at https://org-roam.discourse.group/.

Not sure what I can wrt to the wiki?

**Comment by agzam** [comment]
Ah, right. Somehow when I was writing the issue, I forgot that we have great Discourse already.

**Comment by jethrokuan** [comment]
I'm going to close GitHub discussions, I think Discourse is sufficient. The wiki is now public.
