### ISSUE TITLE
Redundant line in the minibuffer after starting org-roam-find-file for 1st time

### ISSUE THREAD

**Issue by revrari** [org-roam/org-roam#1440]
### Description

After starting Emacs, if I run `org-roam-find-file` I am prompted to type directly into the minibuffer as follows:

`File: `

The minibuffer prompt is **2 lines** whereas it should be only one. If I escape and cancel and then hit `org-roam-find-file again`, the minibuffer prompt appears correctly with only 1 line. 

#### Steps to Reproduce

Restart Emacs
run `org-roam-find-file`
Escape
run `org-roam-find-file` again

**Comment by jethrokuan** [comment]
I've never seen this before, can you try if this happens with only Org-roam in your Emacs config? Highly doubt it's caused by Org-roam.

**Comment by revrari** [comment]
If I start Emacs with -Q and add this minimal configuration, it is reproducible:

(add-to-list 'load-path "~/.emacs.d/elpa/org-roam-20210128.1341")
(add-to-list 'load-path "~/.emacs.d/elpa/dash-20210210.1449")
(add-to-list 'load-path "~/.emacs.d/elpa/f-20191110.1357")
(add-to-list 'load-path "~/.emacs.d/elpa/s-20180406.808")
(add-to-list 'load-path "~/.emacs.d/elpa/emacsql-20200714.28")
(add-to-list 'load-path "~/.emacs.d/elpa/emacsql-sqlite3-20200914.508")

(require 'org-roam)

**Comment by revrari** [comment]
If I use the `use-package` configuration below instead of `(require 'org-roam)`, the problem disappears:

```
(use-package org-roam
      :ensure t
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-directory "/path/to/org-files/")
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n g" . org-roam-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))
              (("C-c n I" . org-roam-insert-immediate))))
```
This illustrates for me once again the importance of providing a configuration for those who do not wish to use `use-package`.

**Comment by aoibird** [comment]
The previous config doesn't enable org roam mode. Check it with:

```emacs-lisp
(bound-and-true-p org-roam-mode)
```


If the org roam mode isn't enabled, the `org-roam-find-file` will enable it:

```emacs-lisp
(defun org-roam-find-file (&optional initial-prompt completions filter-fn no-confirm)
  (interactive)
  (unless org-roam-mode (org-roam-mode))
  ;; ...
  )
```

`(org-roam-mode)` prints `(org-roam) total: Δ0, files-modified: Δ0, ids: Δ0, links: Δ0, tags: Δ0, titles: Δ0, refs: Δ0, deleted: Δ0`. It takes 2 lines if the width is narrow enough. The minibuffer will fix the height to the text it displays and won't shrink. (The default value of `resize-mini-windows` is `grow-only`.)

If you don't use `use-package`, you can add `(add-hook 'after-init-hook 'org-roam-mode)` to your config.

**Comment by jethrokuan** [comment]
@aoibird's diagnosis seems spot-on.

**Comment by revrari** [comment]
Thank you. This has solved my issue.
