### ISSUE TITLE
Add a way to render\display org-roam links the way Roam displays links to Notes

### ISSUE THREAD

**Issue by spolakh** [org-roam/org-roam#1443]
### Description

Hi! Even though Org-Roam manual advises to not use `org-roam-link-title-format` - `If your version of Org is at least 9.2, consider styling the link differently, by customizing the org-roam-link, and org-roam-link-current faces.` - it still seems to be the only way to make org-roam links render the way Roam renders them (`[[Title of a Linked Note]]`). However, it seems to break auto link renaming:

#### Steps to Reproduce

1. Load Emacs with `(setq org-roam-link-title-format "[[%s]]")`
3. Create two Notes, A and B
4. Add a link to B from A, gets rendered as [[B]]
5. Change the title of B to C
6. Observe that the link to B in A now is rendered as [[[[B]]]] instead of [[C]]

Can you please look into this or advise how to achieve the same visual representation without using `org-roam-link-title-format`?

**Comment by kisaragi-hiu** [comment]
`org-roam-link-title-format` governs how links are *inserted*, not displayed. Run `org-toggle-link-display` to make Org show the brackets.

**Comment by spolakh** [comment]
It seems like `org-toggle-link-display` makes it display the link as `[[file:/path/to/org/roam/B.org][B]]`, not `[[B]]`?

**Comment by jethrokuan** [comment]
To achieve roam-like display would require changing Org's own font-locking rules:

```
(defun org-activate-links (limit)
  "Add link properties to links.
This includes angle, plain, and bracket links."
  (catch :exit
    (while (re-search-forward org-link-any-re limit t)
      (let* ((start (match-beginning 0))
	     (end (match-end 0))
	     (visible-start (- (or (match-beginning 3) (match-beginning 2)) 1))
	     (visible-end (+ (or (match-end 3) (match-end 2)) 1))
	     (style (cond ((eq ?< (char-after start)) 'angle)
			  ((eq ?\[ (char-after (1+ start))) 'bracket)
			  (t 'plain))))
	(when (and (memq style org-highlight-links)
		   ;; Do not span over paragraph boundaries.
		   (not (string-match-p org-element-paragraph-separate
					(match-string 0)))
		   ;; Do not confuse plain links with tags.
		   (not (and (eq style 'plain)
			     (let ((face (get-text-property
					  (max (1- start) (point-min)) 'face)))
			       (if (consp face) (memq 'org-tag face)
				 (eq 'org-tag face))))))
	  (let* ((link-object (save-excursion
				(goto-char start)
				(save-match-data (org-element-link-parser))))
		 (link (org-element-property :raw-link link-object))
		 (type (org-element-property :type link-object))
		 (path (org-element-property :path link-object))
                 (face-property (pcase (org-link-get-parameter type :face)
				  ((and (pred functionp) face) (funcall face path))
				  ((and (pred facep) face) face)
				  ((and (pred consp) face) face) ;anonymous
				  (_ 'org-link)))
		 (properties		;for link's visible part
		  (list 'mouse-face (or (org-link-get-parameter type :mouse-face)
					'highlight)
			'keymap (or (org-link-get-parameter type :keymap)
				    org-mouse-map)
			'help-echo (pcase (org-link-get-parameter type :help-echo)
				     ((and (pred stringp) echo) echo)
				     ((and (pred functionp) echo) echo)
				     (_ (concat "LINK: " link)))
			'htmlize-link (pcase (org-link-get-parameter type
								  :htmlize-link)
					((and (pred functionp) f) (funcall f))
					(_ `(:uri ,link)))
			'font-lock-multiline t)))
	    (org-remove-flyspell-overlays-in start end)
	    (org-rear-nonsticky-at end)
	    (if (not (eq 'bracket style))
		(progn
                  (add-face-text-property start end face-property)
		  (add-text-properties start end properties))
	      ;; Handle invisible parts in bracket links.
	      (remove-text-properties start end '(invisible nil))
	      (let ((hidden
		     (append `(invisible
			       ,(or (org-link-get-parameter type :display)
				    'org-link))
			     properties)))
		(add-text-properties start visible-start hidden)
                (add-face-text-property visible-start visible-end face-property)
		(add-text-properties visible-start visible-end properties)
		(add-text-properties visible-end end hidden)
		(org-rear-nonsticky-at visible-start)
		(org-rear-nonsticky-at visible-end)))
	    (let ((f (org-link-get-parameter type :activate-func)))
	      (when (functionp f)
		(funcall f start end path (eq style 'bracket))))
	    (throw :exit t)))))		;signal success
    nil))
```

You can override Org's `org-activate-links` in this fashion to get `[link]`.

I'm removing `org-roam-link-title-format` in #1401

**Comment by spolakh** [comment]
Thank you, this works! Wonder if it can be made configurable through some sort of org-roam api (through hooks maybe?), but my elisp-foo is not strong enough yet to come up with a nice solution.
I'll close the issue and also retitle it for better searcheability

**Comment by spolakh** [comment]
Actually, wonder what you meant by `Actually I would note that this doesn't work with plain links.`
I've noticed that after I define `org-activate-list` the way you put above, both org-roam and non-org-roam (e.g. regular urls to websites, etc) get rendered the same way - `[Description of a link to website]`. Hate to ask, but is there any way to only render `file:` (ideally, only `file:` links that belong to org-roam, but that's not really important to my usecase), not the others?

**Comment by jethrokuan** [comment]
This request needs to be posted upstream to Org, there's no exposed api for styling links.
