### ISSUE TITLE
Suggestion: Split note

### ISSUE THREAD

**Issue by j-steinbach** [org-roam/org-roam#1447]
### Brief Abstract

I want to be able to split a note (by moving specific headings/regions into new note-files). 

### Long Description

Often I re-visit a note, only to notice that it has grown too big. In this case I divide the note into sub-headings. But this usually is not enough (and also bad practice for the sake of atomic notes). The next step would be to split the current note into multiple smaller notes.

This is already do-able in emacs/org-mode, but this approach does not take the org-roam specific linking, tags and aliases into account. Therefore I believe this should be solved by org-roam.

_This also leads to the case of combining notes, i.e. select two (or more) notes, create a new note that contains each "old" note as a heading, update all links/references to the new note, then delete the old notes._

#### Example

If I have a file

```
#title: Hello World

* Heading One
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

* Heading Two
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
```

Then I want to be able to split the file and move each/specific headings into a new note

```
#title: Hello World

[Link to Heading One]
[Link to Heading Two]
```

```
#title: Heading One

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
[Link to Hello World]
```

```
#title: Heading Two

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
[Link to Hello World]
```

### Proposed Implementation (if any)

I believe that it is best if each heading in an org-roam note file should be "splitable":

- Select a heading
- Command a "split"
- Take the heading as the title of the new note
- Insert the contents of the heading as note contents
- Link the original file and the new note
- Update all links and references that linked to the heading in the old file

This gives the user a tool to maintain their notes and leaves the decision which headings to split to their choice.

---

[This](https://stackoverflow.com/questions/33885244/emacs-org-mode-how-can-i-refile-a-subtree-to-a-new-file) seems to be the org-mode way, but I am wary of the underlying org-roam database. There are likely to be issues with updating the links, references, ...

### Please check the following:

- [X] No similar feature requests; I searched for "split" in the issues, but didn't see anything.

**Comment by thriveth** [comment]
Perhaps a silly question, but is it not sufficient to simply create a new note and move the text over that you want to go there?

**Comment by jethrokuan** [comment]
In #1401 , there's a command `org-roam-refile` for this purpose.

**Comment by j-steinbach** [comment]
@thriveth What if you have a note `Random Note` that links to `Heading One`? I believe that that link is somehow filed in the org-roam-db. You would have to update it, too. And there likely are a few more problems.

@jethrokuan #1401 is titled "V2", which means that this feature is coming in the next iteration of org-roam? _(Sorry for the question, I am not very familiar with github collaboration.,)_ Also, is there a reason that "Motivation for this change" in the pull request is empty?

Lastly, can you give some input on _"This also leads to the case of combining notes, i.e. select two (or more) notes, create a new note that contains each "old" note as a heading, update all links/references to the new note, then delete the old notes."_? I believe it to be the logical antithesis of a split feature.

**Comment by natask** [comment]
@j-steinbach as long as you use ids for your headings, placing the headline within another file also preserves backlinks.

**Comment by j-steinbach** [comment]
The problem is that I want to get rid of headings. You can see in my example above that the headings become new notes.

**Comment by natask** [comment]
you can with file level id.
taking from your example.
``` org
#title: Hello World

* Heading One
:PROPERTIES:
:ID:       e0375891-9402-4c32-9b7a-0e82bfbd3ae
:END:
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
```

and convert it to this
notice that the headline property drawer has been promoted into a file level property drawer
``` org
:PROPERTIES:
:ID:       e0375891-9402-4c32-9b7a-0e82bfbd3ae
:END:
#title: Heading One

 Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
```

**Comment by j-steinbach** [comment]
Thanks! Didn't know that.

---

Unfortunately I am in the death throes of my thesis, so I won't try/test this for the time being. 
_(Fiddling with Emacs = Procrastination. Writing on Github = Procrastination. Times are tough..)_

Your suggestion seems like a viable (interim) solution to me, but I believe it is best to keep this "issue" open until #1401 drops with `org-refile` - there likely is going to be some discussion happening in the future.

**Comment by PRESFIL** [comment]
@j-steinbach , now you also have `org-roam-extract-subtree` (#1710)

**Comment by j-steinbach** [comment]
Based on my meager lisp-understanding this very much looks like the thing I was asking and hoping for. Awesome!

*Note: I have not yet had the opportunity to switch to v2.. looking at the swamp I am currently in, I won't be testing this feature any time soon.*

---

From my side this can be closed. (Not sure who actually is supposed to do that -- If no one answers back in the next 24h, then I will close this.)
