### ISSUE TITLE
[V2] Title is mandatory - org-roam-node-find fail with error

### ISSUE THREAD

**Issue by nobiot** [org-roam/org-roam#1450]
### Description
In V2, `org-roam-node-find` fails with this error (see image below), when title is not present in a note.
![image](https://user-images.githubusercontent.com/12507865/112033611-e10e2a80-8b3d-11eb-8b60-c03ac66d1fb5.png)

This happens when only one of the notes has the issue (and the completion does not appear in minibuffer).

#### Steps to Reproduce

1. Create a note without a title defined via `#+title:` keyword
2. org-roam-db-sync (automatic)
3. Try `org-roam-node-find`

In my case, the title is stored in the file level property drawer like this:

```
:properties:
:id: 2021-03-02T190042
:title: Open Knitting Machine Scheme
:date: 2021-03-02
:category: R
:orig_name: ~/evergreen/work/2021-03-02T190042__R.org
:end:
```

#### Backtrace
My edebug shows that this part returns the error message:
```
org-roam-node.el
function: org-roam-node--completions
L169 (cons (propertize alias 'node node) node
````

#### Expected Results

Minibuffer shows the list of nodes

#### Actual Results

Minibuffer shows the error above
(it works as expected when `#+title: Title` is added).

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-w64-mingw32)
 of 2020-08-21
- Framework: N/A
- Org: Org mode version 9.4.4 ( @ c:/Users/nobiot/.config/emacs/elpa/org-9.4.4/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by nobiot** [comment]
Please consider backward compatibility for these two elements:

- Ideally, I would like to keep using the file level property drawer to define title -- no problem in V1.

- Also, V1 allows for missing title (substituted by the filename, if title is not present).

**Comment by nobiot** [comment]
@jethrokuan ...

Missing the tile of nodes seems to be a pervasive issue.
Now `org-roam-buffer` gives me "Wrong type argument: stringp, nil)

Steps to repro:
1. Create note (with title, and ID) that works
2. Create another note without a title, link to the first note
3. Go back to the first note, do `org-roam-buffer`

`org-roam-node-insert-section` fails with the error above.
It's this location:

```
;; org-roam-node.el
;; cl-defun org-roam-node-insert-section
;; L220
(insert (concat (propertize (org-roam-node-title source-node)
```

**Comment by nobiot** [comment]
For my personal quirk, this is largely because I have maintained title in file property drawer. Let me know if you do not intend to support this feature; then I will do a custom way to add it to the cache db.

Having said this, I can imagine many users will also encounter this issue of missing titles -- so it's probably worth tackling somewhere more centrally -- I will try to see if there is any good way, but I believe you will have the best idea...

**Comment by jethrokuan** [comment]
File nodes will have their titles default to the file relative name if `#+title` is not present.

**Comment by nobiot** [comment]
Thank you, understood.

Then the [issue above](https://github.com/org-roam/org-roam/issues/1450#issuecomment-806188119) at `org-roam-node-insert-section` used to generate backlinks section on `org-roam-buffer` is an issue.

I can repo this adding/removing the title of a file that is a source of a backlink.

If you prefer to have another GH issue open, let me know; happy to.

**Comment by nobiot** [comment]
I see. Thank you.
Then the issue I mentioned above is still a problem (I can repro it now, and also with delete/add the title of the backlink source file).

https://github.com/org-roam/org-roam/issues/1450#issuecomment-806188119

**Comment by nobiot** [comment]
Now with e62cf7f, the issue for the backlink I mentioned earlier is resolved. Thanks!
