### ISSUE TITLE
[V2] org-roam-db-sync does not finish; org-roam-db-insert-link goes into infinate loop

### ISSUE THREAD

**Issue by nobiot** [org-roam/org-roam#1452]
### Description
`org-roam-db-sync` does not finish when any file has this issue reported below.
... I am hoping you can repro this issue.

#### Steps to Reproduce

1. Create a new note (see the sample below)
2. Create a level 2 headline directly from the top level (no level 1 headline); add a URL link inside it
3. Run org-roam-db-sync (in this case, I did it manually via `M-x`)

```
:PROPERTIES:
:ID:       20210323T204730.591696
:END:
#+title: Testing Heading and https

** Heading 1-1
https://google.com
```
...

#### Backtrace
No backtrace (infinate loop)

#### Expected Results

org-roam-db-sync finishes correctly and almost instantaneously (as only one new note).

#### Actual Results

`org-roam-db-insert-link` does not return; it seems to be in an infinite loop.
This while loop below does not exit for some reason.

```
;; org-roam-db.el
;; org-roam-db-insert-link 
;; L381-383
        (while (and (not (setq source (org-id-get)))
                    (not (bobp)))
          (org-up-heading-or-point-min)))
```

The issue does not happen when level 2 heading is included in level 1 heading, like this:
```
:PROPERTIES:
:ID:       20210323T204730.591696
:END:
#+title: Testing Heading and https

* Heading 1

** Heading 1-1
https://google.com
```

### Environment

    Emacs: GNU Emacs 27.1 (build 1, x86_64-w64-mingw32)
    of 2020-08-21

    Framework: N/A

    Org: Org mode version 9.4.4 ( @ c:/Users/nobiot/.config/emacs/elpa/org-9.4.4/)

    Org-roam: 2.0.0

**Comment by jethrokuan** [comment]
Thanks for the detailed bug report as always :slightly_smiling_face: I think you found a bug in `org-up-heading-or-point-min`

```
(defun org-up-heading-or-point-min ()
  "Move to the heading line of which the present is a subheading, or point-min.
This version is needed to make point-min behave like a virtual
heading of level 0 for property-inheritance.  It will return the
level of the headline found (down to 0) or nil if already at a
point before the first headline or at point-min."
  (when (ignore-errors (org-back-to-heading t))
    (if (< 1 (funcall outline-level))
	(org-up-heading-safe)
      (unless (= (point) (point-min)) (goto-char (point-min))))))
```

This function doesn't go to `point-min` when at the level 2 heading without a level 1 heading.

**Comment by nobiot** [comment]
Do you think it's worth reporting it to upstream?
Do you know how? (I am assuming it's via the mailing list; it's two steps away - I'm not on it - and a bit of inconvenience for me at the moment).

**Comment by nobiot** [comment]
@jethrokuan ,

`org-roam-id-at-point` has the following issue. Let me know if you prefer for me to raise another GH issue.

Adding this note below goes into an infinite loop in `org-roam-id-at-point`.
Notes with no ID in `org-roam-directory` with a link (I tried only URL, but I think any link type will have the same issue).

```
#+title: V2 test no ID with link


 http://google.com
```

**Comment by jethrokuan** [comment]
https://github.com/org-roam/org-roam/pull/1401/commits/47c3b024d7b976c0740618da2a9b7049f22f1d06 should fix the above.

**Comment by nobiot** [comment]
Yes, it does for me. Thank you.
