### ISSUE TITLE
This will not work: Local-variables not being accepted / loaded

### ISSUE THREAD

**Issue by herop** [org-roam/org-roam#1453]
I was able to solve this by putting the following in my config:

(add-to-list 'safe-local-variable-values
             '(org-roam-directory . "."))

_Originally posted by @anthrolisp in https://github.com/org-roam/org-roam/issues/80#issuecomment-653931789_

**Comment by herop** [comment]
Nice and all, but:

This will not be called with my config at start
And still the local variable org-roam-db-location will be thrown an error by Messages buffer
Finally, how can both list items combined (at the right place in the correct syntax)?
It would mean a great deal to me if you could help.

So there is still no solution - at least I can't see one - for multiple org-roam-directories.

Regards,
Jochen

**Comment by nobiot** [comment]
If you want want to have one combined list, why would you like to have two root directories (two databases)?

Does this way work for you?
>  I have two sub-folders (private and work) under one org-roam-directory, one database. And the sub-folders are both symlinks, pointing to folders Cloud synced by different providers. Sub-folders are set to be org-roam tags, so it’s easy to filer one or the other．

Source: https://org-roam.discourse.group/t/merge-two-roam-databases/1369/2?u=nobiot

**Comment by nobiot** [comment]
Essentially, I have two sub-folders under single root folder (one database). But they physically reside in two totally separate locations in the OS's filesystem. I needed this set up so that these two folders are synced with different Cloud services.
