### ISSUE TITLE
Reversed edges arrows when building graph with `org-roam-graph`

### ISSUE THREAD

**Issue by PRESFIL** [org-roam/org-roam#1458]
### Description

When I build a graph of my notes, the branches have the opposite direction. I don't have a lot of notes right now, so I know for sure that right now the point of the arrow is pointing to the note that the link is in, not the target of the link. Do I understand correctly that it was intended as `source - > target`? 

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam-graph`

#### Expected Results

A note with a link should point to the source of the link.

#### Actual Results

Links are drawn, but they have a reverse direction.

![image](https://user-images.githubusercontent.com/20644917/112594054-64b76800-8e19-11eb-95f9-0d0dd378f0bf.png)

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
- Org-roam version: 1.2.3

**Comment by nobiot** [comment]
How about this?
https://org-roam.discourse.group/t/graphing-how-to-reverse-the-direction-of-the-arrows/1116

Other options and values are documented in [this part of Org-roam documentation](https://www.orgroam.com/manual.html#Graph-Options) with a link to documentation of Graphviz (underlying graphicing engine).

**Comment by PRESFIL** [comment]
I came across this setting in the documentation. It worked for me.

But I am wondering what exactly is meant by the direction of the arrow in `org-roam`, whether such ambiguity would not obscure. 

Thanks for the additional link.

**Comment by jethrokuan** [comment]
The arrow links from source to target, I thought that would be the most natural. If you don't like it you can reverse it as @nobiot has pointed out.

v2 has temporarily removed graphviz support, probably going to repackage that elsewhere.

**Comment by PRESFIL** [comment]
> I thought that would be the most natural

That's it, but like I said, they were in the reverse order

> **Actual Results**
> 
> Links are drawn, but they have a reverse direction.

If it gets fixed in a new package it will be fine

**Comment by jethrokuan** [comment]
> That's it, but like I said, they were in the reverse order

> Expected Results
> A note with a link should point to the source of the link.

A note "A" with a link to note "B", should have the arrow in the direction A -> B no? The current setting is as I intended it to be.

**Comment by PRESFIL** [comment]
> A note "A" with a link to note "B", should have the arrow in the direction A -> B no? The current setting is as I intended it to be.

This is not the case, unfortunately. At the moment, when I removed the graphviz setting, this is not the case. The arrows on my graph are of the form A <- B.

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
- Org-roam version: 1.2.3 20210405.133 (melpa)
