### ISSUE TITLE
Inserting a link to a new file doesn't use an ID link when it should

### ISSUE THREAD

**Issue by adql** [org-roam/org-roam#1461]
### Description

When inserting a link to a new file, a link to the filename is inserted, even when the new file has an `ID` property and `org-roam-prefer-id-links` is `t`.

A minor issue since it's easy to change manually, however with the move to v2 in which all links are to IDs it may be worth paying attention, for the sake of the habit.

#### Steps to Reproduce

1. `(setq org-roam-prefer-id-links t)` if it was set to nil.
1. Run `org-roam-insert` and create a new note (say `test`).
2. Make sure the new file has an `ID` property.
3. `C-c C-c`.

#### Backtrace

No error.

#### Expected Results

A link `[[id:<new_file_id>][test]]` is inserted, just as happens when the target file already exists.

#### Actual Results

A link `[[file:<filename>][test]]` is inserted.

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
- Framework: Prelude
- Org: Org mode version 9.4.5 (9.4.5-7-gbcfe6f-elpaplus @ ~/.emacs.d/elpa/org-plus-contrib-20210405/)
- Org-roam: 1.2.3

**Comment by adql** [comment]
I'm surprised this hasn't been noticed, but I have searched and couldn't find a bug report. Excuse me if my search was weak :)

**Comment by jethrokuan** [comment]
Please see https://org-roam.discourse.group/t/why-are-file-links-being-created-when-ids-exist/1395 for an explanation of what you're seeing.

**Comment by adql** [comment]
Ok, thanks, I understand. So it depends on the database being updated before the link is inserted, which only happens after the new file has been saved - but that doesn't happen before completing the capturing process with `C-c C-c`. Setting `(setq org-roam-db-update-method 'immediate)` will make it quicker, but even then you have to remember doing `C-x C-s C-c C-c` if you want the link to be if ID type (indeed works for me).

I suppose that adding to `org-roam-file-setup-hook` a call to `save-buffer` will automate this, but will have the unwanted side effect of keeping notes that were discarded with `C-c C-k` from the capture buffer.
