### ISSUE TITLE
Links from org properties are not indexed

### ISSUE THREAD

**Issue by lyndondrake** [org-roam/org-roam#1464]
### Description

While `org-roam` seems to be working, e.g. `org-roam-find-file` correctly shows all my notes including their tags, the `org-roam` buffer shows "No backlinks" even when backlinks do exist.

I've got rid of all my `.elc` files and tried deleting the `org-roam.db` file too. It gets rebuilt fine, but still no backlinks.

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.3.0, Carbon Version 164 AppKit 2022.3)
 of 2021-03-28
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /Users/lyndon/.emacs.d.doom/.local/straight/build-27.2/org-mode/)
- Org-roam: 1.2.3

**Comment by lyndondrake** [comment]
Apologies - I got this wrong - it turns out that links from within an org properties bin are not indexed:
```
** Genesis 23
:PROPERTIES:
:Note: [[file:20210302093117.org][Genesis 23]]
:END:
```

doesn't generate a backlink in the Genesis 23 note. I'm assuming that's by design… I wondered if there's some way then to either change the behaviour, or to include a link in a form that's hidden from export (which is why I've dumped it in a properties bin).

**Comment by jethrokuan** [comment]
This is because the Org parser itself doesn't detect items within property drawers as links. This could be changed to just searching forward for the link regex, but then it would be an inconsistency with the Org syntax parsing itself which can lead to its own surprises.

**Comment by lyndondrake** [comment]
Ah, that makes sense then.

**Comment by lyndondrake** [comment]
My use case is that in my thesis document, I want to add references to relevant notes. I don't want those links to show up in my formatted document though, hence using a property drawer item.

Can you suggest another option for having (effectively) a hidden link?

Or would there be a way for me to add a save-hook that looks for a link in a particular property — in my case, the `:Note:` property?

**Comment by d12frosted** [comment]
@lyndondrake 

This is a bummer for me as well. While I was migrating some notes to
`org-roam` style of links I discovered that properties drawer does not
support links. They are displayed as links, but semantically they are
not! Meaning that open link may not work as expected (for example,
=id= links), elements API doesn't parse them as links (meaning that so
many things break, including org-roam backlinks). Though I can't find
a relevant link to documentation anymore.

In my case I needed to manipulate properties that link to other notes
(e.g. read and write) and using properties API would be convenient
alas it doesn't support links. So I had to use description lists and
write my own API around that. Which sucks.

But I was fine with these links being part of the visible content. In
your case I think the easiest approach would be to use some reference
outline with `noexport` tag, as org export mechanism ignores such
headings:

```org
* Some Topic
:PROPERTIES:
:ID:                     451ca5fb-a9c9-437b-8ec3-7f7a5bbfd584
:END:

Aspernatur modi harum porro. Ut ullam autem iusto rerum iste esse
adipisci. Saepe aut provident dolorem nostrum reprehenderit. Cum
debitis perferendis facilis laborum. Quia vel reiciendis porro
repellendus.

** References :noexport:

- [[id:269a7a4e-f06b-4ab8-80cf-3af9b30a14e2][note]]

```

Just keep in mind that for better compatibility with V2 you should not
have `ID` property in the references header.

Hope that works for you.

**Comment by jethrokuan** [comment]
> Or would there be a way for me to add a save-hook that looks for a link in a particular property — in my case, the :Note: property?

Iirc only the :PROPERTIES: drawer has this special property, all other drawers have their links parsed as you would expect.

**Comment by d12frosted** [comment]
@jethrokuan other drawers are getting exported. E.g. when I export to html the following file, I see the `note` link. I wonder if there is a way to `:noexport:` it haha.

```org
* Some Topic
:PROPERTIES:
:ID:                     451ca5fb-a9c9-437b-8ec3-7f7a5bbfd584
:END:
:REFERENCES:
- [[id:269a7a4e-f06b-4ab8-80cf-3af9b30a14e2][note]]
:END:

Aspernatur modi harum porro. Ut ullam autem iusto rerum iste esse
adipisci. Saepe aut provident dolorem nostrum reprehenderit. Cum
debitis perferendis facilis laborum. Quia vel reiciendis porro
repellendus.
```

**Comment by myshevchuk** [comment]
The variable `org-export-with-drawers` controls drawer export.

From its docstring:


```
Non-nil means export contents of standard drawers.

When t, all drawers are exported.  This may also be a list of
drawer names to export, as strings.  If that list starts with
not, only drawers with such names will be ignored.

This variable doesn't apply to properties drawers.  See
org-export-with-properties instead.

This option can also be set with the OPTIONS keyword,
e.g. "d:nil".
```

**Comment by lyndondrake** [comment]
@d12frosted that works well - I get the link indexed by `org-roam` now, and while I haven't setup that export yet I can see how it can work (thanks @myshevchuk).

**Comment by PRESFIL** [comment]
Related #195.

**Comment by jethrokuan** [comment]
Added a short post on Discourse summarizing the discussion: https://org-roam.discourse.group/t/faq-keeping-links-in-org-drawers/1499

**Comment by PRESFIL** [comment]
Am I correct in understanding that exporting does not affect indexing in any way? `org-roam` doesn't use exported files?

**Comment by jethrokuan** [comment]
> Am I correct in understanding that exporting does not affect indexing in any way? `org-roam` doesn't use exported files?

Yes.
