### ISSUE TITLE
Support for gpg files for org-roam-dailies

### ISSUE THREAD

**Issue by alicjanos** [org-roam/org-roam#1465]
### Brief Abstract

org-roam-dailies-capture-templates does not allow to save journal in `org.gpg` files because it always append them with `org`. Please provide support for org.gpg files.

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
If you're on v2, you can specify the use encryption by specifying the file extension in the capture template.

This requires a breaking change in v1, which I have no intention to make.

**Comment by jethrokuan** [comment]
This is now supported on latest commit. by adding `.gpg` to your dailies templates.
