### ISSUE TITLE
Org files with potentially 100s of links impact on performance

### ISSUE THREAD

**Issue by oatmealm** [org-roam/org-roam#1466]
I wasn't sure if this is a bug or something unavoidable, so opening this here. 

I was playing around with Sacha Chua's example of timestamped transcriptions of YouTube clips, where the timestamps link back to the video position on the timeline. Such file can produce hundreds of links and saving them is notably slow. 

Wondering if there might be a way to factor this in when saving, to avoid maybe handling at least external links? i.e. I'm assuming Roam is only interested in links to other notes...

I understand big files are not the ideal scenario in a zettelkasten approach etc, but I'm using Roam for all sorts.

**Comment by jethrokuan** [comment]
We're also interested in external links, because these links can be reference links.

v2's parsing is a lot simpler, and I haven't noticed performance issues so far. Maybe give it a go and see if the performance there is acceptable?

**Comment by jethrokuan** [comment]
@oatmealm v2 is now merged, let me know if it's still laggy.
