### ISSUE TITLE
[V2] filetags not immediately added during capture process

### ISSUE THREAD

**Issue by nobiot** [org-roam/org-roam#1470]
### Description

If you add tags via `#+filetags` keyword during a capture process, it won't be stored in org-roam's cache. You will need to open the file and then save again. 

From what I can see, this is because `org-file-tags` is not populated during the capture process.
I will be sending a PR on this -- I was not sure if it was a fix that you like; please use it as an illustration of the problem.

#### Steps to Reproduce

1. M-x `org-roam-node-find` to create a new file
2. Maintain a tag via #+filetag: keyword (sample file below); no body text needed
3. Complete the capture process
4. `org-roam-node-find` does not show the tag
5. Add a space, save the file; the tag appears in `org-roam-node-find`

```
:properties:
:id: 2021-04-15T173128
:modified: 2021-04-15T173136
:end:
#+title: test tag 17
#+filetags: meeting
```

#### Backtrace
No error

#### Expected Results
Tags get cached after completing the capture process

#### Actual Results
Tags do not get cached after completing the capture process.
You need to save the file again.

**Comment by jethrokuan** [comment]
Yeah I think I noticed this as well, `org-file-tags` is a variable that's set at an odd timing, may be best not to rely on it.

Except `#+filetags` isn't all-encompassing, it's possible to inherit tags from other files, but this is probably a niche use-case.

**Comment by jethrokuan** [comment]
The commit sets `org-file-tags` right before the database is updated, should resolve this issue.

**Comment by nobiot** [comment]
Yes. Works well. Thank you.
