### ISSUE TITLE
V2 is not resilient to missing file-level ID

### ISSUE THREAD

**Issue by jmay** [org-roam/org-roam#1475]
I haven't tried this in V1. I've only been paying attention to org-roam with V2 and the focus on nodes with unique IDs.

If you create a .org file in your org-roam directory that *does not have a file-level PROPERTIES drawer with an ID, but there are IDs within headings in the file* (e.g. when migrating an existing collection of org files to org-roam) then on save, org-roam will throw a warning:

`EmacSQL had an unhandled condition: "near line 315: UNIQUE constraint failed: nodes.id"`

Heading-level identifiers are still saved to the org-roam database.

My expectation is that the system should be more resilient to source files that don't satisfy format requirements. Possibly even automatically add the top-level properties drawer? But for a file that has only a single top-level heading with an ID, I'm not sure it makes sense to have a mandatory ID for the entire file as well.

**Comment by jethrokuan** [comment]
@jmay can you check if this still occurs for you on the latest commit?

You're right in that file-level properties should be optional, it's just that in the code I'd mistakenly assumed anything at `(point-min)` is at outline-level 0, while a heading `*` at point 0 violates this assumption.

**Comment by jmay** [comment]
Looks good! Error no longer occurring. I'll reopen if this error returns.
