### ISSUE TITLE
RET opens random file rather than exits the minibuffer

### ISSUE THREAD

**Issue by revrari** [org-roam/org-roam#1477]
### Description

Invoking `<RET>` after one has invoked `org-roam-find-file` does not exit the minibuffer as expected but opens a random file in the org-roam directory.  `<RET>` in the minibuffer is bound to command `exit-minibuffer`, which is an interactive compiled Lisp function in ‘minibuffer.el’. This problems seems only to occur when `icomplete mode` is enabled. 

#### Steps to Reproduce

enable `icomplete-mode`
invoke `org-roam-find-file`
`<RET>`
...
-->

#### Expected Results

One would expect that one is prompted for an org-roam capture template or that one would exit the minibuffer. 

#### Actual Results

Random file opened--which is always the same file. 

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.2 (build 1, x86_64-w64-mingw32)
 of 2021-03-26
- Framework: Vanilla
- Org: Org mode version 9.4.4 (release_9.4.4 @ c:/msys64/mingw64/share/emacs/27.2/lisp/org/)
- Org-roam: 1.2.3

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
What is the value of `org-roam-capture-templates` here?

**Comment by revrari** [comment]
(setq org-roam-capture-templates
	    '(("d" "default" plain #'org-roam-capture--get-point :file-name "%<%Y-%m-%d>-${slug}" :head "#+title: ${title}
#+ROAM_TAGS: %^{org-roam-tags}
#+created: %u
#+last_modified: %U
%?" :unnarrowed t :jump-to-captured t)
     ("l" "clipboard" plain #'org-roam-capture--get-point "%i%a
" :file-name "%<%Y%m%d%H%M%S>-${slug}" :head "#+title: ${title}
#+ROAM_TAGS: %?
" :unnarrowed t :prepend t :jump-to-captured t)
     ("s" "series" plain #'org-roam-capture--get-point
      (file "~/diary/sermon-template.txt")
      :file-name "%<%Y-%m-%d>_series_${slug}" :head "#+title: ${Title}
#+ROAM_TAGS: Series
#+DATE: %T
#+VENUE: ${Venue}
#+FORMAT: ${Format}
#+DESCRIPTION: ${Main concept of service}
#+OPTIONS: \\n:t
" :unnarrowed t :immediate-finish t :jump-to-captured t)

**Comment by jethrokuan** [comment]
> Random file opened--which is always the same file.

This may mean you have an Org-roam file with an empty title, which would be created the first time you tried it.

If I follow your reproduction steps, I get a file that looks like `DATE-NOW-.org`.

Try deleting the random file and trying again, this time you might see the prompt for a capture template, for creating a new file with blank title.
