### ISSUE TITLE
Links in a divided folder are fragile.

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [org-roam/org-roam#1478]
[This lies somewhere between a bug report and a feature request; I apologize if I chose the less appropriate label.]

Suppose your org repo is divided into folders "public/" and "personal/", as you might do if you want some of them in a public Git repo and others in a personal one. Links from the public repo to the personal one will use paths like "../personal/<filename>.org", and are robust to being moved to the other repo. But links from the personal one to another file in the personal one will use paths like "<filename>.org". If such content is then moved from the personal repo to the public one, the links will break.

One easy solution would be to allow a user to configure their repo to use absolute rather than relative paths. (This has the unfortunate effect of making *all* the links break if the repo is moved, but they could all be fixed with a single call to `sed`.)

A less robust solution would be to simply always back out with "../". The problem with that strategy is that it only works if every subfolder of the repo is flat and every file lies in a subfolder (rather than the top folder).

**Comment by d12frosted** [comment]
I think the most robust solution is to use id links instead of path links. Absolute path is as fragile as relative.

**Comment by maikol-solis** [comment]
Just curious. With V2 this issue won't be a problem anymore, isn't?

**Comment by d12frosted** [comment]
@maikol-solis  It is already possible with V1 - id links are supported for a long time. With V2 you'll have no other choice :)

**Comment by maikol-solis** [comment]
Thanks @d12frosted. Yes I transitioned to V2 like a month ago. My question here was if this issue (and possibly many others) are still valid once V2 is in master. 

Thanks

**Comment by d12frosted** [comment]
@maikol-solis I see 😸 Yes, with V2 it's not an issue anymore, unless you manually link notes via `file` path.

**Comment by maikol-solis** [comment]
I think this issue now is not longer valid and it can be closed.
