### ISSUE TITLE
[v2] duplicate node.id condition not handled

### ISSUE THREAD

**Issue by alanz** [org-roam/org-roam#1480]
### Description

If an org-roam file is accidentally duplicated (for me it was a syncthing conflict that did it), when org-roam starts up it reports a sql uniqueness constraint violated, and it stops the db update.

```
Error (use-package): org-roam/:config: EmacSQL had an unhandled condition: "near line 27: UNIQUE constraint failed: nodes.id"
```
I think it would help to have a handler that at least shows what the offending id is that triggered the problem, to help sorting it out.

#### Steps to Reproduce

Shut down emacs.

Duplicate any file in the org-roam directory

Start up emacs.

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
 of 2021-03-27, modified by Debian
- Framework: N/A
- Org: Org mode version 9.4.5 (release_9.4.5-321-ge641d3 @ /home/alanz/.emacs.d/straight/build/org/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/org-roam/org-roam/commit/be81a3a7383451043fe560c596e0ce8f925c6486

**Comment by jmay** [comment]
Here is some work-in-progress for gracefully reporting duplicates. Updates code in `org-roam-db.el`. Does not handle duplicate IDs at the file level yet.

This has been an excuse to learn how to do exception handling in elisp. I'm bothered by my use of `t` in the handler clause; I couldn't figure out how to match the `emacsql-constraint` error condition.

```elisp
(defun org-roam-db-map-headlines (fns)
  "Run FNS over all headlines in the current buffer."
  (org-with-point-at 1
    (org-map-entries
     (lambda ()
       (catch 'loop
         (dolist (fn fns)
           (condition-case err
               (funcall fn)
             (t
              (message "%s at %s (%s) in %s"
                       (error-message-string err)
                       (org-link-display-format (nth 4 (org-heading-components)))
                       (org-id-get)
                       (buffer-file-name))
              (throw 'loop nil)))))))))
```
