### ISSUE TITLE
Notes added in a certain time slice

### ISSUE THREAD

**Issue by gianscarpe** [org-roam/org-roam#1483]
### Brief Abstract
I was wondering if this could be of any interests for other users. I'm looking for a way to filter out notes based on their timestamp, e.g., every notes added last week. Is there already a similar feature?
### Proposed Implementation (if any)
A org-roam function to filter the notes added in a certain time slice. Function can ask for a "from" and a "to" day, and filter basing onto the timestamp in the name of org-roam notes.

**Comment by jmay** [comment]
This would only work if:
- notes are strictly one-per-file
- all the filenames follow the same timestamp convention.

But if those constraints hold then your suggested implementation should work.

I've suggested a more complicated approach in #1485 that would be applicable to org-roam V2. Filtering timestamped notes/nodes in that environment requires scanning the contents of every file.
