### ISSUE TITLE
Proposal for timestamping notes at time of capture (V2)

### ISSUE THREAD

**Issue by jmay** [org-roam/org-roam#1485]
org-roam should provide an *optional* setting to have timestamps added to new notes/nodes at time of capture.

Timestamps should go into the PROPERTIES drawer of each node (alongside the node ID). The properties drawer is transferred when a node is refiled, so additional properties such as a timestamp would be preserved.

Users should optionally be able to customize the field name used for that timestamp.

Here is the implementation I'm experimenting with:
```elisp
(defvar org-roam-timestamp-field "CREATED")

(defun org-roam--insert-timestamp ()
  (org-entry-put nil org-roam-timestamp-field (format-time-string "[%Y-%m-%d %a %H:%M]"))
)

(advice-add 'org-roam-capture--goto-location :after #'org-roam--insert-timestamp)
```

Some sort of utility should be provided to populate timestamps into existing nodes. Maybe by looking through the `org-roam-directory` for nodes with IDs and inserting a timestamp taken from the file creation date?

**Comment by jethrokuan** [comment]
Your above implementation doesn't always work, because the point may not be in an OLP that is not the same as the newly created node.

e6acc40 adds `org-roam-capture-new-node-hook`, which is run on new node creation.

```
(defun org-roam--insert-timestamp ()
  (org-entry-put nil "CREATED" (format-time-string "[%Y-%m-%d %a %H:%M]")))
(add-hook 'org-roam-capture-new-node-hook #'org-roam--insert-timestamp)
```
> Some sort of utility should be provided to populate timestamps into existing nodes. 

These sort of ad-hoc utility functions will not be added into Org-roam. There isn't any support for processing these user-added properties anyway (they are not, and will likely not be cached by Org-roam)

**Comment by jmay** [comment]
You're right, `new-node-hook` is much better than trying to patch into something via advice.

And I agree that it is best to avoid including migration utilities in the package, that just adds more code to be maintain.ed Such things can be posted publicly, somewhere.

I would not want to add extra properties into the org-roam database cache. Any queries based on timestamp should be rare so can be slow, scanning all the files would be fine.

**Comment by jethrokuan** [comment]
Closing as this is possible already as above.
