### ISSUE TITLE
Org-roam Manual change

### ISSUE THREAD

**Issue by EvanMath** [org-roam/org-roam#1486]
Hey everyone,
I hope this is the right place for this. I think guys you should change the `org-roam-find-index` to `org-roam-jump-to-index` in here https://www.orgroam.com/manual.html#Index-File. I tried to run it and the documentation says that is "This command is obsolete since org-roam 1.1.0; use
org-roam-jump-to-index instead."

**Comment by jethrokuan** [comment]
Thanks for the report. This is no longer relevant in v2.
