### ISSUE TITLE
Cancelling org-roam-node-insert still writes a file to disk

### ISSUE THREAD

**Issue by jeyj0** [org-roam/org-roam#1490]
### Description

When using `org-roam-node-insert` in V2, a file is still written to disk.

#### Steps to Reproduce

1. use org-roam V2
2. run `org-roam-node-insert`
3. type in a new name for the note, hit enter
4. Cancel the capture using `C-c C-k`

#### Backtrace
n/a

#### Expected Results

No file is written to disk

#### Actual Results

File is written to disk, populated with the content of the capture

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
- Framework: N/A
- Org: Org mode version 9.4.4 (9.4.4-27-gb712b9-elpa @ /nix/store/w3cgqgvmsyrnvfxjn5hrcqsjiaiz6ajh-emacs-packages-deps/share/emacs/site-lisp/elpa/org-20210315/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/38b5375354e26165aaf520ea692a2f7d25b33edd

**Comment by jethrokuan** [comment]
Now if Org-roam creates a new file during capture, and the capture is aborted, the file is saved but then immediately deleted. Not the ideal fix, but the simplest, without having to advice org-capture.
