### ISSUE TITLE
Node is not autosaved when org-roam-directory is specified by symlink (V2)

### ISSUE THREAD

**Issue by jmay** [org-roam/org-roam#1491]
If `org-roam-directory` is specified with a path that is resolved via symlink, then file saves might not reliably trigger saving of changed node info to the database.

I haven't checked enough different cases to determine exactly when this occurs. There seems to be some dependency on how the file was opened (via dired, via org-roam-node-find, etc).

I think this is a bug in `org-roam--org-roam-file-p`, which does `(expand-file-name org-roam-directory)`. But `expand-file-name` does not resolve symlinks. Possibly adding `file-truename` here will be sufficient.

- Emacs: GNU Emacs 28.0.50 (build 5, x86_64-apple-darwin20.3.0, NS appkit-2022.30 Version 11.2.2 (Build 20D80))
 of 2021-03-31
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4-253-g4d463e @ /Users/jmay/.emacs.d/straight/build/org/)
- Org-roam: 2.0.0
- commit 1440802

**Comment by jethrokuan** [comment]
We used to have `file-truename` everywhere in Org-roam, but symlink resolution is slow and we made the decision not to resolve symlinks. As per the README, just adding `file-truename` when specifying the Org-roam directory should be sufficient.
