### ISSUE TITLE
Don't (re-) introduce multiple kinds of tags!

### ISSUE THREAD

**Issue by publicimageltd** [org-roam/org-roam#1492]
I just browsed through the v2 commits and saw that ROAM-TAGS have been added again. Over at discourse, I had learned that ROAM-TAGS were discontinued in favor of the filetags system. I would strongly urge to not re-introduce ROAM-TAGS again. These are my reasons:

 - They add semantic confusion, since "tags" can mean both.
 - Functions which e.g. operate with tags have to differentiate between both possiblities, e.g. when adding a tag to the file.
 - A special property needs special treatment, whereas filetags handling can profit from org mode's built in functionality.

I see but one reason to maintain that doubling:

 - ROAM-TAGS allow to tag a file without tagging all nodes which belong to it (subheadings).

So the question is: Why would we need that? My guess is: to differentiate types of pages (files). So why not make that difference explicit and call the property ROAM_PAGETYPE or something like that? (But note that here too, the whole thing suffers from an ambiguity: Why should files have special tagging (that is, types), whereas other "nodes" do not share that possiblity? I think that's the real problem, and org roam should just settle with the universal system "nodes can be tagged, period")

After all, adding headings on a page _is_ a hierarchical operation, which differentiates within a given node. So if we don't want that hierarchy, the user should just have one page - one item.....

**Comment by jmay** [comment]
I think I agree with @publicimageltd here. org-mode has a built-in tagging system that includes inheritance.

What is the use-case for a separate non-inheritable tagging mechanism that only applies at the file level?

org-mode also has handling for a `#+CATEGORY` keyword. May that would be a better match for this requirement? I'm not clear on the intended use of categories in org, I've never used them.

**Comment by publicimageltd** [comment]
@jethrokuan Thanks for the fast reaction! Given that you mainly remove ROAM-TAGS because you favor the built-in org functionality for tags, using `+CATEGORY` as a replacement, as @jmay suggested, seems a good compromise. That could be useful, for example, to differentiate different sorts of org roam files like 'org dailies', 'zettelkasten notes', 'system administration notes', whatever. Choosing a node, then, could be restricted to a category using `C-u`. Also in org mode, categories show up in the agenda, etc.

**Comment by mricke** [comment]
@publicimageltd I would think that nobody here using or knowing of categories, is an indication that they're not beneficial for most use cases of org-roam and org in general. Why not just file_tags for file level tagging? Am I missing something or had development already moved on to that?

**Comment by publicimageltd** [comment]
I thought there might be a need to categorize files (not nodes); for which a sort of extra tagging is useful. And since calling these tags is confusing (see my first post), we could just move to another label. But really, I don't think we need it. I just had a look at the database, we can also differentiate "file level tags" by looking at the position of the tagged heading (which is 1 for file tags). Anyways, I am glad there are not two kind of tags now, so I'll close that specific issue.
