### ISSUE TITLE
Normalize tag strings in db

### ISSUE THREAD

**Issue by publicimageltd** [org-roam/org-roam#1494]
Looking at the database, I see that in the column `tags`, the inherited tags are inserted as propertized strings. That adds extra operations for extracting those tags (converting them with `substring-no-properties`, as well as for joining them in an SQL query. 

So to allow for faster checking of tagged nodes, I suggest (a) to only use string values for the "tags" column, and (b) to add an extra column "inherited" with a boolean value.

What do you think?

**Comment by jethrokuan** [comment]
> (a) to only use string values for the "tags" column

Yeah I missed the property removal for headline nodes

> (b) to add an extra column "inherited" with a boolean value.

Sounds good, but not sure if we really require this information, so I'm leaving it out for now.
