### ISSUE TITLE
V2 `org-roam-dailies-capture-templates` not adding data to expected day

### ISSUE THREAD

**Issue by stindrago** [org-roam/org-roam#1518]
### Description

Affected:
- `org-roam-dailies-capture-yesterday`
- `org-roam-dailies-capture-tomorrow`
- `org-roam-dailies-capture-date`

When you are capturing a day **different than today**, it doesn't matter if it is a day into the past or future, the modified file will be always today.

https://github.com/org-roam/org-roam/blob/3a3c4d97d558912c296253cd805d1afa0b141456/org-roam-dailies.el#L66

#### Steps to Reproduce

With default configuration.

Today is `2021-05-10`

1.  Call `org-roam-dailies-capture-tomorrow`.
2. Write something in the capture buffer (notice the file name).
3. `C-c C-c` to save.

#### Expected Results

`daily/2021-05-11.org` modified.

#### Actual Results

`daily/2021-05-10.org` is modified instead.

**Comment by jethrokuan** [comment]
This should be fixed on latest commit in v2, do confirm when you get the chance
