### ISSUE TITLE
Re-incorporate org-roam-graph into v2

### ISSUE THREAD

**Issue by gcoladon** [org-roam/org-roam#1521]
### Brief Abstract

Many of us love the graphing functionality, but it's temporarily been removed from v2

### Long Description

My understanding is that the change in schema broke org-roam-graph, and that fixing it wasn't a high priority, so it was removed for now.

### Proposed Implementation (if any)

I'm up for attempting to get org-roam-graph.el to work again, though I expect to have a lot of questions as I learn how to do that.

### Please check the following:

- [X] No similar feature requests

**Comment by zaeph** [comment]
Hi.

Basic re-implementation wouldn't be too tricky, since we'd mostly need to redo the pipes between db and `-graph`.  You could try to have a go at it by comparing with the schema for v1 to make the necessary adjustments.

…Otherwise, I could look at it soon-ish.

**Comment by gcoladon** [comment]
I'm up for giving it a go. Where's the right place to ask questions about functions used in `org-roam-graph.el` that seem to have disappeared between v1 and v2, like `org-roam--with-temp-buffer` for instance? Should I create a feature branch PR for this work and ask there? Or would somewhere else be best?

**Comment by zaeph** [comment]
You'd probably be better off starting a PR and pinging us on Slack/IRC if you'd like guidance.  Although, we probably won't be able to give you precise answers without looking at the code ourselves, at which point we might as well fix it ourselves.  So try it, but if you run into too many walls, just ping us back and we'll jump in.

**Comment by herop** [comment]
Implementing or not: 
- Even though I'm completely in V2 now
- Now V1 code in config
- My error is:
- Error in private config: config.el, (file-missing Cannot open load file No such file or directory org-roam-graph)
Since I cannot find any evidence of calling something even related to roam-graph I'm lost.
And no, in my config.el (or .org for that matter) is neither related stuff.
Please help me here.
Thank you very much in advance and have a nice day,
Jochen

**Comment by maikol-solis** [comment]
> Implementing or not:
> 
>     * Even though I'm completely in V2 now
> 
>     * Now V1 code in config
> 
>     * My error is:
> 
>     * Error in private config: config.el, (file-missing Cannot open load file No such file or directory org-roam-graph)
>       Since I cannot find any evidence of calling something even related to roam-graph I'm lost.
>       And no, in my config.el (or .org for that matter) is neither related stuff.
>       Please help me here.
>       Thank you very much in advance and have a nice day,
>       Jochen

All your V1 config is not valid if your are using V2. 

The function `org-roam-graph` does not exist yet in V2. This affects directly to `org-roam-server` if you are using this package as well. 

We have to wait until these functions are translated into the new db scheme.

**Comment by herop** [comment]
You of course are right. Uninstalled the package and world is spinning again. 
Thank you very much and have a great day. 
Jochen.

**Comment by maikol-solis** [comment]
No problem. Glad you have solved this issue.

**Comment by jethrokuan** [comment]
Done, I think :)
