### ISSUE TITLE
scratch buffer is in org roam mode and readonly

### ISSUE THREAD

**Issue by hans-d** [org-roam/org-roam#1525]
### Description

After loading org-roam v2, the scratch buffer is:
- in org roam mode
- readonly

#### Steps to Reproduce

in my init.el
```
(use-package org-roam
    :straight (:branch "v2")
    :config
    (setq org-roam-directory "~/org/roam")
    :hook
    (after-init . org-roam-mode))
```
start emacs, switch to scratch buffer

(disabling this import and restart does not have this crippled scratch buffer)

#### Backtrace

no error is triggered, even with `(setq debug-on-error t)` in the init

M-x list-buffers shows
```
CRM Buffer                 Size Mode             File
 %  *scratch*                 0 Org-roam         ~/
```

#### Expected Results

scratch buffer not impacted

#### Actual Results

scratch buffer impacted

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.4.0, Carbon Version 164 AppKit 2022.44)
 of 2021-05-16 (brew "railwaycat/emacsmacport/emacs-mac")
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-g3c241a @ /Users/hansd/.emacs.d/straight/build/org/)
- Org-roam: 2.0.0

straight freshly pulled from git: commit 226669d989d9c66d072b9e732202d0fac350756

**Comment by jethrokuan** [comment]
>     :hook
    (after-init . org-roam-mode))

This is incorrect in v2. Use

: config
(org-roam-setup)

**Comment by hans-d** [comment]
much better, thanks. Overlooked that part in the docs, my bad.
