### ISSUE TITLE
V2 - org-roam-dailies-find-today / find-tomorrow - org-id-add-location: Wrong type argument: hash-table-p, nil

### ISSUE THREAD

**Issue by liambresnahan** [org-roam/org-roam#1526]
### Description
Having just installed org-roam v2 and toggled it on via `org-roam-setup`. I am getting an issue when running `org-roam-dailies-find-today`. On running this I get an error - `org-id-add-location: Wrong type argument: hash-table-p, nil`

#### Steps to Reproduce
1. Load Emacs
2. Run `org-roam-setup`
3. Run `org-roam-dailies-find-today` or other variations of the same command

#### Backtrace
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  puthash("497e22a1-eebe-4978-bf99-4c1b85188430" "~/Code/org/daily/2021-05-29.org" nil)
  org-id-add-location("497e22a1-eebe-4978-bf99-4c1b85188430" "/Users/lbresnahan/Code/org/daily/2021-05-29.org")
  org-id-get(1 create)
  org-id-get-create()
  (prog1 (org-id-get-create) (run-hooks 'org-roam-capture-new-node-hook))
  (save-excursion (goto-char p) (let* ((node (and t org-roam-capture--node)) (id (and node (org-roam-node-id node)))) (if id (org-entry-put p "ID" id))) (prog1 (org-id-get-create) (run-hooks 'org-roam-capture-new-node-hook)))
  (let (p) (let* ((val (or (org-roam-capture--get :if-new) (user-error "Template needs to specify `:if-new'")))) (if (consp val) (let* ((x47 (car val))) (cond ((eq x47 'file) (let* (...) (if ... ... nil))) ((eq x47 'file+olp) (let* (...) (if ... ... nil))) ((eq x47 'file+head) (let* (...) (if ... ... nil))) ((eq x47 'file+head+olp) (let* (...) (if ... ... nil))) ((eq x47 'file+datetree) (let* (...) (if ... ... nil))) ((eq x47 'node) (let* (...) (if ... ... nil))) (t nil))) nil)) (save-excursion (goto-char p) (let* ((node (and t org-roam-capture--node)) (id (and node (org-roam-node-id node)))) (if id (org-entry-put p "ID" id))) (prog1 (org-id-get-create) (run-hooks 'org-roam-capture-new-node-hook))))
  org-roam-capture--goto-location()
  (cond ((plist-get org-roam-capture--info :ref) (let* ((node (and t (org-roam-capture--get-node-from-ref (plist-get org-roam-capture--info :ref))))) (if node (progn (set-buffer (org-capture-target-buffer (org-roam-node-file node))) (goto-char (org-roam-node-point node)) (widen) (org-end-of-subtree t t)) (org-roam-capture--goto-location)))) ((and (org-roam-node-file org-roam-capture--node) (org-roam-node-point org-roam-capture--node)) (set-buffer (org-capture-target-buffer (org-roam-node-file org-roam-capture--node))) (goto-char (org-roam-node-point org-roam-capture--node)) (widen) (org-end-of-subtree t t) (org-roam-node-id org-roam-capture--node)) (t (org-roam-capture--goto-location)))
  (let ((id (cond ((plist-get org-roam-capture--info :ref) (let* ((node ...)) (if node (progn ... ... ... ...) (org-roam-capture--goto-location)))) ((and (org-roam-node-file org-roam-capture--node) (org-roam-node-point org-roam-capture--node)) (set-buffer (org-capture-target-buffer (org-roam-node-file org-roam-capture--node))) (goto-char (org-roam-node-point org-roam-capture--node)) (widen) (org-end-of-subtree t t) (org-roam-node-id org-roam-capture--node)) (t (org-roam-capture--goto-location))))) (org-capture-put :template (org-roam-capture--fill-template (org-capture-get :template))) (org-roam-capture--put :id id) (org-roam-capture--put :finalize (or (org-capture-get :finalize) (org-roam-capture--get :finalize))))
  org-roam-capture--get-point()
  org-capture-set-target-location()
  org-capture-goto-target("d")
  #f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x1ff523a04245>)((4) "d")
  apply(#f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x1ff523a04245>) ((4) "d"))
  (let ((+file-templates-inhibit t)) (apply orig-fn args))
  +file-templates-inhibit-in-org-capture-a(#f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x1ff523a04245>) (4) "d")
  apply(+file-templates-inhibit-in-org-capture-a #f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x1ff523a04245>) ((4) "d"))
  org-capture((4) "d")
  (let* ((props (plist-put props :call-location (point-marker))) (org-capture-templates (mapcar #'(lambda (template) (org-roam-capture--convert-template template props)) (or templates org-roam-capture-templates))) (org-roam-capture--node node) (org-roam-capture--info info)) (if (and (not keys) (= (length org-capture-templates) 1)) (progn (setq keys (car (car org-capture-templates))))) (org-capture goto keys))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:goto :keys :node :info :props :templates :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:goto :keys :node ..." (car --cl-keys--)))))) (let* ((props (plist-put props :call-location (point-marker))) (org-capture-templates (mapcar #'(lambda (template) (org-roam-capture--convert-template template props)) (or templates org-roam-capture-templates))) (org-roam-capture--node node) (org-roam-capture--info info)) (if (and (not keys) (= (length org-capture-templates) 1)) (progn (setq keys (car (car org-capture-templates))))) (org-capture goto keys)))
  (let* ((goto (car (cdr (plist-member --cl-rest-- ':goto)))) (keys (car (cdr (plist-member --cl-rest-- ':keys)))) (node (car (cdr (plist-member --cl-rest-- ':node)))) (info (car (cdr (plist-member --cl-rest-- ':info)))) (props (car (cdr (plist-member --cl-rest-- ':props)))) (templates (car (cdr (plist-member --cl-rest-- ':templates))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:goto :keys :node ..." (car --cl-keys--)))))) (let* ((props (plist-put props :call-location (point-marker))) (org-capture-templates (mapcar #'(lambda ... ...) (or templates org-roam-capture-templates))) (org-roam-capture--node node) (org-roam-capture--info info)) (if (and (not keys) (= (length org-capture-templates) 1)) (progn (setq keys (car (car org-capture-templates))))) (org-capture goto keys))))
  org-roam-capture-(:goto (4) :node #s(org-roam-node :id nil :file nil :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title nil :properties nil :olp nil :tags nil :aliases nil :refs nil) :templates (("d" "default" entry "* %?" :if-new (file+head "/Users/lbresnahan/Code/org/daily/%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))) :props (:default-time (24755 7300) :call-location #<marker at 6960 in *Messages*>))
  org-roam-dailies--capture((24755 7300) t)
  (let* ((time-str (let ((org-read-date-prefer-future prefer-future)) (org-read-date nil nil nil (if goto "Find daily-note: " "Capture to daily-note: ")))) (time (org-read-date nil t time-str))) (org-roam-dailies--capture time goto) (if goto (progn (run-hooks 'org-roam-dailies-find-file-hook))))
  org-roam-dailies-capture-date(t nil)
  org-roam-dailies-find-date()
  funcall-interactively(org-roam-dailies-find-date)
  call-interactively(org-roam-dailies-find-date record nil)
  command-execute(org-roam-dailies-find-date record)
  counsel-M-x-action("org-roam-dailies-find-date")
  ivy-call()
  ivy-read("M-x " ("org-roam-dailies-find-previous-note" "org-roam-dailies-find-today" "toggle-debug-on-error" "org-roam-dailies-find-yesterday" "org-roam-dailies-find-tomorrow" "org-roam-setup" "org-roam-capture" "doom/reload" "eval-buffer" "org-roam-buffer" "package-install" "org-roam-mode" "dired" "doom/info" "package-autoremove" "org-roam-doctor" "org-roam-buffer-toggle" "org-mode" "doom/upgrade" "flyspell-mode" "package-delete" "evil-tutor-start" "org-id-store-link" "org-roam-node-find" "rgrep" "widen" "calendar" "org-capture" "org-set-effort" "customize-group" "org-cut-subtree" "org-mode-restart" "org-paste-subtree" "recover-this-file" "customize-variable" "org-narrow-to-subtree" "package-list-packages" "enlarge-window-horizontally" "org-roam-dailies-capture-today" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

#### Expected Results

Expected to start the correct daily org file

#### Actual Results

Error as described above

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.4.0, Carbon Version 164 AppKit 2022.44)
 of 2021-05-17
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /Users/lbresnahan/.emacs.d/.local/straight/build-27.2/org-mode/)
- Org-roam: 2.0.0

**Comment by jethrokuan** [comment]
Your `org-id-locations` is nil, maybe this will help:

```
(require 'org-id)
(setq org-id-track-globally t)
```

**Comment by liambresnahan** [comment]
I added this to my `config.el` (I'm using Doom) and am still getting the same error. On checking the variable is set it appears to be the case (shown as `t` when running `describe-variable`. I ended up calling `org-id-update-id-locations` and it started working. 

Is this something that needs to be either altered in the wiki or in the code itself?

**Comment by jethrokuan** [comment]
Your system seems to have reached a bad state somehow. Either way this issue lies with `org-id`, and not `org-roam`, so i'm closing this issue.

**Comment by exAClior** [comment]
If case anyone meets the same problem, following the blog mentioned blow, you may solve the problem by add a line that runs the function (org-id-update-id-locations) in your config file. 

https://github-wiki-see.page/m/org-roam/org-roam/wiki/Hitchhiker%27s-Rough-Guide-to-Org-roam-V2
