### ISSUE TITLE
Multiple org-roam directory - Ignoring unsafe file local variable for org-roam-directory 

### ISSUE THREAD

**Issue by Felixaverlant** [org-roam/org-roam#1527]
Hi there!
Thank you for this amazing product! I'm using it all the time and I feel the need to have more than one directory now.

### Description
I am trying to setup [21.1 How do I have more than one Org-roam directory?](https://www.orgroam.com/manual.html#How-do-I-have-more-than-one-Org_002droam-directory_003f) .

I've added the code provided in a .dir-locals.el.
Everything works fine on the primary org-roam. I can insert, search...

But for the second org-roam, it throws the error provided below. 
If I search or insert, it will do everything on the primary org-roam. 
If I describe org-roam-directory, it's set on the primary org-roam directory. 

Inside my config.el, I've tried to add: 
`(add-to-list 'safe-local-variable-values '(org-roam-directory . "."))`

But it has no effect whatsoever.

#### Steps to Reproduce

I just have to load an org file on the second org-roam to have this error thrown.

#### Backtrace
On load of an org-file of the second org-roam.
```
Ignoring unsafe file local variable: org-roam-db-location
Ignoring unsafe file local variable: org-roam-directory
```

#### Expected Results

I expect to be able to use the second one.

#### Actual Results

I can only use the primary org-roam.

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, aarch64-apple-darwin20.4.0, NS appkit-2022.44 Version 11.3.1 (Build 20E241))
 of 2021-05-23
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /Users/me/.emacs.d/.local/straight/build-28.0.50/org-mode/)
- Org-roam: 1.2.3

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

Thank you!
Best.

**Comment by Felixaverlant** [comment]
Hi, it is a doom-emacs related issue with how [elisp-mode package is configured](https://github.com/hlissner/doom-emacs/blob/26a0244f03a6beb5d9dfb25ccc27c8a69b33002a/modules/lang/emacs-lisp/config.el). 
Best

**Comment by Just-Insane** [comment]
Were you able to find a resolution to this so that you are able to use a second org-roam with doom-emacs?

**Comment by Felixaverlant** [comment]
> Were you able to find a resolution to this so that you are able to use a second org-roam with doom-emacs?
> 
> E: nevermind, setting `(setq-default enable-local-variables t)` in config.el prompts the user to mark the variables as safe when using doom-emacs

I did but then migrated to org-roam v2 and it didn't work anymore.

**Comment by Just-Insane** [comment]
This is my working config with v2:

`/<some other org-roam>/.dir-locals.el`:
```elisp
((nil . (
	 (eval . (setq-local org-roam-directory (expand-file-name "./")))
	 (eval . (setq-local org-roam-db-location (expand-file-name "./org-roam.db"))))))
```

and the line in `~/.doom.d/config.el`:
```elisp
;; Enable local variables
(setq-default enable-local-variables t)
```

Upon entering the new org-roam folder, you will be prompted to accept the local variables.

**Comment by ntharim** [comment]
@us

**Comment by ntharim** [comment]
@Just-Insane Did you find that running `org-roam-db-sync` in the second `org-roam-directory` adds nodes to the first one's database instead of the second one?

**Comment by Just-Insane** [comment]
I did find that the first time, but after deleting both db files and resyncing the second folder and then the main one I didn't have problems.

I also don't have the second folder as a sub folder of the main though, as I figured that might cause issues.
