### ISSUE TITLE
org-roam v2 conflicts with org-babel-tangle

### ISSUE THREAD

**Issue by jkroes** [org-roam/org-roam#1531]
### Description

org-roam inserts property drawers on every heading in init.org--used to generate init.el via org-babel--but only if the following is present at the end of init.org:

```
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t)
# End:
```

#### Steps to Reproduce

1. Launch emacs.
2. `org-roam-find-file` to load org-roam.
3. Open init.org and modify it anyhow.
4. Save init.org.
5. Every heading with an org-mode src block is automatically given a property drawer with an ID on save.
6. `git restore` to discard changes.
7. Launch emacs.
8. Delete the following:
```
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t)
# End:
```
9. Repeat steps 2-4. The property drawers are no longer added on save. It also suffices to `(setq after-save-hook nil)` rather than following steps 8-9. 

### Environment
- Emacs: GNU Emacs 27.2 (build 1, arm-apple-darwin20.3.0, NS appkit-2022.30 Version 11.2.3 (Build 20D91))
 of 2021-03-27
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-gf72a65 @ /Users/jkroes/.emacs.d/straight/build/org/)
- Org-roam: 2.0.0

**Comment by jkroes** [comment]
I traced the issue to a single option: ~org-id-link-to-org-use-id~. When I disable this before invoking org-babel-tangle, everything seems to run smoothly.
```
(defun roam-tangle (old-func &rest args)
    (setq org-id-link-to-org-use-id nil)
    (apply old-func args)
    (setq org-id-link-to-org-use-id t))
(advice-add 'org-babel-tangle :around 'roam-tangle)
```

**Comment by carwin** [comment]
I ran into this issue myself and was able to solve it by setting `org-id-link-to-org-use-id` to `'create-if-interactive`. This stopped the tangling process from inserting a property drawer all over my config files.
