### ISSUE TITLE
Error reading from stdin

### ISSUE THREAD

**Issue by tuh8888** [org-roam/org-roam#1532]
### Description
I seem to be having the same issue as #1364 . Except my systemd is forking and --daemon, yet still fails.

### Environment

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
Can you call other commands that require Org-roam like `counsel-M-x` or `counsel-find-file`? If not, then the issue isn't something Org-roam can fix.

**Comment by tuh8888** [comment]
I think I figured out a solution to the problem though I don't understand why it works. I'm using spacemacs with uses `use-package` to initialize and load org-roam.  Spacemacs has this line in its call to `use-package org-roam`: 

`:hook (after-init . org-roam-mode)`

 which I believe starts org-roam-mode after everything else has loaded. Removing this line remedies the problem, and `org-roam-mode` can be called later without any issue. Perhaps this is Spacemacs' problem, but it seems odd to me that simply starting `org-roam-mode` interferes so profoundly with `counsel-M-x` or `completing-read` or whatever it is under the hood. I can see in my terminal that called `emacs --deamon` that it is awaiting input ("Find file:" for `counsel-find-file). Typing something in that terminal and pressing enter returns control to Emacs.

**Comment by jethrokuan** [comment]
Org-roam changed the way things were loaded a little, feel free to reopen if still an issue.
