### ISSUE TITLE
[v2] a debugging tip with Empty SQL vector expression

### ISSUE THREAD

**Issue by randomwangran** [org-roam/org-roam#1534]
Just want to share my experience with V2 migration b183fd47bde6d61a6cef0ef041bfa596487190c3.

If the file-level info is like this:
```src
:PROPERTIES:
:ID:       15be2774-f063-40a3-a489-ab7e65ab54d9
:ROAM_ALIASES:
:END:
#+TITLE: C\+\+
```
Emacs will through an error, which is very hard to detect the cause.

```
emacsql-error: Invalid SQL statement: "Empty SQL vector expression."
```
`:ROAM_ALIASES:` is automatically generated by this [script](https://gist.github.com/jethrokuan/02f41028fb4a6f81787dc420fb99b6e4/revisions) which was written by @jethrokuan with inputs from @d12frosted

Just make sure `:ROAM_ALIASES:` has something.

I spent a lot of time finding the root cause. I hope someone else can save a little bit of time just in case.

**Comment by d12frosted** [comment]
🤔 [this script][1] should not cause such problem because `vulpea-buffer-prop-get` and `vulpea-buffer-prop-get-list` return `nil` on empty values/strings. Though I am really curious, what was the original note that become malformed during migration process.

```emacs-lisp
;; if roam_key is present but is empty, ROAM_REFS will not be create
(when-let* ((ref (vulpea-buffer-prop-get "roam_key")))
    (org-set-property "ROAM_REFS" ref)
    (let ((case-fold-search t))
      (org-with-point-at 1
        (while (re-search-forward "^#\\+roam_key:" (point-max) t)
          (beginning-of-line)
          (kill-line 1)))))
```

Usage example:

```org-mode
:PROPERTIES:
:ID:       15be2774-f063-40a3-a489-ab7e65ab54d9
:END:
#+TITLE: C\+\+
#+ROAM_ALIAS:
```

```emacs-lisp
> (vulpea-buffer-prop-get "roam_alias")
nil

> (vulpea-buffer-prop-get-list "roam_alias")
nil
```

--- 

While I was writing this message, I realised that `vulpea-buffer-prop-get` still may cause a problem when you have an empty string of non-zero length (e.g. multiple trailing spaces). Fixed that in https://github.com/d12frosted/vulpea/pull/92/commits/f65671a8aa454c09013b24cbd9139f7cfdf9ca9e

[1]: https://gist.github.com/jethrokuan/02f41028fb4a6f81787dc420fb99b6e4#gistcomment-3737019

**Comment by randomwangran** [comment]
Hi @d12frosted :

Sorry for the delaying this response.  V2 is so good that I enjoy it too much.

The migration was not smooth probably because I have some personal hooks in Org-mode.  I remembered that I executed and killed the migration script a couple of times before the database was built. The root cause might be very hard to detect. 

The migration script is good. I test it with the problematic file again. The `:ROAM_ALIASES` is successfully added to the `:PROPERTIES:` drawer.

```elisp
(defun org-roam-v1-to-v2 ()
  ;; Create file level ID
  (org-with-point-at 1
    (org-id-get-create))
  ;; Replace roam_key into properties drawer roam_ref
  (when-let* ((refs (mapcan #'split-string-and-unquote
                            (cdar (org-collect-keywords '("roam_key"))))))
    (let ((case-fold-search t))
      (org-with-point-at 1
        (org-set-property "ROAM_REFS" (combine-and-quote-strings refs))
        (while (re-search-forward "^#\\+roam_key:" (point-max) t)
          (kill-line 1)))))

  ;; Replace roam_alias into properties drawer roam_aliases
  (when-let* ((aliases (mapcan #'split-string-and-unquote
                               (cdar (org-collect-keywords '("roam_alias"))))))
    (let ((case-fold-search t))
      (org-with-point-at 1
        (org-set-property "ROAM_ALIASES" (combine-and-quote-strings aliases))
        (while (re-search-forward "^#\\+roam_alias:" (point-max) t)
          (kill-line 1)))))

  ;; Replace #+roam_tags into #+filetags
  (org-with-point-at 1
    (let ((case-fold-search t))
      (while (search-forward "#+filetags:" nil t)
        (replace-match "#+filetags:" nil t))))
  (save-buffer))
```

P.s.: I also enjoy your [blog ](https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5.html)about dynamic agendas. It is really cool!

Thanks for your contribution @d12frosted and the community. I really appreciate it.
