### ISSUE TITLE
[V2] Support ROAM_ALIASES for non-file-level nodes

### ISSUE THREAD

**Issue by jeyj0** [org-roam/org-roam#1535]
### Brief Abstract

I've tried adding `:ROAM_ALIASES:` for a headline-level node, however that caused an error, so I'm assuming it's not supported yet.

### Long Description

I tried:

```
* My normal headline
:PROPERTIES:
:ID:       8abf5b7d-2147-470b-8468-554476cf6b5a
:ROAM_ALIASES: "Aliased headline"
:END:
```

### Please check the following:

- [ ] No similar feature requests

**Comment by jethrokuan** [comment]
This should've been fixed in https://github.com/org-roam/org-roam/pull/1528, please check if you're on the latest commit.

**Comment by jeyj0** [comment]
Nvm, I hadn't even thought of checking to update first. Sorry for that.
