### ISSUE TITLE
Enable customization of character replacement when generating file names

### ISSUE THREAD

**Issue by salutis** [org-roam/org-roam#1543]
`org-roam` (v2) converts spaces to underscores (`_`) when forming file names:

```
(let* ((pairs `(("[^[:alnum:][:digit:]]" . "_")  ;; convert anything not alphanumeric
```

I would like to use the more standard (in Emacs) dash character (`-`). As an example, I would like "hello world" to become `hello-world` and not `hello_world`.

Would it be possible to add a customization point here?

P.S. What in the world are "slugs"?

**Comment by aruscher** [comment]
> What in the world are "slugs"?
Basically, it's the short name of a given article or in other words the file name. (https://en.wikipedia.org/wiki/Slug_(publishing))

I will try to implement this. I will reference to this issue in the corresponding pull request.

**Comment by aruscher** [comment]
@salutis See pull request

**Comment by aruscher** [comment]
For a proper discussion why this feature has not been integrated, see: https://github.com/org-roam/org-roam/pull/1544#issuecomment-857605271 and the following two comment
This comment describes how the slug-generation has to be adapted for your own customization: https://github.com/org-roam/org-roam/pull/1544#issuecomment-860260777

@jethrokuan Can be closed.

**Comment by salutis** [comment]
@aruscher Thank you!
