### ISSUE TITLE
Org Roam needs to manually run org-roam-db-build-cache on every startup

### ISSUE THREAD

**Issue by komali2** [org-roam/org-roam#1547]
### Description

I'm having some issues around my db. Lately, on every startup, `org-roam-db-build-cache` results in 

```
(org-roam) total: Δ0, files-modified: Δ0, ids: Δ0, links: Δ0, tags: Δ0, titles: Δ0, refs: Δ0, deleted: Δ0
```

when it's run automatically. However, when I wait for startup to finish, and then run with `M-x`, I see:

```
(org-roam) Processed 0/451 modified files...
(org-roam) Processed 1/451 modified files...
(org-roam) Processed 2/451 modified files...
``` 

etc. 

I'm running

`GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23) of 2020-12-14`

With `Spacemacs v.0.300.0` and org-roam version `1.2.3`. 

### Environment

```
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23)
 of 2020-12-14
- Framework: Spacemacs
- Org: Org mode version 9.4.5 (9.4.5-93-gbc857b-elpaplus @ /home/caleb/.emacs.d/elpa/27.1/develop/org-plus-contrib-20210510/)
- Org-roam: 1.2.3
```

**Comment by komali2** [comment]
My config file is here: https://github.com/komali2/Configs/blob/master/emacs/.spacemacs

**Comment by d12frosted** [comment]
I don't see you calling anything from roam in your init. My suggestion is to move org-roam-directory configuration from config to init function, as I suspect something happens on-load and before you set that variable.

Cheers,
***@***.***

**Comment by komali2** [comment]
Ah, that seemed to be the issue! Thank you.
