### ISSUE TITLE
Setting up org-roam-protocol with qutebrowser - not getting a capture with indicated template and in intended directory

### ISSUE THREAD

**Issue by gmachnicki** [org-roam/org-roam#1548]
Hi,

I am trying to set-up a webpage note capture following [this](https://www.reddit.com/r/emacs/comments/m7ofbh/setting_up_orgroam_protocol_in_qutebrowser/) 
I am able to get an action in Emacs, however it is not what I expect. As shown in the screenshot below, emacs can open a file, but if I continue with the process it will do so at an nonexistent ~/org-roam-protocol/.../.../... very long path. It does not call the org-roam-capture-ref-template of interest. And the name of the file does not look as expected.
 
![Screenshot from 2021-06-14 13-40-25](https://user-images.githubusercontent.com/4349523/121928021-1d54bf80-cd16-11eb-9f01-855c2e20faf7.png)

The phyton files synthax and relevant emacs init file look similar to what I am using. Below what I have in init:

(use-package org-roam
  :ensure t
  :hook ((after-init . org-roam-mode))
  :custom
  (org-roam-db-update-method 'immediate)
  (org-roam-directory "~/orgfiles/braindump/org/")
  (org-roam-index-file "index.org")
  (org-roam-dailies-directory "daily/")
  (require 'org-roam-protocol)
  :bind (:map org-roam-mode-map
              (("C-c m l" . org-roam)
               ("C-c m F" . org-roam-find-file)
               ("C-c m r" . org-roam-find-ref)
               ("C-c m ." . org-roam-find-directory)
               ("C-c m >" . zp/org-roam-find-directory-testing)
               ("C-c m d" . org-roam-dailies-map)
               ("C-c m j" . org-roam-jump-to-index)
               ("C-c m b" . org-roam-switch-to-buffer)
               ("C-c m g" . org-roam-graph))
              :map org-mode-map
              (("C-c m i" . org-roam-insert)))
  :config
  (setq org-roam-capture-templates
        '(("d" "default" plain
           (function org-roam-capture--get-point)
           "%?"
           :file-name "%<%Y%m%d%H%M%S>-${slug}"
           :head "#+title: ${title}\n#+created: %u\n#+last_modified: %U\n\n"
           :unnarrowed t)
          ;;("l" "literature" plain (function org-roam-capture--get-point)
          ;; :file-name "literature/%<%Y%m%d%H%M>-${slug}"
          ;; :head "#+title: ${title}\n#+author: %(concat user-full-name)\n#+email: %(concat user-mail-address)\n#+created: %(format-time-string \"[%Y-%m-%d %H:%M]\")\n#+roam_tags: %^{roam_tags}\n\nsource: \n\n%?"
          ;; :unnarrowed t)
          ("f" "fleeting" plain (function org-roam-capture--get-point)
           :file-name "fleeting/%<%Y%m%d%H%M>-${slug}"
           :head "#+title: ${title}\n#+author: %(concat user-full-name)\n#+created: %(format-time-string \"[%Y-%m-%d %H:%M]\")\n#+roam_tags: fleeting\n\n%?"
           :unnarrowed t)
          ("p" "Permanent" plain (function org-roam-capture--get-point)
           :file-name "%<%Y%m%d%H%M>-${slug}"
           :head "#+title: ${title}\n#+author: %(concat user-full-name)\n#+created: %(format-time-string \"[%Y-%m-%d %H:%M]\")\n#+last_modified: %U\n#+last_modified: %U\n#+roam_tags: permanent\n\n%?"
           :unnarrowed t))
        org-roam-capture-ref-templates
        '(("r" "ref" plain
           (function org-roam-capture--get-point)
           "%?"
           :file-name "web/${slug}"
           :head "#+title: ${title}\n#+roam_key: ${ref}\n#+created: %u\n#+last_modified: %U\n\n"
           :unnarrowed t
           ;; ("i" "incremental" plain
           ;;  (function org-roam-capture--get-point)
           ;;  "* %?\n%(zp/org-protocol-insert-selection-dwim \"%i\")"
           ;;  :file-name "web/${slug}"
           ;;  :head "#+title: ${title}\n#+roam_key: ${ref}\n#+created: %u\n#+last_modified: %U\n\n"
           ;;  :unnarrowed t
           :empty-lines-before 1))
        org-roam-dailies-capture-templates
        '(("d" "default" entry
           #'org-roam-capture--get-point
           "* %?"
           :file-name "scratch/%<%Y-%m-%d>"
           :head "#+title: %<%Y-%m-%d>\n\n"
           :add-created t))))
      
Thank you for any help you can provide.

**Comment by gmachnicki** [comment]
Forgot to mention that the page I am trying to capture is [this](https://www.reddit.com/r/DataHoarder/comments/nc27fv/rescue_mission_for_scihub_and_open_science_we_are/)
In general, seems I am able to work with the roam capture templates, also with some org roam bibtex templates, but not with the org-roam-capture-ref-template I have defined.

**Comment by gmachnicki** [comment]
Here is another screenshot trying to capture [this](https://www.reddit.com/r/emacs/comments/m7ofbh/setting_up_orgroam_protocol_in_qutebrowser/)
It proposes to create the file in a strange directory locatation, and the file it creates is in Fundamental mode.

![Screenshot from 2021-06-14 16-00-39](https://user-images.githubusercontent.com/4349523/121945505-3bc4b600-cd2a-11eb-81b5-af0ef5e68ac3.png)

**Comment by gmachnicki** [comment]
Following instructions from org-roam [manual](https://www.orgroam.com/manual.html), I set set a keybinding in qutebrowser. The situation improved a little (the directory where it wants to create the capture is ~/org-protocol:/ , still not what I want but a bit better than before). The file created continues to be in Fundamental mode, no capture template seems to be called.

![Screenshot from 2021-06-14 16-39-02](https://user-images.githubusercontent.com/4349523/121950288-cc51c500-cd2f-11eb-9dbc-2808347de6f7.png)

**Comment by jethrokuan** [comment]
Sorry not familiar with qutebrowser, this looks like the result of Emacs not being setup to use org-protocol correctly. First check that running

```
emacsclient "org-protocol://roam-ref?template=r&ref=abc&title=abc"
```

in the shell results in the correct behaviour

**Comment by gmachnicki** [comment]
Hi, thank you for your guidance. Below three screenshots after running that command in the Emacs shell

![Screenshot from 2021-06-26 14-16-20](https://user-images.githubusercontent.com/4349523/123520852-4f0c4580-d689-11eb-8675-7885b495c345.png)

![Screenshot from 2021-06-26 14-16-59](https://user-images.githubusercontent.com/4349523/123520876-7bc05d00-d689-11eb-86cd-5ef24f1d5a54.png)

![Screenshot from 2021-06-26 14-07-26](https://user-images.githubusercontent.com/4349523/123520887-8975e280-d689-11eb-8124-ea6df9b03631.png)

I do not know if this is the expected behavior and doing a search on the error "_running timer doom-modeline..._" did not lead me far. Any further guidance is appreciated.

**Comment by jethrokuan** [comment]
I think you just need to ensure that `org-roam-protocol` is loaded by Emacs. That is, have `(require 'org-roam-protocol)` somewhere in your emacs configuration.

**Comment by gmachnicki** [comment]
Hi,
Thanks for your answer.
I have that line in my configuration. I include below a relevant section of my init file.

![Screenshot from 2021-07-02 09-17-36](https://user-images.githubusercontent.com/4349523/124273442-67131780-db16-11eb-8148-99eed9ab0f57.png)

![Screenshot from 2021-07-02 09-20-32](https://user-images.githubusercontent.com/4349523/124273788-d7ba3400-db16-11eb-91bc-b444e6454e88.png)

It looks to me that the other templates are working ok, but not this capture-ref-template.
If it helps in any way, I am running Ubuntu and this is a compiled version of emacs (I have some issues with the emacs-snapshot version). Below some more data about my setting.

![Screenshot from 2021-07-02 09-24-31](https://user-images.githubusercontent.com/4349523/124274226-6038d480-db17-11eb-839f-d8b3722f3a06.png)

Thanks for any further guidance.

**Comment by jethrokuan** [comment]
That's not the right place to put the require, you should place it under `:config` and not `:custom` of your use-package clause.

**Comment by gmachnicki** [comment]
You are correct. It is now working nicely. Thank you!
