### ISSUE TITLE
Strings for node completions are too long

### ISSUE THREAD

**Issue by aruscher** [org-roam/org-roam#1553]
It seems that the strings for node completions are to long to be properly shown in the completion buffer.

Node:
``` Org
:PROPERTIES:
:ID:       7bc23411-8e60-46df-9405-a5acd18100e0
:END:
#+title: AAAA
#+filetags: A B C D E F G H I J K
```
Completion Buffer:
![image](https://user-images.githubusercontent.com/4226393/122608760-15ca4900-d07d-11eb-9cfe-11219852014f.png)

**Comment by jethrokuan** [comment]
Please see https://github.com/org-roam/org-roam/issues/1530#issuecomment-849437672
