### ISSUE TITLE
v2: `org-roam-graph` doesn't generate node-local graphs

### ISSUE THREAD

**Issue by Wetlize** [org-roam/org-roam#1556]
### Description
According to `org-roam-graph`'s docstring, when the command is called with universal and numeric arguments it should generate node-local graphs:

https://github.com/org-roam/org-roam/blob/4fc346861c7d4aac83c91760c4a5281458a95436/org-roam-graph.el#L258-L259

but despite the value of `current-prefix-arg`, it always produces a global graph.

#### Steps to Reproduce
1. `C-u M-x org-roam-graph RET`
2. Observe that `org-roam-graph` built a global graph, while expecting a local one.
3. `C-u 2 M-x org-roam-graph RET`
4. Observe that `org-roam-graph` built a global graph, while expecting a local graph limited to 2 steps.

### Environment
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2021-05-01
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /home/user/.emacs.d/.local/straight/build-28.0.50/org-mode/)
- Org-roam: 2.0.0
- Org-roam commit: 4fc346861c7d4aac83c91760c4a5281458a95436

**Comment by jethrokuan** [comment]
Thanks for the report, fixed in bae39c4
