### ISSUE TITLE
v2: `org-roam-graph` doesn't include isolated nodes

### ISSUE THREAD

**Issue by Wetlize** [org-roam/org-roam#1557]
### Description
Just like titles says it, graphs that are generated with `org-roam-graph` don't include nodes that don't link to any other node.

I'm not sure whether this is now expected behavior in the v2. If yes, then I would expect this to be mentioned somewhere in the docstring and documentation.

#### Steps to Reproduce
1. Create org nodes that don't link to any other nodes
2. Build graph with `org-roam-graph`

#### Expected Results
I would expect that `org-roam-graph` include nodes that don't link to any other nodes, as isolated vertices.

#### Actual Results
`org-roam-graph` only renders nodes that link in one way or another with other nodes. Nodes that don't have links with other nodes are not rendered.

### Environment
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2021-05-01
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /home/user/.emacs.d/.local/straight/build-28.0.50/org-mode/)
- Org-roam: 2.0.0
- Org-roam commit: 4fc346861c7d4aac83c91760c4a5281458a95436

**Comment by jethrokuan** [comment]
Fixed in a5e9abe.
