### ISSUE TITLE
v2: `org-roam-node-insert`; include `thing-at-point` (including thing without region) 

### ISSUE THREAD

**Issue by qzdl** [org-roam/org-roam#1558]
### Brief Abstract
A UX note for text suggestion in `completing-read` and/or `immediate-finish` without the need for a region.

It's nice to have rapid-fire sometimes.

The below demonstrates two points: 
- some use the thing at point
- a use-case for the binding of immediate inserts, based on the thing at point.

The latter would have meant basically rewriting `org-roam-node-insert` to mirror the functionality, so I thought I'd raise it as an issue as a possible extension, given a new `pass-thru` (working title) parameter that allows for acting on the thing at point.

### Long Description
I use `C-c n i` for `org-roam-node-insert`, and I wanted some `immediate finish` version that worked on what I have at point, that will populate an existing node, or create one if it doesn't exist. In the provided implementation, this is `qz/roam-immediate-insert`. This approach is a bit _'jesus take the wheel'_ because you aren't inspecting the captured THING value before it's converted to a node, but the point of showing this is for the possibility of doing something with the thing at point.

I couldn't see a way with the `node-insert` API to pass arbitrary text, or resolve this created/not created issue, and as a consequence of my 'feature development', it seems that my modified insert function `qz/org-roam-node-insert` will now supply the `thing` under the cursor, which has been an added benefit to my UX with org-roam

In the implementation below, I've adapted `doom-thing-at-point-or-region`, to return what the user is 'looking at', and the positional information used to retrieve it. So with cond, dispatch:
- a string value of given argument `thing`
- a `region-active-p`; and the containing text, and a cons of the region
- a non-string value of thing; psuedo-region value `(thing-at-point thing)`, and positional information `(bounds-of-thing-at-point thing)`
- xref; if backend for mode not on elisp-path, then `thing-at-point` for a sym, else `thing-at-point` for the relevant xref backend
- NOTE: I haven't gone too deep on recovering the internals of the cl-generic dispatch used in `xref-backend-identifier-at-point`, so I've taken the cheat-path of referencing the `'symbol` instead. 

### Proposed Implementation (if any)
simplified capture template
``` elisp
(add-to-list
 'org-roam-capture-templates
 '(("n" "empty" plain
    "%?"
    :if-new (file+head "${slug}.org" "#+title: ${title}\n")
    :immediate-finish t)))
```
implementation
``` elisp
(global-set-key (kbd "<C-c n C-i>") #'qz/org-roam-immediate-node-insert)

(defun qz/org-roam-immediate-node-insert ()
"Insert a node on `thing-at-point', corresponding to the thing, creating
if not existing"
  (interactive)
  (qz/org-roam-node-insert nil t))

(defun qz/thing-at-point-or-region-and-region (&optional thing prompt)
  "Grab the current selection, THING at point, or xref identifier at point.

Returns THING if it is a string. Otherwise, if nothing is found at point and
PROMPT is non-nil, prompt for a string (if PROMPT is a string it'll be used as
the prompting string). Returns nil if all else fails.

NOTE: Don't use THING for grabbing symbol-at-point. The xref fallback is smarter
in some cases."
  (declare (side-effect-free t))
  (cond ((stringp thing)
         thing)
        ((region-active-p)
         (cons (buffer-substring-no-properties (region-beginning) (region-end))
               (cons (region-beginning)
                     (region-end))))
        (thing
         (cons (thing-at-point thing t)
               (bounds-of-thing-at-point thing)))
        ((require 'xref nil t)
         ;; Eglot, nox (a fork of eglot), and elpy implementations for
         ;; `xref-backend-identifier-at-point' betray the documented purpose of
         ;; the interface. Eglot/nox return a hardcoded string and elpy prepends
         ;; the line number to the symbol.
         (let* ((val
                 (if (memq (xref-find-backend) '(eglot elpy nox))
                     (thing-at-point 'symbol t)
                   ;; A little smarter than using `symbol-at-point', though in most
                   ;; cases, xref ends up using `symbol-at-point' anyway.
                   (xref-backend-identifier-at-point (xref-find-backend)))))
           (cons val (bounds-of-thing-at-point 'symbol))))
        (prompt
         (read-string (if (stringp prompt) prompt "")))))

(defun qz/org-roam-node-insert (&optional filter-fn pass-thru)
  "Find an Org-roam file, and insert a relative org link to it at point.
Return selected file if it exists.
If LOWERCASE is non-nil, downcase the link description.
FILTER-FN is the name of a function to apply on the candidates
which takes as its argument an alist of path-completions."
  (interactive)
  (unwind-protect
      ;; Group functions together to avoid inconsistent state on quit
      (atomic-change-group
        (let* ((pt (qz/thing-at-point-or-region-and-region))
               (beg (set-marker (make-marker) (car (cdr pt))))
               (end (set-marker (make-marker) (cdr (cdr pt))))
               (region-text (org-link-display-format
                             (substring-no-properties (car pt))))
               (node (if pass-thru
                         (or (org-roam-node-from-title-or-alias region-text)
                             (org-roam-node-create :title region-text))
                       (org-roam-node-read region-text filter-fn)))
               (description (or (and node region-text (org-roam-node-title node))
                                region-text))) 
          (if (org-roam-node-id node)
              (progn
                (when region-text
                  (delete-region beg end)
                  (set-marker beg nil)
                  (set-marker end nil))
                (insert (org-link-make-string
                         (concat "id:" (org-roam-node-id node))
                         description)))
            (funcall
              `(lambda ()
                 (org-roam-capture-
                  :node node
                  ;; there could be a better way to reference the `immediate-finish'
                  ;; roam-capture-template here, but for demo it's just easier to splice in
                  ;; with a funny metaprogramming hack for conditional interning `:key "val"'
                  ,@(when pass-thru '(:keys "n"))  ; where "n" is an `immediate-finish' template
                  :props (append
                          (when (and beg end)
                            (list :region (cons beg end)))
                          (list :insert-at (point-marker)
                                :link-description description
                                :finalize 'insert-link))))))))
    (deactivate-mark)))
```
### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
Thanks for sharing, but I don't think this behaviour is something that I want to include in Org-roam, and is best left within user configurations. Couple of things to note:

1. `org-roam-node-insert` now supports the `templates` key, which lets you pass in the `immediate-finish` template you want, so you don't need the pass-thru hack
2. Instead of returning the beginning and end of thing at point, simply making the function mark that as the region before calling `org-roam-node-insert` should get most of what you want already without modifying `org-roam-node-insert`s behaviour.
