### ISSUE TITLE
[V2] roam links doesn't convert to proper links after save-buffer

### ISSUE THREAD

**Issue by maikol-solis** [org-roam/org-roam#1563]
### Description

In V2 if you have  a `[[roam:My note]]`, org-roam does not convert it to a proper link after saving the buffer

After saving the buffer we expect that the roam link converts automatically to  `[[id:1234][My note]]`

#### Steps to Reproduce

1. Load Emacs
2. Open any org-roam file
3. Type `[[roam:My note]]` (where the node exists in the db)
4. Save the buffer

#### Expected Results

A proper link  `[[id:1234][My note]]`

#### Actual Results

A roam link `[[roam:My note]]`

### Environment

```
- Emacs: GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4)
 of 2021-06-25
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /home/maikol/.emacs.d/.local/straight/build-28.0.50/org-mode/)
- Org-roam: 2.0.0
```

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/8bed015cdff44bc813cad5c9cbe0194026d53370

**Comment by jethrokuan** [comment]
Closed with https://github.com/org-roam/org-roam/commit/e448b80b12d08e270416a7664ebb28dc482f3e6f

**Comment by maikol-solis** [comment]
Thanks Jethro!
