### ISSUE TITLE
V2 - completion-ignore-case doesn't work

### ISSUE THREAD

**Issue by vascoferreira25** [org-roam/org-roam#1564]
### Description

On V2, completion while ignore case doesn't work.

By checking the source, this variable isn't being used yet on `org-roam-completion.el/org-roam-complete-link-at-point`.

**Comment by jethrokuan** [comment]
Yeah it's not a variable anymore actually, `org-roam` now just respects `completion-styles`, I think `orderless` is a great fit for completions with `org-roam`, and it does ignore case by default.

**Comment by vascoferreira25** [comment]
Thank you for your help. It seems to work great.

In case someone else also has this problem, this is what I added to my config to make it work:

```
(straight-use-package
 '(orderless :type git :host github :repo "oantolin/orderless"))

(setq completion-styles '(orderless))
```
