### ISSUE TITLE
[V2] [Feature Request] Show file/heading context of nodes 

### ISSUE THREAD

**Issue by amatsukawa** [org-roam/org-roam#1565]
### Description

I could have sworn I saw some discussions about this already, but I couldn't find it, so I thought I'd file a new feature request.
I think the migration to use IDs only has really simplified things tremendously, and I'm loving it so far. One pain point is that now there are many more entries in `org-roam-{find/insert}-node`.

Consider this sample org file about something:

```
#+title: my concept

* definition
some concept is ....
* properties
  - property 1 # <----- i want to insert a link here to a note that elaborates on property 1
```

What will happen if I insert this link is that the `properties` heading will get an ID, and simply show up as "properties" in `org-roam-find-node`. Of course if I have 10 concepts, each with a `properties` heading, I'll get 10 such entries and no way to disambiguate them when linking.

This forces one to use fully qualified/descriptive titles for all things that might get an ID, ie. one has to structure notes like this:

```
#+title: my concept

* definition of my concept 
some concept is ....
* properties of my concept
  - property 1 # <----- i want to insert a link here to a note that elaborates on property 1
```

I like that all links are IDs, and that has many benefits (eg. I can "refactor" a heading into a new note easier, without breaking links) but I think ideally the `org-roam-find-node` dialog would show something the heading "path" like `my concept/properties`.

**Comment by Wetlize** [comment]
@amatsukawa I think what you're looking for is `org-roam-node-display-template` variable. You can set it to to something like `${olp}/${title:80} ${tags:*}`. Each such `${template}` maps to a corresponding `org-roam-node`'s fields.

**Comment by amatsukawa** [comment]
Ahhhh excellent. Thank you @Wetlize. That gets me most of the way there, to a point where I can live with it :) 

Is there a way to get the *page* title? `${olp}` starts from the first `*`, not the page title. Therefore, my example above would still show up as ` > properties`. I can use `file` for now, but sometimes I end up changing the title after the file is created (since filenames are meaningless now).

I could structure my notes as 

```
#+title: my concept
* my concept
** definition
some concept is ....
```

but I believe this will make `my concept` appear twice.

**Comment by Wetlize** [comment]
@amatsukawa I don't think that's possible right now, at least easily. Outline path, as far as I understand is obtained with the built-in org-mode parser, which doesn't track `#+title:` as part of the OLP and nodes only store file paths. 

Since this Emacs I imagine one can hack something, e.g. by writing custom `cl-method` for `org-roam-node` or using an overriding advice for function that controls `org-roam-node-display-template`, but I imagine the performance wouldn't be as good and it's an extra maintenance on the user side. 

Maybe Jethro can came up with something for this, I would like `#+title`s included as a starting element of each OLP too.

**Comment by amatsukawa** [comment]
@jethrokuan perhaps a property (eg. `filetitle` or `pagetitle`) added to `org-roam-node` so we can use it in `org-roam-node-display-template`? 

I tried to look for if there was one place these nodes are created, but I can only find a few places there they are queried from the db (eg. here https://github.com/org-roam/org-roam/blob/v2/org-roam.el#L483) but not where it's inserted :)

**Comment by Wetlize** [comment]
@amatsukawa Oh, I talked specifically if you would write something like this on the user side. It definitely shouldn't be hard to extract title at the package side, for both org and org-roam.

**Comment by jethrokuan** [comment]
```
(cl-defmethod org-roam-node-filetitle ((node org-roam-node))
   "Return the file TITLE for the node."
   (org-roam-with-file (org-roam-node-file node) nil
       (org-roam-get-keyword "TITLE")))
```

Should work on latest v2 commit.

**Comment by qzdl** [comment]
yeah I've been thinking about this a lot, since for prose, I basically only use headlines in my notes; just a much quicker way to get an AST.

my implementation modifies some OR internals, working on the current buffer. you could peg this on org-id creation

(F N Q &optional LIMIT)
  - N: "size"
  - Q: " => "
  - PN: (discovered) "crytographic key"
  - output: "cryptographic key => sizes"

- for a given headline node N, qualifier Q
- go up headlines, with LIMIT
- if parent node PN found, then make qualifying alias (PN:title Q N:title)
- add alias as ROAM_ALIASES property to prop drawer
- blah default variables

``` elisp
(defvar qz/roam-qualifier " => ")
(defvar qz/roam-qualifier-limit 1)

(defun qz/qualify-node (&optional qualifier limit)
  (interactive)
  (let (q)
    (save-excursion
      (when-let ((n (qz/node-title 0))) ;; get current title
        (org-roam-up-heading-or-point-min) ;; set point up to start search from above current
        (when-let ((pn (qz/org-roam-node-at-point nil (or limit qz/roam-qualifier-limit))))
          (setq q (message
                    (concat (org-roam-node-title pn)
                            (or qualifier qz/roam-qualifier)
                            n))))))
    (org-roam-alias-add q)
    (save-buffer)
    q))

(defun qz/org-roam-node-at-point (&optional assert limit)
  "Return the node at point.
If ASSERT, throw an error if there is no node at point."
  (if-let ((node (magit-section-case
                   (org-roam-node-section (oref it node))
                   (t (let* (id
                             (count 0))
                        (org-with-wide-buffer
                         (while (and (not (setq id (org-id-get)))
                                     (if limit (< limit (setq count (1+ count))) t)
                                     (not (bobp)))
                           (org-roam-up-heading-or-point-min))
                         (when id
                           (org-roam-populate
                            (org-roam-node-create :id id
                                                  :point (point))))))))))
      node
    (when assert
      (user-error "No node at point"))))

(defun qz/node-title (&optional limit)
  (save-excursion
    (goto-char (org-roam-node-point (qz/org-roam-node-at-point 'assert limit)))
    (if (= (org-outline-level) 0)
        (cadr (car (org-collect-keywords '("title"))))
      (substring-no-properties (org-get-heading t t t)))))

```

open to comments here, I'm just taking the approach that more information (-> in this case, more completion candidates) == better, as this works for me.

**Comment by amatsukawa** [comment]
I don't really know elisp but I tried to put something together. 

```elisp
(cl-defmethod org-roam-node-filetitle ((node org-roam-node))
   "Return the file TITLE for the node."
   (org-roam-get-keyword "TITLE" (org-roam-node-file node)))

(defun my/org-roam-node--format-entry (fn node width)
  (concat (org-roam-node-filetitle node)
          " > "
          (funcall fn node width)))

(advice-add 'org-roam-node--format-entry :around #'my/org-roam-node--format-entry)
```

This gives me an error `if: Wrong type argument: sequencep, 0`

In fact, even when I try a no-op like this I get the same error
```elisp
(defun my/org-roam-node--format-entry (fn &rest args)
  (apply fn args))
```

Any ideas what I'm doing wrong?

**Comment by maikol-solis** [comment]
> ```emacs-lisp
> (defun my/org-roam-node--format-entry (node width)
>   (let ((display (org-roam-node-title node))
>          (olp (org-roam-node-olp node))
>          (level (org-roam-node-level node))
>          (filetitle (org-roam-node-filetitle node)))
>     (when (> level 1) (setq display (concat (string-join olp " > ") " > " display)))
>     (when (> level 0) (setq display (concat filetitle " > " display)))
>     display))
> (advice-add 'org-roam-node--format-entry :override #'my/org-roam-node--format-entry)
> ```
> 
> <img alt="Screen Shot 2021-07-02 at 9 58 00 AM" width="456" src="https://user-images.githubusercontent.com/463809/124285570-071f6f80-db1c-11eb-95da-cc0dfc5db1a0.png">

This looks super clean. Why this config isn't the `org-roam`'s default?

**Comment by yiufung** [comment]
> ```
> (cl-defmethod org-roam-node-filetitle ((node org-roam-node))
>    "Return the file TITLE for the node."
>    (org-roam-get-keyword "TITLE" (org-roam-node-file node)))
> ```
> 
> Should work on latest v2 commit.

I digged a bit the code. After you add @jethrokuan 's snippet above, you need to add `${filetitle}` to template:

```
(setq org-roam-node-display-template
              "${filetitle} > ${olp} > ${title:80} ${tags:*}")
```

There are some glitches (extra spaces and whatnot), but this is good enough for me now. 

After digging the code, I think Jethro Kuan's design aimed for extensibility: you can actually use various kinds of slots in `org-roam-node`

![image](https://user-images.githubusercontent.com/1023375/125425726-6f96f27b-35e5-416c-8a69-19449931801d.png)

I think there are 2 problems to solve:
- Not all files have a `#+TITLE` property. 
- A file with `#+TITLE` but without any heading will have same value of `${filetitle}` and `${title}`

Solving them requires quite a lot of code change. I think it's easier to point people to @amatsukawa 's solution. Perhaps add it to [User Contributed Tricks](https://github.com/org-roam/org-roam/wiki/User-contributed-Tricks)? From there user can add more fields that suits their flavor, for example, I added `tags` to it.

**Comment by amatsukawa** [comment]
Added it here: https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2#showing-context-of-nodes

I also ended up adding tags 😄

**Comment by mchowning** [comment]
Thanks to everyone here for this discussion. So helpful! :bow: 

Just sharing in case it's useful to anyone else, since I ended up using a slight variation on @amatsukawa excellent solution.

```
  (cl-defmethod org-roam-node-filetitle ((node org-roam-node))
    "Return the file TITLE for the node."
    (org-roam-get-keyword "TITLE" (org-roam-node-file node)))

  (cl-defmethod org-roam-node-hierarchy ((node org-roam-node))
    "Return the hierarchy for the node."
    (let ((title (org-roam-node-title node))
          (olp (org-roam-node-olp node))
          (level (org-roam-node-level node))
          (filetitle (org-roam-node-filetitle node)))
      (concat
       (if (> level 0) (concat filetitle " > "))
       (if (> level 1) (concat (string-join olp " > ") " > "))
       title))
    )

  (setq org-roam-node-display-template "${hierarchy:*} ${tags:20}")
```

```

**Comment by amatsukawa** [comment]
Ah, I like this much more @mchowning 😄. It has the advantage that it can use the existing width logic. Updated the wiki.

**Comment by amatsukawa** [comment]
Closing the issue, I think it's been sufficiently addressed.

**Comment by chasecaleb** [comment]
@amatsukawa `org-roam-get-keyword` is deprecated now and recommends using `org-collect-keywords` instead. Permalink to current master at time of this comment: https://github.com/org-roam/org-roam/blob/1d03f87cd1d8e1cd7e089b3be78289b757f78156/org-roam-compat.el#L134

I came up with this based on how `org-roam-get-keyword` is implemented. It works for me, but I have no idea if it's a particularly good way of doing so:
```elisp
  (cl-defmethod org-roam-node-filetitle ((node org-roam-node))
    "Return the file TITLE for the node."
    (if-let ((file (org-roam-node-file node)))
        (with-temp-buffer
          (insert-file-contents file nil 0 1024)
          (cadr (assoc "TITLE"
                       (org-collect-keywords (list "TITLE")))))
      (cadr (assoc "TITLE"
                   (org-collect-keywords (list "TITLE"))))))

  (cl-defmethod org-roam-node-hierarchy ((node org-roam-node))
    "Return the hierarchy for the node."
    (let ((title (org-roam-node-title node))
          (olp (org-roam-node-olp node))
          (level (org-roam-node-level node))
          (filetitle (org-roam-node-filetitle node)))
      (concat
       (if (> level 0) (concat filetitle " > "))
       (if (> level 1) (concat (string-join olp " > ") " > "))
       title)))
```

You're welcome to update the wiki with this. Let me know if there's a better way, too.

**Comment by mchowning** [comment]
Thanks to @publicimageltd [adding file-title to the table column](https://github.com/org-roam/org-roam/pull/1963), with the latest versions of org-roam we no longer need to look up the filetitle with our own (slow) `org-roam-node-filetitle` function inside `org-roam-node-hierarchy`. Instead, we can use the newly defined `org-roam-file-title`, which is _much_ faster. :rocket:
