### ISSUE TITLE
v2: All the variants of `:if-new (file+[headline] ...)` don't capture to the right places

### ISSUE THREAD

**Issue by Wetlize** [org-roam/org-roam#1566]
### Description
If the target file doesn't exist or it doesn't contain any headings in it, then it will capture to the right place, as expected. However, it doesn't do so if the target file has some headings in it, independently of whether such headings match the defined in template OLP or these're some other non-matching headings, or whether they have an ID in them or not, none of this matter. 

When this happens, the capture will somehow randomly embed the new entry to the target file, for example, it can put entry as a level 1 heading, completely ignoring the defined OLP, or embed it as a child of some other random headings that were not in the OLP but were previously existing in the file.

I suspect this doesn't just happen with `(file+olp)`, but also with any other `(file+[heading])` targets, including `datetree`. I will update the title if I confirm that.

#### Steps to Reproduce
1. Use the next capture template:
```emacs-lisp
(setq-default
 org-roam-capture-templates
 `("d" "default" entry
   ,(mapconcat #'identity
               '("* ${title}%?"
                 ":PROPERTIES:"
                 ":ID: %(org-id-new)"
                 ":END:")
               "\n")
   :if-new (file+olp "test.org" ("Capture's OLP"))))
```
2. Run the capture for this template without previously creating the needed for it file.
3. Confirm that it captured the thing **as expected.**
3. Delete all the content inside the file, except file's title and properties.
3. Run the capture for already created `test.org` file, but with no headings or other content inside of it.
4. Confirm that it captured the things **as expected.**
4. Run the capture again for a new heading, keeping the previous capture inside the file.
5. Confirm that the captured heading **wasn't inserted at the right place.** 
5. Delete all the content inside the file, except file's title and properties.
6. Add some random headings inside this file that wouldn't match the defined OLP.
7. Run the capture for a new heading.
8. Confirm that the captured heading **was inserted at some random place.**

### Environment
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-05-01
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /home/user/.emacs.d/.local/straight/build-28.0.50/org-mode/)
- Org-roam: 2.0.0
- Org-roam commit: 31817f3483636300bd587b3f768ef31338427ad0

**Comment by Wetlize** [comment]
At first I though this problem could be unique to templates who's `type` is set to `entry`, so I've tried to use `plain` as `type`:
```diff
(setq-default
 org-roam-capture-templates
- `("d" "default" entry
+ `("d" "default" plain) 
   ,(mapconcat #'identity
-               '("* ${title}%?"
+              '("** ${title}%?")
                 ":PROPERTIES:"
                 ":ID: %(org-id-new)"
                 ":END:")
               "\n")
   :if-new (file+olp "test.org" ("Capture's OLP"))))
```

It worked as it should be, but if you add extra levels to OLP:
```diff
(setq-default
 org-roam-capture-templates
 `("d" "default" plain) 
   ,(mapconcat #'identity
-              '("** ${title}%?"
+              '("***** ${title}%?")
                 ":PROPERTIES:"
                 ":ID: %(org-id-new)"
                 ":END:")
               "\n")
-   :if-new (file+olp "test.org" ("Capture's OLP"))))
+   :if-new (file+olp "test.org" ("Capture's OLP" "Level 2" "Level 3" "Level 4"))))
```
then it will fail to capture to correct place: the node will simply always end-up captured under `Level 2` outline and the template will create `Level 3` and `Level 4` outlines at same level as `Level 2`
```org
* Capture's OLP
** Level 2
****** ${title} 
** Level 3
** Level 4
```
Unlike `entry`, `plain` will do so independelty of whether it was an empty file or not.

Out of interest I decided to also switch back to `entry` with a single `*`, while keeping the same OLP and it would fail similarly to `plain`. Specifically in case of new/empty files it would capture like this:
```diff
* Capture's OLP
** Level 2
- ****** ${title} 
** Level 3
+ *** ${title} 
** Level 4
```
yep, it would do so under `Level 3` heading as a level 3 outline.

If you continue adding new captures to this file it will keep add them under `Level 3` heading as level 3 outlines, but it will now introduce another problem: it will start duplicate some headings from OLP as level 2 headings:
```diff
* Capture's OLP
** Level 2
** Level 3
*** ${title} 
+ *** ${title} 2
+ *** ${title} 3
** Level 4
+ ** Level 3
+ ** Level 4
+ ** Level 3
+ ** Level 4
```

I'm not sure what's going on here and whether this is a single issue, or multiple issues that somehow related to each other.

**Comment by Wetlize** [comment]
I've also quickly tried other capture targets:

- `(file+head+olp)` will incorrectly create OLP and won't even respect pre-defined template. Repeated execution will duplicate some headings from OLP.
- `(file+datetree)` will create the datetree, but will always capture under the datetree as level 1 outline (if `type` is `entry`) or hardcoded outline (if it's `plain`). Repeated capture for the same date will add new entries to the last heading in file and will also randomly pollute entries with `:ID:` property, e.g. the datetree itself.

Which makes all `(file+[headline])` targets broken in one way or another. All this points that `org-roam-capture` will need some programmatic tests to ensure some level of degree for correctness in future.

**Comment by cdlm** [comment]
Even with #1574 I'm still having problems with `file+head+olp` in my dailies capture template:
```emacs-lisp
(setq org-roam-dailies-capture-templates
        '(("d" "daily" entry
           "** %<%R>  %i%?\n"
           :if-new (file+head+olp
                    "%<%Y-%m-%d>.org"
                    "#+title: %<%Y-%m-%d (%A)>

- where ::
- mood ::
- agenda ::
-----\n\n"
                    ("Journal"))
           :empty-lines 1 :unnarrowed t)))
```

- as is shownn above, capture fails with `wrong type argument: integer-or-marker-p, nil`
- if I add a `* Journal` entry in the head template, capture inserts the entry at top-level (a sibling of `* Journal` instead of a child). Same if the file already exists.
- if there is another `* Whatever` top-level entry after `* Journal`, then the capture is inserted as a child of it; but if `* Journal` is the last one, I get a top-level entry…

**Comment by Wetlize** [comment]
@cdlm I can't reproduce the error. When I run this template for a new file it creates everything as expected. However, I can confirm that it doesn't work as expected when the file already contains some other headings (including the one from the OLP), where it fails similarly to `file+datetree`, so I wonder if both of these targets have a common source of the problem, which I'm still unable to identify in the source code...

**Comment by Wetlize** [comment]
OK, I've identified the source of all problems here and it doesn't look like the fix will be trivial. It all boils down to how `org-roam-capture` hooks itself to `org-capture`, by setting `org-roam-capture--get-point` as `(function)` based target for `org-capture-set-target-location` function, and this carries with itself some unwanted side effects for `org-roam`'s capture templates. 

It looks like a potential solution would need to either, hook `org-roam-capture` to `org-capture` differently from how it's done right now or somehow take control over these side effects. Hope I'm wrong in both cases and there's more simpler solution.

**Comment by Wetlize** [comment]
Fixed now with dbc0b2fbd90e38416f7fb837bd8411ba5a9d8935 and c9bed390b6b72bd31f4c949b088c28358a868906 in place.

**Comment by brabalan** [comment]
I’m also having an issue with `file+head+olp`. Should the following work?
```emacs-lisp
    (setq org-roam-dailies-capture-templates
          (let ((head
                 (concat "#+title: %<%Y-%m-%d (%A)>\n#+startup: showall\n* Daily Overview\n"
                         "#+begin_src emacs-lisp :results value raw\n"
                         "(as/get-daily-agenda \"%<%Y-%m-%d>\")\n"
                         "#+end_src\n"
                         "* [/] Do Today\n* [/] Maybe Do Today\n* Journal\n")))
            `(("j" "journal" entry
               "* %<%H:%M> %?" :if-new
               (file+head+olp "%<%Y-%m-%d>.org" ,head ("Journal"))))))
```

When I test it, the file is created with the correct template, but the Journal item (with the current time) is not inserted.

Please let me know if I should open another issue for it.

**Comment by Wetlize** [comment]
@brabalan Just run your template and everything is working for me. Keep in mind that `org-roam-dailies-goto-*` and `org-roam-dailies-capture-*` are two slightly different set of commands. The former will do the behavior that you described

> When I test it, the file is created with the correct template, but the Journal item (with the current time) is not inserted.

for a new file and otherwise it will simply jump to where the target (the `:if-new` part)  of the capture template would run (hence "goto") for repeated execution. On the other hand, the latter will always run the template itself, which is `entry "* %<%H:%M> %?"` in your case.

**Comment by brabalan** [comment]
@Wetlize Ah, thank you, I confirm it works. I was surprised the `goto` command was bringing up the capture template dialog. What would it be used for?

**Comment by Wetlize** [comment]
@brabalan I think the intent was to allow the user to jump to the file with a corresponding template without triggering a full blow capture process, but it wasn't thought through how to extract the needed file/target if you have multiple capture templates, e.g. see discussion in #1354.

**Comment by brabalan** [comment]
Thank you for the explanation!
