### ISSUE TITLE
v2: [[roam:]] links infect nearby [[roam:]] links

### ISSUE THREAD

**Issue by rberaldo** [org-roam/org-roam#1572]
### Description

When using the `[[roam:n]]` shortcut, saving will cause a `[[roam:n-1]]` link to be changed.

Say you have two IDs already created: topics `a` and `b`. You reference `[[roam:a]]`, then `[[roam:b]]`. Upon saving, the mention to `b` will be left untouched, while `a` will have changed to be a link to `b`.

This does not happen if either `a` or `b` reference nonexistent files.

.gif bug report:
![ezgif-1-2f58eddf6862](https://user-images.githubusercontent.com/162562/124338477-99f0f600-db7e-11eb-8078-0f83de2e85a5.gif)

#### Steps to Reproduce

1. Create `a` and `b`.
2. Link to `a` and `b` by using the `[[roam:]]` syntax.
3. `a` will be turned into `b` and `b` will be left untouched.

#### Expected Results

Links `a` and `b` are correctly updated to their IDs.

#### Actual Results

Link `a` is "infected" by `b`.

### Environment

```
Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.5.0, Carbon Version 164 AppKit 2022.5)
 of 2021-06-14
Framework: N/A
Org: Org mode version 9.4.4 (release_9.4.4 @ /usr/local/Cellar/emacs-mac/emacs-27.2-mac-8.2/share/emacs/27.2/lisp/org/)
Org-roam: 2.0.0
```

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/77af8e6b237d0cf92dd2e351856b7bb74c18801b

**Comment by jethrokuan** [comment]
Should be fixed on latest v2, thanks for the detailed bug report and example.
