### ISSUE TITLE
[v2] non-ASCII text display byte-code in org-roam-buffer unlinked references section

### ISSUE THREAD

**Issue by jay1803** [org-roam/org-roam#1575]
### Description

The unlinked-references-section display the byte code in the buffer, but the file title of unlinked section and backlinks section displayed correctly.

I have this settings in spacemacs `init.el` file.

``` emacs-lisp
 (setq org-roam-mode-section-functions
        (list #'org-roam-backlinks-section
              #'org-roam-reflinks-section
              #'org-roam-unlinked-references-section))
```

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/6468344/124376525-f1f03f80-dcd9-11eb-853f-d5937e401fdb.png">

#### Expected Results
```
现实的个人构建是基于你的一般知识、过去经验的记忆、当前的需求、价值、信念和将来目标对当前情境的独特解释。
```
#### Actual Results

<img width="977" alt="image" src="https://user-images.githubusercontent.com/6468344/124376626-82c71b00-dcda-11eb-9be2-0c275863f17f.png">

### Environment

```
- Emacs: GNU Emacs 28.0.50 (build 2, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H524))
 of 2021-02-16
- Framework: Spacemacs
- Org: Org mode version 9.4.6 (9.4.6-7-gc09356-elpa @ /Users/max/.emacs.d/elpa/develop/org-20210628/)
- Org-roam: 2.0.0
```

**Comment by Elilif** [comment]
Could you tell me how do you use unlinked references in v2?

**Comment by rasendubi** [comment]
https://github.com/org-roam/org-roam/pull/1616 should fix this.
