### ISSUE TITLE
Org-roam-doctor freezes emacs when finding file

### ISSUE THREAD

**Issue by sdpenguin** [org-roam/org-roam#1577]
When using org-roam-doctor on all files, if you use the 'r' option to replace a link, but then subsequently attempt to cancel the operation by pressing C-g, then emacs will freeze and be unresponsive to input. Am happy to help debug this.

**Comment by maikol-solis** [comment]
From this commit https://github.com/org-roam/org-roam/commit/0bc38d1e076f3e14fa62a7eec9cc42d49c18aa38 org-roam-doctor was removed in V2. Once V2 is merged with the master branch, this won't be a problem.

**Comment by sdpenguin** [comment]
Ah ok, I didn't realise that org-roam-doctor was being removed in a future version. Although that's great if it is - I'm assuming then in V2 there's going to be a better way of keeping links up to date?

**Comment by maikol-solis** [comment]
All the links must linked with IDs so it won't be any chance to break them even if you change your files to another directory (inside your org-roam-directory).

I think that the only thing missing is the links renaming if you rename the parent file.

Best.

**Comment by jethrokuan** [comment]
Even if you rename a file, the links won't break if they are ID links.

The only thing not propagated is title changes now, this won't propagate to changing link descriptions. I'm experimenting with a different approach, that is using bare id links (like [[id:foo]]), and using overlays to show the description, so there is no need for propagation at all. You can try `org-roam-overlay-mode` in v2.

**Comment by jethrokuan** [comment]
Closed with v2 merged.
