### ISSUE TITLE
Helm completion too wide for side-by-side windows

### ISSUE THREAD

**Issue by bnordbo** [org-roam/org-roam#1578]
#### Steps to Reproduce

1. Set up two windows side-by-side using `C-x 3`.
2. Run `M-x org-roam-node-find`.

#### Expected Results

A list of completions in the inactive window.

#### Actual Results

As expected, except all the lines are way too long. This causes them to wrap, causing a very untidy display.

From what I can tell, the problem is caused by using `frame-width` as the basis for the width  of the completion list in [`org-roam-node--to-candidate`](https://github.com/org-roam/org-roam/blob/v2/org-roam.el#L738). Replacing `(1- (frame-width))` with  `(window-width)` works as long as the windows are of equal width, but I suspect this might affect completions using the minibuffer. I suppose the problem is that neither function return the width of the to-be completion buffer.

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.4.0, NS appkit-2022.44 Version 11.3.1 (Build 20E241))
 of 2021-06-08
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4 @ /usr/local/Cellar/emacs-plus@28/28.0.50/share/emacs/28.0.50/lisp/org/)
- Org-roam: 2.0.0
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/90945e8c03b170731070af2009b89b9687ff2f58

**Comment by jethrokuan** [comment]
Do you have a screenshot of what it actually looks like? Are your minibuffer completions never always the frame width? I've always assumed this to be the case.

**Comment by bnordbo** [comment]
Sure, here's an example when the frame is split side-by-side:

![image](https://user-images.githubusercontent.com/696788/125159112-a6c0ab80-e175-11eb-8127-2be58271fee0.png)

When it's split below (or not split at all), it looks fine because the completions get the full width. Note that the lines are almost twice as long as the window width. I've set aside 20 characters for tags.

In the above example, `(frame-width)` returns 237, and `(window-width)` gives 117 for both windows. I have a stock helm setup, and it will show completions in the window to the right if split side-by-side (or the current window if invoked in the rightmost window).

Maybe there's a way to get the width of the window which will be used for completions given the current window setup?

**Comment by jethrokuan** [comment]
@bdarcus do you have any insights here? I see that `bibtex-actions` also uses `frame-width` to compute the rich UI, I suppose it would see similar issues.

**Comment by bdarcus** [comment]
> do you have any insights here? I see that `bibtex-actions` also uses `frame-width` to compute the rich UI, I suppose it would see similar issues.

I don't think so. Using the completing-read UI, like Vertico, means we use the minibuffer, where it will be the full frame width.

I borrowed the use of `frame-width` from bibtex-completion, and did run into problems with it that I thought I had fixed, and have not seen lately.

Maybe this is only an issue for Helm?

I wonder what happens if we change to `window-width`; perhaps it would work for both situations?

**Comment by bnordbo** [comment]
@bdarcus I suspect `window-width` will not work with e.g. `ivy` in a side-by-side split frame. The completions in the minibuffer will probably be narrowed to the width of the window where `org-roam-node-find` was invoked. It might be good for readability thoug; not having too much whitespace between the title and the tags.

I suspect this is a problem affecting all completion systems showing completions in a regular buffer – pehaps that's only helm?

This is a minimal example of a config exhibiting the behaviour:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(when (not (package-installed-p 'use-package))
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package-ensure)
(setq use-package-always-ensure t)

(use-package helm
  :config (helm-mode 1))

(use-package org-roam
  :pin manual
  :load-path "~/src/forks/org-roam"
  :bind (("C-c n f" . org-roam-node-find))
  :init (setq org-roam-directory "~/Repository/Roam")
  :config (org-roam-setup))
```

Should work with e.g. `emacs -nw -q -l completions-test.el`.

**Comment by bdarcus** [comment]
> I suspect this is a problem affecting all completion systems showing completions in a regular buffer – pehaps that's only helm?

Yes, probably this.

I haven't tested this, but what would be the implications of the change for those completion UIs that use the minibuffer?

Would it work there too, or would there need to be some logic to determine when to use `windows-width` and when to use `frame-width`?

**Comment by bnordbo** [comment]
I did a quick test by replacing the helm bit with ivy, and alas using `(window-widh)` results in a narrow display in the minibuffer:

![image](https://user-images.githubusercontent.com/696788/125162570-eba20d80-e188-11eb-8c48-884ea70b06d6.png)

I had a look at closed helm issues, and found one that appears relevant:

https://github.com/emacs-helm/helm/issues/1294

**Comment by bdarcus** [comment]
So ideally, if in buffer, use window-width, else frame-width.

**Comment by bdarcus** [comment]
Would it be so simple as?

``` elisp
(if (bufferp (current-buffer)
  (window-width) (-1 frame-width))
```

**Comment by bnordbo** [comment]
> So ideally, if in buffer, use window-width, else frame-width.
> 

Yeah, that would work as long as the windows have equal width, which they often do. I can test your fix later today.

**Comment by bnordbo** [comment]
@bdarcus Alas it doesn't quite work for me. But I think a proper fix is not so hard: The entries should be formatted by the annotation function provided to `completing-read` in `org-roam-node-read`. In that context, `widow-width` appears to have correct value. I tried making a quick change, but of course it's not _quite_ so easy. Can give it another shot tomorrow. :-)

**Comment by bnordbo** [comment]
I gave it a shot by bypassing the formatting in `org-roam-node--completions`, and instead doing it in `completing-read`. There appears to be two ways to make it work with that approach:

The first is to provide a metadata handler for `annotation-function` that carefully formats the tags as an annotation. It has access to the right `window-width`. But as it will be appended to the completion, which is not in scope, it is a bit fidgety as there's not a robust way to know how much space to fill to get the tags neatly aligned.

The second approach is to use the `affixiation-function` hook that allows setting both a prefix and a suffix, as well as formatting the actual completion. This seems to be the more robust approach. Alas, neither Ivy nor Helm appears to support this yet, it's an Emacs 28 feature, and not quite stable yet. So this is probably not the way to go yet.

By the way, there's a [related thread](https://org-roam.discourse.group/t/find-node-ui-possibilities-for-v2/1422/17) on the Roam Discourse.

**Comment by bdarcus** [comment]
One thing to keep in mind about both annotation and affixation:

It adds relevant metadata to the display, but that content can't be searched.

**Comment by pprevos** [comment]
Found this workaround on [Reddit](https://www.reddit.com/r/OrgRoam/comments/on3mlk/org_roam_2_and_helm/h5vmu8c/):

```
  (defun org-roam-node--to-candidate (node)
      "Return a minibuffer completion candidate given NODE."
      (let ((candidate-main (org-roam-node--format-entry
                             node
                             (if (bufferp (current-buffer))
                                 (window-width) (-1 frame-width)))))
        (cons (propertize candidate-main 'node node) node)))
```
I popped this into my config and it solves the issue.

**Comment by bnordbo** [comment]
Thanks, @pprevos. Does it also work if your frames are not the same width?

Personally I've switched to using [Vertico](https://github.com/minad/vertico), and displaying the match results in the minibuffer, so I dont' experience this issue anymore.

**Comment by pprevos** [comment]
Thanks @bnordbo, I am not ready to move away from Helm just yet :)

The workaround seems affective in all my use cases. It would be good if Org-roam can be updated to fix this minor annoyance.

**Comment by pprevos** [comment]
The issue seems to have resolved itself in the last release. Tags are now display directly after the title. 

Flushing the right is nicer, but alas, this will work.

**Comment by bnordbo** [comment]
Good, then I think we can close this. I'm not using helm anymore, so I'm unable to confirm.
