### ISSUE TITLE
sqlite column types are not defined

### ISSUE THREAD

**Issue by smallstepman** [org-roam/org-roam#1582]
I wish to use org-roam's backing sqlite database from within [prisma](https://www.prisma.io/) ORM, unfortunately, the database seems to not have defined data types for all columns. Because of this, prisma is not able to figure out how to interpret the schema and fails to initialize. 

Here is schema dump for org-roam db
```sql
❯ sqlite3  ~/.emacs.d/.local/etc/org-roam.db  .schema
CREATE TABLE files (file UNIQUE PRIMARY KEY, hash NOT NULL, meta NOT NULL);
CREATE TABLE ids (id UNIQUE PRIMARY KEY, file NOT NULL, level NOT NULL);
CREATE TABLE links (source NOT NULL, dest NOT NULL, type NOT NULL, properties NOT NULL);
CREATE TABLE tags (file UNIQUE PRIMARY KEY, tags);
CREATE TABLE titles (file NOT NULL, title );
CREATE TABLE refs (ref UNIQUE NOT NULL, file NOT NULL, type NOT NULL);
```
vs schema dump of sqlite with defined types
```sql
❯ sqlite3 chinook.db  .schema
CREATE TABLE IF NOT EXISTS "albums"
(
    [AlbumId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Title] NVARCHAR(160)  NOT NULL,
    [ArtistId] INTEGER  NOT NULL,
    FOREIGN KEY ([ArtistId]) REFERENCES "artists" ([ArtistId])
                ON DELETE NO ACTION ON UPDATE NO ACTION
);
```

**Comment by jethrokuan** [comment]
You're out of luck here. EmacsSQL basically uses STRING for all its column types, it stores the lisp object string representation into the database, and does a string serialization/deserialization when reading/writing the database. The upside is that any Emacs object can be directly stored in the database, but this means the much of the db is useless outside of Emacs.

**Comment by smallstepman** [comment]
thanks for quick response! 

https://youtu.be/qN5JUy_2HsQ?t=41 I was worried this would be the answer
seems like only way around would be to first export whole db to csv and redo the db, this time with types. I believe whole process is still achievable within the realms of nodejs. I wanted to build org-roam viz tool using that database, however other options are currently being considered https://github.com/smallstepman/org-roam-server/discussions/3

**Comment by jethrokuan** [comment]
> seems like only way around would be to first export whole db to csv and redo the db, this time with types.

This is not true, you just need to map over all the returned values from the database. Some examples:

- If column contains string, it will be stored as `"foo"` (with the quotes), you just need to `SELECT str_col FROM table`, and map over it later.
- If column contains list, it will be stored as `(a b c)`, you just need to `SELECT list_col FROM table` and parse it into an array.

The database is still readable outside of Emacs.

**Comment by smallstepman** [comment]
ah, sorry, i wasnt clear enough
i meant that in order to use that database with ORM engine I'd need to rebuild it, though that's a good point I could go the route of querying with raw sql, thanks for that
