### ISSUE TITLE
Can't set dailies capture template on v2

### ISSUE THREAD

**Issue by arozbiz** [org-roam/org-roam#1584]
### Description

I can't customize the template in the `org-roam-dailies-capture-templates` variable.

#### Steps to Reproduce

For example, I set `org-roam-dailies-capture-templates` to

```
'(("d" "default" entry "* TEST %?"
       :if-new (file+head "%<%Y-%m-%d>.org"
			  "#+title: %<%Y-%m-%d (%A)>"))))
```

#### Expected Results

I expect:
```
:PROPERTIES:
:ID:       5346f909-4a0d-4016-b43e-cefe9c35ae86
:END:
#+title: 2021-07-14 (Wednesday)
* TEST |
```
(where | is the cursor).

#### Actual Results
What I get:
```
|:PROPERTIES:
:ID:       5346f909-4a0d-4016-b43e-cefe9c35ae86
:END:
#+title: 2021-07-14 (Wednesday)
```
(where | is the cursor).

The fact that the cursor is at the top of the file makes me think that there's an error happening somewhere in the org-capture process, but running with `toggle-debug-on-error` doesn't produce anything.

### Environment

```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4)
 of 2021-07-05
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-10-gee652a-elpaplus @ /home/alan/.emacs.d/elpa/org-plus-contrib-20210712/)
- Org-roam: 2.0.0
```

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by Wetlize** [comment]
@arozbiz If you capture with `org-roam-dailies-capture-today` command, does it work then as expected?

**Comment by arozbiz** [comment]
It does indeed work! Interesting.

**Comment by Wetlize** [comment]
@arozbiz That's by design, I think. You use `org-roam-dailies-find-today` to only jump to the daily file, not capture. For a new file it will only expand `:if-new` part and will jump to the capture target, but won't run the template itself. To capture something you suppose to use instead `org-roam-dailies-capture-today` command.

**Comment by Wetlize** [comment]
@jethrokuan If that's the case, would it make sense to rename `org-roam-dailies-find-*` to `org-roam-dailies-goto-*` (or `jump`, but I think `goto` better to reflects the relevant `org-capture` argument) instead, to reduce the confusion?

**Comment by arozbiz** [comment]
But looking at the definition of `org-roam-dailies-find-today` shows that it just runs `(org-roam-dailies-capture-today t)`.

**Comment by Wetlize** [comment]
Yes, this argument that's explicitly passed to `org-roam-dailies-capture-today` is the reason why I think this behavior is by the design. It will propagate then to `goto` paremter for `org-capture` command and [do exactly what the current behavior is](https://code.orgmode.org/bzg/org-mode/src/fdb98a436bbdb86834af08c168c3bcbcc73d349c/lisp/org-capture.el#L620-L623).

**Comment by jethrokuan** [comment]
> @jethrokuan If that's the case, would it make sense to rename `org-roam-dailies-find-*` to `org-roam-dailies-goto-*` (or `jump`) instead, to reduce the confusion? People can get confused with the current naming, since `org-roam-node-find` will also try to start a full blown capture process for a new node.

Yeah I think this makes sense.
