### ISSUE TITLE
Not all files are converted by the migration wizard

### ISSUE THREAD

**Issue by linwaytin** [org-roam/org-roam#1592]
### Description
`org-roam-migrate-wizard` does not convert all notes.

#### Steps to Reproduce
1. Upgrade to V2.
2. Restart Emacs.
3. Run `org-roam-migrate-wizard`.

#### Backtrace
No error message appeared.

#### Expected Results
All files should have had a `PROPERTIES` drawer at the beginning of the file.

#### Actual Results
Only a few of them are converted.
Some files and headlines are converted, but most are not.

### Environment
- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-10-gee652a-elpa @ my_elpa)
- Org-roam: 2.0.0

**Comment by jethrokuan** [comment]
Hard to tell you what went wrong with this little information. I'll need to know if the files that were to be converted are in `(org-roam--list-all-files)`.

**Comment by linwaytin** [comment]
It looks `(org-roam--list-all-files)` gives all files I have, but only a few of them were converted.

**Comment by jethrokuan** [comment]
what exactly is not converted? You can try running `M-: (org-roam-migrate-v1-to-v2)` in the unconverted file to see if anything changes.

**Comment by linwaytin** [comment]
`(org-roam-migrate-v1-to-v2)` adds the `PROPERTIES` at the beginning of the file, so this function is fine.

**Comment by linwaytin** [comment]
I might find some hints for the problem.
In my case, it seems only the first 4 files listed by `(org-roam--list-all-files)` were converted.
(`(org-roam-node-find)` lists more, but those are headings with org-id I added before.)
The 4th file contains a `#+ROAM_KEY`. Is this relevant?

**Comment by linwaytin** [comment]
I use the backup files to run the whole process again, and surprisingly, everything seems to work this time.
I got warnings for files containing `#+roam_key`, but they are still successfully converted. Strange. 
In my opinion, I would guess that the conversion for files with `ROAM_KEY` does cause some problem.

**Comment by jethrokuan** [comment]
>  I got warnings for files containing #+roam_key, but they are still successfully converted. Strange.

What warnings?

Since it works for you now, and there's no actionable information here I'm closing this issue.

**Comment by linwaytin** [comment]
It turns out the warnings are because the old ones do not have `file://` as the prefix. Thus everything seems OK now.

Thank you for your help.
