### ISSUE TITLE
org-roam-node-slug is already defined as something else than a generic function

### ISSUE THREAD

**Issue by patrolli** [org-roam/org-roam#1598]
### Description
I update org-roam from v1 to v2. I follow the wiki page and first use the command `org-roam-migrate-wizard` to convert my org files. I finished this step, but when I use `org-roam-node-find`, it failed and show this error message.
### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 28.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2021-07-07
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4 @ /usr/local/share/emacs/28.0.50/lisp/org/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
What does your config look like?

**Comment by patrolli** [comment]
Thanks for your quick reply, my config now is this
```elisp
(use-package org-roam
  :ensure t
  ;; :hook
  ;; (after-init . org-roam-mode)
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory (concat lxs-home-dir "Documents/" "org/" "org-roam-files"))
  :pretty-hydra
  ((:title (pretty-hydra-title "Org roam menu" 'faicon "book"  :height 1.1 :v-adjust -0.1)
    :color blue)
   ("Basic"
    (("f" org-roam-node-find "find nodes")
     ("b" org-roam-switch-to-buffer "switch buffer")
     ("i" org-roam-node-insert "insert")
     ("I" org-roam-inert-immediate "insert immediate")
     ("t" org-roam-tag-add "add tag"))
    "Dailies"
    (("j " org-roam-dailies-capture-today "capture today daily")
     ("y " org-roam-dailies-capture-yesterday "capture yesterday daily")
     ("s a" org-roam-dailies-today "show today daily")
     ("s y" org-roam-dailies-yesterday "show yesterday daily")
     ("s f" org-roam-dailies-find "find dailies"))
    "Others"
    (("v t" org-tags-view "filt buffer tags")
     ("q" hydra-pop "exit")
   )))
  :config
  (org-roam-setup)
  (require 'org-roam-protocol)
	)  
```

**Comment by jethrokuan** [comment]
Nothing looks off, could you try relaunching Emacs with `--debug-init` and get a backtrace?

**Comment by patrolli** [comment]
Here is the screenshot of `emacs --debug-init` startup:
![image](https://user-images.githubusercontent.com/25717445/126059544-8e6049fa-3458-408c-817d-bc7dca9bbd18.png)

**Comment by patrolli** [comment]
opps, seems I found what's wrong with it. I ever custom a function to query org-roam.db with tag "Project". I comment this function and try again.

**Comment by patrolli** [comment]
This problem disappears~ I define a custom function somewhere that use the function `org-query-db`, which will cause this problem when updating into org-roam-v2. Thanks for your quick and enthusiasitc reply.
