### ISSUE TITLE
After starting Emacs for the first time, I had to run org-roam-setup once to execute some roam commands， otherwise, I would get an error.

### ISSUE THREAD

**Issue by flyingns** [org-roam/org-roam#1600]
### Description

I usually start my notes with 'org-roam-dailies-capture today' after starting Emacs. I must manually execute org-roam-setup once before this command, otherwise I will report an error like this:

```
Org-roam-capture -: Symbol's function definition is void: org-roam-node-create.
```

There are several roam commands that produce similar errors, such as `org-roam-db-sync`, `org-roam-dailies-captured-date` ... etc.

These commands can be used normally only after `org-roam-setup` is executed. Is this a BUG or am I doing something wrong?

**Comment by jethrokuan** [comment]
What does your config look like? It's probably missing byte-compile declarations again like #1590 .

You should call `(org-roam-setup)` once in your init file, otherwise your db will not be kept in sync.

**Comment by flyingns** [comment]
```
(use-package! org-roam
  :after org
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n g" . org-roam-graph)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n c" . org-roam-capture)
         ("C-c n T" . org-roam-dailies-capture-today))
  :config
  (org-roam-setup))
```

It turns out that `bind` causes this error,

Remove the bind part and return to normal.

**Comment by Wetlize** [comment]
I think this is something to do with the new autoload cookies that I've added. Things like `:bind` and `:commands` will create autoloads directly to the main file of the corresponding package, in the case of org-roam it will be `org-roam.el`, but the `###autoload`s provided by the package point to their own files, e.g. in the case of `org-roam-dailies-capture-today` the autoload from the package will point to `org-roam-dailies.el`.

If that's the case, it could be that there's some missing `require`s in the package itself.
