### ISSUE TITLE
On Android Termux, any access to the database fails with "middleware out of memory" error

### ISSUE THREAD

**Issue by chunglak** [org-roam/org-roam#1605]
In emacs running in Termux on Android, when running `org-roam-setup` or any function that accesses the database, the process aborts with a "middleware out of memory" error.
I tracked it down to apparently a problem with the binary compiled by emacsql-sqlite that somehow doesn't work on Termux.
If I replace the call to `emacsql-sqlite` in `org-roam-db` with `emacsql-sqlite3`, it seems to work. 
I read somewhere that the reason org-roam moved from emacsql-sqlite3 to emacsql-sqlite was to support foreign keys, but it seems emacsql-sqlite3 also supports foreign key if called with the pragma directive "foreign-keys=on", which I saw in the code for `org-roam-db-init`.

So, is it ok to use this workaround?

**Comment by jethrokuan** [comment]
You can use emacsql-sqlite3 if you want (by changing the code locally), there's no hard dependency on the foreign keys for now. I've tried the pragma directive and it doesn't work.

**Comment by chunglak** [comment]
Perfect, thanks!

**Comment by iT-Boyer** [comment]
After upgrading V2 in termux, the same "middleware out of memory" issues were encountered,How did you replace SQLite with SQLite3 to fix the problem?
I try this ,but don't work.
```elisp
(use-package! emacsql-sqlite
  :custom (emacsql-sqlite-executable-path (executable-find "sqlite3"))
  )
```

**Comment by chunglak** [comment]
The emacsql-sqlite executable is not the sqlite3 binary but a custom-compiled binary that incorporates sqlite that is generated in a subdirectory of the emacsql-sqlite project, and that's this executable that's not working on termux.
That's why I switched the emacs-to-sqlite interface from emacs-sqlite to emacs-sqlite3 which is a pure elisp module that directly uses the sqlite3 binary.

What I ended up doing was to include the below after loading the package but before calling `org-roam-setup` to redefine some org-roam functions (it's important to enable foreign-keys otherwise each time a note changes, the database update will fail with `UNIQUE constraint failed on nodes.id
`
```
    (require 'emacsql-sqlite3)
    (defun org-roam-db ()
      "Entrypoint to the Org-roam sqlite database.
Initializes and stores the database, and the database connection.
Performs a database upgrade when required."
      (unless (and (org-roam-db--get-connection)
                   (emacsql-live-p (org-roam-db--get-connection)))
        (let ((init-db (not (file-exists-p org-roam-db-location))))
          (make-directory (file-name-directory org-roam-db-location) t)
          ;; (let ((conn (emacsql-sqlite org-roam-db-location)))
          (let ((conn (emacsql-sqlite3 org-roam-db-location)))
            (emacsql conn [:pragma (= foreign_keys ON)])
            (set-process-query-on-exit-flag (emacsql-process conn) nil)
            (puthash (expand-file-name org-roam-directory)
                     conn
                     org-roam-db--connection)
            (when init-db
              (org-roam-db--init conn))
            (let* ((version (caar (emacsql conn "PRAGMA user_version")))
                   (version (org-roam-db--upgrade-maybe conn version)))
              (cond
               ((> version org-roam-db-version)
                (emacsql-close conn)
                (user-error
                 "The Org-roam database was created with a newer Org-roam version.  "
                 "You need to update the Org-roam package"))
               ((< version org-roam-db-version)
                (emacsql-close conn)
                (error "BUG: The Org-roam database scheme changed %s"
                       "and there is no upgrade path")))))))
      (org-roam-db--get-connection))
    (defun org-roam-db--init (db)
      "Initialize database DB with the correct schema and user version."
      (emacsql-with-transaction db
        ;; (emacsql db "PRAGMA foreign_keys = ON")
        (emacsql db [:pragma (= foreign_keys ON)])
        (pcase-dolist (`(,table ,schema) org-roam-db--table-schemata)
          (emacsql db [:create-table $i1 $S2] table schema))
        (pcase-dolist (`(,index-name ,table ,columns) org-roam-db--table-indices)
          (emacsql db [:create-index $i1 :on $i2 $S3] index-name table columns))
        (emacsql db (format "PRAGMA user_version = %s" org-roam-db-version))))

```

**Comment by bram85** [comment]
I filed this issue at emacsqsl, see https://github.com/skeeto/emacsql/issues/78 , hoping for a more structural solution.

**Comment by bram85** [comment]
I fixed the error in Termux, happily using org-roam v2 with emacsql-sqlite now on Android. I filed a [PR](https://github.com/skeeto/emacsql/pull/79) towards the project, let's hope it gets incorporated.

**Comment by emacsomancer** [comment]
@chunglak thanks for this. it at least gets me by the "Selecting deleted buffer" error I was having.

(Though I ran into some issues - like `EmacsSQL had an unhandled condition: "near line 159: UNIQUE constraint failed: nodes.id"`)

**Comment by CapMau** [comment]
Hello, 
Bram85 solution, where you reanme the buffer does nothing for me, unless i need to do some extra step other then change theyr name.

copy pasting your solution onto my doomemacs config only produces an error, at the start of emacs, declaring that sqlite3 wasnt found.

being no expert, and a big noob at this, i would appreciate a more straithgfoward solution, or atleast a hint of where Im failing.

I have searched, on and off for the last month and a half for it, so any help is deeply apreciated.

**Comment by bram85** [comment]
Did you recompile emacsql-sqlite after making changes to the C source file?

**Comment by CapMau** [comment]
> Did you recompile emacsql-sqlite after making changes to the C source file?

using DOOM emacs, did a DOOM build, same error, nothing changed

**Comment by chunglak** [comment]
Just go to the emacs-sqlite/sqlite folder and delete the emacs-sqlite binary. On relaunch of emacs it will be recompiled automatically.

**Comment by ISouthRain** [comment]
Oh，I also have the same problem!
The solution I solved is to run the command "rm Your Org-Roam.db" before running Emacs.
This will restart writing data, but if your file is very much, this data write will take some time.
This doesn't need any configuration, you only need to let Roam use Emacs SQLITE3!

**Comment by ronnac** [comment]
> The emacsql-sqlite executable is not the sqlite3 binary but a custom-compiled binary that incorporates sqlite that is generated in a subdirectory of the emacsql-sqlite project, and that's this executable that's not working on termux. That's why I switched the emacs-to-sqlite interface from emacs-sqlite to emacs-sqlite3 which is a pure elisp module that directly uses the sqlite3 binary.
> 
> What I ended up doing was to include the below after loading the package but before calling `org-roam-setup` to redefine some org-roam functions (it's important to enable foreign-keys otherwise each time a note changes, the database update will fail with `UNIQUE constraint failed on nodes.id `
> 
> ```
>     (require 'emacsql-sqlite3)
>     (defun org-roam-db ()
>       "Entrypoint to the Org-roam sqlite database.
> Initializes and stores the database, and the database connection.
> Performs a database upgrade when required."
>       (unless (and (org-roam-db--get-connection)
>                    (emacsql-live-p (org-roam-db--get-connection)))
>         (let ((init-db (not (file-exists-p org-roam-db-location))))
>           (make-directory (file-name-directory org-roam-db-location) t)
>           ;; (let ((conn (emacsql-sqlite org-roam-db-location)))
>           (let ((conn (emacsql-sqlite3 org-roam-db-location)))
>             (emacsql conn [:pragma (= foreign_keys ON)])
>             (set-process-query-on-exit-flag (emacsql-process conn) nil)
>             (puthash (expand-file-name org-roam-directory)
>                      conn
>                      org-roam-db--connection)
>             (when init-db
>               (org-roam-db--init conn))
>             (let* ((version (caar (emacsql conn "PRAGMA user_version")))
>                    (version (org-roam-db--upgrade-maybe conn version)))
>               (cond
>                ((> version org-roam-db-version)
>                 (emacsql-close conn)
>                 (user-error
>                  "The Org-roam database was created with a newer Org-roam version.  "
>                  "You need to update the Org-roam package"))
>                ((< version org-roam-db-version)
>                 (emacsql-close conn)
>                 (error "BUG: The Org-roam database scheme changed %s"
>                        "and there is no upgrade path")))))))
>       (org-roam-db--get-connection))
>     (defun org-roam-db--init (db)
>       "Initialize database DB with the correct schema and user version."
>       (emacsql-with-transaction db
>         ;; (emacsql db "PRAGMA foreign_keys = ON")
>         (emacsql db [:pragma (= foreign_keys ON)])
>         (pcase-dolist (`(,table ,schema) org-roam-db--table-schemata)
>           (emacsql db [:create-table $i1 $S2] table schema))
>         (pcase-dolist (`(,index-name ,table ,columns) org-roam-db--table-indices)
>           (emacsql db [:create-index $i1 :on $i2 $S3] index-name table columns))
>         (emacsql db (format "PRAGMA user_version = %s" org-roam-db-version))))
> ```

@bram85 @chunglak where do you put this code in Doom Emacs? I tried in config.el but  I get errors.

**Comment by chunglak** [comment]
What kind of error are yoy getting?

**Comment by ronnac** [comment]
@chunglak I had the "out of memory" error. Further research revealed that @bram85 had found the cause (in emacsql), written a fix and created a [pull request](https://github.com/skeeto/emacsql/pull/79), which has not yet been approved by the maintainer of emacsql. Here's how to use this fix in Doom Emacs in termux on Android:

First remove org-roam if you have already installed it:
In init.el replace 
`(org +roam2)` 
by 
`org`

Then open packages.el and add
```
(package! emacsql
  :recipe
        (:host github
        :repo "bram85/emacsql"
        :files ("*")))
```
- run `doom sync`
- restart Emacs

Now in init.el put back 
`(org +roam2`
- run `doom sync`
- restart Emacs

Create a new Roam note :
SPC n r n

You should see 'compiling emacs-sqlite'.

This is a temporary workaround to make org-roam and magit work in termux until above mentioned pull request is accepted.

**Comment by chunglak** [comment]
Yes, that or my initial workaround to use emacsql-sqlite3 instead of emacsql-sqlite. But obviously, it'd be nice if the emacsql maintainer integrated the patch

**Comment by ronnac** [comment]
I didn't know how to apply your workaround in doom Emacs, I'm fairly new to Emacs.

**Comment by chunglak** [comment]
I actually don't use my workaround anymore. I just patched emasql as per @bram85.
But I just discovered that there's now a setting in org-roam to use emacsql-sqlite3: just put  (setq org-roam-database-connector 'sqlite3) in your config (haven't tried)

**Comment by ISouthRain** [comment]
but, add new id to sync have erro 'UNIQUE constraint failed on nodes.id'

**Comment by chunglak** [comment]
That means the foreign key feature of sqlite is not active. Did you set (setq org-roam-database-connector 'sqlite3)?

**Comment by ISouthRain** [comment]
yes

**Comment by chunglak** [comment]
Maybe you can go back to your previous solution using @bram85's solution.
I think the problem there is that you still had the original emacsql and not @bram85's fork. Maybe you can go to wherever the package is stored in your system, delete it and restart emacs?

**Comment by Cletip** [comment]
Your setup @chunglak and explanation helped me a lot, and I thank you for that! On the other hand, I have a mistake, which doesn't seem very important but which may have the merit to be underlined: 
"Selecting deleted buffer", which comes (I think) from using the emacsql-sqlite3 function.
Do you have this error too? 
I have looked on the net and unfortunately I have not found anything that would allow me to solve this error. Moreover, I have the impression that everything is working properly.

PS: I'm doing this under termux, and everything seems to work... except this "error"

Thank you in advance for your answers.

**Comment by ISouthRain** [comment]
It might be a roam configuration problem, as I did
, It is my roam config,no errors 👇
OS: Termux
version: Emacs 28.1
roam-version: org-roam-20220528.1937
Package download: Elpa
```elisp
;; org-roam
(use-package org-roam
  :defer 3
  :ensure t
  :init
  (when (string= "windows-nt" system-type)
  (setq org-roam-directory (file-truename "F:\\MyFile\\Org")))
  (when (string= "gnu/linux" system-type)
  (setq org-roam-directory (file-truename "~/MyFile/Org/")))
  (when (string= "darwin" system-type)
  (setq org-roam-directory (file-truename "~/Desktop/MyFile/Org/")))
  :config
(defun org-roam-db-sync-myself ()
  (interactive) ; 如果不需要定义成命令，这句可以不要。
(when (string= "gnu/linux" system-type)
  (shell-command "rm ~/.emacs.d/emacs/var/org/org-roam.db")
)
(when (string= "darwin" system-type)
  (shell-command "rm ~/.emacs.d/emacs/var/org/org-roam.db")
)
(when (string= "windows-nt" system-type)
  (shell-command "del C:\\Users\\Jack\\AppData\\Roaming\\.emacs.d\\emacs\\var\\org\\org-roam.db")
)
  (org-roam-db-sync)
(evil-goto-line)
(org-global-cycle)
)

(require 'org-roam-protocol)
  ;;搜索
(setq org-roam-node-display-template "${title}")

;;补全
(setq org-roam-completion-everywhere t)

;;一个也可以设置org-roam-db-node-include-function。例如，ATTACH要从 Org-roam 数据库中排除所有带有标签的标题，可以设置：
(setq org-roam-db-node-include-function 
      (lambda () 
        (not (member "ATTACH" (org-get-tags)))))

(setq org-roam-db-update-on-save t)

(setq org-roam-db-gc-threshold most-positive-fixnum)

;; 创建左边显示子目录分类
(cl-defmethod org-roam-node-type ((node org-roam-node))
  "Return the TYPE of NODE."
  (condition-case nil
      (file-name-nondirectory
       (directory-file-name
        (file-name-directory
         (file-relative-name (org-roam-node-file node) org-roam-directory))))
    (error "")))

(setq org-roam-node-display-template
      (concat "${type:15} ${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
(org-roam-db-autosync-mode)
(setq org-roam-database-connector 'sqlite)

)
```

**Comment by Cletip** [comment]
Ok so I removed the redefinition of the org-roam-db--init and org-roam-db functions, and I used exactly the same setup as on my computer... and everything works fine.
I've made a lot of trouble for nothing (I followed a tutorial that looks... not very fair)
Thanks a lot for your answer @ISouthRain
