### ISSUE TITLE
Basic functions are not defined, such as `org-roam` and `org-roam-find-file`

### ISSUE THREAD

**Issue by TheCatster** [org-roam/org-roam#1607]
### Description
I was having the same issues as #1600. I saw that `bind` was most likely causing problems, so I removed it as suggested. This, however, broke the rest of my `org-roam` setup. I can no longer use any basic commands, such as `org-roam-find-file`, `org-roam`, etc (all those mentioned in the `bind`.) I am not sure why this is, and wish I was of more help. What I can do is provide my configuration, and the very minimal backtrace Emacs shows.

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam`, `org-find-file`
3. See "backtrace" (since there really is not one)

#### Backtrace
```sh
Symbol's function definition is void: org-roam
Symbol's function definition is void: org-roam-find-file
```

#### Expected Results
The functions run: I see the pop-up with `org-roam`, I get to select a file with `org-roam-find-file`, etc.

#### Actual Results
The above error.

### Environment
```sh
Copy info below this line into issue:
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
 of 2021-07-17
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-g604bfd @ /home/danya/.emacs.d/straight/build/org/)
- Org-roam: 2.0.0
 ```
### Configuration
My `org-roam` configuration is as follows:
```elisp
(setq org-roam-v2-ack t)
(use-package org-roam
  :custom
  (org-roam-db-gc-threshold most-positive-fixnum)
  (org-roam-directory "~/Nextcloud/org/org-roam")
  :config
  (org-roam-setup))
```
I've also tried separately adding in the keybindings (which fixes the autoload issue but this one appears):
```elisp
;; Org Roam
(bind-keys :map global-map
           :prefix-map my-org-mode-map
           :prefix "C-c n"
           ("l" . org-roam)
           ("f" . org-roam-find-file)
           ("g" . org-roam-graph)
           ("i" . org-roam-insert)
           ("I" . org-roam-insert-immediate))
```
Thank you!

**Comment by nobiot** [comment]
org-roam-find-file should be org-roam-node-find (the former does not exist in v2).
Would this solve the issue?

**Comment by nobiot** [comment]
Also… org-roam isn’t a command now. I believe what you are after is 
org-roam-buffer-toggle.

https://www.orgroam.com/manual.html#The-Org_002droam-Buffer

**Comment by jethrokuan** [comment]
> I do not know if there is an equivalent for insert-immediate.

There is not.

**Comment by TheCatster** [comment]
Alright, thank you both! I didn't see that in the section for migrating to v2, would you think that should be there? My apologies if this was written somewhere obviously (I assume I looked at the README, thought that it was similar enough, and didn't read it thoroughly).

This did work!
