### ISSUE TITLE
Incomplete org-protocol setup

### ISSUE THREAD

**Issue by ndw** [org-roam/org-roam#1614]
### Description

I noticed the AppleScript application in the manual and got excited about the possibility of getting org-protocol to work. I've tried several times in the past but never had any luck.

#### Steps to Reproduce

1. Follow the instructions for configuring the `OrgProtocolClient.app`.
2. Create the bookmarklet
3. Restart the browser (because that seemed to be necessary)
4. Restart emacs, for good measure.
5. `(require org-protocol)`
6. Click on the bookmarklet

#### Expected Results

To be editing an org-roam note for the website.

#### Actual Results

I'm editing an empty buffer named `roam-ref?template=r&ref=https://...` that's visiting the file `//org-protocol:/roam-ref?template=r&ref=https://...`

### Environment

```
- Emacs: GNU Emacs 27.2 (build 3, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
 of 2021-07-01
- Framework: N/A
- Org: Org mode version 9.4.6 (release_9.4.6-598-g604bfd @ /Users/ndw/.emacs.d/straight/build/org/)
- Org-roam: 2.0.0
```

I'm reasonably sure this is user-error, but a little nudge in the right direction would certainly be appreciated!

**Comment by jethrokuan** [comment]
You need to `(require 'org-roam-protocol)` as well.

**Comment by ndw** [comment]
Thank you. *blush*
