### ISSUE TITLE
Migrate wizard drops description from links while migrating

### ISSUE THREAD

**Issue by blaa** [org-roam/org-roam#1617]
#### Steps to Reproduce
Have org files with meaningful descriptions like this:
    
    [[file:projects/20200816195754-esp8266_nodemcu_learning.org][esp8266 description]]

Run org-roam-migrate-wizard and get them converted to:

    [[id:22511b7f-ad6c-499e-926d-c084d42e79eb]]

I don't see reason why migrator can't preserve the descriptions.

#### Expected Results

    [[id:22511b7f-ad6c-499e-926d-c084d42e79eb][esp8266 description]]

#### Actual Results

    [[id:22511b7f-ad6c-499e-926d-c084d42e79eb]]

### Environment

Fresh melpa version (updated before running) on org mode 9.4.6, emacs 28.0.50 spoiled heavily with spacemacs.
    
To run migrator I had to disable the git-gutter-mode which caused the migrator to do nothing, and break emacs in fact, neither buffer list, or killing a buffer or running M-x would work afterwards (with the selecting deleted buffer error) - I updated wiki about it.

- Emacs: GNU Emacs 28.0.50 (build 3, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
 of 2021-07-15
- Framework: Spacemacs
- Org: Org mode version 9.4.6 (9.4.6-10-gee652a-elpaplus @ /home/bla/.emacs.d/elpa/28.0/develop/org-plus-contrib-20210712/)
- Org-roam: 2.0.0

**Comment by blaa** [comment]
Maybe link descriptions could be generated from the file names if lacking too... currently this drops a lot of information. I don't have much links so I'll fix them by hand. My links in dailies (tomorrow/yesterday) got mangled a lot, but those are of low value.

**Comment by blaa** [comment]
I guess pullrequest 1615 would fix that? Just managed to find some discussion in prs/closed issues: https://github.com/org-roam/org-roam/commit/63450e9eaf66c554f6ebd9b6dd7c34353e5d9953 https://github.com/org-roam/org-roam/pull/1609

**Comment by jethrokuan** [comment]
Should be closed by #1615 , apologies for the error
