### ISSUE TITLE
org-roam-migrate-wizard: Symbol’s function definition is void: org-roam--list-all-files

### ISSUE THREAD

**Issue by revrari** [org-roam/org-roam#1620]
### Description

org-roam-migrate-wizard generates an error:
`org-roam-migrate-wizard: Symbol’s function definition is void: org-roam--list-all-files`

#### Steps to Reproduce

Start Emacs
Update `org-roam` to version 2 using `straight`
M-x `org-roam-migrate-wizard`

#### Backtrace

Unable to run a backtrace

### Environment
Copy info below this line into issue:
- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21)
 of 2021-03-26

**Comment by gpetrini** [comment]
I had the same issue using doom emacs:
```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
 of 2021-07-16, unofficial emacs-snapshot build: http://emacs.secretsauce.net
- Framework: Doom
- Org: Org mode version 9.5 (9.5-b83ae59 @ /home/gpetrini/.emacs.d/.local/straight/build-28.0.50/org/)
- Org-roam: 2.0.0
```

**Comment by jethrokuan** [comment]
It's because of all the deferred loading, similar in cause to #1590, just evaluate `(require 'org-roam)` first in the meantime.

**Comment by gpetrini** [comment]
Thank you for the quick response.
After including `(require 'org-roam)` the procedure moved on, but I got a new error:
`org-id-add-location: Wrong type argument: hash-table-p, nil`

If this is not related with this issue I can open a new one.

**Comment by jethrokuan** [comment]
Please see if anything in this thread helps https://github.com/org-roam/org-roam/issues/1526

**Comment by gpetrini** [comment]
It worked!
Thank you a lot for the support and for this amazing package.

**Comment by revrari** [comment]
It is a pity that you have chosen to close this issue before checking with me who opened it to see if it was solved.

**Comment by jethrokuan** [comment]
Sorry didn't notice you weren't OP.

**Comment by revrari** [comment]
Thank you. I have now successfully migrated.
