### ISSUE TITLE
Database doesn't seem to sync automatically

### ISSUE THREAD

**Issue by ndw** [org-roam/org-roam#1623]
### Description

I've noticed that new notes aren't getting automatically indexed. I don't recall having this issue with V1. 

#### Steps to Reproduce

1. Run `org-roam-node-find` and type in some new title (Outer Test).
2. Write a few words, then run `org-roam-node-insert` and create another new entry (Inner Test).
3. Write a few words, then save with `C-c C-c`.
4. The link is correctly added to Outer Test and following the link works.
5. Save Outer Test with `C-c C-c`

#### Expected Results

Now if I run `org-roam-node-find`, I expect to be able to find both Outer Test and Inner Test.

#### Actual Results

Neither show up. (When I started this report, I *thought* it was only the inner one that didn't show up, that was the behavior I noticed this morning, but it appears to apply to both notes.)

If I run `org-roam-db-sync` by hand, then everything works as I expect.

### Environment

```
- Emacs: GNU Emacs 27.2 (build 3, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
 of 2021-07-01
- Framework: N/A
- Org: Org mode version 9.4.6 (release_9.4.6-598-g604bfd @ /Users/ndw/.emacs.d/straight/build/org/)
- Org-roam: 2.0.0
```

Here's the relevant part of my init file, in case this turns out to be just user error again:

```
(straight-use-package
 '(org-roam :type git :host github :repo "org-roam/org-roam"))

(global-set-key "\C-cnl" 'org-roam-buffer)
(global-set-key "\C-cnf" 'org-roam-node-find)
(global-set-key "\C-cni" 'org-roam-node-insert)
;(global-set-key "\C-cng" 'org-roam-show-graph)

(setq org-roam-directory "/Users/ndw/Documents/Notes")

(setq org-roam-v2-ack t)
(require 'org-roam)
(require 'org-protocol)
(require 'org-roam-protocol)
```

**Comment by JingYenLoh** [comment]
I believe you're missing an `(org-roam-setup)` in your init file, which is the last line required in 5.3 Setting up Org-roam.

**Comment by ndw** [comment]
Yes. That was it. User error, as expected.

In my defense, when `(org-roam-setup)` is first encountered in 4.4.1, the impression I got was that this was something you had to do once, not every time you start Emacs. But that's a lame defense since on closer inspection 5.3 is entirely clear about it. :-/
