### ISSUE TITLE
Errors while Installing Org-Roam via Melpa

### ISSUE THREAD

**Issue by aprajit** [org-roam/org-roam#1626]
### Description
Hi,
I get numerous errors while installing org-roam on melpa (ubuntu 20.04) and several commands are not recognized after install (e.g. org-roam-db-build-cache).

#### Steps to Reproduce
M-x package-install org-roam
------------------

#### Actual Results
produces the following results:
----------------------
In toplevel form:
org-roam-capture.el:528:1:Warning: Unused lexical variable
    ‘org-end-time-was-given’

In end of data:
org-roam-capture.el:829:1:Warning: the following functions are not known to be
    defined: org-roam-node-from-id, org-roam-node-from-title-or-alias,
    org-roam-node-file, org-roam-node-point, org-roam-node-id,
    org-element-type, org-element-property, org-roam-populate,
    org-roam-node-create, org-roam-node-read

In end of data:
org-roam-dailies.el:333:1:Warning: the function ‘org-roam-node-create’ is not
    known to be defined.

In org-roam-db-sync:
org-roam-db.el:484:18:Warning: reference to free variable ‘file’

In end of data:
org-roam-db.el:525:1:Warning: the function ‘file’ is not known to be defined.

In end of data:
org-roam-graph.el:282:1:Warning: the following functions are not known to be
    defined: org-roam--nodes-table, org-roam-node-p, org-roam-node-title,
    org-roam-node-id, org-roam-node-at-point

In org-roam-migrate-wizard:
org-roam-migrate.el:82:83:Warning: reference to free variable
    ‘org-roam-directory’

In end of data:
org-roam-migrate.el:194:1:Warning: the following functions are not known to be
    defined: org-roam--list-all-files, org-roam-ref-add, org-roam-alias-add

In org-roam-file-at-point:
org-roam-mode.el:371:44:Warning: Unknown slot ‘node’

In org-roam-unlinked-references-section:
org-roam-mode.el:433:78:Warning: reference to free variable
    ‘org-roam-file-extensions’

In end of data:
org-roam-mode.el:469:1:Warning: the following functions are not known to be
    defined: org-roam-node-title, org-roam-node-id, org-roam-node-create,
    org-roam-node-insert-section, org-roam-node-refs, org-roam-node-file,
    org-roam-node-aliases, org-roam--list-files-search-globs

In end of data:
org-roam-overlay.el:99:1:Warning: the following functions are not known to be
    defined: org-roam-node-from-id, org-roam-node-title

In org-roam-protocol-open-ref:
org-roam-protocol.el:68:28:Warning: assignment to free variable ‘k’
org-roam-protocol.el:68:28:Warning: assignment to free variable ‘v’
org-roam-protocol.el:70:61:Warning: reference to free variable ‘k’
org-roam-protocol.el:70:61:Warning: reference to free variable ‘v’

### Environment
- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)
 of 2020-03-26, modified by Debian
- Framework: I don't know
- Org: Org mode version 9.4.6 (9.4.6-11-g1ee52c-elpa @ ~/.emacs.d/elpa/org-20210719/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
These are just byte-compile errors, you can safely ignore them.

The installation is fine, `org-roam-db-build-cache` is not a command anymore, please read [the wiki](https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2) for more info.

**Comment by aprajit** [comment]
Thank You!
