### ISSUE TITLE
Padding & white spaces added by `format-entry` confuses completion

### ISSUE THREAD

**Issue by nobiot** [org-roam/org-roam#1627]
#### Case 1
This file node in the image below is entitled "Note". 
Simply typing "Note" in the minibuffer does not match it; you need all the spaces after it padded by `format-entry` function.

Padding is added based on the default value of variable `org-roam-node-display-template` `"${title:*} ${tags:10}"`

![image](https://user-images.githubusercontent.com/12507865/126225111-37b6817f-004c-4a48-b308-c7eb255f1f14.png)

If you accidentally type "Note" without tab completing it, you would end up creating a new file with the same title. 
For some reason, next time you call `org-roam-node-find` shows you only one of the notes created (where do we de-dupe this?)
Dired correctly shows two files.

#### Case 2
If I change the variable to the following value:

    (setq org-roam-node-display-template "${tags:10} ${title:*}")

![image](https://user-images.githubusercontent.com/12507865/126225736-beb51e0e-79a4-4439-9f9e-404d51d2084d.png)

Typing "Note" and TAB does not match it -- you would need to take care of the initial padded spaces e.g. by typing "*Note"

I don't know if there is an easy fix for this, but I'm sending a simple PR that might get your thoughts going. I think the formatted candidate string needs to be trimmed left and right both.

#### Steps to Reproduce

- emacs -Q (or new HOME location)
- Add MELPA archive, install `org-roam`
- Create a note with a title (see the image above)
- Call `org-roam-node-find`

#### Backtrace
Not applicable

#### Expected Results
For Case 1, typing "Note" matches the file node entitled "Note"

For Case 2, typing "Note" match the file node

#### Actual Results
For Case 1, it will create a new file with the same title.

For Case 2, no match

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-w64-mingw32)
 of 2021-03-26
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4 @ c:/Program Files/Emacs/x86_64/share/emacs/27.2/lisp/org/)
- Org-roam: 2.0.0

- MELPA org-roam-20210719.930

**Comment by jethrokuan** [comment]
Unfortunately this fix is not correct, the spaces are there for alignment and shouldn't be trimmed.

Not sure there's a fix at all here, unless we give up alignment.

**Comment by nobiot** [comment]
@jethrokuan 
Thanks for the comment.

The fix retains padding between columns; it removes only the outer-most padding.

Could you consider following if not s-trim both left and right?

1. Trim right
2. Disallow column width "*" if it is not the last column

Trimming right solves Case 1 I report.

Disallowing "*" for columns that are not the last one should solve this issue in the image. Note the wide gap between the title and tag. This is after applying the fix (retaining formatting between columns).
![image](https://user-images.githubusercontent.com/12507865/126268397-f5bdaba1-0f34-4136-9ca2-fb7daa4d47bf.png)

This should should also solve a formatting problem for Helm users.

If there isn't an easy way, could I suggest to change the default value of `org-roam-node-display-template` to be something like
`"${tags:10} ${title:*}"` or `"${title:60} {tags:10}"`?

**Comment by nobiot** [comment]
@jethrokuan 
I have a second thought now. Maybe it's a matter of setting the right "length" values to `org-roam-node-display-template` (or choosing not to set a length specifier); perhaps this does not require program change.
