### ISSUE TITLE
Inconsistencies in org-roam buffer with toggle function

### ISSUE THREAD

**Issue by agarbuno** [org-roam/org-roam#1630]
### Description

I am not sure I grasp the difference between the `org-roam-buffer` and `org-roam-buffer-toggle`. I am trying out V2 and although I understand the concept of having the backlinks buffer somewhat permanently (which is achieved by `org-roam-buffer-toggle`), I am experiencing a situation where the `org-roam-buffer-toggle` opens up a buffer that tracks the node as intended. The problem is that the contents are not in order (see below). 

#### Steps to Reproduce

With my existing configuration after following the wiki is enough to follow this

#### Backtrace

I am not seeing any messages in the debugger buffer. 

#### Expected Results

I would expect both buffers to be like the one under `org-roam-buffer`. 

#### Actual Results

<img width="2242" alt="image" src="https://user-images.githubusercontent.com/6402081/126235175-7eb0727c-7408-4a68-b8a5-bdf70f86354d.png">

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95))
 of 2021-03-27
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by nobiot** [comment]
Try turning off `page-break-lines-mode` (or something called similarly) if you have it. If you don’t and still have this issue, I am not sure what causes it.

**Comment by agarbuno** [comment]
Thanks a lot for the response! I don't have it enabled globally as a quick describe variable at startup on `page-break-lines-mode` is set to `nil`. However, I do see that the mode is enabled in certain nodes. I deleted the package from my config and that solved the issue.

**Comment by mattford63** [comment]
Spacemacs uses page-break-lines-mode in it's core

Forcing the removal by hacking out the page-break-lines-mode require solves the problem.  But it it's ugly.

I tried `(delete 'outline-mode page-break-lines-modes)` to remove it from all org buffers but that didn't help.

Why does it work in the org-roam-buffer but not the toggle one?  Seems weird.

**Comment by carlos-wong** [comment]
I found run org-roam-buffer-refresh in the org-roam-buffer-toggle result buffer will fix this issue.
