### ISSUE TITLE
Cannot use calendar

### ISSUE THREAD

**Issue by cheerio-pixel** [org-roam/org-roam#1633]
### Description

Since `org-roam-dailies-calendar--file-to-date` doesn't check if the input is a file name like "capture.org", `org-parse-time-string` will throw an error and make the calendar unusable and the functions that use it.

#### Steps to Reproduce

1. Either run `calendar`, `org-time-stamp`, `org-time-stamp-inactive` or `org-roam-dailies-find-date`. In my case `org-time-stamp-inactive`

#### Backtrace

`Debugger entered--Lisp error: (error "Not an Org time string: capture")`
  `signal(error ("Not an Org time string: capture"))`
  `error("Not an Org time string: %s" "capture")`
  `org-parse-time-string("capture")`
  `org-roam-dailies-calendar--file-to-date("/home/cheerio-pixel/Dropbox (Maestral)/Creativè/org-roam/capture/capture.org")`
  `mapcar(org-roam-dailies-calendar--file-to-date ("/home/cheerio-pixel/Dropbox (Maestral)/Creativè/org-roam/capture/capture.org"))`
  `org-roam-dailies-calendar-mark-entries()`
  `run-hooks(calendar-today-visible-hook)`
  `#f(compiled-function () #<bytecode -0x1d53d4755e0db681>)()`
  `calendar-generate-window(7 2021)`
  `calendar-basic-setup(nil)`
  `calendar()`
  `org-read-date(nil totime nil nil nil nil inactive)`
  `org-time-stamp(nil inactive)`
  `org-time-stamp-inactive(nil)`
  `funcall-interactively(org-time-stamp-inactive nil)`
  `call-interactively(org-time-stamp-inactive nil nil)`
  `command-execute(org-time-stamp-inactive)`

#### Expected Results
Is inserting my timestamp

#### Actual Results
I don't get my timestamp

### Environment
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-07-07
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4 @ /usr/share/emacs/28.0.50/lisp/org/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/3a78422

**Comment by randomwangran** [comment]
This issue came from commit: 56a5723c37601c86e7cc8292fc38c8bc8c0e1998


The following hook was first introduced in this [line](https://github.com/org-roam/org-roam/commit/56a5723c37601c86e7cc8292fc38c8bc8c0e1998#diff-ea64d21b3bb52b9bc05a500003131b74e4d558776418cf34463d09ae579184dfR306.), which is the source of the problem.

`(add-hook 'calendar-today-visible-hook #'org-roam-dailies-calendar-mark-entries)`

**Comment by mbafford** [comment]
This is a duplicate/related to #1585 
I left a comment here with more details about what's happening:
https://github.com/org-roam/org-roam/issues/1585#issuecomment-884192127

The core problem is org-roam has a default "dailies" folder that runs `org-parse-time-string` on every **filename** in that default directly and if any one doesn't parse as a time string, it errors out and breaks the calendar.

**Comment by mbafford** [comment]
@cheerio-pixel  @jethrokuan 

This looks to be resolved with https://github.com/org-roam/org-roam/commit/2fe233ffa0c590678807cbc344accbf8e8861de0 for #1585
