### ISSUE TITLE
Recursively cache all org files in org-roam directory

### ISSUE THREAD

**Issue by sati-bodhi** [org-roam/org-roam#1638]
### Brief Abstract

Function needed to recursively call `org-id-get-create` for all existing org files in the org directory without an `id` so that they can be cached by org-roam.

### Long Description

I am migrating from a regular org-mode notes directory into `org-roam`. It seem like only files and headings with an existing id are picked up by org-roam, but most of my org files have not been indexed this way. Is there an existing function that does this job? If not, is it possible to implement such function to help people migrating from regular org-mode notes?

### Proposed Implementation (if any)

Implement a function that creates an `ord-id` for all files in `org-roam` directory.

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
The migration wizard does that already, maybe your Org version does not support file level property drawers.

**Comment by sati-bodhi** [comment]
It does. New note files are working fine for me. I have not invoked the migration wizard on my folder, though. I thought it was meant for v1-v2 transition only.

**Comment by sati-bodhi** [comment]
My current org version is 9.5

**Comment by dancewhale** [comment]
I have the same problem, Throught some debug  I found that fuction org-id-add-location will  found .orgids under ~/org,
If there is no ~/org dir , org-id-get-create will fail which final cause  puthash  wrong-type-argument hash-table-p nil  Error.


create  dir ~/org

**Comment by dancewhale** [comment]
> My current org version is 9.5
> 
> I get the following error when invoking `org-roam-migrate-wizard`:
> `org-id-add-location: Wrong type argument: hash-table-p, nil`
> 
> ```
> Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
>   puthash("33eba35e-3002-492a-9c62-6b0245e51cfb" "~/Creation/notes/reading_notes/【書目】性自命出.org" nil)
>   org-id-add-location("33eba35e-3002-492a-9c62-6b0245e51cfb" "/home/sati/Creation/notes/reading_notes/【書目】性自命出.o...")
>   org-id-get(1 create)
>   org-id-get-create()
>   (save-restriction (widen) (goto-char (or --mpom (point))) (org-id-get-create))
>   (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (org-id-get-create)))
>   (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (org-id-get-create))))
>   (let ((--mpom 1)) (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (org-id-get-create)))))
>   org-roam-migrate-v1-to-v2()
>   (progn (org-roam-migrate-v1-to-v2))
>   (setq res (progn (org-roam-migrate-v1-to-v2)))
>   (save-current-buffer (set-buffer buf) (if (equal major-mode 'org-mode) nil (progn (make-local-variable 'delay-mode-hooks) (let ((delay-mode-hooks t)) (let ((org-inhibit-startup t) (org-agenda-files nil)) (org-mode))))) (setq res (progn (org-roam-migrate-v1-to-v2))) (if (and new-buf (not nil)) nil (save-buffer)))
>   (let* (new-buf (auto-mode-alist nil) (buf (or (and (not f) (current-buffer)) (find-buffer-visiting f) (progn (setq new-buf t) (find-file-noselect f)))) res) (save-current-buffer (set-buffer buf) (if (equal major-mode 'org-mode) nil (progn (make-local-variable 'delay-mode-hooks) (let ((delay-mode-hooks t)) (let ((org-inhibit-startup t) (org-agenda-files nil)) (org-mode))))) (setq res (progn (org-roam-migrate-v1-to-v2))) (if (and new-buf (not nil)) nil (save-buffer))) (if (and new-buf (not nil)) (if (find-buffer-visiting f) (progn (kill-buffer (find-buffer-visiting f))))) res)
>   (let ((f (car --dolist-tail--))) (let* (new-buf (auto-mode-alist nil) (buf (or (and (not f) (current-buffer)) (find-buffer-visiting f) (progn (setq new-buf t) (find-file-noselect f)))) res) (save-current-buffer (set-buffer buf) (if (equal major-mode 'org-mode) nil (progn (make-local-variable 'delay-mode-hooks) (let ((delay-mode-hooks t)) (let (... ...) (org-mode))))) (setq res (progn (org-roam-migrate-v1-to-v2))) (if (and new-buf (not nil)) nil (save-buffer))) (if (and new-buf (not nil)) (if (find-buffer-visiting f) (progn (kill-buffer (find-buffer-visiting f))))) res) (setq --dolist-tail-- (cdr --dolist-tail--)))
>   (while --dolist-tail-- (let ((f (car --dolist-tail--))) (let* (new-buf (auto-mode-alist nil) (buf (or (and (not f) (current-buffer)) (find-buffer-visiting f) (progn (setq new-buf t) (find-file-noselect f)))) res) (save-current-buffer (set-buffer buf) (if (equal major-mode 'org-mode) nil (progn (make-local-variable 'delay-mode-hooks) (let (...) (let ... ...)))) (setq res (progn (org-roam-migrate-v1-to-v2))) (if (and new-buf (not nil)) nil (save-buffer))) (if (and new-buf (not nil)) (if (find-buffer-visiting f) (progn (kill-buffer (find-buffer-visiting f))))) res) (setq --dolist-tail-- (cdr --dolist-tail--))))
>   (let ((--dolist-tail-- (org-roam--list-all-files))) (while --dolist-tail-- (let ((f (car --dolist-tail--))) (let* (new-buf (auto-mode-alist nil) (buf (or (and ... ...) (find-buffer-visiting f) (progn ... ...))) res) (save-current-buffer (set-buffer buf) (if (equal major-mode 'org-mode) nil (progn (make-local-variable ...) (let ... ...))) (setq res (progn (org-roam-migrate-v1-to-v2))) (if (and new-buf (not nil)) nil (save-buffer))) (if (and new-buf (not nil)) (if (find-buffer-visiting f) (progn (kill-buffer ...)))) res) (setq --dolist-tail-- (cdr --dolist-tail--)))))
>   (progn (let ((backup-dir (expand-file-name "org-roam.bak" (file-name-directory (directory-file-name org-roam-directory))))) (message "Backing up files to %s" backup-dir) (copy-directory org-roam-directory backup-dir)) (let ((--dolist-tail-- (org-roam--list-all-files))) (while --dolist-tail-- (let ((f (car --dolist-tail--))) (let* (new-buf (auto-mode-alist nil) (buf (or ... ... ...)) res) (save-current-buffer (set-buffer buf) (if (equal major-mode ...) nil (progn ... ...)) (setq res (progn ...)) (if (and new-buf ...) nil (save-buffer))) (if (and new-buf (not nil)) (if (find-buffer-visiting f) (progn ...))) res) (setq --dolist-tail-- (cdr --dolist-tail--))))) (org-roam-db-sync 'force) (let ((--dolist-tail-- (org-roam--list-all-files))) (while --dolist-tail-- (let ((f (car --dolist-tail--))) (let* (new-buf (auto-mode-alist nil) (buf (or ... ... ...)) res) (save-current-buffer (set-buffer buf) (if (equal major-mode ...) nil (progn ... ...)) (setq res (progn ... ...)) (if (and new-buf ...) nil (save-buffer))) (if (and new-buf (not nil)) (if (find-buffer-visiting f) (progn ...))) res) (setq --dolist-tail-- (cdr --dolist-tail--))))))
>   (if (yes-or-no-p "Org-roam will now convert all your notes from v1 t...") (progn (let ((backup-dir (expand-file-name "org-roam.bak" (file-name-directory (directory-file-name org-roam-directory))))) (message "Backing up files to %s" backup-dir) (copy-directory org-roam-directory backup-dir)) (let ((--dolist-tail-- (org-roam--list-all-files))) (while --dolist-tail-- (let ((f (car --dolist-tail--))) (let* (new-buf (auto-mode-alist nil) (buf ...) res) (save-current-buffer (set-buffer buf) (if ... nil ...) (setq res ...) (if ... nil ...)) (if (and new-buf ...) (if ... ...)) res) (setq --dolist-tail-- (cdr --dolist-tail--))))) (org-roam-db-sync 'force) (let ((--dolist-tail-- (org-roam--list-all-files))) (while --dolist-tail-- (let ((f (car --dolist-tail--))) (let* (new-buf (auto-mode-alist nil) (buf ...) res) (save-current-buffer (set-buffer buf) (if ... nil ...) (setq res ...) (if ... nil ...)) (if (and new-buf ...) (if ... ...)) res) (setq --dolist-tail-- (cdr --dolist-tail--)))))))
>   org-roam-migrate-wizard()
>   funcall-interactively(org-roam-migrate-wizard)
>   call-interactively(org-roam-migrate-wizard record nil)
>   command-execute(org-roam-migrate-wizard record)
>   counsel-M-x-action("org-roam-migrate-wizard")
>   ivy-call()
>   ivy-read("M-x " ("org-roam-migrate-wizard" "toggle-debug-on-error" "view-echo-area-messages" "org-id-get-create" "org-version" "describe-char" "yankpad-insert" "visual-line-mode" "org-roam-setup" "revert-buffer" "org-noter" "writeroom-mode" "org-footnote-action" "org-roam-db-sync" "org-noter-sync-current-note" "comment-region" "org-roam-capture" "pdf-tools-install" "org-roam-node-find" "so-long-minor-mode" "org-mode" "evil-mode" "doom/reload" "yankpad-edit" "describe-face" "outshine-mode" "pdf-tools-help" "read-only-mode" "org-roam-buffer" "lisp-indent-line" "org-bullets-mode" "toggle-read-only" "slime-eval-buffer" "so-long-commentary" "org-roam-file-visit" "org-roam-diagnostics" "org-roam-db-clear-all" "toggle-truncate-lines" "org-noter-sync-prev-note" "pdf-tools-enable-minor-modes" "org-noter-insert-precise-note" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" ...) :predicate (closure ((externs "org-roam-migrate-wizard" "toggle-debug-on-error" "view-echo-area-messages" "org-id-get-create" "org-version" "describe-char" "yankpad-insert" "visual-line-mode" "org-roam-setup" "revert-buffer" "org-noter" "writeroom-mode" "org-footnote-action" "org-roam-db-sync" "org-noter-sync-current-note" "comment-region" "org-roam-capture" "pdf-tools-install" "org-roam-node-find" "so-long-minor-mode" "org-mode" "evil-mode" "doom/reload" "yankpad-edit" "describe-face" "outshine-mode" "pdf-tools-help" "read-only-mode" "org-roam-buffer" "lisp-indent-line" "org-bullets-mode" "toggle-read-only" "slime-eval-buffer" "so-long-commentary" "org-roam-file-visit" "org-roam-diagnostics" "org-roam-db-clear-all" "toggle-truncate-lines" "org-noter-sync-prev-note" "pdf-tools-enable-minor-modes" "org-noter-insert-precise-note" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" ...) (initial-input) smex-ido-cache smex-initialized-p amx-cache amx-initialized info-lookup-mode find-tag-marker-ring company-prefix company-common company-candidates t) (x) (not (get (intern x) 'no-counsel-M-x))) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
>   (let ((externs (counsel--M-x-externs))) (ivy-read (counsel--M-x-prompt) (or externs obarray) :predicate (if externs #'(lambda (x) (not (get (intern x) 'no-counsel-M-x))) #'(lambda (sym) (and (commandp sym) (not (get sym ...)) (not (get sym ...))))) :require-match t :history 'counsel-M-x-history :action #'counsel-M-x-action :keymap counsel-describe-map :initial-input initial-input :caller 'counsel-M-x))
>   counsel-M-x()
>   funcall-interactively(counsel-M-x)
>   call-interactively(counsel-M-x nil nil)
>   command-execute(counsel-M-x)
> ```
> 
> Even though file level property drawers are inserted correctly when applying `org-id-get-create` on a single file, the above error also pops up.
> 
> ```
> Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
>   puthash("f8826838-a82b-4eda-8e66-f4b4a51bb1c0" "~/Creation/notes/reading_notes/VirágEarly2014.org" nil)
>   org-id-add-location("f8826838-a82b-4eda-8e66-f4b4a51bb1c0" "/home/sati/Creation/notes/reading_notes/VirágEarl...")
>   org-id-get(101 create)
>   org-id-get-create(nil)
>   funcall-interactively(org-id-get-create nil)
>   call-interactively(org-id-get-create record nil)
>   command-execute(org-id-get-create record)
>   counsel-M-x-action("org-id-get-create")
>   ivy-call()
>   ivy-read("M-x " ("org-roam-migrate-wizard" "toggle-debug-on-error" "view-echo-area-messages" "org-id-get-create" "org-version" "describe-char" "yankpad-insert" "visual-line-mode" "org-roam-setup" "revert-buffer" "org-noter" "writeroom-mode" "org-footnote-action" "org-roam-db-sync" "org-noter-sync-current-note" "comment-region" "org-roam-capture" "pdf-tools-install" "org-roam-node-find" "so-long-minor-mode" "org-mode" "evil-mode" "doom/reload" "yankpad-edit" "describe-face" "outshine-mode" "pdf-tools-help" "read-only-mode" "org-roam-buffer" "lisp-indent-line" "org-bullets-mode" "toggle-read-only" "slime-eval-buffer" "so-long-commentary" "org-roam-file-visit" "org-roam-diagnostics" "org-roam-db-clear-all" "toggle-truncate-lines" "org-noter-sync-prev-note" "pdf-tools-enable-minor-modes" "org-noter-insert-precise-note" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" ...) :predicate (closure ((externs "org-roam-migrate-wizard" "toggle-debug-on-error" "view-echo-area-messages" "org-id-get-create" "org-version" "describe-char" "yankpad-insert" "visual-line-mode" "org-roam-setup" "revert-buffer" "org-noter" "writeroom-mode" "org-footnote-action" "org-roam-db-sync" "org-noter-sync-current-note" "comment-region" "org-roam-capture" "pdf-tools-install" "org-roam-node-find" "so-long-minor-mode" "org-mode" "evil-mode" "doom/reload" "yankpad-edit" "describe-face" "outshine-mode" "pdf-tools-help" "read-only-mode" "org-roam-buffer" "lisp-indent-line" "org-bullets-mode" "toggle-read-only" "slime-eval-buffer" "so-long-commentary" "org-roam-file-visit" "org-roam-diagnostics" "org-roam-db-clear-all" "toggle-truncate-lines" "org-noter-sync-prev-note" "pdf-tools-enable-minor-modes" "org-noter-insert-precise-note" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" ...) (initial-input) smex-ido-cache smex-initialized-p amx-cache amx-initialized info-lookup-mode find-tag-marker-ring company-prefix company-common company-candidates t) (x) (not (get (intern x) 'no-counsel-M-x))) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
>   (let ((externs (counsel--M-x-externs))) (ivy-read (counsel--M-x-prompt) (or externs obarray) :predicate (if externs #'(lambda (x) (not (get (intern x) 'no-counsel-M-x))) #'(lambda (sym) (and (commandp sym) (not (get sym ...)) (not (get sym ...))))) :require-match t :history 'counsel-M-x-history :action #'counsel-M-x-action :keymap counsel-describe-map :initial-input initial-input :caller 'counsel-M-x))
>   counsel-M-x()
>   funcall-interactively(counsel-M-x)
>   call-interactively(counsel-M-x nil nil)
>   command-execute(counsel-M-x)
> ```


I have the same problem,

 Throught some debug I found that fuction org-id-add-location will found .orgids under ~/org,
If there is no ~/org dir , org-id-get-create will fail which final cause puthash wrong-type-argument hash-table-p nil Error.

create dir ~/org

**Comment by sati-bodhi** [comment]
@dancewhale: Yes, it works when you set the org-roam directory to `~/org/roam`, which is the default. 

@jethrokuan: See if it is necessary to fix this as a bug, alternatively, maybe we could just add a side-note to the documentation as a reminder to users who are unaware of this.
