### ISSUE TITLE
V2 no longer sorts node suggestions by most recent

### ISSUE THREAD

**Issue by draxil** [org-roam/org-roam#1639]
### Description

In v1 when I used the old command to find a node the suggestions sorted in such a way that the more recently visited nodes would sort to the top. Now in v2 the suggestions appear in the same order always. 

I use helm as my completion framework.

I hope this isn't some vagary of my local setup! 

#### Steps to Reproduce

1. org-roam-node-find
2. Pick a node
3. org-roam-node-find
4. No helpful sorting occurs.

**Comment by jethrokuan** [comment]
It's sorted by file mtime by default, the file migration wizard probably updated every file so that's why you think the sort order is not helpful.

**Comment by draxil** [comment]
@jethrokuan Thanks. It wasn't updating earlier which was the visible problem, to start with I found that if I forced a db update it was okay... But now it's fine. 

So I'll sheepishly close this :)
