### ISSUE TITLE
Helm Completion Buffer Displays "Extra" Tags Wrapping to Second Line

### ISSUE THREAD

**Issue by mchowning** [org-roam/org-roam#1640]
### Description

When searching for nodes, Helm is displaying [the `'invisible` tags](https://github.com/org-roam/org-roam/blob/master/org-roam.el#L710), causing the completion candidate to wrap to a new line. To be clear, I do not have this issue when using Ivy. For example, if I have

```
(setq org-roam-node-display-template "${title:*} ${tags:20}")
```

Then I end up getting duplicate tags (once for the `${tags:20}` and once from [the `'invisible` tags](https://github.com/org-roam/org-roam/blob/master/org-roam.el#L710).

![image](https://user-images.githubusercontent.com/4656348/126328918-15318dbd-af1d-446d-a121-848263f2b85a.png)

Although this issue has some similarities to [Helm completion too wide for side-by-side windows #1578](https://github.com/org-roam/org-roam/issues/1578), I think it is a different issue.

#### Occurs on Emacs 27.2, but not 27.1

This may be a helm or emacs issue. I did not observe this behavior on emacs 27.1, but I did observe it on 27.2. I actually had two computers sharing the same dotfile, and I had this problem on the one running 27.2, but not the one running 27.1. Then when I upgraded the computer running 27.1 to use 27.2, it immediately started showing this problem as well.

#### Steps to Reproduce

1. Load Emacs version 27.2
2. Run `org-roam-node-find` using Helm as your completion (I haven't tested other completion frameworks)
3. Observe that the tags for a node are listed once more than expected (based on the value of `org-roam-node-display-template`) and wrap to a second line (unless the tag is extremely short)

#### Expected Results

The completion candidates should only display tags if they are specified in `org-roam-node-display-template` and should not wrap the completion candidate to a second line.

#### Actual Results

The completion candidates should displays tags once more than indicated in `org-roam-node-display-template` and wrap the completion candidate to a second line so the "additional" tags are on the second line..

### Environment

I have this issue both on Linux/Ubuntu and Mac

#### Mac
- Emacs: GNU Emacs 27.2 (build 1, aarch64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
 of 2021-07-14
- Framework: Spacemacs
- Org: Org mode version 9.4.6 (9.4.6-11-g1ee52c-elpa @ /Users/matt/.emacs.d/elpa/27.2/develop/org-plus-contrib-20210712/)
- Org-roam: 2.0.0

#### Linux
- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2021-06-04
- Framework: Spacemacs
- Org: Org mode version 9.4.5 (9.4.5-16-g94be20-elpaplus @ /home/matt/.emacs.d/elpa/27.2/develop/org-plus-contrib-20210412/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/7d5b7e6

### Additional Info

It appears that it is not only the `'invisible` string property that gets ignored for me. I also cannot seem to get "dimmed" text to appear in the completion buffer using something like `(propertize filetitle 'face 'org-roam-dim)`  as seen [here](https://orgroam.slack.com/archives/CV20S23C0/p1626620862030700). I certainly wouldn't rule out the possibility that I'm setting the string properties incorrectly, but it also wouldn't surprise me if the `'invisible` property wasn't the only one getting "ignored". Again, I only have this issue when using Helm--Ivy seems to work fine.

**Comment by mchowning** [comment]
Opened https://github.com/org-roam/org-roam/pull/1641 with a potential fix for the immediate problem, but I am not sure this is the best way to address this issue.

**Comment by PRESFIL** [comment]
:hand: I noticed this too. :eyes:

It seems like helm is no longer helm, but an ordinary minibuffer. :disappointed:

**Comment by jethrokuan** [comment]
I think Helm should be the one addressing this? I think it's a bug that Helm doesn't respect text properties.

**Comment by mchowning** [comment]
> I think Helm should be the one addressing this? I think it's a bug that Helm doesn't respect text properties.

I did a fair bit of searching and wasn't able to isolate the issue in helm or find a pre-existing report of a similar helm issue, so I wasn't certain if the problem was helm or org-roam. It does seem most likely that the issue is with helm though, so I'll go ahead and close this and we can re-open it if we later learn that the issue is not with helm.

I do wonder if my "fix" (#1641 ) might still be worth merging since it does avoid this issue (even if it is helm's issue) and with v2 anyone who wants to search by tags can always include the tag in their `org-roam-node-display-template`, which seems more transparent than adding the tag as invisible text inside org-roam.

**Comment by PRESFIL** [comment]
It seems to me tags-to-result tags-to- strings is used twice when forming pvariants for minibuffer in this place: https://github.com/org-roam/org-roam/pull/1641/commits/d83aec51616beee4bce460ea1916dae587a59d8a

**Comment by PRESFIL** [comment]
Please, reopen issue.

**Comment by PRESFIL** [comment]
I was also able to reproduce it:

![2021-07-28_15-48](https://user-images.githubusercontent.com/20644917/127330105-73109193-2e73-47bb-befb-5e1af7500d7b.png)

By setting:

```lisp
(org-roam-node-display-template "${title:*} ${tags:*}")
```

This is reproducible in both Helm and minibuffer. So it's not about invisible.

> It seems like helm is no longer helm, but an ordinary minibuffer. :disappointed:

Yes, it really is Helm. I just had no idea how to turn it on. But now I can...

**Comment by mchowning** [comment]
Just noting that the stop-gap fix for the immediate issue of completion spanning multiple lines (#1641) has been merged. That does not address the underlying problem of helm failing to respect formatting options though.

**Comment by matthuszagh** [comment]
Has anybody been able to isolate why helm is ignoring text properties? Or, identified an issue tracking this bug in helm?

**Comment by benthamite** [comment]
Thank you for taking the time to open a bug report. Unfortunately, for me Thierry's suggestion does not work when the frame is split vertically, as can be seen in the screenshots below. Does anyone have thoughts on whether the above code could be revised to handle this case?

<img width="1916" alt="Screenshot 2021-12-02 at 20 38 02" src="https://user-images.githubusercontent.com/5490677/144520138-39e3c542-b665-4a13-a403-a884316e3516.png">
<img width="1920" alt="Screenshot 2021-12-02 at 20 38 31" src="https://user-images.githubusercontent.com/5490677/144520147-30dfbd53-25fd-46e5-867a-4a95cb529216.png">

**Comment by matthuszagh** [comment]
@benthamite it works fine for me. How have you set `org-roam-node-display-template` and `helm-completing-read-handlers-alist`?

**Comment by benthamite** [comment]
Hi. For `org-roam-node-display-template`:

``` emacs-lisp
#("${title:*} ${tags:10}" 11 21
  (face org-tag))
```

For `helm-completing-read-handlers-alist`:

``` emacs-lisp
((org-roam-node-find . helm-completing-read-sync-default-handler)
 (find-tag . helm-completing-read-default-find-tag)
 (xref-find-definitions . helm-completing-read-default-find-tag)
 (xref-find-references . helm-completing-read-default-find-tag)
 (ggtags-find-tag-dwim . helm-completing-read-default-find-tag)
 (tmm-menubar)
 (find-file)
 (execute-extended-command)
 (dired-do-rename . helm-read-file-name-handler-1)
 (dired-do-copy . helm-read-file-name-handler-1)
 (dired-do-symlink . helm-read-file-name-handler-1)
 (dired-do-relsymlink . helm-read-file-name-handler-1)
 (dired-do-hardlink . helm-read-file-name-handler-1)
 (basic-save-buffer . helm-read-file-name-handler-1)
 (write-file . helm-read-file-name-handler-1)
 (write-region . helm-read-file-name-handler-1))
```

**Comment by matthuszagh** [comment]
Hm, yeah I see the same. I started debugging it a bit, but unfortunately I don't really have the time to keep debugging at the moment. If you're up for it, I'd use edebug on the relevant functions. I'd be a bit surprised if this was helm's fault because it's respecting all the text properties I'm giving it.

**Comment by benthamite** [comment]
Thanks! I'll try `edebug` and will report back if I manage to figure out what's going on.
