### ISSUE TITLE
The migration script handles filetags in an unexpected manner

### ISSUE THREAD

**Issue by ndw** [org-roam/org-roam#1642]
### Description

Advice for tags, for example [from the org manual](https://orgmode.org/guide/Tags.html) shows them as being delimited by colons. I'm not sure what Org Roam V2 uses, but migration appears to have turned all the colons into underscores.

#### Steps to Reproduce

I had a bunch of V1 files that used tags with colons:

```
#+FILETAGS :Saxonica:DeclarativeAmsterdam:
```

they have become single tags with underscores in them:

```
#+filetags: _Saxonica_DeclarativeAmsterdam_
```

That's obviously not right at all. It's not a huge problem to fix them, but I thought I should report it.

#### Expected Results

I expected the tags to be preserved, should they still be using colons as delimiters?

**Comment by jethrokuan** [comment]
Thanks for the report @ndw , I had a misunderstanding of how filetags worked before.
