### ISSUE TITLE
command-execute: Wrong type argument: commandp, org-roam-find-file

### ISSUE THREAD

**Issue by jason--liu** [org-roam/org-roam#1650]
### Description
Hi,  I want to try org-roam in spacemacs, and I have  updated to latest commit(develop branch).
#### Steps to Reproduce
`spc a o r f` to invoke `org-roam-find-file`，the error bellow
```
command-execute: Wrong type argument: commandp, org-roam-find-file
```
And this is my init config in `dotspacemacs/layers`
```
     (org :variables
          org-enable-org-journal-support t
          org-journal-dir "~/Dropbox/org/journal/"
          org-journal-file-type 'monthly
          org-journal-file-format "%Y-%m"
          org-default-notes-file "~/Dropbox/org/captures.org"
          org-superstar-leading-bullet "  "
          ;;org-roam
          org-enable-roam-support t
          org-enable-roam-server t
          org-enable-roam-protocol t
          org-roam-directory "~/Dropbox/org/roam"
          org-roam-v2-ack t
          )
```

I have also tried to open a org file first and delete elpa/develop/org-roam-* ， and restart emacs , but none of them works.

#### Backtrace

```
Debugger entered--Lisp error: (wrong-type-argument commandp org-roam-find-file)
  call-interactively(org-roam-find-file nil nil)
  command-execute(org-roam-find-file)
```

### Environment

```
- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)
 of 2020-03-26, modified by Debian
- Framework: Spacemacs
- Org: Org mode version 9.4.6 (9.4.6-gab9f2a @ /home/qianyi/.emacs.d/elpa/develop/org-9.4.6/)
- Org-roam: 2.0.0
```

Hope there is a way to solve this problem, Thank you.

**Comment by jethrokuan** [comment]
That command is now `org-roam-node-find`, do read the manual to see what commands are now available.

**Comment by nobiot** [comment]
@jason--liu you might like to look at this https://org-roam.discourse.group/t/spacemacs-org-roam-wrong-type-argument-commandp-org-roam-find-file/1795/2.

**Comment by jason--liu** [comment]
Thanks,I will close this issue
