### ISSUE TITLE
Backlinks buffer not updating

### ISSUE THREAD

**Issue by agzam** [org-roam/org-roam#1656]
### Description

Looks like the recent commit: 9c10a3c04c06d1658a63d44927e385e2d97854d6 broke the org-roam buffer.
It no longer updates for me when moving from one node to another.  

### Environment

- Emacs: GNU Emacs 28.0.50 (build 2, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
 of 2021-06-23
- Framework: Spacemacs
- Org: Org mode version 9.4.6 (9.4.6-11-g1ee52c-elpa @ /Users/aibragim/.emacs-profiles/.emacs-spacemacs.d/elpa/28.0/develop/org-20210719/)
- Org-roam: 2.0.0

**Comment by emacs18** [comment]
Backlink buffer does update for me on ubutu 20.04 using emacs 27 or 28 and spacemacs.
My problem is that clicking on links in the backlink buffer does not bring up appropriate buffers.  Instead I always get this error when I click (or hit RETURN key) on any links in the backlink buffer.
```
org-roam-visit-thing: There is no thing at point that could be visited
```

**Comment by agzam** [comment]
@emacs18 That's unrelated to this issue, check: https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2#navigation-in-backlink-buffer

**Comment by bulbousBullfrog** [comment]
### Environment
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.16.0)
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-11-g1ee52c-elpa @ /nix/store/km32iimn85pwmzpg9api5bxv9xsxp477-emacs-packages-deps/share/emacs/site-lisp/elpa/org-20210726/)
- Org-roam: 2.0.0

My backlinks buffer still isn't updating while switching between notes. Was there any commit or reason to close this issue?

**Comment by emacs18** [comment]
I don't think there was any commit, since this is likely to be a user error, e.g., forgetting to add `(org-roam-setup)` in the setup code.

**Comment by bulbousBullfrog** [comment]
Yes in case anybody was wondering like I was, this was a case of simply forgetting to add `(org-roam-setup) `to package setup as described in the documentation. Thank you emacs18

**Comment by ayrat555** [comment]
> My problem is that clicking on links in the backlink buffer does not bring up appropriate buffers. Instead I always get this error when I click (or hit RETURN key) on any links in the backlink buffer.
> 
> ```
> org-roam-visit-thing: There is no thing at point that could be visited
> ```

@emacs18  were you able to resolve it?  I'm experiencing the same issue. Even though I set `(org-roam-setup)` in my config - https://github.com/ayrat555/dot-emacs/blob/master/lisp/init-org-mode.el#L84

**Comment by emacs18** [comment]
No, the problem has not been diagnosed.  I just submitted https://github.com/org-roam/org-roam/issues/1732 for this issue.
