### ISSUE TITLE
Org-roam-refile

### ISSUE THREAD

**Issue by agzam** [org-roam/org-roam#1658]
### Brief Abstract

Org-refile is a great tool, but it looks like Org-Roam needs its own alternative.

### Long Description

Sometimes I stack some notes nested in headings. e.g., "Cytology" doesn't need to be in a separate file; it can be a subheading of "Biology", which is stored in "Science.org" file.

But when "Cytology" grows enough to deserve its own separate file, currently, that has to be done manually.

It would be nice to have a built-in function that would allow you to perform such conversion. And of course, it would be nice if the opposite way was possible - converting a file note to a subheading.

### Proposed Implementation 

I spent some time and wrote something very basic: https://gist.github.com/agzam/607acb518f584e0ae6b902697dc53b45

**Comment by Wetlize** [comment]
There's `org-roam-refile` command if you haven't seen it.

**Comment by agzam** [comment]
Damn, I'm such a specimen :) How could I miss that? That function however, doesn't seem to be able to create a note file out of a heading, does it?
