### ISSUE TITLE
org-roam-graph appears to be broken

### ISSUE THREAD

**Issue by agzam** [org-roam/org-roam#1659]
### Description

org-roam-graph command (since switching to v2) stopped working for me.

It silently fails with the message:

```
Error: /var/folders/z_/tkhzzcq179jg1t28z2n73p880000gn/T/graph.pvRzVy.dot: syntax error in line 450 near 'New'
```
in `*org-roam-graph--build-process*` buffer

Maybe I'm missing some third-party utility, or something else? I'm on a Mac (Intel based).

### Environment

- Emacs: GNU Emacs 28.0.50 (build 2, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
 of 2021-06-23
- Framework: Spacemacs
- Org: Org mode version 9.4.6 (9.4.6-11-g1ee52c-elpa @ /Users/aibragim/.emacs-profiles/.emacs-spacemacs.d/elpa/28.0/develop/org-20210719/)
- Org-roam: 2.0.0

**Comment by naistran** [comment]
I had something similar, it was caused by a `shell:` link. Try hiding more link types from the graph?

```lisp
(setq org-roam-graph-link-hidden-types '("file" "attachment" "bbdb" "docview" "doi" "elisp"
                                         "ftp" "gnus" "help" "http" "https" "info" "irc"
                                         "mailto" "mhe" "news" "tel" "rmail" "shell"))
```

**Comment by jethrokuan** [comment]
Would help to have the `.dot` a sample of the dot file, so I know exactly where to fix things.

**Comment by agzam** [comment]
[graph.XuYZ4Z.dot.zip](https://github.com/org-roam/org-roam/files/6864433/graph.XuYZ4Z.dot.zip)

**Comment by agzam** [comment]
Looks like it's due to a malformed link in one of the headings.
