### ISSUE TITLE
save-restriction: Symbol’s function definition is void: org-back-to-heading-or-point-min

### ISSUE THREAD

**Issue by nrvale0** [org-roam/org-roam#1661]
### Description

org-roam calls non-existant org.el function: org-back-to-heading-or-point-min

#### Steps to Reproduce

M-x emacs-version
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-09-19

M-x org-version
Org mode version 9.3 (release_9.3 @ /usr/share/emacs/27.1/lisp/org/)

M-x org-roam-version
2.0.0

M-x org-roam-migrate-wizard

#### Backtrace

Debugger entered--Lisp error: (error "Before first headline at position 1 in buffer 2021...")
  signal(error ("Before first headline at position 1 in buffer 2021..."))
  error("Before first headline at position %d in buffer %s" 1 #<buffer 20210618123611-<redacted>.org>)
  org-back-to-heading(t)
  org-entry-put(1 "ID" "e7a1ecad-970b-421f-a89d-09a6876ee9a9")
  org-id-get(1 create)
  org-id-get-create()
  org-roam-migrate-v1-to-v2()
  org-roam-migrate-wizard()
...

### Environment

23605546d881e9ea54e88c43976ba7e66c30d6ea

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2020-09-19
- Framework: N/A
- Org: Org mode version 9.3 (release_9.3 @ /usr/share/emacs/27.1/lisp/org/)
- Org-roam: 2.0.0

**Comment by nobiot** [comment]
You might need to upgrade your Org to 9.4.
That’s part of prerequisites.

https://github.com/org-roam/org-roam/blob/9c10a3c04c06d1658a63d44927e385e2d97854d6/org-roam.el#L9

**Comment by nrvale0** [comment]
Ah, I didn't see it listed as such. But indeed, upgrading to 9.4.x (sort of not easy with straight.el) resolved the issue.

Perhaps a warning as to Org version similar to the warning about needing to setq confirm the usage of v2?
