### ISSUE TITLE
v2: migration didnt finish properly from v1 to v2

### ISSUE THREAD

**Issue by jave** [org-roam/org-roam#1662]
### Description
A number of files were not converted from v1 to v2 during migration wizard.

#### Steps to Reproduce
run the migration wizard, it chugs along nicely, but in the end it errors out with:
(org-roam) Upgrading the Org-roam database from version 10 to version 16
Clearing removed files...done
Processing modified files...59% 
Saving file /home/joakim/Plans/org-roam/defining_custom_handlers_for_use_with_org_protocol.org...
Wrote /home/joakim/Plans/org-roam/defining_custom_handlers_for_use_with_org_protocol.org
Processing modified files...done
apply: Selecting deleted buffer

### Environment

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jave** [comment]
12:24:33-joakim@tanaka:~/Plans/org-roam$ grep -m1 -v ':ID:' *|wc -l
113
12:24:36-joakim@tanaka:~/Plans/org-roam$ grep -m1  ':ID:' *|wc -l
45


So, 45 files were converted, 113 were not

**Comment by jave** [comment]
I just re-ran the wizard again, and now all files seems converted. odd.

**Comment by howdoicomputer** [comment]
I'm going to piggy back on this issue and say that org-roam is now broken for me. I run the migration function and it creates an `~/org/org-roam.bak` directory that is empty and then quits.

I do have my roam directory set to its own directory with `(setq org-roam-directory "~/org-roam")`. Org-roam is breaking my config so I have to disable it for now.

**Comment by jethrokuan** [comment]
This is likely result of an emacsql timeout, you can ignore this I guess. There's an ongoing PR for catching the error that should catch the error.
