### ISSUE TITLE
Unknown specializer org-roam-node

### ISSUE THREAD

**Issue by zamlz** [org-roam/org-roam#1669]
### Description

The commands to get the backlinks count appear as per the [hitchikers guide ](https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2#showing-the-number-of-backlinks-for-each-node-in-org-roam-node-find)work when run in my emacs section.
The problem arises when I keep them in my config and restart emacs. This commands produce the following error.

#### Steps to Reproduce

1. Copy code to config and run interactively (it works as expected)
2. Restart Emacs
3. See backtrace

#### Backtrace
```
Debugger entered--Lisp error: (error "Unknown specializer org-roam-node")
  signal(error ("Unknown specializer org-roam-node"))
  error("Unknown specializer %S" org-roam-node)
  #f(compiled-function (specializer) "Support for the catch-all t specializer which always matches." #<bytecode 0x1ffb7ce9c1d9>)(org-roam-node)
  apply(#f(compiled-function (specializer) "Support for the catch-all t specializer which always matches." #<bytecode 0x1ffb7ce9c1d9>) org-roam-node)
  #f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d1f1>)()
  #f(compiled-function (cl--cnm specializer) "Support for (head VAL) specializers.\nThese match if the argument is a cons cell whose car is `eql' to VAL." #<bytecode 0x1ffb7ce9c217>)(#f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d1f1>) org-roam-node)
  apply(#f(compiled-function (cl--cnm specializer) "Support for (head VAL) specializers.\nThese match if the argument is a cons cell whose car is `eql' to VAL." #<bytecode 0x1ffb7ce9c217>) #f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d1f1>) org-roam-node)
  #f(compiled-function (&rest args) #<bytecode 0x157b07bc7401>)(org-roam-node)
  apply(#f(compiled-function (&rest args) #<bytecode 0x157b07bc7401>) org-roam-node)
  #f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d1d5>)()
  #f(compiled-function (cl--cnm type) "Support for dispatch on types defined by `cl-defstruct'." #<bytecode 0x1ffb7cea16b1>)(#f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d1d5>) org-roam-node)
  apply(#f(compiled-function (cl--cnm type) "Support for dispatch on types defined by `cl-defstruct'." #<bytecode 0x1ffb7cea16b1>) #f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d1d5>) org-roam-node)
  #f(compiled-function (&rest args) #<bytecode 0x157b07bc742d>)(org-roam-node)
  apply(#f(compiled-function (&rest args) #<bytecode 0x157b07bc742d>) org-roam-node)
  #f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d1b9>)()
  #f(compiled-function (cl--cnm type) "Support for dispatch on builtin types.\nSee the full list and their hierarchy in `cl--typeof-types'." #<bytecode 0x1ffb7cea1a01>)(#f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d1b9>) org-roam-node)
  apply(#f(compiled-function (cl--cnm type) "Support for dispatch on builtin types.\nSee the full list and their hierarchy in `cl--typeof-types'." #<bytecode 0x1ffb7cea1a01>) #f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d1b9>) org-roam-node)
  #f(compiled-function (&rest args) #<bytecode 0x157b07bc7459>)(org-roam-node)
  apply(#f(compiled-function (&rest args) #<bytecode 0x157b07bc7459>) org-roam-node)
  #f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d19d>)()
  #f(compiled-function (cl--cnm specializer) "Support for dispatch on types defined by EIEIO's `defclass'." #<bytecode 0x157b07bbc64d>)(#f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d19d>) org-roam-node)
  apply(#f(compiled-function (cl--cnm specializer) "Support for dispatch on types defined by EIEIO's `defclass'." #<bytecode 0x157b07bbc64d>) #f(compiled-function (&rest cnm-args) #<bytecode 0x157b09f5d19d>) org-roam-node)
  #f(compiled-function (&rest args) #<bytecode 0x157b07bc7485>)(org-roam-node)
  apply(#f(compiled-function (&rest args) #<bytecode 0x157b07bc7485>) org-roam-node nil)
  cl-generic-generalizers(org-roam-node)
  cl-generic-define-method(org-roam-node-directories nil ((node org-roam-node)) nil (lambda (node) (progn (let* ((dirs (and t (file-name-directory ...)))) (if dirs (format "(%s)" (car (f-split dirs))) "")))))
  eval-buffer(#<buffer  *load*-418128> nil "/home/zamlz/.config/emacs/lisp/init-org-roam.el" nil t)  ; Reading at buffer position 1715
  load-with-code-conversion("/home/zamlz/.config/emacs/lisp/init-org-roam.el" "/home/zamlz/.config/emacs/lisp/init-org-roam.el" nil t)
  require(init-org-roam)
  eval-buffer(#<buffer  *load*-518854> nil "/home/zamlz/.config/emacs/lisp/init-org-roam-proto..." nil t)  ; Reading at buffer position 400
  load-with-code-conversion("/home/zamlz/.config/emacs/lisp/init-org-roam-proto..." "/home/zamlz/.config/emacs/lisp/init-org-roam-proto..." nil t)
  require(init-org-roam-protocol)
  (while --dolist-tail-- (setq dir (car --dolist-tail--)) (require (intern (replace-regexp-in-string "\\.el" "" dir))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- (directory-files (expand-file-name "lisp" user-emacs-directory) nil ".*\\.el")) dir) (while --dolist-tail-- (setq dir (car --dolist-tail--)) (require (intern (replace-regexp-in-string "\\.el" "" dir))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  eval-buffer(#<buffer  *load*> nil "/home/zamlz/.config/emacs/init.el" nil t)  ; Reading at buffer position 12097
  load-with-code-conversion("/home/zamlz/.config/emacs/init.el" "/home/zamlz/.config/emacs/init.el" t t)
  load("/home/zamlz/.config/emacs/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x157b07b18299>) #f(compiled-function () #<bytecode 0x157b07b18191>) t)
  command-line()
  normal-top-level()

```

#### Expected Results

Startup does not error out

#### Actual Results

Startup errors out

### Environment

```
- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-g604bfd @ /home/zamlz/.config/emacs/straight/build/org/)
- Org-roam: 2.0.0
```

**Comment by jethrokuan** [comment]
That snippet of code needs to run after `org-roam` is `require`d, order is important here.

**Comment by zamlz** [comment]
Well I can say this much, the `require` (or the `use-package` equivalent) is happening before that. I can guarantee as much.

```lisp
(use-package org-roam
  :hook (after-init . org-roam-mode)
  :bind (:map org-mode-map
         ("M-i" . org-roam-node-insert)))
```

However, from this snippet, could it be that perhaps the way of setting up `org-roam-mode` is not correct? Perhaps it doesn't need to wait until after the init like its doing here.

**Comment by jethrokuan** [comment]
The hook is incorrect in v2, please refer to the README for updated setup instructions:

```
(use-package org-roam
  :bind (:map org-mode-map
         ("M-i" . org-roam-node-insert))
  :config
  (org-roam-setup))
```

**Comment by nobiot** [comment]
It appears from the error stack that you run init-org-roam.el (and various other init-*.el files) in init.el. 

Alternative to Jethro’s instruction, I believe you could explicitly require Org-roam in init-org-roam.el at around the top. 

You defer this to after init is done via after-init, so your sequence currently should be:
1. init-org-roam.el 
2. require org-roam (use-package equivalent)

And as Jethro instructs, you need to call org-roam-setup.

**Comment by zamlz** [comment]
> The hook is incorrect in v2, please refer to the README for updated setup instructions:
> 
> ```
> (use-package org-roam
>   :bind (:map org-mode-map
>          ("M-i" . org-roam-node-insert))
>   :config
>   (org-roam-setup))
> ```

Okay so I've made these changes, but unfortunately I still get the same error. Let me share my configuration files themselves and perhaps the issue may become clear. @nobiot the `use-package` statement is at the top of the file basically.

[Org Roam Config File](https://github.com/zamlz/dotfiles/blob/master/org_roam.org)

**Comment by jethrokuan** [comment]
Because you have a `:bind` construct the `org-roam` package load is deferred, so the package is not `require`d until you call a command. You have placed related configuration outside the `use-package` construct, so you are calling `cl-defmethod` before `org-roam` is being `require`d, hence the issue you see.

Moving the org-roam configuration into the use-package `:config` construct will fix that.

**Comment by nobiot** [comment]
Do you have a stale .elc somewhere that has the previous code?
I don't use `use-package` so I converted first part of your file into the following into my init and restarted emacs.

Since `org-roam-v2-ack` appears after require org-roam, I get the org-roam's warning messaging asking met to set the `org-roam-v2-ack, as I expected.

Since you report that "unfortunately I still get the same error." I think Emacs does not use your new config file to initialize.

![image](https://user-images.githubusercontent.com/12507865/126906572-40a15de3-fa6b-43ee-ba99-c1e494e325d0.png)


```
(require 'org)
(require 'org-roam)
(org-roam-setup)

(setq org-roam-v2-ack t)

(setq org-roam-directory "~/org/")
(setq org-roam-dailies-directory "private/journal/")
;;(setq org-roam-file-exclude-regexp "README.org")
;;(setq org-roam-db-update-method 'immediate)

(cl-defmethod org-roam-node-directories ((node org-roam-node))
  (if-let ((dirs (file-name-directory (file-relative-name (org-roam-node-file node) org-roam-directory))))
      (format "(%s)" (car (f-split dirs)))
    ""))

(cl-defmethod org-roam-node-backlinkscount ((node org-roam-node))
  (let* ((count (caar (org-roam-db-query
                       [:select (funcall count source)
                                :from links
                                :where (= dest $s1)
                                :and (= type "id")]
                       (org-roam-node-id node)))))
    (format "[%d]" count)))

(setq org-roam-node-display-template "${directories:14} ${title:100} ${backlinkscount:6} ${tags:50}")

```

**Comment by nobiot** [comment]
If I move (setq org-roam-v2-ack t) before (require 'org), relaunch Emacs, and then call `org-roam-node-find`, I get this in my vanilla Emacs completion:

![image](https://user-images.githubusercontent.com/12507865/126906697-53f9969c-063f-45d6-a89b-08e57f67e619.png)

**Comment by zamlz** [comment]
> Because you have a `:bind` construct the `org-roam` package load is deferred, so the package is not `require`d until you call a command. You have placed related configuration outside the `use-package` construct, so you are calling `cl-defmethod` before `org-roam` is being `require`d, hence the issue you see.
> 
> Moving the org-roam configuration into the use-package `:config` construct will fix that.

Strange that this would the issue. I have like a seperate org file for ever single package I use that follows the same type of setup and haven't had any issues so far. But I will take your word for it. It must be that `org-mode-setup` isn't being called basically as you've implied. Now to fix this, I found that the following works for me actually. I got the idea from @nobiot as moving `org-roam-setup` outside of the `use-package` was still causing other errors (such as using the default value for the org-roam directory as opposed to one I eventually set).

Basicaly the code I have below now works. Thanks everyone!

```lisp
(use-package org-roam
  :bind (:map org-mode-map ("M-i" . org-roam-node-insert)))

(setq org-roam-v2-ack t)

(setq org-roam-directory "~/org/")
(setq org-roam-dailies-directory "private/journal/")
(setq org-roam-file-exclude-regexp "README.org")
(setq org-roam-db-update-method 'immediate)

;; Started outside after all the variables have been set!
(org-roam-setup)

;; Now we setup the backlinks count format stuff
(cl-defmethod org-roam-node-directories ((node org-roam-node))
  (if-let ((dirs (file-name-directory (file-relative-name (org-roam-node-file node) org-roam-directory))))
      (format "(%s)" (car (f-split dirs)))
    ""))

(cl-defmethod org-roam-node-backlinkscount ((node org-roam-node))
  (let* ((count (caar (org-roam-db-query
                       [:select (funcall count source)
                                :from links
                                :where (= dest $s1)
                                :and (= type "id")]
                       (org-roam-node-id node)))))
    (format "[%d]" count)))

(setq org-roam-node-display-template "${directories:14} ${title:100} ${backlinkscount:6} ${tags:50}")
```

**Comment by nobiot** [comment]
> Because you have a `:bind` construct the `org-roam` package load is deferred, so the package is not `require`d until you call a command

I hadn’t seen Jethro’s response before I wrote mine. This makes perfect sense now…
