### ISSUE TITLE
Link in headline breaks org-roam buffer

### ISSUE THREAD

**Issue by sopoforic** [org-roam/org-roam#1674]
### Description

If I have a headline linking to the node TARGET, then the org-roam buffer (for TARGET) encounters an error when inserting the preview section.

#### Steps to Reproduce

1. Create two nodes, SOURCE and TARGET
2. In SOURCE, create a headline like `* [[id:2757f654-6ead-458b-83d7-f942e1552a48][TARGET]]` with some content.
3. Visit TARGET and open the org-roam buffer
4. The org-roam buffer does not display the content of the section as a preview, and an error is printed in `*Messages*`.

#### Backtrace

No backtrace appears when debug on error is enabled, but a message like the following is printed:

```
org-roam-node-insert-section: Wrong type argument: char-or-string-p, (1 3240 "text of the section...")
```

#### Expected Results

The section preview should show up in the org-roam buffer.

#### Actual Results

The headline for the node displays in the org-roam buffer, but the buffer ends there. No preview text is displayed.

### Environment

- Framework: N/A
- Org: Org mode version 9.4.4 (9.4.4-25-g3a522a-elpaplus @ /home/tracy/.emacs.d/elpa/org-plus-contrib-20210301/)
- Org-roam: 2.0.0- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.25, cairo version 1.16.0)
 of 2021-07-22

**Comment by xiaolaoc** [comment]
I come to the same problem, and the debug say "Debugger entered--Lisp error: (wrong-type-argument char-or-string-p (1 548 ""))
  org-roam-fontify-like-in-org-mode((1 548 ""))"
  it seems something wrong with org-roam-fontify-like-in-org-mode

**Comment by xiaolaoc** [comment]
in this case, if there is some url link in org format, will come some further bug
<img width="1426" alt="Snipaste_2021-07-26_08-27-49" src="https://user-images.githubusercontent.com/20012636/126918546-0710ba49-39b5-4d1c-b3e0-c3f19ef87bcd.png">
