### ISSUE TITLE
SQL constraint violation

### ISSUE THREAD

**Issue by ndw** [org-roam/org-roam#1679]
### Description

I have a number of Org-Roam documents that have filenames that contain accented letters. 

Sometimes, if I edit and then save one of these documents, I get a spurious "SQL constraint violation" error. It doesn't happen every time, and I haven't been able to work out the circumstances exactly, but I thought I'd report it anyway. FYI.

#### Steps to Reproduce

1. Create some org documents with filenames that contain accented characters.
2. Edit and save them.

**Comment by dangom** [comment]
Are you sure you don't have any duplicate entries? If you copy paste an entry and its ID from one file to another you'll get that error on save.

**Comment by ndw** [comment]
Yes. I just assumed that I'd done that somehow so I grepped about for the ID that was reported as a duplicate. It definitely only occurs in the single file. Because I've only seen it happen for files that have accented characters in their names, my only thought is that some code path sees the names encoded with UTF-8 as single characters and some other path sees them encoded some other way.

Sure enough, I did a little poking around this morning and I've discovered something quite odd.

1. If I run `/bin/ls` and look back at the scroll buffer, in the file named `Agavé-Terrace-closed.org`, the accented "e" is represented as an "e" followed by a combining acute accent: 0x65 0xCC 0x81
2. If I run `/bin/ls A*` and look back, the accented "e" is represented as a single Unicode codepoint, 0xC3 0xA9.

Shell (ZSH) expansion seems to do one thing and `/bin/ls` does something else. I have no idea how they're actually represented in the filesystem. I'd have expected them to be single code points, but perhaps they aren't.

The lesson here is probably not to put accented characters in filenames. I don't generally, and I see that `org-roam-node-find` doesn't, I just happen to have a dozen or so because these Org files started out as entries in my address book.

**Comment by jethrokuan** [comment]
> Sure enough, I did a little poking around this morning and I've discovered something quite odd.
> 
>     1. If I run `/bin/ls` and look back at the scroll buffer, in the file named `Agavé-Terrace-closed.org`, the accented "e" is represented as an "e" followed by a combining acute accent: 0x65 0xCC 0x81
> 
>     2. If I run `/bin/ls A*` and look back, the accented "e" is represented as a single Unicode codepoint, 0xC3 0xA9.

That's... unnerving. It sounds like strings with different unicode codepoints can resolve to the same file, which would certainly be able to cause the duplicate IDs in the database. Don't think Org-roam can fix anything here though, unless there's a way to canonicalize filenames (a brief search didn't turn up anything). Thanks for investigating!

**Comment by constpetrov** [comment]
Hello! 
It seems I have the same issue without any accented letters in the file names. 
```
Warning (org-roam): SQL constraint violation: "UNIQUE constraint failed: nodes.id" for Моя история (EE461748-9629-43E1-A532-194066F76480) in /Users/kpetrov/org/20220121105626-моя_история.org Disable showing Disable logging
Warning (org-roam): SQL constraint violation: "UNIQUE constraint failed: nodes.id" for Shave (B047D0F8-09F1-40BB-A737-9B92A05D681D) in /Users/kpetrov/org/habits.org Disable showing Disable logging
Warning (org-roam): SQL constraint violation: "UNIQUE constraint failed: nodes.id" for Переезд 2022 (BE5A9038-D5B9-4E1D-890F-E64C6EBF15D3) in /Users/kpetrov/org/20220202103740-переезд_2022.org Disable showing Disable logging
Warning (org-roam): SQL constraint violation: "UNIQUE constraint failed: nodes.id" for Амерсфорт (312BCA85-89A6-40E1-A3E5-AA9732AC0354) in /Users/kpetrov/org/20220202103740-переезд_2022.org Disable showing Disable logging
Warning (org-roam): SQL constraint violation: "UNIQUE constraint failed: nodes.id" for Periodic tasks (1399FD2E-A0D3-4643-9EDD-39D224458EFF) in /Users/kpetrov/org/periodic.org Disable showing Disable logging
Warning (org-roam): SQL constraint violation: "UNIQUE constraint failed: nodes.id" for Emacs enhansed (DA502996-F88B-4392-AA18-9734E945D620) in /Users/kpetrov/org/20220202111133-emacs_enhansed.org Disable showing Disable logging
Warning (org-roam): SQL constraint violation: "UNIQUE constraint failed: nodes.id" for ../../../../../org/init (A64F30DC-A04F-4DBC-A5AD-811E40D152BC) in /Users/kpetrov/org/init.org Disable showing Disable logging
```

**Comment by webloginwu** [comment]
I have the same issue, I found there were a lot of space between ID and abc as followings
:PROPERTIES:
:ID:         abc
:TABLE_EXPORT_FILE: /tmp/table.html
:TABLE_EXPORT_FORMAT: orgtbl-to-html
:END:

After I removed extra space between them, 
run
org-roam-db-clear-all
org-roam-db-sync
problem solved.

**Comment by alazaydin** [comment]
for me it was the heading with >15 stars, inlinetasks inserted with `org-inlinetask-insert-task`
