### ISSUE TITLE
v2: garabaged healines in some migrated notes

### ISSUE THREAD

**Issue by oatmealm** [org-roam/org-roam#1687]
### Description

Some headlines (in Hebrew) appear garbaged (escape sequences) in org-roam's db/UI after migration from v1.

#### Steps to Reproduce

1. v1 db with some notes  containing headlines in Unicode charset (I assume)
2. run migration wizard

#### Backtrace

No error messages during migration.

#### Expected Results

Headline should be kept in their original charset.

#### Actual Results

Headlines show as an escape sequence. 

![image](https://user-images.githubusercontent.com/68159077/127106517-77d59ab3-f6ed-4489-989c-2a1df0ca0a44.png)

This seem to resolve once a file is manually edited and the node is re-saved.

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
 of 2021-07-18
- Framework: Doom
- Org: Org mode version 9.5 (9.5-b83ae59 @ /home/xxx/src/doom-emacs/.local/straight/build-28.0.50/org/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/028c95a011395d01ff9b5217dc365f23187bc26c
[pinned]

**Comment by ilya-konovalov** [comment]
I've had the same issue with Russian titles and narrowed the issue down to `org-roam-get-keyword` function where `insert-file-contents-literally` is used to get the title of file node. Replacing it with `insert-file-contents` helps but I'm afraid it might break some other things. Right now I'm using the following snippet to work around that:
```emacs-lisp
(advice-add
 'org-roam-get-keyword
 :around
 (lambda (orig-func &rest r)
   (unwind-protect
       (progn
         (advice-add 'insert-file-contents-literally :override #'insert-file-contents)
         (apply orig-func r))
     (advice-remove 'insert-file-contents-literally  #'insert-file-contents))))
```

**Comment by oatmealm** [comment]
Hi @ilya-konovalov ! Thank you for the suggestion. I guess this is needed only if I would want to re-import/migrate again from v1 to v2?

**Comment by jethrokuan** [comment]
> I've had the same issue with Russian titles and narrowed the issue down to `org-roam-get-keyword` function where `insert-file-contents-literally` is used to get the title of file node. Replacing it with `insert-file-contents` helps but I'm afraid it might break some other things. Right now I'm using the following snippet to work around that:
> 
> ```emacs-lisp
> (advice-add
>  'org-roam-get-keyword
>  :around
>  (lambda (orig-func &rest r)
>    (unwind-protect
>        (progn
>          (advice-add 'insert-file-contents-literally :override #'insert-file-contents)
>          (apply orig-func r))
>      (advice-remove 'insert-file-contents-literally  #'insert-file-contents))))
> ```

This has already been fixed in #1672 .

**Comment by oatmealm** [comment]
Good to hear! Can this help me fixing the nodes after the migration as well?

**Comment by jethrokuan** [comment]
> This seem to resolve once a file is manually edited and the node is re-saved.

If this is true, you can script this:

```
(dolist (f (org-roam--list-files))
  (org-roam-with-file f nil
    (set-buffer-modified-p t)
    (save-buffer)))
```

**Comment by oatmealm** [comment]
No, it doesnt. It seems to work when I edit and save manually, since I make some changes I guess...?

**Comment by jethrokuan** [comment]
Hmm but that's what `set-buffer-modified-p` is supposed to do, i guess if you really wanted you can add something innocuous behind like a newline...

```
(goto-char (point-max))
(insert "\n")
```

**Comment by oatmealm** [comment]
Yes. That's what I meant. When I actually added some content and saved it seem to have sort itself out.

**Comment by jethrokuan** [comment]
I meant in a script:

```
(dolist (f (org-roam--list-files "~/Nextcloud/roam/references"))
  (org-roam-with-file f nil
    (goto-char (point-max))
    (insert "\n")
    (save-buffer)))
```

but I don't think there would be any difference.
