### ISSUE TITLE
Cannot find entry with ID, where the file ID exsit

### ISSUE THREAD

**Issue by lengyueyang** [org-roam/org-roam#1688]
### Description

Migrate from v1 to v2, after insert the node before, ENTER the link, say ""Cannot find entry with ID \"%s\"" "a1013ac4-b632-4c62-b58e-d87b24eb1a23")"

but newly insert node is OK.

#### Steps to Reproduce

1. Load Emacs, open the file aaa.org under org-roam directory
2. Run `org-roam-node-insert`
3. `click the link`

#### Expected Results

  error("Cannot find entry with ID \"%s\"" "a1013ac4-b632-4c62-b58e-d87b24eb1a23")
  org-id-open("a1013ac4-b632-4c62-b58e-d87b24eb1a23" nil)
  org-link-open((link (:type "id" :path "a1013ac4-b632-4c62-b58e-d87b24eb1a23" :format bracket :raw-link "id:a1013ac4-b632-4c62-b58e-d87b24eb1a23" :application nil :search-option nil :begin 217 :end 270 :contents-begin 260 :contents-end 268 :post-blank 0 :parent (paragraph (:begin 217 :end 272 :contents-begin 217 :contents-end 271 :post-blank 1 :post-affiliated 217 :parent nil)))) nil)
  org-open-at-point(nil)
  (if (or (equal (org-element-property :type lineage) "img") (and path (image-type-from-file-name path))) (+org--toggle-inline-images-in-subtree (org-element-property :begin lineage) (org-element-property :end lineage)) (org-open-at-point arg))
  (let* ((lineage (org-element-lineage context '(link) t)) (path (org-element-property :path lineage))) (if (or (equal (org-element-property :type lineage) "img") (and path (image-type-from-file-name path))) (+org--toggle-inline-images-in-subtree (org-element-property :begin lineage) (org-element-property :end lineage)) (org-open-at-point arg)))
  (let nil (let* ((lineage (org-element-lineage context '(link) t)) (path (org-element-property :path lineage))) (if (or (equal (org-element-property :type lineage) "img") (and path (image-type-from-file-name path))) (+org--toggle-inline-images-in-subtree (org-element-property :begin lineage) (org-element-property :end lineage)) (org-open-at-point arg))))
  (cond ((eq type 'headline) (let nil (cond ((memq (and (boundp ...) org-goto-map) (current-active-maps)) (org-goto-ret)) ((and (fboundp 'toc-org-insert-toc) (member "TOC" (org-get-tags))) (toc-org-insert-toc) (message "Updating table of contents")) ((string= "ARCHIVE" (car-safe (org-get-tags))) (org-force-cycle-archived)) ((or (org-element-property :todo-type context) (org-element-property :scheduled context)) (org-todo (if (eq ... ...) (or ... ...) 'done)))) (org-update-checkbox-count) (org-update-parent-todo-statistics) (if (and (fboundp 'toc-org-insert-toc) (member "TOC" (org-get-tags))) (progn (toc-org-insert-toc) (message "Updating table of contents"))) (let* ((beg (if (org-before-first-heading-p) (line-beginning-position) (save-excursion ... ...))) (end (if (org-before-first-heading-p) (line-end-position) (save-excursion ... ...))) (overlays (condition-case nil (progn ...) (error nil))) (latex-overlays (cl-find-if #'... overlays)) (image-overlays (cl-find-if #'... overlays))) (+org--toggle-inline-images-in-subtree beg end) (if (or image-overlays latex-overlays) (org-clear-latex-preview beg end) (org--latex-preview-region beg end))))) ((eq type 'clock) (let nil (org-clock-update-time-maybe))) ((eq type 'footnote-reference) (let nil (org-footnote-goto-definition (org-element-property :label context)))) ((eq type 'footnote-definition) (let nil (org-footnote-goto-previous-reference (org-element-property :label context)))) ((memq type '(timestamp planning)) (let nil (org-follow-timestamp-link))) ((memq type '(table-row table)) (let nil (if (org-at-TBLFM-p) (org-table-calc-current-TBLFM) (condition-case nil (progn (save-excursion (goto-char ...) (org-call-with-arg ... ...))) (error nil))))) ((eq type 'table-cell) (let nil (org-table-blank-field) (org-table-recalculate arg) (if (and (string-empty-p (string-trim (org-table-get-field))) (and (boundp 'evil-local-mode) evil-local-mode)) (progn (evil-change-state 'insert))))) ((eq type 'babel-call) (let nil (org-babel-lob-execute-maybe))) ((eq type 'statistics-cookie) (let nil (save-excursion (org-update-statistics-cookies arg)))) ((memq type '(inline-src-block src-block)) (let nil (org-babel-execute-src-block arg))) ((memq type '(latex-environment latex-fragment)) (let nil (org-latex-preview arg))) ((eq type 'link) (let nil (let* ((lineage (org-element-lineage context '... t)) (path (org-element-property :path lineage))) (if (or (equal (org-element-property :type lineage) "img") (and path (image-type-from-file-name path))) (+org--toggle-inline-images-in-subtree (org-element-property :begin lineage) (org-element-property :end lineage)) (org-open-at-point arg))))) ((org-element-property :checkbox (org-element-lineage context '(item) t)) (let nil (let ((match (and (org-at-item-checkbox-p) (match-string 1)))) (org-toggle-checkbox (if (equal match "[ ]") '(16)))))) (t (let nil (if (or (org-in-regexp org-ts-regexp-both nil t) (org-in-regexp org-tsr-regexp-both nil t) (org-in-regexp org-link-any-re nil t)) (call-interactively #'org-open-at-point) (+org--toggle-inline-images-in-subtree (org-element-property :begin context) (org-element-property :end context))))))
  (let* ((context (org-element-context)) (type (org-element-type context))) (while (and context (memq type '(verbatim code bold italic underline strike-through subscript superscript))) (setq context (org-element-property :parent context) type (org-element-type context))) (cond ((eq type 'headline) (let nil (cond ((memq (and ... org-goto-map) (current-active-maps)) (org-goto-ret)) ((and (fboundp ...) (member "TOC" ...)) (toc-org-insert-toc) (message "Updating table of contents")) ((string= "ARCHIVE" (car-safe ...)) (org-force-cycle-archived)) ((or (org-element-property :todo-type context) (org-element-property :scheduled context)) (org-todo (if ... ... ...)))) (org-update-checkbox-count) (org-update-parent-todo-statistics) (if (and (fboundp 'toc-org-insert-toc) (member "TOC" (org-get-tags))) (progn (toc-org-insert-toc) (message "Updating table of contents"))) (let* ((beg (if ... ... ...)) (end (if ... ... ...)) (overlays (condition-case nil ... ...)) (latex-overlays (cl-find-if ... overlays)) (image-overlays (cl-find-if ... overlays))) (+org--toggle-inline-images-in-subtree beg end) (if (or image-overlays latex-overlays) (org-clear-latex-preview beg end) (org--latex-preview-region beg end))))) ((eq type 'clock) (let nil (org-clock-update-time-maybe))) ((eq type 'footnote-reference) (let nil (org-footnote-goto-definition (org-element-property :label context)))) ((eq type 'footnote-definition) (let nil (org-footnote-goto-previous-reference (org-element-property :label context)))) ((memq type '(timestamp planning)) (let nil (org-follow-timestamp-link))) ((memq type '(table-row table)) (let nil (if (org-at-TBLFM-p) (org-table-calc-current-TBLFM) (condition-case nil (progn (save-excursion ... ...)) (error nil))))) ((eq type 'table-cell) (let nil (org-table-blank-field) (org-table-recalculate arg) (if (and (string-empty-p (string-trim ...)) (and (boundp ...) evil-local-mode)) (progn (evil-change-state 'insert))))) ((eq type 'babel-call) (let nil (org-babel-lob-execute-maybe))) ((eq type 'statistics-cookie) (let nil (save-excursion (org-update-statistics-cookies arg)))) ((memq type '(inline-src-block src-block)) (let nil (org-babel-execute-src-block arg))) ((memq type '(latex-environment latex-fragment)) (let nil (org-latex-preview arg))) ((eq type 'link) (let nil (let* ((lineage (org-element-lineage context ... t)) (path (org-element-property :path lineage))) (if (or (equal ... "img") (and path ...)) (+org--toggle-inline-images-in-subtree (org-element-property :begin lineage) (org-element-property :end lineage)) (org-open-at-point arg))))) ((org-element-property :checkbox (org-element-lineage context '(item) t)) (let nil (let ((match (and ... ...))) (org-toggle-checkbox (if (equal match "[ ]") '...))))) (t (let nil (if (or (org-in-regexp org-ts-regexp-both nil t) (org-in-regexp org-tsr-regexp-both nil t) (org-in-regexp org-link-any-re nil t)) (call-interactively #'org-open-at-point) (+org--toggle-inline-images-in-subtree (org-element-property :begin context) (org-element-property :end context)))))))
  (if (button-at (point)) (call-interactively #'push-button) (let* ((context (org-element-context)) (type (org-element-type context))) (while (and context (memq type '(verbatim code bold italic underline strike-through subscript superscript))) (setq context (org-element-property :parent context) type (org-element-type context))) (cond ((eq type 'headline) (let nil (cond ((memq ... ...) (org-goto-ret)) ((and ... ...) (toc-org-insert-toc) (message "Updating table of contents")) ((string= "ARCHIVE" ...) (org-force-cycle-archived)) ((or ... ...) (org-todo ...))) (org-update-checkbox-count) (org-update-parent-todo-statistics) (if (and (fboundp ...) (member "TOC" ...)) (progn (toc-org-insert-toc) (message "Updating table of contents"))) (let* ((beg ...) (end ...) (overlays ...) (latex-overlays ...) (image-overlays ...)) (+org--toggle-inline-images-in-subtree beg end) (if (or image-overlays latex-overlays) (org-clear-latex-preview beg end) (org--latex-preview-region beg end))))) ((eq type 'clock) (let nil (org-clock-update-time-maybe))) ((eq type 'footnote-reference) (let nil (org-footnote-goto-definition (org-element-property :label context)))) ((eq type 'footnote-definition) (let nil (org-footnote-goto-previous-reference (org-element-property :label context)))) ((memq type '(timestamp planning)) (let nil (org-follow-timestamp-link))) ((memq type '(table-row table)) (let nil (if (org-at-TBLFM-p) (org-table-calc-current-TBLFM) (condition-case nil (progn ...) (error nil))))) ((eq type 'table-cell) (let nil (org-table-blank-field) (org-table-recalculate arg) (if (and (string-empty-p ...) (and ... evil-local-mode)) (progn (evil-change-state ...))))) ((eq type 'babel-call) (let nil (org-babel-lob-execute-maybe))) ((eq type 'statistics-cookie) (let nil (save-excursion (org-update-statistics-cookies arg)))) ((memq type '(inline-src-block src-block)) (let nil (org-babel-execute-src-block arg))) ((memq type '(latex-environment latex-fragment)) (let nil (org-latex-preview arg))) ((eq type 'link) (let nil (let* ((lineage ...) (path ...)) (if (or ... ...) (+org--toggle-inline-images-in-subtree ... ...) (org-open-at-point arg))))) ((org-element-property :checkbox (org-element-lineage context '(item) t)) (let nil (let ((match ...)) (org-toggle-checkbox (if ... ...))))) (t (let nil (if (or (org-in-regexp org-ts-regexp-both nil t) (org-in-regexp org-tsr-regexp-both nil t) (org-in-regexp org-link-any-re nil t)) (call-interactively #'org-open-at-point) (+org--toggle-inline-images-in-subtree (org-element-property :begin context) (org-element-property :end context))))))))
  +org/dwim-at-point(nil)
  funcall-interactively(+org/dwim-at-point nil)
  command-execute(+org/dwim-at-point)

**Comment by jethrokuan** [comment]
Did you save the newly created node you made with `org-roam-node-insert`? If it is not saved Org won't pick it up, and neither will Org-roam.

**Comment by lengyueyang** [comment]
Newly created node is OK, but the node migrate from v1, the migrate file has ID, and I could insert with the org-roam-node-insert, But when click it, has errors as before.

**Comment by jethrokuan** [comment]
Can you follow the instructions in this comment? https://github.com/org-roam/org-roam/issues/1702#issuecomment-888998330

**Comment by lengyueyang** [comment]
Thanks for you replay, after follow the comment #1702 M-: (org-id-update-id-locations (directory-files-recursively org-roam-directory ".org$\\|.org.gpg$")), I solved.

**Comment by lengyueyang** [comment]
The answer in #1702
