### ISSUE TITLE
Refactor Org-roam's modules

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam#1690]
### Description

Org-roam's codebase is in need of some restructuring. For more context, see https://github.com/org-roam/org-roam/issues/1590#issuecomment-885817825.

### Migration plan

- Many modules have intricate interdependencies, so we migrate most of them into `org-roam.el`.
- Extensions that aren't core to org-roam's functionality are left in their own files, and perhaps in an extensions directory
  - [ ] graph
  - [ ] dailies
  - [ ] protocol
  - [ ] overlay

**Comment by jethrokuan** [comment]
@Wetlize I've invited you to the GitHub team, which should give you commit rights.

I agree with most of what you mentioned in the previous thread, it does seem like there will be quite some overlap between your proposal and #1686 , so it's up to you whether you want to work on a new branch or just modify that one. While walking through this i'm also earmarking certain functions/variables that should be reworked/renamed.

**Comment by progfolio** [comment]
For what it's worth, I think the suggestion @Wetlize gave of completely restructuring things, but maintaining the modularity is the correct approach. See packages like helm, magit, or Org which manage to do just that. I imagine the conceptual model is clearer than it was in v1, so it should be easier to untangle.

**Comment by Wetlize** [comment]
@jethrokuan Is this dependency still needed?
https://github.com/org-roam/org-roam/blob/0c2454063939fdf75320cd0ed9ce494e46967ad6/org-roam.el#L40

**Comment by jethrokuan** [comment]
> @jethrokuan Is this dependency still needed?

No, this was for v1, but now I think we use `split-string-and-unquote`.
