### ISSUE TITLE
Add support for indexing org-cite `citation-reference` elements

### ISSUE THREAD

**Issue by bdarcus** [org-roam/org-roam#1691]
I initially posted this over on the ORB tracker, but realize OR itself just needs a small enhancement.

https://github.com/org-roam/org-roam-bibtex/issues/191

Org 9.5 will have support for the new `org-cite` module, which is now in master.

This will obsolete much of `org-ref`, and offer state-of-art modular citation support in Org.

John Kitchin has started this project to target it; should likely be on MELPA soon.

https://github.com/jkitchin/org-ref-cite

I think all you need to start is to index the new citation-reference elements. See, for example, [org-cite-list-keys](https://code.orgmode.org/bzg/org-mode/src/master/lisp/oc.el#L798).

```elisp
(defun org-cite-list-keys (info)
  (delete-dups
   (org-element-map (org-cite-list-citations info) 'citation-reference
     (lambda (r) (org-element-property :key r))
     info)))
```

**Comment by bdarcus** [comment]
A related question:

How should bib notes be identified ideally in v2, and then in turn accessed?

```org
:ROAM_REFS: doe19
```

... or since that gives no type info for the ref:

 ```org
:ROAM_REFS: [cite:@doe19]
```

... except org-cite citations aren't currently allowed there.

Or instead the earlier (`org-ref`?) syntax:

 ```org
:ROAM_REFS: cite:doe19
```

**Comment by yuuyins** [comment]
if org-roam ever supports org-cite style i'd vote for `[cite:@doe19]` by default because it's the default for org-cite and as i see it this module uses org-cite, i.e. consistency.

**Comment by Wetlize** [comment]
Closing this now with #1806 merged.
