### ISSUE TITLE
org-roam-node-find can't show unicode characters properly for titles

### ISSUE THREAD

**Issue by Zetagon** [org-roam/org-roam#1696]
### Description
Unicode characters in title are not displayed properly.

#### Steps to Reproduce
Add an org file with the content below
```
:PROPERTIES:
:ID:       a0579a2b-6cdd-464a-8870-009f725f1737
:END:
\#title: föö
* bär
:PROPERTIES:
:ID:       ec40c03c-9cdc-4374-bf6f-b60e83128f0a
:END:
```

#### Expected Results
`org-roam-node-find` should show `#title: föö > bär`

#### Actual Results
`org-roam-node-find` shows `#title: f\\303\\245 > bär`

### Environment
```
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
- Framework: Doom
- Org: Org mode version 9.5 (9.5-b83ae59 @ /home/leo/.emacs.d/.local/straight/build-27.1/org/)
- Org-roam: 2.0.0
```

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/028c95a011395d01ff9b5217dc365f23187bc26c

**Comment by Wetlize** [comment]
This was fixed with 6ce07cdbf7c75e4b70e124cb7b2529768e8c6f4f (also see https://github.com/hlissner/doom-emacs/issues/5293). You need to either, bump the package in your private config or wait until Doom will do it (https://github.com/hlissner/doom-emacs/issues/5294).
