### ISSUE TITLE
org-roam-capture fails if there is a function to get point given in the template.

### ISSUE THREAD

**Issue by spacekitteh** [org-roam/org-roam#1699]
c.f. #704 and https://github.com/progfolio/doct/issues/16

Specifically, it complains that it cannot find `:if-new`.

Either:
1. Fix the logic which finds `:if-new`, or
2. Use the hardcoded `org-roam-capture--get-point` as a default but allow it to be overriden, or
3. Strip out any point-finding function.

**Comment by jethrokuan** [comment]
The function is hardcoded because I don't think it makes sense to be overridden, but I'll allow a special value `'ignore` in place of where the function should be.
