### ISSUE TITLE
org-roam capture template doesn't work correctly, capture buffer isn't being shown

### ISSUE THREAD

**Issue by RastiGiG** [org-roam/org-roam#1700]
### Description

I run into an error, whenever i try to run 'org-roam-node-find'. The command actually runs normally first, the error only occurs after i enter the name of the node (any node) into the minibuffer.
The following message shows up in the *warnings* buffer:

org-capture: Capture template ‘d’: Wrong type argument: listp, t

When i look up the variable 'org-roam-capture-templates' it has the value specified in the documentation:

(("d" "default" plain "%?" :if-new
  (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
  :unnarrowed t))

I use the 'normal' org capture regularly and they work just fine for me, which is why i can't really determine, what causes the issue for me.
Also i use straight.el to install packages, but that should not make a difference, should it?
I couldn't find this issue being solved anywhere, so if it was, please point me there. 

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam-node-find`
3. Enter the name of the node

#### Backtrace

Debugger entered--Lisp error: (error "Capture template ‘d’: Wrong type argument: listp, ...")
  signal(error ("Capture template ‘d’: Wrong type argument: listp, ..."))
  error("Capture template `%s': %s" "d" "Wrong type argument: listp, t")
  org-capture(nil "d")
  org-roam-capture-(:node #s(org-roam-node :file nil :file-hash nil :file-atime nil :file-mtime nil :id nil :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title "Index" :properties nil :olp nil :tags nil :aliases nil :refs nil) :props (:finalize find-file :call-location #<marker at 11345 in *Messages*>))
  (if (progn (or (and (memq (type-of node) cl-struct-org-roam-node-tags) t) (signal 'wrong-type-argument (list 'org-roam-node node))) (aref node 1)) (org-roam-node-visit node other-window) (org-roam-capture- :node node :props '(:finalize find-file :call-location #<marker at 11345 in *Messages*>)))
  (let ((node (org-roam-node-read initial-input filter-fn))) (if (progn (or (and (memq (type-of node) cl-struct-org-roam-node-tags) t) (signal 'wrong-type-argument (list 'org-roam-node node))) (aref node 1)) (org-roam-node-visit node other-window) (org-roam-capture- :node node :props '(:finalize find-file :call-location #<marker at 11345 in *Messages*>))))
  org-roam-node-find()
  funcall-interactively(org-roam-node-find)
  call-interactively(org-roam-node-find nil nil)
  command-execute(org-roam-node-find)

#### Expected Results

This should create an org file with the specified name and a node id

#### Actual Results

No file gets created, only an empty symlink shows up in dired

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-gfdb98a @ /home/sebastian/.dotfiles/C1_EmacsConfiguration/.emacs.d/straight/build/org/)
- Org-roam: 2.0.0

**Comment by Preve92** [comment]
Same issue here.  Installed via package.el.  Buffer is created, but capture template not shown.

**Comment by Wetlize** [comment]
I can't repro this. Is this on the latest commit? Can you reproduce it with a new and empty `org-roam-directory`?

**Comment by RastiGiG** [comment]
Sure i will try.
Btw i forgot to mention that i use chemacs [https://github.com/plexus/chemacs](url) to manage multiple emacs profiles at the same time. 
Got a spacemacs installation running that i try to slowly move away from to build my own environment, but i still wanted to be able to switch back just in case.
I'll test this in case there's a conflict there, but since normal capture templates work i don't think that should be an issue. Anyway the profile that i run into that problem with is the one i build from scratch.
I'll let you know if i find anything.

**Comment by RastiGiG** [comment]
Quick update

I've been testing a little bit and ran into the following error on a blank slate emacs configuration:

"Could not read 'org-id-values' from ~/.dotfiles/C1-EmacsConfiguration/.emacs.d/.org-id-locations, setting it to nil"

After that the old messages appears:
"org-capture: Capture template 'd': Wrong type argument: listp, t"

On a second note:

I realized, that - although Emacs doesn't open the *capture* buffer - a new buffer is actually created, that one can access through the *buffer list*. When i navigate to the `org-roam-directory` the newly created file is shown to be a link with the new buffer i mentioned above as a target. Once i save that buffer, i can access the file normally. And it also gets shown when i try to navigate to that file with `org-roam-node-find`.
So i'm guessing that org-roam actually sort of works, but requires extra steps for me (looking up the new buffer in the *buffer list* and saving it manually)
Still this is obviously not the intended behaviour and i would like to get it working correctly.
So i'll keep on looking
If you come up with anything in the meantime, pls let me know

**Comment by Wetlize** [comment]
> "Could not read 'org-id-values' from ~/.dotfiles/C1-EmacsConfiguration/.emacs.d/.org-id-locations, setting it to nil"

Do you have the mentioned file in your `.emacs.d`? Try to run <kbd>M-:</kbd> `(org-id-update-id-locations (directory-files-recursively org-roam-directory ".org$\\|.org.gpg$")` <kbd>RET</kbd> after loading Emacs and `org-roam` and see if it helps. If doesn't, then it's a guessing game without being able to see the config file.

**Comment by RastiGiG** [comment]
So running your command worked, now the file can be found. Guessing that was due to me basically 'deleting' the old file within .emacs.d folder by renaming the whole folder.
However i tested org-roam again on this 'fresh' install (installing from melpa as described in documentation) and it worked fine.
I also tried loading a new config with chemacs and it also worked. So it is definitely something in my config that causes that conflict.
I'll try a little longer to narrow it down. Can't rlly offer a minimal config at that point in time, sry.
Are there any known conflicts with other packages? Something i should check first?
I will try loading `org-roam` before i set my custom capture templates in case that is causing the issue.
If that doesn't fix it i will have to postpone testing to next week. Can't spend more time on this today

**Comment by uningan** [comment]
Im getting exactly this error but is not an org-id problem. Because my backtrace have id prop:

```
Debugger entered--Lisp error: (error "Capture template ‘d’: Wrong type argument: listp, t")
  error("Capture template `%s': %s" "d" "Wrong type argument: listp, t")
  (condition-case error (org-capture-place-template (eq (car (org-capture-get :target)) 'function)) ((error quit) (if (and (buffer-base-buffer (current-buffer)) (string-prefix-p "CAPTURE-" (buffer-name))) (progn (kill-buffer (current-buffer)))) (set-window-configuration (org-capture-get :return-to-wconf)) (error "Capture template `%s': %s" (org-capture-get :key) (error-message-string error))))
  (cond ((equal entry "C") (customize-variable 'org-capture-templates)) ((equal entry "q") (user-error "Abort")) (t (org-capture-set-plist entry) (org-capture-get-template) (org-capture-put :original-buffer orig-buf :original-file (or (buffer-file-name orig-buf) (and (featurep 'dired) (car (rassq orig-buf dired-buffers)))) :original-file-nondirectory (and (buffer-file-name orig-buf) (file-name-nondirectory (buffer-file-name orig-buf))) :annotation annotation :initial initial :return-to-wconf (current-window-configuration) :default-time (or org-overriding-default-time (org-current-time))) (org-capture-set-target-location (and (equal goto 0) 'here)) (condition-case error (org-capture-put :template (org-capture-fill-template)) ((error quit) (if (get-buffer "*Capture*") (kill-buffer "*Capture*")) (error "Capture abort: %s" (error-message-string error)))) (setq org-capture-clock-keep (org-capture-get :clock-keep)) (condition-case error (org-capture-place-template (eq (car (org-capture-get :target)) 'function)) ((error quit) (if (and (buffer-base-buffer (current-buffer)) (string-prefix-p "CAPTURE-" (buffer-name))) (progn (kill-buffer (current-buffer)))) (set-window-configuration (org-capture-get :return-to-wconf)) (error "Capture template `%s': %s" (org-capture-get :key) (error-message-string error)))) (if (and (derived-mode-p 'org-mode) (org-capture-get :clock-in)) (progn (condition-case nil (progn (if (org-clock-is-active) (progn ...)) (org-clock-in) (set (make-local-variable ...) t)) (error "Could not start the clock in this capture buffer")))) (if (org-capture-get :immediate-finish) (progn (org-capture-finalize)))))
  (let* ((orig-buf (current-buffer)) (annotation (if (and (boundp 'org-capture-link-is-already-stored) org-capture-link-is-already-stored) (plist-get org-store-link-plist :annotation) (condition-case nil (progn (org-store-link nil)) (error nil)))) (entry (or org-capture-entry (org-capture-select-template keys))) initial) (setq initial (or org-capture-initial (and (org-region-active-p) (buffer-substring (point) (mark))))) (if (stringp initial) (progn (remove-text-properties 0 (length initial) '(read-only t) initial))) (if (stringp annotation) (progn (remove-text-properties 0 (length annotation) '(read-only t) annotation))) (cond ((equal entry "C") (customize-variable 'org-capture-templates)) ((equal entry "q") (user-error "Abort")) (t (org-capture-set-plist entry) (org-capture-get-template) (org-capture-put :original-buffer orig-buf :original-file (or (buffer-file-name orig-buf) (and (featurep 'dired) (car (rassq orig-buf dired-buffers)))) :original-file-nondirectory (and (buffer-file-name orig-buf) (file-name-nondirectory (buffer-file-name orig-buf))) :annotation annotation :initial initial :return-to-wconf (current-window-configuration) :default-time (or org-overriding-default-time (org-current-time))) (org-capture-set-target-location (and (equal goto 0) 'here)) (condition-case error (org-capture-put :template (org-capture-fill-template)) ((error quit) (if (get-buffer "*Capture*") (kill-buffer "*Capture*")) (error "Capture abort: %s" (error-message-string error)))) (setq org-capture-clock-keep (org-capture-get :clock-keep)) (condition-case error (org-capture-place-template (eq (car (org-capture-get :target)) 'function)) ((error quit) (if (and (buffer-base-buffer ...) (string-prefix-p "CAPTURE-" ...)) (progn (kill-buffer ...))) (set-window-configuration (org-capture-get :return-to-wconf)) (error "Capture template `%s': %s" (org-capture-get :key) (error-message-string error)))) (if (and (derived-mode-p 'org-mode) (org-capture-get :clock-in)) (progn (condition-case nil (progn (if ... ...) (org-clock-in) (set ... t)) (error "Could not start the clock in this capture buffer")))) (if (org-capture-get :immediate-finish) (progn (org-capture-finalize))))))
  (cond ((equal goto '(4)) (org-capture-goto-target keys)) ((equal goto '(16)) (org-capture-goto-last-stored)) (t (let* ((orig-buf (current-buffer)) (annotation (if (and (boundp ...) org-capture-link-is-already-stored) (plist-get org-store-link-plist :annotation) (condition-case nil (progn ...) (error nil)))) (entry (or org-capture-entry (org-capture-select-template keys))) initial) (setq initial (or org-capture-initial (and (org-region-active-p) (buffer-substring (point) (mark))))) (if (stringp initial) (progn (remove-text-properties 0 (length initial) '(read-only t) initial))) (if (stringp annotation) (progn (remove-text-properties 0 (length annotation) '(read-only t) annotation))) (cond ((equal entry "C") (customize-variable 'org-capture-templates)) ((equal entry "q") (user-error "Abort")) (t (org-capture-set-plist entry) (org-capture-get-template) (org-capture-put :original-buffer orig-buf :original-file (or (buffer-file-name orig-buf) (and ... ...)) :original-file-nondirectory (and (buffer-file-name orig-buf) (file-name-nondirectory ...)) :annotation annotation :initial initial :return-to-wconf (current-window-configuration) :default-time (or org-overriding-default-time (org-current-time))) (org-capture-set-target-location (and (equal goto 0) 'here)) (condition-case error (org-capture-put :template (org-capture-fill-template)) ((error quit) (if ... ...) (error "Capture abort: %s" ...))) (setq org-capture-clock-keep (org-capture-get :clock-keep)) (condition-case error (org-capture-place-template (eq ... ...)) ((error quit) (if ... ...) (set-window-configuration ...) (error "Capture template `%s': %s" ... ...))) (if (and (derived-mode-p ...) (org-capture-get :clock-in)) (progn (condition-case nil ... ...))) (if (org-capture-get :immediate-finish) (progn (org-capture-finalize))))))))
  org-capture(nil "d")
  org-roam-capture-(:node #s(org-roam-node :file nil :file-title nil :file-hash nil :file-atime nil :file-mtime nil :id "d6ed26dc-fae0-434d-bc4b-0336bb133750" :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title "Ambu2" :properties nil :olp nil :tags nil :aliases nil :refs nil) :templates nil :props (:finalize find-file :call-location #<marker at 1 in *Backtrace*>))
  org-roam-node-find()
  funcall-interactively(org-roam-node-find)
  command-execute(org-roam-node-find record)
  execute-extended-command(nil "org-roam-node-find" nil)
  funcall-interactively(execute-extended-command nil "org-roam-node-find" nil)
  command-execute(execute-extended-command)
```
Im using protesilaos vanilla emacs config (https://github.com/protesilaos/dotfiles/blob/master/emacs/.emacs.d/prot-emacs.org) with my own customizations for org-roam (in user-emacs.org)

```
;;; Org-Roam
(prot-emacs-elpa-package 'org-roam
  (setq org-roam-directory (file-truename "~/Documents/org/roam"))
  (org-roam-db-autosync-mode t)
  (require 'org-roam))
```
I've checked .org-id-locations file and its all ok.

My env:
"GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)"
Org mode version 9.5.2 (9.5.2-gfbff08 @ /nix/store/688q3q4sa0gp0mf5q15djcs8lvnllkg0-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.5.2/)
Org-roam 20220319.1902
