### ISSUE TITLE
Org-roam requires re-indexing each startup when org-roam-directory is a symlink

### ISSUE THREAD

**Issue by egregius313** [org-roam/org-roam#1712]
### Description

When first starting `org-roam`, it must re-index the entire directory when `org-roam-directory` is a symlink.

I have `~/org` sync to Nextcloud, so I have `~/org` point to `~/Nextcloud/Documents/org` via symlink (`ln -s ~/Nextcloud/Documents/org ~/org/`).

My temporary solution has been to set my `org-roam-directory` to `~/Nextcloud/Documents/org/roam/` directly. However this makes my configuration less portable.

#### Steps to Reproduce

- `$ ln -s ~/Nextcloud/Documents/org ~/org`
- `(setf org-directory (expand-file-name "~/org"))`
- `(setf org-roam-directory (expand-file-name "roam" org-directory))`
- `(org-roam-db-sync)`
- Close Emacs
- Reopen Emacs and re-invoke `(org-roam-db-sync)` manually or via `org-roam-setup`.

#### Backtrace

`org-roam-db-sync` uses `org-roam--list-all-files` (https://github.com/org-roam/org-roam/blob/master/org-roam-db.el#L480), which does not follow symlinks when getting the file paths. The data base stores the real path to the file, so on line https://github.com/org-roam/org-roam/blob/master/org-roam-db.el#L485, the db presence-check always has a cache invalidation, causing a file to be marked as modified.

This may be because Emacs (at least with my Doom configuration) follows symlinks for `(buffer-file-name)`

#### Expected Results

Org-roam to not need to re-index all files `org-roam-directory` each time `org-roam-db-sync` is invoked.

#### Actual Results

`org-roam-db-sync` treats all files as modified, regardless of their modification status.

### Environment

- Org-roam commit: https://github.com/org-roam/org-roam/commit/de47f0a28d0e346c88c632ea1bb078b69d1e4b52
- Emacs: GNU Emacs 27.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4)
 of 2021-06-13
- Framework: Doom
- Org: Org mode version 9.5 (9.5-b83ae59 @ /home/egregius313/.ihsec/doom/.local/straight/build-27.2/org/)
- Org-roam: 2.0.0

**Comment by jethrokuan** [comment]
use `(setf org-roam-directory (file-truename (expand-file-name "roam" org-directory)))`. For performance reasons Org-roam doesn't resolve symlinks.

**Comment by dre-sctg** [comment]
just an update for others. I've worked around my issue with syncing across different users by keeping different database files per each user. 
```
      (org-roam-db-location (file-truename (concat "~/Dropbox/etc/" user-login-name ".roam.db")))
```

**Comment by jonbarksdale** [comment]
similar note - roam dailies doesn't recognize a file as being a daily if the org-roam-dailies directory is a symlink.

**Comment by simendsjo** [comment]
I have the same problem where I have several profiles, A, B and C, and each of them has a symlink to Common for shared things. Whenever I change something in Common, the current profile doesn't update. And when I start roam/switch profile, I need to rebuild the database.
