### ISSUE TITLE
Template needs to specify ‘:if-new’

### ISSUE THREAD

**Issue by OrionRandD** [org-roam/org-roam#1714]
I have this issue 
user-error: Template needs to specify ‘:if-new’
and I am unable to create new nodes.
I know that I have to add ‘:if-new’

In my previous templates that worked in my org-roamV1
But, I do not know where specifically  :(
Here are my current org-roam templates:
Where do I add the ":if-new" directive to stop org-roam 
complaining, so that I can create new nodes?

;; When using bibtex-completion via the `biblio` module
(unpin! bibtex-completion helm-bibtex ivy-bibtex)

(setq orb-preformat-keywords '("citekey" "author" "date"))
(setq orb-templates
      '((\"r\" \"reference\" plain (function org-roam-capture--get-point)
         "#+ROAM_KEY: %^{citekey}%?
%^{author} published %^{entry-type} in %^{date}: fullcite:%\\1."
         :file-name "references/${citekey}"
         :head "#+TITLE: ${title}"
         :unnarrowed t)))

(setq org-roam-capture-templates
      '(("r" "reference" plain (function org-roam-capture--get-point)
         (file "~/org~/template.org") ; <--
         :file-name "test/${citekey}"
         :head "#+TITLE: ${title}\n"
         :unnarrowed t)))

(setq orb-preformat-keywords
      '("citekey" "title" "url" "author-or-editor" "keywords" "file")
      orb-process-file-keyword t
      orb-file-field-extensions '("pdf"))

(setq orb-templates
      '(("r" "ref" plain (function org-roam-capture--get-point)
         ""
         :file-name "${citekey}"
         :head "#+TITLE: ${citekey}: ${title}\n#+ROAM_KEY: ${ref}

- tags ::
- keywords :: ${keywords}

* ${title}
:PROPERTIES:
:Custom_ID: ${citekey}
:URL: ${url}
:AUTHOR: ${author-or-editor}
:NOTER_DOCUMENT: ${file}  ; <== special file keyword: if more than one filename
:NOTER_PAGE:              ;     is available, the user will be prompted to choose
:END:")))

        ("r" "ref" plain (function org-roam-capture--get-point) ""
             :file-name "${citekey}"
             :head "#+TITLE: ${citekey}: ${title}\n#+ROAM_KEY: ${ref}\n" ; <--
             :unnarrowed t)

**Comment by jethrokuan** [comment]
```
(setq org-roam-capture-templates
      '(("r" "reference" plain
         (file "/org/template.org")
         :if-new (file+head "test/${citekey}.org"
                            "#+TITLE: ${title}\n")
         :unnarrowed t)))
```

is an example, please see [the manual](https://www.orgroam.com/manual.html#The-Templating-System) for details.

**Comment by OrionRandD** [comment]
> ```
> (setq org-roam-capture-templates
>       '(("r" "reference" plain
>          (file "/org/template.org")
>          :if-new (file+head "test/${citekey}.org"
>                             "#+TITLE: ${title}\n")
>          :unnarrowed t)))
> ```
> 
> is an example, please see [the manual](https://www.orgroam.com/manual.html#The-Templating-System) for details.

Thx :)
