### ISSUE TITLE
Cannot build emacsql sqlite binary

### ISSUE THREAD

**Issue by wang1zhen** [org-roam/org-roam#1718]
### Description

I was trying to use org-roam v2 in doom emacs, and I simply added the `+roam2` flag in doom emacs init file.

When I tried to `find-node`, here is what prompted in my minibuffer:

```
Compiling EmacSQL SQLite binary ...
emacsql-sqlite-ensure-binary: No EmacSQL SQLite binary available, aborting
```

And the following is my compiler log:
```
/usr/bin/cc -I/home/wang1zhen/.emacs.d/.local/straight/build-27.1/emacsql-sqlite/sqlite -O2 -DSQLITE_THREADSAFE=0 -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_JSON1 -DSQLITE_SOUNDEX /home/wang1zhen/.emacs.d/.local/straight/build-27.1/emacsql-sqlite/sqlite/sqlite3.c /home/wang1zhen/.emacs.d/.local/straight/build-27.1/emacsql-sqlite/sqlite/emacsql.c -lm -ldl -o /home/wang1zhen/.emacs.d/.local/straight/build-27.1/emacsql-sqlite/sqlite/emacsql-sqlite
during GIMPLE pass: fre
/home/wang1zhen/.emacs.d/.local/straight/build-27.1/emacsql-sqlite/sqlite/sqlite3.c: In function ‘sqlite3BitvecSet’:
/home/wang1zhen/.emacs.d/.local/straight/build-27.1/emacsql-sqlite/sqlite/sqlite3.c:207609:1: internal compiler error: Segmentation fault
207609 | SQLITE_API const char *sqlite3_sourceid(void){ return SQLITE_SOURCE_ID; }
       | ^~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
```

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
 of 2021-03-28, modified by Debian
- Framework: Doom
- Org: Org mode version 9.5 (9.5-b83ae59 @ /home/wang1zhen/.emacs.d/.local/straight/build-27.1/org/)
- Org-roam: 2.0.0

Thanks for your help.

**Comment by jethrokuan** [comment]
I'd recommend changing your version of gcc, or using clang instead. But do file an issue to [emacsql](https://github.com/skeeto/emacsql/), I'm sure they're more equipped to address what you've faced.

**Comment by wang1zhen** [comment]
> 
> 
> I'd recommend changing your version of gcc, or using clang instead. But do file an issue to [emacsql](https://github.com/skeeto/emacsql/), I'm sure they're more equipped to address what you've faced.

Thank you for your help, after I switched to clang instead of gcc, the compiling problem seem to be resolved. I shall report the issue to emacsql as well. Yet, I encountered another issue, when I tried to add a node with `org-roam-node-find`, there is a error message of `org-id-add-location: Wrong type argument: hash-table-p, nil`, and I am not switched to the new node buffer, how can I deal with it?

**Comment by Wetlize** [comment]
Try following steps from https://github.com/org-roam/org-roam/issues/1700#issuecomment-889116709, it should help with this problem.

**Comment by wang1zhen** [comment]
Thank you, it did help. Closing the issue for now.

**Comment by jonathanabennett** [comment]
> I'd recommend changing your version of gcc, or using clang instead. But do file an issue to [emacsql](https://github.com/skeeto/emacsql/), I'm sure they're more equipped to address what you've faced.

How would I switch to clang? I'm having the same issue.
