### ISSUE TITLE
Early custom hooks to `org-roam-capture-new-node-hook` prevent `--insert-refs` being added

### ISSUE THREAD

**Issue by meliache** [org-roam/org-roam#1729]
I configure emacs via `use-package` and prefer to define all my hooks via the `:hook` keyword. So I added some hooks to `org-roam-capture-new-node-hook`:

``` emacs-lisp
(use-package org-roam
   :hook
   (org-roam-capture-new-node . my/journal-habit-done-after-journal-capture)
   (org-roam-capture-new-node . my/org-set-created-property)
   ...)
```

However, this resulted in a bug where the `ROAM_REFS` property was never set. I found out that this is because this hook is initialized with `defvar` with an initial value in `org-roam-capture.el`:

``` emacs-lisp
(defvar org-roam-capture-new-node-hook (list #'org-roam-capture--insert-ref)
  "Normal-mode hooks run when a new Org-roam node is created.
The current point is the point of the new node.
The hooks must not move the point.")
```

However, the hook is already non-nil due to the prior `:hook` definition, so `defvar` isn't adding the binding in my case any more.

This can be worked around by adding the hooks only after `org-roam-capture` is loaded, but maybe there is a better way.

I first [reported](https://orgroam.slack.com/archives/C011XLMELUB/p1627660336000700?thread_ts=1627600684.051300&cid=C011XLMELUB) this in the `org-roam-bibtex` slack channel because I initially thought this is a bug with org-roam-bibtex. Its author @myshevchuk replied:

> In fact, it may be indeed considered a bug of Org-roam. From add-hook docstring:
> ``` emacs-lisp
> HOOK should be a symbol, and FUNCTION may be any valid function.  If
> HOOK is void, it is first set to nil.  If HOOK's value is a single
> function, it is changed to a list of functions.
> ```
> So the package should ideally take care of properly setting its own hooks like this:
> ``` emacs-lisp
> (defvar org-roam-capture-new-node-hook nil)
> (add-hook 'org-roam-capture-new-node-hook ...)
> ```
> instead of
> ``` emacs-lisp
> (defvar org-roam-capture-new-node-hook ...)
> ```
But so far I haven't seen any code where his suggestion is implemented, so I'm not so sure about that, but I don't know best practices for emacs hooks either.

**Comment by Wetlize** [comment]
This should be fixed now with 2d8dc8e31b8f542b9baa9e58d1d427a315203912 and https://github.com/org-roam/org-roam-bibtex/commit/c13a05b2c855ba1516241d8a1de33bf2c689d6e4, so I'm closing this. You can post here if this isn't the case, in which case it'll be reopened.
