### ISSUE TITLE
org-roam-node-find adds whitespace to titles

### ISSUE THREAD

**Issue by vallon** [org-roam/org-roam#1735]
### Description

After upgrading to v2, I found my shortcut to org-roam-find-file was broken because the function disappeared.  I seem to find a replacement in org-roam-node-find.

However, the actual input string that it uses contains a lot of whitespace (seemingly an entire line).

I traced it down to the fact that it is using org-roam-node-display-template to generate its completion strings.  However, it is odd that the completion would be "title   #tag".  So, it seems to be done on purpose, but it is odd.

Or, maybe there is a better alternative to v1's org-roam-find-file than org-roam-node-find.

#### Steps to Reproduce

WIth a node with title "test":  M-x org-roam-node-find tes TAB.  Completion fills in "test{lots of spaces}".

Repl:

```
(org-roam-node-title (car (org-roam-node-list)))
"Channels"
(org-roam-node-title (cdr (car (org-roam-node--completions))))
"Channels"
(substring-no-properties (car (car (org-roam-node--completions))) nil nil
"Channels                                                                                  "
```

#### Backtrace

None

#### Expected Results

Completion (input) by title, not display-format.

#### Actual Results

Completion has lots of noise.

### Environment

Can't cut-paste.  GNU emacs 27.1, org 9.4.6 (9.4.6-g604bfd), org-roam 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/1d03f87 (master @ 8/2 21:37)

**Comment by Wetlize** [comment]
Do you use the default Emacs completion interface? No package like vertico/selectrum/ivy/helm etc? Anyway, you can simply change `org-roam-node-display-template` to what you need (see its docstring). Here some examples:
```emacs-lisp
;; This would only display the title, without any whitespaces
(setq org-roam-node-display-template "${title}")

;; This would display title and tags without of extra whitespace
(setq org-roam-node-display-template "${title} ${tags}")
```

**Comment by ebwb** [comment]
This got in my way when first learning org-roam (I'm new to it, even since v2). When I had two node names, one being a substring of another, I'd have to add a space after the smaller node name in order to get the tab-complete to work. Otherwise, if I only had the substring on an `org-roam-node-insert`, I'd be taken to a fresh node with the same name rather than insert the already existing node.

I use the default Emacs completion interface.

**Comment by vallon** [comment]
My completion-styles is '(basic partial-completion emacs22), which is the default for my emacs.

Changing org-roam-node-display-template to "${title}" makes the completion behave as I expect, thanks.
