### ISSUE TITLE
emacsql-sqlite-ensure-binary: No EmacSQL SQLite binary available, aborting (windows 10/11)

### ISSUE THREAD

**Issue by pinacle2000** [org-roam/org-roam#1736]
### Description
I updated my org roam v1 to v2 and got the same issue as in #1718, as describled in title. I checked the el files and found it requires "emacsql-sqlite.exe", which is not in my file system.

When I use v1, I installed sqlite binary for windows e.g. by "scoop install sqlite", and it has been working well. 

Is there a way to find the binary of emacsql-sqlite.exe somewhare? Or any detailed steps on how to compile to get it?

**Comment by jethrokuan** [comment]
You can try referring to this: https://github.com/nobiot/emacsql-sqlite.exe

**Comment by pinacle2000** [comment]
> You can try referring to this: https://github.com/nobiot/emacsql-sqlite.exe

Thanks! It works and I need to move on to coming issues on running org-roam-migrate-wizard, i.e. it changes noting on my existing v1 notes.

**Comment by roiholtzman** [comment]
I have the same error. I just migrated to v2. I am running on Mac, with doom emacs.
I don't know how to solve the issue.

**Comment by roiholtzman** [comment]
The problem was that my gcc was not broken.
I had to update it using the command 
```
xcode-select --install
```
Then everything worked fine.
(Note that I had to remove the my `org-roam-directory`.bak, because otherwise the migration would not work.
