### ISSUE TITLE
Symbol’s value as variable is void: org-roam-slug-trim-chars

### ISSUE THREAD

**Issue by xiaolaoc** [org-roam/org-roam#1742]
### Description
when the org-roam-capture-templates contain ${slug}, if I use org-roam-node-find or org-roam-node-insert, I can not create a new node, it shows the error above

this is my org-roam-capture-templates
'(
	      ("d" "default" plain
	       "%?"
	       :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
				  "#+TITLE: ${title}\n#+STARTUP: overview\n#+filetags: \n- sources ::\n")
	       :Unnarrowed t)

for example I create a node named by "MacOS", it shows bug as follow

<img width="691" alt="1" src="https://user-images.githubusercontent.com/20012636/128512458-d2125d9d-5cb6-437b-b93e-c4aef2798fdc.png">
<img width="958" alt="2" src="https://user-images.githubusercontent.com/20012636/128512460-76ff4b65-0592-4d5f-bb90-5bfb40ef7613.png">

if i change "%<%Y%m%d%H%M%S>-${slug}.org" to others, like "%<%Y%m%d%H%M%S>-${title}.org"
then I can create the new node ""MacOS"
![image](https://user-images.githubusercontent.com/20012636/128512968-824af132-ac42-4f09-bb76-44e1c547cfc0.png)

**Comment by Wetlize** [comment]
Are you sure you're running v2 and v1? `org-roam-slug-trim-chars` doesn't exist in v2, but does exist in v1. This could be a stale byte code, so you might need to recompile the package.

**Comment by xiaolaoc** [comment]
> Are you sure you're running v2 and not v1? `org-roam-slug-trim-chars` doesn't exist in v2, but does exist in v1. This also can be stale byte code that was leftover from v1, so you might need to recompile the package.

thanks, after I reinstall the package, it worked

**Comment by knl** [comment]
I had the same problem, and I copied the code from https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2#overriding-the-slug-function -- maybe that page needs an update, since it references `org-roam-slug-trim-chars`.
