### ISSUE TITLE
org-roam file not playing well with company

### ISSUE THREAD

**Issue by OrionRandD** [org-roam/org-roam#1743]
After I installed org-roamV2, I am unable to get company to suggest words for completing them with TAB.
If I open an org-roam file and start typing, it only suggests file names from the database...

**Comment by Wetlize** [comment]
That's sounds like your configuration for company doesn't do what you want it to. Org-roam provides its completions using `completing-at-point`; with company this will be triggered by `company-capf` backend. See `company-backends` and setup them the way how you need them for `org-mode` buffers, e.g.
```emacs-lisp
(add-hook 'org-mode-hook #'my-org-setup-company-h)
(defun my-org-setup-company-h ()
  (setq-local company-backends '(:separate company-dabbrev company-capf)))
```

**Comment by OrionRandD** [comment]
> That sounds like your configuration for company doesn't do what you want it to. Org-roam provides its completions using `completing-at-point`; with company this will be triggered by `company-capf` backend. See `company-backends` and setup them the way how you need them for `org-mode` buffers, e.g.
> 
> ```emacs-lisp
> (add-hook 'org-mode-hook #'my-org-setup-company-h)
> (defun my-org-setup-company-h ()
>   (setq-local company-backends '(:separate company-dabbrev company-capf)))
> ```

thx for trying to help.
Actually, my org-roam confing was kind of messed.
I have found this one 
https://github.com/jethrokuan/dots/blob/master/.doom.d/config.el#L375
and it did the trick for me.
The only down side is that, it creates a  "~/org-roam"  directory instead of obeying what I would like to be.
here:
(setq org-roam-directory (file-truename "~/org/deft-notes/")

**Comment by Wetlize** [comment]
`file-truname` won't automatically interpolate environment variables in strings. Just use `(file-truename "~/your-path/")` instead.

**Comment by OrionRandD** [comment]
> `file-truname` won't automatically interpolate environment variables in strings. Just use `(file-truename "~/your-path/")` instead.

thx  :)
