### ISSUE TITLE
Latex preview feature default in *org-roam* buffer in v2```

### ISSUE THREAD

**Issue by hokten** [org-roam/org-roam#1745]
```
(add-to-list 'org-roam-buffer-prepare-hook (lambda () (org--latex-preview-region (point-min) (point-max))) t)
```

should do the trick.

These are all temporary solutions, we'll consider all these small details in the side-buffer revamp.

_Originally posted by @jethrokuan in https://github.com/org-roam/org-roam/issues/1054#issuecomment-677644685_

**Comment by jethrokuan** [comment]
See https://github.com/org-roam/org-roam/issues/1867#issuecomment-979732164
