### ISSUE TITLE
v2 links in headings cause backlink buffer failure

### ISSUE THREAD

**Issue by cycomanic** [org-roam/org-roam#1746]
### Description

I just converted my org-roam files from v1 to v2 and noticed an issue with my backlink buffers. Essentially they would only display part of the backlinks. I traced this back to backlinks from headings, which cause a failure when the buffer is generated 

#### Steps to Reproduce

Create two files:

File 1:
```
:PROPERTIES:
:ID:       86fd963b-fc08-4515-ac0c-bdb84b8fad46
:END:
#+title: example1

Some test text.
```

File 2:
```
:PROPERTIES:
:ID:       f0749638-2356-4eed-8109-82a870170039
:END:
#+title: example2

More test text, here I'm linking back to [[id:86fd963b-fc08-4515-ac0c-bdb84b8fad46][example1]].

* This is a test heading
** A subheading linking to [[id:86fd963b-fc08-4515-ac0c-bdb84b8fad46][example1]]
some more text

* Another heading
- A third link to [[id:86fd963b-fc08-4515-ac0c-bdb84b8fad46][example1]]
```

When opening the example1 the following error is generated:
`Error in post-command-hook (org-roam-buffer--redisplay-h): (wrong-type-argument char-or-string-p (1 236 #("some more text" 0 14 (line-prefix #("    " 0 4 (face org-indent)) wrap-prefix #("    " 0 4 (face org-indent))))))`

and the last text in the backlink buffer is `example2 (This is a test heading)` So it stops generating backlinks after the subheading containing a link.

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26

using doom.

**Comment by Wetlize** [comment]
This was already fixed a while ago, e.g. see #1730. With Doom you need to either, pin the package to a different commit, unpin it or request Doom to bump the package.

**Comment by cycomanic** [comment]
Thanks, somehow I missed this when searching previous bugs. Closing.
