### ISSUE TITLE
Org-roam-dailies not loading with move of org-roam-dailies.el to extensions folder

### ISSUE THREAD

**Issue by arozbiz** [org-roam/org-roam#1748]
### Description

A recent [commit](https://github.com/org-roam/org-roam/commit/2d8dc8e31b8f542b9baa9e58d1d427a315203912) moved some org-roam .el files, including `org-roam-dailies.el`, to a new `extensions` subdirectory. This causes problems using org-roam-dailies functionality, at least when using a standard `(use-package 'org-roam)` installation. First, you now to need to explicitly include `(require 'org-roam-dailies)` (which is fine, but should be documented). But the bigger problem is that the `extensions` subdirectory isn't automatically added to `load-path`, so you also need to do something like `(add-to-list 'load-path "/home/alan/.emacs.d/elpa/org-roam-20210808.603/extensions/")`. But the problem with this is that this will break every time org-roam is updated, because the folder name will change.

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4)
 of 2021-07-05
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-12-gdcc3a8-elpaplus @ /home/alan/.emacs.d/elpa/org-plus-contrib-20210802/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by Wetlize** [comment]
Also see https://github.com/org-roam/org-roam/pull/1724#issuecomment-894799473. Should be fixed when the MELPA recipe will be updated.

**Comment by arozbiz** [comment]
Thanks. How do I know when the MELPA recipe is updated?

**Comment by Wetlize** [comment]
I'll notify in this issue.

**Comment by Wetlize** [comment]
Should be fixed now. The latest build log for the package on MELPA now has all the files. I'm closing this, but you can post here if the issue persist.
