### ISSUE TITLE
Documentation build is broken

### ISSUE THREAD

**Issue by spwhitton** [org-roam/org-roam#1749]
Hello,

I was looking into updating the Debian packaging of Org-roam but there are a lot of broken links which means the docs don't build.  These are the commands we run to the build the docs:

    rm -f doc/org-roam.texi
    make -C doc texi
    make -C doc info html-dir

But we get numerous errors of this form:

    Unable to resolve link: "id:70083bfd-d1e3-42b9-bf83-5b05708791c0"

Thanks.

**Comment by jethrokuan** [comment]
Is there any reason you're removing the texi file before rebuilding though? The texi is exported using additional Org plugins (like `ox-texinfo+`), so your build process will result in a manual that is different (no function index, no formatted functions/variable docs etc.)

**Comment by spwhitton** [comment]
@jethrokuan thanks for the fix.  Debian tries to rebuild everything from source rather than relying on pregenerated files wherever possible, because this enables us to be confident that we're actually shipping the preferred form for modification for everything in our archive, and it also tends to uncover bugs -- like these broken links!  We have ox-texinfo+ in Debian, and it looks like we do have the function index included in the docs we install, at least for Org-roam 1.2.3.
