### ISSUE TITLE
`org-roam-db-autosync-mode` not found

### ISSUE THREAD

**Issue by phye** [org-roam/org-roam#1761]
### Description
`org-roam-db-autosync-mode` function is not found
#### Steps to Reproduce
1. install and configure org-roam 2.0.0
```
(use-package org-roam
      :ensure t
      :custom
      (org-roam-directory (file-truename "~/ws/OrgNotes/roam"))
      :bind (("C-c n l" . org-roam-buffer-toggle)
             ("C-c n f" . org-roam-node-find)
             ("C-c n g" . org-roam-graph)
             ("C-c n i" . org-roam-node-insert)
             ("C-c n c" . org-roam-capture)
             ;; Dailies
             ("C-c n j" . org-roam-dailies-capture-today))
      :config
      ;; If using org-roam-protocol
      (require 'org-roam-protocol))
(setq org-roam-v2-ack t)
```
2. Invoke `org-roam-db-auto-sync-mode` per guide
``` M-x 
org-roam-db-auto-sync-mode
```
org-roam-db-auto-sync-mode not found

#### Backtrace
None

#### Expected Results

There're such command

#### Actual Results

There's not

### Environment

- Org-roam commit: https://github.com/org-roam/org-roam/commit/3a78422a099261317d369be58947f4d4b3df1da3

**Comment by Wetlize** [comment]
`org-roam-db-auto-sync-mode` was added recently with 5dce6261a2a45798cdf0c65371b76c83dd5b1de6. Your `org-roam` on the other hand is pretty old (3a78422a099261317d369be58947f4d4b3df1da3). So either, update the package or use `org-roam-setup` instead.

**Comment by phye** [comment]
Thanks for the quick response!
I was reading the [doc](https://www.orgroam.com/manual.html#Introduction), which says that the doc is for version 2.0.0 (which the commit 3a78422 is on), hence the question :)
![image](https://user-images.githubusercontent.com/3255399/128871642-d5f4f268-ccb0-4f78-b176-f26742c340b7.png)

I'll use the latest one from melpa. Thanks again.

**Comment by Wetlize** [comment]
No probs. The new "official" release should be cut soon™ after some other minor things will be done.
