### ISSUE TITLE
Cannot org-roam-buffer-toggle a node back on right after toggling it off

### ISSUE THREAD

**Issue by swang251** [org-roam/org-roam#1770]
### Description
Staying in the same node, I can not org-roam-buffer-toggle a node back on right after toggling it off. It works only if I switch to another node.

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam-find-file` and open a node
3. Run `org-roam-buffer-toggle` to display the backlinks
4. Run `org-roam-buffer-toggle` to close the backlinks window
5. Run `org-roam-buffer-toggle` again

#### Expected Results

The backlink buffer would be displayed

#### Actual Results

The backlink buffer wouldn't display, unless we switch to a new node.

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6)
 of 2021-04-17
- Framework: Spacemacs
- Org: Org mode version 9.4.6
- Org-roam: 2.0.0

**Comment by Wetlize** [comment]
Can't reproduce this. What commit are you on? Can you reproduce this with a minimal config?

**Comment by swang251** [comment]
I was using Org-roam [commit](https://github.com/org-roam/org-roam/commit/8a21131d9f5f6a136bf355b2d3f3f1c765f0eddd) but I couldn't repeat it either with a minimal Emacs config. Thank you for following this up. I would try the two default configurations of spacemacs later.

**Comment by swang251** [comment]
Hi Wetlize, I can't replicate the problem anymore after reinstalling the spacemacs (unfortunately I forgot to backup the old .emacs.d). Hope I could run into it again but I'll close the PR and issue for now.
