### ISSUE TITLE
Support 0 width entries in `org-roam-node-display-template`

### ISSUE THREAD

**Issue by mohkale** [org-roam/org-roam#1775]
### Brief Abstract
I'd like you to be able to hide entries in `org-roam-node-display-template` by setting their width to 0. This allows us to still search based on them but prevents them taking up screen space.

### Long Description
Before org-roam-v2 used to attach the tags of a node to the formatted entry with the display none property so that even if the tags weren't in `org-roam-node-display-template` you could still search with them in completing-read. Recent changes seem to have invalidated this feature so I'd like org-roam to support it directly.

Here's is what my configuration for org-roam display-template currently is.

```lisp
(use-package org-roam
  :custom
  (org-roam-node-display-template "${title}")
  (org-roam-node-annotation-function #'org-roam-annotate-tag+)
  :commands (org-roam-annotate-tag+)
  :config
  (defun org-roam-annotate-tag+ (node)
    (let ((tags (org-roam-node-read--tags-to-str (org-roam-node-tags node))))
      (unless (string-empty-p tags)
        (concat
          " "
          (propertize " " 'display `(space :align-to (- right ,(+ 1 (length tags)))))
          tags)))))
```

![Screenshot_20210815_161118](https://user-images.githubusercontent.com/23294780/129483232-c66e1f3c-0608-4e24-8c13-faa2941f7bc3.png)

Because I already display tags using org-roam annotation function I don't want to have switch to using the template instead so I'd rather just attach the tags after the node title I.E. `(setq org-roam-node-display-template "${title} ${tags:0}")`

### Proposed Implementation (if any)
```diff
diff -u --label /home/mohkale/.cache/emacs/straight/repos/org-roam/org-roam-node.el --label \#\<buffer\ org-roam-node.el\> /home/mohkale/.cache/emacs/straight/repos/org-roam/org-roam-node.el /tmp/buffer-content-nffqoX
--- /home/mohkale/.cache/emacs/straight/repos/org-roam/org-roam-node.el
+++ #<buffer org-roam-node.el>
@@ -485,7 +485,7 @@
            (setq field-width (string-to-number field-width))
            (let ((display-string (truncate-string-to-width
                                   field-value
-                                  (if (> field-width 0)
+                                  (if (>= field-width 0)
                                       field-width
                                     (- width (cdr fmt)))
                                   0 ?\s)))
```

### Please check the following:

- [X] No similar feature requests

**Comment by Wetlize** [comment]
I think @jethrokuan already works on an alternative way to do it in #1723. So you would only need to specify display templates that will be relevant to the actual display (e.g. just "${title}"), instead of setting them to 0 width, and then you would be able to write something like `#[tag]` or `t:[todo keyword]` to narrow down by queries.

**Comment by mohkale** [comment]
@Wetlize 

Huh, that looks kinda cool.  If it's alright with you I don't mind waiting for that to be merged in before addressing this issue. :smile:.

**Comment by Wetlize** [comment]
Yeah, no problems. I feel like something like this is up to Jethro, so I wouldn't close it anyway.

**Comment by jethrokuan** [comment]
This should be fixed in latest master I think, feel free to reopen if not the case.
