### ISSUE TITLE
`org-roam-node-find` always creates a new node

### ISSUE THREAD

**Issue by tramzee** [org-roam/org-roam#1778]
### Out of the Box org-roam-node-find always creates new node

After installing org-roam on my emacs 27.1 (ubuntu 20.04) everything seems to work as advertised. The one exception is that any function that attempts to find or create a new org-roam node (e.g. `org-roam-node-find` and `org-roam-node-insert`) ends up *always* creating a new node even when the requested node already exists.

I can get things to work (apparently correctly) if I monkey-patch the `org-roam-node--to-candidate` like this:
````
(defun org-roam-node--to-candidate (node)
    "Return a minibuffer completion candidate given NODE."
    (let ((candidate-main (org-roam-node--format-entry node (1- (frame-width))))
          (tag-str (org-roam--tags-to-str (org-roam-node-tags node))))
      (cons (propertize (concat (string-trim candidate-main)
                                (propertize tag-str 'invisible t))
                        'node node)
            node)))
````
This is the same as the original `org-roam-node--to-candidate` except that I have put a `string-trim` around the `candidate-main` value. `candidate-main` comes back as a string that is padded with spaces out to the width of my emacs frame. So if I have a node called "MyNode", the `candidate-main` value is something like (note the extra spaces after 'MyNode')
````
"MyNode                                                            "
````
where the number of spaces after 'MyNode' is dependent on the width of my emacs frame
This does not match the `"MyNode"` string that is typed in in the minibuffer  'Node:' prompt and therefore creates the new node.

#### Steps to Reproduce

1. Install org-roam from melpa stable
2. Set the org-roam-directory to "~/org/roam"
3. `M-x org-roam-node-find`
4. Type the name of a new node ("MyNode")
5. Enter some text in the new node and save the node
6. `M-x org-roam-node-find`
7. Type (or complete) the name of the new node you just created ("MyNode")
8. Instead of going to the existing node it creates another "MyNode" node (different timestamp on the filename)

#### Expected Results
I expect `org-roam-node-find` to put me into the previously created node

#### Actual Results
I am always presented with a new node

### Environment
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2020-08-18
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-gab9f2a @ /home/tramsey/.emacs.d/elpa/org-9.4.6/)
- Org-roam: 2.0.0

**Comment by nobiot** [comment]
This should be the same issue as [https://org-roam.discourse.group/t/cant-open-node-if-another-nodes-name-starts-with-the-same-string/1890?u=nobiot](this)

**Comment by rngesus-wept** [comment]
It would be nice if the out-of-the-box behavior for `org-roam-node-display-template` did not assume the end user is using a vertical completion system. I encountered this problem as well and ended up just installing `vertico` before I realized what was happening. It's also very strange that you can get a new node by just by correcting the trailing whitespace generated by the display -- perhaps there should be a call to a trim function somewhere.

**Comment by nobiot** [comment]
@hraban 

> just going back to putting tags in front of the completions.

If displaying tags in front of the completion candidates fixes the issue on your end, you might like to customize `org-roam-node-display-template` to do so and see if it works for you. I use Vertico and get other attributes displayed. It works great.

**Comment by hjudt** [comment]
I am also using ido for all of my stuff, and I like I can see many selection candidates on not too many lines from the start. After I spent quite some time tweaking it and together with ido-flx it's very easy and fast to select the right candidates. It also has a feature called "virtual buffers" which can reopen files that I recently closed, which is really great, and I don't know whether other completion frameworks provide these. So far changing org-roam-node-display-template accordingly seems to work, so I'll try this and otherwise maybe try vertico and see how I can get accustomed to vertical completion modes.

**Comment by Inkbottle007** [comment]
I'm in node `org_protocol_part_two`. In it, I type `org_protocol_part_three`. There is no existing node of that name at that point. I select the string and do `M-x org-roam-node-insert`. I get the new node created in a capture buffer as expected. I do `C-c C-c` to finalize the creation. (Note that my completion framework is `vertico`.)
So at that point I do `C-c n f`, type `org_proto`, hit completion key (`tab`), and up-down-arrow-select `org_protocol_part_three`.
(Note that what I really get in the minibuffer is a white-spaces-right-padded version of `org_protocol_part_three`. Specifically, the total length is 88. `M-: (frame-width)` returns `92`. `grep 88 ~/.emacs.d/init.el` returns nothing.)
So I do `C-c n f` as described above and I do get into the already existing node, as expected.
Now I do just as I did initially to create the forward link, but this time for a backward link.
I type in node `org_protocol_part_three` the string `org_protocol_part_two`, select it, and call `M-x org-roam-node-insert`, and voila, I get a brand new node. Not what I expected.

When doing `C-c n f` and hit `tab` without prefix, I get the "and the completions are completely borked", described above on 20 Oct.

**Comment by Inkbottle007** [comment]
> This should be the same issue as this https://org-roam.discourse.group/t/cant-open-node-if-another-nodes-name-starts-with-the-same-string/1890?u=nobiot
> 
> A solution provided

Hum, interesting, let's try that. (In `*scratch*`):
```
(symbol-value 'org-roam-node-display-template)
"${title:*} ${tags:10}"

(setq org-roam-node-display-template "${title} ${tag}")
"${title} ${tag}"
```
Then I follow the steps for the back-link from selection described above and, (copied from `*Message*`):
```
Symbol’s function definition is void: org-roam-node-tag
```
(wow)

So `M-: (setq org-roam-node-display-template "${title}")`.
Back to the back-link from selection: this time it worked as expected.

Also when doing `C-n f c` and hitting `Tab`, the result is way less otherworldly.

I do use tags, but I guess I'll do without them for the time being.

**Comment by nobiot** [comment]
> Symbol’s function definition is void: org-roam-node-tag
Try "tags", plural. Not singular "tag".

**Comment by jethrokuan** [comment]
Closing with #2054.

**Comment by justinmakes** [comment]
Hey guys, I had the same issue but none of the solutions in here worked for me.

running "org-roam-db-sync" fixed it for me.
Also tried enabling "org-roam-db-autosync-mode" by passing a positive number to it as described in the docs. Doesn't seem to be working though. Have to manually update every time I make a new node.

**Comment by nilesjohnson** [comment]
> running "org-roam-db-sync" fixed it for me. Also tried enabling "org-roam-db-autosync-mode" by passing a positive number to it as described in the docs. Doesn't seem to be working though. Have to manually update every time I make a new node.

I'm having the same issue, with the same db sync behavior.  I see a few other hints of this kind of thing around the web, but no solution so far.  I'm using spacemacs with the [default setup](https://develop.spacemacs.org/layers/+emacs/org/README.html#org-roam-support).
