### ISSUE TITLE
non-interactive option for org-roam-node-insert for a new node entry

### ISSUE THREAD

**Issue by gberenfield** [org-roam/org-roam#1781]
### Brief Abstract

Please add an option to hook into org-roam-node-read from org-roam-node-insert to pass INITIAL-INPUT for node creation non-interactively.

### Long Description

I'm trying to convert old org-entries to org-roam and created a function that cuts an org-entry and uses an org-roam template with it's clipboard to create a new org-roam entry. This all works great but I still have to manually enter the org-roam node each time and would like to simply pass the Heading title as the "Node: " prompted input.

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
If you're creating them programmatically then why use `org-roam-node-read` at all? Just call `org-roam-capture-` directly, with the node:

```
(org-roam-capture- :node (org-roam-node-create :title heading-title)
                   :templates templates)
```

**Comment by gberenfield** [comment]
I did try that previously and it works fine in and of itself. What I failed to mention is I like org-roam-node-insert's behavior to actually immediately insert a link to the new node.

So I'm replacing my individual org entries with links to org-roam files.

**Comment by jethrokuan** [comment]
> What I failed to mention is I like org-roam-node-insert's behavior to actually immediately insert a link to the new node.

Then pass in the `'insert-link` as props:

```
(org-roam-capture- :node (org-roam-node-create :title heading-title)
                   :templates templates
                   :props (list :insert-at (point-marker) :link-description heading-title :finalize 'insert-link))
```

**Comment by gberenfield** [comment]
Perfect, Thank you so much!
Closing
