### ISSUE TITLE
Enable user to add custom properties and prompts in capture templates to the file-level :PROPERTIES: drawer

### ISSUE THREAD

**Issue by yuuyins** [org-roam/org-roam#1783]
### Brief Abstract
Enable user to add custom properties and prompts in capture templates to the file-level `:PROPERTIES:` drawer.

### Long Description

On Org-roam v2, when capturing a new note, Org-roam automatically adds

    :PROPERTIES:
    :ID: 9e8d2f1f-526f-4281-8be0-b4193200595e
    :END:

but doesn’t enable the user to customize it through `org-roam-capture-templates` (at least doesn't seem to be documented). Thus, the user is unable to set on the template Org-roam properties like `:ROAM_ALIASES: %^{aliases}` or custom properties when capturing a new note. On Org-roam v1 the user was able to set for example aliases while capturing a new note because Org-roam recognized ROAM_ALIASES as `#+ROAM_ALIASES:`.

Adding a new properties drawer (which will result in the below) in the capture template doesn’t work. The same is true for `#+PROPERTY: ROAM_ALIASES alias`.

    :PROPERTIES:
    :ID: 9e8d2f1f-526f-4281-8be0-b4193200595e
    :END:
    
    :PROPERTIES:
    :ROAM_ALIASES: "doesn't work"
    :END:

P.S. Org-mode doesn’t support file-level template expansion for properties, i.e. `%^{ROAM_ALIASES}p` set on file-level doesn’t work.

### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
This works for me:

```
(setq org-roam-capture-templates
        '(("d" "default" plain
           "%?"
           :if-new (file+head "${slug}.org"
                              ":PROPERTIES:
:ROAM_ALIASES: %^{aliases}
:END:
#+title: ${title}\n")
           :immediate-finish t
           :unnarrowed t)))
```

**Comment by yuuyins** [comment]
Your example works for me. I was testing with

    (setq org-roam-capture-templates
          '(("t" "test" plain
             "
    :PROPERTIES:
    :ROAM_ALIASES: %^{aliases}
    :END:
    
    #+TITLE: ${title}
    
    %?
    "
             :if-new (file "${slug}.org"))))

Seem like I got the syntax wrong. Thanks for the example. I think it would be useful to have a similar example on the Org-roam docs. I could see into adding it myself.

**Comment by nazzacode** [comment]
this example diesnt work for me, instead I get: 

`:PROPERTIES:
:ID:       3d183a3a-572f-4e83-9dd2-891fc7274645
:END:
#+title: :PROPERTIES:
:ROAM_ALIASES:  test
:END:
#+title: Testing
`

Any ideas?

**Comment by mholson** [comment]
I can confirm that this method was working (possibly before commit https://github.com/org-roam/org-roam/commit/c3867619147175faf89ed8f3e90a1e67a4fd9655 ) AND I can also confirm that the method described above produces the same incorrect file header code as shown by @nazzacode.

@jethrokuan Can we open this issue up again?

**Comment by mholson** [comment]
@nazzacode I had the same problem as you (same incorrect output in the capture capture buffer). This started to occur at some point after I had this capture template working to include ROAM_ALIAS in the property drawer. 

Originally, I suspected an org-roam upgrade the cause, but it turns out it was the formatting of my config file. I now suspect the problem to be attributed to formatting the ifnew list on multiple lines, which resulted in the same incorrect capture buffer as you have shown in your comment. Including the list back on one line seemed to fix this for me.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I am sorry for warming this up.

In my special case it doesn't work. I opened a [reddit question](https://www.reddit.com/r/OrgRoam/comments/w3htuw/add_custom_properties_from_prompts_in_capture/) for that. Would be very nice if you could take a look on it.

**Comment by nazzacode** [comment]
@mholson Yes I recently discovered the same: that it was being triggered by some minor bug in my config file. So for anyone else having this issue, I would try debugging your config until you (hopefully) find the culprit.

**Comment by CyberFox001** [comment]
I think a few words in the documentation about how to define custom file properties in a capture template could help.
