### ISSUE TITLE
Point release?

### ISSUE THREAD

**Issue by spwhitton** [org-roam/org-roam#1784]
Would it be an appropriate time for a 2.0.1 release, or similar, containing recent fixes?

The context is that I'm trying to update Org-roam in Debian (and therefore Ubuntu, etc.) to v2+, but to do that I need to backport #1751 to the 2.0.0 release, otherwise the build fails.  That backport is a bit of a pain because the manual has changed quite a lot since then.  It is possible for me just to upload a snapshot of 'master' to Debian, but I'm not sure how stable 'master' is considered to be at the present time.

If you would prefer not to tag a new release, could you advise on the current status of 'master' -- perhaps there is a recent commit that it would be appropriate to snapshot?

Thanks!

**Comment by jethrokuan** [comment]
I've been meaning to cut a release, shall do it soon.

**Comment by jethrokuan** [comment]
Closed with #1792

**Comment by spwhitton** [comment]
Thanks for this.  Just waiting on Debian's magit maintainer to update magit-section and I'll be able to update org-roam :)
