### ISSUE TITLE
(setq org-roam-v2-ack t) doesn't work

### ISSUE THREAD

**Issue by notuntoward** [org-roam/org-roam#1789]
When emacs starts, I see a warning page from org-roam.  This one:

```
------------------------------------
WARNING: You’re now on Org-roam v2!
------------------------------------

<STUFF DELETED>

If you’ve gone through the migration steps (if necessary), and
know what you’re doing set ‘org-roam-v2-ack’ to ‘t’ to disable
this warning. You can do so by adding:

(setq org-roam-v2-ack t)

To your init file.
```

But `(setq org-roam-v2-ack t)` in my .emacs file doesn't disable this message if I put it in any of

- just above or after the the `(use-package org-roam ...)`
- within `(use-package org-roam ...)` :config
- within `(use-package org-roam ...)` :init

Here's an example that fails where I do all of them:

```
(setq org-roam-v2-ack t)

(use-package org-roam
  :custom
  (org-roam-directory (file-truename "~/tmp"))
  (org-id-method 'ts) ;; use timestamps for org-id
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n g" . org-roam-graph)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n h" . org-roam-capture)
         ([mouse-1] . org-roam-visit-thing)
         ("C-c n j" . org-roam-dailies-capture-today))
  :init
  (setq org-roam-v2-ack t)
  :config
  (setq org-roam-v2-ack t)
  (org-roam-db-autosync-mode)
  (require 'org-roam-protocol))

(setq org-roam-v2-ack t)
```

**Comment by jethrokuan** [comment]
With the config you provide, when you restart emacs the warning still shows?

**Comment by notuntoward** [comment]
Yes, I still get the warning after restarting Emacs.

**Comment by jethrokuan** [comment]
My guess is that something is loading org-roam before all of that, hard to say without your full emacs config. It is only necessary to put it in the `:init` block.

**Comment by notuntoward** [comment]
Thanks!  It was org-roam-bibtex, which I'd deleted from my config file, but which was still in .emacs.d/elpa.  

Whenever emacs restarted, a leftover and ancient customization continued starting org-roam-bibtex, and I guess that started org-roam without reference to my use-package statement.
