### ISSUE TITLE
`org-roam-complete-at-point` breaks when the symbol completed is nested between org links [org-roam v2]

### ISSUE THREAD

**Issue by egrefen** [org-roam/org-roam#1790]
### Description

When writing an org-roam document, it is a common practice (for me) to use `complete-symbol`/`completion-at-point` (via `M-TAB` on doom-emacs) in order to call `org-roam-complete-at-point` to expand the partial word I am writing into a link to an org-node. With `org-roam-completion-everywhere` I can do this quite quickly as I write.

However, I have noted since upgrading to org-roam v2, that completions fail (i.e. no match found) when the symbol being completed is in a block of text with org links (of any sort, i.e. matching the syntax `[[...]]`) anywhere on both sides of the symbol completed (i.e. situations matching the regex `.*\[\[.*\]\].*S*\[\[.*\]\].*` where S is the word I want to complete).

I suspect that one of the functions involved in the completion incorrectly parses the symbol in need of completion as a result of being nested between a `[[` on the left, and a `]]` on the right. Because when `org-roam-completion-everywhere` is not `t`, completion happens between `[[` and `]]` only, I suspect that the fault lies within the org-roam end of things, and that the parser incorrectly captures the context between the beginning of the left link and the end of the right link as the completion target, rather than the word the point is sitting on, but I am not proficient enough with elisp or emacs debugging to verify this.

#### Steps to Reproduce

1. Load emacs, verify that  `org-roam-completion-everywhere` is set to `t`
2. Open a new (or existing) `org-roam` buffer.
3. Assume there is some node with a name beginning with `P` (e.g. `Patrick`). Write/copy the following text into the buffer:
```org
Foo x P y bar
```
4. Place the point on the `P` and run `M-x completion-at-point`. Verify that this offers a completion list, or suggests `Patrick` as the only completion.
5. Edit/replace the tex above to read:
```org
Foo [[x]] P [[y]] bar
```
6. Place the point on the `P` and run `M-x completion-at-point`. Verify that this offers a completion list, or suggests `Patrick` as the only completion. Verify that the completion options are *not* presented, and that instead the message line reads `No matches`.

The problem is replicable for any attempted completion where the word being completed lies between two `[[...]]` links, for example in
```org
Foo [[x]] P [[y]] P
```
The first `P` can't be completed, but the second `P` can.

The problem persists across line breaks, so for example in 
```org
Foo [[x]] P 
[[y]] bar
```
the `P` on the first line can't be completed.

However, a double line break does not reproduce the issue, i.e. in
```org
Foo [[x]] P

[[y]] bar
```
the `P` on the first line *can* be completed.

#### Expected Results

In step 6, above, the completion should work as it does in step 4.

#### Actual Results

In step 6, above, the completion does not work as it does in step 4.

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin19.6.0, Carbon Version 162 AppKit 1894.6)
 of 2021-05-17
- Framework: Doom
- Org: Org mode version 9.5 (9.5-b83ae59 @ /Users/egrefen/.doom-emacs/.local/straight/build-27.2/org/)
- Org-roam: v2.0.0-73-gf29a770

**Comment by FinallyFinancialFreedom** [comment]
did this bug totally disabled org-roam completion? because i can not find roam node in completion list.

**Comment by egrefen** [comment]
No, it only disables completion within a specific scope (until the next line break), indicating a regex error.
