### ISSUE TITLE
Capture templates changed in v2: how do I include a ROAM-REFS property in my capture template?

### ISSUE THREAD

**Issue by thor314** [org-roam/org-roam#1791]
Updating my config for v2. I haven't been able to figure out how to add the ROAM-REFS property prompt through `org-roam-capture-templates`. My current looks like this.

```
  (setq org-roam-capture--file-name-default "<%Y-%m%-%d>-${slug}")
  (setq org-roam-capture-templates '(
       ("a" "article" plain "%?"
         :if-new (file+head "lit/article/%<%Y-%m-%d>-${slug}.org"
                   "#+title: ${title}\n")
                   :unnarrowed t)
       ("p" "paper" plain "%?"
         :if-new (file+head "lit/paper/%<%Y-%m-%d>-${slug}.org"
                   "#+title: ${title}\n")
                   :unnarrowed t)
       ))
```
I think I might need to do something with 
`"%^{ROAM_REFS}p"` which would add a prompt for the property, but there are no examples in the documentation of doing so.

**Comment by jethrokuan** [comment]
Please see https://github.com/org-roam/org-roam/issues/1783#issuecomment-900452202 for a sample, just s/alias/refs/

**Comment by thor314** [comment]
thanks!
