### ISSUE TITLE
Org-roam-migrate-wizard not working properly on windows

### ISSUE THREAD

**Issue by Hxppdv** [org-roam/org-roam#1794]
I Tried to migrate by running Org-roam-migrate-wizard, but got an error message (Query timeout error: "Query timed out", 30)
I think this may not be a very serious problem and is extremely likely to occur only on windows. Everything is working fine with the migration, but the org-roam.db file is not generated properly maybe because of the emacsql problem on windows. But I can run org-roam-db-sync manually to create org-roam.db.

**Comment by jethrokuan** [comment]
Yeah this seems to be a more pronounced problem on non-unix platforms, but it's mainly because many sql queries are run at once during the migration process.
