### ISSUE TITLE
Org-Roam does not register files with local variables in first line

### ISSUE THREAD

**Issue by pprevos** [org-roam/org-roam#1797]
### Description
Org-Roam does not recognise files that have [file variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html) specified on the first line. I use local file variables to set a local dictionary for my multi-lingual note collection.

#### Steps to Reproduce
1. Pick a random Org-Roam file
2. Add a file variable as the first line, e.g. `-*- mode: org; ispell-local-dictionary: "nederlands" -*-`
3. Save the file and refresh the Org-Roam database. The file is no no longer registered.

#### Backtrace
No error is thrown. 

#### Expected Results
Files with a header line are registered in he Org-Roam database as this is standard Emacs functionality.

#### Actual Results
When the first line does not contain the phrase `:PROPERTIES:`, the file is not registered by Org-Roam. I registered this as a bug because file variables are part of base Emacs functionality.

#### Workaround
File variables can be defined at the end of the file, e.g.:

```
#+begin_export 
/* Local Variables:                      */
/* ispell-local-dictionary: "nederlands" */
/* End:                                  */
#+end_export
```

### Environment
- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-27
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4 @ /usr/share/emacs/27.2/lisp/org/)
- Org-roam: 2.1.0

**Comment by jethrokuan** [comment]
This is a requirement of Org-mode, not Org-roam. Try `org-id-get-create` on a file with the file variable on the first line, and you'll see that it creates a property drawer above it. If you think this is an issue, then you should file this upstream.

**Comment by pprevos** [comment]
Makes sense. I'll contact the Org mode developers.

**Comment by jethrokuan** [comment]
> Having said this, why does Org-Roam not recognise the properties drawer when it is not on the first line?

We just make the same assumptions that Org does, since we use Org's provided API.

**Comment by pprevos** [comment]
That makes sense. I have lodged the issue with Org mode. 

Thank for the fast response.

**Comment by rekahsoft** [comment]
Just wanted to note here that you can use file local variables in org, but if you have a document level properties block (like you will with org-roam), you need to use the alternative form for file local variables ([as described in the emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html)). For example, I use the following at the end of org-mode files where I need to use file-local variables:

```
* Local Variables                                                  :noexport:
Local Variables:
org-duration-format: '(special . h:mm)
End:
```
