### ISSUE TITLE
Tags are truncated in org-roam-node-find

### ISSUE THREAD

**Issue by mat-r** [org-roam/org-roam#1819]
When searching for nodes with `org-roam-node-find`,  the tags on the right of each item in the list seems to be truncated after quite few characters.

See the screenshot below:
<img width="647" alt="Screenshot 2021-08-28 at 22 39 19" src="https://user-images.githubusercontent.com/36885389/131230633-89389d40-1d67-4a86-a919-c618cfc80bd0.png">

The node has 3 tags: one, two, three. If I search a node with the tag `two`, it looks like it is working but the item in the result list shows only `one` and `three` truncated -> `thre`. I think two is not displayed because the tags are displayed sorted in alphabetical order and are limited to very few characters.

Am I correct? Is it intentional to have this limitation? If not, would it be possible to increase the number of characters to display for tags?
A limitation must be used anyway but at least I think it would be nice to truncate the tag list only after a full word.

**Comment by Wetlize** [comment]
You can configure the next variable to adjust the display to your own needs:

https://github.com/org-roam/org-roam/blob/48a5d017267afb1663a89b619cb37b069b5a283d/org-roam-node.el#L39-L65

**Comment by mat-r** [comment]
If I understood well, I can for example increase the tag length like this (from 10 to 50):
```emacs-lisp
(defcustom org-roam-node-display-template 
   "${title:*} ${tags:50}" 
   "Configures display formatting for Org-roam node. 
 Patterns of form \"${field-name:length}\" are interpolated based 
 on the current node. 
  
 Each \"field-name\" is replaced with the return value of each 
 corresponding accessor function for `org-roam-node', e.g. 
 \"${title}\" will be interpolated by the result of 
 `org-roam-node-title'. You can also define custom accessors using 
 `cl-defmethod'. For example, you can define: 
  
   (cl-defmethod org-roam-node-my-title ((node org-roam-node)) 
     (concat \"My \" (org-roam-node-title node))) 
  
 and then reference it here or in the capture templates as 
 \"${my-title}\". 
  
 \"length\" is an optional specifier and declares how many 
 characters can be used to display the value of the corresponding 
 field. If it's not specified, the field will be inserted as is, 
 i.e. it won't be aligned nor trimmed. If it's an integer, the 
 field will be aligned accordingly and all the exceeding 
 characters will be trimmed out. If it's \"*\", the field will use 
 as many characters as possible and will be aligned accordingly." 
   :group 'org-roam 
   :type  'string)
```

I added it at the end of my init.el but it does not seem to have any effect. Am I doing something wrong?

**Comment by jethrokuan** [comment]
In Emacs you use `setq` or `M-x customize-variable` to alter the value of variables. So you should be doing:

```
(setq org-roam-node-display-template "${title:*} {tags:50}")
```

instead.

**Comment by mat-r** [comment]
It works indeed. I just had to add a dollar sign before the opening bracket of "tags".

Thanks!

**Comment by cdlm** [comment]
This feature (customizing the appearance of nodes in the minibuffer) looks to me like it's…
- reinventing `marginalia`
- conflating the node itself, the metadata used in the query, and how all that's displayed visually (being unable to match on a tag because it's truncated out of the minibuffer is proof of that)

I understand having `org-roam` depend on `marginalia` might be a problem, but surely there's a way to design that dependency in a clean way?

**Comment by mat-r** [comment]
Just for information, even if a tag is displayed truncated, it will still match the tag.
E.g. here I set the tags to be display with 5 characters maximum:
<img width="638" alt="Screenshot 2021-08-30 at 09 16 57" src="https://user-images.githubusercontent.com/36885389/131300905-4eb73748-715d-4da2-9a38-4cfaa08aa735.png">
We can see that it is matching.
And if I enter a different last letter which is a non-existent tag, the node list become empty:
<img width="638" alt="Screenshot 2021-08-30 at 09 20 02" src="https://user-images.githubusercontent.com/36885389/131301236-a7f269e7-392a-4427-a8e3-60750602c67a.png">
This is in my opinion a valid behaviour.
