### ISSUE TITLE
Org-roam (V2) does not do, what I do expect

### ISSUE THREAD

**Issue by algon-ns** [org-roam/org-roam#1830]
### Description
I'm confused, if I do something wrong, my configuration is wrong, or if it's an error?
#### Steps to Reproduce

creating aa.org by C-c n f
creating bb.org by C-c n f
creating cc.org by C-c n f
by now, everything is OK

opening bb.org by dired
set link to aa.org by C-c n d i
emacs opens buffer with aa.org
C-c C-c sets link in bb.org and closes buffer with aa.org

**but** now I have two different files with <date/time>-aa.org in my org-roam directory.

### Environment
- Emacs: GNU Emacs 28.0.50 (build 10, aarch64-apple-darwin20.6.0, NS appkit-2022.60 Version 11.5.2 (Build 20G95))  of 2021-08-31
- Framework: 
- Org: Org mode version 9.4.6 (9.4.6-g8df3e2 @ /Users/niels/.emacs.d/straight/build/org-agenda/)
- Org-roam: v2.1.0-15-ga8a36a4

My org-roam configuration:
(setq org-roam-v2-ack t)
(setq org-roam-verbose t)
(setq org-roam-db-location "~/org/roam/.database/org-roam.db")
(setq org-roam-dailies-directory "daily/")

(use-package org-roam
  :straight t
  :custom
  (org-roam-directory (file-truename "~/org/roam"))
  (org-roam-dailies-capture-templates
    '(("d" "default" entry "* %<%H:%M>: %?"
    :if-new (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))))    
  (org-roam-node-display-template "${title:*} ${tags:40}")
  :init
  (add-to-list 'display-buffer-alist
               '("\\*org-roam\\#"
                 (display-buffer-in-side-window)
                 (side . right)
                 (slot . 0)
                 (window-width . 0.33)
                 (window-parameters . ((no-other-window . t)
                                       (no-delete-other-windows . t)))))
  (setq org-roam-v2-ack t)
  (org-roam-db-autosync-mode))

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by nobiot** [comment]
what's your completion framework? Ido?

**Comment by algon-ns** [comment]
Yes, it’s the one I think I use by:   (setq org-completion-use-ido t)
But that’s a little unclear as I just now load some other……
I try to figure it out…
mvh
Niels
 <applewebdata://F15C12E6-2878-49C4-97BF-24170EBE46FA>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45 4052 2789>+45 4052 ***@***.*** ***@***.***>
Ultra posse nemo obligatur.

**Comment by nobiot** [comment]
It's very likely the same issue as this [one discussed on Discourse
](https://org-roam.discourse.group/t/cant-open-node-if-another-nodes-name-starts-with-the-same-string/1890)

Try something like this:
```
(setq org-roam-node-display-template "${title} ${tag}")
```

Alternatively, if you use a vertical completion framework, such as Vertical Icomplete, Vertico, Selectrum, Ivy, or Helm, you will not have the same issue -- provided my assumption is correct.

**Comment by nobiot** [comment]
Also I think [this issue](https://github.com/org-roam/org-roam/issues/1778) is the same problem; same solution.
