### ISSUE TITLE
Am I blind or is org-roam-db-query gone? (V2) 

### ISSUE THREAD

**Issue by biffbaxter** [org-roam/org-roam#1836]
### Description

Probably blind or missing something simple. so apologies as I have not touched my config in a while - but this is all fresh install now. (as of today 9-6-2021) fresh pulls from doom and org-roam. 

I am running doom emacs vanilla pulled today from git (so it shows DOOM v3.0.0-alpha 
running Arch Linux 
I removed all my custom stuff so its only doom being pulled with default configs (EG. only the config.el, init.el, and packages.el)
I added the +roam2 in the init.el for org `(org +roam2)` - so it shows version `2.0.0`
I did a doom sync and upgrade and all came back good and appeared to pull and do everything normal. 

Want to use the `org-roam-db-query` for several things I am tweaking and I don't seem to see it? 

![2021-09-06-123926_263x146_scrot](https://user-images.githubusercontent.com/36861063/132257020-5d4a5d88-bd4f-4284-b21e-5b4627417282.png)

What am I missing, and again apologies if its a simple fix, but V2 is a tad new to me, so I am digging around with not much success so far on this topic.

**Comment by biffbaxter** [comment]
I think I will close this. I think this was/is related to loading of modules in the right order and calling commands for modules that are not loaded yet...thus the "void function" errors I was seeing. My ElispFu is not strong, but after some FAFO I determined I could get the things working I needed by making sure modules needed are loaded in the correct order.

**Comment by MattiaSilvestri** [comment]
Hey do you mind if I ask how exactly you solved the issue? I also don't find the `org-roam-db-query` function anymore, but since I'm quite new to emacs I'm not sure what you mean by loading the modules in the correct order and how to achieve that. Thank you!

**Comment by AnweshGangula** [comment]
I'm facing the same issue
