### ISSUE TITLE
org-roam-dailies--daily-note-p fails when invoked from a non-file buffer

### ISSUE THREAD

**Issue by offbyone** [org-roam/org-roam#1840]
### Description

When invoking functions such as `org-roam-dailies-go-to-previous-note` eventually `org-roam-dailies--daily-note-p` is called, which fails if the current buffer is not a file.

#### Steps to Reproduce

1. Open a non-file buffer (`*scratch*` does this quite well)
2. Run `org-roam-dailies-go-to-previous-note`

#### Backtrace
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  (and t (expand-file-name (or file (buffer-file-name (buffer-base-buffer)))))
  (let* ((path (and t (expand-file-name (or file (buffer-file-name (buffer-base-buffer)))))) (directory (and path (expand-file-name org-roam-dailies-directory org-roam-directory)))) (if directory (progn (setq path (expand-file-name path)) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (and (org-roam-file-p path) (f-descendant-of-p path directory))) (set-match-data save-match-data-internal 'evaporate)))) nil))
  org-roam-dailies--daily-note-p()
  (if (org-roam-dailies--daily-note-p) nil (user-error "Not in a daily-note"))
  org-roam-dailies-goto-next-note(-1)
  (let ((n (if n (- n) -1))) (org-roam-dailies-goto-next-note n))
  org-roam-dailies-goto-previous-note(1)
  funcall-interactively(org-roam-dailies-goto-previous-note 1)
  command-execute(org-roam-dailies-goto-previous-note)
```

#### Expected Results

I expect it to open the most recent org note in this case, but honestly, I don't think this matters :D 

#### Actual Results

The aforementioned stack trace.

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
 of 2021-08-27
- Framework: Doom
- Org: Org mode version 9.5 (9.5-b83ae59 @ /Users/offby1/.emacs.d/.local/straight/build-28.0.50/org/)
- Org-roam: 2.0.0

Commit SHA: 028c95a011395d01ff9b5217dc365f23187bc26c

**Comment by japhir** [comment]
can reproduce here!

**Comment by jethrokuan** [comment]
This was fixed somewhere along the way...
