### ISSUE TITLE
EmacSQL had an unhandled condition: "cannot rollback - no transaction is active"

### ISSUE THREAD

**Issue by RCoeurjoly** [org-roam/org-roam#1841]
#### Backtrace
Debugger entered--Lisp error: (emacsql-access "attempt to write a readonly database")
  signal(emacsql-access ("attempt to write a readonly database"))
  #f(compiled-function (_ code message) "Get condition for MESSAGE provided from SQLite." #<bytecode 0x4813040775f8c9d>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac> 8 "attempt to write a readonly database")
  apply(#f(compiled-function (_ code message) "Get condition for MESSAGE provided from SQLite." #<bytecode 0x4813040775f8c9d>) #<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac> (8 "attempt to write a readonly database"))
  emacsql-handle(#<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac> 8 "attempt to write a readonly database")
  #f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode -0xdbcb54563df08b6>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac>)
  apply(#f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode -0xdbcb54563df08b6>) #<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac> nil)
  emacsql-parse(#<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac>)
  #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0xaac7063452640ed>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac> [:insert :into files :values $v1] (["/home/drcoeurjoly/Exocortex/20200415103912-org_roa..." "154f232e01ad5cfaa50b23f2c26dab616d180302" (24888 43124 9540 595000) (24480 29983 552476 164000)]))
  apply(#f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0xaac7063452640ed>) #<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac> ([:insert :into files :values $v1] (["/home/drcoeurjoly/Exocortex/20200415103912-org_roa..." "154f232e01ad5cfaa50b23f2c26dab616d180302" (24888 43124 9540 595000) (24480 29983 552476 164000)])))
  emacsql(#<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac> [:insert :into files :values $v1] (["/home/drcoeurjoly/Exocortex/20200415103912-org_roa..." "154f232e01ad5cfaa50b23f2c26dab616d180302" (24888 43124 9540 595000) (24480 29983 552476 164000)]))
  apply(emacsql #<emacsql-sqlite-connection emacsql-sqlite-connection-157298f8b0ac> [:insert :into files :values $v1] (["/home/drcoeurjoly/Exocortex/20200415103912-org_roa..." "154f232e01ad5cfaa50b23f2c26dab616d180302" (24888 43124 9540 595000) (24480 29983 552476 164000)]))
  org-roam-db-query([:insert :into files :values $v1] (["/home/drcoeurjoly/Exocortex/20200415103912-org_roa..." "154f232e01ad5cfaa50b23f2c26dab616d180302" (24888 43124 9540 595000) (24480 29983 552476 164000)]))
  org-roam-db-insert-file()
  org-roam-db-update-file("/home/drcoeurjoly/Exocortex/20200415103912-org_roa...")
  org-roam-db-sync(force)
  org-roam-migrate-wizard()
  funcall-interactively(org-roam-migrate-wizard)
  call-interactively(org-roam-migrate-wizard record nil)
  command-execute(org-roam-migrate-wizard record)
  helm-M-x-execute-command(org-roam-migrate-wizard)
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0xad5e0c2316e03e2>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0x147acbe9b0f92087>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x18f2a8323b799f1c>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0x1935675699f63d75>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history)
  apply(helm-internal ((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0xad5e0c2316e03e2>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . helm-follow-action-forward) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keeping se...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0x147acbe9b0f92087>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x18f2a8323b799f1c>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . helm-follow-action-forward) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keeping se...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0x1935675699f63d75>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history))
  helm((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0xad5e0c2316e03e2>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0x147acbe9b0f92087>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x18f2a8323b799f1c>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0x1935675699f63d75>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history)
  apply(helm ((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0xad5e0c2316e03e2>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . helm-follow-action-forward) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keeping se...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0x147acbe9b0f92087>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x18f2a8323b799f1c>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . helm-follow-action-forward) (67108897 . helm-toggle-suspend-update) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keeping se...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0x1935675699f63d75>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history))
  helm(:sources (((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0xad5e0c2316e03e2>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0x147acbe9b0f92087>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode 0x18f2a8323b799f1c>)) (candidates . helm-candidates-in-buffer) (keymap keymap (keymap ...) keymap (21 . helm-M-x-universal-argument) keymap (127 . helm-mode-delete-char-backward-maybe) (27 keymap ...) (C-return . helm-cr-empty-string) keymap (C-iso-lefttab . helm-follow-action-backward) (26 . helm-select-action) (tab . helm-execute-persistent-action) (17 . ace-jump-helm-line) (f13 lambda nil ... ...) (f12 lambda nil ... ...) (f11 lambda nil ... ...) (f10 lambda nil ... ...) (f9 lambda nil ... ...) (f8 lambda nil ... ...) (f7 lambda nil ... ...) (f6 lambda nil ... ...) (f5 lambda nil ... ...) (f4 lambda nil ... ...) (f3 lambda nil ... ...) (f2 lambda nil ... ...) (menu-bar keymap ...) (help keymap ...) (23 . #f(compiled-function () ... #<bytecode 0x13b978795fc42e5>)) (f1 lambda nil ... ...) (8) (20 . helm-toggle-resplit-and-swap-windows) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer-no-sort #f(compiled-function (candidates source) #<bytecode -0x15abf1fdc8789783>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . "C-j: Describe this command (keep...") (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0x1935675699f63d75>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) :prompt "M-x " :buffer "*helm M-x*" :history helm-M-x-input-history)
  helm-M-x-read-extended-command([## helm-ff-avfs-directory proof-general-version-year sphinx-doc-split-args helm-candidates-in-buffer copy-epl-upgrade Undo vc-git-stash-snapshot so-long-override-variables edebug-trace image-dired-update-property spacemacs/web-transient-state/web-mode-element-sibling-previous octave-close-block gnus-sync olp gnus-info-set-score helm-type-timers-actions vc-hg--read-u8 viper-deactivate-input-method-action helm-gtags--update-tags-p js--expression-in-sgml-indent-line ess-inside-comment-p gnus-summary-recenter spacemacs/symbol-overlay-transient-state/symbol-overlay-jump-next bloop Find\ file\ in\ directory infix-token edebug-clear-frequency-count c-standard-font-lock-fontify-region-function bibtex-SuppCollection 0 ada-for-loop-prompt-variable semanticdb-project-database-file-child-p shr-parse-image-data soap-element-namespace-tag--cmacro one Edebug\ All\ Defs org-projectile-single-file-strategy--anon-cmacro helm-browse-project-build-buffers-source \' nnoo-import-1 helm-grep-mode-jump-other-window-forward helm-buffer-run-ediff-merge rx-trans-forms sessions tramp-gvfs-unmount todo-categories-mode tramp-goa-account-host org-roam-db-diagnose-node helm-gtags--set-parsed-file ...])
  helm-M-x(nil)
  funcall-interactively(helm-M-x nil)
  call-interactively(helm-M-x)
  (let ((completion-styles completion-styles)) (add-to-list 'completion-styles (if (version< emacs-version "27") 'helm-flex 'flex) t) (call-interactively 'helm-M-x))
  spacemacs/helm-M-x-fuzzy-matching()
  funcall-interactively(spacemacs/helm-M-x-fuzzy-matching)
  call-interactively(spacemacs/helm-M-x-fuzzy-matching nil nil)
  command-execute(spacemacs/helm-M-x-fuzzy-matching)

#### Expected Results

Success in migrating files!

#### Actual Results

EmacSQL had an unhandled condition: "cannot rollback - no transaction is active"

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.32, cairo version 1.16.0)
 of 2020-04-26
- Framework: Spacemacs
- Org: Org mode version 9.4.6 (9.4.6-12-gdcc3a8-elpa @ /home/drcoeurjoly/.emacs.d/elpa/develop/org-20210906/)
- Org-roam: 2.1.0

**Comment by RCoeurjoly** [comment]
Lack of space on device.

You have to love them informative error messages.

**Comment by Wetlize** [comment]
Thanks for filling the issue, but I don't think that something that we can handle on our side, hence closing this. Something like this should be handled and took care about by `emacsql` itself and I don't think we can do much about this on our side (as you can see yourself, the error is just way too generic).
