### ISSUE TITLE
Store #+CATEGORY in db

### ISSUE THREAD

**Issue by real-or-random** [org-roam/org-roam#1844]
### Brief Abstract

Currently, the org-roam database stores all kind of org metadata, e.g., `SCHEDULED` times or tags. It should also store the `CATEGORY` property of nodes. 

### Long Description

`CATEGORY` is an org-mode keyword that adds a category to files or headlines, see https://orgmode.org/manual/Categories.html. Categories are used for example in the agenda, and other packages in the org universe build upon this functionality.

Note that this is a property built into org mode, so I'm not asking for arbitrary keywords as in #672.  Moreover, I'm not asking for a new tag mechanism as discussed in #1492. Categories are there for a reason in plain org, and some users and tools rely on them. I personally use them to categorize my notes very broadly into "Personal", "Work", etc. while still being able to have them in one place to enable links from Personal pages to Work pages. But I guess the use is very individual, and as always, everyone has their own workflow. (See https://karl-voit.at/2019/09/25/categories-versus-tags/ for a discussion.)

Support in org-roam would for example mean we can list them in the minibuffer and/or fileter when searching for nodes (similar to how we list tags). Previously in v1, I abused the custom tag functionality for this:
```
  (defun org-roam--extract-tags-category (_file)
    "Extract category from the current buffer's \"#category\" global property."
    (cdr (assoc "CATEGORY" (org-roam--collect-keywords '("CATEGORY")))))
  (setq org-roam-tag-sources '(prop category))
```
Now with v2 and the database storing all kinds of org metadata, adding the category would be simple. 

A common misconception is that categories apply only on a file level. This is simply not true. While they're often used on a file-level only (using `#+CATEGORY`) and headlines inherit them, they can be added to every heading using a property drawer like `:PROPERTIES: :CATEGORY: foo :END:`, see the org docs. So they don't contradict the new v2 design where everything is a node. 

### Proposed Implementation (if any)

Getting the category is easy: just call `(org-get-category)` with the cursor at the node. (The reason I used `org-roam--collect-keywords` above was to workaround another issue, which now has been fixed.)

Here's one caveat: As the org docs say "By default, the category is simply derived from the file name", so if your file is "foo.org" and you don't specify a category, it will be "foo". Now that default may be okay for the normal org-agenda user but it's pretty useless if you use org-roam and have autogenerated files names which are derived from the title...

But I don't think this would stop us from having a useful implementation for people who really set their categories manually: We could either make sure to ignore "default" categories (e.g., by simply comparing the category name to the file name, or by parsing the property on our own). Or even simpler, make sure they stay out of the way for users who don't use categories. For example, the default `org-roam-node-display-template` would not need to include the category. 
 
### Please check the following:

- [x] No similar feature requests

edit: And I forgot to say thanks again for all your work. v1 was great and now I finally did the migration and v2 is awesome!

**Comment by Wetlize** [comment]
Hi! I think this should be already possible to do so. You see, while the category isn't specified as a unique entry within `nodes` table, it's still obtained as part of the properties during parsing (as part of the [special properties](https://orgmode.org/manual/Special-Properties.html)), which means that the category is already stored under `properties` for each node under the `nodes` table.

https://github.com/org-roam/org-roam/blob/a8a36a420bfb4e19d76345f98bc33d8cfb2a03fe/org-roam-db.el#L152-L164

So all what's need to be done is to define the next method for the node:
```emacs-lisp
(cl-defmethod org-roam-node-category ((node org-roam-node))
  "Return the currently set category for the NODE."
  (assoc-string "CATEGORY" (org-roam-node-properties node)))
```
After which you should be able to use `${category}` in `org-roam-node-display-template` and other places that use template expansion.

> Here's one caveat: As the org docs say "By default, the category is simply derived from the file name", so if your file is "foo.org" and you don't specify a category, it will be "foo". Now that default may be okay for the normal org-agenda user but it's pretty useless if you use org-roam and have autogenerated files names which are derived from the title...

This can be handled to, as such:
```emacs-lisp
(cl-defmethod org-roam-node-category ((node org-roam-node))
  "Return the currently set category for the NODE."
  (let ((category (assoc-string "CATEGORY" (org-roam-node-properties node))))
    (if (string= category (file-name-base (buffer-file-name)))
        "" ; or return the current title, e.g. (org-roam-node-title node)
      category)))
```

**Comment by real-or-random** [comment]
Okay,  "it's already there" is of course the best reply for a feature request. 

I needed to add `cdr` but this works great: 
```emacs-lisp
(cl-defmethod org-roam-node-category ((node org-roam-node))
  "Return the currently set category for the NODE."
  (cdr (assoc-string "CATEGORY" (org-roam-node-properties node))))
```

Maybe this function should be added to the project.

**Comment by real-or-random** [comment]
Okay, here's one bug:

When I change a `+CATEGORY: A` entry to `+CATEGORY: B:` and save the file, the org-roam cache won't pick up that change. It works fine when the category is set in the property drawer and not with `+CATEGORY`.

The issue is that org hasn't updated the category yet when org-roam syncs the db.

Here's a fix:
Add a call to `org-refresh-category-properties` after this line:
https://github.com/org-roam/org-roam/blob/1795039ab93ef19611dbb3fca21c4211c4e655a9/org-roam-db.el#L500

Interestingly, removing `'tags-only` from the call to `org-set-regexps-and-options` does not help even though this function will do category-stuff when `'tags-only` is not given. Maybe we need more of those refresh functions, see `org-agenda-prepare-buffers` for code that has a similar purpose. I don't know how this is supposed to work but wouldn't the proper way be to let org do its all org stuff first on saving, and only then update the db?
