### ISSUE TITLE
Ability to create a template used when org-roam-dailies need to create new files

### ISSUE THREAD

**Issue by stig** [org-roam/org-roam#1845]
### Brief Abstract

I'd like to use an existing file as a template to be used when Org Roam dailies creates new daily files.

I'm currently using Org Roam 2.0.0 and can't find a way to do this. 

### Long Description

I currently have the following capture templates. They capture to the same file for each day, but to different headings. 

```emacs-lisp
(setq org-roam-dailies-capture-templates
     '(("d" "Journal" entry "* %?"
        :if-new (file+head+olp "%<%Y-%m-%d>.org"
	  		     "#+title: %<%Y-%m-%d>\n#+filetags: %<:%Y:%B:>\n"
		  	     ("Journal")))
       ("m" "Most Important Thing" entry "* TODO %? :mit:"
        :if-new (file+head+olp "%<%Y-%m-%d>.org"
			     "#+title: %<%Y-%m-%d>\n#+filetags: %<:%Y:%B:>\n"
			     ("Most Important Thing(s)")))))
```

Rather than using `file+head+olp` here I would love to instead use `file+olp`, and specify the path to a separate template file that would be used to create the file. (This because I want to pre-fill my daily file with some tasks.)

### Proposed Implementation (if any)

It would probably work if each `org-roam-dailies-capture-template` entry supported an additional `:new-file-template` key, and I could specify that like so:

```emacs-lisp
(setq org-roam-dailies-capture-templates
     '(("d" "Journal" entry "* %?"
        :new-file-template file("templates/daily.org")
        :if-new (file+olp "%<%Y-%m-%d>.org"
		  	     ("Journal")))
       ("m" "Most Important Thing" entry "* TODO %? :mit:"
        :new-file-template file("templates/daily.org")
        :if-new (file+olp "%<%Y-%m-%d>.org"
			     ("Most Important Thing(s)")))))
```

Alternatively, maybe I could use a (new) `file+template+olp` construct instead of `file+head+olp`, something like:

```emacs-lisp
(setq org-roam-dailies-capture-templates
     '(("d" "Journal" entry "* %?"
        :if-new (file+template+olp "%<%Y-%m-%d>.org"
	  		     "templates/daily.org"
		  	     ("Journal")))
       ("m" "Most Important Thing" entry "* TODO %? :mit:"
        :if-new (file+template+olp "%<%Y-%m-%d>.org"
			     "templates/daily.org"
			     ("Most Important Thing(s)")))))
```

### Please check the following:

- [X] No similar feature requests

**Comment by Wetlize** [comment]
This should be already possible with the current system. Org-roam doesn't just expand `${these}` kind of templates, but also %-escape ones from `org-capture`. One of the such escape is `%(sexp)`, which allows to run an arbitrary Elisp code inside the template and insert the return value of the form into the template. 

So this:
```emacs-lisp
(setq org-roam-dailies-capture-templates
      '(("d" "Journal" entry "* %?"
         :if-new (file+head+olp "%<%Y-%m-%d>.org"
	  	  	        "#+title: %<%Y-%m-%d>\n#+filetags: %<:%Y:%B:>\n"
		  	        ("Journal")))
        ("m" "Most Important Thing" entry "* TODO %? :mit:"
         :if-new (file+head+olp "%<%Y-%m-%d>.org"
			        "#+title: %<%Y-%m-%d>\n#+filetags: %<:%Y:%B:>\n"
			        ("Most Important Thing(s)")))))
```
Can be refactored into:
```emacs-lisp
(setq org-roam-dailies-capture-templates
      '(("d" "Journal" entry "* %?"
         :if-new (file+head+olp "%<%Y-%m-%d>.org"
                                "%(my-org-roam--get-template \"path\")"
	  	  	        "#+title: %<%Y-%m-%d>\n#+filetags: %<:%Y:%B:>\n"
		  	        ("Journal")))
        ("m" "Most Important Thing" entry "* TODO %? :mit:"
         :if-new (file+head+olp "%<%Y-%m-%d>.org"
                                "%(my-org-roam--get-template \"path\")"
			        ("Most Important Thing(s)")))))

(defun my-org-roam--get-template (path)
  (let ((template (f-read-text path)))
    (org-roam-capture--fill-template template t)))
```

Alternatively you can also `let`-bind your values and refactor the template as such:
```emacs-lisp
(setq org-roam-dailies-capture-templates
      (let ((head "#+title: %<%Y-%m-%d>\n#+filetags: %<:%Y:%B:>\n"))
        `(("d" "Journal" entry "* %?"
           :if-new (file+head+olp "%<%Y-%m-%d>.org" ,head
		  	          ("Journal")))
          ("m" "Most Important Thing" entry "* TODO %? :mit:"
           :if-new (file+head+olp "%<%Y-%m-%d>.org" ,head
			          ("Most Important Thing(s)"))))))
```

I'm also in a middle of a pretty large redesign of the whole targeting system (`:if-new`/`:target` stuff) , with which you will be able to freely extend the targeting system in various ways. One of which would allow you to easily define your own target properties and do something like this:

```emacs-lisp
(setq org-roam-dailies-capture-templates
      '(("d" "Journal" entry "* %?"
         :if-new (file+template+olp "%<%Y-%m-%d>.org"
                                    "path"
		                    ("Journal")))
        ("m" "Most Important Thing" entry "* TODO %? :mit:"
         ;; this will be new alternative style
         :if-new (file "%<%Y-%m-%d>.org"
                       :template "path"
		       :olp ("Most Important Thing(s)")))))

(defun org-roam-capture--target+template (path)
  (let ((template (f-read-text path)))
    (org-roam-capture--target+head template)))
```

**Comment by stig** [comment]
Thank you @Wetlize! I tried something like this before, but I must have messed something up as I didn't get it to work. FWIW it works now! 🤷🏼 I went with your first let-variant, as when using the `%(sexp)` form I could not get template expansion to work. I like my template to contain this header:

```
#+title: %<%Y-%m-%d>
#+filetags: %<:%Y:%B:>
```

**Comment by MaikuMori** [comment]
Actually, you don't even need `"%(f-read-text \"path\")"`, just use `"%[path]"` - this has the upside of expanding template text inside the file.
