### ISSUE TITLE
Getting org-roam to work

### ISSUE THREAD

**Issue by algon-ns** [org-roam/org-roam#1846]
### Description
Now, I'm here again, I can get some feature to work in org-roam, but I can't just do "find file" and "link" in files.
Whenever I make a C-c n f, I get this rather long error messages:

_Debugger entered--Lisp error: (void-function org-roam-node-tag)
  org-roam-node-tag(#s(org-roam-node :file "/Users/niels/org/roam/systemcrafters.org" :file-hash nil :file-atime (24890 35808 112853 910000) :file-mtime (24890 35806 887745 448000) :id "29286066-96B4-4D8E-AC97-058B2E5C4A99" :level 0 :point 1 :todo nil :priority nil :scheduled nil :deadline nil :title "/Users/niels/org/roam/systemcrafters.org" :properties (("CATEGORY" . "Dokument") ("ID" . "29286066-96B4-4D8E-AC97-058B2E5C4A99") ("BLOCKED" . "") ("FILE" . "/Users/niels/org/roam/systemcrafters.org") ("PRIORITY" . "B")) :olp nil :tags nil :aliases nil :refs nil)) ............._

### Environment
GNU Emacs 28.0.50 (build 10, aarch64-apple-darwin20.6.0, NS appkit-2022.60 Version 11.5.2 (Build 20G95))
 of 2021-08-31 built on macal.local
Repository revision: 67545b99c95eeec92379543b3a56385ccf9a66cc
Repository branch: master
Windowing system distributor 'Apple', version 10.3.2022
System Description:  macOS 11.5.2

- Org: Org mode version 9.4.6 (9.4.6-g8df3e2 @ /Users/niels/.emacs.d/straight/build/org/)
- Org-roam: v2.1.0-16-g1795039

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by Wetlize** [comment]
Please, don't cut the backtrace; you can pastebin and then link it here if it something large. I suspect in your config `org-roam-node-display-template` has `${tag}` somewhere in a string, which should be changed into `${tags}`. Changing that should fix this.

**Comment by algon-ns** [comment]
Thanks, that were the problem...
