### ISSUE TITLE
complete between [[]] does not work twice on same line

### ISSUE THREAD

**Issue by dustinfarris** [org-roam/org-roam#1861]
#### Steps to Reproduce

1. Type `[[some node title]] and [[another node title]]`

#### Expected Results

Both links offer completion results.

#### Actual Results

Only first link offers completion results, but a link on a new line will start working again.

### Environment

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.6.0, NS appkit-2022.60 Version 11.5.2 (Build 20G95))
 of 2021-09-11
- Framework: Spacemacs
- Org: Org mode version 9.4.6 (9.4.6-12-gdcc3a8-elpa @ /Users/pepsi/.emacs.d/elpa/28.0/develop/org-20210906/)
- Org-roam: 2.1.0

**Comment by jethrokuan** [comment]
Closed with #1948
