### ISSUE TITLE
capture heading node

### ISSUE THREAD

**Issue by dustinfarris** [org-roam/org-roam#1864]
### Brief Abstract

Would like a way to target a file (e.g. work.org) and add a TODO heading that itself is a node.

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
You can target a node by its id in `org-roam-capture-templates`:

```emacs-lisp
(setq org-roam-capture-templates
      '(("d" "default" entry "* TODO %?"
         :target (node "node-id-here")
         :unnarrowed t)))
```

**Comment by wztdream** [comment]
> 
> @dustinfarris you can simply make your entry capture template create a properties drawer as well:
> 
> ```emacs-lisp
> (setq org-roam-capture-templates
>       `(("d" "default" entry ,(concat "* TODO %?\n"
>                                       ":PROPERTIES:\n"
>                                       ":ID: " (org-id-get-create)
>                                       "\n:END:")
>          :target (file "work.org")
>          :unnarrowed t)))
> ```

This does not work, it will trigger:
```
(Spacemacs) Error in dotspacemacs/user-config: ‘org-id-get’ expects a file-visiting buffer
```
And if I manually execute this code by `C-x e` it will add `id` to my configure file.

**Comment by dustinfarris** [comment]
> > @dustinfarris you can simply make your entry capture template create a properties drawer as well:
> > ```emacs-lisp
> > (setq org-roam-capture-templates
> >       `(("d" "default" entry ,(concat "* TODO %?\n"
> >                                       ":PROPERTIES:\n"
> >                                       ":ID: " (org-id-get-create)
> >                                       "\n:END:")
> >          :target (file "work.org")
> >          :unnarrowed t)))
> > ```
> 
> This does not work, it will trigger:
> 
> ```
> (Spacemacs) Error in dotspacemacs/user-config: ‘org-id-get’ expects a file-visiting buffer
> ```
> 
> And if I manually execute this code by `C-x e` it will add `id` to my configure file.

you're probably trying to use this in some read-only buffer or something

try replacing `org-id-get-create` with `org-id-new` (this is working for me fyi)

**Comment by anthonyfinch** [comment]
For anyone else who comes here searching for a similar thing - I found that the above suggested template didn't work for me - it instead inserted a heading that said "Invalid capture template." 

I got it to work with a little change:

`(defun tiger/todo-node-template ()
  (concat "* TODO %?\n"
          ":PROPERTIES:\n"
          ":ID: " (org-id-new)
          "\n:END:"))

;; and a capture template like:
            ("t" "task" entry (function tiger/todo-node-template)
             :target
             (file "inbox.org")
             :unnarrowed t)
`

Someone with better elisp that me can probably suggest a way to make it work inline again.

**Comment by cheerio-pixel** [comment]
> For anyone else who comes here searching for a similar thing - I found that the above suggested template didn't work for me - it instead inserted a heading that said "Invalid capture template."
> 
> I got it to work with a little change:
> 
> ```
>       (defun tiger/todo-node-template ()
>       (concat "* TODO %?\n"
>       ":PROPERTIES:\n"
>       ":ID: " (org-id-new)
>       "\n:END:"))
> 
>        ;; and a capture template like:
>        ("t" "task" entry (function tiger/todo-node-template)
>          :target
>          (file "inbox.org")
>          :unnarrowed t)
> ```
> 
> Someone with better elisp that me can probably suggest a way to make it work inline again.

In the template you can make it evaluate a function and paste the result, like this
```
"* TODO ${title} :project:
:PROPERTIES:
:ID: %(org-id-new)
:END:

- Description

  %?"
```
