### ISSUE TITLE
Executing `org-roam-extract-subtree` saves the file under the current directory instead of `org-roam-directory`

### ISSUE THREAD

**Issue by rdrg109** [org-roam/org-roam#1870]
#### Steps to Reproduce

The steps shown below were executed with a very minimal `init.el` file. The file is shown below.

```elisp
(setq org-roam-v2-ack t)
(require 'org-roam)
(org-roam-setup)
```

Also, `org-roam-directory` was empty (i.e. there were no files) in order to ensure that nothing is interfering with this issue.

1. Load Emacs

I opened it with

```sh
$ emacs -nw
```

2. Place your cursor in any headline. The location of the file containing the headline should be different than `org-roam-directory`.

I will use this file with name `foobar.org`. Suppose that my cursor is on the `* bar` headline.

```
* foo
* bar
```

3. Execute `org-roam-extract-subtree`.

#### Backtrace

Because this issue doesn't throw an error, there's no backtrace.

#### Expected results

The line containing `* bar` is moved to a node under `org-roam-directory`.

#### Actual results

The line containing `* bar` is not moved to a node under `org-roam-directory. Further details below.

After executing `org-roam-extract-subtree`, the following prompt is shown:

```
Extract node to: ~/org-roam/20210924120224-bar.org
```

Press RET to accept the default prompt for the desired location. Now, the following prompt is shown:

```
Non-existent agenda file ~/e/20210924120224-bar.org . [R]emove from list or [A]bort?
```

If I press `R`, `20210924120224-bar.org` is saved in the current directory instead of `org-roam-directory. If I press `A` instead, `20210924120224.org` is created in the current directory, but it is not saved. In either case (pressing `R` or `A`), the file is not created under `org-roam-directory`. This is definitively a bug because the node is ultimately created in the current directory instead of the path which I was prompt.

### Environment

```
- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4 @ /usr/share/emacs/27.2/lisp/org/)
- Org-roam: 2.1.0
```

**Comment by dustinfarris** [comment]
I am seeing this in a read-only buffer.  when I try to run `org-roam-extract-subtree` it interactively prompts to confirm the file locations, something like `roam/20220102_mything.org` which seems fine.  I hit enter to confirm and get:

```
Buffer is read-only
```

in the minibuffer and the node is not written.

**Comment by xeruf** [comment]
Interesting, I am observing the opposite:

When calling `org-roam-extract-subtree`, the file is saved to the root of my org-roam-directory, even though I am in a subdirectory and would the node to default into that as well.

**Comment by jmay** [comment]
@rdrg109 This might be fixed by https://github.com/org-roam/org-roam/pull/2091

Specifically, the "Non-existent agenda file..." message.

I'm seeing the same refile-directory behavior as @xeruf above.
