### ISSUE TITLE
`org-roam-set-keyword` doesn't consider LOGBOOK drawers 

### ISSUE THREAD

**Issue by rdrg109** [org-roam/org-roam#1872]
#### Steps to Reproduce

1. Create two headings
2. Move the cursor to the second heading
3. Set `org-log-into-drawer` to `t`.
4. Insert a note in the second heading with `org-add-note` (binded by default in `C-c C-z` as org-mode v.9.4.4)
5. Execute `org-roam-extract-subtree` while the cursor is on the second heading.

#### Expected Results

Given this org document

```org
* Heading no. 1
* Heading no. 2
:PROPERTIES:
:ID: 77e47479-7704-4faa-bc05-8f7aeb1628cb
:END:
:LOGBOOK:
- Note taken on [2021-09-26 Sun 10:53] \\
  This is a note
:END:
```

If we execute `org-roam-extract-subtree` in `Heading no. 2`, the extracted subtree should look as

```org
:PROPERTIES:
:ID: 77e47479-7704-4faa-bc05-8f7aeb1628cb
:END:
:LOGBOOK:
- Note taken on [2021-09-26 Sun 10:53] \\
  This is a note
:END:
#+TITLE: Heading no. 2
```

#### Actual Results

The extracted subtree results in

```org
:PROPERTIES:
:ID: 77e47479-7704-4faa-bc05-8f7aeb1628cb
:END:
:LOGBOOK:
#+TITLE: Heading no. 2
- Note taken on [2021-09-26 Sun 10:53] \\
  This is a note
:END:
```

#### Additional information

If anyone is willing to solve this issue, it is good to know that the problem here is `org-roam-set-keyword`, so if you want to easily debug your solution. You can create this document

```
:PROPERTIES:
:ID: c19800c9-292a-4c09-bdc3-024c4a017d2f
:END:
:LOGBOOK:
- Note taken on [2021-09-26 Sun 10:53] \\
  This is a note
:END:
```

and then call `org-roam-set-keyword`, for example, `(org-roam-set-keyword "FOOBAR" "123")`.

### Environment

```
- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4 @ /usr/share/emacs/27.2/lisp/org/)
- Org-roam: 2.1.0
```

**Comment by jethrokuan** [comment]
Closed by #1931
