### ISSUE TITLE
org-roam.db does not exists

### ISSUE THREAD

**Issue by skarning** [org-roam/org-roam#1875]
### Description
I followed this guide https://www.orgroam.com/manual.html#Windows for installing org-roam on windows. The compilation of the emacsql-sqlite.exe went fine.

When launching org-roam i get the following error: "Error (use-package): org-roam/:config: Selecting deleted [buffer]" 

Dir looks like this.
![image](https://user-images.githubusercontent.com/26875224/135045343-93b2e4a4-7c00-4b48-98bd-2916eeccfa18.png)

The org-roam-db location is the following.
"c:/Users/sivert.skarning/AppData/Roaming/.emacs.d/org-roam.db"

![image](https://user-images.githubusercontent.com/26875224/135045917-5ba93bf5-7bd1-4ef8-ad19-347657321679.png)

I have done a recursive search to se if the org-roam.db file exists on the computer but it does not.

Does anyone know why this file has not been generated?

**Comment by nobiot** [comment]
I suggest that you try org-roam-db-sync command manually and see it can create the db file. If you get the selecting deleted buffer, simply run the command again. On Windows it’s common to get that error every second time.

**Comment by skarning** [comment]
It does not create the db file. Tried the org-roam-db-sync multiple times.

**Comment by nobiot** [comment]
No message from db-sync command?

I use Org-roam on Windows 10 daily and have no problem. I don’t use use-package but not sure if this has any influence.

Three further suggestions.

1. Turn in toggle-debug-on-error and then call db-sync to see if there is any error
2. Try vanilla only with Org-roam (run emacs -q to launch Emacs with no config and only set up Org-roam; no use-package)
3. Use edebug to see what happens in run time one line by line while running db-sync

**Comment by skarning** [comment]
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  #f(compiled-function (connection) "Return true if the end of the buffer has a properly-formatted prompt." #<bytecode 0x28c4c61>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-2767970>)
  apply(#f(compiled-function (connection) "Return true if the end of the buffer has a properly-formatted prompt." #<bytecode 0x28c4c61>) #<emacsql-sqlite-connection emacsql-sqlite-connection-2767970> nil)
  emacsql-waiting-p(#<emacsql-sqlite-connection emacsql-sqlite-connection-2767970>)
  #f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0x2769cd5>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-2767970>)
  apply(#f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0x2769cd5>) #<emacsql-sqlite-connection emacsql-sqlite-connection-2767970> nil)
  emacsql-wait(#<emacsql-sqlite-connection emacsql-sqlite-connection-2767970>)
  #f(compiled-function (#<emacsql-sqlite-connection emacsql-sqlite-connection-2767970> (:file "c:/Users/sivert.skarning/AppData/Roaming/.emacs.d/..."))
  apply(#f(compiled-function 
  #f(compiled-function (&rest args) #<bytecode 0x27679a9>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-2767970> (:file "c:/Users/sivert.skarning/AppData/Roaming/.emacs.d/..."))
  apply(#f(compiled-function (&rest args) #<bytecode 0x27679a9>) #<emacsql-sqlite-connection emacsql-sqlite-connection-2767970> (:file "c:/Users/sivert.skarning/AppData/Roaming/.emacs.d/..."))
  initialize-instance(#<emacsql-sqlite-connection emacsql-sqlite-connection-2767970> (:file "c:/Users/sivert.skarning/AppData/Roaming/.emacs.d/org-roam.db"))
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x129e97d>)(emacsql-sqlite-connection :file "c:/Users/sivert.skarning/AppData/Roaming/.emacs.d/...")
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x129e97d>) emacsql-sqlite-connection (:file "c:/Users/sivert.skarning/AppData/Roaming/.emacs.d/..."))
  make-instance(emacsql-sqlite-connection :file "c:/Users/sivert.skarning/AppData/Roaming/.emacs.d/org-roam.db")
  emacsql-sqlite("c:/Users/sivert.skarning/AppData/Roaming/.emacs.d/org-roam.db")
  org-roam-db()
  org-roam-db-sync(nil)
  funcall-interactively(org-roam-db-sync nil)
  call-interactively(org-roam-db-sync record nil)
  command-execute(org-roam-db-sync record)
  execute-extended-command(nil "org-roam-db-sync" "org-roam-db-sy")
  funcall-interactively(execute-extended-command nil "org-roam-db-sync" "org-roam-db-sy")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)


This is what I got back when running org-roam-db-sync. Tried edbug, but did not really got to prduce something useful

**Comment by nobiot** [comment]
Hmm. So it tries to create the db file and fails by the looks of it. Sorry no idea. I haven’t seen anything like this before.

The only thing I would try at this point is to backup all the custom configuration and installed files, including the compiled exe, and start from scratch. Only with built-in package and Org-roam., nothing else. 

I never fail to get Org-roam working this way on my Windows. See this WIP guide for beginners for V2: https://github.com/nobiot/Zero-to-Emacs-and-Org-roam

**Comment by rgkirch** [comment]
The org-roam.db file dosen't currently exist and org-roam is failing to create a new file. I get `(error "Selecting deleted buffer")` if I run `org-roam-db-sync` or `org-roam-node-find` I don't know how the org-roam.db file got deleted in the first place; I just started getting this error. I tried to debug the code and followed it to the point where it's supposed to make the file. If I call `(make-instance 'emacsql-sqlite-connection :file org-roam-db-location)` like the code does then I get this error:

 ```
Debugger entered--Lisp error: (file-error "Spawning child process" "Exec format error")
  signal(file-error ("Spawning child process" "Exec format error"))
  flycheck-buffer()
  flycheck-buffer-automatically((idle-change))
  flycheck--handle-idle-trigger(#<buffer *doom:scratch*>)
  apply(flycheck--handle-idle-trigger #<buffer *doom:scratch*>)
  timer-event-handler([t 25006 23629 840151 nil flycheck--handle-idle-trigger (#<buffer *doom:scratch*>) nil 0 nil])
  accept-process-output(#<process emacsql-sqlite> 30)
    inhibit-quit = t
  #f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode -0x24131db017f78fb>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-7d3ecbf37c>)
  apply(#f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode -0x24131db017f78fb>) #<emacsql-sqlite-connection emacsql-sqlite-connection-7d3ecbf37c> nil)
  emacsql-wait(#<emacsql-sqlite-connection emacsql-sqlite-connection-7d3ecbf37c>)
  #f(compiled-function (#<emacsql-sqlite-connection emacsql-sqlite-connection-7d3ecbf37c> (:file "c:/Users/richie/org-roam.db"))
  apply(#f(compiled-function 
  #f(compiled-function (&rest args) #<bytecode 0xdd342fc169f793b>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-7d3ecbf37c> (:file "c:/Users/richie/org-roam.db"))
  apply(#f(compiled-function (&rest args) #<bytecode 0xdd342fc169f793b>) #<emacsql-sqlite-connection emacsql-sqlite-connection-7d3ecbf37c> (:file "c:/Users/richie/org-roam.db"))
  initialize-instance(#<emacsql-sqlite-connection emacsql-sqlite-connection-7d3ecbf37c> (:file "c:/Users/richie/org-roam.db"))
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode -0xa0c3b0e79f613bd>)(emacsql-sqlite-connection :file "c:/Users/richie/org-roam.db")
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode -0xa0c3b0e79f613bd>) emacsql-sqlite-connection (:file "c:/Users/richie/org-roam.db"))
  make-instance(emacsql-sqlite-connection :file "c:/Users/richie/org-roam.db")
  (setq elisp--eval-defun-result (make-instance 'emacsql-sqlite-connection :file org-roam-db-location))
  elisp--eval-defun()
  #<subr eval-defun>(nil)
  edebug--eval-defun(#<subr eval-defun> nil)
  apply(edebug--eval-defun #<subr eval-defun> nil)
  eval-defun(nil)
  eros-eval-defun(nil)
  funcall-interactively(eros-eval-defun nil)
  command-execute(eros-eval-defun)
```
I'm on Windows 10 and I have `c:\msys64\mingw64\bin` on my path...

**Comment by rgkirch** [comment]
Oh, my issue was [this](https://github.com/org-roam/org-roam/issues/1855#issuecomment-920224285) issue.

**Comment by jethrokuan** [comment]
Windows users can try the `sqlite3` connector, or the binary that @nobiot has compiled at https://github.com/nobiot/emacsql-sqlite.exe

See https://www.orgroam.com/manual.html#Customizing-Node-Caching
