### ISSUE TITLE
list breaking changes in the changelog (e.g. org-roam-dailies-find-previous-note → org-roam-dailies-goto-previous-note)

### ISSUE THREAD

**Issue by japhir** [org-roam/org-roam#1879]
### Description

I only just figured out that my config was outdated but couldn't find anything in the CHANGELOG at the V2 entry.

I was finally able to figure it out from the function no longer working and then searching for org-roam-dailies functions by name via M-x. Ultimately I found it here: https://github.com/org-roam/org-roam/blob/941bd1f6b433ffdc2001f0387656a0a271195883/org-roam-compat.el#L181 

#### Expected Results

List all breaking changes in the CHANGELOG.md file so that I know where to tweak my config

**Comment by Delapouite** [comment]
Hi

You are right. Having to hunt for breaking changes is never fun.
I've added a link to the org-compat file for the 2.0.0 entry in https://github.com/org-roam/org-roam/commit/8e6938a39d33bdb204b731be7b89aac1226af75f

Also we'll make our best to list potentiel future breaking changes for upcoming releases.
