### ISSUE TITLE
https://melpa.org/packages/org-roam-20210926.735.tar: Not found

### ISSUE THREAD

**Issue by RCoeurjoly** [org-roam/org-roam#1881]
#### Steps to Reproduce
M-x package-install org-roam

#### Expected Results
Installed successfully
#### Actual Results
helm-M-x-execute-command: https://melpa.org/packages/org-roam-20210926.735.tar: Not found

**Comment by alphapapa** [comment]
https://www.google.com/search?hl=en&q=emacs%20install%20package%20tar%20not%20found

**Comment by nobiot** [comment]
Yes. This issue is typically solved by this:

> Try package-refresh-contents? You probably have an outdated package database.
