### ISSUE TITLE
Make title-format for `org-roam-node-insert` customizable

### ISSUE THREAD

**Issue by mohkale** [org-roam/org-roam#1892]
### Brief Abstract
Add an option to convert the output of `(org-roam-node-title node)` in `org-roam-node-insert` so that users can customize how links to nodes are presented.

### Long Description
I like to create nodes in title case "Foo Bar" but insert links to them in lower case "foo bar". At the moment `org-roam-node-insert` inserts the title of the node directly and I always have to go back over it to downcase them. In practice I think it would be nicer if org-roam exposed an option for this that users could customize.

### Proposed Implementation (if any)
The option name probably needs changing.

```diff
--- /home/mohkale/.cache/emacs/straight/repos/org-roam/org-roam-node.el
+++ #<buffer org-roam-node.el>
@@ -563,6 +563,11 @@
   "Placeholder function. Return empty string for annotations."
   "")
 
+(defcustom org-roam-node-insert-translate-description #'identity
+  "Function that the title of an org-node is passed to to create a description."
+  :group 'org-roam
+  :type 'function)
+
 ;;;; Linkage
 ;;;;; [id:] link
 ;;;###autoload
@@ -585,7 +590,7 @@
                     (setq region-text (org-link-display-format (buffer-substring-no-properties beg end)))))
                (node (org-roam-node-read region-text filter-fn))
                (description (or region-text
-                                (org-roam-node-title node))))
+                                (funcall org-roam-node-insert-translate-description (org-roam-node-title node)))))
           (if (org-roam-node-id node)
               (progn
                 (when region-text
```

```lisp
(setq org-roam-node-insert-translate-description #'downcase)
```

### Please check the following:

- [X] No similar feature requests

**Comment by japhir** [comment]
one workaround for this could be to set a ROAM_ALIAS property with the lowercase version? Perhaps add this to your capture template?
