### ISSUE TITLE
Find node by title (was: Jump to the first / best / only match on 'org-roam-node-find (or: non-interactive find node))

### ISSUE THREAD

**Issue by hraban** [org-roam/org-roam#1902]
### Brief Abstract

I have a hotkey to jump to a specific heading. How do I jump to that heading if I know it exists, without going through any interactive minibuffer / helm reading?

### Long Description

My current implementation:

```emacs-lisp
    (org-roam-node-find
     nil
     fmt
     (lambda (n) (->> n
                      org-roam-node-title
                      (equal "my page title"))))))
```

and press [enter] immediately after pressing the hotkey.

### Proposed Implementation (if any)

This monstrosity is the best I could come up with from outside the lib, without changing org-roam:

```emacs-lisp
(let ((completing-read-function 'completing-read-default))
  (cl-letf (((symbol-function 'complete-with-action) (lambda (_ nodes &rest ignore)
             (caar nodes)))
            ((symbol-function 'completing-read) (lambda (_ cb &rest ignore)
             (funcall cb nil nil nil))))
    (org-roam-node-find nil nil (lambda (n) (->> n
                                                 org-roam-node-title
                                                 (equal "my page title"))))))

```

I'd love a way for `'org-roam-node-read` to entirely bypass `completing-read` if the post filter nodes list has only one result. To be honest, I'm very unfamiliar with completing-read; e.g. I'm not sure why org-roam doesn't use its provided predicate param instead of doing filtering on its own, before calling it. It has a million flags and a mile long help page, maybe one of those flags can be set to mean "just get the first result immediately if available". Otherwise, it could be bypassed entirely? Again, depending on how the parent function is called. You wouldn't always want this functionality.

Or provide some kind of escape hatch, somehow, to just "jump to this page non-interactively because I know it exists, dangit". Maybe an entirely separate function? .... maybe that already exists?? :)

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
> Obviously I would think that it's a useful function to add to the lib and export :) but that's me.

We used to have these sort of functions, but they're rarely used and end up as just code that requires maintenance. So generally now we only keep functions that are used internally by our interactive functions.
