### ISSUE TITLE
`org-roam-open-id-at-point` doesn't work when the context is node-property

### ISSUE THREAD

**Issue by rdrg109** [org-roam/org-roam#1923]
Sorry for not using the template for bug reports, but I feel there's no need to do it since the report can be easily understood.

As can be seen in the code of the master branch (as for the time of this writing), `org-roam-open-id-at-point` won't work when the link is in a property drawer. This because when `org-element-context` is executed in property drawers, the returned element doesn't have a `:type` property.

https://github.com/org-roam/org-roam/blob/2c75b194d8f75a8edaec77d503a47d1bf0c58f24/org-roam-node.el#L664-L677

**Comment by Wetlize** [comment]
@jethrokuan After searching through Org's mailing list it looks like they indeed decided to treat property drawers as plain key-value strings, however, if we look at the implementation of `org-open-at-point` they still resolve links in elements that shouldn't be there ("for convenience"), so I think it's something that isn't strictly prohibited.

So maybe if storing links in properties isn't harmful for the rest of Org, e.g. for exporters (I think this was the argument that they made against citations in drawers, not sure if this applies to links), then I don't see problem providing support for links in properties. 

> Patch the link extraction function to not consider links within ROAM_REFS. This adds a small amount of complexity.

That's the way to go, it shouldn't be hard to exclude such links during parsing. I'm actually in a progress of making parsing decoupled from DB insertion (where it's 2 different operations and stages), so I can fix this myself (if you wish) when I make the branch public.

**Comment by jethrokuan** [comment]
@Wetlize 

> That's the way to go, it shouldn't be hard to exclude such links during parsing. I'm actually in a progress of making parsing decoupled from DB insertion (where they become as a 2 different operations and even stages), so, if you wish, I can fix 1890 myself along with this issue when I will make the branch public.

Sounds great, thanks for looking into this! I also want to return to https://github.com/org-roam/org-roam/pull/1804, I think we were headed in the right direction there.

**Comment by Wetlize** [comment]
> I also want to return to #1804, I think we were headed in the right direction there.

Yep, it still in my plans to get it done, but only after I publish a couple of other PRs that I didn't make public due to lack of free time for Org-roam. I think I'll be able to get it done before we step into 2022.
