### ISSUE TITLE
[nitpick] order of arguments on functions dealing with properties.

### ISSUE THREAD

**Issue by Delapouite** [org-roam/org-roam#1925]
Hello

Sorry in advance for this post that may feel a bit like bikeshedding.

I had a bit of struggle while writtng some code involving `org-roam-add-property` and `org-roam-remove-property`
Let's illustrate by this snippet taken from the `org-roam` codebase:
```elisp
(defun org-roam-ref-add (ref)
  "Add REF to the node at point."
  (interactive "sRef: ")
  (let ((node (org-roam-node-at-point 'assert)))
    (save-excursion
      (goto-char (org-roam-node-point node))
      (org-roam-add-property ref "ROAM_REFS"))))

(defun org-roam-ref-remove (&optional ref)
  "Remove a REF from the node at point."
  (interactive)
  (let ((node (org-roam-node-at-point 'assert)))
    (save-excursion
      (goto-char (org-roam-node-point node))
      (org-roam-remove-property "ROAM_REFS" ref))))
```

The mistake I made in my code was trying to use them symmetrically, but these functions have opposite argument order, `prop` and `val` are inversed, which I found quite confusing:

```elisp
(org-roam-add-property ref "ROAM_REFS")
(defun org-roam-add-property (val prop) …)
```
vs
```elisp
(org-roam-remove-property "ROAM_REFS" ref)
(defun org-roam-remove-property (prop &optional val) …)
```

As the `val` argument is optional in the `org-roam-remove-property` function, what about changing the signature of `org-roam-add-property` to pass `prop` first : `(defun org-roam-add-property (prop val) …)`.

It would be more consistent and follow the principle of least astonishment.

Bonus bikeshedding. There are `org-roam-ref-add`, `org-roam-tag-add`, so should the function dealing with properties be called `org-roam-property-add` to follow this naming scheme ? (same for `remove` versions)

Thanks.

**Comment by jethrokuan** [comment]
@Delapouite thanks for reporting this, I think this is important and should definitely be addressed!
