### ISSUE TITLE
Invalid ref [cite@XXXX], skipping

### ISSUE THREAD

**Issue by oatmealm** [org-roam/org-roam#1938]
### Description
Error when saving a file containing `org-cite` keys. 

#### Steps to Reproduce

1. Create a node wit ROAM_REFS set with a valid `org-cite` style key, i.e. [cite:@Pals15] which is available in the bib file pointed by `org-cite-global-bibliography`
2. Add some content and save

#### Backtrace

n/a 

#### Expected Results

File should save with no errors.

#### Actual Results

```
Warning (org-roam): /home/[user]/Nextcloud/roam/references/ocr/Burke2008-3.org:1	Invalid ref [cite:@Pals15], skipping... Disable showing Disable logging
```

### Environment
`org-ref` is not installed and doesn't seem to be rquired by `org-roam` AFAIK.

```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
 of 2021-09-29
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-d4e192514 @ /home/uri/.emacs.d/.local/straight/build-28.0.50/org/)
- Org-roam: c789531
```

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/c789531e368f440f554601790747f10003d1796b

**Comment by oatmealm** [comment]
I think it's because `org-ref` was not being activated. Testing `org-cite` so now requiring it manually for `org-roam`.

**Comment by telotortium** [comment]
I encountered this issue again when using an org-cite link.
