### ISSUE TITLE
DB update via idle timer

### ISSUE THREAD

**Issue by xeruf** [org-roam/org-roam#1939]
### Brief Abstract
I have a few large files, which upon saving freeze Emacs for multiple seconds, so I had to turn off `org-roam-db-update-on-save`.
Yet I often shuffle things around and adjust and add ids, meaning I currently have to regularly trigger manual updates.

### Proposed Implementation (if any)
Bring back idle-timer as db update mode.

### Please check the following:

- [x] No similar feature requests

**Comment by nobiot** [comment]
How about something like this in your own configuration?
Adjust the interval to your liking.

I am not sure if this type of thing should make a way to the package (I am not saying it should not; I don't know).
If you are Windows, you will see `Error running timer ‘org-roam-db-sync’: (error "Selecting deleted buffer")` every second time. That has been the way it is for Windows but works for the every odd number of times.

```
(defvar my/auto-org-roam-db-sync--timer nil)
(defvar my/auto-org-roam-db-sync--timer-interval 5)

(define-minor-mode my/auto-org-roam-db-sync-mode
  "Toggle automatic `org-roam-db-sync' when Emacs is idle.
Referece: `auto-save-visited-mode'"
  :group 'org-roam
  :global t
  (when my/auto-org-roam-db-sync--timer (cancel-timer my/auto-org-roam-db-sync--timer))
  (setq my/auto-org-roam-db-sync--timer
        (when my/auto-org-roam-db-sync-mode
          (run-with-idle-timer
           my/auto-org-roam-db-sync--timer-interval :repeat
           #'org-roam-db-sync))))
```

**Comment by nobiot** [comment]
Added to wiki https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2#run-org-roam-db-sync-when-emacs-is-idle. (Will change it if the code above proven non-functional).

**Comment by xeruf** [comment]
Works well. Only seems to sometimes break the fancy displaying of org-mode files in Doom.

**Comment by nobiot** [comment]
Interesting. I don’t use doom so can’t really comment. I don’t know if you would like to pursue this further, but would you like to verify this? 

> Only seems to sometimes break the fancy displaying of org-mode files in Doom.

What the custom minor mode does is call `org-roam-db-sync`. It is not easy to connect this operation with breaking of “fancy displaying of org-mode files in Doom”.

**Comment by jethrokuan** [comment]
I've mentioned this before elsewhere, but I won't be adding or maintaining a different db update mode: these can be offered as a package outside of org-roam and maintained by someone else. I have very little capacity as is, and would like to focus my efforts elsewhere.

**Comment by xeruf** [comment]
> Interesting. I don’t use doom so can’t really comment. I don’t know if you would like to pursue this further, but would you like to verify this?
> 
> > Only seems to sometimes break the fancy displaying of org-mode files in Doom.
> 
> What the custom minor mode does is call `org-roam-db-sync`. It is not easy to connect this operation with breaking of “fancy displaying of org-mode files in Doom”.

I think what happens is that the function takes the focus off the buffer, which triggers an autosave after which the file is sometimes not correctly highlighted/indented anymore. I had this with other "background" operations as well.

**Comment by nobiot** [comment]
@xeruf 

If auto-save is getting in the way, then you could simply disable it temporarily while db update is running like this below.
It's crude because it assumes `auto-save-visited` is used by the user. 
Just an idea.

```
(defun my/org-roam-db-sync ()
  "Disable `auto-save-visited-mode' temporarily when running db update."
  (auto-save-visited-mode -1
  (org-roam-db-sync)
  (auto-save-visited-mode 1))

(define-minor-mode my/auto-org-roam-db-sync-mode
  "Toggle automatic `org-roam-db-sync' when Emacs is idle.
Referece: `auto-save-visited-mode'"
  :group 'org-roam
  :global t
  (when my/auto-org-roam-db-sync--timer (cancel-timer my/auto-org-roam-db-sync--timer))
  (setq my/auto-org-roam-db-sync--timer
        (when my/auto-org-roam-db-sync-mode
          (run-with-idle-timer
           my/auto-org-roam-db-sync--timer-interval :repeat
           #'my/org-roam-db-sync))))
```

**Comment by xeruf** [comment]
@nobiot thank you very much! I tried adjusting it to my needs, but hit an obstacle - how can I pass a chain of functions as parameter?
```elisp
(setq my/auto-org-roam-db-sync--timer
      (when my/auto-org-roam-db-sync-mode
        (run-with-idle-timer
         my/auto-org-roam-db-sync--timer-interval :repeat
         (and (equal major-mode 'org-mode) 'org-roam-db-sync 'org-roam-update-org-id-locations 'org-mode-restart)))))
```
I have tried `some`, `apply`, `-first`, `lambda` and a lot more, but I can't figure out this seemingly simple snippet...

**Comment by nobiot** [comment]
I suggest you examine the signature of `run-with-idle-timer`. I think it takes only one function as an argument (and arguments to it with `&rest`).

The simplest way I can think of is to create another function that does the chain of functions, and get `run-with-idle-timer` to call this single function. Like this below.

Your current example pass the result of evaluating `and`, which returns only `t` or `nil` -- `run-with-idle-timer` expects a symbol that is the name of a function, not `t` or `nil`.

Does this make sense?

```emacs-lisp
(setq my/auto-org-roam-db-sync--timer
      (when my/auto-org-roam-db-sync-mode
        (run-with-idle-timer
         my/auto-org-roam-db-sync--timer-interval :repeat
         #'my/single-function)))

(defun my/single-function ()
  "Docstring."
  (fn1) (fn2) (fn3))
```
