### ISSUE TITLE
completing-read selection has a trailing new line

### ISSUE THREAD

**Issue by memeplex** [org-roam/org-roam#1941]
### Description

![image](https://user-images.githubusercontent.com/2845433/140177687-d933cc40-1265-4de0-97a2-c857e6892986.png)

#### Steps to Reproduce

1. Create a node
2. Execute org-roam-node-find
3. Type the title of the new note
4. Press Tab

**Comment by jethrokuan** [comment]
Org-roam's default display-template works best for the majority (ivy/helm/vertico users). If you wish to use the default completion framework you can change the node display template:

```emacs-lisp
(setq org-roam-node-display-template "${title}")
```

**Comment by memeplex** [comment]
Ok, thanks!
