### ISSUE TITLE
Backlink buffer is emptied when interacting with org-journal

### ISSUE THREAD

**Issue by dagomar** [org-roam/org-roam#1942]
### Description
This issue is similar to [Backlinks buffer not updated after file creation, only after manual file reloading](https://github.com/org-roam/org-roam/issues/1137)

I am using org-journal, with the journal directory as a subdirectory in the roam directory. I noticed the backlinks buffer has erratic behaviour when interacting with a journal file; opening and creating new entries leave the backlink buffer empty. However, if I am in a roam file with a link to a journal entry, when I click on it, the backlink buffer works, until I click in the journal file.

I understand that this issue is probably not due to org-roam, I am mostly hoping to get some guidance. Perhaps I can use a hook to trigger something on save and on active? I guess my question is, why does clicking a link to a journal entry make the buffer work, does roam hook into it somehow and triggers something to update the backlink buffer? Can I use that to fix this?

Thanks for any assistance and for an amazing piece of software.

#### Steps to Reproduce

1. Have org-journal setup with a directory inside the roam directory
2. Create a journal entry
3. Open a roam file
4. Add reference to the journal entry
5. Click on the reference -> the backlink buffer displays the backlink
6. Click on the journal file
7. The buffer is emptied

#### Backtrace
I have not found errors

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.60 Version 10.13.6 (Build 17G65))
- Framework: Doom
- Org: Org mode version 9.5 (9.5-888aaa9 @ /Users/paulidesd1/.emacs.d/.local/straight/build-27.2/org/)
- Org-roam: v2.1.0-16-g1795039

**Comment by jethrokuan** [comment]
Is it emptied because the journal file you clicked into is also a node, hence the backlink buffers updates to show backlinks for that node? If you want a persistent backlinks buffer, use `org-roam-buffer` rather than `org-roam-buffer-toggle`.

**Comment by dagomar** [comment]
Oh gosh Jethro,

That points me to the reason: I'm linking to day nodes within a week file, when I click outside the day, the backlink buffer is empty (as no links to the parent exist). I _guess_ I would like to see the links to child and sibling nodes when I have nodes in a file, but that would be a feature request.

Thanks for pointing me to the right answer! I will close the issue.
