### ISSUE TITLE
Slightly declutter note view

### ISSUE THREAD

**Issue by memeplex** [org-roam/org-roam#1950]
### Brief Abstract

I'm requesting a couple of modifications that were discussed in https://org-roam.discourse.group/t/turn-off-the-bright-meta/2174 which I consider non controversial, perhaps more of neglected corner cases in org-roam:

1. Fold top-level property drawers by default.
2. Don't include the extension .org in note titles.

### Long Description

1. Fold top-level property drawers by default. In overview org-mode unfolds the top-level property drawer. I think this is a strange decision from them, I asked about it in their mailing list but received no feedback until now. Nevertheless it's specially noisy in the org-roam case because each file has a top-level drawer that uses 3 additional lines just to show a long opaque number, so folding it to a single line and hiding the meaningless (for the human reader) number seems like the right call to me.

2. Don't include the extension .org in note titles. I feel that having an id, a title, a filename and potentially a top-level heading competing over the "note identity" semantics is too much. But that's me. The id is there to stay, so at least we can hide it as requested in the previous point. It's very easy to change the filename to resemble a note title, in the way traditional wikis do. The title is optional and fallbacks to the filename. So far so good but there is one quirk: the .org extension is left alongside the title. This behavior is hardcoded and doesn't strike me as the natural thing to do. In order to support a more "naive" workflow it would be desirable that the note filename were able to properly codify a note title without further technological ornaments like a file extension.

### Proposed Implementation (if any)

See comments https://org-roam.discourse.group/t/turn-off-the-bright-meta/2174/3 and https://org-roam.discourse.group/t/turn-off-the-bright-meta/2174/9. 

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
(1) I think is not within the scope of Org-roam, someone can write up a minor mode akin to `writeroom-mode` that hides clutter for Org files.

(2) Agreed wrt to title, merged with #1952 .

**Comment by memeplex** [comment]
Thanks!!!

**Comment by memeplex** [comment]
Sorry for necrobumping this, but wouldn't it be better if the directory were also removed? That is if the node path is `d/f.org`, only keep `f` as the title.

**Comment by jethrokuan** [comment]
> Sorry for necrobumping this, but wouldn't it be better if the directory were also removed? That is if the node path is d/f.org, only keep f as the title.

You can do this in your personal config, usually `d` here provides useful information.

**Comment by memeplex** [comment]
This is not customizable AFAICS. I don't see why the directory is important for the title here when by default title = (slug of) filename *sans* dir.

**Comment by jethrokuan** [comment]
```
(cl-defmethod org-roam-node-my-title ((node org-roam-node))
  "Return the slug of NODE."
  (file-name-base (org-roam-node-file node)))

(setq org-roam-node-display-template "${my-title}")
```
