### ISSUE TITLE
trailing empty line in capture buffer created by org-roam-capture

### ISSUE THREAD

**Issue by grothesque** [org-roam/org-roam#1954]
I'm using org-roam 2.1.0 from elpa-stable.  When I type `M-x org-roam-capture` (the variable `org-roam-capture-templates` has its default value) a capture buffer is created that ends with **two** newline characters.  Example:
```
:PROPERTIES:
:ID: 4aa5de9e-226c-486a-a812-8fdc02ba40a0
:END:
#+title: Something

```
This means that when this buffer is saved as-is (useful when creating a new node as a keyword), the resulting text file will finish with one empty line.

Trailing whitespace can be problematic particularly in the context of version control but avoiding it is generally a good idea.

**Comment by jethrokuan** [comment]
Addressed by #2010
