### ISSUE TITLE
Why the org buffer is read-only?

### ISSUE THREAD

**Issue by vanniuner** [org-roam/org-roam#1970]
I use org-roam-node-insert ,and the message show :
org-roam-capture--prepare-buffer: Buffer is read-only: #<buffer 20211114210609-test2.org>

I use doom  (org +roam2) in init.el.

**Comment by jethrokuan** [comment]
Most likely case is the folder that file is in is read-only, or Emacs does not have write permissions for that folder.

**Comment by vanniuner** [comment]
In the org-roam-directory I use vterm create 2 files. One is test.org and I use emacs open it show org-self-insert-command: Buffer is read-only. Another is test.html everything is ok.

**Comment by vanniuner** [comment]
Anybody cloud help me？

**Comment by jethrokuan** [comment]
@vanniuner hard to say what's causing your buffer to be read-only, but it's likely to be an error on your own user-configuration.

**Comment by vanniuner** [comment]
> @vanniuner hard to say what's causing your buffer to be read-only, but it's likely to be an error on your own user-configuration.

oaky, thanks

**Comment by tomaskrulis** [comment]
Org roam newbie, the same happened to me when following the official org roam documentation. I had to revert the read-only buffer state with `read-only-mode`.

I have no idea why that happens though.
