### ISSUE TITLE
`C-c n i`: org-roam.elc failed to define function org-roam-insert

### ISSUE THREAD

**Issue by nickstares** [org-roam/org-roam#1972]
### Description
`org-roam-insert` does not work
#### Steps to Reproduce
Simply `C-c n i`

#### Backtrace
```
Debugger entered--Lisp error: (error "Autoloading file /Users/nick/.emacs.d/.local/straight/build-27.1/org-roam/org-roam.elc failed to define function org-roam-insert")
  #<subr autoload-do-load>((autoload "org-roam" nil t nil) org-roam-insert nil)
  apply(#<subr autoload-do-load> ((autoload "org-roam" nil t nil) org-roam-insert))
  autoload-do-load((autoload "org-roam" nil t nil) org-roam-insert)
  command-execute(org-roam-insert)
```

#### Expected Results

Insert a link to a file

#### Actual Results

Error

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G2021))
 of 2021-02-08
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-2e99997 @ /Users/nick/.emacs.d/.local/straight/build-27.1/org/)
- Org-roam: 50cc4d6

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by nobiot** [comment]
`org-roam-insert` does not exist. 
I suggest to review the autoloading definition you have set it to `org-roam-node-insert`.
