### ISSUE TITLE
reflinks don't always show

### ISSUE THREAD

**Issue by zipy124** [org-roam/org-roam#1973]
When inserting references using org-ref and creating a org-roam notes file for that reference, the reflink does not always show using the org-roam buffer or org-roam-ui. Normal back-links work as expected.

**Comment by nobiot** [comment]
Do you have reproducible examples?

**Comment by zipy124** [comment]
Here we can see in window 1: the org-roam buffer for an org-roam notes file attached to an org-ref citation, the buffer open in windows 2 contains a link to the buffer open in window 3, but is not shown as a backlink:
![image](https://user-images.githubusercontent.com/6547350/142200049-1f9a808b-af5a-45b3-a7ae-786ee94b7cd4.png)

If i then cite the note in the note itself, it is however displayed:
![image](https://user-images.githubusercontent.com/6547350/142200428-f45d9e96-47a8-4625-86c0-7e20256c6305.png)

I then re-cite the note in the other note and we can see it is not however displayed:
![image](https://user-images.githubusercontent.com/6547350/142200637-e08d37ff-fd6c-4b79-85fc-10c9353f30c2.png)

In-fact if I even link to the roam ID directly using org-roam-node-insert it does not work, I can however do the reverse and link the original file:
![image](https://user-images.githubusercontent.com/6547350/142201311-7581453b-2975-4094-a385-43e3ca582ba7.png)
![image](https://user-images.githubusercontent.com/6547350/142201330-99c51fc9-ab7a-4b71-a8ee-3dd7f0d99607.png)

**Comment by zipy124** [comment]
Upon reflection, perhaps it is because I updated to org-ref v3 and org-ref-bibtex only just got this commit:
https://github.com/org-roam/org-roam-bibtex/commit/f399b85f5c38bd52f6eb41da18fccfb971a04fe1

**Comment by nobiot** [comment]
I don't seem to be able to reproduce the problem.

Does this correctly reflect what you have in the example?

- Window 1 (left) org-roam-buffer for "Literature note" (Window 3)
- Window 2 (top right) TODO with citing the literature note with `org-ref` syntax
- Window 3 (bottom right) "Literature note" with `roam_refs` property for `org-ref`

![Screenshot from 2021-11-17 17-30-50](https://user-images.githubusercontent.com/12507865/142241436-718426a9-153e-4db5-8f31-43d79158588a.png)

You seem to be using Spacemacs. Try without it.

**Comment by nobiot** [comment]
Side note. Your screens are bit small for me to read (sorry, I don't think I have as good eye sight as you).  I may have missed some important elements from your examples. Very difficult to see and understand what's presented.

**Comment by nobiot** [comment]
Okay. I didn't know about Org-ref V3 and didn't see you had the "&" in your citations (sorry, too small).

I see that you need to add it to *both* `roam_refs` and citations with `[cite:&cite-key]`.

![Screenshot from 2021-11-17 18-59-49](https://user-images.githubusercontent.com/12507865/142256492-28550f82-fa47-4280-9581-8eed3e2b3298.png)

@jethrokuan, at the moment, the manual does not talk about the "&" from `org-ref` V3. Is this a documentation issue, or functional issue for `ROAM_REFS`?

**Comment by jmkard** [comment]
Same issue here.

Description: 
1. Node1: ROAM_REFS: cite:somecitation
2. Node 2: words cite:&somecitation
3. Open roam buffer 

Expected: Note 2 to show up in Note 1. 
Actual: Note 2 absent from Note 1. 

Environment:
* Org: Org mode version 9.5
* Org-roam: v2.1.0 (d93423d)
* Emacs: GNU Emacs 27.2 (build 1, aarch64-apple-darwin21.0.1, Carbon Version 165 AppKit 2103.13) of 2021-10-28
* Doom 21.12.0
* Org-roam-bibtex: 0.6.0

Everything else seems to work as it should. Org-ref works for inserting links, I can use orb templates to create new nodes, and non-citation ROAM_REFS show up as backlinks. E.g. Note1 :ROAM_REFS: https://www.google.com/, Note2 some text https://www.google.com/; Note2 shows up in Note1. I'm stumped, and would appreciate any help. Thanks in advance.

**Comment by nobiot** [comment]
Try adding & to roam_ref. Does this work on your end?

**Comment by nobiot** [comment]
I had a quick look in the Org-roam code. It does not look to support `org-ref` v3. It has had a significant changes.
For now, Org-roam does not look to be compatible with V3 of Org-ref.

As I see it, you can do either:

1. Stay with Org-ref V2
2. With V3, add "&" to the ROAM_REFS, like `ROAM_REFS: cite:&cite-key` as in my example above

Option 2 is only work around as it's treated as a normal link, not a citation (it's a detail but may be relevant in the context of other packages, such as `org-roam-ui` for graphing).

I can only do this much. I think @jethrokuan would need to decide what to do with Org-ref V3. 

As a quick summary, I found following. It might be a bit messy to try to support both V2 and V3 Org-ref.

This part:
https://github.com/org-roam/org-roam/blob/d93423d4e11da95bcf177b2bc3c74cb1d1acf807/org-roam-db.el#L510-L511
- Function `org-ref-split-and-strip-string` does not exist in V3 Org-ref
- `org-ref-cite-types` is now a different type in V3; `member` does not match; use `assoc` instead
- "&" prefix is not considered currently, citation link does not match ROAM_REF without "&"

**Comment by zipy124** [comment]
> Try adding & to roam_ref. Does this work on your end?

Unfortunately this does not solve the issue

**Comment by nobiot** [comment]
@zipy124 Can you show us exactly how you have done this, please? 

I have done a preliminary PR; Jethro is working to support both v2/v3 Org-ref. 

Your report indicates your problem might be different to what we think is the problem — regardless, v2/v3 is an issue.

**Comment by nobiot** [comment]
Alternatively, you could try the fix branch to see if it fixes your issue.

**Comment by jmkard** [comment]
> @zipy124 Can you show us exactly how you have done this, please?
> 
> I have done a preliminary PR; Jethro is working to support both v2/v3 Org-ref.
> 
> Your report indicates your problem might be different to what we think is the problem — regardless, v2/v3 is an issue.

Another data point: the proposed fix, adding "&" to the ROAM_REFS for V3 refs, works in my case.

**Comment by nobiot** [comment]
@jmkard Thank you.

That's what I expected. I can't reproduce @zipy124's issue. His may be a totally different one.

> I see that you need to add it to *both* `roam_refs` and citations with `[cite:&cite-key]`.
> 
> ![Screenshot from 2021-11-17 18-59-49](https://user-images.githubusercontent.com/12507865/142256492-28550f82-fa47-4280-9581-8eed3e2b3298.png)
> 
>

**Comment by jmkard** [comment]
@nobiot Thank you for your work on this.

**Comment by jmkard** [comment]
I'm not sure if this is (un)expected behavior...If I attempt to visit an existing citation's note using org-ref's citation actions menu, a new node is created, or the existing one is overwritten (depending on how I've set up my capture template). This happens after applying @nobiot 's temporary fix. It doesn't happen, however, with cite:somecitation; in this case, selecting the note associated with a citation in org-ref's citation actions menu brings me to the existing node. Without the "&", though, that citation doesn't show up in the roam buffer. What to do? For now, I'm getting the behavior I want by adding both cite:&somecitation and cite:somecitation to ROAM_REFS. Citations show up in the roam buffer AND no new/overwritten node when selecting a citation. This seems janky (I'm new to org-roam and relatively new to emacs), but I wanted to flag the workaround here in case someone stumbles on this thread and wants immediate results.

**Comment by jethrokuan** [comment]
Closed with #1977

**Comment by nobiot** [comment]
@jethrokuan I’d suggest to keep this issue open. The original post was by @zipy124 and he seems to have a different issue that I cannot reproduce. I think we need his confirmation.

**Comment by zipy124** [comment]
@nobiot  After some trying to de-bug to find a way to reliably reproduce this issue, It has somehow resolved itself, sorry I can't be of more help but best to leave this issue closed unless someone else in the future comes across this aswell.
