### ISSUE TITLE
org-roam-version returns misterious version number

### ISSUE THREAD

**Issue by GuiHeurich** [org-roam/org-roam#1974]
### Description

Before running the migration wizard, version was correctly displayed, but after running the migration wizard, version number is `25bc3ac`. 

#### Steps to Reproduce

1. Run `org-roam-version`

#### Backtrace
No backtrace. 

#### Expected Results

`2.1.0`

#### Actual Results

`25bc3ac`

### Environment

Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2021-11-05
- Framework: N/A
- Org: Org mode version 9.5 (nil @ /home/guilhermeorlandiniheurich/.emacs.d/.local/straight/build-27.2/org-mode/)
- Org-roam: 25bc3ac

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
That's the commit hash, as you can see, for the org-roam version. We haven't been very diligent in releasing minor releases, and the commit hashes are much more useful for us. You can see the "version" by looking at the header file of any org-roam source coede.

**Comment by GuiHeurich** [comment]
That makes sense, thanks.
