### ISSUE TITLE
Backlinks window shows comments content

### ISSUE THREAD

**Issue by oatmealm** [org-roam/org-roam#1979]
### Description
The backlinks buffer shows comments in preview of linked content.

#### Steps to Reproduce

1. Create a new node 
2. Add a comment under a specific headline
3. Link to the headline from another node 

#### Backtrace
n/a

#### Expected Results

Preview of a linked node should not include areas marked as comments [?]

#### Actual Results

Preview includes full content of everything under the headline linked, including comments.

See attachment. 

![Screenshot from 2021-11-21 09-13-30](https://user-images.githubusercontent.com/68159077/142754950-90eb311a-0ee1-4fe8-b35a-d4cdc8fcc860.png)

### Environment

```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
 of 2021-09-29
- Framework: Doom
- Org: Org mode version 9.5 (9.5-??-73875939a @ /home/uri/.emacs.d/.local/straight/build-28.0.50/org/)
- Org-roam: a2e46db
```

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/3e47f198c7b6c3254944d98357e41840e5e1b102

**Comment by jethrokuan** [comment]
#1990 introduces `org-roam-strip-comments` included by default in `org-roam-preview-postprocess-functions`, which strips the comments.
