### ISSUE TITLE
Linking to files, vs opening roam notes

### ISSUE THREAD

**Issue by stefanv** [org-roam/org-roam#198]
Currently, there is only one org-roam path.  However, one could argue that there are two separate concerns:

1. The list of files you would like to search for links and
2. The list of files you want to search when handling your notes.

To make it concrete: I have a daily planner that is outside my org-roam directory.  I am quite happy to keep this separate from roam (I don't want to see all those files when looking for notes).  *But*, when I refer to an org-roam file from my planner, it would be nice to see that from the roam sidebar.

I can think of various ways to hack this into place, but thought I'd ask whether this could be a common use-case.

**Comment by jethrokuan** [comment]
> when I refer to an org-roam file from my planner, it would be nice to see that from the roam sidebar

So you're saying that when you're looking at your planner file, you want to see the linked org-roam files in the sidebar? Those seem like forward links.

**Comment by stefanv** [comment]
No, I mean if I look at the roam file, in the side bar view I would like to see that it was references by the planner.

**Comment by jethrokuan** [comment]
Basically there needs to be a way to include files from outside the `org-roam-directory`. One way to get what you're looking for is to move away from `org-roam-directory` to `org-roam-files`, which would be either a list of files, or a function to obtain the list of files. Not sure how to gracefully transition over to that though.

**Comment by nalhasan** [comment]
@jethrokuan Is there a way to incorporate forward links into org-roam? I mean, is there any value in doing so considering I can see the link right in the file?

**Comment by jethrokuan** [comment]
There's still a bunch of stuff to add to the org-roam buffer, I'll need to think about whether that would crowd out the other information in the org-roam buffer.
