### ISSUE TITLE
`DONE` state and links in node's heading cause foreign key errors on updates to the links table

### ISSUE THREAD

**Issue by solodov** [org-roam/org-roam#1989]
#### Steps to Reproduce

1. minimal test file:

```
* DONE [[http://bar.baz][bar]]
:PROPERTIES:
:ID:       40CD2EC4-0E32-418E-BC38-10778653F988
:END:
```

2. Run `(org-roam-db-sync t)`

#### Errors

Warnings buffer contains:

```
Error (org-roam): Failed to process /test/org/test.org with error SQL constraint violation: "FOREIGN KEY constraint failed", skipping...
```

#### Expected Results

Node should be added to the database.

#### Actual Results

Entire file with the offending node is skipped, none of the nodes can be found

### Environment

```
- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.6.0, Carbon Version 164 AppKit 2022.6)
 of 2021-11-16
- Framework: N/A
- Org: Org mode version 9.5 (9.5-g0a86ad @ /Users/.../.emacs.d/elpa/org-9.5/)
- Org-roam: 2.1.0
```

org-roam melpa package `20211124.713`

**Comment by jethrokuan** [comment]
I still can't reproduce with this test file. Is this the only file in your database?

**Comment by solodov** [comment]
I did some more digging and I think I found the problem, I have this for org mode:

```
(setq org-agenda-skip-function-global '(org-agenda-skip-entry-if 'todo 'done))
```

it appears that with this set it's not just agenda entries that are skipped, I was playing with todo states and examining resulting database entries and nodes with heading in done state were skipped entirely. Restoring `org-agenda-skip-function-global` to the default value makes everything work correctly again. Seems like  a pretty weird pitfall...

**Comment by jethrokuan** [comment]
@solodov perhaps it's org-agenda doing some form of narrowing, can you try evaluating this:

```
(defmacro org-roam-with-file (file keep-buf-p &rest body)
  "Execute BODY within FILE.
If FILE is nil, execute BODY in the current buffer.
Kills the buffer if KEEP-BUF-P is nil, and FILE is not yet visited."
  (declare (indent 2) (debug t))
  `(let* (new-buf
          (auto-mode-alist nil)
          (find-file-hook nil)
          (buf (or (and (not ,file)
                        (current-buffer)) ;If FILE is nil, use current buffer
                   (find-buffer-visiting ,file) ; If FILE is already visited, find buffer
                   (progn
                     (setq new-buf t)
                     (find-file-noselect ,file)))) ; Else, visit FILE and return buffer
          res)
     (with-current-buffer buf
       (unless (derived-mode-p 'org-mode)
         (delay-mode-hooks
           (let ((org-inhibit-startup t)
                 (org-agenda-files nil))
             (org-mode))))
       (org-with-wide-buffer
        (setq res (progn ,@body)))
       (unless (and new-buf (not ,keep-buf-p))
         (save-buffer)))
     (if (and new-buf (not ,keep-buf-p))
         (when (find-buffer-visiting ,file)
           (kill-buffer (find-buffer-visiting ,file))))
     res))
```

and see if the problem goes away?

**Comment by solodov** [comment]
it made no difference, heading in "DONE" state is completely ignored.

**Comment by jethrokuan** [comment]
@solodov thanks for reporting and investigating, I traced it down and fixed it. Feel free to reopen if incorrect.
