### ISSUE TITLE
Md-roam not turned on; ‘org-roam-db-version’ 16 is not compatible

### ISSUE THREAD

**Issue by esrztk** [org-roam/org-roam#1992]
Hi,

I want to use md-roam. However. every time I try to open the md-mode it gives "Md-roam not turned on; ‘org-roam-db-version’ 16 is not compatible" error.

Currently I am using Emacs 27.2 and Org-Roam version 2.1.0. 

Is there anything that would fix this issue?

**Comment by nobiot** [comment]
Update org-roam. Current shorted db-version is 18.

**Comment by nobiot** [comment]
In addition, I must suggest that you should create Md-roam issues in the Md-roam project. This way, you would have gotten a response quicker.
