### ISSUE TITLE
org-roam-tag-remove does not respect tags argument

### ISSUE THREAD

**Issue by turbana** [org-roam/org-roam#1998]
### Description
`org-roam-tag-remove` does not respect `tags` argument when visiting an org element (as opposed to a file).

#### Steps to Reproduce
1. Navigate to a org-roam node implemented as an org heading.
2. Evaluate `(org-roam-tag-remove '("tag"))`.

#### Example
```
* Test Node                                                             :tag:
:PROPERTIES:
:ID:       47CFDB1F-6969-4401-AD79-E082135025FC
:END:
```
#### Backtrace
N/A

#### Expected Results
Tag `tag` is removed from heading.

#### Actual Results
User is prompted for tag to remove with `completing-read`.

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G22010))
 of 2021-11-18
- Framework: N/A
- Org: Org mode version 9.5.1 (9.5.1-gad53c5 @ /Users/ian/.config/emacs/straight/build/org/)
- Org-roam: v2.1.0-73-ge992fc2
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/e992fc2

**Comment by jethrokuan** [comment]
Closed with #1999
