### ISSUE TITLE
Emacs hangs with opening org-roam(V2) file after a few happy weeks 

### ISSUE THREAD

**Issue by mrfengguan** [org-roam/org-roam#2000]
### Description

Emacs hangs with opening org-roam file after a few happy weeks, a fresh install from V2, no migration.

I was pretty happy with using org-roam, until a few hours ago, after all tries, I found:

1) I can't open any files in the org-roam directory in Emacs, but I can open them with VIM.
2) I can open the org files in the org directory with Emacs.

Since the problem only occurs opening roam file, I doubt it might be caused by some roam related service like database or something.  What should I do to provide more diagnosing information?

#### Steps to Reproduce

The first time hanging
1. Load Emacs
2. Run `org-roam, find roam node` or  open a file in org-roam directory
3. Saving the file after modifying.
4. Emacs hangs with info "Processing modified file"

The later hanging
1. Load Emacs
2. Run `org-roam, find roam node` or  open a file in org-roam directory
3. Emacs hangs with info "Processing modified file"

![image](https://user-images.githubusercontent.com/95098546/144949587-93a5f5a8-4d44-4c55-af53-5d8e52d72cce.png)

#### Backtrace

No any debug info

### Environment

```
generated    Dec 06, 2021 17:35:19
system       MacOS 11.6 Darwin 20.6.0 arm64 ns
emacs        27.2 ~/.emacs.d/ -> ~/.emacs.d/
doom         21.12.0-alpha HEAD -> develop c93790bb 2021-11-28 22:08:07 +0100 ~/.doom.d/ -> ~/.doom.d/
shell        /bin/zsh
features     RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM NS MODULES THREADS JSON PDUMPER LCMS2 GMP
traits       gui server-running envvar-file
modules      :completion company helm vertico :ui deft doom doom-dashboard doom-quit hl-todo modeline neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :os macos :lang emacs-lisp markdown (org +roam2) sh :config (default +bindings +smartparens)
packages     (org-download) (sis)
```

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere
a2e46db

**Comment by jethrokuan** [comment]
maybe your db was corrupted, you can try deleting the database and rebuilding the cache from scratch.

**Comment by mrfengguan** [comment]
Now it's fixed, with such steps:


1. Moved the default org-roam.db from `/.emacs.d/` to other folder
2. Found the problem file, and use `org-roam-db-sync` to rebuild the db for other files. Now it's fixed and I can access all files.
3. The problem file seems causing problem by empty item symbol like '-' . eg.
```
* Tests
- test 1
- test 2
- 
```
After I remove that empty '-' item, it's working again.

4. but after 'db sync', everything seems restored except I can't find the roam db file. 🤔

**Comment by mrfengguan** [comment]
before: I deleted org-roam.db 
org-roam is working, but can't find any 'org-roam.db'.  (how is it possible ?)
after :  added ```(setq org-roam-db-location "~/Document/org-roam.db")``` in config.el
It's still working, and the org-roam.db is found at the new location

**Comment by jethrokuan** [comment]
> org-roam is working, but can't find any 'org-roam.db'. (how is it possible ?)

It is not. Look at `org-roam-db-location` for the location of the database.

>  The problem file seems caused by some empty item like '-' or indent .

This doesn't cause any issues for me.  Can you also update org-roam? #2006 might have fixed something. 

Please open a second issue with the problem file, if you're able to consistently reproduce the hanging.

**Comment by kisaragi-hiu** [comment]
I think this might be an issue with some versions of org-persist.el: as org-persist functions run on `kill-buffer-hook`, and Org-roam creates and kills temporary org-mode buffers, in the commits where org-persist is bugged, the hang would only seem to happen for Org-roam files.

https://github.com/bzg/org-mode/commit/5ca866d08aaadfa43be9c836492b488f36ec600f (2021/10/27) introduced the hang when killing an org-mode buffer; https://github.com/bzg/org-mode/commit/5abd149cf1e2ae0f6837536de1093ad04ad45f70 fixed it. It can be reproduced by creating an empty org-mode buffer and then killing it - the buffer will take quite a while to kill.

**What was your version of Org Mode when you first encountered the issue**? I see that you were on Doom Emacs commit [c93790bb](https://github.com/hlissner/doom-emacs/blob/c93790bb5cbd8d70a778670b018442fc71f74727/modules/lang/org/packages.el), which pins Org to https://github.com/bzg/org-mode/commit/27edae8cedd1fc793acb8ff34e478762a330e867, which is after the fix. But perhaps you hadn't updated Org when you encountered the hang?
