### ISSUE TITLE
emacs hangs with latest org roam

### ISSUE THREAD

**Issue by pinacle2000** [org-roam/org-roam#2007]
> I've just tested with a file with a thousand links, and it took less than a second. Can you confirm if the changes in #1946 have been pulled in?
> 
> See also [#1752 (comment)](https://github.com/org-roam/org-roam/issues/1752#issuecomment-962689026)

I use doom emacs and did an update today (including the latest org-roam update), which took forever to load. I checked my config and fount it is the org roam part. When I commentted the roam part, my emacs loads in a few seconds (acceptable in Windows). I deleted the roam db and started emacs. Now it has been loading (I guess since I can only see the changing memory/cpu usage of emacs process) for half an hour, with the memory usage from dozens of MB to 322 MB now, and the number is still growing.

I have 5 hundrends of roam org files with a few levels of directory, e.g. org-roam-root/level1/level2/level3/level4/abc.org. I had 3 hundrends when I use v1 and had no such problem. Therefore I believe it is the same issue here.

_Originally posted by @pinacle2000 in https://github.com/org-roam/org-roam/issues/1995#issuecomment-995825647_

**Comment by pinacle2000** [comment]
> > I've just tested with a file with a thousand links, and it took less than a second. Can you confirm if the changes in #1946 have been pulled in?
> > See also [#1752 (comment)](https://github.com/org-roam/org-roam/issues/1752#issuecomment-962689026)
> 
> I use doom emacs and did an update today (including the latest org-roam update), which took forever to load. I checked my config and fount it is the org roam part. When I commentted the roam part, my emacs loads in a few seconds (acceptable in Windows). I deleted the roam db and started emacs. Now it has been loading (I guess since I can only see the changing memory/cpu usage of emacs process) for half an hour, with the memory usage from dozens of MB to 322 MB now, and the number is still growing.
> 
> I have 5 hundrends of roam org files with a few levels of directory, e.g. org-roam-root/level1/level2/level3/level4/abc.org. I had 3 hundrends when I use v1 and had no such problem. Therefore I believe it is the same issue here.
> 
> _Originally posted by @pinacle2000 in [#1995 (comment)](https://github.com/org-roam/org-roam/issues/1995#issuecomment-995825647)_

I found I was wrong. I made my org-roam dir empty and nothing changed. It seems forever to load emacs, though not true as I tried to leave it aside overnight (before I empty my org roam note dir) and got the following message:

> Doom loaded 201 packages across 28 modules in 8715.270s

**Comment by pinacle2000** [comment]
Moreover, emacs takes less than 100MB memory without roam and took near 400MB with my overnight test.

**Comment by ribelo** [comment]
Are you using doom-emacs + pgtk + native-comp?

I had a similar problem. It helped to dump everything and compile emacs from source.

**Comment by pinacle2000** [comment]
> Are you using doom-emacs + pgtk + native-comp?
> 
> I had a similar problem. It helped to dump everything and compile emacs from source.

My emacs was installed through scoop. Maybe I could have a try to reinstall everything? It worked fine before I did a doom upgrade yestterday (last update was about 2 weeks agon)

**Comment by jethrokuan** [comment]
Since you're using scoop i'm assuming you're on Windows? I think this is a perpetual issue with `emacsql-sqlite`. Please consider using `emacsql-sqlite3` (see https://www.orgroam.com/manual.html#Customizing-Node-Caching)

The TLDR is that you set:

```
(setq org-roam-database-connector 'sqlite3)
```

and ensure that the official sqlite3 binary is available on your machine and in your PATH.

see also https://github.com/org-roam/org-roam/issues/2001#issuecomment-988718445

**Comment by pinacle2000** [comment]
I started using roam v1 with sqlite3 as well as the emacsql-sqlite.exe menthoned in #2001. It had been working well ...

**Comment by jethrokuan** [comment]
So are you using emacsql-sqlite3 now with v2 or v1?

**Comment by pinacle2000** [comment]
> So are you using emacsql-sqlite3 now with v2 or v1?

I had been using emacsql-sqlite3 with v2 untill yesterday, when I had to wait this issue to be solved.

**Comment by jethrokuan** [comment]
I don't use Windows and have never personally faced issues regarding the db connector. @nobiot seen anything like this before?

**Comment by nobiot** [comment]
Windows or otherwise, I don’t think emacsq-sqlite3 works… Refer to #1927.

We need to use the default option, sqlite, and let Emacs compile the exe file as described in the manual or in the [wiki](https://github.com/org-roam/org-roam/wiki/V2-Binary-emacsql-sqlite.exe-for-Windows)

**Comment by nobiot** [comment]
Install msys2 as instructed on its official website

Within msys2, install gcc (via command pacman -S; the instruction on the webiste)

On Windows, add C:\msys64\usr\bin (command where gcc in MSYS2 terminal can tell you the directory) to PATH in your environmental variables

On Emacs, install emacsql-sqlite package and start Org-roam (v2)

Emacs will start compiling the executable automatically

**Comment by pinacle2000** [comment]
My emacs + roam v1 & v2 + sqlite3 worked fine untill I made the update yesterday. I tried emacs --debug, and it shows
```
Debugger entered--Lisp error: (emacsql-timeout "Query timed out" 30)
  signal(emacsql-timeout ("Query timed out" 30))
  #f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0x1d5cf7d>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-3b7592c>)
  apply(#f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0x1d5cf7d>) #<emacsql-sqlite-connection emacsql-sqlite-connection-3b7592c> nil)
  emacsql-wait(#<emacsql-sqlite-connection emacsql-sqlite-connection-3b7592c>)
  #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x1d5f7c1>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-3b7592c> [:select [file hash] :from files])
  apply(#f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x1d5f7c1>) #<emacsql-sqlite-connection emacsql-sqlite-connection-3b7592c> [:select [file hash] :from files])
  emacsql(#<emacsql-sqlite-connection emacsql-sqlite-connection-3b7592c> [:select [file hash] :from files])
  apply(emacsql #<emacsql-sqlite-connection emacsql-sqlite-connection-3b7592c> [:select [file hash] :from files] nil)
  org-roam-db-query([:select [file hash] :from files])
  org-roam-db--get-current-files()
  org-roam-db-sync()
```

It seems the cause is emacsql. I'll have a try on sqlite instead of sqlite3.

**Comment by nobiot** [comment]
Yes, I suggest you try the sqlite option with emacsql-sqlite, not emacsql-sqlite3. 

Ideally you should compile the exe file yourself but you could quickly try the binary I created in the link from the other post you referenced. This is my repo anyway — both instruction and the binary file are available in the repo.

**Comment by pinacle2000** [comment]
> Yes, I suggest you try the sqlite option with emacsql-sqlite, not emacsql-sqlite3.
> 
> Ideally you should compile the exe file yourself but you could quickly try the binary I created in the link from the other post you referenced. This is my repo anyway — both instruction and the binary file are available in the repo.

I was wrong. I just found I had been using your emacs-sqlite and roam default connection, i.e. not sqlite3. Though I downloaded sqlite3 and put it in my PATH before. Anyway, the problem remains unchanged.

**Comment by jethrokuan** [comment]
try @nobiot 's compiled sqlite binary, seems to work for many others: https://github.com/org-roam/org-roam/wiki/V2-Binary-emacsql-sqlite.exe-for-Windows

**Comment by pinacle2000** [comment]
> try @nobiot 's compiled sqlite binary, seems to work for many others: https://github.com/org-roam/org-roam/wiki/V2-Binary-emacsql-sqlite.exe-for-Windows

As my last post said, I found I have been using this from v1 to v2 till not working two days ago.

**Comment by nobiot** [comment]
@pinacle2000, 

As Jethro does not have access to Windows, he cannot analyze the issue you are facing. 

I cannot reproduce it on my Windows machine. I also tried with minimum Org-roam settings at the most up-to-date version from MELPA today (org-roam-20211215.848). This is without Doom.

This means, as far as we know, it happens only on your Windows machine. Therefore, unfortunately, we don't have many options to offer:

1. Try Jethro's suggestion
2. Remove Doom (or use Doom's sandbox (?)) and try to reproduce the issue with only Org-roam
3. Find a way for me or other Windows users to reproduce your issue on their machine

It looks to me that Option 1 requires the least amount of efforts on your end -- we don't know if it changes anything, though.

**Comment by pinacle2000** [comment]
I tried the sqlite3 way but not working. Is it possible because of win11? I will try to do a fresh installation of emacs and test when I get some time. Thanks for all your kind help.

**Comment by nobiot** [comment]
`sqlite3` does not work ([this comment](https://github.com/org-roam/org-roam/issues/2007#issuecomment-996512740)  above).

Use the default `sqlite` option. But compile the new `emacsql-sqlite.exe` or use the one I complied and share in the repo as Jethro suggests. The exe file should be put into the specified folder (if you don’t know where it should be, read my instruction in the repo).

Someone has reported that my exe file has worked with Windows 11, so I don’t see an issue with it.

If what Jethro and I have been saying does not make sense to you, let us know. I am not at the PC now and can’t show screen shots of you my screen…

**Comment by pinacle2000** [comment]
I made several tests and now the case becomes:
1. doom emacs loads well and org roam v2 loads well (e.g. when I find node), if I don't use "use-package" in my config.el and just 
```
  (setq org-roam-directory "~/Documents/org-roam/")
  (setq org-roam-db-location (expand-file-name "my-org-roam.db" org-roam-directory))
```
2. doom emacs hangs if I use:
(use-package! org-roam
  :custom
  (org-roam-directory "~/Documents/org-roam/")
  (org-roam-db-location (expand-file-name "my-org-roam.db" org-roam-directory)))

I keep the org-roam configuration as minimum as above two variable settings. @nobiot any suggestion?

**Comment by nobiot** [comment]
Is the syntax of `:custom` in `use-package!` correct?
I don't use Doom so I can't really confirm but I thought you needed a "." (dot) between the variable name and value you would like to set to; thus:
```
(use-package! org-roam
  :custom
  (org-roam-directory . "~/Documents/org-roam/")
  (org-roam-db-location . (expand-file-name "my-org-roam.db" org-roam-directory)))
```

**Comment by nobiot** [comment]
It's probably quicker and more likely for you to get a correct response from the Doom community.

**Comment by jethrokuan** [comment]
I'm not sure if the `:custom` portion does `let*` bindings, so it could be setting your `org-roam-db-location` in a weird place too.

**Comment by pinacle2000** [comment]
I am newbie and just copy&paste some configuration by someone's instruction. I checked again the roam readme and realized it is not instructed the way I am using roam. So I am closing this issue. Thanks for your help.
