### ISSUE TITLE
Convert In-file Node to File Node

### ISSUE THREAD

**Issue by joshcho** [org-roam/org-roam#2019]
### Brief Abstract
ID-based nodes introduced in v2 is highly useful. It allows for multiple nodes in a single file. Converting them from in-file node to a separate file node would be useful as a function.

### Proposed Implementation
I am not an elisp hacker, but I don't think this should be too difficult. I may create a pull request if nobody else does.

### Please check the following:

- [x] No similar feature requests

I may have missed something.

**Comment by nobiot** [comment]
Does this existing function fulfil your requirements?

https://github.com/org-roam/org-roam/blob/ee9a8d423e24923ec60c3116a00c8a0e93095d86/org-roam-node.el#L898

**Comment by joshcho** [comment]
Yes! Thank you very much
