### ISSUE TITLE
How am I supposed to create a ref node?

### ISSUE THREAD

**Issue by deshearth** [org-roam/org-roam#2023]
I saw `org-roam-capture-ref-templates` exists but there is no function to create a ref node. I expect `org-roam-ref-find` to create a new ref node when I enter some new file names as `org-roam-node-find`. But it needs match results. In other words, it can only open existing ref nodes.

**Comment by nobiot** [comment]
Add a `ROAM_REFS` property to a node. You can simply type or use command `org-roam-ref-add`.

**Comment by deshearth** [comment]
I saw that. But that requires a few extra key stroke if I plan to add a ref nodeI in the first place.

**Comment by nobiot** [comment]
@deshearth You can have your own custom capture template for ref. 

If you would like org-roam-ref-find to have a feature to be able to create a new node, then it would be a new feature request.

**Comment by deshearth** [comment]
I see. I may try customizing capture templates. Thanks!
