### ISSUE TITLE
db-clear-all followed by db-sync for second instance org-roam directory adds links to first instance

### ISSUE THREAD

**Issue by zhewy** [org-roam/org-roam#2024]
### Description

second instance/directory of org-roam running, otherwise fine and working as expected, setup per 18.1 org-roam manual. If I do a org-roam-db-clear-all followed by a org-roam-db-sync, org-roam-node-find from the second instance does not see available nodes, instead org-roam-node-find from first instance now includes.

#### Steps to Reproduce
1. Visit one of the Org files in the first instance’s directory
2. org-roam-node-find ok.
3. Visit one of the Org files in the second instance’s directory
4. db-clear-all
5. db-sync
6. org-roam-node-find shows only open/visited nodes
7. Visit one of the Org files in the first instance’s directory
8. org-roam-node-find shows nodes that should be showing in second instance

ref also: https://org-roam.discourse.group/t/org-roam-node-find-not-seeing-existing-nodes-after-doing-db-clear-all-followed-by-db-sync-for-additional-org-roam-directory/2327

#### Expected Results

org-roam-node-find from second instance shows all available nodes from second instance

#### Actual Results

org-roam-node-find from second instance shows limited set of nodes
org-roam-node-find from first instance shows incorrect/missing nodes from second instance

### Environment
GNU Emacs 27.2
Org mode version 9.5.2
Org-Roam version: 679ef6ef001fd1a69b691108178721aa913e7f0f

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
Probably related to #1917

**Comment by zhewy** [comment]
fixed with #2033
