### ISSUE TITLE
Sync Database on capture finish

### ISSUE THREAD

**Issue by xeruf** [org-roam/org-roam#2026]
When I finish capturing a new node, I would like to auto-update the database. I probably can use some kind of hook for that?

**Comment by jethrokuan** [comment]
The database should only be in sync with what's actually written on disk, so if you want to update the database after capture, you need to invoke a save on the file for the new node.

This is typically already the case if you have `org-roam-db-autosync-mode` enabled and you don't have `:no-save t` in your capture templates.

**Comment by xeruf** [comment]
I usually don't have that enabled because it causes lag on big files. As said, I would like to have it specifically for captures.

**Comment by jethrokuan** [comment]
I guess you can try using `org-capture-after-finalize-hook`; calling `org-roam-db-update-file` if `org-roam-file-p`.

**Comment by xeruf** [comment]
Thanks for the help, I think this is it :)
```elisp
(add-hook 'org-capture-after-finalize-hook (lambda () (if (org-roam-file-p) (org-roam-db-sync))))
```
