### ISSUE TITLE
Identical id link under outline produce two different backlink content

### ISSUE THREAD

**Issue by czqhurricnae** [org-roam/org-roam#2029]
### Description
Identical id link under outline produce two different backlink content.
#### Steps to Reproduce
I use https://github.com/nobiot/org-transclusion this package to transclude some id link.

1. `bar` file contents:
```
section.
section.

* First outline
org transclude

* Second outline
- [[id:0EC84816-9B40-4AF3-9964-12463699A63C][foo]]
- two two
- three three

#+transclude: [[id:0EC84816-9B40-4AF3-9964-12463699A63C][foo]] 
```
The keyword `#+transclude` is used by org-transclusion to include contents.
2. `foo` fiile content:
```
foo foo foo.
```
3. `foo` file backlinks buffer:
![image](https://user-images.githubusercontent.com/20676402/148575439-920bc5e3-6ae2-40ed-96fe-c2643be4cd22.png)

#### Expected Results

Maybe the first one backlink in the picture is correct, and the second one is redundant and not correct.

#### Actual Results

The identical id link cause different backlink content as the picture shows.

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.0.0, Carbon Version 158 AppKit 1671)
 of 2020-10-24
- Framework: Spacemacs
- Org: Org mode version 9.5.1 (9.5.1-g36086a @ /Users/c/.emacs.d/elpa/27.1/develop/org-9.5.1/)
- Org-roam: 2.1.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by nobiot** [comment]
For the second wrong backlink preview content, is the transclusion added? If so, what happens when it’s removed?

**Comment by czqhurricnae** [comment]
The second backlink preview content is added by the transclusion, once it's removed, the related second preview content is gone。

**Comment by nobiot** [comment]
So the user can control the behaviour. It sounds like a good thing to me: depending on whether or not the user adds or removes the transclusion in question, the backlink content changes accordingly.

What do you see as a problem? How should the transclusion behave in this case in your view?

**Comment by czqhurricnae** [comment]
Because both of normal id link and transclusion id link is all the same, so this link cities foo the same file content in the context of the second outline. 

But the backlink buffers in the foo file are different.The first one tell me bar file cities foo file under the second outline.
And the second one tell me bar file cities foo file at the very beginning of all outlines.

But actually both of these two id links are under the bar file's second outline.

These two different results make me feel confused.

Itn my opinion the first one backlink should be only kept.

**Comment by nobiot** [comment]
I see. It's a little complicated but I seem to be able to reproduce the issue you report.
But it is not caused by Org-transclusion. The links after any keyword (`#+keyword`) have the same issue.

See the screen shots below to compare the following three different cases:

1. Normal Org-ID link: `[[id:org-id][foo]]`
2. The same Org-ID as a value in property of a drawer (`:drawer:`)
3. The same Org-ID as a value of a keyword (`#+keyword`)

**Case 1. Normal link**
![Screenshot from 2022-01-09 19-13-10](https://user-images.githubusercontent.com/12507865/148695651-07c8567d-0f51-4f35-b1a1-adfafe5eca6b.png)

**Case 2. Drawer**
![Screenshot from 2022-01-09 19-13-49](https://user-images.githubusercontent.com/12507865/148695676-cbc61dd2-0bd4-417b-8342-1cf7b2d2bcd6.png)

**Case 3. Keyword**
![Screenshot from 2022-01-09 19-12-49](https://user-images.githubusercontent.com/12507865/148695699-b23f8d6d-a86d-4951-b87e-0cd93ae91b4e.png)

<details>
<summary>Testing Environment (Vanilla)</summary>

``` emacs-lisp

;; cd path/to/dir
;; emacs -Q -l ./add-load-path.el
;; Org version: 9.5

;; add-load-path.el

(add-to-list 'load-path (expand-file-name "org-roam-20220102.603" "~/.config/emacs/elpa"))
(add-to-list 'load-path (expand-file-name "f-20210624.1103" "~/.config/emacs/elpa"))
(add-to-list 'load-path (expand-file-name "s-20210616.619" "~/.config/emacs/elpa"))
(add-to-list 'load-path (expand-file-name "dash-20210826.1149" "~/.config/emacs/elpa"))
(add-to-list 'load-path (expand-file-name "magit-section-20220101.841" "~/.config/emacs/elpa"))
(add-to-list 'load-path (expand-file-name "emacsql-20220101.1820" "~/.config/emacs/elpa"))
(add-to-list 'load-path (expand-file-name "emacsql-sqlite-20220101.1820" "~/.config/emacs/elpa"))
(add-to-list 'load-path (expand-file-name "org-transclusion-1.1.1.0.20220108.205254" "~/.config/emacs/elpa"))

(require 'org-roam)
(require 'org-transclusion)

(setq org-roam-directory (file-truename "~/src/org-roam-transclusion-test"))
(setq org-roam-db-location "~/src/org-roam-transclusion-test/org-roam.db")
(setq org-id-locations-file "~/src/org-roam-transclusion-test/.org-id-locations")

;;; Org-roam
(define-key global-map (kbd "C-c n /") #'org-roam-node-find)
(define-key global-map (kbd "C-c n c") #'org-roam-capture)
(define-key global-map (kbd "C-c n i") #'org-roam-node-insert)
(define-key global-map (kbd "C-c n l") #'org-roam-buffer-toggle)

;;; Org-transclusion
(define-key global-map (kbd "<f12>") #'org-transclusion-add)
(define-key global-map (kbd "S-<f12>") #'org-transclusion-mode)

(org-roam-db-autosync-mode 1)
```
</details>

**Comment by nobiot** [comment]
> In my opinion the first one backlink should be only kept.

For this, one thing you could do on your end is to override the function `org-roam-db-map-links` and remove the following part so that Org-roam would ignore links in `#+transclude:`:

https://github.com/org-roam/org-roam/blob/master/org-roam-db.el#L360-L372

**Comment by czqhurricnae** [comment]
Thanks for your solution, It works as I expect now.
