### ISSUE TITLE
Prefer lowercase properties?

### ISSUE THREAD

**Issue by lionel-** [org-roam/org-roam#2031]
I find the property list at the beginning of a node to be noisy in large part because the properties are uppercase. I now systematically lowercase them.

Would it make sense to prefer lowercase properties, just like org-roam prefers lowercase keywords (see #768)?

```org
:properties:
:id:       DBEDFF26-63AC-48DC-B9A3-3E45BC905377
:end:
#+title: Title
```

**Comment by nobiot** [comment]
My experience with Org is that you should still be using upper case for properties (`:PROPERTIES:`).

It seems that some frequently used Org commands, such as `org-sparse-tree` ( `C-c /` by default), differentiate `:CATEGORY:` vs `:category:` -- you can try it yourself. Org's sparse tree search seems to find the value for only the upper case property name `CATEGORY`.

If you use `org-sparse-tree`, and potentially `org-agenda` (I don't  use it), you might like to be careful of the case-sensitive nature in these standard Org facilities. My observation has been with Org v9.4, v9.5, and for testing purposes v9.6.

**Comment by lionel-** [comment]
Thanks for your input. Let's revisit this in the future when/if lowercase props are better supported.
