### ISSUE TITLE
Unexpected dynamic rebinding of `org-roam-directory` when capturing daily

### ISSUE THREAD

**Issue by chrisbarrett** [org-roam/org-roam#2032]
### Description

`org-roam-dailies--capture` is dynamically rebinding `org-roam-directory`. I'm not sure if this is intentional.

I encountered this when hooking into the dailies creation process and noticed `org-roam-dailies--daily-note-p` wasn't working as expected.

https://github.com/org-roam/org-roam/blob/66e10df943e49ca45e39788627c67e3506c84bfb/extensions/org-roam-dailies.el#L306

Edit: I realise I'm a bad person for depending on internal functions. I've got a workaround, just thought I'd flag it. :)

### Environment

- Emacs: GNU Emacs 29.0.50 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559))
- Framework: N/A
- Org: Org mode version 9.5.2 (9.5.2-gfbff08 @ /nix/store/k623bls1x7j2z0y2b0bhxh2xal7ac6j9-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.5.2/)
- Org-roam: 2.1.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/66e10df943e49ca45e39788627c67e3506c84bfb

**Comment by jethrokuan** [comment]
This is intentional, so all of org-roam-captures' functionality is now relative to the org-roam-dailies directory instead of the base org-roam-directory. Let me know if there's a better way around this!

**Comment by chrisbarrett** [comment]
Thanks for the reply. 👍 It's all good. 

I observed that `org-roam-dailies--daily-note-p` was broken when in the context of a capture--the dailies directory gets appending to the path twice, so checking whether a note is in the dailies directory no longer works:

- `org-roam-directory` is rebound within the capture process to the dailies dir
- `org-roam-dailies--daily-note-p` always internally tries to expand `org-roam-directory`
- therefore within a capture you get a path ending with `dailies/dailies` (or whatever), so the predicate no longer works.
 
It's surprising but it's not part of the external API so it barely counts as a bug. 😅 I'll leave it there.

Thanks for org-roam. ❤️

**Comment by chrisbarrett** [comment]
My use case is building an evergreen notes+spaced repetition review system on top of org-roam for my personal system.

Code here in case such a use case ever comes up again:
https://github.com/chrisbarrett/.emacs.d/blob/master/lisp/org-roam-review.el
