### ISSUE TITLE
What is the variable to set to not see an org-roam buffer at startup?

### ISSUE THREAD

**Issue by Macavirus** [org-roam/org-roam#2035]
I've searched through available variables for this package, but no matter what I set my emacs always boots with an org-roam buffer on the right side. I would like to have no org-roam buffer until explicitly invoking it.

**Comment by nobiot** [comment]
You are using Doom, aren’t you?
Have a look at [this](https://github.com/hlissner/doom-emacs/blob/86034131c49d38922ccd49db1ac3defc6a53646f/modules/lang/org/contrib/roam2.el#L88).

The standard Org-roam does not open the org-roam buffer automatically.

**Comment by Macavirus** [comment]
Good spot, thanks @nobiot!

For the next reader: the fix is to add this to your config:
```emacs-lisp
(setq +org-roam-open-buffer-on-find-file nil)
```

It does seem like a bug that this would execute on boot though, but that's probably something unique to Doom Emacs startup or the `ui/doom-dashboard` module specifically, as by default no find-file operations should occur.
