### ISSUE TITLE
Newline at end of completion candidates for org-roam-node-find

### ISSUE THREAD

**Issue by spwhitton** [org-roam/org-roam#2044]
The completion candidates for `org-roam-node-find` seem to have newline characters on the end of them.  I use `fido-mode` with `icomplete-prospects-height` set to 1, and thus none of the completion candidates show up.  If I set `icomplete-prospects-height` to a higher value, I get something which looks like this: ![roam-candidates](https://user-images.githubusercontent.com/692648/149681416-c5b5c72e-f5e9-4012-8f74-134fd9ab5705.png) Note that I am *not* using `fido-vertical-mode`, so it should not be one completion candidate per line like this.  Thanks.

**Comment by jethrokuan** [comment]
Can you try

```
(setq org-roam-node-display-template "${title}")
```

**Comment by spwhitton** [comment]
This works.  Thanks.  Am I meant to set that in my init, such that there
isn't a bug here?

-- 
Sean Whitton

**Comment by jethrokuan** [comment]
Yes, the default template is optimized towards vertical completion frameworks: we use spacing for aligning different components of the node. This seems to be the majority choice amongst users.

**Comment by spwhitton** [comment]
Cool.  Happy to set it in my init.  But perhaps this could be documented
somewhere?  Thank you again.

-- 
Sean Whitton

**Comment by spwhitton** [comment]
Thanks again!

On Tue 18 Jan 2022 at 03:56PM -08, Jethro Kuan wrote:

> Closed #2044 via #2047.

-- 
Sean Whitton
