### ISSUE TITLE
Enable using the IDs as file names

### ISSUE THREAD

**Issue by a12l** [org-roam/org-roam#2048]
### Brief Abstract

I want to be able to name my Org Roam files with their IDs.

### Long Description

I would like to create templates like this

```
(setq org-roam-capture-templates '(
  ("d" "default" plain "%?"
   :target (file+head "${id}.org"
                      "#+title: ${title}\n")
   :unnarrowed t))
)
```

and have the ID as the file name. I'm currently prompted for the "id", which I guess is because the ID isn't created yet at the "creation moment" going on  `org-roam-capture-templates`'s documentation

> In addition to all of the above, Org-roam supports additional
substitutions within its templates. "${foo}" will look for the
foo property in the Org-roam node (see the ‘org-roam-node’). If
the property does not exist, the user will be prompted to fill in
the string value.

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
This should be possible on latest master, feel free to reopen if otherwise.
