### ISSUE TITLE
org-roam-refile cannnot create new node

### ISSUE THREAD

**Issue by stshine** [org-roam/org-roam#2058]
### Description

When running `org-roam-refile`, you can only refile to an existing node instead of creating new one.

#### Steps to Reproduce

1. Load Emacs
2. Move cursor to an org heading
3. Run `org-roam-refile`
4. Enter a new node name

#### Expected Results

A new node with the name is created and contents refiled to it.

#### Actual Results

"No match" message displayed in minibuffer.

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-w64-mingw32)
 of 2021-08-27
- Framework: 
- Org: Org mode version 9.4.4 (release_9.4.4 @ c:/msys64/mingw64/share/emacs/27.2/lisp/org/)
- Org-roam: 2.2.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/6f5d65abd9e707b3fdb10092a9fef3b739e143dd

**Comment by Hrothgar32** [comment]
I'm also interested in this, since I also many times create manually a new node, just to be able to refile to it. As I see in the source code of the function however, this is intentional, why is that?

**Comment by stshine** [comment]
> Is `org-roam-extract-subtree` what you want? That will create a new file-node.

It works nice! However there are still some bugs, e.g. title are not in the correct place.

**Comment by Delapouite** [comment]
Hi.

The link merged PR by jmay appears to have fixed the problem.
If that's not the case don't hesitate to reopen this issue. Thanks.
