### ISSUE TITLE
Make org-roam-node-random' filter-fn optional

### ISSUE THREAD

**Issue by PRESFIL** [org-roam/org-roam#2062]
### Brief Abstract

After #2022, it is not possible to get a random note without a filter function, it is inconvenient to use it
with `M-x`. Please make `filter-fn` parameter of `org-roam-node-random` optional as before #2022.

### Please check the following:

- [x] No similar feature requests

**Comment by jethrokuan** [comment]
Closed with #2063

**Comment by PRESFIL** [comment]
Thanks!
