### ISSUE TITLE
Error after upgrading to 2.2.0: (void-function file) 

### ISSUE THREAD

**Issue by kai17** [org-roam/org-roam#2064]
Upgrading org-roam-20211122.801 to  org-roam-20220126.554 throws an error and leaves org-roam unusable. emacs --debug-init gives me:

Debugger entered--Lisp error: (void-function file)
  file(nil)
  org-roam-db-sync()
  org-roam-db-autosync-mode(1)
  org-roam-setup()
  eval-buffer(#<buffer  *load*> nil "/home/kai/.emacs" nil t)  ; Reading at buffer position 92900
  load-with-code-conversion("/home/kai/.emacs" "/home/kai/.emacs" t t)
  load("~/.emacs" noerror nomessage)

Reverting to org-roam-20211122.801 takes me back to a usable state where everything is as before . I wonder if this has anything to do with the support for sqlite3, but I'm too much of a noob to figure this out.

**Comment by jethrokuan** [comment]
The most likely case is that your download from MELPA was corrupted/interrupted halfway, so you can just try again.

**Comment by kai17** [comment]
I retried installing 20220221.51 from MELPA several times on two machines and still get this error. Any pointers re how to solve this would be much appreciated.


Debugger entered--Lisp error: (void-function file)
  file(nil)
  org-roam-db-sync()
  org-roam-db-autosync-mode(1)
  org-roam-setup()
  eval-buffer(#<buffer  *load*> nil "/home/kai/.emacs" nil t)  ; Reading at buffer position 92857
  load-with-code-conversion("/home/kai/.emacs" "/home/kai/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x772b59>) #f(compiled-function () #<bytecode 0x772b6d>) t)
  command-line()
  normal-top-level()

**Comment by jethrokuan** [comment]
Did you delete your byte-compiled versions?

**Comment by kai17** [comment]
I re-installed the new version from melpa and moved the old version to a
backup directory. As far as I can tell, there are no old byte-compiled
files in my load path. Once I remove the 2.2 directory and restore the old
version from backup, everything works fine again.

**Comment by kai17** [comment]
Found the problem: I was still stuck on org-mode 9.4 for some reason I cannot quite fathom. Once I upgraded to 9.5.2, I could upgrade org-roam to 2.2.0, and so far, everything seems to work fine. Big thank you to you personally and to the wider community for developing org-roam!
