### ISSUE TITLE
Cache the list passed to completing-read

### ISSUE THREAD

**Issue by chunglak** [org-roam/org-roam#2069]
I have a directory with over 20000 nodes (lots of auto-generated stuff) and org-roam-node-find is unbearably slow (takes like a minute).
I see in the code that at each call to this function not only the whole database is read but the display string for each node is recomputed.
Could we store the result of org-roam-node-read--completions in a cache as long as the db hasn't changed?

I'm not so fluent in elisp but I guess we can implement the cache and check in org-roam-node-read--completion? Would that work?

**Comment by jethrokuan** [comment]
> Could we store the result of org-roam-node-read--completions in a cache as long as the db hasn't changed?

We could, but I don't think this is the bottleneck anymore. I think a lot more time is spent passing through the node-list, filtering and sorting them.

Do you really need the auto-generated stuff to be cached by Org-roam?

**Comment by chunglak** [comment]
I didn't mean caching the results from the db query, but the result of calling  org-roam-node-read--completions that filters, sorts and create the display strings from the template.
I do need all my nodes, the auto-generated ones are still "real" nodes (reference to books, movies, papers etc)

I did a quick hack below. Seems to work. However, each time I make an update to the db, it needs to rebuild everything, so that's slow. Anyway, it's better than nothing and simple to do. Ideally, the db would keep track of when each node is updated (not just the file as is the case now) so that we need only to update the nodes that have changed. I kind of did that with some external python helpers (not fluent enough in elisp)

`
(with-eval-after-load "org-roam"
  (setq org-roam-cache-ts 0
        org-roam-cached-nodes nil)
  ;; save the original update function;
  (setq org-roam-node-read--completions-original (symbol-function 'org-roam-node-read--completions))
  (defun org-roam-node-read--completions (&optional filter-fn sort-fn)
    "Return an alist for node completion.
The car is the displayed title or alias for the node, and the cdr
is the `org-roam-node'.
FILTER-FN is a function to filter out nodes: it takes an `org-roam-node',
and when nil is returned the node will be filtered out.
SORT-FN is a function to sort nodes. See `org-roam-node-read-sort-by-file-mtime'
for an example sort function.
The displayed title is formatted according to `org-roam-node-display-template'."
    (let* (
           (attr (file-attributes org-roam-db-location))
           (mtime (time-convert (file-attribute-modification-time attr) 'integer))
           )
      (when (> mtime org-roam-cache-ts)
        (setq
         org-roam-cached-nodes (funcall org-roam-node-read--completions-original filter-fn sort-fn)
         org-roam-cache-ts mtime))
      org-roam-cached-nodes
      )
    )
  )
`

**Comment by jethrokuan** [comment]
> I didn't mean caching the results from the db query, but the result of calling org-roam-node-read--completions that filters, sorts and create the display strings from the template.

Yes, but this cache needs to be keyed to the value of `filter-fn` and `sort-fn`. It just happens that you're probably using neither.

**Comment by chunglak** [comment]
True, my code only uses the filter-fn and sort-fn passed to it whenever it needs to update, but I've never had the use of filter-fn and sort-fn until now.
Anyway, it's fine if it's not a priority as I understand I have an ususual number of nodes, I'll just keep my hacks because I find org-roam invaluable. Thanks for the feedback
