### ISSUE TITLE
ROAM_REFS gives "Invalid ref xxx"

### ISSUE THREAD

**Issue by simendsjo** [org-roam/org-roam#2073]
### Description

Not really sure how to reproduce. Several of my notes gives this error, and I get it when creating new nodes.

```
Warning (org-roam): /home/simendsjo/profiles/notes/20220201201035-testnode.org:1	Invalid ref testnode, skipping... Disable showing Disable logging
```

```emacs-lisp
:PROPERTIES:
:ID:       ef273e08-c2c1-410b-b618-88a42fc29331
:ROAM_REFS: testnode
:END:
#+title: testnode
```

Using emacs 28.0.91 with natice compilation.
org-roam commit c7753adbb301dcb647dc96d182c28b228551890e

**Comment by jethrokuan** [comment]
This is expected behaviour on master right now: refs for now are plain links (e.g. websites, citations). The reason is that refs are only useful if you can link to them in other nodes.
