### ISSUE TITLE
HELP! How to make ((id:)) has the same meaning as [[id:]] so that I could let logseq block reference make sense in org-roam

### ISSUE THREAD

**Issue by WaytrueDeng** [org-roam/org-roam#2074]
Happy Lunar New Year, I am so sorry to bother you guys for this useless question, but I have tried search in Google, there is no any help, I have to ask here

**Comment by jethrokuan** [comment]
No easy way, you'll have to mangle with Org's internals to get it to recognize that syntax as links. You can post this question on the Discourse channel or Logseq's discord instead.
