### ISSUE TITLE
org-roam-node-find with vertico - can't create new node if text matches existing node

### ISSUE THREAD

**Issue by mgraham** [org-roam/org-roam#2081]
### Description

When I have `vertico-mode` off, org-roam behaves as expected.

When I have `vertico-mode` on, I can't create a new node with a title that is a substring of an existing node.  

I can use `org-roam-node-find` and `org-roam-node-insert` to pick nodes from the list of nodes, and I can also create new nodes - _as long as the title text does not match an existing node's title_.  If the text typed in matches any node in the list, then org-roam does not create a new node, it uses the matched node.

#### Expected Results
* first call to `org-roam-node-find` creates a node called `programming languages`
* second call to `org-roam-node-find` creates a node called `programming`

#### Actual Results

* first call to `org-roam-node-find` creates a node called `programming languages`
* second call to `org-roam-node-find` loads the existing node `programming languages`

### Environment

```- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95))
 of 2021-03-27
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-gd70f28 @ /Users/michael/.config/dotfiles/config/emacs/emacs.d/straight/build/org/)
- Org-roam: v2.2.0-16-geed1df9
```

**Comment by jethrokuan** [comment]
You can, just `C-p` to select your input line, and press enter.

**Comment by mgraham** [comment]
Oh - thank you, that works!  I guess that's the same as cursor up, which also works.
