### ISSUE TITLE
New note default ID generation doesn't update org-mode ID database

### ISSUE THREAD

**Issue by Jdogzz** [org-roam/org-roam#2083]
### Brief Abstract
It would be good if org-roam-capture- could use "org-id-get-create" instead of "org-id-new" so that org-mode's ID database is updated.

### Long Description
I was reviewing the way org-roam generates IDs for new notes and found that the org-roam-capture- function uses "org-id-new" instead of "org-id-get-create":

[https://github.com/org-roam/org-roam/blob/ccfa97ec3a70634bced494149eb85809a6e47cfb/org-roam-capture.el#L411](https://github.com/org-roam/org-roam/blob/ccfa97ec3a70634bced494149eb85809a6e47cfb/org-roam-capture.el#L411)

From what I understand, org-id-new simply returns a new ID:

[https://github.com/tkf/org-mode/blob/master/lisp/org-id.el#L323](https://github.com/tkf/org-mode/blob/master/lisp/org-id.el#L323)

However, org-id-get-create is the one that takes that ID (by first calling org-id-new) and updates org-mode's ID database:

[https://github.com/tkf/org-mode/blob/master/lisp/org-id.el#L227](https://github.com/tkf/org-mode/blob/master/lisp/org-id.el#L227)

It would be useful if org-id-get-create was used instead of just org-id-new so that the org-mode ID database is updated on the spot.

However, this appears to be a change from how part of org-roam used to work. Tracing recent history shows capture did at one time have org-id-get-create before its removal:

[https://github.com/org-roam/org-roam/pull/2049](https://github.com/org-roam/org-roam/pull/2049)

and later changed to its current form:

[https://github.com/org-roam/org-roam/pull/2052](https://github.com/org-roam/org-roam/pull/2052)

### Please check the following:

- [ ] No similar feature requests

**Comment by nobiot** [comment]
I believe these two conditions will need to be met:
1. The new Org ID must be available to other functions during the capture process
2. Adding the new Org ID must be done after "Abort" check
  That is when the user aborts the capture process, the new ID must not be added to the Org ID file and hash database

Currently, Condition 1 has been met. A fix will need to meet Condition 2 in addition.
To do this, the following change seems to work. Lightly tested. When I have more time, I'd create a PR but putting here as a discussion starter -- @jethrokuan , thoughts?

`org-roam-capture.el`
``` diff
@@ -714,6 +714,7 @@
         (when (find-buffer-visiting new-file)
           (kill-buffer (find-buffer-visiting new-file)))
         (delete-file new-file))
+    (org-id-add-location (org-roam-capture--get :id)(org-roam-capture--get :new-file))
     (when-let* ((finalize (org-roam-capture--get :finalize))
                 (org-roam-finalize-fn (intern (concat "org-roam-capture--finalize-"
                                                       (symbol-name finalize)))))
```

**Comment by Jdogzz** [comment]
This worked! Thank you very much for your help.
