### ISSUE TITLE
Prevent deletion of manually saved captures during accidental abort of org-roam-capture

### ISSUE THREAD

**Issue by refset** [org-roam/org-roam#2094]
I lost a bunch of notes when using `org-roam-capture` that I assumed would had been safely written after a manual `:w` (evil-mode save command) - but unfortunately the file was deleted when I unthinkingly closed the buffer a few hours later with `:q` (evil-mode close buffer command) ...instead of using `C-c C-c` as clearly instructed - my mistake! However, it would be nice if this wasn't such a painful lesson for other new users - perhaps `org-roam-capture` could detect manual writes and assume that the user probably wouldn't want to then abort.

**Comment by nobiot** [comment]
Could it be an issue of `evil-mode` or your configuration should be somehow adjusted?

If I try to kill a capture buffer or Emacs while it is unsaved, I get asked if I want to save it or not.
I can also save the capture buffer before C-c C-c. In this case, the file is written.
Either way, I don't think I can reproduce the problem without `evil-mode` (I don't use it).

![Screenshot from 2022-02-16 17-31-43](https://user-images.githubusercontent.com/12507865/154312060-c39990b0-0598-4c28-8e29-6f82a6c4e113.png)

**Comment by jethrokuan** [comment]
I can confirm this bug, but I can't think of a trivial fix right now.

**Comment by refset** [comment]
Thank you @jethrokuan :pray: - that fix looks great!

**Comment by nobiot** [comment]
@refset :)
I tried looking to understand why it was working for me without this fix; I could not get the answer....
