### ISSUE TITLE
org-open-at-point doesn't work with org-cite links in ROAM_REFS line

### ISSUE THREAD

**Issue by telotortium** [org-roam/org-roam#2095]
### Description

I've added an org-cite citation link to this Org-Roam node:

```
#+bibliography: cites.bib
#+date: [2022-02-16 Wed 15:57]

* How to Cite a Website with BibTeX – Homepage von Jonas Mönnig
:PROPERTIES:
:ID:       16a97b7b-4738-4c61-95ba-f234522c6d05
:ROAM_REFS: [cite:@jonas2016How] https://jonas-moennig.de/how-to-cite-a-website-with-bibtex/
:END:
```

The `cites.bib` file contains this citation:

```
@online{jonas2016How,
    author = {jonas},
    title = {How to Cite a Website with BibTeX},
    year = 2016,
    url = {https://jonas-moennig.de/how-to-cite-a-website-with-bibtex/},
    urldate = {2022-02-16}
}
```

If I put the point over the `cite:` link and call `org-open-at-point` (i.e., C-c C-o), it appears to interpret the citation as an email address, and opens up a mail buffer to `cite:@jonas2016How`. Interestingly, if I copy the `[cite:@jonas2016How]` text out of `ROAM_REFS` to the body and call `org-open-at-point`, it opens to the location of the citation in `cites.bib`, as expected.

Also, I see the same issue as #1938 

```
Warning (org-roam): /Users/bytedance/Documents/org/home-org/roam/how_to_cite_a_website_with_bibtex_homepage_von_jonas_monnig.org:59	Invalid ref [cite:@jonas2016How], skipping... Disable showing Disable logging
```

#### Expected Results

Opening link in ROAM_REFS opens citation file, doesn't produce warning.

#### Actual Results

Opening link in ROAM_REFS opens email buffer, produces warning.

### Environment

- Emacs: GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.3.0, NS appkit-2113.30 Version 12.2 (Build 21D49))
 of 2022-02-04
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-e7ea951ac @ /Users/bytedance/.doom.d/doom.emacs.d/.local/straight/build-29.0.50/org/)
- Org-roam: 2.0.0

- Org-roam commit: https://github.com/org-roam/org-roam/commit/5dce6261a2a45798cdf0c65371b76c83dd5b1de6

**Comment by jethrokuan** [comment]
The error you're seeing in #1938 is because your version of Org-roam is too old. The reason why you're unable to visit cite-links in ROAM_REFS is that they're not supported by Org-mode within property drawers, it's not an Org-roam issue.

**Comment by telotortium** [comment]
Thanks for responding - annoying that I can't visit the links in property drawers. Feel free to reopen if you want to track this for some reason.
