### ISSUE TITLE
Feature request: Find node by case-insensitive substring

### ISSUE THREAD

**Issue by litdream** [org-roam/org-roam#2101]
org-roam became the key software in my day-to-day workflow.
One of the mostly used workflow is `org-roam-node-find` and `org-roam-node-insert`.

When org-roam is filtering down nodes, it uses prefix based narrowing against title.
This fits many cases, but I run into a lot more cases to match titles as substring I type.  VSCode provides file search like this, and that proves to be very useful.
Matching substring to title might be a little more complex,  but can we make a separate functions based on new matcher?
And, if this is case-insensitive, that will be super helpful.
- org-roam-node-find-isubstr
- org-roam-node-insert-isubstr

Thank you for the great software.

**Comment by PRESFIL** [comment]
You may try [orderless](https://github.com/oantolin/orderless) for this, with custom completion framework, [Vertico](https://github.com/minad/vertico), for exaple.
By the way, there is an example of usage it together with orderless on its README.

**Comment by litdream** [comment]
orderless was easy enough to set up.
Thank you for the suggestion.  Closing my request.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Dear @litdream 
after some weeks can you give us a feedback about your experience with `orgroam` and `orderless` and show us your configuration please?

Kind
Christian

**Comment by charlemana** [comment]
@PRESFIL Orderless worked very well for the my use case. Thank you so much
