### ISSUE TITLE
Error Running hook +org-init-roam-h

### ISSUE THREAD

**Issue by jonathanabennett** [org-roam/org-roam#2106]
### Description
When launching Emacs (on the first run of the `org-load-hook`), I receive an error. Clearing the error allows org-roam to work as expected.

Error message:
`Failed to load magit package incrementally, because: (doom-hook-error org-load-hook +org-init-roam-h (file-missing Cannot open load file No such file or directory org-roam-buffer))`
#### Steps to Reproduce

Example:

1. Load Emacs

#### Backtrace
I cannot figure out how to copy the contents of the buffer. Every key that I press kills the buffer. I think this is because the error is occuring during start up, as opening the buffer through `debugger-frame` later allows me to use usual keybindings.

#### Expected Results

There is no error message

#### Actual Results

`Failed to load magit package incrementally, because: (doom-hook-error org-load-hook +org-init-roam-h (file-missing Cannot open load file No such file or directory org-roam-buffer))`

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-27
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-e7ea951 @ /home/jonathanb/.emacs.d/.local/straight/build-27.2/org/)
- Org-roam: c8a360a

**Comment by jethrokuan** [comment]
There's no more `org-roam-buffer` package in v2. Rebuild your doom emacs config: the most reliable way is to delete your `.emacs.d/.local/straight` folder and run `doom sync`.
