### ISSUE TITLE
Request: Provide option for node-insert to leave cursor at the end of the inserted link

### ISSUE THREAD

**Issue by lm-w1n5t0n** [org-roam/org-roam#2108]
### Brief Abstract
I would like the cursor to be left at the end of inserted links so that I can continue typing straight away without having to navigate first.

### Long Description
For whatever reason, inserting a link leaves the cursor at the beginning of the link's text, rather than the expected end. When trying to maintain a train of thought and a state of flow, it's important to minimise distraction sand unnecessary steps. Even with the addition of a custom `org-roam-node-insert-immediate` function to prevent the opening of a capture buffer (taken from [here](https://systemcrafters.net/build-a-second-brain-in-emacs/5-org-roam-hacks/#fast-note-insertion-for-a-smoother-writing-flow)), the workflow is not as smooth as it could/should be because I still have to navigate past the link to continue typing, which in many cases is more than one words and therefore not as easy as a single `forward-word` command.

For users of `evil-mode` or other similar modal editing setups, this adds an additional step of having to navigate between normal and insert modes (I use a `C-c`-based keybinding for `org-roam-node-insert` so that I can use it without leaving insert mode, but `node-insert`'s current behavior forces me to switch to navigation anyway).

### Proposed Implementation (if any)
Provide a custom variable that can toggle between the current behavior or the proposed one, or change the current behavior all together if there is no good reason for it being the way it is.

**Comment by lm-w1n5t0n** [comment]
False flag, I think this may be related to how I set up my key bindings. As to why that would cause this behavior, that's another story.

If this is not in fact the default behavior then please close or delete, sorry.

**Comment by Jdogzz** [comment]
With a clean install and minimal emacs config (out of the box editing setup with Vanilla Emacs, no evil) I can confirm the behavior is as you originally described:

- Calling org-roam-node-insert and generating a new note from a capture template will generate a link and place point at the beginning of the link
- Calling org-roam-node-insert and using a preexisting note will generate a link and place point at the end of the link

In my workflow, the latter is the desired behavior for the link being inserted for both a new and preexisting note, I would like point to be placed after the link, not at the beginning.

**Comment by Jdogzz** [comment]
I can confirm the commit fixes the issue for me.

**Comment by lm-w1n5t0n** [comment]
Same here, works as desired - thanks!
