### ISSUE TITLE
PR #2089 breaks support of symlinked org-files in `org-roam-directory`

### ISSUE THREAD

**Issue by PRESFIL** [org-roam/org-roam#2111]
### Description

It seems that the `file-in-directory-p` function proposed in #2089 is provided only for
*physical directories*, does not work as we would like with *symlinked directories*.
It dereferences all the symlinks in its path, and previously seemed related paths
cease to be such.

For example:

Source paths:

```
~/org-roam/ -> ~/MEGAsync/org-roam/
~/org-roam/note.org -> ~/Desktop/note.org
```

How `file-in-directory-p` sees them after dereference:

```
~/MEGAsync/org-roam/
~/Desktop/note.org
```

Because of this, such notes are ignored and not indexed, although they were indexed earlier.

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam--build-cache-async`
3. Run `org-roam-find-file`
4. Try to find symlinked node

#### Backtrace

There is no runtime errors.

#### Expected Results

Symlinked files not be skipped as before #2089.

#### Actual Results

File not indexed.

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-26
- Framework: N/A
- Org: Org mode version 9.5 (9.5-g0a86ad)
- Org-roam: v2.2.0-30-g0bd6c9a

**Comment by PRESFIL** [comment]
I have a solution, but it needs to be tested on Windows, If @etern agrees to help with this :pray:

**Comment by etern** [comment]
I will test your solution in my environment, thanks for fixing this.

**Comment by PRESFIL** [comment]
Can you use straight to switch to a branch [PRESFIL/org-roam#restore-org-roam-descendant-of-p](https://github.com/PRESFIL/org-roam/tree/restore-org-roam-descendant-of-p) ?

**Comment by etern** [comment]
Should improve regexp, you can try a simple test in your *scratch* buffer
```elisp
(replace-regexp-in-string "^\(\w\):" 'downcase "C:/test" t t)
;; output: "C:/test"
```
regexp need more back slash, and windows driver label only has one character, this should work:
```elisp
(replace-regexp-in-string "^\\([A-Z]\\):" 'downcase "C:/test" t t)
;; output: "c:/test"
```

**Comment by PRESFIL** [comment]
OK, updated. For safety reasons `[A-Z]` become `[A-Za-z]`.

**Comment by PRESFIL** [comment]
I think that all the same, such a check is not enough. If you don't have many
notes, could you re-index the database after switching to this branch?

```elisp
(use-package org-roam
  :straight (org-roam
              :fork (:type git
                     :host github
                     :repo "PRESFIL/org-roam"
                     :branch "restore-org-roam-descedant-of-p"))
...
)
```

**Comment by etern** [comment]
We're doing downcase, don't think `[a-z]` is necessary, it's already lower case.

Anyway, it works, I deleted sqlite db file, reindex is OK.

**Comment by PRESFIL** [comment]
Thank you for your assistance!
