### ISSUE TITLE
Emacs fails to shutdown problem with org-persist/ssh/tramp?

### ISSUE THREAD

**Issue by brittAnderson** [org-roam/org-roam#2113]
### Description
Emacs failed to shutdown because it insisted on trying to contact unavailable hosts. I had been connected to those hosts earlier in the day, but they are behind a firewall and were no longer available. I could halt the connection and try to cleanup Tramp, but that never fixed the problem. Had to kill emacs. 

Problem was not present with an emacs -Q so I started trying to see what might be in my init and found that when I uncommented the org-roam package problems reappeared. 

Looking for newly changed files I saw that ~/.cache/org-persist was being updated and when I looked at the index file I found lines mentioning the problematic ssh connections. Deleting the index file and allowing things to rebuild solved the problem. 

So I think it is an org-roam problem, but I can't be a 100% sure, and I have no easy way to reproduce the problem, because I don't really know how I caused it in the first place. 

But hopefully the search engines will index the issue in case it happens to someone else. It was very frustrating.

**Comment by nobiot** [comment]
> ~/.cache/org-persist was being updated and when I looked at the index file I found lines mentioning the problematic ssh connections

If this is the problem, you can try setting set
`org-element-cache-persistent' to nil. 

Refer to [this](https://lists.gnu.org/r/emacs-orgmode/2021-10/msg00647.html).

This is probably coming from an released version of Org-mode. Upgrading your Org might help. If not, you might like to report the issue in Org’s development mailing list for the maintainer to have a look.

**Comment by jethrokuan** [comment]
yeah `org-persist` is a new Org feature and not related to Org-roam, likely an upstream issue.
