### ISSUE TITLE
Request to not strip leading new lines from template files.

### ISSUE THREAD

**Issue by artelse** [org-roam/org-roam#2115]
Currently org-roam strips new lines `\n` following the header. But if you want a new line between the header and content there currently is no way to achieve this, even new lines from the start of template files are stripped.
It makes perhaps sense to strip extraneous new lines from the header, but I think org-roam should leave it up to the user to put whatever they want in their template files. Hence my request to change this.
See code comments [here](https://github.com/org-roam/org-roam/blob/master/org-roam-capture.el#L776-L791), and a brief discussion [here](https://org-roam.discourse.group/t/multiple-blank-lines-in-head-of-capture-template/2488) at the Discourse group.

**Comment by jethrokuan** [comment]
#2117 should address this.

**Comment by artelse** [comment]
Cool, thanks for addressing this so fast!
