### ISSUE TITLE
Allow for `org-roam-buffer`'s Backlinks section to be unique per source

### ISSUE THREAD

**Issue by jeremyf** [org-roam/org-roam#2119]
### Brief Abstract

Allow customization so that Backlinks portion of `org-roam-buffer` can be unique per source.

### Long Description

Part of my writing process is to include the same reference multiple times in an `org-roam-node`.  (For example, when I reference a person in my dailies they might have multiple references within the same day).  When I look at the backlinks I see duplicate source titles.  This can lead to a huge backlink buffer.

### Proposed Implementation (if any)

The following query appears to produce a desired effect for what I'm after:

```elisp
(org-roam-db-query
		    [:select :distinct [source dest (funcall min pos) (funcall min properties)]
		     :from links
		     :where (= dest $s1)
		     :and (= type "id")
		     :group :by source]
		    (org-roam-node-id node))
```

A concession of the query is to use the "first" `pos`.  I'm uncertain the best approach for `properties` but went with something similar.

I see two routes to proceed:

1. Create a new `org-roam-backlinks-unique-source-section` function2. 
2. Create a variable (`(defvar org-roam-backlinks-section-limit-to-unique-sources)`? then add a switch in `org-roam-backlinks-get`

My preference would be to have the unique customizable variable.

Also, I'm prepared to create the solution as I think I have all the necessary context to proceed once I have guidance on an approach.

### Please check the following:

- [X] No similar feature requests; though it's almost close to https://github.com/org-roam/org-roam/issues/2029

**Comment by jethrokuan** [comment]
@jeremyf thanks for investigating! I think the best approach moving forward is being able to specify the config options directly in `org-roam-mode-section-functions`, something like:

```
(defcustom org-roam-mode-section-functions (list #'org-roam-backlinks-section
                                                 #'org-roam-reflinks-section)
  "Functions that insert sections in the `org-roam-mode' based buffers.
Each function is called with one argument, which is an
`org-roam-node' for which the buffer will be constructed for.
Normally this node is `org-roam-buffer-current-node'."
  :group 'org-roam
  :type 'hook)
  ```
  
  to

```
(defcustom org-roam-mode-section-functions (list (#'org-roam-backlinks-section . (:unique t))
                                                 #'org-roam-reflinks-section)
  "Functions that insert sections in the `org-roam-mode' based buffers.
Each function is called with one argument, which is an
`org-roam-node' for which the buffer will be constructed for.
Normally this node is `org-roam-buffer-current-node'."
  :group 'org-roam
  :type 'hook)
```

**Comment by jeremyf** [comment]
I like that syntax, and at the moment am unsure how I'd apply it to the existing system.  However, I'm happy to investigate further in regards to implementation.  I'm unable to assign issues on this repository but would love to be assigned.

**Comment by jethrokuan** [comment]
Here are my immediate thoughts on how to make this happen:

1. Make each function like `org-roam-backlinks-section` a `cl-defun` which takes in optional (or default) arguments.
2. Change this line of code: https://github.com/org-roam/org-roam/blob/6f86d0e5fedf7a95ee5772d6f550cb202c697b12/org-roam-mode.el#L231

Instead of `run-hook-with-args`, you'll just iterate the list, and do a pcase:
1. If function, call it with single arg `org-roam-buffer-current-node`
2. If cons cell, call it with additional args as specified in the cdr of cell.

**Comment by jeremyf** [comment]
I haven't done `pcase` work, but I do have a PR that I'm currently crafting that works.  The syntax is a bit different but I don't think introduces anything breaking.

**Comment by jeremyf** [comment]
So `first` and `first_value` don't work as a substitution of `min`.  I'm looking at further modifications to the query.  Throwing this into draft status.
