### ISSUE TITLE
Links resolving to file paths on org-roam-insert

### ISSUE THREAD

**Issue by jolitp** [org-roam/org-roam#2128]
### Description
After setting up org-roam with Doom Emacs, linking one note to another does not create a link with [id:note_name], instead it puts [file:name_of_file.org]. I don't think this is the desired behavior, and looking at tutorials online it is not how it is shown on the tutorial.

### Config
Both org and org-roam are unpinned from Doom versions:

packages.el
```
(unpin!
  org
  org-roam
)
```
init.el
```
(doom!
...
:lang
       (org              ; organize your plain life in plain text
       ;; +brain
        +dragndrop
       ;; +gnuplot
       ;; +hugo
       ;; +ipython
        +journal
       ;; +jupyter
        +noter
       ;; +pandoc
        +pomodoro
        +present
        +pretty
        +roam
        )
...
)
```

config.el
```
(use-package! org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
  :custom
  (setq org-roam-directory (file-truename "~/Dropbox/org/roam"))
  (setq org-roam-dailies-directory "~/Dropbox/org/roam/daily")
  (org-roam-completion-everywhere t)
)

;; workaround (void-function ucs-normalize-NFD-string)
(after! org
  (require 'ucs-normalize) 
)
```
#### Steps to Reproduce

0. maybe try getting a Doom Emacs installation with the above config
1. create 2 notes: note1 and note2
2. link note1 to note2
3. check if the link is linked via file or id

#### Backtrace
there is no elisp error

#### Expected Results

note link with the pattern [id:note_name]

#### Actual Results

note link with the pattern [file:name_of_file.org].

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.32, cairo version 1.17.4)
 of 2022-03-05
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-91681fc03 @ /home/jolitp/Config/Emacs/doom/emacs.d/.local/straight/build-29.0.50/org/)

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
Use `(org +roam2)` for Doom Emacs to use v2 of Org-roam.

**Comment by jolitp** [comment]
Right on the money, that fix the issue.

The Doom Emacs default config comes with those examples on how to enable the modules, and that was +roam instead of +roam2. I will look into seeing if they can make those better.
