### ISSUE TITLE
Capture Templates File Option Fails with Type Error

### ISSUE THREAD

**Issue by yuki-tsubaki** [org-roam/org-roam#2129]
# Description

When I specify the template for `org-roam-capture-templates` using the file option as given in the
documentation for the variable, it fails saying that it is getting the wrong type argument (`replace-regexp-in-string: Wrong type argument: stringp, (file "/souko/templates/default.org")`.

## Steps to Reproduce

1.  Load Emacs with a config using a file as a template. Here is a abbreviated version of my template config.

```emacs-lisp
    (setq org-roam-capture-templates
          '(
                ;; This template fails with an error
                ("r" "test" plain "%?"
                :target (file+head "niwa/%<%Y%m%d%H%M%S>-${slug}.org"
                                    (file "../souko/templates/default.org"))
                :unnarrowed t)

                ;; This template properly inserts the contents of the file
                ("t" "test" plain "%?"
                :target (file+head "niwa/%<%Y%m%d%H%M%S>-${slug}.org"
                                    "%[../souko/templates/default.org]")
                :unnarrowed t)
            )
          )
```
2.  Attempt to capture using the template.

## Backtrace

```
    Debugger entered--Lisp error: (wrong-type-argument stringp (file "../souko/templates/default.org"))
      string-match("\\${\\([^}]+\\)}" (file "../souko/templates/default.org") 0)
      replace-regexp-in-string("\\${\\([^}]+\\)}" #f(compiled-function (md) #<bytecode 0x13d2299>) (file "../souko/templates/default.org") t t)
      org-roam-format-template((file "../souko/templates/default.org") #f(compiled-function (key default-val) #<bytecode 0x15f6f35>))
      org-roam-capture--fill-template((file "../souko/templates/default.org") t)
      org-roam-capture--setup-target-location()
      org-roam-capture--prepare-buffer()
      org-capture-set-target-location(nil)
      #f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x15bb0c5>)(nil nil)
      apply(#f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x15bb0c5>) (nil nil))
      (let ((+file-templates-inhibit t)) (apply fn args))
      +file-templates-inhibit-in-org-capture-a(#f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x15bb0c5>) nil nil)
      apply(+file-templates-inhibit-in-org-capture-a #f(compiled-function (&optional goto keys) "Capture something.\n\\<org-capture-mode-map>\nThis will let you select a template from `org-capture-templates', and\nthen file the newly captured information.  The text is immediately\ninserted at the target location, and an indirect buffer is shown where\nyou can edit it.  Pressing `\\[org-capture-finalize]' brings you back to the previous\nstate of Emacs, so that you can continue your work.\n\nWhen called interactively with a `\\[universal-argument]' prefix argument GOTO, don't\ncapture anything, just go to the file/headline where the selected\ntemplate stores its notes.\n\nWith a `\\[universal-argument] \\[universal-argument]' prefix argument, go to the last note stored.\n\nWhen called with a `C-0' (zero) prefix, insert a template at point.\n\nWhen called with a `C-1' (one) prefix, force prompting for a date when\na datetree entry is made.\n\nELisp programs can set KEYS to a string associated with a template\nin `org-capture-templates'.  In this case, interactive selection\nwill be bypassed.\n\nIf `org-capture-use-agenda-date' is non-nil, capturing from the\nagenda will use the date at point as the default date.  Then, a\n`C-1' prefix will tell the capture process to use the HH:MM time\nof the day at point (if any) or the current HH:MM time." (interactive "P") #<bytecode 0x15bb0c5>) (nil nil))
      org-capture(nil nil)
      org-roam-capture-(:goto nil :info nil :keys nil :templates nil :node #s(org-roam-node :file nil :file-title nil :file-hash nil :file-atime nil :file-mtime nil :id "8575c666-0b65-4c76-abb2-722aa95dfe86" :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title "this" :properties nil :olp nil :tags nil :aliases nil :refs nil) :props (:immediate-finish nil :call-location #<marker at 8311 in config.org>))
      org-roam-capture(nil)
      funcall-interactively(org-roam-capture nil)
      call-interactively(org-roam-capture nil nil)
      command-execute(org-roam-capture)
```

## Expected Results

The template file contents will be used as the template.

## Actual Results

`org-roam-capture` quit with an error.

# Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2020-09-19
- Framework: N/A
- Org: Org mode version 9.6 (9.6-??-e7ea951 @ /home/pete/.emacs.d/.local/straight/build-27.1/org/)
- Org-roam: eed1df9

-   Org-roam commit:
    https://github.com/jethrokuan/org-roam/commit/eed1df9

**Comment by nobiot** [comment]
Move `(file "../souko/templates/default.org")` to where `"%?"` is like this. That's how I read the doc string of `org-roam-capture-templates`. 
It works on my end. I have a feeling that the file name (`~/default.org`) needs to be an absolute file name like this example (the relative file name like you do didn't work for me).

```
          ("r" "test" plain (file "~/default.org")
           :target (file+head "${id}.org" "")
           :unnarrowed t)
```

**Comment by jethrokuan** [comment]
@nobiot that results in different behaviour. `head` is only inserted once, when the node is new, while the template option is inserted each time a capture happens.

@williamspete001 The `head` option just doesn't support the `(file ...)` syntax right now, and never did. Is the `%[..]` option insufficient, or would you rather I provide support for `(file ...)`?

**Comment by nobiot** [comment]
@jethrokuan Thank you , good to know. Different behaviour but the same outcome for this case, is it not? You could call the capture with the same template only once for the same file (when you create the file).

**Comment by jethrokuan** [comment]
Correct, the outcome is the same if the capture template is only used every used once per node.

**Comment by williamspete001** [comment]
The solution listed by @nobiot works for my purposes.

@jethrokuan I think the main issue for me came down to my understanding of the documentation. I thought that the part of the docstring labeled "template" was the "prefilled template" that was referred to in the target property. This was mainly because the text I saw inserted when I used the default template was that. The actual "template" parameter for the capture was a mystery to me until I saw the example with the file property in the place of the `%?` and reread the docstring with that in mind.

On weather the `%[filename]` option would have worked for me, it didn't (without some hacking). The `${title}` replacement did not work from inside the file. To get that to work I needed to put the part of my template directly in the "prefilled template" spot directly as a string (E.g. `"#+title: ${title}\n%[../souko/templates/default.org]"`). So it works, but not in the way I would have expected it to.

One thing that is still unclear to me after reading the docs again is what the "head content" is.

In general, I feel like the current implementation is fine, but figuring out how to use it with the current documentation is pretty difficult. Some things I think would be helpful:
1. A more detailed breakdown of the structure of the parameters. Covering how they are nested, and what inputs they can have (E.g. relative or absolute file path).
2. More clear terminology for differentiating the "template" from the "prefilled template" inside its target parameter.

**Comment by jethrokuan** [comment]
> On weather the %[filename] option would have worked for me, it didn't (without some hacking). The ${title} replacement did not work from inside the file. To get that to work I needed to put the part of my template directly in the "prefilled template" spot directly as a string (E.g. "#+title: ${title}\n%[../souko/templates/default.org]"). So it works, but not in the way I would have expected it to.

Right, the expansion runs in the following order:

1. Org-roam `${}` based expansion
2. Org-capture's template expansion, which handles `%[]` based expansion.

A lot of this complexity is incidental, trying to work around the quirks of org-capture. I'm happy to update the documentation, although I think the best and only way to go about understanding the template expansion flow is to look at the code itself: trying to explain it all in the manual would be a direct translation of the code into text.
