### ISSUE TITLE
Node list not displayed

### ISSUE THREAD

**Issue by Marie-Antoinette** [org-roam/org-roam#2135]
### Description

1. Load Emacs
2. Run org-roam-node-insert
3. Create node call Wiki and save
4. Run org-roam-node-insert
5. Create node call Emacs and save
6. Run org-roam-node-find
7. in the minibuffer I can type the name of the node I want to load **but i don't have the list of nodes displayed.** 
8. If i type the name of an existing node I can access and modify it (autocompletion works for the name of the node).

### Environment

- Emacs: GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5)
 of 2021-01-31, modified by Debian- Emacs: GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5)
 of 2021-01-31, modified by Debian

Thanks for help

**Comment by nobiot** [comment]
Do you get a prompt in the minibuffer like this image below?

![2022-03-26T160117](https://user-images.githubusercontent.com/12507865/160245314-742564bc-2164-43c7-ac73-d3262395ffad.png)

If so, your Emacs and Org-roam are likely working as you configured them. Try to find a so-called "completion framework" -- a package that displays completion candidates vertically as a list. Popular ones are Ivy, Helm, Vertico, and Selectrum. You can find them in MELPA or some of them in ELPA.

For example, I use Vertico (vertico-mode):
![2022-03-26T160359](https://user-images.githubusercontent.com/12507865/160245481-cee15303-5b52-4e16-bcfe-5b1f6bbc8e90.png)

**Comment by Marie-Antoinette** [comment]
Thanks for your help
