### ISSUE TITLE
Capture buffer isn't being shown

### ISSUE THREAD

**Issue by uningan** [org-roam/org-roam#2142]
Im getting issue #1700 same error but in my case is not an org-id problem. My backtrace populates id prop correctly:

```
Debugger entered--Lisp error: (error "Capture template ‘d’: Wrong type argument: listp, t")
  error("Capture template `%s': %s" "d" "Wrong type argument: listp, t")
  (condition-case error (org-capture-place-template (eq (car (org-capture-get :target)) 'function)) ((error quit) (if (and (buffer-base-buffer (current-buffer)) (string-prefix-p "CAPTURE-" (buffer-name))) (progn (kill-buffer (current-buffer)))) (set-window-configuration (org-capture-get :return-to-wconf)) (error "Capture template `%s': %s" (org-capture-get :key) (error-message-string error))))
  (cond ((equal entry "C") (customize-variable 'org-capture-templates)) ((equal entry "q") (user-error "Abort")) (t (org-capture-set-plist entry) (org-capture-get-template) (org-capture-put :original-buffer orig-buf :original-file (or (buffer-file-name orig-buf) (and (featurep 'dired) (car (rassq orig-buf dired-buffers)))) :original-file-nondirectory (and (buffer-file-name orig-buf) (file-name-nondirectory (buffer-file-name orig-buf))) :annotation annotation :initial initial :return-to-wconf (current-window-configuration) :default-time (or org-overriding-default-time (org-current-time))) (org-capture-set-target-location (and (equal goto 0) 'here)) (condition-case error (org-capture-put :template (org-capture-fill-template)) ((error quit) (if (get-buffer "*Capture*") (kill-buffer "*Capture*")) (error "Capture abort: %s" (error-message-string error)))) (setq org-capture-clock-keep (org-capture-get :clock-keep)) (condition-case error (org-capture-place-template (eq (car (org-capture-get :target)) 'function)) ((error quit) (if (and (buffer-base-buffer (current-buffer)) (string-prefix-p "CAPTURE-" (buffer-name))) (progn (kill-buffer (current-buffer)))) (set-window-configuration (org-capture-get :return-to-wconf)) (error "Capture template `%s': %s" (org-capture-get :key) (error-message-string error)))) (if (and (derived-mode-p 'org-mode) (org-capture-get :clock-in)) (progn (condition-case nil (progn (if (org-clock-is-active) (progn ...)) (org-clock-in) (set (make-local-variable ...) t)) (error "Could not start the clock in this capture buffer")))) (if (org-capture-get :immediate-finish) (progn (org-capture-finalize)))))
  (let* ((orig-buf (current-buffer)) (annotation (if (and (boundp 'org-capture-link-is-already-stored) org-capture-link-is-already-stored) (plist-get org-store-link-plist :annotation) (condition-case nil (progn (org-store-link nil)) (error nil)))) (entry (or org-capture-entry (org-capture-select-template keys))) initial) (setq initial (or org-capture-initial (and (org-region-active-p) (buffer-substring (point) (mark))))) (if (stringp initial) (progn (remove-text-properties 0 (length initial) '(read-only t) initial))) (if (stringp annotation) (progn (remove-text-properties 0 (length annotation) '(read-only t) annotation))) (cond ((equal entry "C") (customize-variable 'org-capture-templates)) ((equal entry "q") (user-error "Abort")) (t (org-capture-set-plist entry) (org-capture-get-template) (org-capture-put :original-buffer orig-buf :original-file (or (buffer-file-name orig-buf) (and (featurep 'dired) (car (rassq orig-buf dired-buffers)))) :original-file-nondirectory (and (buffer-file-name orig-buf) (file-name-nondirectory (buffer-file-name orig-buf))) :annotation annotation :initial initial :return-to-wconf (current-window-configuration) :default-time (or org-overriding-default-time (org-current-time))) (org-capture-set-target-location (and (equal goto 0) 'here)) (condition-case error (org-capture-put :template (org-capture-fill-template)) ((error quit) (if (get-buffer "*Capture*") (kill-buffer "*Capture*")) (error "Capture abort: %s" (error-message-string error)))) (setq org-capture-clock-keep (org-capture-get :clock-keep)) (condition-case error (org-capture-place-template (eq (car (org-capture-get :target)) 'function)) ((error quit) (if (and (buffer-base-buffer ...) (string-prefix-p "CAPTURE-" ...)) (progn (kill-buffer ...))) (set-window-configuration (org-capture-get :return-to-wconf)) (error "Capture template `%s': %s" (org-capture-get :key) (error-message-string error)))) (if (and (derived-mode-p 'org-mode) (org-capture-get :clock-in)) (progn (condition-case nil (progn (if ... ...) (org-clock-in) (set ... t)) (error "Could not start the clock in this capture buffer")))) (if (org-capture-get :immediate-finish) (progn (org-capture-finalize))))))
  (cond ((equal goto '(4)) (org-capture-goto-target keys)) ((equal goto '(16)) (org-capture-goto-last-stored)) (t (let* ((orig-buf (current-buffer)) (annotation (if (and (boundp ...) org-capture-link-is-already-stored) (plist-get org-store-link-plist :annotation) (condition-case nil (progn ...) (error nil)))) (entry (or org-capture-entry (org-capture-select-template keys))) initial) (setq initial (or org-capture-initial (and (org-region-active-p) (buffer-substring (point) (mark))))) (if (stringp initial) (progn (remove-text-properties 0 (length initial) '(read-only t) initial))) (if (stringp annotation) (progn (remove-text-properties 0 (length annotation) '(read-only t) annotation))) (cond ((equal entry "C") (customize-variable 'org-capture-templates)) ((equal entry "q") (user-error "Abort")) (t (org-capture-set-plist entry) (org-capture-get-template) (org-capture-put :original-buffer orig-buf :original-file (or (buffer-file-name orig-buf) (and ... ...)) :original-file-nondirectory (and (buffer-file-name orig-buf) (file-name-nondirectory ...)) :annotation annotation :initial initial :return-to-wconf (current-window-configuration) :default-time (or org-overriding-default-time (org-current-time))) (org-capture-set-target-location (and (equal goto 0) 'here)) (condition-case error (org-capture-put :template (org-capture-fill-template)) ((error quit) (if ... ...) (error "Capture abort: %s" ...))) (setq org-capture-clock-keep (org-capture-get :clock-keep)) (condition-case error (org-capture-place-template (eq ... ...)) ((error quit) (if ... ...) (set-window-configuration ...) (error "Capture template `%s': %s" ... ...))) (if (and (derived-mode-p ...) (org-capture-get :clock-in)) (progn (condition-case nil ... ...))) (if (org-capture-get :immediate-finish) (progn (org-capture-finalize))))))))
  org-capture(nil "d")
  org-roam-capture-(:node #s(org-roam-node :file nil :file-title nil :file-hash nil :file-atime nil :file-mtime nil :id "d6ed26dc-fae0-434d-bc4b-0336bb133750" :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title "Ambu2" :properties nil :olp nil :tags nil :aliases nil :refs nil) :templates nil :props (:finalize find-file :call-location #<marker at 1 in *Backtrace*>))
  org-roam-node-find()
  funcall-interactively(org-roam-node-find)
  command-execute(org-roam-node-find record)
  execute-extended-command(nil "org-roam-node-find" nil)
  funcall-interactively(execute-extended-command nil "org-roam-node-find" nil)
  command-execute(execute-extended-command)
```
To reproduce error:

Im using exactly this emacs config (https://github.com/protesilaos/dotfiles/tree/9a3b77d6de599b49b2596fe038704825bcc1d920/emacs/.emacs.d) with my own customizations for org-roam (in user-emacs.el):

```
;;; Org-Roam
(prot-emacs-elpa-package 'org-roam
  (setq org-roam-directory (file-truename "~/Documents/org/roam"))
  (org-roam-db-autosync-mode t)
  (require 'org-roam))
```
I've checked .org-id-locations file and its all ok.

My env:

- "GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)"
- Org mode version 9.5.2 (9.5.2-gfbff08 @ /nix/store/688q3q4sa0gp0mf5q15djcs8lvnllkg0-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.5.2/)
- Org-roam 20220319.1902

_Originally posted by @uningan in https://github.com/org-roam/org-roam/issues/1700#issuecomment-1081644316_

**Comment by uningan** [comment]
I'm going to take the liberty of ping @protesilaos here. I tried to debug this error during various days but my elisp knowledge is very limited yet.

**Comment by protesilaos** [comment]
Hello @uningan!  This is most likely an issue with my setup and not an org-roam bug.  I know org-roam uses capture templates so there may be a conflict there.  I am not a user and not familiar with the internals.  Will need to read the docs and report back to you.

**Comment by protesilaos** [comment]
I am trying to test this on `emacs -Q` in orded to determine if the bug is with my configuration, but I have trouble with a circular dependency where `org-roam.el` requires `org-roam-compat.el` and vice versa.

I gave up here (tweaked the order a few times):

```elisp
(require 'org)
(require 'dash "/home/prot/.emacs.d/elpa/dash-20220404.2004/dash.el")
(require 'magit-section "/home/prot/.emacs.d/elpa/magit-section-20220329.1154/magit-section.el")
(require 'emacsql-compiler "/home/prot/.emacs.d/elpa/emacsql-20220408.1614/emacsql-compiler.el")
(load-file "/home/prot/.emacs.d/elpa/emacsql-20220408.1614/emacsql.el")
(require 'emacsql-sqlite "/home/prot/.emacs.d/elpa/emacsql-sqlite-20220218.1543/emacsql-sqlite.el")
(load-file "/home/prot/.emacs.d/elpa/org-roam-20220409.2317/org-roam-compat.el")
(require 'org-roam "/home/prot/.emacs.d/elpa/org-roam-20220409.2317/org-roam.el")
(require 'org-roam-db "/home/prot/.emacs.d/elpa/org-roam-20220409.2317/org-roam-db.el")
(require 'org-roam-utils "/home/prot/.emacs.d/elpa/org-roam-20220409.2317/org-roam-utils.el")
(require 'org-roam-capture "/home/prot/.emacs.d/elpa/org-roam-20220409.2317/org-roam-capture.el")
(require 'org-roam-node "/home/prot/.emacs.d/elpa/org-roam-20220409.2317/org-roam-node.el")
(require 'org-roam-id "/home/prot/.emacs.d/elpa/org-roam-20220409.2317/org-roam-id.el")
(require 'org-roam-mode "/home/prot/.emacs.d/elpa/org-roam-20220409.2317/org-roam-mode.el")
```

I searched the `org-roam` manual for "emacs -Q" and also perused the contents in hope of finding some way to test this package in a pristine environment.  Perhaps you know about such a method?

**Comment by uningan** [comment]
Hi Prot, at first just say I really appreciate you waste your time troubleshooting this.

I'm get to run org-roam in a pristine environment (emacs -Q) and org-roam capture works well. Using this:

```
(add-to-list 'load-path "/nix/store/sabhicnqdgb9fqc9sxrxndljz9jx2mjv-emacs-packages-deps/share/emacs/site-lisp/elpa/")
(require 'org)
(require 'dash)
(require 'magit-section)
(require 'emacsql-compiler)
(require 'emacsql-sqlite)
(require 'org-roam)
(require 'org-roam-db)
(require 'org-roam-utils)
(require 'org-roam-capture)
(require 'org-roam-node)
(require 'org-roam-id)
(require 'org-roam-mode)
```
I'll try to go further adding your org-capture config. Thanks for put me on track.

**Comment by protesilaos** [comment]
> Update: I tested block by block your `org-mode` config and still works. 

Very well!  The intent is to use `org-roam` in `emacs -Q` without any
further configurations beyond the basics you shared earlier.  You should
run the command that triggers the error in this environment to see how
it behaves.

If it works, then try to test how it behaves after you also edit the
`org-capture-templates` (such as how I do in my config):

    (setq org-capture-templates
          `(("b" "Basic task for future review" entry
             (file+headline "tasks.org" "Tasks to be reviewed")
             ,(concat "* %^{Title}\n"
                      ":PROPERTIES:\n"
                      ":CAPTURED: %U\n"
                      ":END:\n\n"
                      "%i%l")
             :empty-lines-after 1)
            ("c" "Clock in to a task" entry
             (file+headline "tasks.org" "Clocked tasks")
             ,(concat "* TODO %^{Title}\n"
                      "SCHEDULED: %T\n"
                      ":PROPERTIES:\n"
                      ":EFFORT: %^{Effort estimate in minutes|5|10|15|30|45|60|90|120}\n"
                      ":END:\n\n"
                      "%a\n")
             :prepend t
             :clock-in t
             :clock-keep t
             :immediate-finish t
             :empty-lines-after 1)
            ("m" "Memorandum of conversation" entry
             (file+headline "tasks.org" "Tasks to be reviewed")
             ,(concat "* Memorandum of conversation with %^{Person}\n"
                      ":PROPERTIES:\n"
                      ":CAPTURED: %U\n"
                      ":END:\n\n"
                      "%i%?")
             :empty-lines-after 1)
            ("t" "Task with a due date" entry
             (file+headline "tasks.org" "Tasks with a date")
             ,(concat "* TODO %^{Title} %^g\n"
                      "SCHEDULED: %^t\n"
                      ":PROPERTIES:\n"
                      ":CAPTURED: %U\n"
                      ":END:\n\n"
                      "%a\n%i%?")
             :empty-lines-after 1)
            ("e" "Email note" entry
             (file+headline "tasks.org" "Tasks to be reviewed")
             ,(concat "* MAYBE %:subject :mail:\n"
                      ":PROPERTIES:\n"
                      ":CAPTURED: %U\n"
                      ":END:\n\n"
                      "%a\n%i%?")
             :empty-lines-after 1)))

Does it still work?

**Comment by uningan** [comment]
Of course it still works. Then keep adding more org related configuration
from your vanilla dotemacs/.emacs.d/prot-emacs.el

Block by block. And it still works. So I'm starting to think conflict is
lower level config.

**Comment by protesilaos** [comment]
> Of course it still works. Then keep adding more org related
> configuration from your vanilla dotemacs/.emacs.d/prot-emacs.el
> 
> Block by block. And it still works. So I'm starting to think conflict
> is lower level config.

Okay.  So the bug is not reproducible in `emacs -Q`?  We need to be able
to reproduce it there, otherwise the problem is specific to my setup.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by uningan** [comment]
I found it. This excerpt of your `prot-org.el` package makes `org-roam` capture fail.
```
;;;; org-capture

(declare-function cl-letf "cl-lib")

;; Source: https://stackoverflow.com/a/54251825
(defun prot-org--capture-no-delete-windows (oldfun args)
  (cl-letf (((symbol-function 'delete-other-windows) 'ignore))
    (apply oldfun args)))

;; Same source as above
(advice-add 'org-capture-place-template
            :around 'prot-org--capture-no-delete-windows)
```

Can you point me a workaround? Have sense solve it upstream?

**Comment by protesilaos** [comment]
On 2022-04-16, 10:45 -0700, Juanjo Presa ***@***.***> wrote:

> I found it. This excerpt of your `prot-org.el` package makes `org-roam` capture fail.
> ```
> ;;;; org-capture
>
> (declare-function cl-letf "cl-lib")
>
> ;; Source: https://stackoverflow.com/a/54251825
> (defun prot-org--capture-no-delete-windows (oldfun args)
>   (cl-letf (((symbol-function 'delete-other-windows) 'ignore))
>     (apply oldfun args)))
>
> ;; Same source as above
> (advice-add 'org-capture-place-template
>             :around 'prot-org--capture-no-delete-windows)
> ```
>
> Can you point me a workaround? Have sense solve it upstream?

Maybe this?

    (defun prot-org--capture-no-delete-windows (oldfun &rest args)
      (cl-letf (((symbol-function 'delete-other-windows) 'ignore))
        (apply oldfun args)))

    (advice-add 'org-capture-place-template :around 'prot-org--capture-no-delete-windows)

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by uningan** [comment]
Huge! It works. Thanks very much. Are you planning to change this upstream in your dotfiles?

**Comment by protesilaos** [comment]
On 2022-04-16, 11:19 -0700, Juanjo Presa ***@***.***> wrote:

> Huge! It works. Thanks very much. Are you planning to change this upstream in your dotfiles?

Yes, I will do it right away and mention you as well.

-- 
Protesilaos Stavrou
https://protesilaos.com
