### ISSUE TITLE
DB sync/cache slow with windows directory on WSL

### ISSUE THREAD

**Issue by loopdreams** [org-roam/org-roam#2144]
### Description
I recently tried to set up org roam on Windows (WSL). Currently, I have my org/org-roam notes directories stored on Dropbox. I have my Dropbox directory symlinked to my home WSL directory. 

When I first initialize org-roam, it goes through a 'processing modified files' sequence which takes about 40-50 seconds (this happens regardless of whether the files have changed or not).

This is also the case if I use the direct path to the Dropbox folder on the Windows system (/mnt/c/Users/.../Dropbox/notes...).

If I copy the files directly to the Ubuntu home directory, they load/initialize in a couple of seconds, so I don't think the problem is with the emacs configuration. It must be with how org-roam/emacs interacts with the Windows filesystem from the WSL system.

Anyway, my current solution is to just install the Dropbox instance directly on the Ubuntu system, which works fine. I just thought I'd flag this as an issue in case there is some way it could be fixed.

#### Steps to Reproduce

Install emacs/roam on WSL
Use a directory located on the windows filesystem as the org-roam-directory

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 - Framework: Doom
- Org: Org mode version 9.6 (9.6-??-971eb68 @ /home/eoin/.emacs.d/.local/straight/build-27.1/org/)
- Org-roam: 3615259
of 2020-09-19

**Comment by ParetoOptimalDev** [comment]
Do you have large directories without org files?

**Comment by loopdreams** [comment]
Hi @ParetoOptimalDev, thanks for your reply. I don't think it's the case here though. 

I tried something else today:
- changing the org-roam.db file location to the roam directory on the windows filesystem -> works normally (builds/initializes very quickly)

Then, I just tired the original setup again (org roam directory on windows, emacs/org-roam.db on WSL) and, while it still took almost a minute to build the first time, afterwards it only takes around 6-7 seconds now. It's still slower than when I have the org roam directory on the WSL filesystem, but that is probably to be expected. 

Anyway, there must have just been something wrong with my environment which is now working okay again. 

Probably wasn't an org-roam issue so will close this now.
