### ISSUE TITLE
2.2.1 has broken docs build

### ISSUE THREAD

**Issue by spwhitton** [org-roam/org-roam#2145]
rm -f doc/org-roam.texi
    make -C doc texi
    make[2]: Entering directory '/<<PKGBUILDDIR>>'
    make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
    Loading /etc/emacs/site-start.d/00debian.el (source)...
    Loading /etc/emacs/site-start.d/50autoconf.el (source)...
    Unable to resolve link: "id:280bfca8-83f3-4371-bc3a-25478d25129c"
    make[2]: *** [Makefile:84: texi] Error 255

Thanks!

**Comment by jethrokuan** [comment]
Do you need a separate release to be cut?

**Comment by spwhitton** [comment]
Hello,

On Sat 09 Apr 2022 at 12:54AM -07, Jethro Kuan wrote:

> Do you need a separate release to be cut?

No, that's fine, thanks.

In your commit message you write "debian packaging cannot use id links
to build docs" but I don't think this is inherent to the Debian
packaging.  We ought to be able to invoke Emacs in such a way that id
links are not a problem.  But I don't myself know how to do that :)
Anyway, great to have it fixed so I can update Org-roam in Debian.

-- 
Sean Whitton
