### ISSUE TITLE
org-roam-promote-entire-buffer incorrectly puts the #+title after the first paragraph

### ISSUE THREAD

**Issue by stig** [org-roam/org-roam#2154]
#### Steps to Reproduce

1. Create a file foo.org with this content (as created by `org-road-extract-subtree`): 

```org
    * Title
    :PROPERTIES:
    :ID:		C177BD79-8646-4FCE-9D6D-D1B612627252
    :END:
    
    Phasellus lacus.  
```

2. Call `org-roam-promote-entire-buffer` in foo.org. 

#### Expected Results

I would **expect** the title to be above the first paragraph, i.e.:

```org
:PROPERTIES:
:ID:		C177BD79-8646-4FCE-9D6D-D1B612627252
:END:

#+title: Title
Phasellus lacus.  
```
#### Actual Results

The title is below the first paragraph. 

```org
:PROPERTIES:
:ID:		C177BD79-8646-4FCE-9D6D-D1B612627252
:END:

Phasellus lacus.  
#+title: Title
```

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.2 (build 1, x86_64-apple-darwin17.7.0, Carbon Version 158 AppKit 1561.6)
 of 2022-02-14
- Framework: N/A
- Org: Org mode version 9.5.2 (9.5.2-g70970d @ /Users/stig/.config/emacs/straight/build/org/)
- Org-roam: v2.2.0-12-g3e2716e
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/g3e2716e

**Comment by jmay** [comment]
Fix for this is in https://github.com/org-roam/org-roam/pull/2091

**Comment by darkfeline** [comment]
I think I'm still seeing this at 3bb45afccb9f17758c5604e4d883c769f4fc3545

**Comment by jmay** [comment]
@jethrokuan The PR for this issue is merged, I believe this can be closed.

**Comment by Delapouite** [comment]
Ok. Let's close this issue.
Feel free to reopen it if needed. Thanks.
