### ISSUE TITLE
`org-roam-node-insert` reports error `Odd length text property list`

### ISSUE THREAD

**Issue by VitalyAnkh** [org-roam/org-roam#2155]
#### Steps to Reproduce

Run emacs 29.0.50(my custom build, commit hash is 10c675b96042f184524cc9ea817cad14ff1f7fc0) with doom emacs's +roam2. Then execute `org-roam-node-insert` in a org file.

#### Backtrace
```
Debugger entered--Lisp error: (error "Odd length text property list")
  read()
  #f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x1052cb0d5b300199>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-1587a08e80ae>)
  apply(#f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x1052cb0d5b300199>) #<emacsql-sqlite-connection emacsql-sqlite-connection-1587a08e80ae> nil)
  emacsql-parse(#<emacsql-sqlite-connection emacsql-sqlite-connection-1587a08e80ae>)
  #f(compiled-function (connection sql &rest args) #<bytecode -0x98c2dd4ebc991a4>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-1587a08e80ae> "SELECT\n  id,\n  file,\n  filetitle,\n  \"level\",\n  tod...")
  apply(#f(compiled-function (connection sql &rest args) #<bytecode -0x98c2dd4ebc991a4>) #<emacsql-sqlite-connection emacsql-sqlite-connection-1587a08e80ae> "SELECT\n  id,\n  file,\n  filetitle,\n  \"level\",\n  tod...")
  emacsql(#<emacsql-sqlite-connection emacsql-sqlite-connection-1587a08e80ae> "SELECT\n  id,\n  file,\n  filetitle,\n  \"level\",\n  tod...")
  apply(emacsql #<emacsql-sqlite-connection emacsql-sqlite-connection-1587a08e80ae> "SELECT\n  id,\n  file,\n  filetitle,\n  \"level\",\n  tod..." nil)
  org-roam-db-query("SELECT\n  id,\n  file,\n  filetitle,\n  \"level\",\n  tod...")
  org-roam-node-list()
  org-roam-node-read--completions(nil nil)
  org-roam-node-read(nil nil)
  org-roam-node-insert()
  #<subr funcall-interactively>(org-roam-node-insert)
  apply(#<subr funcall-interactively> org-roam-node-insert)
  funcall-interactively(org-roam-node-insert)
  #<subr call-interactively>(org-roam-node-insert nil nil)
  apply(#<subr call-interactively> (org-roam-node-insert nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> org-roam-node-insert nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (org-roam-node-insert nil nil))
  call-interactively(org-roam-node-insert nil nil)
  command-execute(org-roam-node-insert)
```
#### Expected Results

Shoule insert node normally.

#### Actual Results

Error.

### Environment

- Emacs: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)
 of 2022-04-14, commit is 10c675b96042f184524cc9ea817cad14ff1f7fc0
- Framework: Doom
- Org: Org mode version 9.5 (f6813dbea @ /home/vitalyr/.config/.emacs.d/.local/straight/build-29.0.50/org-mode/)
- Org-roam: 3bb45af

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/3bb45af

**Comment by nobiot** [comment]
Is it possible that this error is because [Doom does not support Emacs 29+](https://github.com/hlissner/doom-emacs#prerequisites) yet? Is it reproducible with a stable Emacs version such as 27.2 that Doom recommends?

**Comment by jethrokuan** [comment]
This looks like an issue with the Emacs build actually, as far as I can tell this error is from Emacs itself: it's neither thrown by org-roam, org or sqlite.

**Comment by VitalyAnkh** [comment]
Yes, I'm using my customed emacs build. I will try other build options and see if things go different. Thanks!

**Comment by VitalyAnkh** [comment]
I can confirm this problem is caused by my own configurations now. Emacs, Doom and org-roam are all running well. Closing this issue since I think it's all my own fault.

**Comment by nobiot** [comment]
@VitalyAnkh Is it possible to document (briefly) what configuration caused the issue by any chance? It would be good as future reference.

**Comment by nobiot** [comment]
@VitalyAnkh Is it possible to document (briefly) what configuration caused the issue by any chance? It would be good as future reference.

**Comment by VitalyAnkh** [comment]
Hi @nobiot, I find I can't document the detailed cause... I was trying to debug this problem using `git bisect` last night, I I found all versions of Emacs and Doom will have this error with my configurations. Then I tried to debug my configurations with `git bisect`, and found all commits would cause this error... But after I run `git bisect reset`, this error is gone... I can't figure out why. So the only thing I could document is: use `git` to manage your configurations, and use `git bisect` to debug when you encounter errors.

**Comment by nobiot** [comment]
@VitalyAnkh Thank you for coming back. Understood okay, thanks for trying and advice about using Git to version control  configurations.

**Comment by yuuyins** [comment]
```elisp
Debugger entered--Lisp error: (error "Odd length text property list")
  read()
  #f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x102fc179770709d9>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-3f4ba22>)
  apply(#f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x102fc179770709d9>) #<emacsql-sqlite-connection emacsql-sqlite-connection-3f4ba22> nil)
  emacsql-parse(#<emacsql-sqlite-connection emacsql-sqlite-connection-3f4ba22>)
  #f(compiled-function (connection sql &rest args) #<bytecode -0x98f79e11258f7a4>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-3f4ba22> "SELECT\n  id,\n  file,\n  filetitle,\n  \"level\",\n  tod...")
  apply(#f(compiled-function (connection sql &rest args) #<bytecode -0x98f79e11258f7a4>) #<emacsql-sqlite-connection emacsql-sqlite-connection-3f4ba22> "SELECT\n  id,\n  file,\n  filetitle,\n  \"level\",\n  tod...")
  emacsql(#<emacsql-sqlite-connection emacsql-sqlite-connection-3f4ba22> "SELECT\n  id,\n  file,\n  filetitle,\n  \"level\",\n  tod...")
  org-roam-db-query("SELECT\n  id,\n  file,\n  filetitle,\n  \"level\",\n  tod...")
  org-roam-node-list()
  org-roam-node-read--completions(nil nil)
  org-roam-node-read(nil nil)
  org-roam-node-find()
  funcall-interactively(org-roam-node-find)
  command-execute(org-roam-node-find)
```

```command
- Emacs: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-971eb6885 @ /home/yuu/.config/emacs/.local/straight/build-28.1/org/)
- Org-roam: 01843a6
- sqlite-connector: sqlite
```
