### ISSUE TITLE
Org-roam doesn’t autocomplete when in ‘org-add-note’

### ISSUE THREAD

**Issue by arvydasg** [org-roam/org-roam#2167]
### Description

[Here is a video showcasing the problem](https://www.loom.com/share/599bff4754694ebfbbbea24c772156cd)

When I am adding org-roam links by org-roam-node-insert - the link gets added properly. Good.

When I write a +3 letters of org-roam link that I know exists - the autocompletetion helps me finish it and adds a link - fantastic.

HOWEVER, when I try to use the autocompletion feature INSIDE org-add-note (C-c C-z), the autocompletion works, but org link desn’t get added.

Why is that? Does it have to do something with minor modes?

[My emacs config can be found here](https://github.com/arvydasg/emacs/blob/master/myinit.org)

Thanks!

### Environment

- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)
 of 2020-03-26, modified by Debian
- Framework: N/A
- Org: Org mode version 9.5.2 (9.5.2-gfbff08 @ /home/arvydas/.emacs.d/elpa/org-9.5.2/)
- Org-roam: 2.2.1

**Comment by nobiot** [comment]
This should be because the buffer that opens when you do `C-c C-z` named `*Org Note*` is a temporary buffer and not considered part of `org-roam-directory`. You can verify this by evaluating `(org-roam-file-p (buffer-file-name))` in it; you should get an error. Compare it with another Org file in your Org-roam directory.

**Comment by arvydasg** [comment]
Thank you, @nobiot , it is how you say. 

So I guess I should forget about this feature, right? Or somehow make temporary buffers be a part of org-roam-directory (which probably doesn't make sense).?

**Comment by nobiot** [comment]
Not sure if it does makes sense or not. It will be a new feature request if you wish it to be part of Org-roam code base and will be for the project and Jethro do decide.

In parallel, you could consider your own Elisp code to achieve it — maybe you could create a PR.

**Comment by arvydasg** [comment]
I see, thank you. 

My elisp knowledge is too little, so I can not make a PR with this feature.

Is it enough to rename this discussion to "Feature request:...." for this ticket to become a feature request instead of a bug report and for Jethro to notice?

I would really find this feature useful for my workflow, I believe others would as well.

Thanks

**Comment by nobiot** [comment]
One easy option would be to add the following in your configuration:
```
(add-hook 'org-log-buffer-setup-hook #'org-roam--register-completion-functions-h)
```
After you have done this, `org-add-note` should be able to use the "autocompletion".

Note that this does not differentiate whether or not your Org file is in `org-roam-directory` or not; it might fail if you use it outside it.

**Comment by arvydasg** [comment]
@nobiot Thank you for spending your time on this issue of mine. The code that you have provided does EXACTLY what I needed! Great!
