### ISSUE TITLE
emacsql-error after update to commit b2d954

### ISSUE THREAD

**Issue by tommyjiang** [org-roam/org-roam#2189]
### Description
As title.

#### Steps to Reproduce
1. Load Emacs
2. Run `org-roam-find-file` to find a org-roam file.

#### Backtrace
Debugger entered--Lisp error: (emacsql-error "near \"IN\": syntax error")
  signal(emacsql-error ("near \"IN\": syntax error"))
  #f(compiled-function (_ code message) "Get condition for MESSAGE provided from SQLite." #<bytecode -0x2041407a7242c43>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e> 1 "near \"IN\": syntax error")
  apply(#f(compiled-function (_ code message) "Get condition for MESSAGE provided from SQLite." #<bytecode -0x2041407a7242c43>) #<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e> (1 "near \"IN\": syntax error"))
  emacsql-handle(#<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e> 1 "near \"IN\": syntax error")
  #f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x1051a908dc6938d9>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e>)
  apply(#f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x1051a908dc6938d9>) #<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e> nil)
  emacsql-parse(#<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e>)
  #f(compiled-function (connection sql &rest args) #<bytecode -0x98ce906b91a0b24>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e> [:update (atime) :in files :values $v1 :where (= file $s2)] [new-atime] "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...")
  apply(#f(compiled-function (connection sql &rest args) #<bytecode -0x98ce906b91a0b24>) #<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e> ([:update (atime) :in files :values $v1 :where (= file $s2)] [new-atime] "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o..."))
  emacsql(#<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e> [:update (atime) :in files :values $v1 :where (= file $s2)] [new-atime] "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...")
  apply(emacsql #<emacsql-sqlite-connection emacsql-sqlite-connection-155bac14082e> [:update (atime) :in files :values $v1 :where (= file $s2)] ([new-atime] "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o..."))
  org-roam-db-query([:update (atime) :in files :values $v1 :where (= file $s2)] [new-atime] "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...")
  org-roam-db--update-file-atime-h()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer 20220510185400-反直觉投资.org> "~/org/org-roam/20220510185400-反直觉投资.org" nil nil "~/org/org-roam/20220510185400-反直觉投资.org" (15859884 64769))
  #f(compiled-function (filename &optional nowarn rawfile wildcards) "Read file FILENAME into a buffer and return the buffer.\nIf a buffer exists visiting FILENAME, return that one, but\nverify that the file has not changed since visited or saved.\nThe buffer is not selected, just returned to the caller.\nOptional second arg NOWARN non-nil means suppress any warning messages.\nOptional third arg RAWFILE non-nil means the file is read literally.\nOptional fourth arg WILDCARDS non-nil means do wildcard processing\nand visit all the matching files.  When wildcards are actually\nused and expanded, return a list of buffers that are visiting\nthe various files." #<bytecode -0x1368d5738a2973cc>)("/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...")
  apply(#f(compiled-function (filename &optional nowarn rawfile wildcards) "Read file FILENAME into a buffer and return the buffer.\nIf a buffer exists visiting FILENAME, return that one, but\nverify that the file has not changed since visited or saved.\nThe buffer is not selected, just returned to the caller.\nOptional second arg NOWARN non-nil means suppress any warning messages.\nOptional third arg RAWFILE non-nil means the file is read literally.\nOptional fourth arg WILDCARDS non-nil means do wildcard processing\nand visit all the matching files.  When wildcards are actually\nused and expanded, return a list of buffers that are visiting\nthe various files." #<bytecode -0x1368d5738a2973cc>) "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o..." nil)
  editorconfig--advice-find-file-noselect(#f(compiled-function (filename &optional nowarn rawfile wildcards) "Read file FILENAME into a buffer and return the buffer.\nIf a buffer exists visiting FILENAME, return that one, but\nverify that the file has not changed since visited or saved.\nThe buffer is not selected, just returned to the caller.\nOptional second arg NOWARN non-nil means suppress any warning messages.\nOptional third arg RAWFILE non-nil means the file is read literally.\nOptional fourth arg WILDCARDS non-nil means do wildcard processing\nand visit all the matching files.  When wildcards are actually\nused and expanded, return a list of buffers that are visiting\nthe various files." #<bytecode -0x1368d5738a2973cc>) "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...")
  apply(editorconfig--advice-find-file-noselect #f(compiled-function (filename &optional nowarn rawfile wildcards) "Read file FILENAME into a buffer and return the buffer.\nIf a buffer exists visiting FILENAME, return that one, but\nverify that the file has not changed since visited or saved.\nThe buffer is not selected, just returned to the caller.\nOptional second arg NOWARN non-nil means suppress any warning messages.\nOptional third arg RAWFILE non-nil means the file is read literally.\nOptional fourth arg WILDCARDS non-nil means do wildcard processing\nand visit all the matching files.  When wildcards are actually\nused and expanded, return a list of buffers that are visiting\nthe various files." #<bytecode -0x1368d5738a2973cc>) "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...")
  find-file-noselect("/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...")
  org-roam-node-marker(#s(org-roam-node :file "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o..." :file-title "反直觉投资" :file-hash nil :file-atime (25212 27950 104435 212000) :file-mtime (25212 27950 96435 436000) :id "5377f88b-632c-45a1-b793-68ee69efb7ff" :level 0 :point 1 :todo nil :priority nil :scheduled nil :deadline nil :title "反直觉投资" :properties (("CATEGORY" . "20220510185400-反直觉投资") ("ID" . "5377f88b-632c-45a1-b793-68ee69efb7ff") ("BLOCKED" . "") ("FILE" . "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...") ("PRIORITY" . "B")) :olp nil :tags nil :aliases nil :refs nil))
  org-roam-node-open(#s(org-roam-node :file "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o..." :file-title "反直觉投资" :file-hash nil :file-atime (25212 27950 104435 212000) :file-mtime (25212 27950 96435 436000) :id "5377f88b-632c-45a1-b793-68ee69efb7ff" :level 0 :point 1 :todo nil :priority nil :scheduled nil :deadline nil :title "反直觉投资" :properties (("CATEGORY" . "20220510185400-反直觉投资") ("ID" . "5377f88b-632c-45a1-b793-68ee69efb7ff") ("BLOCKED" . "") ("FILE" . "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...") ("PRIORITY" . "B")) :olp nil :tags nil :aliases nil :refs nil) pop-to-buffer-same-window nil)
  org-roam-node-visit(#s(org-roam-node :file "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o..." :file-title "反直觉投资" :file-hash nil :file-atime (25212 27950 104435 212000) :file-mtime (25212 27950 96435 436000) :id "5377f88b-632c-45a1-b793-68ee69efb7ff" :level 0 :point 1 :todo nil :priority nil :scheduled nil :deadline nil :title "反直觉投资" :properties (("CATEGORY" . "20220510185400-反直觉投资") ("ID" . "5377f88b-632c-45a1-b793-68ee69efb7ff") ("BLOCKED" . "") ("FILE" . "/home/haojiang/org/org-roam/20220510185400-反直觉投资.o...") ("PRIORITY" . "B")) :olp nil :tags nil :aliases nil :refs nil) nil)
  org-roam-node-find()
  funcall-interactively(org-roam-node-find)
  call-interactively(org-roam-node-find nil nil)
  command-execute(org-roam-node-find)

#### Expected Results
Works fine.

#### Actual Results
emacsql-error

### Environment
- Emacs: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2022-05-05
- Framework: Spacemacs
- Org: Org mode version 9.5.2 (release_9.5.2-25-gaf6f12 @ /usr/local/share/emacs/28.1/lisp/org/)
- Org-roam: 2.2.2- sqlite-connector: sqlite

**Comment by jethrokuan** [comment]
I reverted the commit for now, although I really can't tell from the stacktrace why that fails.

**Comment by tommyjiang** [comment]
Thanks, I comment out the `hook` and it works fine for me.

**Comment by Delapouite** [comment]
Hi.
It looks like you managed to circumvent your problem tommyjiang.
If you don't mind I'm going to close this issue.
Thanks.
