### ISSUE TITLE
"Sticky'ing" the org-roam window 

### ISSUE THREAD

**Issue by yangnom** [org-roam/org-roam#219]
### Brief Abstract
It would be good if I could have the org-roam window be the backlinks for a certain org-roam file when I'm looking at another org-roam file

### Long Description
I've been using org-roam for about a week, and amassing notes, but I've run into two problems and the larger one is that I'll have the file that I want to amass all of my notes into from my daily notes, let's say it's my `emacs` file.
I'll open up the org-roam window on the right to see all the backlinks, and then I'll open a backlink (into a new buffer window below my main `emacs` file, let's say it's `2020-02-29`), but as I'm going through those notes, the org-roam window switches to show me the backlinks for the `2020-02-29`, which is generally pretty useless as I don't think I'll ever have backlinks for the `2020-02-29` type of daily org-roam file.
It would be great if I could "sticky" the `emacs` org-roam backlinks so I can go through the backlinks and open them up in the lower window buffer without losing where I am in the `emacs` backlinks windows.

I hope I've described myself well enough and apologize if I haven't.

The second thing would be if the backlinks could be in reverse order from _newest_ to _oldest_ but that wouldn't be so important if I could "sticky" the org-roam sidebar to a certain files backlinks.

### Please check the following:
- [x] No similar feature requests

**Comment by jethrokuan** [comment]
Maybe this is related to tracking file trails: #118 .

I can see the losing of context happening, and do face it a little myself. I'd need to think about the interface a bit harder.

**Comment by yangnom** [comment]
My best workflow to get around this problem is to make a new workspace, open all the back links in seperate buffers in that workspace, split the screen between the cleanup notes, `emacs` and the daily notes like `2020-02-29`, and then go through all the backlinked buffers closing them off one by one as I copy and redo the relevant information in them to the main notes.
