### ISSUE TITLE
Update from 2022-05-28 throws lisp error (void-function json-serialize) 

### ISSUE THREAD

**Issue by QMeqGR** [org-roam/org-roam#2210]
### Description

After updating org-roam to the 20220528 version I get the following error on startup (with --debug-init):

Debugger entered--Lisp error: (void-function json-serialize)
  json-serialize(t)

If I comment out all of my org-roam configuration in my init.el file, and don't load org-roam, the error goes away.

Notes:
1. I can't run org-roam-diagnostics. It just throws the error "Symbol's function definition is void: json-serialize"
2. Emacs 29.0.50
3. org-version 9.5.3

Let me know if I can provide more information.

**Comment by nobiot** [comment]
It's very unlikely the error is coming from Org-roam. The 20220528 date does not contain any JSON related code; Org-roam in general does not rely on it. If anything, it might be Org-roam-UI.

`json-serialize` in my Emacs 28.1 is written in C. 

For your Emacs 29.0.50, I suggest that the easiest fix would be for you to compile Emacs from source with JSON enabled -- 
If you look at variable `system-configuration-features`, you probably do not see JSON there (mine includes it) -- meaning your Emacs was built without it. Building JSON should the default, so I guess you are missing a relevant development library. In my Ubuntu, I believe I needed `libjansson-dev`.

**Comment by QMeqGR** [comment]
Thank you, building --with-json fixes the issue.
