### ISSUE TITLE
org-roam-exclude-directories

### ISSUE THREAD

**Issue by notuntoward** [org-roam/org-roam#2211]
### Brief Abstract
I'd like a customization to exclude a list of subdirectories below my top level org-roam note database
### Long Description
When I point other programs at my org-roam directory, they somethings leave their own directories in it.  For example, logseq leaves a subdirectory `logseq` and then underneath that, it makes a backup of any org-roam note I open in logseq.  This causes org-roam to create error messages, saying that I have notes with the same key.
### Please check the following:

- [ x] No similar feature requests

**Comment by jethrokuan** [comment]
You can add the directory to `org-roam-file-exclude-regexp` directly:

```
(defcustom org-roam-file-exclude-regexp (list org-attach-id-dir)
  "Files matching this regular expression are excluded from the Org-roam."
  :type '(choice
          (repeat
           (string :tag "Regular expression matching files to ignore"))
          (string :tag "Regular expression matching files to ignore")
          (const :tag "Include everything" nil))
  :group 'org-roam)```

**Comment by notuntoward** [comment]
Thanks for the very quick answer.  I did see `org-roam-file-exclude-regexp` but didn't realize that it would also exclude directories.  But it does.
