### ISSUE TITLE
Question about parent/child nodes hierarchy

### ISSUE THREAD

**Issue by deb75** [org-roam/org-roam#2213]
Hello,

Usually, as far as I understand, each org heading with an id acts as a node
whose parent is either the higher level heading, if this one has an id, or the org file itself.

This means that if I have a file like this :
* heading 1
* heading 2
* heading 3

The graph structure will be a star centered on the org file containing the headings
heading3-------file--------heading 1
                          |
                          |
                 heading2

I wonder if it is (would be) possible to change this node's hierarchy and to make it appear as a chain : 
file-------------heading1-----------heading2-------heading3

that is to say, the parent node of one heading is the previous heading with an id and at same level.

This makes sense for example if you build a course on (e.g.) quantum physics : 
quantum_physics.org
* Introduction
* First postulate
* Second postulate
* Third postulate
* Applications
** Sensing
** Communication
** Computing

The first level nodes should be chained : 
quantum_physics.org----introduction-----First p-----Second p-----Third p-----applications

in order to reflect the fact that there is an implicit dependency between headings : 
you need to understand the first postulate before the second, the second before the third,
and all postulates before applications

However, when dealing with applications, you can dive into sensing, communication or
computing independently of each subject, so the corresponding nodes should refer the
Application node itself and appear as a star centered on applications.

Ideally this should be parameterized at the file level depending on which hierarchy is
the most pertinent, as a I tried to demonstrate.

What say you ?

PS : My apologies for my poor understanding in quantum physics, I think you can tackle
      at least the two first postulates independently, this is just an example.

**Comment by deb75** [comment]
Any thoughts ?

Regards

**Comment by nobiot** [comment]
Are you using Doom?

Where do you see the hierarchy among nodes? (where does Org-roam display relationship among nodes in a hierarchical manner)?

**Comment by deb75** [comment]
in `org-roam-ui`

**Comment by nobiot** [comment]
I suggest you raise this issue in their repo.

**Comment by deb75** [comment]
I move it here #243
