### ISSUE TITLE
`org-roam-property-*` code duplication removed

### ISSUE THREAD

**Issue by clanghans** [org-roam/org-roam#2217]
### Brief Abstract
Named functions in the headline have code duplication within their deprecated counterparts e.g. `org-roam-add-property`.

### Long Description
I was stumbling upon these functions yesterday and was really confused by the code duplication. 

### Proposed Implementation (if any)
the deprecated functions should call the correct functions.  

### Please check the following:

- [x] No similar feature requests

**Comment by clanghans** [comment]
provided PR

**Comment by jethrokuan** [comment]
looks good. The only reason there are 2 versions of it is because I think some people had been using these functions in their own config, and the function arguments are flipped so there's no way to remove it cleanly without breaking their configs.

**Comment by clanghans** [comment]
Was assuming something like this. 

Is there a way to mark functions as deprecated in elisp?

**Comment by jethrokuan** [comment]
yeah using `define-obsolete-function-alias`, or just the primitive `make-obsolete`

**Comment by jethrokuan** [comment]
Closed with #2218
