### ISSUE TITLE
Allow `:aliases` to be applied during `org-roam-capture-`

### ISSUE THREAD

**Issue by jeremyf** [org-roam/org-roam#2220]
### Brief Abstract

As part of the capture sequence, I would like to be able to add an alias (or aliases).

### Long Description

I have tried the following; both adding `:aliases` to the node and to the `:info`.  However, none of these appear to add the `:ROAM_ALIASES:` to the capture buffer.

```emacs-lisp
(org-roam-capture-
   :keys keys
   :node (org-roam-node-create :title title :aliases aliases)
   :info (list :ref url :aliases aliases)
   :props '(:immediate-finish nil)
   :templates templates)
```

### Please check the following:

- [X] No similar feature requests

**Comment by mholson** [comment]
Does [issue 1783](https://github.com/org-roam/org-roam/issues/1783) help?  

I was able to add :ROAM_ALIASES: to the file PROPERTY drawer during a capture, although it appears before :ID: property.

**Comment by jeremyf** [comment]
Yes.  This would work for me.  Thank you!

**Comment by mholson** [comment]
@jeremyf are you still able to capture the ALIAS to the :PROPERTY: drawer using this method? I ask because after a recent upgrade it seems that it no longer works.
