### ISSUE TITLE
Entry capture template that uses ID property is given ID of parent node, and not unique value. 

### ISSUE THREAD

**Issue by roygbyte** [org-roam/org-roam#2223]
### Description

When making use of the PR ["create ID before capture process #2049"](https://github.com/org-roam/org-roam/pull/2049) to use `${id}` in an *entry* capture template, the ID of the parent node is passed to the template. What I would expect is that a unique ID is passed to the entry, since I would expect I'd want the new entry cached for lookup later.  

#### Steps to Reproduce

This is an example entry template that uses `${id}`.

``` emacs-lisp
    (use-package org-roam
      :custom
          (org-roam-dailies-capture-templates
            '(("T" "Entry with unique id" entry "* %? ${id}"
               :if-new (file+head "test-%<%Y_%m_%d>.org" "#+title: %<%Y-%m-%d>\n" )))))
```

#### Backtrace

N/A

#### Expected Results

I would expect that the value return to `${id}` is unique and not the id of the parent node. 

#### Actual Results

The id inserted into the template is the same id as the parent node. 

``` emacs-lisp
:PROPERTIES:
:ID:       b258e9a0-ddf5-4adb-969d-763b7bcf3867
:END:
#+title: 2022-06-15
*  b258e9a0-ddf5-4adb-969d-763b7bcf3867
```

### Environment

```
- Emacs: GNU Emacs 28.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2022-05-09
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-796-ge68375.dirty-elpa @ /home/user/.emacs.d/elpa/org-20210929/)
- Org-roam: 2.2.2- sqlite-connector: sqlite
- ```

**Comment by astynax** [comment]
@roygbyte There is no easy way to deduce what is the "parent" you asked about. If you want to capture a note about *the file or note that was active* just before the capturing you can try this:

```emacs-lisp
(defvar *org-roam-captured-origin* nil
  "A buffer that was active just before capturing was started.")

(defadvice org-roam-capture- (around org-roam-capture-origin activate)
  (let ((*org-roam-captured-origin* (current-buffer))) ; remember current buffer
    ad-do-it))

;; This call is just a demo of the concept
(org-roam-node-find
 nil
 "foo"
 nil
 nil
 ;; you'll need just this template
 :templates
 '(("d" "default" plain "* %(buffer-name *org-roam-captured-origin*)\n%?" ; <- accessing to remembered buffer
    :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}"))))
```

Here is a more complex example. It inserts links to nodes or links to files with current line number:

```emacs-lisp
(defun org-roam-get-origin-link ()
  "Returns an org-link to the current org-roam node or file."
  (if-let* ((id (org-roam-id-at-point))
            (node (org-roam-node-from-id id)))
      (org-make-link-string
       (format "id:%s" id)
       (org-roam-node-title node))
    (when-let ((fname (buffer-file-name (current-buffer))))
      (org-make-link-string
       (format "file:%s::%s" fname (line-number-at-pos (point)))
       fname))))

(defvar *org-roam-captured-origin* nil
  "A buffer that was active just before capturing was started.")

(defadvice org-roam-capture- (around org-roam-capture-origin activate)
  (let ((*org-roam-captured-origin* (org-roam-get-origin-link)))
    ad-do-it))

(org-roam-node-find
 nil
 "foo"
 nil
 nil
 :templates
 '(("d" "default" plain "* %(or *org-roam-captured-origin* \"???\")\n%?" ; insert link as-is
    :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}"))))
```

So there is no need to expand templates infinitely when you already have all you need :)

**Comment by roygbyte** [comment]
I think you have misunderstood my question! What I'm saying is that during the template expansion for a new node entry, `{I'd}` is expanded to the org ID for the node the entry is contained within, when it would make more sense (in my situation) to expand it to a new org ID.

**Comment by astynax** [comment]
`${id}` that equals to ID of that new note you want to capture totally makes sense to me. If you need just a fresh new org id why just don't use `%(org-id-new)`?

**Comment by roygbyte** [comment]
I didn't use `%(org-id-new)` because I didn't know I could! :) Wow, that is super handy--thank you for sharing that with me.
