### ISSUE TITLE
Links not displayed properly in org-roam-buffer

### ISSUE THREAD

**Issue by joachimnielandt** [org-roam/org-roam#2228]
### Description
I have a pretty basic Doom Emacs setup, using org-roam, and trying to figure out how to cleanly display links' titles in the backlinks of the org-roam-buffer.

The only way I currently know of to control this behaviour is `org-toggle-link-display`, but this doesn't work in the minibuffer that `org-roam-buffer` creates (it outputs an error: `org-link is not a valid folding spec`).

#### Steps to Reproduce

Create two files:
```
:PROPERTIES:
:ID:       004c42ce-8770-46a4-b937-a35299b1cdf3
:END:
#+title: Test node A
#+filetags:
Link to B: [[id:59be5585-ac84-4f25-9855-5f89cee3ec03][Test node B]]
```

```
:PROPERTIES:
:ID:       59be5585-ac84-4f25-9855-5f89cee3ec03
:END:
#+title: Test node B
#+filetags:
Link a A: [[id:004c42ce-8770-46a4-b937-a35299b1cdf3][Test node  A]]
```
Open org-roam-buffer with `org-roam-buffer-toggle`. Buffer shows the following when in `Test node B`:
```
Backlinks (1)
Test node A (Top)
Link to B: [[id:59be5585-ac84-4f25-9855-5f89cee3ec03][Test node B]]
```

#### Expected Results

Links in the backlinks are rendered with their title, markup hidden.

#### Actual Results

Links are rendered in raw text: `[[id:x][y]`.

### Environment
- Emacs: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)
 of 2022-04-28
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-e9da29b @ /home/joachim/.emacs.d/.local/straight/build-28.1/org/)
- Org-roam: 171a8db
- sqlite-connector: sqlite

**Comment by tjstankus** [comment]
May be a dup of #2198

**Comment by DrBanana419** [comment]
I too have the same problem on doom emacs.  

Environment:
- Emacs: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)
 of 2022-06-13
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-e9da29b @ /home/user/.emacs.d/.local/straight/build-28.1/org/)
- Org-roam: 171a8db
- sqlite-connector: sqlite

**Comment by honza** [comment]
I still have this problem on latest d95d25615e69e7cc847641800c1886366336c97e using doom.

**Comment by thephatmaster** [comment]
I still also have this problem, and the links aren't clickable - also using doom - apologies, but I have no idea how to check the version of org-roam I am using

**Comment by WouterSpekkink** [comment]
The fix does not work for me either. The links are displayed in literal form with the current versions of org and org-roam. Setting `org-fold-core-style` to "overlays" corrects the display of links in the org-roam-buffer, but then breaks `org-cycle` for me: Headings and drawers will fold, but they refuse to unfold.

Given that the default value for `org-fold-core-style` is "text-properties", I would modestly suggest that a fix would ideally avoid having to change the value to "overlays"?
