### ISSUE TITLE
Symlinks broken again.

### ISSUE THREAD

**Issue by MagicRB** [org-roam/org-roam#2239]
### Description

When a symlink is put into org roam's directory, it won't traverse into it and won't discover nodes in it.

#### Steps to Reproduce

Install org-roam and then create a symlink in `org-roam-directory` pointing out of the roam directory.

#### Backtrace
N/A

#### Expected Results
Org Roam works through the symlink.

#### Actual Results
All files behind the symlink aren't indexed.

### Environment
- Emacs: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)
- Framework: N/A
- Org: Org mode version 9.5.3 (9.5.3-g8e69ad @ /home/main/.emacs.d/straight/build/org/)
- Org-roam: v2.2.2-20-g917a325
- sqlite-connector: sqlite

**Comment by nobiot** [comment]
I just tried with the last available on MELPA (org-roam-20220723.2058 -- this should correspond to the lastest commit). Both a symlink to a file and to a directory work... Not sure what might be the cause of the behaviour your observe... The files in the symlinked directory (the target directory is outside of `org-roam-directory`) are all index and can be found with `org-roam-node-find`.

Initially I thought you could use `file-truename` as indicated in [Configuration](https://github.com/org-roam/org-roam#configuration) section of README but in my case symlinks work without using it -- it may be still worth trying just in case for you.
 
I have different Emacs and Org versions from yours.

- Emacs: GNU Emacs 28.1.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
 of 2022-05-15
- Framework: N/A
- Org: Org mode version 9.6 (9.6-g127e7f @ /home/nobiot/.config/emacs/elpa/org-9.6snapshot0.20220723.141654/)
- Org-roam: 2.2.2- sqlite-connector: sqlite

**Comment by MagicRB** [comment]
It may be some regression in Emacs, because I just tested a version of Org Roam I know works (pinned in my dotfiles) and it still doesn't work. I'll try updating emacs, if not then I'll revert it to a know to work version.

**Comment by MagicRB** [comment]
I tested both an older Emacs and Org and Org Roam, still nothing, must be something up with my filesystem or config, idk tbh. I have to solve it though since i cant work until it works

**Comment by MagicRB** [comment]
`strace`ing Emacs shows it `open`s files in the symlink, but it doesn't index them for some bizzare reason.

**Comment by MagicRB** [comment]
I attempted to match up my Emacs to yours and still nothing
- Emacs: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)
- Framework: N/A
- Org: Org mode version 9.5.4 (9.5.4-g127e7f @ /home/main/.emacs.d/straight/build/org/)
- Org-roam: v2.2.2-21-ge435581
- sqlite-connector: sqlite

**Comment by MagicRB** [comment]
Found it,  a certain program added license headers to all my files, which broke org-roam....
