### ISSUE TITLE
feature request : just show file node when run org-roam-node-find

### ISSUE THREAD

**Issue by dian-yu-luo** [org-roam/org-roam#2245]
As far as I know, roam has two types of nodes: headline nodes and file nodes. I want to save both of them in a sqlite database, however when I run "org-roam-node-find," I hope only file nodes are candidates, and when I run "org-roam-node-insert," both of them are referred to. 
what about a condition : (nodes.level == 0)

**Comment by chrisbarrett** [comment]
I have a similar use-case. You can do this yourself by defining your own command:

```elisp
(defun my-org-roam-find (&optional other-window)
  "Find an org-roam node. See `org-roam-node-find'."
  (interactive "P")
  (org-roam-node-find other-window nil (lambda (node)
                                         (= 0 (org-roam-node-level node)))))
```

**Comment by dian-yu-luo** [comment]
> 

thanks for your help

**Comment by Delapouite** [comment]
dian-yu-luo, if you don't mind I'm gonna close this issue as chrisbarrett provided a working snippet.
