### ISSUE TITLE
org-roam-mode buffer is read-only

### ISSUE THREAD

**Issue by lehitoskin** [org-roam/org-roam#2248]
### Description
I created a simple org-roam file, saved it to disk, and closed emacs. Opening it again the buffer was set to regular org-mode, so I manually set it with `M-x org-roam-mode`, but after that the syntax highlighting disappeared and then the buffer became read-only.

#### Steps to Reproduce
1. Open Emacs
2. `C-x C-f` a pre-existing .org file
3. `M-x org-roam-mode`
4. Try to edit the file (either typing directly or trying to insert a node link with `C-c n i`)
5. Try to save the file
6. Buffer is read-only

#### Backtrace
`M-x toggle-debug-on-error` never opens the debugger buffer, but here's the output of the Messages window:
```
For information about GNU Emacs and the GNU system, type C-h C-a. [2 times]
Debug on Error enabled globally
You can run the command ‘org-roam-mode’ with M-x o-ro-mo RET
Mark set
a is undefined
s is undefined
d is undefined
f is undefined
Making completion list...
funcall-interactively: Buffer is read-only: #<buffer 20220811124832-org_mode_info.org>
Mark set
```

#### Expected Results

org file is able to be edited by org-roam-mode

#### Actual Results

buffer is read-only when in org-roam-mode

### Environment
```
Copy info below this line into issue:
- Emacs: GNU Emacs 28.1 (build 1, x86_64-apple-darwin21.4.0, Carbon Version 165 AppKit 2113.4)
 of 2022-08-04
- Framework: 
- Org: Org mode version 9.5.2 (release_9.5.2-25-gaf6f12 @ /Applications/MacPorts/EmacsMac.app/Contents/Resources/lisp/org/)
- Org-roam: 2.2.2- sqlite-connector: sqlite
```

### init.el
It's entirely bare-bones, trying to diagnose what could be the issue.
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 `(org-roam-directory ,(file-truename "~/Documents/Dropbox/Apps/org-roam"))
 '(package-selected-packages '(org-roam)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(require 'org-roam-mode)
(define-key org-roam-mode-map (kbd "C-c n l") 'org-roam-buffer-toggle)
(define-key org-roam-mode-map (kbd "C-c n f") 'org-roam-node-find)
(define-key org-roam-mode-map (kbd "C-c n i") 'org-roam-node-insert)
```

### Final Thoughts
I opened a `*scratch*` buffer, turned on org-roam-mode, and then _that_ also turned read-only. It seems like it isn't isolated to just org files.

**Comment by chrisbarrett** [comment]
Hey there! `org-roam-mode` is the mode for the backlinks buffer, not for the org files you'd normally edit. See the manual for setup instructions:
https://www.orgroam.com/manual.html#Setting-up-Org_002droam

Since you've got it installed, probably the only thing you need to do is load it up after org.

```elisp
;; Bare-metal elisp
(with-eval-after-load 'org
  (org-roam-db-autosync-enable))

;; use-package
(use-package org-roam
  :after org
  :demand t
  :custom
  (org-roam-directory "~/org/or/wherever")
  :config
  (org-roam-db-autosync-enable))
```

**Comment by lehitoskin** [comment]
That explains a lot! Adding `(org-roam-db-autosync-enable)` seems to get things working. Thanks!
