### ISSUE TITLE
Links from drawers of nested nodes aren't picked up

### ISSUE THREAD

**Issue by VitruvianVice** [org-roam/org-roam#2252]
### Description

Links from property drawers are not inserted into the `links` table.

#### Steps to Reproduce

_Edit: This steps are not enough, follow the steps outlined in_ [this comment](https://github.com/org-roam/org-roam/issues/2252#issuecomment-1226306324) _to reproduce. I didn't edit it here to keep the conversation_ comprehensible.

1. Load Emacs
2. Create an org-link in a property drawer
3. Save the file (or run `org-roam-db-update-file`)

#### Expected Results

A new row with the link shows up in the links table

#### Actual Results

No new row was created

**Comment by nobiot** [comment]
I don't seem to be able to reproduce the issue report. Storing links from property drawers is built-in with Org-roam.
See [`org-roam-db-extra-links-elements`](https://github.com/org-roam/org-roam/blob/main/org-roam-db.el#L113) and [`org-roam-db-extra-links-exclude-keys`](https://github.com/org-roam/org-roam/blob/main/org-roam-db.el#L125).

If I use the property named `link`, I can see the backlink displayed as normal...

```
* Heading
:PROPERTIES:
:link: [[id:d0437ffc-a9c0-42a4-99ef-44cd9487a770][org-id]]
:END:
```

**Comment by VitruvianVice** [comment]
Thanks for looking into it. I was probably negligent with my description. I'll test it again later when I have more time!
Regarding the variables: I have come across them too, also read the docstring explicitly mentioning prop-drawers and wondered why it didn't work for me, I thought it a possibility that it was a v1->v2 issue.

But I'll examine it more isolated and give more info, later. Maybe I messed up something. As far as I understand its not the variables though:
```
org-roam-db-extra-links-elements 
=> (node-property keyword)

org-roam-db-extra-links-exclude-keys 
=> ((node-property "ROAM_REFS")
 (keyword "transclude"))
 ```

**Comment by nobiot** [comment]
Perhaps narrowing affects the behavior and your PR fixed this issue? The report above does not mention narrowing. What’s the exact step of I want to reproduce the issue?

You might be using Doom (not clear); that might also affect your observation. I don’t use it.

**Comment by VitruvianVice** [comment]
I have reproduced it runnin `emacs -q -l init-org-roam.el` where I only loaded straight, use-package and org-roam as described in the docs. The content of init-org-roam.el is:

```
(setq user-emacs-directory default-directory)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory (concat default-directory "roam/"))
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n g" . org-roam-graph)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n c" . org-roam-capture)
         ;; Dailies
         ("C-c n j" . org-roam-dailies-capture-today))
  :config
  (org-roam-db-autosync-mode)
  ;; If using org-roam-protocol
  (require 'org-roam-protocol))
```

But you probably don't need to do this. You can follow these steps:

1. Set up a simple filenode (via `org-roam-node-find`). Mine got the id: B8159C17-31EF-4952-807D-077EF965B4FC
2. Set up a second filenode
3. Add a heading node into the second node and link the first node from its property drawer. Or simply paste the content of my buffer:
```
:PROPERTIES:
:ID:       AF36A7E4-481F-406B-A18F-1BB369A5D889
:END:
#+title: filenode2

* headingnode1
:PROPERTIES:
:ID:       E7477780-A2AC-49C6-86B6-853E51866430
:link:     [[id:B8159C17-31EF-4952-807D-077EF965B4FC][filenode1]]
:END:
```
4. Then call `org-roam-db-sync`

This time you will not have the correct backlinks.

What I in a slip called "narrowing" is the problem. Its about the function`org-roam-db-map-links` which is invoked by `org-roam-db-update-file` to map `org-roam-db-insert-link` over the links of a file.

If `org-element-context` determines the element to be a `link` everything is fine. In the property drawer elements are of type`node-property` (As you know, that's why you referred me to `org-roam-db-extra-links-elements`).
To get a context of type `link` the link is inserted in an empty buffer and `org-element-context` is called again.
The resulting org-element is then of type `link` and passed as argument to the FNS `org-roam-db-map-links` was called with (i.e. `org-roam-insert-link`).

`org-roam-db-insert-link` starts with the statement `(goto-char (org-element-property :begin link))` and moves to position 1 where it calls `(source (org-roam-id-at-point))` where it picks up whatever id is at the beginning of the buffer as the source of the link.

The correct bounds of the link in the original document are known at the execution time of `org-roam-db-map-links` which is why I proposed to set them then.

**Comment by bhuztez** [comment]
I run into the same issue months ago. I have a naive fix #2230 for this. It has nothing to do with narrowing. I checked the database, the outline of the link is blank, so that it does not show up.

**Comment by VitruvianVice** [comment]
@bhuztez with _outline_ you mean the property `:outline` in the `properties` column?
Interesting that you get a new row at all, for me it doesn't create any. Without investigation I'd guess that depends on the buffer structure. Have you checked that the `source`-id is correct?

I have not tested it yet but your code looks like a valid fix. Judging by the code, if it were my decision to make, I'd prefer your PR over mine. My fix changes less code but your `org-roam-db-map-links` function is cleaner. Taking the `org-element-context` not from a temporary buffer but the original seems benefitial to me!

**Comment by bhuztez** [comment]
@VitruvianVice at that time, I `select properties from links where dest=xxxx` there is a row without outline. I updated to latest org-roam, now, there is nothing returned.

**Comment by jethrokuan** [comment]
@bhuztez's fix seems to have done it, closing for now
