### ISSUE TITLE
tags with - (e.g. abc-def) are not handled properly

### ISSUE THREAD

**Issue by dmgerman** [org-roam/org-roam#2266]
### Description

tags with a hyphen in between (eg. abc-def) are not properly handled in header
nodes.

#### Steps to Reproduce

create an internal node with an id, such as:

     * Bar   
     :PROPERTIES:
     :id: barid
     :END:

then run org-roam-add-tag inside this node. Add tag: abc-def.
Do it again. And do it again.

Now you have:

     * Bar   :abc-def: :abc-def: :abc-def:
     :PROPERTIES:
     :id: barid
     :END:

Furthermore, the tag is not added to the table tags either.

#### Backtrace
NA

#### Expected Results

It should add only one tag, instead of repeating it. Also, the tags table should include this tag.

#### Actual Results

- tag is not added to database
- tag is inserted several times

### Environment

- Emacs: GNU Emacs 28.1 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559))
 of 2022-05-11
- Framework: Prelude
- Org: Org mode version 9.5.2 (release_9.5.2 @ /Users/dmg/.emacs.d/org-mode/lisp/)
- Org-roam: 2.2.2- sqlite-connector: sqlite

**Comment by andersjohansson** [comment]
This is most certainly because `-` is not allowed in tags in org, so this is not a problem in org-roam.

> Every headline can contain a list of tags; they occur at the end of the headline. **Tags are normal words containing letters, numbers, ‘_’, and ‘@’**. Tags must be preceded and followed by a single colon, e.g., ‘:work:’. Several tags can be specified, as in ‘:work:urgent:’. Tags by default are in bold face with the same color as the headline. 
From https://orgmode.org/guide/Tags.html

However, I think that what is stated in the manual does not match how org works exactly. `#` and `%` are allowed as well, given that `org-tag-re`, the regexp responsible for matching tags, is: `"[[:alnum:]_@#%]+"`.

**Comment by andersjohansson** [comment]
I don’t have an answer for _why_ this is the case in org, however. My workaround for distinguishing parts of a tag is usually to use `_` (`abc_def`) or capitalization: `abcDef`

**Comment by jethrokuan** [comment]
seems like there is a satisfactory explanation for this, thanks @andersjohansson .
