### ISSUE TITLE
Upgrading to version 2.2.2 has broken my system.

### ISSUE THREAD

**Issue by GeekyPeas** [org-roam/org-roam#2267]
### Description
Upgrading to version 2.2.2 has broken my system. 
#### Steps to Reproduce

More details can be found on this [emacs.stackexchange post](https://emacs.stackexchange.com/questions/73807/opening-emacs-without-the-scratch-buffer-when-opening-a-file-please-tell-me-wha).

Quick summary:
I upgraded to `org-roam` version 2.2.2 via the following steps: 
1. `M-x list-packages` 
2. Then select `org-roam` and clicked `delete`.
3. `M-x list-packages` again
4. Then select `org-roam` and clicked `install`.

Now if I run

    (use-package org-roam
      :ensure t)

in my `*scratch*` buffer it executes and returns `nil`.

If I now do `M-x org-roam` I get the error message:  `command-execute: Autoloading file $HOME/.emacs.d/elpa/org-roam-2.2.2/org-roam.elc failed to define function org-roam`.

In the [emacs.stackexchange post](https://emacs.stackexchange.com/questions/73807/opening-emacs-without-the-scratch-buffer-when-opening-a-file-please-tell-me-wha) initially I thought it to be different issue. But as it became clearer to me what was the _actual_ issue, I felt someone with more expertise/ familiarity with the `org-roam` package may be needed for help. Hence posting the relevant details here.

This is the part of my `.emacs` that is relevant to `org-roam`:

    (use-package org-roam
          :ensure t
          ;; :hook
          ;; (after-init . org-roam-mode)
          :custom
          (org-roam-directory "$HOME/Zettelkasten")
          :bind (:map org-roam-mode-map
                  (("C-c n l" . org-roam)
                   ("C-c n f" . org-roam-find-file)
                   ("C-c n r" . org-roam-graph))
                  :map org-mode-map
                  (("C-c n i" . org-roam-insert))
                  (("C-c n I" . org-roam-insert-immediate))))
    ;; (add-hook 'after-init-hook 'org-roam-mode)
    ;; (add-to-list 'auto-mode-alist '("\\.org$" . org-roam-mode))
    ;; (add-to-list 'auto-mode-alist '("\\.org\\'" . org-roam-mode))

I commented out the `(add-hook 'after-init-hook 'org-roam-mode)` lines based on the discussions on the [emacs.stackexchange post](https://emacs.stackexchange.com/questions/73807/opening-emacs-without-the-scratch-buffer-when-opening-a-file-please-tell-me-wha).

After commenting out the `(add-hook 'after-init-hook 'org-roam-mode)` lines I was trying to use `auto-mode-alist` but it was causing me these errors: `File mode specification error: (void-function org-roam-mode)`. So I commented out the `auto-mode-alist` lines as well.

Everything in `*Messages*` looks normal except this:

    Source file ‘$HOME/.emacs.d/elpa/org-9.4.4/org.el’ newer than byte-compiled file; using older file

*EDIT:* I upgraded my `org`-mode to version 9.5.5. So the above message doesn't appear for me any more.

#### Backtrace

If I now do `M-x org-roam` I get the error message:  `command-execute: Autoloading file $HOME/.emacs.d/elpa/org-roam-2.2.2/org-roam.elc failed to define function org-roam`.

This is the output of `M-x toggle-debug-on-error`:
```

Debugger entered--Lisp error: (error "Autoloading file $HOME/.emacs.d/elpa/org-roam...")
  autoload-do-load((autoload "org-roam" nil t nil) org-roam)
  command-execute(org-roam record)
  execute-extended-command(nil "org-roam" "org-roam")
  funcall-interactively(execute-extended-command nil "org-roam" "org-roam")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

```    

#### Expected Results

`org-roam` should work.
#### Actual Results
`org-roam` is not working

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
 of 2022-01-24, modified by Debian
- Framework: N/A
- Org: Org mode version  ( @ $HOME/.emacs.d/elpa/org-9.4.4/)
- Org-roam: 2.2.1- sqlite-connector: sqlite

*EDIT: I upgraded my org-mode*. So new results are:
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
 of 2022-01-24, modified by Debian
- Framework: 
- Org: Org mode version 9.5.5 (9.5.5-g8ef620 @ $HOME/.emacs.d/elpa/org-9.5.5/)
- Org-roam: 2.2.1- sqlite-connector: sqlite

**Comment by franburstall** [comment]
Q: what do you expect the `org-roam` command to do?  I ask because I have `C-c n l` bound to `org-roam-buffer-toggle`.  I recall that the API changed quite a bit with v2.

**Comment by GeekyPeas** [comment]
> Q: what do you expect the `org-roam` command to do? I ask because the [documentation](https://github.com/org-roam/org-roam#configuration) has `C-c n l` bound to `org-roam-buffer-toggle`. I recall that the API changed quite a bit with v2.

I tried `M-x org-roam-buffer-toggle` and it gives me errors as well.

I am using the config inspired by David Wilson of System Crafters from [here](https://config.daviwil.com/emacs#org-roam) and this config, I believe, should be considered fairly standard as it is featured in the README.md of the official org-roam github repository [here](https://github.com/org-roam/org-roam#getting-started).

However I will give [this official config](https://github.com/org-roam/org-roam#getting-started) a try and see if it fixes my situation.

**Comment by GeekyPeas** [comment]
@franburstall : Yes you are probably right - the API has changed. When I switched to the new config file, and I pressed `C-c n l` it did showed something was compiling in the status bar. I couldn't capture the message. I closed my emacs without recording the message.

Now that I am using [this official config](https://github.com/org-roam/org-roam#getting-started) (with only the `org-roam-directory` changed) it is still not working for me. 

This is the backtrace for trying `M-x org-roam-node-insert`:
```
Debugger entered--Lisp error: (void-function \(setf\ org-roam-node-id\))
  \(setf\ org-roam-node-id\)("2abc239d-1630-43f1-b326-a18f25f6283c" #s(org-roam-node :file nil :file-title nil :file-hash nil :file-atime nil :file-mtime nil :id nil :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title "new_node" :properties nil :olp nil :tags nil :aliases nil :refs nil))
  org-roam-capture-(:node #s(org-roam-node :file nil :file-title nil :file-hash nil :file-atime nil :file-mtime nil :id nil :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title "new_node" :properties nil :olp nil :tags nil :aliases nil :refs nil) :info nil :templates nil :props (:link-description "new_node" :finalize insert-link :call-location #<marker at 106 in 20220925D.org>))
  org-roam-node-insert()
  funcall-interactively(org-roam-node-insert)
  call-interactively(org-roam-node-insert record nil)
  command-execute(org-roam-node-insert record)
  execute-extended-command(nil "org-roam-node-insert" "org-roam-node-insert")
  funcall-interactively(execute-extended-command nil "org-roam-node-insert" "org-roam-node-insert")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

```
I am a bit lost as to what is going on now.

**Comment by GeekyPeas** [comment]
On `*Messages*` I am getting these messages: `org-roam-capture-: Symbol’s function definition is void: \(setf\ org-roam-node-id\)`

**Comment by GeekyPeas** [comment]
Alright major progress: I uninstalled `org-roam` once again and installed it again. Now with [this official config](https://github.com/org-roam/org-roam#getting-started) I am able to run `C-c n i` to insert a new file etc. But now my old zettels are missing. I see them in my org-roam-directory. But somehow org-roam doesn't see them. What to do?

**Comment by GeekyPeas** [comment]
Further I am able to `C-c n i` to insert nodes. But when I `C-c n f` to find a zettel: I don't see any suggestions. Even if I enter the full name of an existing node after `C-c n f`, it just creates them again. Please help!

**Comment by franburstall** [comment]
What was the previous version you were using?  If v1 then things have
changed a lot.  See section 16.5 of the manual for migration help.

**Comment by GeekyPeas** [comment]
I don't remember the previous version that I was using. But I was on v2 from the start. I tried out org-roam around the time David Wilson of System Crafters made his youtube video. So it must be after v2.

**Comment by franburstall** [comment]
Try `(org-roam-db-sync t)` to force a rebuild of the database.

**Comment by GeekyPeas** [comment]
> Try `(org-roam-db-sync t)` to force a rebuild of the database.

That almost fixed it for me! Now I am able to find all the nodes that I created with version 2.2.2.

However my earlier zettels are not found. But if I query the `$HOME/.emacs.d/org-roam.db` I can _now_ see my old zettels in the table `files` and the new zettels are in the table `nodes` (and also in `files`)! I think I understand why this is happening: From the [org-roam user Manual on: The org-roam node](https://www.orgroam.com/manual.html#The-Org_002droam-Node) it says:

> _A node is any headline or top level file with an ID._

In my earlier version this was not the case. So:

1. how do I now automatically generate IDs for my old zettels?
2. what is a _safe_ way to delete zettels. (As I peruse through I find some of my zettels are obsolete. I might have created them for something but didn't maintain them. And now I don't want to keep them around any more. But I am worried that some other zettel might be linking to them and so _backlinks_ could possibly break? Right now as my old zettels are not showing on the `node` table I think my backlink may be broken - so I am a little scared to just delete anything now.)

**Comment by GeekyPeas** [comment]
Another thing that is broken for me: If I do `M-x org-roam-mode` then it becomes this _read-only_ buffer _without_ any syntax highlighting (all my content is now unfolded and white. It looks like the text would appear on any other editor, like say on `gedit`, that does not understand `org-mode`). 

Is this the _new_ intended behavior now? Or is something _broken_?

**Comment by franburstall** [comment]
> > _A node is any headline or top level file with an ID._
> 
> In my earlier version this was not the case.

Then you were on v1 before: this is the distinguishing feature of v2!  Please look at the Migration part of the manual.

**Comment by GeekyPeas** [comment]
Yes I have successfully migrated my database to v2 now! Thanks a lot @franburstall for your many kind inputs!

So `(add-to-list 'auto-mode-alist '("\\.org$" . org-roam-mode))` is still broken for me. More details [here](https://github.com/org-roam/org-roam/issues/2267#issuecomment-1257099791). 

Other than this, everything else is solved! Please suggest what I can do with my broken `org-roam-mode`.

**Comment by franburstall** [comment]
I think you misunderstand what `org-roam-mode` is for.  From the documentation:

>Major mode for displaying relevant information about Org-roam nodes.
This mode is used by special Org-roam buffers, such as persistent
‘org-roam-buffer’ and dedicated Org-roam buffers
(‘org-roam-buffer-display-dedicated’), which render the
information in a section-like manner (see
‘org-roam-mode-sections’), with which the user can
interact with.

In particular, you should *not* be using it for `.org` files.

**Comment by GeekyPeas** [comment]
Got it. Thanks. So closing this issue now.
