### ISSUE TITLE
Skip node selection if the org-capture-template defines a node

### ISSUE THREAD

**Issue by ntBre** [org-roam/org-roam#2269]
### Brief Abstract

I added a template for adding a line to a table in a particular org-roam node:

```elisp
  (add-to-list
   'org-roam-capture-templates
   '("w" "weight" table-line "| %t | %? | "
     :target (node "Weight")
     :unnarrowed t))
```

and yet when I call `org-roam-capture`, it first prompts me for the node. I think it would make more sense to ask for the capture template first and then the node if the template requires a node to be specified. In this case, I can select any node and my target node from the template is still found.

### Proposed Implementation

I think this would just involve moving the template checking logic from `org-roam-capture-` into `org-roam-capture`. I'm happy to submit a PR for this, probably later today if there is any interest in the idea.

I made a couple of searches in the issues and PRs for similar issues, but apologies in advance if this has been discussed before.

**Comment by bitozoid** [comment]
IMHO I also think that the use of `:target` is confusing. The node selection of `org-roam-capture` seems to be taken into account for files but ignored for nodes.

Anyway, if your node is in a fixed position, I'd use `org-capture-templates` for this.

**Comment by ntBre** [comment]
Thanks for the suggestion! Somehow I hadn't even considered using a normal org-capture-template for this. That works great! When I looked at the code it seemed like this would actually require a huge change anyway.
