### ISSUE TITLE
Suggestion list for node finding tends to omit title

### ISSUE THREAD

**Issue by xeruf** [org-roam/org-roam#2272]
#### Steps to Reproduce

1. Resize emacs to be slim, or open a second buffer.
2. Call org-roam-node-find 

#### Expected Results

The box uses the whole width, and if something is cut, keeps the node name in view.

#### Actual Results

depending on the width *of the focused buffer*, the title is not infrequently omitted:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/13354331/193475877-c5028823-8ae5-4a8b-bd52-1c5f8cb42c7b.png">

this is especially weird when focusing the backlinks buffer:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/13354331/193475929-f1265357-00af-46f5-92a9-6742aeeed43b.png">

### Environment
- Emacs: GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-09-12
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-86c4635 @ /home/janek/.local/state/emacs/straight/build-28.2/org/)
- Org-roam: d95d256
- sqlite-connector: sqlite

**Comment by cmirdesouza** [comment]
It could be the same as  #2143 , the solution seems to be modify `org-roam-node-display-template`

**Comment by xeruf** [comment]
Yep, moving discussion over there
