### ISSUE TITLE
Advanced Autocompletion

### ISSUE THREAD

**Issue by xeruf** [org-roam/org-roam#2275]
### Brief Abstract

Two little autocompletion issues:
- sometimes I want to autocomplete a very short heading, maybe just two characters, but autocompletion does not  even activate until then - and why does it hide when I have typed out the word? I might still want to add a link
- option to autocomplete case-insensitively as i don't always remember on which pages I capitalised `org` or specific shell commands ^^

### Please check the following:

- [x] No similar feature requests

**Comment by nobiot** [comment]
What’s the package you use for “autocomplete”? Company?

If so, check variable `company-minimum-prefix-length` for the first issue. For the second issue, it’s probably easier id you search in company user manual or forum. I use Corfu for “autocomplete” combined with Orderless and have no issue that you point out — that is, neither of them are directly Org-roam issues

**Comment by nobiot** [comment]
If using Orderless is not an option, you can also check variable `completion-ignore-case`.

**Comment by xeruf** [comment]
thank you! this all came preconfigured with doom, so I was not aware where the problem was rooted:

Trying this now, looking good :)

    (setq company-minimum-prefix-length 1
          company-dabbrev-ignore-case 't
          completion-ignore-case 't)
