### ISSUE TITLE
Adding a function to get the catagory of node aside from tags

### ISSUE THREAD

**Issue by aadi58002** [org-roam/org-roam#2290]
### Brief Abstract
Adding a function to get the catagory of a node
### Long Description
A function similar to org-roam-node-tags which can be used to get the catagory of nodes instead of tag.
### Proposed Implementation (if any)
Using the same concept as org-roam-node-tags except for `#+category: Todo`
### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
what would this function be used for? calling `(org-roam-node-properties (org-roam-node-at-point))` will return an `alist with `CATEGORY` amongst them if it exists.

**Comment by aadi58002** [comment]
I think it will be useful addition and it will make it writing the org-roam filter function easier for someone who want to filter by catagories . I had to use many function in order to get the catagory instead of using the tag function which does a similar thing.
```elisp
(defun my/org-roam-remove-category (node)
  (let ((category (list "daily" "Groups")))
  (not (member (cdr (assoc-string "CATEGORY" (org-roam-node-properties node))) category))))

(defun my/org-roam-find-node-custom()
  (interactive)
  (org-roam-node-find nil nil 'my/org-roam-remove-category))

(map! :leader
       :desc "Roam Nodes" :n "<return>" #'my/org-roam-find-node-custom)
```
