### ISSUE TITLE
Documentation regarding using Emacs builtin Sqlite is outdated

### ISSUE THREAD

**Issue by declantsien** [org-roam/org-roam#2295]
### Description
[Documentations](https://github.com/org-roam/org-roam/blob/main/doc/org-roam.org#how-to-cache) regarding using Emacs builtin Sqlite is outdated, which probably should reflect the changes here [#2146](https://github.com/org-roam/org-roam/issues/2146)?

**Comment by nobiot** [comment]
I suppose you could help Jethro (author) by creating a PR. Just a gentle suggestion.
