### ISSUE TITLE
Feature request: include more information in nodes returned by `org-roam-node-at-point`

### ISSUE THREAD

**Issue by Hugo-Heagren** [org-roam/org-roam#2303]
### Brief Abstract
Include more information than is currently provided by calls to `org-roam-node-at-point` in capture buffers for unsaved nodes.

### Long Description
If called from a capture buffer for a node which is not saved yet, then `org-roam-node-at-point` returns a node object which only contains the `id` and `point` slots. I propose to include more information (e.g. properties, title, refs) if it is available, by examining the current buffer and populating the returned node.

I want this because I'm writing some config which relies heavily on getting information about org-roam-nodes. In particular, it relies on getting the title, refs and tags associated with a capture buffer. I have my templates setup so these things are automatically populated when capturing in the first place, so it is quite likely that my code could be called before the node is saved.

### Proposed Implementation (if any)
A lot of this information is avaible directly in an org mode buffer from different functions anyway, so the lack of data in the database shouldn't be a problem.

A simple implementation could look like this:

```diff
diff --git a/org-roam-node.el b/org-roam-node.el
index 7614e67..06b4ba6 100644
--- a/org-roam-node.el
+++ b/org-roam-node.el
@@ -236,6 +236,12 @@ populated."
               (org-roam-populate
                (org-roam-node-create
                 :id id
+                :refs (split-string (org-entry-get (point) "ROAM_REFS")
+                                    " +" t "@\\|[[:space:]]")
+                :title (org-get-title)
+                :tags (org-get-tags)
+                :properties (org-entry-properties)
+                ;; ... more functions could be added here.
                 :point (point)))))))
       (and assert (user-error "No node at point"))))
 ```

I don't know why more slots are not populated at the moment, but if it has something to do with performance, the above might be a bit naive. A better solution could be to define a custom variable -- an plist associating the names of slots with functions for getting their values. Then we could just calculate all the values in the list and interpolate it into the call.

There is only one other problem 

### Please check the following:

- [x] No similar feature requests

**Comment by nobiot** [comment]
Does this need to be done for an unsaved capture buffer for you?

I think the reason why the function does not return the node with more slots populated is because the node is not saved yet — and so the cache database is not populated with the slots yet. You can cancel the capture process and the database does not have to be cleared. 

To me, this is the correct reflection of the state of the node as before it being cached.

Could your config be done at a later stage after the node cache has been populated? If this is an option, that might be a better solution without impacting other users like me who do not need the additional information.

**Comment by nobiot** [comment]
Just to add, you do not have to rely on the node and cache. It sounds to me that one of the capture hooks might serve you well and you could use just the org functions you list in your diff in a capture hook. Have you explored this avenue?

**Comment by Hugo-Heagren** [comment]
> Does this need to be done for an unsaved capture buffer for you?

yes (sometimes).

To elaborate. I'm writing a [related-files](https://github.com/DamienCassou/related-files) jumper to take me from pdfs of papers I'm reading to a capture buffer on org-roam notes for that paper. It intergrates with org-roam's own refs system (i.e. setting refs properly), and citar. It works even if there doesn't already exist a node of notes on the relevant paper -- it just looks up the bibliographic information and interpolates that into the template, populating the node upon capture. This is where I need to access the refs.

I don't want to have to get into the habit of saving capture buffers as soon as they open (seems like cognitive load for something the computer could be doing for me), and I don't want capture buffers to always be saved immediately (sometimes I change my mind about writing anything, and I cancel the capture).

> think the reason why the function does not return the node with more slots populated is because the node is not saved yet — and so the cache database is not populated with the slots yet. **You can cancel the capture process and the database does not have to be cleared**

Ahh this makes sense to me.

> Could your config be done at a later stage after the node cache has been populated?

As described above, no.

> It sounds to me that one of the capture hooks might serve you well and you could use just the org functions you list in your diff in a capture hook. Have you explored this avenue?

I did have a look at this and it doesn't work for me. The way my config works is that I need to use org-roam node accessor functions to get the information. The problem is that for a newly created capture buffer  `org-roam-node-at-point` creates a new node every time it is called and populates that, so using a hook to set the refs slot on the node returned is pointless, because that isn't the same as the node which will be returned when I later call `org-roam-node-at-point` to get this information.

*However*, I have solved the issue for my own case using advice. I just used a `:filter-output` advice on org-roam-node-at-point to populate the refs slot with the relevant information. Thus:

```elisp
(defun my/org-roam-node-at-point-add-refs-advice (node)
    "Add refs to org-roam node at point if not already present.

If NODE is an org-roam-node and `org-roam-node-refs' returns nil,
get the refs from the in-buffer property ROAM_REFS, and set the
node's slot appropriately (using `setf').

Whether this is done or not, return node.

This is used as advice on `org-roam-node-at-point', so that
related-files can be used correctly in capture buffers which have
not yet been saved to the database."
    (if-let* (((org-roam-node-p node))
	      ((not (org-roam-node-refs node)))
	      (refs-raw (org-entry-get nil "ROAM_REFS"))
	      (sep (org--property-get-separator "ROAM_REFS"))
	      (refs-list (split-string refs-raw sep t "@\\|[[:space:]]")))
	(progn
	  (setf (org-roam-node-refs node) refs-list)
	  node)
      node))
  (advice-add
   #'org-roam-node-at-point
   :filter-return
   #'my/org-roam-node-at-point-add-refs-advice)
```

I don't really like using advice unless I have to (hence this issue, hoping to setup another solution), but it seems like there are good reasons for the way the function works at the moment. I'll close this, and leave my solution here in case anyone else ever comes across this sort of thing again.
