### ISSUE TITLE
org-roam on Windows : org-roam--sqlite-available-p variable does not pop up

### ISSUE THREAD

**Issue by soilc** [org-roam/org-roam#2307]
### Brief Abstract
org-roam on Windows : org-roam--sqlite-available-p variable does not pop up
- Emacs: GNU Emacs 28.1 (build 2, x86_64-w64-mingw32)
 of 2022-04-21
- Framework: N/A
- Org: Org mode version 9.5.2 (release_9.5.2-25-gaf6f12 @ c:/emacs/emacs-28.1/share/emacs/28.1/lisp/org/)
- Org-roam: 2.2.2- sqlite-connector: sqlite

### Long Description
I have GNU Emacs 28.1 (build 2, x86_64-w64-mingw32).
I have followed the instructions in the Org Roam manual (https://www.orgroam.com/manual.html#C-Compiler) to build the database program.

This is my config:
;; org-roam
(use-package org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "~/RoamNotes")
  (org-roam-completion-everywhere t)
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert)
         :map org-mode-map
         ("C-M-i"    . completion-at-point))
  :config
  (org-roam-setup))

I'm also trying to follow this recommendations: "After loading the package, you can check the variable org-roam--sqlite-available-p for a value of t to ensure that everything is set up correctly and ready to run." (https://systemcrafters.cc/build-a-second-brain-in-emacs/getting-started-with-org-roam/) and I have installed org-roam, but org-roam--sqlite-available-p variable does not pop up.
II can create the nodes with org-roam-node-insert. can create the nodes with org-roam-node-insert.

### Proposed Implementation (if any)
Could you clarify the question regarding the org-roam--sqlite-available-p variable?
### Please check the following:

- [ ] There is a similar feature requests here:
https://www.reddit.com/r/emacs/comments/ryrejc/orgcollectkeywords_issue_when_trying_out_org_roam/, but there is not any answer.

**Comment by soilc** [comment]
I can create the nodes with org-roam-node-insert.

**Comment by nobiot** [comment]
`org-roam--sqlite-available-p` was [removed a year ago](https://github.com/org-roam/org-roam/pull/2018#issuecomment-1003496641) as it is not needed. 

What is the issue? If `org-roam-node-inert` is working, it's usually an indication that Org-roam is working for you.

**Comment by soilc** [comment]
Yes, `org-roam-node-insert` is working. Thanks a lot!

**Comment by nobiot** [comment]
Could I suggest that you close this issue then?
