### ISSUE TITLE
Capture templates (file "path/to/template") fails when the path is returned from a function

### ISSUE THREAD

**Issue by jb-stack** [org-roam/org-roam#2310]
#### Steps to Reproduce

Example:

1. Load Emacs
2. Add a template to org-roam-capture-templates using this format:
("t" "test" plain (file "path/to/some/file.org"))
3. Add a new node using the template.
4. Modify the above line to:
("t" "test" plain (file (expand-file-name "path/to/some/file.org")))
5. Add a new node using the template.

#### Backtrace

Debugger entered--Lisp error: (wrong-type-argument stringp (expand-file-name "path/to/some/file.org"))
  org-capture-get-template()
  org-capture(nil nil)
  org-roam-capture-(:node #s(org-roam-node :file nil :file-title nil :file-hash nil :file-atime nil :file-mtime nil :id "58348322-5470-47d2-8815-f49fb03b5400" :level nil :point nil :todo nil :priority nil :scheduled nil :deadline nil :title "delete" :properties nil :olp nil :tags nil :aliases nil :refs nil) :templates nil :props (:finalize find-file :call-location #<marker at 4143 in config.el>))
  org-roam-node-find()
  funcall-interactively(org-roam-node-find)
  command-execute(org-roam-node-find)

#### Expected Results

Both versions should work correctly.

#### Actual Results

It only works when the file path is specified as a string. It doesn't work using an expression which returns a string. Using a variable containing the string also doesn't work.

### Environment

- Emacs: GNU Emacs 28.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2023-01-19
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-bed47b4 @ /home/username/.emacs.doom/.local/straight/build-28.2/org/)
- Org-roam: d95d256
- sqlite-connector: sqlite

**Comment by nobiot** [comment]
I don’t think it is part of the valid syntax for capture.

**Comment by jb-stack** [comment]
I solved it by using setting `org-roam-capture-templates` to a [backquoted](https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html#Backquote) list and then selectively evaluating `(expand-file-name "path/to/some/file.org")` by using `,`. E.g.:

```
(setq org-roam-capture-templates
      `(("d" "default" plain (file ,(expand-file-name "path/to/template.org")) :target
         (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
         :unnarrowed t))))
```

**Comment by nobiot** [comment]
Yes, good one.
