### ISSUE TITLE
org-roam-dailies-capture-templates does not insert template

### ISSUE THREAD

**Issue by Deanamic** [org-roam/org-roam#2312]
Hi, 

I've been looking to use org-roam dailies but I'm having trouble configuring the template.

My current config looks like this:
```
(setq org-roam-dailies-capture-templates
          '(
             ("d" "default" plain "* %?"
              :target (file+head "%<%Y-%m-%d>.org"
                       "#+title: %<%Y-%m-%d>")
              :unnarrowed t)))
```
But whenever I try running `org-roam-dailies-goto-today` a file is created with the appropriate name and header, but the template itself `"* %?` never gets added.

I've also been testing this on the normal org roam template and it seem to work perfectly.

Some info on my system:
- Running Spacemacs
- Emacs 28.1
- org-roam-20221231.2122

**Comment by nobiot** [comment]
I suggest you try using the command `org-roam-dailies-capture-today` instead.

**Comment by Deanamic** [comment]
Sorry wasn't clear in my original wording. I am using the `org-roam-dailies-capture-today` method, but it doesn't insert a template.

I would expect this to create a buffer with `*` but it creates a buffer with only the heading

**Comment by nobiot** [comment]
It does on my end. Perhaps you could try with emacs -q?

**Comment by Deanamic** [comment]
Doesn't `emacs -q` just load with no init.el at all?

**Comment by nobiot** [comment]
Sure, if "clean Spacemacs" changes anything. My suggestion is to even remove Spacemacs from the equation and test the vanilla. You might need to re-install Org-roam, but that ensures there is no interference.

**Comment by Deanamic** [comment]
> I suggest you try using the command org-roam-dailies-capture-today instead.

Quite embarrassing, didn't realize that the method was `capture` and not `goto`. So there was no issue in the end.

Thank you
