### ISSUE TITLE
Can't see backlinks from org-roam-dailies

### ISSUE THREAD

**Issue by filippsidorov** [org-roam/org-roam#2313]
### Description
Hi, I always had backlinks from the org-roam-dailies to basic nodes. But now they are completely disappeared. At the same time I still can see backlinks from node to node. 

#### Steps to Reproduce
1. Go to one of the org-roam-dailies note.
2. Add any header ** Some heading
3. Insert link with org-roam-node-insert
4. Save buffer & do db sync
5. Visit node from step 3
6. Open buffer and its empty! :(

#### Expected Results

I expect that if I link node in daily note. I will see backlinks in this nodes buffer.

#### Actual Results

Any link from dailies is not visible in backlinks of regular nodes.

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559))
 of 2022-09-12
- Framework: 
- Org: Org mode version 9.5.5 (release_9.5.5 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)
- Org-roam: 2.2.1- sqlite-connector: sqlite

<img width="654" alt="insert-node" src="https://user-images.githubusercontent.com/13422529/215793466-3086bf6a-8e76-40b2-a4a9-e96e60ee63cf.png">

<img width="953" alt="empty-buffer" src="https://user-images.githubusercontent.com/13422529/215793455-8e6f42b9-c6c8-4b4e-8f5e-117bdce9881a.png">

**Comment by nobiot** [comment]
Works with vanilla on my end. Perhaps your dailies is in a directory that is excluded from Org-roam or something?

![image](https://user-images.githubusercontent.com/12507865/215875959-22ae3f28-37e1-4cb8-9980-0743d5a4f38b.png)

**Comment by filippsidorov** [comment]
It worked for me too all the time. I don't what changed now, so that it's broken. Here's my current config. Directories of dailies and org roam are symlinks. I've just tried all steps on my another Linux machine. And I see no backlinks too. 

```
(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory (file-truename "~/Zettelkasten"))
  (org-roam-dailies-directory (file-truename "~/Dailies"))
  :bind (("C-c n l" . org-roam-buffer-toggle)
	 ("C-c n f" . org-roam-node-find)
	 ("C-c n i" . org-roam-node-insert)
	 ("C-c n r" . org-roam-node-random)
	 ("C-c n d c" . org-roam-dailies-capture-today)
	 ("C-c n d t" . org-roam-dailies-goto-today)
	 ("C-c n d d" . org-roam-dailies-goto-date)
	 ("C-c n d p" . org-roam-dailies-goto-previous-note)
	 ("C-c n d n" . org-roam-dailies-goto-next-note) 
	 :map org-mode-map
	 ("C-M-i" . completion-at-point))
  :config
  (org-roam-db-autosync-mode)
  )
```

**Comment by nobiot** [comment]
Sorry no idea; I can't reproduce the issue. I'd try using normal directories without symlinks just to remove them from the possibility.

**Comment by filippsidorov** [comment]
Additionally all config, maybe I'm missing something. Anyway thank you!
```
;; Basics
(tool-bar-mode -1)
(set-frame-font "Hack 18" nil t)
(setq-default fill-column 79)

(load-theme 'zenburn t)

(setq find-file-visit-truename t)

(add-hook 'text-mode-hook '(lambda ()
                             (auto-fill-mode 1)))

(add-hook 'org-mode-hook '(lambda ()
                             (auto-fill-mode 1)))

;; Spacing in minibuffer
(define-key minibuffer-local-completion-map "\M- "
  (lambda() (interactive) (insert " ")))


;; Bindings
(global-set-key "\C-cd" 'kill-whole-line)     
(global-set-key (kbd "C-c a") #'org-agenda)


;; Melpha-Stable
(require 'package)
(add-to-list 'package-archives
             '("melpa-stable" . "http://stable.melpa.org/packages/") t)


;; yasnippets
(setq yas-snippet-dirs
      '("~/emacs.d/snippets"))

(yas-global-mode 1)


;; Org-roam

(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory (file-truename "~/Zettelkasten"))
  (org-roam-dailies-directory (file-truename "~/Dailies"))
  :bind (("C-c n l" . org-roam-buffer-toggle)
	 ("C-c n f" . org-roam-node-find)
	 ("C-c n i" . org-roam-node-insert)
	 ("C-c n r" . org-roam-node-random)
	 ("C-c n d c" . org-roam-dailies-capture-today)
	 ("C-c n d t" . org-roam-dailies-goto-today)
	 ("C-c n d d" . org-roam-dailies-goto-date)
	 ("C-c n d p" . org-roam-dailies-goto-previous-note)
	 ("C-c n d n" . org-roam-dailies-goto-next-note) 
	 :map org-mode-map
	 ("C-M-i" . completion-at-point))
  :config
  (org-roam-db-autosync-mode)
  )


(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-agenda-files '("~/Org/входящие.org" "~/Dailies"))
 '(package-selected-packages
   '(org-roam zenburn-theme yasnippet use-package markdown-mode)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Comment by nobiot** [comment]
Whats the truename of Dailies directory? Does it contain “data” or something? It might be exlcuded

**Comment by filippsidorov** [comment]
I've cleared db and resynced it and I opened SQL Lite and I don't see any link any node from the Dailies directory!

**Comment by nobiot** [comment]
I would try setting the dailies dir to the same as other notes and see if something wrong with dir, or dailies capture itself.

I would also try with emacs -q to see if any configuration is interfering.

As I cannot reproduce the issue, it is happening only in your PC at the moment.

**Comment by nobiot** [comment]
I have also seen a report running `org-roam-update-org-id-locations` might fix some issues similar to yours. Nothing conclusive; I'm stabbing in the dark. Sorry if none of my suggestions works.

**Comment by filippsidorov** [comment]
@nobiot I moved Dailies to the same directory as other notes and it perfectly works now. Thanks for your help. I still don't know what caused such behaviour when Dailies are in separate folder, but now the problem solved. It works and fine.

**Comment by nobiot** [comment]
The document string of `org-roam-dailies-directory` reads as follows.
They need to be a subdirectory of `org-roam-directory` by the sound of it.

> Path to daily-notes.
> This path is relative to ‘org-roam-directory’.

**Comment by nobiot** [comment]
I don't use dailies so I didn't notice your configuration strange. 
```
  (org-roam-directory (file-truename "~/Zettelkasten"))
  (org-roam-dailies-directory (file-truename "~/Dailies"))
```

**Comment by filippsidorov** [comment]
@nobiot yes, it was the problem. Now it works perfectly. Really appreciate. 

Dailies should be inside org-roam-directory. And it's clearly written in documentation. Don't know why I missed it.
