### ISSUE TITLE
It's there some 'filter-fn' example?

### ISSUE THREAD

**Issue by arstum** [org-roam/org-roam#2315]
I want to filter some nodes with the tag, and I can't find any example for the function 'filter-fn'.

**Comment by nobiot** [comment]
The Discourse forum has some examples, [like this](https://org-roam.discourse.group/t/find-node-based-on-property-value/2719/5?u=nobiot). It is to filter by a property, but filtering by a tag will be similar.

Is this sufficient for you to move forward?

**Comment by arstum** [comment]
Still don't get it, it's not enough.

**Comment by nobiot** [comment]
Can you elaborate on what part is hard? What have you tried so far? Or do you not know hoe to code Elisp? 

To be frank, you are asking for help but you are not giving enough information that helps those who are willing to help, so it is difficult to communicate.

**Comment by nobiot** [comment]
This works on my end for a single tag. 

```
(defun my/org-roam-node-find-tag-filter ()
  "Select a signel tag from list and filter `org-roam-node' by it."
  (interactive)
  (let ((tag (car (completing-read-multiple "Tag: "
                                            (org-roam-tag-completions)))))
    (org-roam-node-find nil nil
                        (lambda (node)
                          (member tag
                                  (org-roam-node-tags node))))))
```

It's essentially the same example as the `insert` example in the linked Discourse post [above](https://github.com/org-roam/org-roam/issues/2315#issuecomment-1415270183), and follows the doc string where how `FILTER-FN` is explained as below:
> FILTER-FN is a function to filter out nodes: it takes an ‘org-roam-node’,
> and when nil is returned the node will be filtered out.

**Comment by Delapouite** [comment]
Hello arstum.
As a couple of valid answers have been given in this thread and on discourse, I'll close this issue. Don't hesitate to re-open it if needed.
