### ISSUE TITLE
Upstreaming?

### ISSUE THREAD

**Issue by jgarte** [org-roam/org-roam#2323]
Hi,

Are there any plans to upstream `org-roam` now that latest Emacs includes [sqlite](https://lists.gnu.org/archive/html/emacs-devel/2021-12/msg00463.html) support?

**Comment by nailuoGG** [comment]
Hi

We can use the following configuration to make org-roam use the built-in SQLite of Emacs 
```
  (org-roam-database-connector 'sqlite-builtin)
```

**Comment by xeruf** [comment]
I don't understand the question, and the issue title is also quite nondescriptive.
Might be related to https://github.com/org-roam/org-roam/issues/2374

**Comment by jgarte** [comment]
> I don't understand the question

Upstreaming means to integrate org-roam into Emacs itself the same way that eglot was upstreamed, for example. 

I now realize that this would likely not happen with org-roam. Closing.
