### ISSUE TITLE
Dedupe items in unlinked references section

### ISSUE THREAD

**Issue by okomestudio** [org-roam/org-roam#2362]
### Brief Abstract

Deduping unlinked references items listed in the Org Roam buffer will improve browsability.

### Long Description

The unlinked references section of Org Roam buffer lists matched line multiple times (this originates from ripgrep behavior). While the Magit-like support for being able to jump to the matched position is nice, repeatedly showing the same line bloats the buffer and making sense of search results difficult.  

For example, in the following result, lines 333 and 337 contain the word "china" matched multiple times, and the rather long paragraph gets repeated for apparently no benefit.

![Duplicate lines](https://github.com/org-roam/org-roam/assets/2257159/f7ea2946-0196-43c0-bb10-1f1ccc90b61a)

(Note that truncation is avoided by the use of `visual-line-mode` and `adaptive-wrap-prefix-mode` for indentation of wrapped line. This is purely my personal settings.)

### Proposed Implementation

A simple code modification to replace repetition with ellipses (`...` here) can make the Org Roam buffer cleaner to browse without loss of any information:  

![Deduped with ellipsis](https://github.com/org-roam/org-roam/assets/2257159/5d77a521-527b-44b1-a57b-7a32d64e7ecc)

while the ability for us to click on the entry line to jump to the match via Magit is retained.

I will submit a PR implementing the minimal change.

**Comment by xbc5** [comment]
Try innovating a solution yourself then.

**Comment by okomestudio** [comment]
To avoid clutter, I will close this in favor of https://github.com/org-roam/org-roam/issues/2416 which offers a more general solution.

**Comment by hpfr** [comment]
Seems like this is a result of `--only-matching` and `--vimgrep`. We might be able to fix this just by tweaking ripgrep options
