### ISSUE TITLE
Notes with a link cannot be found by `org-roam-node-find`

### ISSUE THREAD

**Issue by Porcupine96** [org-roam/org-roam#2369]
### Description

Notes that have link to an external website are not indexed correctly (the notes cannot be found using `org-roam-node-find`). 

#### Steps to Reproduce

1. Open Emacs
2. Create a new org-roam note "Bug test"
3. Call `org-roam-node-find`

![image](https://github.com/org-roam/org-roam/assets/17063095/9b632d42-bd19-46ba-a58a-70cbae05c18e)

The newly created node is found as expected. ✅

4. Add an external link (any link) in the note's body. 
5. Call `org-roam-db-sync`

![image](https://github.com/org-roam/org-roam/assets/17063095/c9bcd089-ec23-42e3-a147-e9f57028e209)

6. Call `org-roam-node-find` 

The node can no longer be found ❌

#### Expected Results

The file should be indexed correctly no matter if it has a link or not. 

#### Actual Results

Every note that I have which has a link cannot be found by `org-roam-node-find`.

### Environment

- Emacs: GNU Emacs 28.2.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-01-07
- Framework: N/A
- Org: Org mode version 9.7-pre (release_9.6.7-572-g39de4a @ /home/porcupine/.emacs.default/straight/build/org/)
- Org-roam: v2.2.2-42-g5c06471
- sqlite-connector: sqlite

**Comment by LukasCBossert** [comment]
I noticed the same behavior of org/org-roam. All nodes with links are not recognized as nodes anymore. As soon as I try to modify any content of the node I get this error 

```
org-roam-db-map-links: Wrong type argument: integer-or-marker-p, nil
```

** Environment **
- Emacs: GNU Emacs 29.0.90 (build 1, aarch64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3.1 (a) (Build 22E772610a)) of 2023-05-03
- org-roam: 5c06471
- org: Org mode version 9.7 (9.7-??-d6f3aed7b @ /Users/lukascbossert/.config/emacs/.local/straight/build-29.0.90/org/)
- Doom core     v3.0.0-pre       HEAD -> master 06c891e1 2023-07-24 23:25:34 +0200
- Doom modules  v23.03.0-pre     HEAD -> master 06c891e1 2023-07-24 23:25:34 +0200

**Comment by JakDar** [comment]
Probably a duplicate of https://github.com/org-roam/org-roam/issues/2361
[Pinning org](https://github.com/org-roam/org-roam/issues/2361#issuecomment-1650957932) worked for me ;)

**Comment by LukasCBossert** [comment]
yes, that solved this issue, too!

**Comment by Porcupine96** [comment]
Thanks! I do confirm that pinning `org` to `9.6.7` fixes the issue :)
