### ISSUE TITLE
org-export-as-html: Important markdown with two dashes result in one "&#x2013;"

### ISSUE THREAD

**Issue by buhtz** [org-roam/org-roam#2372]
Original org code is a heading with a important/bold part in it.

    *  *--foo*

Results via `org-export-as-html` in

    <h2 id="orgf2ca317"><span class="section-number-2">2.</span> <b>&#x2013;foo</b></h2>

OK, `&#x2013;` is an HTML entity for the dash. But there are two dashes not one.

Rendered in orgroam-mode in a terminal looks OK
![image](https://github.com/org-roam/org-roam/assets/11861496/d7f27091-ef19-4942-a1ef-9eba970c90d5)

My expected HTML results would be

        <h2 id="orgf2ca317"><span class="section-number-2">2.</span> <b>&#x2013;&#x2013;foo</b></h2>

or

        <h2 id="orgf2ca317"><span class="section-number-2">2.</span> <b>--foo</b></h2>

Please delegate this report to "org" if it is related there. Thanks.

Using self-build Emacs 29 on Debian 11 ARM via SSH shell.
org: `version 9.6.7 ( @ /home/user/.emacs.d/elpa/org-9.6.7/)`
org-roam: `2.2` (via `org-roam-version`) or `20230307.1721` via `list-packages`

## Edit
I realized that it is not related to the heading or markdown. It is just a simple `--` is translated into a one-dash entity `&#x2013;`. Feels like "auto-formatting" in MS Word.

**Comment by jethrokuan** [comment]
`org-mode` treats the double-dashes as a special string. You can add `#+OPTIONS: -:nil` to the top of the org-mode file if you don't want conversion of special strings during export.

Exporting org-mode files to HTML is entirely an Org-mode feature and has nothing to do with Org-roam, so if you'd like you can refile this with Org.
