### ISSUE TITLE
Trace org-roam sync hanging and blocking emacs

### ISSUE THREAD

**Issue by oatmealm** [org-roam/org-roam#2387]
I'm running into a problem with org-roam not finishing synching. Most of the time it eats up all the memory, blocks emacs or crash.  Is there away to see where it hangs or why?

**Comment by meedstrom** [comment]
Happens to me as well.  Delete org-roam.db and then sync will work -- once!

So I have to delete it every time I sync.

**Comment by meedstrom** [comment]
I've found that many times it doesn't *really* get stuck, it's just very, very, very slow, for reasons unrelated to the exact file it's scanning.

So if I wait long enough, it resumes.

But what could be going wrong? SQL busy?

**Comment by eamonnsullivan** [comment]
It's happening to me as well. I have two laptops, with org directories kept in sync via Syncthing. One is running Mac OS and the other Ubuntu. Same versions of Emacs, same init files, same org files. On Ubuntu, I can't open the agenda -- the CPU to to 100% (on one core). On the Mac, no problems at all.

org-roam-version : v2.2.2-44-g8667e44
emacs version on Ubuntu: GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2024-03-26, modified by Debian. (I was using the Snap version without issues, but switched to a PPA deb version to see if it would help. It didn't.)
emacs version on Mac OS: GNU Emacs 29.3 (build 2, aarch64-apple-darwin23.4.0, NS appkit-2487.50 Version 14.4 (Build 23E214)) of 2024-03-28

Is there anything else I can do to debug this? I'm a long time org-mode user, but recently started trying to use org-roam when the issues started. It's making it unusable for me, I'm afraid.

**Comment by eamonnsullivan** [comment]
Actually, I just fixed it for me. I noticed that this is recommended for Emacs 29: 
```
(setq org-roam-database-connector 'sqlite-builtin)
```
And bingo! That worked.

**Comment by lkcp** [comment]
> Actually, I just fixed it for me. I noticed that this is recommended for Emacs 29:
> 
> ```
> (setq org-roam-database-connector 'sqlite-builtin)
> ```
> 
> And bingo! That worked.

I had the same problem in my macbook m1pro (with the same emacs version), and this config works for me.

**Comment by Delapouite** [comment]
Hi.
As the fix provided by eamonnsullivan appears to resolve the performance problem, I'm going to close this issue. Feel free to reopen if needed.
Thanks
