### ISSUE TITLE
Selecting deleted buffer.

### ISSUE THREAD

**Issue by Abbie-Boo** [org-roam/org-roam#2438]
### Description
I am following this [Installation](https://www.orgroam.com/manual.html#Installation) guid, and the next step after the installation is to use the **`org-roam-node-find`**, I followed everything correctly, but none of the org commands mentioned in the guid (`org-roam-node-insert, org-roam-node-find, org-roam-capture`) seems to work, they all show the same message **"Selecting deleted buffer"**.   I saw a reddit post with this same issue opened 2years ago. They mentioned upgrading the package and re-compiling **emacsql-sqlite.exe** manually. I also  tried using this [nobiot/emacsql-sqlite.exe](https://github.com/nobiot/emacsql-sqlite.exe) nothing seems to work for me. 

#### Files
```
.emacs.d/elpa/emacsql-sqlite-3.1.1/sqlite
├── Makefile
├── emacsql-sqlite.exe
├── emacsql.c
├── sqlite3.c
└── sqlite3.h
0 directories, 5 files
```
`".emacs.d\org-roam.db"`

sqlite path. This is also added into the environmental variable and accessible form terminal.
`"C:\red\sqlite3\sqlite3.exe"`

#### Actual Results
The echo area keep showing me this "Selecting deleted buffer" message.

### Environment
- Emacs: GNU Emacs 29.1 (build 2, x86_64-w64-mingw32)
 of 2023-07-31
- Framework: N/A
- Org: Org mode version 9.6.6 (release_9.6.6 @ c:/Program Files/Emacs/emacs-29.1/share/emacs/29.1/lisp/org/)
- Org-roam: 2.2.1- sqlite-connector: sqlite

![Screenshot 2024-06-14 203134](https://github.com/org-roam/org-roam/assets/146865091/c10d06f6-985e-49e2-ac63-714ff1bba477)

**Comment by nobiot** [comment]
I suggest to use [emascql-builtin](https://melpa.org/#/emacsql-sqlite-builtin). You don't need the executable. sqlite comes with the Emacs installation.

29.1 should work but I suggest you use 29.3 -- some security issue patched with it.
