### ISSUE TITLE
Add a parameter to ignore specific subfolders in `org-roam-directory` 

### ISSUE THREAD

**Issue by adamoudad** [org-roam/org-roam#2442]
### Brief Abstract
Due to my use of Syncthing with versioning to synchronize my org-roam folder between different devices, org-roam gets confused between saved versions of the same org file containing the same headings with the same IDs and often points to the wrong file.

I would like to have the ability to ignore specific subfolder in my `org-roam-directory`, especially `.stversions` to avoid such conflict.

### Long Description
- I use Syncthing with versioning to synchronize my org-roam folder between my different devices (laptop, smartphone, tablet).
- Due to syncthing's versioning, a `.stversions` is created inside my `org-roam-directory` (which is `~/Notes/`).
- Due to this, org-roam, which recursively searches for headings with IDs inside `org-roam-directory` often makes a mistake by pointing an ID to an old version of the org file inside `~/Notes/.stversions/`, instead of the most up-to-date one inside `~/Notes/`.
- I would like to have the ability to ignore the `.stversions` folder to tell org-roam not to search for org files inside it, to avoid such conflicts in ID resolution. 

### Proposed Implementation (if any)
One solution, not modifying org-roam, would be to change the location of the `.stversions` to somewhere else on my PC.

But I think this feature could be nice in general, to get more fine-grained control over which org file is handled by org-roam and which one is not.

I though of an implementation which would be to provide a user parameter which is a regular expression pattern to ignore some subfolders or org files. Otherwise, a list of paths to ignore, similar to a `.gitignore` file.

I looked at the source code and am guessing I would need to modify the following `org-roam-update-id-locations` function defined inside `org-roam-id.el`, but would be happy for guidance on this, as I am not sure yet how to proceed. I have some knowledge in elisp, but am not very confident in my ability to make this work. 
```
  (interactive)
  (cl-loop for dir in (cons org-roam-directory directories)
           for org-roam-directory = dir
           nconc (org-roam-list-files) into files
           finally (org-id-update-id-locations files org-roam-verbose)))
```
### Please check the following:

- [X] No similar feature requests. I could not find a similar issue, so I am posting here.

**Comment by nobiot** [comment]
Have you tried this?

```
(defcustom org-roam-file-exclude-regexp (list org-attach-id-dir)
  "Files matching this regular expression are excluded from the Org-roam."
```

**Comment by adamoudad** [comment]
I did not know about that variable, thanks!

I tried "*stversions*" but it does not work, so maybe the regexp is only applied to the filename, not the full path.

Syncthing also appends some numbers for the modification datetime like "[filename]-20240602-010508.org".

So I tried `"*[0-9]+-[0-9]+\\.org"` which is still not working.

Sorry to ask, but could I get help on the regexp?

Also, I am running `org-roam-update-id-locations`, then `org-roam-db-sync` every time to make sure I work on the updated dataabase.

**Comment by adamoudad** [comment]
Sorry for taking time to come back, and thanks a lot for your thorough tutorial, @nobiot !

With `(setq org-roam-file-exclude-regexp "\\.stversion")` my issue is resolved.

This variable is quite handy, and I am happy it also lets you define a list of regexp.

On a side note,

The help of the variable `org-roam-file-exclude-regexp` says it contains "a regular expression", so I suggest wouldn't it be better to specify that the variable can either contain one regexp or a list of regexp?

Otherwise, should I assume that when a variable's help says it holds a regexp always means that it can hold a list of regexp?
