### ISSUE TITLE
Support for nested nodes

### ISSUE THREAD

**Issue by Dietr1ch** [org-roam/org-roam#2467]
### Brief Abstract

I often end up having nested org-roam nodes, which work fine, but result in ambiguous node names when searching for them.

### Long Description

A document like this,

```org
:PROPERTIES:
:ID:       <UUIDv4 for org-roam>
:ROAM_REFS: https://www.orgroam.com/
:END:
#+title: org-roam


* Issues
:PROPERTIES:
:ID: <UUIDv4 for org-roam's Issues>
:ROAM_REFS: https://github.com/org-roam/org-roam/issues
:END:
```

Defines 2 nodes,
  1. "org-roam"
  2. "Issues". This name is problematic as it lacks context.
  
It'd be better to have the second node called something around "org-roam| Issues" so that when looking for it there's enough context and no clashes with heading names in similar documents.

### Proposed Implementation (if any)

I don't see a problem with nesting and altering the names nodes get in the DB, but I'm not familiar with the codebase and it might seem hacky.

Alternatively having a property in the drawer that overrides the node name would work, but it'd be burdensome to use and maintain up to date with the heading names in the tree.

### Please check the following:

- [X] No similar feature requests

**Comment by nobiot** [comment]
I think it’s already available. See this: https://github.com/org-roam/org-roam/wiki/User-contributed-Tricks#showing-node-hierarchy

**Comment by Dietr1ch** [comment]
Right, it's exactly what I wanted, my bad.

**Comment by nobiot** [comment]
No need to say “my bad”; there is nothing wrong with the fact that you asked the question. I suggest it would be good if you thanked the other person instead ;)
