### ISSUE TITLE
"(wrong-type-argument arrayp nil)" when using "org-roam-insert"

### ISSUE THREAD

**Issue by mathewkelly** [org-roam/org-roam#262]
### Description

I get this `(wrong-type-argument arrayp nil)` error when trying to use `org-roam-insert`. This is the full error readout as far as I can tell:

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  file-truename(nil)
  org-roam-insert(nil)
  funcall-interactively(org-roam-insert nil)
  call-interactively(org-roam-insert record nil)
  command-execute(org-roam-insert record)
  execute-extended-command(nil "org-roam-insert" "org-roam-insert")
  funcall-interactively(execute-extended-command nil "org-roam-insert" "org-roam-insert")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I noticed that it was similar to [Issue 93](https://github.com/jethrokuan/org-roam/issues/93), but I think the difference is that I'm not using doom-emacs.

When I try to use `org-roam-find-file` as suggested in that issue, I get a different error:

```org-capture-select-template: Symbol’s function definition is void: org-mks```

Here's my init file:

```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes (quote (monokai))))
(custom-set-faces
 )

;; Org mode settings from this tutorial:
;; https://orgmode.org/worg/org-tutorials/orgtutorial_dto.html
(require 'org)
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\C-ca" 'org-agenda)
(setq org-log-done t)

;; Get org mode to log a timestamp when closing TODO items
(setq org-log-done 'time)

;; Word wrap at 110 lines
;;(setq-default auto-fill-function 'do-auto-fill)
;;(setq-default fill-column 110)

;; Automatically wrap I-search (so that it doesn't only search below the cursor)
(define-key isearch-mode-map [remap isearch-delete-char] 'isearch-del-char)

(defadvice isearch-search (after isearch-no-fail activate)
  (unless isearch-success
    (ad-disable-advice 'isearch-search 'after 'isearch-no-fail)
    (ad-activate 'isearch-search)
    (isearch-repeat (if isearch-forward 'forward))
    (ad-enable-advice 'isearch-search 'after 'isearch-no-fail)
    (ad-activate 'isearch-search)))

;; Make I-search non-case-sensitive by default
(setq search-upper-case nil)
(setq isearch-case-fold-search 'yes)

;; Set org mode to show content in subtrees by default on startup
(setq-default org-startup-folded 'content)

;; Preserve indentation when exportin from orgmode to HTML
(setq org-src-preserve-indentation nil 
      org-edit-src-content-indentation 0)

;; Install/load the Straight package manager
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; Install/load use-package
;;(straight-use-package 'el-patch)
;; accidentally installed this ^, need to uninstall or remove later?
(straight-use-package 'use-package)

;; Install/load EmacSQL SQLite for use by org-roam
(straight-use-package 'emacsql-sqlite)


;; Install/load org-roam
(use-package org-roam
      :hook 
      (after-init . org-roam-mode)
      :straight (:host github :repo "jethrokuan/org-roam" :branch "develop")
      :custom
      (org-roam-directory "/path/to/org-files/")
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-show-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))))

;; Set default folder for org-roam
(setq org-roam-directory "C:\\Users\\mkelly\\OneDrive - MJFF\\Documents\\org\\roam")

;; Prefix org-roam links with "R:"
(setq org-roam-link-title-format "R:%s")

;; Set python path
(setq python-shell-interpreter "C:\\Users\\mkelly\\AppData\\Local\\Programs\\Python\\Python38-32\\python.exe")
```
A few other things I've tried:

1. Set python path using `(setq python-shell-interpreter "C:\\Users\\mkelly\\AppData\\Local\\Programs\\Python\\Python38-32\\python.exe")` in my init file
2. Installed the C compiler and "Basic GNU" package from [MinGW](http://www.mingw.org/)
3. Deleted the `elpa` folder in my `.emacs.d` folder, hoping it would rebuild that folder with newly-downloaded packages (Emacs never rebuilt the folder)

Other org-roam commands seem to work, like `org-roam-build-cache` (though this shows `0` for everything since there are no files in the directory). The EmacSQL SQLite DB seems to be running fine in the background too.

If there are other logs or config I can provide, please let me know.

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam-insert`

### Versions
- Emacs: 26.3
- Org-roam commit: I don't know how to check this, but I'm using Straight like this in my init file: `:straight (:host github :repo "jethrokuan/org-roam" :branch "develop")`

**Comment by jethrokuan** [comment]
It looks like you're using the org-mode shipped with Emacs, which is too old. Can you upgrade it?

```
(straight-use-package 'org-plus-contrib)
```

right after bootstrapping straight, and move the org config below.

**Comment by mathewkelly** [comment]
I'm still getting the same errors for `org-roam-insert` and `org-roam-find-file`.

The addition to my init for `org-plus-contrib`:

![image](https://user-images.githubusercontent.com/17037208/76238851-d91b6b00-6206-11ea-8449-935ddaebd29c.png)

The result of `M-x org-version`:

![image](https://user-images.githubusercontent.com/17037208/76238763-bb4e0600-6206-11ea-95da-ffcf9a89072b.png)

**Comment by jethrokuan** [comment]
Just pushed a more friendly error message for `org-roam-insert`. It's only meant to be called from Org-roam files.

The error you see from `org-roam-find-file` has something to with your Org versioning and setup. Did you move also move the `(require 'org)` stuff down below the `org-plus-contrib` line?

**Comment by jethrokuan** [comment]
Closing this for now, let me know if you face issues again.
