### ISSUE TITLE
Graph is not created when there's a title with double quotes

### ISSUE THREAD

**Issue by brunoarine** [org-roam/org-roam#313]
### Description

If one of your notes' title has double quotes in it, `org-roam-show-graph` can't generate the file /tmp/graph.svg. I suggest a policy regarding illegal characters in the title, since this is most likely a problem with graphviz rather than Emacs.

#### Steps to Reproduce

Example:

1. Load Emacs
2. Run `org-roam-find-file`
3. Create a new note using double quotes, e.g. `David Deutsch's "Fun Criterion"`
4. Run `org-roam-show-graph`
-->

#### Expected Results
Your prefered program should show the content of /tmp/graph.svg.

#### Actual Results
The program returns an error that the filename /tmp/graph.svg doesn't exist.

In my case, the file graph.dot was created in /tmp/, and when I tried to convert it manually via `dot -Tps graph.dot -o graph.svg`, the following error appeared:

> Error: graph.dot: syntax error in line 117 near 'Criterion'

The line containing the error was the one with the filename using double quotes:

>   "David Deutsch's "Fun Criterion"" [label="David Deutsch's "Fun Criterion"", shape=ellipse, URL="roam:///home/soldeace/Sync/textos/zettelkasten/20200316181209_david_deutsch_s_fun_criterion.org", tooltip="David Deutsch's "Fun Criterion""];

**Comment by jethrokuan** [comment]
This should've been fixed a while back, see https://github.com/jethrokuan/org-roam/issues/205.

The label could be better though, so I'm fixing that.

**Comment by jethrokuan** [comment]
I tried creating a file with that title and the node appears in the graph on latest master.
