### ISSUE TITLE
[Wishlist] Enable embedding blocks

### ISSUE THREAD

**Issue by alex-rozenshteyn-leapyear** [org-roam/org-roam#317]
### Brief Abstract

Roam allows embedding of blocks via `{{embed: ((blockref))}}` syntax. Org-roam should too.

### Long Description

Recently, I tried to summarize an article. I found that one of the sections was better suited to its own note, but I wanted the contents to appear while I'm reading the summary. In roam I could accomplish this with the embed syntax mentioned above.

### Proposed Implementation (if any)

The best thing I've come up with is to use org's include syntax:

```
#+INCLUDE: sub_topic.org::*Description :only-contents t
```
This means I can use `ox-org` to view it in another buffer.

### Please check the following:
- [x] No similar feature requests

### Note

I _think_ that roam will also allow you to edit the block right from the embedding file. I think that functionality is less crucial and do not include it as part of this feature request.

**Comment by jethrokuan** [comment]
what you're asking for is "transclusions". I just played around with https://github.com/progfolio/emacs-transclusion a little, might need to polish it up a little before including as part of org-roam.

![image](https://user-images.githubusercontent.com/1667473/76859246-e3d3a100-6893-11ea-93f8-cae78c8f55eb.png)

**Comment by progfolio** [comment]
Just to be clear, that's a fork of https://github.com/justintaft/emacs-transclusion. I'm not sure if @justintaft has any interest in/time for working on that package any more or not. In any case, the package is still in its infancy. 

Another option is:
https://github.com/whacked/transclusion-minor-mode by @whacked 

This package is more mature. 
I can't speak to its quality, as I have not used it.

In general, I think solid transclusion for Org/Emacs would be a feature that many packages, including org-roam, would benefit from.

**Comment by dit7ya** [comment]
This list looks like a comprehensive one.

https://github.com/alphapapa/transclusion-in-emacs

**Comment by bdarcus** [comment]
As I'm thinking about this again, just wanted to add some random, not fully developed,  thoughts here.

It occurs to me transclusion support could significantly add to the power of OR. Or maybe not.

If added, that power would need to be marshaled through smart UX design, else the UX could take a step backward.

Roam itself has a core subfile content concept of "blocks." In org language, these are simply headlines or headings.

One can transclude those blocks within another files through a "block reference" which works the same as file references from a UI perspective, but uses a different syntax.

Not sure how this would work with the more complex content model of org though. Could get really messy.

Also, I would say transclusion probably isn't necessary for files in OR, given the ability is to easily spawn new buffers to access that content.

In sum, transclusion might be cool, but could be tricky.

**Comment by alexrs** [comment]
I'm here only to say that I'd love to have this feature. I think it's the most important feature in RoamResearch, and Org's `include` syntax isn't as powerful.

**Comment by wuqui** [comment]
I also think transclusion would be extremely powerful. One of the main advantages of org-roam is that you store information in small (atomic) packages and that you can then combine these small pieces to form different coherent wholes. Ideally one should not copy information from these packages, which creates redundancy and is less than ideal for a number of reasons. You should just combine the packages as they are via something like transclusion, so that the information gets updated everywhere I use it. This is basically also why links are so powerful, but transclusion would in turn make linking much, much more powerful. Without transclusion combining smaller pieces of information to form coherent larger-scale notes and texts is so impractical that it encourages bad practice regarding where and how one stores information.

**Comment by bdarcus** [comment]
I'll just reiterate in more compact form something more implicit in my tentative post above.

org + org-roam ≠ roam

Just because it's in roam does not mean it should be in org-roam. 

And even if the devs ultimately do add it, it may well involve a different approach to roam proper, which will require a lot of thought and testing on UX.

**Comment by zaeph** [comment]
I'd like to give this one a shot in the future.  I have a decent amount of experience with indirect buffers and narrowing, and I think there might be a way to do this without too much hassle.  I'd rather not give an ETA on this for now.

**Comment by yubrshen** [comment]
Any progress on supporting "block reference" and/or "block embed"? To me, this the most innovative invention of Roam. It's a game change to be freely transclude in org-mode. This may lead a lots of interesting applications.

**Comment by affan-salman** [comment]
+1 for both @yubrshen's comment and this feature request.

**Comment by visika** [comment]
There are interesting developments in this direction
https://old.reddit.com/r/emacs/comments/jm1nv6/orgtransclusion_alpha_v004_demo_4/

**Comment by TimQuelch** [comment]
> There are interesting developments in this direction
> https://old.reddit.com/r/emacs/comments/jm1nv6/orgtransclusion_alpha_v004_demo_4/

I'll also link the discourse thread where @nobiot has been keeping us updated about the status of that project 

https://org-roam.discourse.group/t/prototype-transclusion-block-reference-with-emacs-org-mode/830

**Comment by nobiot** [comment]
@TimQuelch , thanks for the mention (and @visika for the reference). 
I was not aware of this thread, and my humble attempt at Org-transclusion is independent of Org-roam. As an active user of Org-roam, though, I would love some level of interoperability where it makes sense and technically possible. 

I would appreciate your feedback (as many of you in this thread have; thank you) in the Discourse forum TimQuelch cites, Org-roam slack channel, and/or my GitHub repo.

**Comment by jethrokuan** [comment]
Closing as it's best solved outside of Org-roam (e.g. using @nobiot 's org-transclusion).
