### ISSUE TITLE
Detecting similarities among notes

### ISSUE THREAD

**Issue by khinsen** [org-roam/org-roam#326]
### Brief Abstract

Use [Word2vec](https://en.wikipedia.org/wiki/Word2vec) for deriving feature vectors for each notes, store them in the SQLite database, and use them to display notes similar to the current one in the `org-roam` buffer.

### Long Description

The motivation for such a feature is to discover relations between notes that go beyond what the note taker thought of when creating links. I expect this to be particularly useful when
 1. Working collectively on a shared note database.
 2. Pasting text from outside sources (Web pages etc.) into notes.

I used to work with [DEVONthink](https://www.devontechnologies.com/apps/devonthink), a note and article database for macOS, which has such a feature, and I found it very useful. I don't use DEVONthink any more because I am slowly moving from macOS to Linux, but I'd love to get that feature back.

In a second step, the Word2Vec feature database could be extended to other files, such as a collection of PDF files.

### Proposed Implementation (if any)

None, this is just an idea for now. Its implementation would probably involve more code than the entire `org-roam` code base today. For now, I am mainly interested in feedback, and in finding people willing to collaborate on such a project.

### Please check the following:
- [X] No similar feature requests

**Comment by jethrokuan** [comment]
Something like [Latent Dirichlet Allocation](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation) might be more suitable for this sort of text-mining, although short texts will pose some issue.

As for integration with org-roam, these probably have to built as CLI applications. Org-roam can parse the response, and display them somehow.

**Comment by khinsen** [comment]
Looks very appropriate indeed. The reason why I mentioned Word2Vec is the availability of implementations. Is there any LDA code that we could reuse? I agree that most of it would have to happen externally to Emacs.

**Comment by jethrokuan** [comment]
LDA is available in scikitlearn and gensim. A common trouble across both the NN methods and these is that you'll probably need to redo tokenization, since each new note is likely to introduce technical terms that rarely occur. This is a research project unto itself!

**Comment by dit7ya** [comment]
I would rather want this as another Emacs package with easy plug and play for org-roam. Seems like this is a more powerful (albeit heavy) alternative - https://tfhub.dev/google/universal-sentence-encoder/4

I am willing to help with the Python and ML side of this project.

**Comment by khinsen** [comment]
@dit7ya That sounds good. Something in the spirit of [DocFetcher](https://sourceforge.net/projects/docfetcher/) but Emacs-centric and ML-powered (DocFetcher only does indexing).

**Comment by khinsen** [comment]
A relevant Twitter thread: https://twitter.com/marcinignac/status/1282625655725858817

**Comment by Schroedingberg** [comment]
I am intrigued by this idea, count me in.

**Comment by jethrokuan** [comment]
Closing as out of scope for Org-roam, but open to community extensions built on the db.
