### ISSUE TITLE
Reduce org-capture-plist pollution

### ISSUE THREAD

**Issue by progfolio** [org-roam/org-roam#332]
Instead of directly adding keys to `org-capture-plist` with `org-capture-put`, add a single `:org-roam` plist to `org-capture-plist`. You can then add as many keywords as you want without worry of conflicting keys

e.g.
```emacs-lisp
;;org-capture-plist
'(...:org-roam (:head ... :file-name ... :etc ...))
```

### Proposed Implementation (if any)
I've implemented something similar in [doct](https://www.github.com/progfolio/doct):

https://github.com/progfolio/doct/blob/443a0b631b577879647b1c00ce3814165d86afde/doct.el#L221-L229

Your case is even simpler:

```emacs-lisp
(defun org-roam-get (keyword)
  (plist-get (plist-get org-capture-plist :org-roam) keyword))
```

All that is required is a simple wrapper function.

### Please check the following:
- [x ] No similar feature requests

Interesting package. Look forward to seeing how it develops.
Thanks, 
Nick Vollmer

**Comment by jethrokuan** [comment]
That does sound neater. It is a breaking change though.

**Comment by jethrokuan** [comment]
I'm going to go with this approach, and throw an error for existing templates.

**Comment by progfolio** [comment]
I don't think it needs to be a breaking change. You can add the properties behind the scenes without changing the format of the template itself.

**Comment by myshevchuk** [comment]
Or create a separate `org-roam-capture-plist` altogether. One could then use it locally in the same manner as `org-capture-templates` is used in `org-roam-capture`.
```
(let ((org-capture-templates org-roam-capture-templates)
        (org-capture-plist org-roam-capture-plist))
```

**Comment by jethrokuan** [comment]
> I don't think it needs to be a breaking change. You can add the properties behind the scenes without changing the format of the template itself.

There are some properties that are specified by the user: `:file-name` and `:head`. These are part of the customization process. Any user configuration would then be invalid.

**Comment by progfolio** [comment]
> Or create a separate org-roam-capture-plist altogether

I was actually going to suggest the opposite. Org-capture is very mature and powerful. I'd have to look more closely at the source, but I think most if not all of what the extensions to the template syntax can be achieved with vanilla org-capture. 

org-capture can use a function to locate the file. That function could conditionally find or create the file.  That combined with a function for finding point, doing any buffer set up, may simplify the implementation and may fix bugs like #327 

e.g.
```emacs-lisp
  ("d" "default" plain
   (file+function org-roam--capture-get-create-file org-roam--capture-get-point)
   "%?"
   ;;etc...
   )
```
The custom keywords could still exist, but org-roam could take care of 'hiding' them on the org-capture-plist to avoid keyword conflicts. This would be transparent to the user.

**Comment by progfolio** [comment]
> There are some properties that are specified by the user: :file-name and :head. These are part of the customization process. Any user configuration would then be invalid.

> The custom keywords could still exist, but org-roam could take care of 'hiding' them on the org-capture-plist to avoid keyword conflicts. This would be transparent to the user.

**Comment by jethrokuan** [comment]
I'm not sure what you mean by "hiding" them.

say I want to change the file-name of a created file for a particular template. I have this in my `init.el`:

```
(setq org-roam-capture-templates
        '(("p" "private" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "private-${slug}"
           :head "#+TITLE: ${title}\n")
           :unnarrowed t)))
```

how do we get the user to specify the created file name without putting it in the capture template?

**Comment by progfolio** [comment]
If done properly, org-roam could also leverage org-catpure-templates-contexts to only show org-roam related templates when org-roam-mode is enabled. This would have the benefit of allowing the user to keep their template definitions in one spot (org-capture-templates) and could be implemented with another keyword to signal to org-roam that the template should be converted before passing it to org-capture.

```emacs-lisp
    (setq org-capture-templates '(("n" "Not an org-roam template" ;;etc
                                   )
                                  ;;org-roam 
                                  ("r" "Org Roam" :org-roam t :unnarrowed t)))
```

**Comment by progfolio** [comment]
> how do we get the user to specify the created file name without putting it in the capture template?

A function that converts that template to a template with org-roam's keywords on an :org-roam plist.
I'll write a demo.

**Comment by progfolio** [comment]
```emacs-lisp
(defun org-roam--convert-template (template)
  "Convert template from org-roam syntax to org-capture-templates syntax"
  (let* ((copy (copy-tree template))
         converted
         org-roam-plist
         key
         val)
    ;;put positional args on converted template
    (dotimes (_ 5)
      (push (pop copy) converted))
    (while (setq key (pop copy)
                 val (pop copy))
      ;;may want to make the list of keywords a variable for easier maintenance
      (if (member key '(:file-name :head))
          (progn
            (push val org-roam-plist)
            (push key org-roam-plist))
        (push key converted)
        (push val converted)))
  (append (nreverse converted) `(:org-roam ,org-roam-plist))))


(org-roam--convert-template '("d" "default" plain (function org-roam--capture-get-point)
                              "%?"
                              :file-name "%<%Y%m%d%H%M%S>-${slug}"
                              :head "#+TITLE: ${title}\n"
                              :unnarrowed t))
```

returns:

```emacs-lisp
("d" "default" plain #'org-roam--capture-get-point "%?" :unnarrowed t :org-roam (:head "#+TITLE: ${title}
" :file-name "%<%Y%m%d%H%M%S>-${slug}"))
```

**Comment by progfolio** [comment]
If you combine that with a wrapper for org-capture-get that accesses the :org-roam plist on org-capture-plist, the keywords are isolated from the rest of org-capture-plist and the user does not have to change anything.

**Comment by jethrokuan** [comment]
> I think most if not all of what the extensions to the template syntax can be achieved with vanilla org-capture.

@progfolio  Is there an easy way to pass variable values into the capture template? Right now there's an initial template expansion: E.g. `foo-${title}`. Ideally I'd have org-capture also expand that `title` into the value of `title`.

**Comment by progfolio** [comment]
```emacs-lisp
("d" "default" plain
 (file+function org-roam--capture-get-create-file org-roam--capture-get-point)
 (function org-roam--capture-get-template)
 ;;etc...
 )
```

So here you would have three functions responsible for setting up the buffer and the template string. `org-roam--capture-get-create-file` would create or get the target file programatically. `org-roam--capture-get-point` would be responsible for setting up the buffer (This could be generalized to insert the #+TITLE, and potentially customizable for the user) and setting up the point within that buffer. 

`org-roam--capture-get-template` could process the template string that would then be used by org-capture. This function could access members of org-capture-plist directly, or members of the :org-roam plist on org-capture-plist. The main takeaway here is that once you're using a function, you could do almost anything you want with the template string.

Does that make sense?

**Comment by progfolio** [comment]
I extend the template string expansion syntax in doct.
Users can access values stored on declarations in the template string using `%doct(keyword)`.
e.g.
```emacs-lisp
(doct '(("Parent" :keys "p"
         :file ""
         :template "* %doct(todo-state) %?"
         :children (("One" :keys "1" :todo-state "TODO")
                    ("Two" :keys "2" :todo-state "IDEA")))))
```
The template string is returned by this function:
https://github.com/progfolio/doct/blob/443a0b631b577879647b1c00ce3814165d86afde/doct.el#L347-L364

doct does some extra things, so that function has a little more going on than you would need, but it should give you the general idea.

**Comment by progfolio** [comment]
As a side note: I may be able to write a very simple package that extends doct to include an :org-roam keyword. This may simplify things for you and org-roam users. I'll work out a rough implementation and open a new issue if it seems viable.

**Comment by jethrokuan** [comment]
> ```emacs-lisp
> ("d" "default" plain
>  (file+function org-roam--capture-get-create-file org-roam--capture-get-point)
>  (function org-roam--capture-get-template)
>  ;;etc...
>  )
> ```

Okay I had no idea you could have so many of those positional clauses :O

I'd be very happy to replace the hacked-up templating system I'm using right now, with an external package like doct. That would take quite a bit of complexity out of org-roam.

**Comment by progfolio** [comment]
> Okay I had no idea you could have so many of those positional clauses :O

I was surprised to learn this as well while writing doct. It's a very flexible system.

> I'd be very happy to replace the hacked-up templating system I'm using right now, with an external package like doct. That would take quite a bit of complexity out of org-roam.

I'm still working on the internals of doct, but the user-facing API is pretty solid. There are several ways we could go about integrating it, but I'll have to think on it to weigh out the options. I'll submit a pull request soon and we can discuss its potential.

**Comment by jethrokuan** [comment]
awesome, looking forward to it!
