### ISSUE TITLE
Possible to use eww for clickable graph?

### ISSUE THREAD

**Issue by anthrolisp** [org-roam/org-roam#364]
Is it possible to use eww, or other emacs browser, for the clickable graph?
Thanks in advance!

**Comment by jethrokuan** [comment]
Some people had luck viewing the SVG within emacs, you need to compile Emacs with svg support for this: #145

**Comment by pcrama** [comment]
Maybe also look at this: https://github.com/alphapapa/org-graph-view (specifically the usage of :map keyword argument in https://github.com/alphapapa/org-graph-view/blob/13314338d70d2c19511efccc491bed3ca0758170/org-graph-view.el#L196) to make a clickable map on top of an SVG.

For people (like me) that already have Emacs with SVG support, this would be very nice.  No time to work on it myself ATM, though.

**Comment by michaelmrose** [comment]
It's possible to use Emacs Application Framework's browser to view the graphs displayed by org-roam-server.

https://github.com/org-roam/org-roam-server

From the EAF page. 

"EAF is an extensible framework, one can develop any Qt5 application and integrate it into Emacs."

https://github.com/manateelazycat/emacs-application-framework

Here is a function that either selects the existing buffer or starts one with eaf

    (defun mmr/visualize-org-roam ()
    "Either switch to the existing buffer for org-roam-server or create one with eaf."
    (interactive)
    (if (get-buffer "Org Roam Server")
        (switch-to-buffer "Org Roam Server")
        (eaf-open-browser "127.0.0.1:8080")))

Here is a fish shell script that is set via a desktop file to handle org-protocol links

    #!/usr/bin/env fish
    set class (xprop -id (xdotool getactivewindow) WM_CLASS|awk '{print $4}' | sed 's#"##g')
    if [ $class = Emacs ]
        emacsclient -n "$argv" &
    else
        emacsclient -cn "$argv" &
    end


If the current window class is Emacs for example you are clicking on links in the graph shown in the EAF window it opens the link in the current window.  If the link comes from an external application for example from capturing from your browser it opens in a new window alongside the other application.

You can capture from your browser with a bookmarklet or binding example via tridactyl for firefox for firefox

bind rr js javascript:location.href = 'org-protocol://roam-ref?template=r&ref=' + encodeURIComponent(location.href) + '&title=' + encodeURIComponent(document.title)

**Comment by jethrokuan** [comment]
`(setq org-roam-graph-viewer nil)` is the answer to OP's original question, for interacting with SVGs, using something that can better render SVGs is recommended (e.g. a browser).

`org-roam-server` is probably the best option if you use the graph functionality heavily.
