### ISSUE TITLE
Inconsistency in test suite results

### ISSUE THREAD

**Issue by progfolio** [org-roam/org-roam#384]
### Description
I've had the test suite fail several times in areas I have not touched. 
#### Steps to Reproduce
Seems to happen intermittently. See https://github.com/jethrokuan/org-roam/pull/383
The only thing that has changed is a few strings in the docs. No code was touched.

**Comment by jethrokuan** [comment]
I'm aware, but not sure what the fix should be yet

**Comment by progfolio** [comment]
Just documenting this in hopes that we can track this down. 
Another case in which a change to documentation failed: #433

Failure:
```
org-roam-insert nested/temp3 -> foo

Traceback (most recent call last):
  (buttercup-fail "%s" "Expected `(buffer-string)' with value \"\" to match ...
  (signal buttercup-failed "Expected `(buffer-string)' with value \"\" to ma...
FAILED: Expected `(buffer-string)' with value "" to match the regexp "file:\\.\\./foo\\.org", but instead it was "".
```

**Comment by jethrokuan** [comment]
This should be resolved already.
