### ISSUE TITLE
Allow a manual similarity scale for notes 

### ISSUE THREAD

**Issue by dit7ya** [org-roam/org-roam#395]
### Brief Abstract

This would meaningfully extend the `ROAM_ALIAS` feature by providing means to manually mention which note is similar to which note. This is practically creating Zettelkasten links by hand (enforcing the links in your mind better).

### Long Description

There should be some feature for manually setting how much a file is related to another one. Example: when I am looking at the file `emacs.org`, the org-roam buffer should display links to `spacemacs.org` buffer (and its backlinks too). Similarly, I would want to see all information about `personal-knowledge-management.org`, `extended-neocortex.org`, and `memex.org` at the same place.  If there is a scale of relationship, the keyword `ROAM_ALIAS` can be thought as $1$ in the scale while the relationship between Emacs and Spacemacs is maybe $.6$. 

When I am browsing the org-roam buffer, very often I want to glance at information about few other closely related files too. The current options for creating links between notes is to either linking them inside text or grouping them by tags. 

(AFAIK I understand this feature is not isomorphic to any of these two.)

This is a less expensive (albeit providing more control to the user) implementation of #326.

### Proposed Implementation (if any)

Provide a function `org-roam-setup-relationship` that lets you link the current buffer file with another one by automatically putting in a keyword like `#ROAM_RELATESTO: "filename:value"` in both the files. 

The org-roam buffer can have multiple headers for all the files the current file links to with their backlinks as subtrees.

I would love to know if others have more suggestions. 

### Please check the following:
- [x] No similar feature requests

**Comment by dit7ya** [comment]
Thanks for your comment.

The major difference - I would personally want to *see* the related pages' content and backlinks in the agenda buffer which I cannot do with the current setup. For example, in my head `machine-learning.org` and `artificial-intelligence.org` are similar things, but not exactly the same. However, I would want to see the content and backlinks of `machine-learning.org` as well when I as visiting the other file.

Idea: With sufficient number of options (apart from just this) we can even have custom org-roam views just like custom agenda views. I think this would provide a great deal of flexibility.

**Comment by dit7ya** [comment]
Thanks for your comment.

The major difference - I would personally want to *see* the related pages' content and backlinks in the agenda buffer which I cannot do with the current setup. For example, in my head `machine-learning.org` and `artificial-intelligence.org` are similar things :robot:, but not exactly the same. However, I would want to see the content and backlinks of `machine-learning.org` as well when I am visiting the other file.

:bulb: Idea: With sufficient number of options (apart from just this) we can even have custom org-roam views just like custom agenda views :rocket: . I think this would provide a great deal of flexibility.

**Comment by jethrokuan** [comment]
I don't intend to implement this, since this is not supported by the native id link type.
