### ISSUE TITLE
Unable to use ox-hugo with pandoc citations if org-roam note contains links to other notes

### ISSUE THREAD

**Issue by soldeace** [org-roam/org-roam#409]
### Description

I'm trying to export my org-roam notes to my Hugo website, but I chose to stick with pandoc rather than org-ref as the citation processing engine (`#+HUGO_PANDOC_CITATIONS: t`). But whenever an org-roam note contains a link to another note, ``M-x org-hugo-export-to-md`` issues the following error:

```org-hugo-pandoc-cite--fix-pandoc-output: Invalid use of ‘\’ in replacement text```

I tried to reproduce the error with a plain org file (outside the org-roam environment) with a link of the type `[[file:foo.org][Foo]]`, and the error does not occur.

This one may be tricky since it's perhaps a matter of incompatibility with ox-hugo.

### Versions
- Emacs: v26.3
- Org-roam: 20200407.553 from melpa

**Comment by jethrokuan** [comment]
Sorry for getting to this so late. Is this still an issue? I can't see to reproduce it.

**Comment by soldeace** [comment]
Yes! Everything's working now. Thank you!

**Comment by Rindrics** [comment]
@soldeace I encountered the same problem with yours.
Do you remember how you solved this problem?
Thanks.

**Comment by soldeace** [comment]
@Rindrics When @jethrokuan asked me if it was still an issue, I couldn't reproduce the problem either. That's why I considered it solved. But I forgot to use the WIP syntax for my citations the second time (e.g. `@JohnDoe2002` instead of `cite:JohnDoe2002`), which is needed if you want ox-hugo to call up pandoc. And when it happens, it does fail with the error message I mentioned in my first post.

My solution was giving up the `#+HUGO_PANDOC_CITATIONS` thing and started using citeproc-org to process my references during export. It works like a charm.
