### ISSUE TITLE
How to migrate from single file workflow to roam?

### ISSUE THREAD

**Issue by dangom** [org-roam/org-roam#414]
### Brief Abstract

A have a huge org file where I keep all of my notes. 
I was wondering what would be the best way to migrate to org-roam without losing these notes. Has anyone been through the same and would have suggestions on how to proceed?

### Please check the following:
- [x] No similar issues after searching for "single file"

**Comment by progfolio** [comment]
It may be helpful to give others an idea of the structure of your notes. Is each note an entry? Are they highly nested or relatively flat? etc.

**Comment by dangom** [comment]
Thanks.
I have one heading for each day, and one subheading for each topic of the day.
I then link to external files that are unrelated to my notes, if necessary, and link to previous notes using standard org links.

A toy example:

```org
...

* Monday 26th August
** Collect data for reviewer 1
Ran experiment on W to get data to address reviewer 1's comments.
* Tuesday 27th August
** Meeting with X
- Showed results from latest experiment. See [[*Collect data for reviewer 1]]
- Discussed manuscript revision, see [[./rev.org]]
** Extracting signals from data using Y's method

Y's method is good for Z. 
Example code on how to get it working can be found under [[github.com]].

* Wednesday 28th August
** Rework details of revision
- Add results from latest experiment to adress reviewer 2 concerns.

...
```

**Comment by bdarcus** [comment]
Do those kinds of notes (essentially, journaling of what you did) benefit from a system like org-roam, which is more focused on interlinking of ideas?

**Comment by dangom** [comment]
That's a good question. My notes are messy and don't have enough tags, so at first it doesn't seem like interlinking of ideas would make sense. However, many of activities I do on a day to day basis are similar, so having them all connected in one place would help me find patterns faster and remember why I was doing something on a given day.

My journaling approach comes from a lack of a better alternative. Do org-roam workflows support concepts such as journaling?

**Comment by bdarcus** [comment]
You might want to read the author's post on his workflow.

https://blog.jethro.dev/posts/how_to_take_smart_notes_org/

**Comment by kbruskiewicz** [comment]
I've set up my Capture template for Org-Roam to take a region of selection with `%i`.

You could migrate your notes with such a template by selecting them, doing `org-roam-insert`, and let the template do the rest.

**Comment by jethrokuan** [comment]
All your notes seem nested under a certain date, I'm not sure if that's something you wish to keep during your migration. You can do the same, by using org-journal to create the daily notes, and chronicle everything there.

What's different would be creating files as tags. For example, every project gets a tag. That would allow you to see things like: when you worked on a particular project, or how different projects are related.

**Comment by dimitry12** [comment]
I am in a "several huge files" situation (one journal file; one file per course/book/project) as well. Currently, when I look at my journal-file, in org-roam-buffer I see everything linked to every entry in the file - while is meaningless.

Is it a correct statement that: I can only use org-roam (to connect the notes) if I have one note per file? In other words, I can not have an individual subheading as a current org-roam context?

How about long-form notes, where I do want to have outline/hierarchical structure **plus** be able to link subheadings? Or is it contrary to the process which org-roam aims to facilitate?

> would be creating files as tags. For example, every project gets a tag. That would allow you to see things like: when you worked on a particular project, or how different projects are related.

This might be a good "crutch" to gradually transition while "refiling" entries.

**Comment by real-or-random** [comment]
> Is it a correct statement that: I can only use org-roam (to connect the notes) if I have one note per file? In other words, I can not have an individual subheading as a current org-roam context?

When you wrote this, the answer was "yes", but soon we'll have v2 ( https://org-roam.discourse.group/t/org-roam-major-redesign/1198 ) whose primary goal is to change exactly this. Every subheading will be a "node" and you can connect nodes. So if you haven't tried org-roam you may want to reconsider now or when a stable v2 is released.

**Comment by jethrokuan** [comment]
The single-file workflow is now supported.
