### ISSUE TITLE
No links in org roam buffer 

### ISSUE THREAD

**Issue by RCoeurjoly** [org-roam/org-roam#446]
### Description
No links appear in org roam buffer, even after executing:
`org-roam-db-build-cache`
And getting the message:

> files: 3, links: 1, titles: 3, refs: 0, deleted: 0

#### Steps to Reproduce

1. Clone https://github.com/RCoeurjoly/babel_sandbox
2. Load Emacs
3. Open file babel_sandbox/20200412134256-literate_programming.org
4. Run `org-roam-db-build-cache`
5. Run `org-roam`

#### Expected Results
Backlinks in *org-roam* buffer
#### Actual Results
Empty *org-roam* buffer

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: org-roam-20200411.1041

**Comment by RCoeurjoly** [comment]
Doing some queries in sqlite3, I get the following results:

> sqlite> select * from files;
"/home/rcl/babel_sandbox/babel_sandbox.org"|"5317e809b74f0d0633f4ec20454bfddd772f7330"|(24211 5156 318286 602000)
"/home/rcl/babel_sandbox/20200412134256-literate_programming.org"|"af9d8cdcf355072d9e261e7d2e8de21a54d6d3cf"|(24211 5156 318286 602000)
"/home/rcl/babel_sandbox/2020-04-12.org"|"0eb34f0df452163bd82effb7378f4d20db41c58c"|(24211 5156 318286 602000)
sqlite> select * from files;
"/home/rcl/babel_sandbox/babel_sandbox.org"|"5317e809b74f0d0633f4ec20454bfddd772f7330"|(24211 5156 318286 602000)
"/home/rcl/babel_sandbox/20200412134256-literate_programming.org"|"af9d8cdcf355072d9e261e7d2e8de21a54d6d3cf"|(24211 5156 318286 602000)
"/home/rcl/babel_sandbox/2020-04-12.org"|"0eb34f0df452163bd82effb7378f4d20db41c58c"|(24211 5156 318286 602000)
sqlite> select * from links;
"/home/rcl/babel_sandbox/2020-04-12.org"|"/home/rcl/babel_sandbox/20200412134256-literate_programming.org"|"roam"|(:content "Trying org-roam\n[[file:20200412134256-literate_programming.org][literate programming]]" :point 22)
sqlite> select * from refs;
sqlite> select * from titles;
"/home/rcl/babel_sandbox/babel_sandbox.org"|
"/home/rcl/babel_sandbox/20200412134256-literate_programming.org"|("literate programming")
"/home/rcl/babel_sandbox/2020-04-12.org"|("2020-04-12")

So it seems the database is populated with valid data, now the issue is why it is not displayed in the *org-roam* buffer.

Am I missing something here?

**Comment by progfolio** [comment]
I have experienced this as well when using commands before enabling org-roam-mode. 
Does this work for you?

1. Execute `org-roam-mode`
2. Select a file with `org-roam-find-file`
3. Execute the `org-roam` command

**Comment by jethrokuan** [comment]
Are there any error messages? When the backlinks buffer is completely blank, it usually means the text insertion process aborted abruptly due to some error.

**Comment by RCoeurjoly** [comment]
> I have experienced this as well when using commands before enabling org-roam-mode.
> Does this work for you?
> 
>     1. Execute `org-roam-mode`
> 
>     2. Select a file with `org-roam-find-file`
> 
>     3. Execute the `org-roam` command

I get the same result, a blank org-roam buffer.

**Comment by RCoeurjoly** [comment]
I think I have found the issue.

I hadn't set a global org-roam-directory, just a local one.

Once I set a global one. the local one works!!

I think it shouldn't be that way.
The locally defined org-roam-directory should work regardless of a global org-roam-directory,.

**Comment by jethrokuan** [comment]
> I hadn't set a global org-roam-directory, just a local one.

I doubt this is it though.

**Comment by RCoeurjoly** [comment]
And now again I have a blank org-roam buffer.

What are the steps to debug a problem in org-roam? What would you @jethrokuan add to the following list?

- Make sure org-roam minor mode is enabled
M-x describe-variable RET minor-mode-list
- Make sure you have installed sqlite3
`sqlite3 --version`
- Make sure you have open the org-roam buffer
M-x org-roam
- Make sure you have open an org file with links
 M-x org-roam-find-file

**Comment by progfolio** [comment]
With an org-roam buffer as the current buffer, eval:
```emacs-lisp
(org-roam--maybe-update-buffer :redisplay t)
```
Is the org-roam buffer updated?

**Comment by RCoeurjoly** [comment]
> With an org-roam file as the current buffer, eval:
> 
> ```emacs-lisp
> (org-roam--maybe-update-buffer :redisplay t)
> ```
> 
> Is the org-roam-buffer updated?

It is updated indeed.
How come there is not a hook to execute that command when you open an org file with org-roam mode activated?

**Comment by RCoeurjoly** [comment]
> With an org-roam file as the current buffer, eval:
> 
> ```emacs-lisp
> (org-roam--maybe-update-buffer :redisplay t)
> ```
> 
> Is the org-roam-buffer updated?

Is that something that I should put in my init.el file?

**Comment by jethrokuan** [comment]
> How come there is not a hook to execute that command when you open an org file with org-roam mode activated?

It's on `post-command-hook`. I tested the dir-local overrides, and the org-roam buffer is only empty when i launch `org-roam` when not in a org-roam file. Once I navigate to an org-roam file, the buffer is populated.

**Comment by weishuhn** [comment]
@RCoeurjoly `org-roam` was working as expected initially but when I restarted emacs, I was having the same problem as you.  For the record, I'm using spacemacs.  It turns out that I had forgot change `the org-roam-directory` in the layer file and had done it manually initially and when I restarted emacs, that was wiped out.  When I executed:

```
(org-roam--maybe-update-buffer :redisplay t)
```

It would update as it did for you.  

Hopefully this helps.

**Comment by progfolio** [comment]
I've hit similar problems myself by using an autoloaded command before explicitly enabling `org-roam-mode`. 

@jethrokuan: we should probably have a separate minor-mode for the org-roam-buffer. 
`org-roam-buffer-mode`. This way we could check and enable/disable that minor-mode when showing/hiding the org-roam-buffer.

**Comment by telotortium** [comment]
The way that I encounter this issue is as follows:

1. Start Emacs, and navigate to an Org file with a dir-local `org-roam-directory`.
1. Follow link from Org file (not in `org-roam-directory`) to Org file in `org-roam-directory`.
1. From the Org file in `org-roam-directory`, run `org-roam-buffer-toggle-display`.
1. I see the title of the org-roam backlinks buffer set to something like `../../path/to/roam/DATE-roam-file.org` (if the Org file's title is "Roam File").
1. From the Org file, run `(org-roam--maybe-update-buffer :redisplay t)`.
1. Now the backlinks buffer is updated correctly.

**Comment by bbigras** [comment]
I had a similar problem. When I tried to run `org-roam-db-build-cache` I got:
`peculiar error: "UNIQUE constraint failed: files.file"`

I deleted `org-roam.db` in my notes directory. Rebuilt the cache and restarted emacs and it's fine now.

**Comment by telotortium** [comment]
I got that error too, and fixed it the same way. Furthermore, before the
fix, it seemed to prevent my other after-init-hook functions from running.

**Comment by RCoeurjoly** [comment]
For me it is now solved, although I don't know why.

**Comment by gkowzan** [comment]
I have the same issue as @telotortium with `../../path/to/roam/DATE-roam-file.org` when using deft to open a roam file. Using `org-roam-find-file` works without problems. Additionally, I get a line in `*Messages*` buffer saying: `~/roam/file.org and /home/user/roam/file.org are the same file`. This is unexpected because I made sure to give the path to roam directory everywhere in my init file as `(expand-file-name "~/roam")`. Deleting `org-roam.db`, rebuilding roam cache and restarting Emacs doesn't have any effect. Does deft have its own cache which could cause that?

**Comment by jethrokuan** [comment]
Deft has no cache, but it doesn't do the appropriate path expansion. I bumped into this issue a while back, when I was working with deft.

**Comment by gkowzan** [comment]
Ok, are you using something else now instead of deft or did you fix this issue?

**Comment by jethrokuan** [comment]
I'm just using org-roam functions, not using deft anymore.

**Comment by gkowzan** [comment]
I dug around in the code and the issue wasn't with `~` and `expand-file-name` but with symlinks. My `deft-directory` and `org-roam-directory` was `~/Documents/roam` which is a symlink to `~/Dokumenty/roam`. Setting both variables to the latter path seems to have fixed the issue. I suppose that patching `deft-open-file` with a strategically placed `file-truename` (which resolves symlinks) would solve it.

Hope that helps someone.

**Comment by digizeph** [comment]
I had encountered the same issue and confirmed that the issue was caused by symlink. After replacing symlink, the org roam buffer shows up again, and everything back to normal. I had to run `org-roam-db-build-cache` again afterwards.
