### ISSUE TITLE
Multiple insert file selection

### ISSUE THREAD

**Issue by obrowny** [org-roam/org-roam#459]
### Thank you !
First of all, thank you for your work, it is fabulous !
I apologize if my request is a misunderstanding from my part.
### Brief Abstract
It would be nice to be able to select multiple files when inserting links instead of C-c ni multiple times.
### Long Description
I am using Helm.
Doing C-c ni in the capture template opens listed files.
Selecting multiple files works with C-space
Hitting enter does insert one linked file only.
### Proposed Implementation (if any)
Org-ref manages to insert many citation doing the same way as described.
Maybe the solution could be find there.
### Please check the following:
- [x] No similar feature requests

**Comment by obrowny** [comment]
I have edited my request, didn't see that space and enter keys didn't print (initially put them between<> signs.)

**Comment by jethrokuan** [comment]
The core Org-roam will only support `completing-read`, and I don't intend to work on Helm/Ivy equivalent commands, although I have kept this in mind and made the v2 API much easier for reuse.
