### ISSUE TITLE
incompatibility with org-id-get-create

### ISSUE THREAD

**Issue by obrowny** [org-roam/org-roam#472]
### Description
If you have a hook to create a unique id to capture templates, org-roam-find-file will fail.
#### Steps to Reproduce
1. add  to init file:
(add-hook 'org-capture-mode-hook #'org-id-get-create) 
or
(add-hook 'org-capture-prepare-finalize-hook 'org-id-get-create)
2. Reload Emacs
3. Execute org-roam-find-file

#### Expected Results
org-roam-find-file should work without having to desactivate org-id for capture templates.

#### Actual Results
In the first case capture template does not pop up. (but file is shadowly created)
In the second case it is impossible to confirm capture hitting C-c C-c nor exit the buffer.

Message is (org-back-to-heading: Before first headline at position 52 in buffer CAPTURE-file-name)
### Versions
- Emacs 26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/e33c144

**Comment by jethrokuan** [comment]
Please see #420

**Comment by progfolio** [comment]
To add to #420:
If you're going to add  functions to any of org-capture-mode's hooks you'll want to be very careful that they do not fail for other templates. You can do so by filtering for a specific template in the hook function by querying `org-capture-plist`:

```emacs-lisp
(defun my/org-capture-template-k ()
  (when (string= (org-capture-get :key t) "k")
    (message "Only run when the template with key \"k\" is selected")))
```
You'll also have to be careful to maintain that relationship between the function and the template if the key string ever changes. This was part of the motivation for writing https://github.com/progfolio/doct. It allows you to add per-template hooks in an easy and maintainable way.
