### ISSUE TITLE
Non-org files are styled as roam links

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam#485]
### Description
The changes introduced by #470 caused image links to be styled with `org-roam-link` face, reported by @isolet.

#### Steps to Reproduce

1. Create a roam file with file link to image [[file:images.png]].
2. `M-x describe-face`

#### Expected Results
Face should be `org-link`

#### Actual Results
Face is `org-roam-link`
### Versions
- Emacs (`C-h v emacs-version`): v28.0.50
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/6175739b33b0abaa862c0137e216e6029f24d5cd

**Comment by juergenhoetzel** [comment]
> The changes introduced by #470 caused image links to be styled with `org-roam-link` face, reported by @isolet.

I can't confirm/reproduce this issue and do not see how this issue could be related to #470 .

**Comment by jethrokuan** [comment]
![image](https://user-images.githubusercontent.com/1667473/79686700-e2234180-8274-11ea-8704-d07c3278cc36.png)

The green links are styled with the `org-roam-link` face.

**Comment by juergenhoetzel** [comment]
I still can't reproduce it: `(org-roam--org-file-p path)` returns `nil` for non-org files.

**Comment by jethrokuan** [comment]
I believe this is no longer the case:

![image](https://user-images.githubusercontent.com/1667473/83323106-33b8e600-a28f-11ea-81bb-0b93640054b9.png)
