### ISSUE TITLE
Generalize org-roam-graph to allow multiple graph building backends

### ISSUE THREAD

**Issue by progfolio** [org-roam/org-roam#494]
Currently dot/graphviz are the only option. We could generalize similarly to #488 and allow either a function or a string for `org-roam-graph-executable`.  Then when we build the graph, if a function is supplied we can simply defer to that. This would allow alternative graph visualization back ends to be easily developed for org-roam as separate packages. This would also allow the  graphviz/dot functionality to be moved to its own module and offer more/cleaner customization options as well.

**Comment by progfolio** [comment]
Not packaged yet, but implementing this would allow users to plug in something like: https://github.com/alphapapa/org-graph-view

**Comment by Accacio** [comment]
it could also be interesting to generate a html page instead of a svg, so we could use visjs to plot the graph as in [https://visjs.github.io/vis-network/examples/network/data/dotLanguage/dotEdgeStyles.html](https://github.com/jethrokuan/org-roam/issues/url)

**Comment by zaeph** [comment]
> it could also be interesting to generate a html page instead of a svg, so we could use visjs to plot the graph as in https://visjs.github.io/vis-network/examples/network/data/dotLanguage/dotEdgeStyles.html

I believe there's already been a project exploring a JS implementation of the graph on Slack.  The author said he might open a PR in the future, so we'll have to keep an eye out for that.
