### ISSUE TITLE
open buffer when opening an org-roam file

### ISSUE THREAD

**Issue by bdarcus** [org-roam/org-roam#507]
### Brief Abstract

When I load an org-roam file, I want the org-roam buffer to load with it.

I think from a UX perspective that should be the default behavior, but it would be fine if configurable and set to off by default too.

### Proposed Implementation (if any)

Add a simple variable so user can choose; perhaps call it something like `org-roam-buffer-autoload`?

### Please check the following:
- [x] No similar feature requests

**Comment by zaeph** [comment]
Without creating a variable, it would be easy to do by adding a hook-function to `org-mode` which would run something like:
```el
(when (org-roam--org-roam-file-p)
  (org-roam))
```

But I agree that a toggle-variable might be a good idea, at least until we get to revamp the side-window.

**Comment by brianmcgillion** [comment]
personally I would not like it as the default mode. I have a lot of leaf nodes that do not have backlinks so it is wasted space. `C-c z l ` to show org-roam buffer is faster to type than `C-x 1` to get rid of it :) But an option to set it either by a hook or variable would be a good one.

**Comment by zaeph** [comment]
> personally I would not like it as the default mode.

I also agree that this shouldn't be the default, but that one should be able to toggle on that behaviour.

**Comment by brianmcgillion** [comment]
https://github.com/hlissner/doom-emacs/commit/635d070e9432b135d4f78448e5702cbce43991a5

This was just added to Doom emacs

**Comment by zaeph** [comment]
> [hlissner/doom-emacs@635d070](https://github.com/hlissner/doom-emacs/commit/635d070e9432b135d4f78448e5702cbce43991a5)
> 
> This was just added to Doom emacs

Not sure how I feel about having that behaviour downstream instead of upstream, especially when they make it the default.  Plus, this doesn't look like it would gracefully close the side-window upon leaving an Org-roam buffer.

Not sure either how much energy we want to invest into this if we are going to revamp the side-window.

**Comment by brianmcgillion** [comment]
https://github.com/hlissner/doom-emacs/commit/6bcd1063e6dfe6a9fbd2f35f5cdcf49acd9fb555

this was also added by default. so the backlinks buffer stays around

**Comment by brianmcgillion** [comment]
Once the changes are made to OR, then the backlinks buffer handling code can be reverted and replaced with the upstream version

**Comment by zaeph** [comment]
> Once the changes are made to OR, then the backlinks buffer handling code can be reverted and replaced with the upstream version

All right.  Let's revisit this when we've made progress on the revamp, then.

**Comment by bdarcus** [comment]
FWIW, I didn't suggest this on Doom; guess I wasn't the only one who thought it a good idea ;-)

**Comment by real-or-random** [comment]
I'd love to see this implemented.

As an adhoc solution I tried to add `(add-hook 'org-mode-hook 'org-roam-buffer-activate)` to my config but this doesn't work.

**Comment by ErnestDong** [comment]
So how to do in v2?

**Comment by jethrokuan** [comment]
Not going to include this in the repo, but something like this should be sufficient.

```
(add-hook! 'find-file-hook
  (and (org-roam-file-p)
       (not (eq 'visible (org-roam-buffer--visibility)))
       (org-roam-buffer-toggle)))
```

**Comment by real-or-random** [comment]
I needed this more aggressive variant. When I run org-agenda first, it will visit many of my org-roam files in the background. So when then want to visit the file, there's already a buffer and `find-file-hook` does not apply anymore.  

```
(add-hook 'window-buffer-change-functions
          (lambda (_)
             (and (org-roam-file-p)
                 (not (eq 'visible (org-roam-buffer--visibility)))
                 (org-roam-buffer-toggle))))
```

Maybe this is helpful to others here.

**Comment by real-or-random** [comment]
Sorry to resurrect the closed issue but here's an updated version. This works pretty well for me.

```
  (defun tim/org-roam-buffer-show (_)
    (if (and
         ;; don't do anything if we're in the minibuffer
         (not (minibufferp))
         ;; show org-roam buffer iff the current buffer has a org-roam file
         (xor (org-roam-file-p) (eq 'visible (org-roam-buffer--visibility))))
        (org-roam-buffer-toggle)))
  (add-hook 'window-buffer-change-functions 'tim/org-roam-buffer-show)
```

Again, maybe this is helpful to people.

**Comment by real-or-random** [comment]
I've improved this again. Now it doesn't need hackish checks like `(not (minibufferp))` and I made this a minor mode so that it can be enabled or disabled on demand.

```
(defun tim/org-roam-buffer-auto-toggle (frame)
  "Ensure that org-roam buffer is visible iff frame contains an org-roam file."
  (with-selected-frame frame
    (when (xor
           (eq 'visible (org-roam-buffer--visibility))
           (seq-find
            (lambda (window) (org-roam-buffer-p (window-buffer window)))
            (window-list)))
      (org-roam-buffer-toggle))))

(define-minor-mode tim/org-roam-buffer-auto-mode
  "Global minor mode for toggling the org-roam buffer automatically.

When this global minor mode is enabled, then the org-roam backlink buffer is
shown if and only if the current frame has a window with an org-roam file."
  :global t
  :lighter " OrgRoamBuf"
  (if tim/org-roam-buffer-auto-mode
    (add-hook 'window-buffer-change-functions 'tim/org-roam-buffer-auto-toggle)
    (remove-hook 'window-buffer-change-functions 'tim/org-roam-buffer-auto-toggle)))

```
Works like a a charm for me. 

@jethrokuan Do you think this is mature enough to be included here (default off)? The above version is still not perfectly non-intrusive (e.g., if you want to maximize the window with org buffer, that won't work because the hook will jump in and show the org-roam buffer again), but if this is too much for anyone, they can turn simply the mode off again. Of course, it should be off by default. A few people here have expressed that this is how they expect org-roam to work. It would be wonderful to have this included in the package.

**Comment by real-or-random** [comment]
Doom has yet another method. It's simpler than my minor mode above, and it works pretty well in practice:

https://github.com/doomemacs/doomemacs/blob/03d692f129633e3bf0bd100d91b3ebf3f77db6d1/modules/lang/org/contrib/roam.el#L64-L66
https://github.com/doomemacs/doomemacs/blob/03d692f129633e3bf0bd100d91b3ebf3f77db6d1/modules/lang/org/contrib/roam.el#L75-L86
