### ISSUE TITLE
Support nested org-roam-capture

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#527]
### Brief Abstract
We've disabled nested `org-roam-capture` because it'd be complicated to handle well.  However, from the user's perspective, running `org-roam-insert` inside an `org-roam-capture` buffer prompted by another `org-roam-insert` should be possible.

### Long Description
#327 brought up some problems with nested `org-roam-capture`, which were addressed in #329 by disabling nesting.  @jethrokuan mentioned [here](https://github.com/jethrokuan/org-roam/issues/327#issuecomment-601665965) that solving this issue would be complex, but I think this is necessary.

### Proposed Implementation (if any)
Reenable nested `org-roam-capture`, and create the infrastructure to have *parents* be aware of their *children*.
- When `org-roam-insert` calls `org-roam-capture` inside an `org-roam-capture` buffer (the parent), we make the *child* buffer aware of its *parent*, and the *parent* aware of its child.  This can be achieved with local variables in the two buffers.
- In the *parent* buffer, shadow all the commands that would result in the killing of the `org-roam-capture` buffer (success, abort, `kill-buffer`) as long as the *child* buffer exists.  The commands should now warn that a child-`org-roam-capture` is underway, and that it should be completed first.
- If a parent has multiple *children*, simply store them in a list, and check for the existence of all of them before killing the *parent* buffer.
- In the *child* buffer, on a successful capture, ensure that we insert the link inside the *parent* `org-roam-capture` buffer.  Point might be an issue, but we could create a marker in the *parent*, and have the *child* be aware of it.

We now have a hierarchy between the buffers that ensures that the links are inserted where they should, and that the captures aren't aborted or completed before we need them to be.

I'm going to start working on an implementation next week.  In the meantime, if you have any suggestion, I'm all ears!

### Please check the following:
- [X] No similar feature requests

**Comment by progfolio** [comment]
This is a problem I've been thinking about with [doct](https://github.com/progfolio/doct) as well.
org-capture allows nested capture processes.
 `org-capture-current-plist` is a buffer-local variable that is set per capture process. 
`org-capture-get` accepts an argument that makes it query that variable instead of `org-capture-plist`.

If I recall correctly, we add custom properties to `org-capture-plist`, but are accessing them before `org-capture-current-plist` is set up with `org-roam-capture--get`. (e.g. in `org-roam-capture--new-file`)
I'll have to look over my notes for doct and see if I came up with a solution.

**Comment by zaeph** [comment]
> `org-capture-current-plist` is a buffer-local variable that is set per capture process.
> `org-capture-get` accepts an argument that makes it query that variable instead of `org-capture-plist`.

Yes, thanks for mentioning it.  It's the variable that I was intended to use to store the buffers of the parent and the children.

The prototyping is going well, but it's made it obvious that the ping-pong between note buffers, parent `org-roam-capture` buffers, and children `org-roam-capture` buffers is going to be delicate.  For the most art, I think we can get away with using `org-capture-current-plist`, but there are some core functionalities that still make use of `org-capture-plist` (i.e., the non-local version), most notably the `org-roam-capture--new-file`.

I think I'm not going to touch it for the moment, and only try to implement nesting without bumping around other stuff.

**Comment by zaeph** [comment]
Made some progress on this tonight, but it's quite complex indeed.  I've almost got the parallel and nested items working, and I need to iron out the kinks.  Then, I'll move on the parent/child link.

I'm not publishing a PR yet because the code is quite ugly.  Will get to it by next week, got a thesis to finish by then.

Small demo:
![output-2020-04-27-00:48:47](https://user-images.githubusercontent.com/12202828/80321900-58014d00-8821-11ea-8314-f438cbfb2ecf.gif)

**Comment by zaeph** [comment]
I've opened #532 to share my work, but bear in mind that it's very alpha.

**Comment by progfolio** [comment]
Looked over #532. I think you're on the right track. I've been wrestling with this in doct as well. Looked over my notes from that and this is what I understand the situation to be:

- Any metadata that needs to be accessed before org-capture-mode is invoked (while building the template) should be accessed via `org-capture-plist`.
- Hooks that have access to `org-capture-current-plist` are `org-capture-before-finalize` and `org-capture-prepare-finalize`. There's no reason we shouldn't be able to access the variable during the `org-capture-mode-hook`, but unfortunately it is set after `org-capture-mode` is invoked in the capture buffer. I've submitted a patch to the Org dev team to see if this can be changed. It's a matter for flipping two lines and has no downside that I could think of, so hopefully that is rectified soon.

- `org-capture-after-finalize-hook` is executed after the capture buffer is killed, so we can't reliably use `org-capture-current-plist` there. A solution I thought of in doct is just to set `org-capture-plist` to `org-capture-current-plist` during `org-capture-before-finalize-hook`. This way `...after-finalize` hook functions can still access the information that was associated with the capture buffer that was finalized. I think that should take care of most nested capture problems.

**Comment by jethrokuan** [comment]
Closed with #966
