### ISSUE TITLE
Encryption of content in the database when using `.org.gpg` files

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#528]
### Brief Abstract
We handle [GPG-encrypted `.org.gpg` files](https://github.com/jethrokuan/org-roam/blob/41423005010f2f78c3e9301b97f1b0db83fd29b5/doc/configuration.md#encryption), but we're storing plain-text content in the database with commands like `org-roam--extract-links`

### Long Description
I don't know much about the way we handle the database, but I'm pretty sure we're storing plain-text objects in it.  `org-roam--extract-links` also extracts the surrounding context of the links, which means that some of the cached information might be leaked.

### Proposed Implementation (if any)
Multiple options:
- Encrypt/decrypt on request/retrieval when in `.org.gpg` files.
- Encrypt the whole database when using `.org.gpg` files.

### Please check the following:
- [X] No similar feature requests

**Comment by gsx** [comment]
I hacked together something to (optionally) use [sqlcipher](https://github.com/sqlcipher/sqlcipher) in the place of sqlite3. That enables encrypting the database contents using a symmetric key derived from a passphrase. It is pretty raw, but in my very limited testing seems to work smoothly, at least for my use case anyway. Would you be interested in a PR for this?

**Comment by jethrokuan** [comment]
#1388 removes the stored content in the database, preferring fetching the content on the fly. However, the outline is still stored in the database, which could potentially be sensitive. 

@gsx does this require any changes to Org-roam's source code? If not, documenting the process of encrypting the database would be useful to others.

**Comment by gsx** [comment]
Technically you could probably get away without changing any org-roam source but it feels like it would be fairly hacky.

The changes I made are to do with toggling encryption of the database and handling the encryption key. They are fairly well contained. You can get an idea of the diff from [my feature branch](https://github.com/gsx/org-roam/tree/support-sqlcipher).

I'm not particularly well versed in elisp so the change is probably not acceptable as it is, but I'm happy to turn it into a PR and make changes based on any feedback.

**Comment by ParetoOptimalDev** [comment]
> If not, documenting the process of encrypting the database would be useful to others.

Agreed, I'm looking for this now. 

> The changes I made are to do with toggling encryption of the database and handling the encryption key. They are fairly well contained. You can get an idea of the diff from [my feature branch](https://github.com/gsx/org-roam/tree/support-sqlcipher).

I'll take a look at this and see if I can figure it out and use it.
