### ISSUE TITLE
org-roam--rename-file-advice breaks when NEW-FILE points to a directory

### ISSUE THREAD

**Issue by Wetlize** [org-roam/org-roam#554]
### Description

`rename-file` allows users to both, rename and move files. When moving files, user can just select a directory from an interactive prompt, in which it case it will move the selected file to the selected directory reusing its old filename. From the corresponding docstring:

> If NEWNAME is a directory name, rename FILE to a like-named file under
NEWNAME. For NEWNAME to be recognized as a directory name, it should
end in a slash.

Org-Roam right now doesn't handle this. If `org-roam--rename-file-advice` receives `NEW-FILE` as a directory, it will not understand that the user here reuses the previous filename, just with a different path.

As result, `rename-file` will complete itself as expected, but the backlinks will never repair themselves.

#### Steps to Reproduce

1. In `org-roam-directory` reproduce the next file-system layout:
    - `org-roam-directory`/
      - root.org
      - origin-dir/
        - file-to-move.org
        - move-target-dir/
2. In the `file-to-move.org` create org-roam link to `root.org`.
3. In the `root.org` create org-roam link to `file-to-move.org`.
4. Interactively execute `rename-file` and select `file-to-move.org` as `FILE` and the `move-target-dir` as our `NEWNAME`.

#### Expected Results
1. `file-to-move.org` should be moved from the `origin-dir` to the `move-target-dir`.
2. `root.org` should repair its link to `file-to-move.org`
3. `file-to-move.org` should repair its link to `root.org`.

#### Actual Results
1. Works as expected
2. Does not repair the link.
3. Does not repair the link.

### Versions
- Emacs (`C-h v emacs-version`): v26.1
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/69d4f05a131921d7ebb1e79cd7cf0eac61f030df

**Comment by Wetlize** [comment]
I should probably note that everything work as expected if you explicitly specify yourself `NEWNAME` as a filename.

I don't think the bug is difficult to fix, the advice should just check `NEW-FILE` with `file-directory-p` somewhere in it, and if it would pass the check, just change `NEW-FILE` to `(concat NEW-FILE (file-name-nondirectory FILE)` and then run the remaining instructions.

**Comment by Wetlize** [comment]
> I should probably note that everything work as expected if you explicitly specify NEWNAME as a filename yourself.

Update: While links that point in other files to `NEWNAME` (in this case) get repaired just fine, the backlinks inside the `NEWNAME` file are never get repaired. So the bug fix is probably a little bit more involved than I thought at first.

**Comment by jethrokuan** [comment]
Thanks for looking into this, I'll hopefully have a follow up fix tomorrow.
