### ISSUE TITLE
Support tags as first-class values

### ISSUE THREAD

**Issue by Wetlize** [org-roam/org-roam#572]
### Brief Abstract
There's use cases when you need to interact with notes for meta specific purposes, where title alone end-up insufficient, e.g. as a meta-data for an an extra taxonomy. Right now sub-directories or custom file prefixes kind of allow you to do this, but they aren't as flexible as tags are (e.g. storing one note under 2 different directories is a PITA experience) and involve a higher level of friction.

### Long Description
I should clarify that the purpose (or at least focus) of tags that I'm describing here is not for the formation of new notes that would create backlinks in them (nor empty files). The backlinks here (at least for me) don't really carry much value, *however*, if you feel like backlinks should be allowed to work as tags too, feel free to do so.

At the very basic level (see "Assignment of tags" section for more details), tags would be assigned as simple strings to a dedicated org-mode keyword in files, that would not form any backlinks, so they will not create any extra notes (nor empty files) with corresponding to them names.

The purpose of tags that described here is to provide more value at a meta level instead. For example, they can be utilized by the graph, completion system in Emacs, exporting/publishing systems, or organizational purposes. As a more concrete example, take the completion system: just like we do right now with sub-directories, tags could format titles and assign themselves as part of the title.

![Example 1](https://user-images.githubusercontent.com/17055067/81127726-c9d74600-8f47-11ea-9728-30cf1fa4ee20.png) 
*(here, `bib` displayed as tag and it isn't part of the `#+TITLE:`, instead it's just formatted to be  displayed this way along with title)*

In this case we are able to use tags to narrow down to a specific set of candidates, which is very useful when you don't remember specific title but can quickly recap (or guess) its taxonomy.

#### Assignment of tags
This would be done programmatically, so the user would be able to specify how tags should be set based on specific conditions. He could write and add his own rules and/or use rules that we would supply ourselves as part of the default "library". Here's some basic examples of what can be supplied to the user as part of the library:

- Extract tags based on specific org-mode keyword in files. It was suggested in Slack by @zaeph that `#+ROAM_TAGS` would be a good candidate for this.
  - It was also noted in Slack that we shouldn't reuse `#+FILETAGS:` for this purpose, because its semantic is a bit different from what is proposed here.
  - As values accepts:
    - comma or space separated in-buffer strings, e.g. `#+ROAM_TAGS: tag, another tag`
    - maybe optionally roam links too (for those who needs this), in which case the org-roam buffer or graph would also render them as backlinks (also see the item bellow as an alternative).
- Extract tags from top level `- tags :: {backlinks}` description list.
- Automatically turn sub-directories into tags, e.g. files that reside in `org-roam-directory`/inbox/foo/ would return `inbox` and `foo` tags.
- Automatically turn filenames that have specific filename pattern into tags, e.g. files that have name `tag_foo.org` would return `tag` tag (that's it, `#+TITLE:` here would be `foo`, so tag here is `tag`).
- Automatically add `ref` tag for entries that have `#+ROAM_KEY` specified in them.

The implementation would look like this:

```elisp
;; If set to nil, then we will never collect any tags.
(defvar org-roam-tags-setters #'(org-roam-tags-from-tag-keyword ; returns tags by extracting them from the `#+ROAM_TAGS` keyword
                                 org-roam-tags-from-subdirs     ; `org-roam-directory`/inbox/foo/ would return `inbox` and `foo` tags.
                                 org-roam-tags-from-key-keyword ; returns `ref` tag if there's `#+ROAM_KEY` entry present
                                 ...)
  "Functions that will be executed to set tags programmatically.

..[API details].")
```

 I don't really now though, when would be the best time to run these setters, but I suspect, from the user perspective, it would be when we load each note into Emacs buffer (i.e. when we read files to build or update the database, like [here](https://github.com/jethrokuan/org-roam/blob/3ca2d9f4caf688b14ad752e68cec74be0cb74ca6/org-roam-db.el#L336-L347)), so these functions would be able collect tags by analyzing its content or other information about the file itself. In this case buffer can be accessed implicitly (think of `this` or `self` pointer), or explicitly (as a passed argument for each function). Alternatively we can pass an AST of each note instead of direct buffer, though this can end-up noticeably expensive thing to do in Emacs.

#### Formatting and insertion of tags
There can be a separated set of (interactive and non-interactive) functions that would be dedicated for collection of tags, their completion, insertion and other behaviors.

Just like in case with sub-directories, user should be allowed to specify how tags should be formatted along with titles.

```elisp
;; Similarly to how `org-roam-titles-subdir-format` does it right now.
(defvar org-roam-tags-title-format #'org-roam--format-title-with-tags
  "Function to use to format the titles of entries with tags.

..[details].")
```

When inserting org-roam links there should be a way to strip tags automatically from the "description" part of the link. This could be done as either, automatic post-processing step or manual "toggle at point" command (something tells me that tags inserted with titles can still provide value in some contexts). Alternatively, since tags can potentially change in future, we can always strip them after insertion, and just render them as togglable overlays.

#### Integration with other modules

- Some code that's responsible for sub-directories would need to be rewritten, so they would be turned into tags instead.
- For graphs, `org-roam-graph-exclude-matcher` could utilize tags too (along with paths?)
- Probably more, just haven't thought deep enough about this.

### Please check the following:
- [X] No similar feature requests

*... There were topics about tags (e.g. #460, #421, #84, #255 and maybe more), but I don't think any of them describes the same.*

**Comment by bdarcus** [comment]
Just to clarify, how do you think these these tags would relate to the zettlekasten model (or I guess how it was reinterpreted in roam per se) on which OR is based?

Do they conflict with it? Are they a sympathetic additions specific to enhancing the implementation of that model in this software? Something else?

How do we, and users, clearly distinguish tags/metadata from note links?

I only ask because having that well-known model gives us (the larger OR community that is) a touchstone to ground feature-request discussions.

**Comment by kbruskiewicz** [comment]
I think the assumption that links ought not to be used as tags, on top of being used as titles, is false. If the purpose of a link is to give the means to satisfy the question, "In what context do I want to see this note again?", then the link-based answer to this use-case is that you want to be able to indirectly search for in a completion window any file containing a link – rather than finding the file for the tag-link, and using the backlinks view to satisfy the query.

A reinterpretation of the feature request could be to write a completion window for the backlinks that satisfy matching links for a given input, which should be generally more useful and would take advantage of prior features (like the database).

**Comment by bdarcus** [comment]
That seems helpful.

Maybe (thinking ahead to documentation, if this is approved), some
examples would help?

Right now, we have two types of notes: the default, and bibliographic.

And we have two link types based on those: default, and citations.

So examples of where to use these new tags, and where not?

**Comment by zaeph** [comment]
There's definitely something to do with tags.  I'm scheduling this for next week, but I think it's lower priority than #531.

**Comment by Wetlize** [comment]
I've updated a bit the initial post, but I'm having difficulties right now to explain better use cases (it kind of feels like explaining to someone what and why you need metaprogramming).

> So examples of where to use these new tags, and where not?

Anytime when you not interacting with the org-roam buffer and you need to somehow narrow down to a specific set of notes based on other kind of metataxonomy. An easy example is when you insert links into the buffer (either with `company-mode` or `org-roam-insert` command) and you don't really remember which title you need to use; in such case in you can narrow to needed for you titles quickly using these tags.

> Not sure the "bib" example is quite right, given that we have bibliographic notes (those with the ROAM_KEY). Unless I'm just misunderstanding.

You cannot really know (unless you remember) if your note is bibliographical. `org-roam-find-ref` works over references, instead of titles. Right now you can only sort of do that by moving all your notes into something like `biblio` sub-directory and setting `org-roam-title-include-subdirs` to `t`, or by manually prefixing your titles.

**Comment by bdarcus** [comment]
> ... An easy example is when you insert links into the buffer (either with `company-mode` or `org-roam-insert` command) and you don't really remember which title you need to use; in such case in you can quickly narrow to needed for you titles using these tags.

OK, I see now. Thanks.

> > Not sure the "bib" example is quite right, given that we have bibliographic notes (those with the ROAM_KEY). Unless I'm just misunderstanding.
> 
> Base on titles, you cannot really know right now quickly (unless you remember or lookup) whether your note is bibliographical or not. 

But this is a UI problem; no? We don't need tags to solve that particular issue, though I can imagine they may help.

**Comment by Wetlize** [comment]
> But this is a UI problem; no? We don't need tags to solve that particular issue, though I can imagine they may help.

Well, tags tags
You kind of do when you need to know if its say a combination of tags, like `bib`, `inbox` and `
 We don't need tags to solve that particular issue, though I can imagine they may help.

**Comment by Wetlize** [comment]
*^^^ a miss click, sorry*

> But this is a UI problem; no? We don't need tags to solve that particular issue, though I can imagine they may help.

You can easily replace `bib` with any other kind of tag (or their combination), so I don't really see a problem here. I'll try to add some more examples later (there's already some others in the initial post), but no promises.

**Comment by bdarcus** [comment]
> I feel like what supplied right now in this whole thread is enough to communicate about tags at the issue level.

I agree, and support this FR. Thanks.

The broader question of zettekasten, structure, and tags is discussed in [this post](https://zettelkasten.de/posts/three-layers-structure-zettelkasten/).

**Comment by edumerco** [comment]
Some comments, that may be included in the previous discussion but I'd prefer to make them explicit from a User point of view... I hope it's not futile or bothersome. :)

> [...] Such tags provide more value at a meta level instead. For example, they can be utilized by the graph, completion system in Emacs, and exporting and publishing systems.

And filtering too. I may like to slice the network of notes (notework? netes?) to only books (one specific facet-type value), and tags can help to do exactly that. In this regard, we could also harness the org-mode agenda power to search and filter (with or without a structured UI to help with the facet slicing), just as other properties could do so too. If a note is marked as pertinent to a category (or more than one), isn't that like an implicit link?

In traditional wiki working style there are reserved keywords for links that act as such, and there is a lot to learn from them since that discussion has been going for a lot of time. For example, the classic (configurable) "Category" prefix allows to relate things to one or more groups. While they are usually added to the end, there is really no need to do so, as we could easily write "This work is part of the honored [CategoryDesignFiction|design fiction] growing body of..." integrating both human meaning with a precise grouping. This is already implied in...

> [...] Automatically turn filenames that have specific filename pattern into tags, e.g. files that have name tag_foo.org would return foo tag.

In wikis this is done because there are (usually) no typed links. But org-mode has a powerful system already included and working: tags and properties. Let's use them. ;)

Also, in the graph, we may format books with a different style that idea notes, or movies or persons (i.e. everything that belongs to the CategoryDesignFiction has a light blue background and uses a circle instead of a rectangle). Surely, it involves more complexity than what is seen at first sight, like what about belonging to more than one category, but we can see that when it arrives.

**Comment by nivekuil** [comment]
A tag is simply a generic relation between notes with no further semantics.
Instead, what I would like to see is a `key: value` system, or more specifically, `relation: links`.
This would be a superset of tag functionality, as tags could be denoted as `tagged: [[thing1]] [[thing2]]`.
But personally, what I would use this for is to make those relations more specific, e.g. `expands: [[original-thought]]`, `depends-on: [[earlier-claim]]`.
This could be a way to make arbitrarily rich relations, including hierarchies (which Luhmann himself employed, and I don't think is cleanly doable in `org-roam` today).

**Comment by jethrokuan** [comment]
Just popping in to say I do see value in supporting tags, and the original proposed implementation seems like the right direction.

**Comment by bdarcus** [comment]
> A tag is simply a generic relation between notes with no further semantics.

I'm confused. Isn't a tag on the note, so is not about relations at all?

And links are the relations?

As in, conceptually, two kinds of tags: objects (notes), and relations (links).

But the subject of this FR is the former (though I think maybe we want both).

**Comment by edumerco** [comment]
> As in, conceptually, two kinds of tags: objects (notes), and relations (links).

Tags create an implicit link (as I understand it), so in this conception, they create a relation.

**Comment by edumerco** [comment]
> [...] what I would like to see is a `key: value` system, or more specifically, `relation: links`. [...]
> But personally, what I would use this for is to make those relations more specific, e.g. `expands: [[original-thought]]`, `depends-on: [[earlier-claim]]`. [...]

Those key:value tags would be typed links in hypertext theory. 
Tags alone would be typed nodes. 
Both are useful and powerful, and we should discuss how we'd like to use them. 

The only danger I see ahead with this is to reinvent the wheel (at least, in the hypertext domain). These discussions where carried a long time ago, and some solid systems (as Mediawiki) have emerged from them. 

Please, I'm not saying that we shouldn't do that at all: just that we should learn from what was done before. :smirk:

**Comment by nivekuil** [comment]
> > A tag is simply a generic relation between notes with no further semantics.
> 
> I'm confused. Isn't a tag on the note, so is not about relations at all?
> 
> And links are the relations?
> 
> As in, conceptually, two kinds of tags: objects (notes), and relations (links).
> 
> But the subject of this FR is the former (though I think maybe we want both).

The benefit of my proposal is we don't have to have both.

As I understand it this proposal would move away from "every node is an org file, and every edge is an org link". I like the simplicity of the current ontology, and I believe that we could more elegantly and powerfully achieve explicit tagging functionality within it by being able to assign a "type" to links to further describe the nature of its relation.  So instead of having an `org-roam-tag` concept (which I think would be confusing if distinct from vanilla org tags), we stay within vanilla org-mode as much as possible: a tag is still just a link to a (likely) empty file.

While the actual tag itself would still be some empty `tag.org` file, some other `note.org` would specify that it wants its relation to `tag.org` to be of type `tagged`. This would be like a labeled edge on the `org-roam-graph`. 

> Those key:value tags would be typed links in hypertext theory.

Interesting! I was circling around this sort of terminology: https://en.wikipedia.org/wiki/Link_relation, although it doesn't seem to be academic.

**Comment by Wetlize** [comment]
@nivekuil The proposed implementation already allows you to do what you're describing (if you would need that), see "Assignment of tags" section. It also allows different kind of workflows (which I personally prefer myself, so might be other people too) that you would be able to select yourself. You would also be able to program your own ways of how tags would be polluted and combine it with other methods.

**Comment by kbruskiewicz** [comment]
I agree with @nivekuil, the value in the way `org-roam` does things is that using links to organize is simple, and supports a workflow that other notetaking strategies tend to overlook, i.e. bottom-up associations and clustering.

Using links as tags is not incompatible with this, which makes adding first-class tags redundant. But adding metadata to links with a header doesn't oppose any existing system while being consistent with using links. And adding a completion view to search backlinks on header-link is also generally valuable as well.

If you want a diversity of linking types with first-class support there's always `org-brain`.

**Comment by Wetlize** [comment]
OK, so to clarify what's being proposed by @nivekuil. You would only have have normal org-roam links across files, but instead they would be specially prefixed in a way that org-roam would be able to recognize as metadata, e.g. `inbox:[[path][description]]`, would form a backlink in the `description` and in the database `path` would receive `inbox` as tag. Am I following this right?

**Comment by Wetlize** [comment]
Okay, I thing I've got it, you want something that would store keys along with values, where value is a backlink and key is an arbitrary construct, like `depends-on`, instead of just a list of tags without any relations.

**Comment by nivekuil** [comment]
> OK, so to clarify what's being proposed by @nivekuil. You would only have have normal org-roam links across files, but instead they would be specially prefixed in a way that org-roam would be able to recognize as metadata, e.g. `inbox:[[path][description]]`, would form a backlink and in the database `path` would receive `inbox` as tag. Am I following this right?

I don't think so; it would be more like `tagged:[[./tag/inbox.org][inbox]]`, probably at the top of your file like what Jethro does in his gifs.

**Comment by Wetlize** [comment]
> it would be more like tagged:[[./tag/inbox.org][inbox]]

Thanks, this clarified for me how all this would look like even better. I somehow skipped over my head some parts of your posts, but now they are clear to me.

I didn't think much previously about what tags are from the graph's perspective and with the proposed implementation they suppose to end-up either, invisible on it or represented as another set of nodes.

Now, when I spent some time digesting this and thinking about all kind of workflows and how it would end-up integrate with org-roam, I've concluded that I do like @nivekuil's idea of having explicit arbitrary relations between notes and how they can be automatically represented as labels for edges on the graph, that's definitely useful and unlocks more interactivity with graphs, plus connections end-up more clear.

However, right now I cannot really conclude whether explicitly defined relations conflict somehow with the the proposed idea of tags, and whether they end-up in all kind of useful situations less powerful than explicitly defined key-value relations. `Key: value` relations are explicit and obvious (no wonder, since they are just metadata for links), while tags that I propose form implicit kind of relations, that are not obvious. As for now, they look to me more like a 2 different things that intersect over each other, just how it [mentioned](https://github.com/org-roam/org-roam/issues/572#issuecomment-625889603) by @edumerco. Within this intersected space there's also have to be trade-offs, that I cannot clearly see at the moment fully.

I would like to see other people thoughts on this, and what people who actually maintain org-roam (@jethrokuan, @zaeph) think of all this (don't rush yourself though).

**Comment by nivekuil** [comment]
> However, right now I cannot really conclude whether explicitly defined relations conflict somehow with the the proposed idea of tags, and whether they end-up in all kind of useful situations less optimal than explicitly defined key-value relations.

I do think that key-value relations are a superset of bare tags in terms of expressiveness. 
If you are using a `tagged` key, where `tagged` denotes an implicit relationship, then you are *explicitly* declaring an *implicit* relationship.
If all you want to do is declare *implicitly* declare *implicit* relationships between nodes, then the explicit approach is less optimal (more complex). But this functionality is already part of org-roam in the form of backlinks.

If we limit ourselves to only such a `tagged` key, then the additional expressiveness from the `key:value` system is the same as the tag system.  In such a system, we can *explicitly* declare *implicit* relationships with tags, as well as *implicitly* declare *implicit* relationships with backlinks.

However, what I want to do is be able to *explicitly* declare *all sorts of* relationships, where *all sorts of* is the set of `key`s in the roam.

> As for now, just how it mentioned by @edumerco, they look to me more like a 2 different things that partially intersect over each other. Within this intersected space there's also have to be trade-offs, that I cannot clearly see at the moment completely.

With the qualification that I am not familiar with hypertext theory, going off http://paul.luon.net/hypermedia/chapter1/intro/nodesLinks.html as the source for understanding *typed nodes* which correspond to your concept of tags (they give as examples: detail, proposition, collection, summary, observation, issue), I don't think there is a conceptual tradeoff.  If I wanted to classify a note in the `key:value` system with any of those, I might choose to use an `instance-of` key which I link to `./tag/detail.org`, `./tag/proposition.org`, etc.  There's probably a performance tradeoff in an actual hypertext system, though.

**Comment by zaeph** [comment]
> It would be interesting to see some other thoughts on all this, especially (eventually) thoughts of [people](https://github.com/orgs/org-roam/people) who actually responsible for org-roam.

Just a quick message to reiterate that I'll start working on this by the end of next week.  Haven't had the time to follow the conversation here, but I will in due time.

**Comment by Wetlize** [comment]
I still feel like we need both, tags and explicit relations. There's value in pure implicitness from the perspective of how you can automate it, and it requires far more less effort to manage it. If we would have both, then I don't think it also would be difficult to make tags cast specific kind of relations, that you would define yourself automatically; if tags' would not specify any relations in them, than it would always would be assumed as an implicitly `tagged` relation. Additionally people would be able to freely pick what they need in their workflow.

I cannot also imagine how would you use (and implement) efficiently explicit relations in something like completion window for further narrowing, though I can imagine this with grep, the org-roam buffer and graphs. For the completion window though, if we would only stick with explicit relations without any tags, it would be difficult to hit properly balance between efficient implementation and UI overloading.

I think we should defer the decision to people who will be implementing all this, though anyone feel free to post your further thoughts on all this.

**Comment by wakatara** [comment]
I have to admit I was going or ask for this feature myself but I was thinking of it as much ore in lie with the way the current Roam wiki product utilizes tags. Basically, they create a "auto-page" where anything tagged is listed with some context (it's a kickass feature actually and unlocks a lot of power for org-roam, I believe). (for example, tagging something with `:projects:` would yield an automatic Projects page etc. 

Can I just ask for a more explicit explanation of the proposed implementation. I was unsure from the comments whether that had been sussed, or whether it was still under discussion. Apologies if this is clear to everyone but me...).

**Comment by zaeph** [comment]
> Can I just ask for a more explicit explanation of the proposed implementation. I was unsure from the comments whether that had been sussed, or whether it was still under discussion. Apologies if this is clear to everyone but me...).

The implementation is detailed in #604.

**Comment by bdarcus** [comment]
The PR could be extended to allow creation of tag/index.org files (aka auto structure notes for tags), but seems that would take more thought and discussion?

But I do think it looks good as a starting point.

**Comment by jethrokuan** [comment]
I think tags have been largely covered by #604 , feel free to reopen or create a new issue if there are more asks.
