### ISSUE TITLE
File not found error when installing org-roam

### ISSUE THREAD

**Issue by spilornis** [org-roam/org-roam#582]
### Description
I get following error message when trying to install org-roam:
    Debugger entered--Lisp error: (file-error "https://melpa.org/packages/org-roam-20200425.1053.tar" "Not found")

#### Steps to Reproduce
Run `package-install` and enter org-roam.

### Versions
- Emacs (`C-h v emacs-version`): v26.3

**Comment by jethrokuan** [comment]
You'll need to update your mirror first, with `package-refresh-contents` before trying again.

**Comment by aaaron** [comment]
What's in your MELPA install [docs](https://www.orgroam.com/manual/Installing-from-MELPA.html#Installing-from-MELPA) didn't work for me (no match error), unless I added:
 
(package-initialize)
