### ISSUE TITLE
org-capture-set-target-location: Invalid capture target specification: nil

### ISSUE THREAD

**Issue by BrettWitty** [org-roam/org-roam#583]
### Description

Using the standard `org-mode` hierarchical capture templates doesn't appear to work in `org-roam`.

#### Steps to Reproduce

1. Customize `org-roam-capture-templates` as per normal but with the two-element tree variant.

```elisp
(setq org-roam-capture-templates
      '(
        ("i" "Inbox" plain (function org-roam--capture-get-point) "%?" :file-name "${slug}" :head "#+TITLE: ${title}")
        ("p" "Projects")
        ("pa" "Project A" plain (function org-roam--capture-get-point) "%?" :file-name "a/${slug}" :head "#+TITLE: ${title}")
        ("pb" "Project B" plain (function org-roam--capture-get-point) "%?" :file-name "b/${slug}" :head "#+TITLE: ${title}")
        ("pc" "Project C" plain (function org-roam--capture-get-point) "%?" :file-name "c/${slug}" :head "#+TITLE: ${title}")
        ))
```

2. Run `org-roam-find-file`.
3. Insert any new title.
4. Select a capture template:
```
Select a capture template
=======================

[i]     Inbox
[p]     Projects
------------------------------------------------------------------
[C]     Customize org-capture-templates
[q]     Abort
```
5. Select `p` for menu

#### Expected Results

Expecting `p...` in the menu rather than just `p`, and then being able to select a, b or c from there.

#### Actual Results

Get error `org-capture-set-target-location: Invalid capture target specification: nil`.

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam version: 20200507.1838 from MELPA

**Comment by zaeph** [comment]
I can reproduce this.

It's probably because we haven't foreseen this case when we created the expansion for `org-roam-capture-templates`.  Fixing should be trivial, hopefully.

**Comment by zaeph** [comment]
`org-roam-capture--convert-template` is definitely the culprit:
https://github.com/jethrokuan/org-roam/blob/c1bfa99aced79f2e122ededc9e2e5b6636e836fd/org-roam-capture.el#L280-L298
