### ISSUE TITLE
peculiar error: "UNIQUE constraint failed: refs.ref"

### ISSUE THREAD

**Issue by leonhandreke** [org-roam/org-roam#585]
#### Steps to Reproduce

Probably only on my machine with my database, but:

1. org-roam-insert
2. In the capture buffer, finish with C-c C-c.
3. New title does not get inserted at the previous location and the error `peculiar error: "UNIQUE constraint failed: refs.ref"` shows up. However, the new note is created, and when triggering org-roam-insert again and selecting the note in the list, the link is inserted as expected.

I'm happy to help debugging, but I have no experience with emacs/elisp etc. I use ROAM_ALIAS quite a bit, maybe I have a duplicate entry there?

### Versions
- Emacs (`C-h v emacs-version`): 28.0.50
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/d0f5477c323ef6600e29d22b75d876c49916b3f4 (I pulled this from `~/.emacs.d/.cache/quelpa/build`, I hope that's correct)

**Comment by zaeph** [comment]
This is probably because you already have a note in your `org-roam-directory` which has the same `#+ROAM_KEY:`.  You could run `M-x org-roam-find-ref` and look for that citekey to make sure.

**Comment by leonhandreke** [comment]
Ah, I see. I had an empty `#+ROAM_KEY:` in my template, hoping that it would save me from typing it manually when I create a new "something I've read" note and would do nothing if I didn't fill it in.

I understand that this is may be a weird usecase. I'll leave it to you to decide whether this is a bug or improvement to make or to just close this bug. Thanks for your help!

**Comment by zaeph** [comment]
> Ah, I see. I had an empty `#+ROAM_KEY:` in my template, hoping that it would save me from typing it manually when I create a new "something I've read" note and would do nothing if I didn't fill it in.
> 
> I understand that this is may be a weird usecase. I'll leave it to you to decide whether this is a bug or improvement to make or to just close this bug. Thanks for your help!

I agree that we could do a better job about either not getting the ref if it's empty _or_ providing a more informative error-message.
