### ISSUE TITLE
Option to remove one-file-one-citation workflow

### ISSUE THREAD

**Issue by stites** [org-roam/org-roam#587]
### Brief Abstract
The current org-roam workflow preferences one-file / one-citation workflow. This workflow is a little prescriptive and users should have the ability to opt-out if they want to work with more atomic notes with the same ROAM_KEY. 
 
### Long Description
I am transitioning a backlog of a physical zettelkasten which worked under the principle that each index card is a stand-alone idea or thought. This idea conflicts with the 1-1 note-to-citation correspondence (you can't fit a textbook in a 6x4" card!). In org-roam, I believe this workflow resembles an [ORB-based workflow](https://github.com/zaeph/org-roam-bibtex) using [structure notes for each reference](https://zettelkasten.de/posts/three-layers-structure-zettelkasten/).

I'm of the opinion that there are some benefits to this level of granularity. One motivating example might be starting with the note "theorem 1 from textbook A" which is linked to several papers. At some later point I might update this note so that the reference has better provenance. With the proposed workflow I would not have to update any linked documents and can do the same with other theorems in the textbook.

A potential pain point of this workflow is that atomic notes might require more context from the original reference via a page-number ([a la org-ref support](https://www.reddit.com/r/orgmode/comments/90sk11/how_do_you_cite_pages_for_quotes_with_orgref/e2tckcu/)) -- this is considered out-of-scope.

### Proposed Implementation (if any)
Proposed by @zaeph, this feature would be flagged by a variable that would remove the UNIQUE key constraint in the refs.ref table. This would require a user to clear and rebuild their current DB cache. ref-backlinks would also have to be deduped via data structure (ie: use a set) or algorithmically. 

### Similar requests
- #585 is the expected error you would see if you do not adhere to the one-note/one-reference rule.

**Comment by zaeph** [comment]
Thanks for filing the issue.

Implementing this in a sensible way would also imply to modify existing commands acting on refs.  For instance, `org-roam-find-ref` should be a two-step completion: 1) the current behaviour of picking the `ROAM_KEY`, then 2) completion with the titles of all the entries which have that ROAM_KEY.  Note that this behaviour should also be used by `org-ref` when opening a link.

Cite-backlinks should be all right, with probably just an adjustment in the way they're constructed in the `org-roam-buffer`.

However, this seems to be the tip of the iceberg, and I expect plenty of things to go wrong along the way.  I'm setting a low priority on this, and I don't expect to get back to it within the fortnight, but if anyone wants to tackle it, please do.

**Comment by jethrokuan** [comment]
Yeah I don't think there needs to be a hard constraint on refs being unique. Now's also probably a good time to visit the one-ref-per-file constraint we're placing at the moment.

**Comment by Wetlize** [comment]
Would it also make sense then to automatically connect all backlinks with the same `#+ROAM_KEY`? In the org-roam buffer they would be hidden behind their own heading.

**Comment by zaeph** [comment]
> Would it also make sense then to automatically connect all backlinks with the same `#+ROAM_KEY`? In the org-roam buffer they would be hidden behind their own heading.

Yes.  I believe this is something that I've mentioned somewhere, although I can't remember if it was here, on Discourse, or on Slack.  But the idea would be to list all the files which have the same `#+ROAM_KEY` under a same heading.  Now that we've separated `type` and `ref`, we might also be able to provide ref-backlinks, i.e., a superset of cite-backlinks with more control.

Along with #588, this it the type of discussion we'll need to have when we get to revamping the `org-roam-buffer`.

**Comment by stites** [comment]
I think the originally proposed "break UNIQUE constraint on refs.ref" isn't necessary, it's really just a quick hack to get my personal workflow less angry with the initial org-roam workflow. That said, I expect maintaining UNIQUE on refs.ref would require a major overhaul of the codebase, switching a lot of the API to work over lists, querying SQL in a different manner, and possibly treating singleton lists in a special manner.

I'm not sure of the scope of either change. If they are comparable, it seems like keeping UNIQUE would be the better solution.

**Comment by jethrokuan** [comment]
There aren't anymore unique constraints in the db, this should work now.
