### ISSUE TITLE
(docs) Update documentation on installation for Spacemacs

### ISSUE THREAD

**Issue by ISTTeo** [org-roam/org-roam#590]
### Description
Following the tutorial in [the documentation for the Spacemacs installation](https://org-roam.readthedocs.io/en/develop/installation/) does not work because it cannot get to the repository.
#### Steps to Reproduce

![image](https://user-images.githubusercontent.com/26068276/81487555-2f804680-9256-11ea-93d8-97bfed32cbb9.png)

To be able to install I changed it to:

`(recipe :fetcher github :repo "org-roam/org-roam" :branch "master"))))`

**Comment by zaeph** [comment]
Thanks!

**Comment by jethrokuan** [comment]
That's actually because the link you're at is for the develop branch, which is long gone.

**Comment by zaeph** [comment]
> That's actually because the link you're at is for the develop branch, which is long gone.

Heh, hadn't even noticed the branch!

Also, `jethrokuan/org-roam` will redirect to `org-roam/org-roam` as long as you don't fork the repo.  If you do, #591 should take care of this problem for newcommers, but it might cause weird problems for old users who would be unaware, so let's keep an eye out for those.
