### ISSUE TITLE
Issue with nested org-roam capture processes and org-roam-capture--get-point

### ISSUE THREAD

**Issue by nathanaelbosch** [org-roam/org-roam#594]
### Description
Org-roam is unusable after a first `org-roam-find-file` to a new file, due to problems with nested org-roam processes. `:immediate-finish t` does not fix this issue. 
I encountered the following suspicious message in the messages buffer, which appears on the first `org-roam-find-file`:
```
f-expand: Wrong type argument: stringp, org-roam-capture--get-point
```

#### Steps to Reproduce
1. Load Emacs.
2. Run `org-roam-find-file` or `org-roam-insert` and create a new file; This also creates the `f-expand` message.
3. Try to run `org-roam-find-file` or `org-roam-insert`, again to create a new file. This does then not work and states "Nested Org-roam capture processes not supported".

#### Expected Results
Create another new org-roam file, and insert the corresponding link.

#### Actual Results
Does not create a new file, does not insert the link. 
Additionally, the following message appears during the **first** `org-roam-find-file`:
```
f-expand: Wrong type argument: stringp, org-roam-capture--get-point
```

### Versions
- Emacs (`C-h v emacs-version`): 26.3
- `spacemacs-version`: 0.300.0
- Org-roam is installed as described [on the official website](https://org-roam.readthedocs.io/en/master/installation/)

**Comment by zaeph** [comment]
> This does then not work and states "Nested Org-roam capture processes not supported".

This is an expected limitation of the package which we are going to address in #527.

> f-expand: Wrong type argument: stringp, org-roam-capture--get-point

First things first, try rebuilding your database with `C-u M-x org-roam-db-build-cache`.  If that doesn't do it, I suspect the problem might be coming from your `org-roam-capture-templates`, which I would encourage you to paste here for debugging.

**Comment by nathanaelbosch** [comment]
1. `org-roam-db-build-cache` did not fix things
2. In the meantime, I also tried to change my org-roam installation: I just declared `org-roam` in `dotspacemacs-additional-packages` (basically the spacemacs way of installing packages that are not in a layer), instead of creating my own layer as instructed on the homepage. This does not fix the problem and I still have the same error as before.
3. I removed my `org-roam-capture-templates`. The error still persists, even when I close the captures with `C-c C-c`.

The template I had before was:
```
  (setq org-roam-capture-templates
        '(("d" "default" plain (function org-roam-capture--get-point)
           "%?"
           :file-name "%<%Y-%m-%d-%H%M>-${slug}"
           :head "#+TITLE: ${title}\n- tags :: \n"
           :unnarrowed t
           :immediate-finish t
           ))
        )
```

**Comment by zaeph** [comment]
Does it work without `:immediate-finish t`?

**Comment by progfolio** [comment]
@nathanaelbosch: Can you `M-x toggle-debug-on-error`, execute behavior that triggers the error and paste a copy of the backtrace from the debugger?

**Comment by nathanaelbosch** [comment]
> Does it work without `:immediate-finish t`?

Without my own personal `org-roam-capture-templates` there is no `:immediate-finish t`, and the error still persists.

**Comment by nathanaelbosch** [comment]
> @nathanaelbosch: Can you `M-x toggle-debug-on-error`, execute behavior that triggers the error, and paste a copy of the backtrace from the debugger?

Thank you very much for this hint! **I managed to fix the issue!**

The during the first `org-roam-insert` was:
```
Debugger entered--Lisp error: (wrong-type-argument stringp org-roam-capture--get-point)
  expand-file-name(org-roam-capture--get-point nil)
  f-expand(org-roam-capture--get-point)
  (and cal-files (f-expand (car (cdr (org-capture-get :target)))))
  (let* ((cal-files (and t (mapcar (quote f-expand) (mapcar (quote cdr) org-gcal-file-alist)))) (capture-target (and cal-files (f-expand (car (cdr (org-capture-get :target)))))) (cal-file-exists (and capture-target (and (mapcar (quote f-file\?) cal-files)))) (capture-target-isfile (and cal-file-exists (eq (car (org-capture-get :target)) (quote file)))) (capture-target-is-cal-file (and capture-target-isfile (member capture-target cal-files)))) (if capture-target-is-cal-file (progn (org-gcal-refresh-token) (org-gcal-post-at-point)) nil))
  google-calendar/sync-cal-after-capture()
  run-hooks(org-capture-after-finalize-hook)
  org-capture-finalize(nil)
  funcall-interactively(org-capture-finalize nil)
  call-interactively(org-capture-finalize nil nil)
  command-execute(org-capture-finalize)
```

Removing the `google-calendar` layer fixed the issue. Without it, the debugger did not complain during the first `org-roam-insert` and I could capture multiple new files, as expected.

I will try to make things work with `google-calendar`, since I ideally would like to use it. Any suggestions are welcome!

**Comment by zaeph** [comment]
> Removing the `google-calendar` layer fixed the issue. Without it, the debugger did not complain during the first `org-roam-insert` and I could capture multiple new files, as expected.
> 
> I will try to make things work with `google-calendar`, since I ideally would like to use it. Any suggestions are welcome!

Judging by what I see from the backtrace, you need to investigate if `google-calendar/sync-cal-after-capture` does anything funky with `point`, i.e., where the cursor is.  Wrapping everything in a `save-excursion` should resolve this.

**Comment by jethrokuan** [comment]
I think the `google-calendar` layer is expecting the target to be a file, and not a function, which org-capture supports. This should probably be raised upstream to `google-calendar`, as that assumption may not always be true.
