### ISSUE TITLE
New auto-saved files do not show up in the org-roam-find-file dialog box, only if I manually save them do they appear. 

### ISSUE THREAD

**Issue by Wathiq60** [org-roam/org-roam#596]

**Comment by zaeph** [comment]
If you mean that, when capturing, the file is not saved as soon as the template is expanded, it's to avoid creating the file which would then be deleted.  The best thing to do in that scenario would be to have `:immediate-finish t` in a template in `org-roam-capture-templates` to immediately confirm the capture.

**Comment by progfolio** [comment]
May also be referring to `auto-save-mode`, which IIRC does not trigger `after-save-hook`. There is an `auto-save-hook`, but I don't know if it would be appropriate to hook into. Auto-saves are separate temp files that are flushed when an actual save is performed.

**Comment by Wathiq60** [comment]
I press `C-c C-c` to capture the buffer and I am using this option `(setq auto-save-visited-file-name t)` where the auto-saved files (every 2 milliseconds) automatically get written to the actual file. If the file gets saved automatically, it does not show up in the org-roam-find-file dialog box. If I go back to the file and manually save it with `C-x C-s` it shows up.

**Comment by Wathiq60** [comment]
Never mind, It works perfectly with `:immediate-finish t`

Thank you so much!
