### ISSUE TITLE
org-roam-jump-to-index not working properly

### ISSUE THREAD

**Issue by zoechi** [org-roam/org-roam#597]
#### Steps to Reproduce
1. Basic org-roam settings:
```lisp
(setq org-roam-directory "~/source/Org/Roam" 
          org-roam-index-file "index.org")
```

2. `M-x` `org-roam-jump-to-index`

>   Would you like to create it? (y or n)
Enter "y", press `C-c C-c`

- Close buffer

3. `M-x` `org-roam-jump-to-index`

>   Would you like to create it? (y or n)

#### Expected Results
The 2nd time around the file should be found. It exists, it's placed in `~/source/Org/Roam/index.org`

It can be found with `M-x` `org-roam-find-file` `Index`

#### Actual Results
I get told the file does not exist yet sand needs to be created every time.

### Versions
- Emacs (`C-h v emacs-version`): 28.0.50

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere
Don't know how to get that easily.
I use straight.el with use-package and there are created several directories in various places for each package.
In `~/.config/emacs/elpa/` it shows `org-roam-20200510.2317`

**Comment by zaeph** [comment]
On it.

**Comment by zaeph** [comment]
Ah, you're write: it's because it's not naming the file properly.  We need to enforce a custom capture-template.  It's a quick fix-up, I'll do that now.

**Comment by zoechi** [comment]
Are there awards for fastest response to bug reports? :rocket:

**Comment by zaeph** [comment]
> Are there awards for fastest response to bug reports? rocket

No, but there's a _Sponsor_ button next to my name. 🤡

**Comment by zoechi** [comment]
I'd happily pay you some, but I'd never make a recurring subscription. Looks to me there is no option for one-time payments.
Are there other ways?

**Comment by zaeph** [comment]
> I'd happily pay you some, but I'd never make a recurring subscription. Looks to me there is no option for one-time payments.

I was just kidding, don't worry!

> Are there other ways?

Not right now, but there might be in the future if people show interest.

**Comment by zoechi** [comment]
> I was just kidding, don't worry!

No need to kid about that. You're doing a great job.
I'm definitely interested.

**Comment by zoechi** [comment]
Setting the full path seems to work
```lisp
(setq org-roam-index-file "~/source/Org/Roam/index.org")
```

**Comment by zaeph** [comment]
> I'm definitely interested.

Well, it was definitely trivial to create a [paypal.me](https://www.paypal.me/zaeph) link, so feel free to use that.

Now, back to troubleshooting.

> Setting the full path seems to work

It's expected to, but there's a better solution that would use our internals to create the file.

**Comment by zoechi** [comment]
Just to be sure:

If the path is relative (as in my original post) and the file exists with `#+TITLE: Index` it still asks about creating the file.  
When the path is absolute, it just opens the file as expected.

Also if it suggests to create the file, it probably should not create it using the usual pattern with date and time prefix (as it did for me).

**Comment by zaeph** [comment]
Your assumptions are correct, and this is exactly what we are addressing in #600.  We've cornered the problem, but it's made us realise that there were other problems with the way we matched files, cf. #601.

We'll fix it soon.

(Also, thanks for your donation!  You're the first person ever to give me money for writing code, and honestly, it makes me feel quite fuzzy inside.)

**Comment by zoechi** [comment]
> You're the first person ever to give me money for writing code

Keep up your great work and it will become common :rocket:

**Comment by anildigital** [comment]
This doesn't work
```(use-package org-roam
  :ensure t
  :hook
  (after-init . org-roam-mode)
  :custom
  (org-roam-directory "~/org")
  (org-roam-index-file "index.org")
```

But this does 

```
(use-package org-roam
  :ensure t
  :hook
  (after-init . org-roam-mode)
  :custom
  (org-roam-directory "~/org")
  (org-roam-index-file "~/org/index.org")
```

Context
```
- Emacs: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, NS appkit-1894.40 Version 10.15.4 (Build 19E287))
 of 2020-05-14
- Framework: N/A
- Org: Org mode version 9.3 (release_9.3 @ /usr/local/Cellar/emacs-plus/HEAD-747e0a2/share/emacs/27.0.91/lisp/org/)
- Org-roam: 1.2.0
```

**Comment by jkaye2012** [comment]
Same for me as for @anildigital

**Comment by jethrokuan** [comment]
Index-file related stuff is removed now.

**Comment by listx** [comment]
> Index-file related stuff is removed now.

@jethrokuan I am currently running `(org-roam-node-find nil "Index")` but it forces me to press `<return>` again to actually select and visit the first candidate. Is there some way to automate away the need to press `<return>` so that it just visits the first candidate in the prompt?

**Comment by jethrokuan** [comment]
@listx You can use this instead:

```
(defun my/visit-org-roam-index ()
  (interactive)
  (org-roam-node-visit
   (org-roam-node-from-id
    (caar (or (org-roam-db-query [:select id :from nodes :where (= title "Index") :limit 1])
              (user-error "No node with title Index"))))))
```
