### ISSUE TITLE
documenting "bibliographic notes" and "structure notes"

### ISSUE THREAD

**Issue by bdarcus** [org-roam/org-roam#603]
I'm not really sure where this should go (likely early on; we really need something like [this](https://zettelkasten.de/posts/overview/)), but it occurs to me it would help if we introduced these concepts explicitly in the documentation somewhere, in part to better clarify details in other places. 

Strawman fragments.

> ## Bibliographic Notes
> 
> Bibliographic notes are notes about a reference source, and are designated with a `#+ROAM_KEY` in the document header. Notes that cite these references will then display in the cite backlinks. The [org-roam-bibtex package](https://github.com/org-roam/org-roam) is designed to optimize bibliographic note-taking in org-roam.

... and:

> ## Structure Notes
> 
> Generally, notes should be fairly focused expressions of ideas. But you can also add more elaborate and structured notes to bundle together and sequence a set of more focused notes by using what are often referred to as [structure notes](https://zettelkasten.de/posts/three-layers-structure-zettelkasten/).

... and then under "index note" (what I mean by "detail in other places" above):

> Org-Roam reserves an index.org file as a master structure note, to provide the highest level entry intro your note system.

**Comment by bdarcus** [comment]
Thinking more about this, and documentation more generally, it strikes me we have a few different non-exclusive groups of users that have emerged:

1. experienced org and emacs users, wanting to enhance note-taking
2. Roam users looking for an open source alternative
3. zettelkasten users, interested in another approach 

It seems we need documentation that works for at least all three of them; that points 1 (and 2) to the principles behind that zettelkasten, and how org-roam implements them, and for 2 and 3 how org-roam extends emacs and org.

My issue here is really focused on the former.

**Comment by jethrokuan** [comment]
I'd like to also have a short introduction to the zettelkasten method as part of the manual, right after the introduction most likely. This is to set the scene and help readers make sense of the manual.

**Comment by bdarcus** [comment]
Yes, makes sense.
