### ISSUE TITLE
Developer coding standards.

### ISSUE THREAD

**Issue by progfolio** [org-roam/org-roam#605]
I'm not proposing anything overly formal, but we should automate some of the simple settings for an agreed upon style standard for the code base. We could implement this in a module that is loaded when the source files are edited.

**Comment by progfolio** [comment]
Leaving this open for now if anyone else has suggestions for what sort of standards we could/should automate.

**Comment by jethrokuan** [comment]
I think we've got a good thing going here, that we can add to later if need be. Closing until something else pops up.
