### ISSUE TITLE
*org-roam* buffer not overlaying link text

### ISSUE THREAD

**Issue by titaniumbones** [org-roam/org-roam#610]
### Description

Rather than displaying a compact list of backlinks, the `*org-roam*` buffer displays a list of send-level headlines with the full link text exposed.
#### Steps to Reproduce

1. Load Emacs and org-roam
2. Open a note with `C-c n f`
3. Open the org-roam buffer with `org-roam-buffer-toggle-display`

#### Expected Results
`*org-roam*` buffer should display links compactly, rather than expanding full text of link syntax

#### Actual Results
full link syntax is visible

### Versions
- Emacs  28.0.50
- Org-roam: 20200510.2117 (MELPA)

doubtless I should provide some more information -- if you can let me know what is needed I will add it to this description. 

Screenshot of the issue
![Screenshot of the issue](https://user-images.githubusercontent.com/364340/81768166-533acb00-94a8-11ea-9b13-d3a946050203.png)
r

**Comment by jethrokuan** [comment]
What version of `org` are you on? looks like an issue with `org-link-set-parameters`.

**Comment by asheidan** [comment]
I had the same issue with the org package i previously installed from Melpa (`org-20171205`).

When using the stable package available from gnu (9.3.6) it looks like it should.

**Comment by zaeph** [comment]
`org-20171205` is a version of org from `2017-12-05`, which is quite old.

You might want to update it and try again.

**Comment by titaniumbones** [comment]
ouch, it was an ancient git version (december). updated & ran `org-reload`, problem fixed.  thanks and sorry for the noise.
