### ISSUE TITLE
[RFC] Rethinking testing org-roam

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam#614]
Right now tests are feeling very brittle, and I'd like to rethink the approach towards testing org-roam functionality. 

The fundamental difficulty with testing org-roam is that it's a highly interactive application, and the behaviour varies a lot based on customization options, and user input. Typically, what we want to do is to test *observable user behaviour*, which is the current approach taken. We simulate calls to interactive commands such as `org-roam-insert`, simulate user input, and test the expected result (changes in buffer-string etc.)

While working on #604 , these tests broke, because vanilla Emacs completions require exact matching from user input from start to end. The proportion of users using vanilla Emacs completion is likely to be small, so we're actually testing for behaviour that few people will see. The alternative then is run these tests with other completion mechanisms such as `ivy` enabled, but that makes org-roam tests subject to upstream changes to the completion mechanisms, and less isolated, among other downsides.

This has also led to some neglect in adding tests into the test suite. For the large part, a lot of the functionality added has not been with new interactive commands: they have been small, incremental improvements to existing features. We need to pick up on these and start adding regression testing as org-roam grows more complex.

What I'm suggesting here may go against typical testing recommendations, but here's what I was thinking we should do:

1. Test the methods directly instead simulating. Add tests for all functions, even the low level ones. This gives us the confidence to modify their behaviour without causing regressions. 
2. Test the typical behaviour. The test org directory we currently have is extremely contrived, and does not represent the typical slip-box. The test directory should also serve as an example of what a slip-box should look like, guiding the use of org-roam.
3. Move the interactive tests and continue to run them, but allow CI to pass regardless of whether they pass or fail. They currently do not inspire much confidence.

**Comment by jethrokuan** [comment]
cc @progfolio @zaeph

**Comment by zaeph** [comment]
> This has also led to some neglect in adding tests into the test suite. For the large part, a lot of the functionality added has not been with new interactive commands: they have been small, incremental improvements to existing features. We need to pick up on these and start adding regression testing as org-roam grows more complex.

Sounds good to me, and I agree that now is perfect time to do this before the code-base grows to a hardly-manageable level.

I've got very little experience with testing besides a tryst with Org-mode's ERT facility, but I could learn the ropes with this project.
