### ISSUE TITLE
Org-roam landing page

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam#623]
Currently I've added a really gorgeous and useful landing page at https://org-roam.github.io/org-roam/, but I think we can make it more useful by adding some information about what the project is, when and why to use it etc.

**Comment by zaeph** [comment]
> really gorgeous and useful

Even websites in the 90s had more flair that the abomination you've just birthed into the world.  Great job! 👍

**Comment by titaniumbones** [comment]
Haven't really thought about it but it shouldn't be too hard to use ox-hugo to recreate something like the old, quite pretty site. not sure I can contribute right now, somewhat scattered harried!

**Comment by zaeph** [comment]
Just to be clear, the [old manual is still up for now at the same address](https://org-roam.readthedocs.io/en/master/), for now at least.

**Comment by bdarcus** [comment]
For this page, how broad and deep do you think it should be?

is it, for example, three paragraphs, with an image and some links?

More like three sections?

**Comment by jethrokuan** [comment]
I was thinking it would be like a typical landing page, like https://obsidian.md/

The goal is to have an elevator pitch. No need for something complex like ox-hugo, basic HTML/CSS will do. We should also do something about the manual CSS

**Comment by bdarcus** [comment]
Ah, OK, so super short!

So we need someone with marketing and/or design skills here.

>

**Comment by bdarcus** [comment]
Possible pitch phrase (note: I do NOT have marketing background):

> structured note-taking for org-mode

**Comment by pprevos** [comment]
> Possible pitch phrase (note: I do NOT have marketing background):
> 
> > structured note-taking for org-mode

Best pitch phrases include the value proposition of the service. The four benefits listed  the old manual got me hooked:
- Private and Secure
- Longevity
- Free and Open-source
- Leverage the Org-mode Ecosystem

Many people get into Emacs because of Org (me included). Roam is the missing piece I was looking for because of its organic structure. So perhaps (I have a marketing PhD, but I suck at copy-writing):

- "Organic note-taking for Org-mode" (structure)
- "The last note-taking app you will ever need to use" (longevity)
- "Discover your mind with Org-roam" (structure)

It depends a bit whether you target existing Emacs users or newbies.

**Comment by dit7ya** [comment]
I made a quick prototype landing page here.

https://org-roam-landing-sample-git-master.dit7ya.now.sh/

If you guys think its good enough I can work on it for more. 

Let me know your comments.

**Comment by zaeph** [comment]
> I made a quick prototype landing page here.

LGTM!

**Comment by bdarcus** [comment]
I think it's great. Only suggestion I would make is to deprecate Slack, and so not put it on the landing page.

That's really up to @jethrokuan and @zaeph though.

**Comment by jethrokuan** [comment]
LGTM, just a couple of comments:

1. Black text on white background feels more paper-ish to me, not sure how that makes y'all feel
2. Features section feels a bit crowded, without any icons or screenshots. Maybe split them up into 2x3 instead.
3. You can say you built the website (visible text on the webpage) but the author meta-tag should probably be something like "org-roam contributors"
4. We should probably have a video or image of the software somewhere
5. I want the links to be to the online manual (including the getting started), so we can centralized documentation efforts to the same place.

I don't think we need to deprecate Slack, it's still a good platform for real-time chat, but I do think there's a significant drop in volume of discussion there since the introduction of Discourse, which is great.

**Comment by bdarcus** [comment]
> I don't think we need to deprecate Slack,

Fair enough. But the question is, where do you want a newbie to go first?

Listing both venues on equal footing on the landing page (as now), I am speculating, will lead to confusion.

At minimum, the text should make clear they are for different purposes?

**Comment by dit7ya** [comment]
>     1. Black text on white background feels more paper-ish to me, not sure how that makes y'all feel

I started with a light background (as that is default for Wing.css but found this better looking, I can create a light version if you want.)

>     2. Features section feels a bit crowded, without any icons or screenshots. Maybe split them up into 2x3 instead.

Okay, sure.

>     3. You can say you built the website (visible text on the webpage) but the author meta-tag should probably be something like "org-roam contributors"

I don't want to be visible as the author! That tag got included as a template, will change.
 
>     4. We should probably have a video or image of the software somewhere

Maybe a screencast as a gif? I really like @zaeph's theme, would be great to include gig of a complete org-roam workflow from them.

>     5. I want the links to be to the online manual (including the getting started), so we can centralized documentation efforts to the same place.

Okay. Also, can we just not host the ReadTheDocs stuff on GitHub pages? There exists a [ReadTheOrg](https://github.com/fniessen/org-html-themes) theme as well.

**Comment by dit7ya** [comment]
Also, I am not sure where we are about the name change (due to the chance of getting sued form Roam's VCs in future) but in the meantime we need to have a canonical spelling of Org-roam.

1. Org-roam
2. org-roam
3. Org Roam
4. orgroam

I like 3 most, followed by 2.

**Comment by progfolio** [comment]
>  I am not sure where we are about the name change

Definitely deserves more discussion. I feel it's a good move not only for the possible protection you mention above, but also for the identity of the project as a whole. Roam may have been the inspiration, but it should not be the goal. The current name sets the expectation of a Roam clone.

**Comment by bdarcus** [comment]
> Roam may have been the inspiration, but it should not be the goal. The current name sets the expectation of a Roam clone.

Really nicely put, and I agree 100%!

**Comment by jrantaka** [comment]
How does governance work in this project? I would like to explore a design based on my logo draft on [discourse](https://org-roam.discourse.group/t/org-roams-logo/15/14?u=jrantaka) but don't want to step on anyones foot regarding pushing my own designs / ideas etc.

**Comment by jethrokuan** [comment]
> How does governance work in this project?

Not much here, but @zaeph, @progfolio and I oversee most of the code changes that go into this repo. 

Regarding design it's basically free territory, but there's a bunch of open questions that need to be resolved:

1. Are we going to have a name change (for future-proofing), and if so, to what?
2. If we change our name, will the logo also need to change?

I personally don't have much of a preference, and does not feel like a priority to me. While some may feel that the decision is up to me, I'd like to leave it for the community to decide. The discussion thus far has been very preliminary, so ideas are just being thrown around. At some point (hopefully soon), I'd like to hold a poll, and just pick the majority choice.

**Comment by jethrokuan** [comment]
> Okay. Also, can we just not host the ReadTheDocs stuff on GitHub pages? There exists a ReadTheOrg theme as well.

Sure, it was just much easier to have the CI generate the HTML using the info document directly.

**Comment by dit7ya** [comment]
I have pushed some blings to the site, also fixed the issues discussed here. Let me know if it looks okay and what else would you like to see, and then I can start a PR.

The URL is same.

https://org-roam-landing-sample-git-master.dit7ya.now.sh/

**Comment by titaniumbones** [comment]
I think it looks awesome.  Can I suggest changing header  Backlinks --> Bscklinking for grammatical  parallelism? Graph visualization is I guess also a noun but stands out less to me.

On May 18, 2020 4:29 a.m., Sayan <notifications@github.com> wrote:

I have pushed some blings to the site, also fixed the issues discussed here. Let me know if it looks okay and what else would you like to see, and then I can start a PR.

The URL is same.

https://org-roam-landing-sample-git-master.dit7ya.now.sh/

**Comment by jethrokuan** [comment]
@dit7ya looks good! Can you begin by opening a PR? Here are some comments:

There's a lot of whitespace here:

![image](https://user-images.githubusercontent.com/1667473/82222016-4eb45d80-9953-11ea-8e7e-e675aac4dbbc.png)

Bottom bar could use some margin at the bottom, and less margins between the header and text. It also feels a bit small.

![image](https://user-images.githubusercontent.com/1667473/82222056-5d9b1000-9953-11ea-8bbe-7738b9febb9c.png)

1. Point to the manual instead of readthedocs.
2. I'll make the other rewording suggestions later on.
