### ISSUE TITLE
line breaks from original content disappear in backlink buffer 

### ISSUE THREAD

**Issue by J0ns4** [org-roam/org-roam#630]
### Description
The text that appears as part of the link context "joins" lines from the original context, so that become one long line of text.

#### Expected Results

<-- The text around the link should be formatted as in the original org file -->

### Versions

- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: latest stable(?) installed from MELPA

**Comment by zaeph** [comment]
Right now, the context is considered to be the paragraph in which the link was found.  A line-break does not end the paragraph, but two line-breaks will.  Can you confirm this?

Also, we're preparing an overhaul of the `org-roam-buffer`, including the contexts shown, so we'll tackle this in the near future.

**Comment by jethrokuan** [comment]
@zaeph I actually do replace line breaks, when writing to the `org-roam-buffer` (remnants from when it was built towards my config).

**Comment by J0ns4** [comment]
Thanks! I'm happy to hear about the upcoming changes.  
I've also noticed that the heading that gets shown in the buffer is the the top most one instead of the one directly preceding (i.e. containing) one, are you planning to address that as well?

It's a great package, I really appreciate all the work that's been put into it!

**Comment by jethrokuan** [comment]
> I've also noticed that the heading that gets shown in the buffer is the the top most one instead of the one directly preceding (i.e. containing) one, are you planning to address that as well?

Is that so? We don't actually grab headings, we grab whatever element surrounds the link: could be a paragraph, bullet-point, or heading. If it's a heading, the text of the heading is printed.

**Comment by J0ns4** [comment]
Indeed. 
Look at the backlink to "neurophysiology" from "labs":
![image](https://user-images.githubusercontent.com/18332012/82206594-2e63af00-9911-11ea-89df-a8e983881e82.png)

it should have the subheader of "weizmann institute"

**Comment by jethrokuan** [comment]
Thanks for the example, could you open a separate issue in the tracker?
