### ISSUE TITLE
org-roam-find-file should create file in subdirectory if name contains org-roam-title-subdir-separator

### ISSUE THREAD

**Issue by zoechi** [org-roam/org-roam#635]
### Brief Abstract
Org-Roam supports files in subdirectories and now even creates tags from them.
I haven't found an easy way to create Org-Roam files in subdirectories, so this feature isn't as useful as it could be.

### Proposed Implementation (if any)
When a new file is created and the given name contains `org-roam-title-subdir-separator` (only when not `nil`)
then it should split it at these characters and use the parts as path except the last which should become the file name.

If the directories do not exist it should ask y/n whether to create them.

### Please check the following:

- [x] No similar feature requests

**Comment by zaeph** [comment]
Thanks for filing the PR.  It should be fairly trivial to implement, although I'm a little worried about the separator being misused.  I'll draft something up in the next few days.

**Comment by jethrokuan** [comment]
This variable is actually gone now after the tagging functionality merge. We can bring it back, but I'm wondering if the UX here is ideal.

Typically, when calling an interactive such as org-roam-insert, the directory will not appear as part of the completion: the current format is `(tag) title`. So if you type `subdir/New File Here`, it means you had known beforehand that the note you wanted did not exist. I can imagine this getting very messy. 

Also, Org-roam operates under the philosophy that a flat hierarchy is sufficient. We do support the use of sub-directories, but as tags (see https://org-roam.github.io/org-roam/manual/Tags.html#Tags). What do you intend to use sub-directories for?

We also support the creation of files under a sub-directory using templates. For example, my ref template currently creates new notes under a subdirectory for website notes:

```
(setq org-roam-ref-capture-templates
        '(("r" "ref" plain (function org-roam-capture--get-point)
           "%?"
           :file-name "websites/${slug}"
           :head "#+ROAM_KEY: ${ref}
#+TITLE: ${title}

- source :: ${ref}"
           :unnarrowed t)))
```

**Comment by zoechi** [comment]
> Also, Org-roam operates under the philosophy that a flat hierarchy is sufficient. We do support the use of sub-directories, but as tags

This statement seems contradictory to me. Either subdirectories are supported or not.
What is the point of supporting directories when creating files in them is cumbersome.

> but as tags

I don't really know what that means. I haven't found any information how tags are supposed to be used or what purpose they should serve exactly or why directories were chosen for this purpose.

My use case is for example to store all information about Emacs, how to use and configure it and all the packages I use in an "Emacs" subdirectory. This way I can for example avoid name clashes with names like "Company".
Usually I like the flat hierarchy concept of Org-Roam, but some concepts are distinct and broad enough that I think their own directory is warranted and also prefixing everything with "Emacs" because otherwise there would be too much ambiguity.

**Comment by jethrokuan** [comment]
> This statement seems contradictory to me. Either subdirectories are supported or not.
> What is the point of supporting directories when creating files in them is cumbersome.

They are supported in the sense that Org-roam picks up the files regardless of how deeply nested they are within `org-roam-directory`. Files within sub-directories can also be configured to receive tags (as mentioned in link to the documentation above), which seems to be your use-case. They are not supported, in the sense that we do not ascribe any meaning beyond tagging.

> I don't really know what that means. I haven't found any information how tags are supposed to be used or what purpose they should serve exactly or why directories were chosen for this purpose.

There's some documentation on tagging at https://org-roam.github.io/org-roam/manual/Tags.html#Tags. Here's what having files in a sub-directory looks like for me, under `refs/websites/...`.

![image](https://user-images.githubusercontent.com/1667473/82115946-9e9af500-9798-11ea-96af-398dd136d850.png)

Note that I use tags to differentiate what kind of note it is, and not what topic it is. Topical hierarchies are created using regular links.

**Comment by zoechi** [comment]
> They are not supported, in the sense that we do not ascribe any meaning beyond tagging.

I think that's exactly what I want. 
Most files will belong to one main category, besides several others, so creating files in directories should be common enough.
I really like that directory and tags in properties can be extracted together to be used as tags.

This issue is just about improving the experience when creating such tagged files.

**Comment by asheidan** [comment]
Just so I understand the current features correctly. Is it not possible to create files in subdirectories unless the subdirectory Is specified in the capture template?

**Comment by zaeph** [comment]
> Just so I understand the current features correctly. Is it not possible to create files in subdirectories unless the subdirectory Is specified in the capture template?

Yes.

**Comment by jethrokuan** [comment]
This is not something I intend to officially support.

**Comment by 0x4d6165** [comment]
Why not? It seemed to have a good amount of interest and even an implementation?

**Comment by Dietr1ch** [comment]
This is something I get around by defining capture templates that create files in specific directories.

It requires to have an idea of your directory structure in advance, but it's not hard to simply add a new entry if a new directory is desired.

```elisp
      org-roam-capture-templates '(
                                   ("d" "default" plain "%?"
                                    :if-new (file+head "Roam/%<%Y%m%d%H%M%S>-${slug}.org"
                                                       "#+title: ${title}\n")
                                    :dir-name "Roam"
                                    :unnarrowed t)

                                   ("a" "Article" plain "%?"
                                    :if-new (file+head "Articles/%<%Y%m%d%H%M%S>-${slug}.org"
                                                       "#+title: ${title}\n#+filetags: :Reading:Article:\n#+TODO: READ(r) READING(rr) | DONE(d) SKIMMED(s) IGNORED(i)\n")
                                    :dir-name "Articles"
                                    :unnarrowed t)
                                   )
```
