### ISSUE TITLE
org-roam-find-file and org-roam-insert not responding

### ISSUE THREAD

**Issue by pprevos** [org-roam/org-roam#636]
### Description
Org-Roam breaks after latest upgrade from MELPA.

#### Steps to Reproduce
When I run the org-roam-find file function I get the following error:

`org-roam-completion--completing-read: Wrong type argument: sequencep, #s(hash-table size 217 test equal rehash-size 1.5 rehash-threshold 0.8125 data `

The same error appears when I run `org-roam-insert`.

I reproduced this error on a clean Emacs with only use-package and org-roam enabled. The database is intact because I can still generate a network.

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam from MELPA

**Comment by zaeph** [comment]
> I reproduced this error on a clean Emacs with only use-package and org-roam enabled. The database is intact because I can still generate a network.

This does not mean that the database is intact.  Could you try rebuilding it with `C-u M-x org-roam-db-build-cache`?

**Comment by togakangaroo** [comment]
I've rebuilt the database the error seems to have to do with this line inside of `org-roam-completion--completing-read`

            (let ((candidates (mapcar #'car choices)))
              (ido-completing-read prompt candidates nil require-match initial-input)))

where `choices` is essentially `((org-roam--get-title-path-completions)`

this in the scratch buffer gives me the same error

   (mapcar #'car (org-roam--get-title-path-completions))

is `mapcar` over a hash-table even valid? This *also* gives me the same error

   (maphash (lambda (a b) a) #s(hash-table size 30 data (key1 val1 key2 300)))

**Comment by zaeph** [comment]
Uhm.  We've changed the alist to a hash-table today to circumvent problems with `completing-read`, but we're planning on moving to something else really soon because this is pretty wonky.

It's working on my end, which seems to indicate a problem with the format of one or more of your files that is causing `org-roam--get-title-path-completions` to conk out.

**Comment by togakangaroo** [comment]
@zaeph that's not possible - look at the last block of code I posted - it doesn't even use anything from roam, just testing whether you can `mapcar` over a hash-table and that seems to not be the case. Could I suppose be a difference of emacs versions?

**Comment by zaeph** [comment]
Ah, now I know, and you were right.

It's because you're using `ido`, and @jethrokuan and I were using different completion-engines for testing, but we forgot to change it here.  I'll try to fix it tonight.

Just a heads-up: we're probably going to require you to use one of the modern completion engines like `ivy` or `helm` in the future.

**Comment by togakangaroo** [comment]
I'm using `helm` so that's fine. Pretty much just default spacemacs for me

**Comment by pprevos** [comment]
> > I reproduced this error on a clean Emacs with only use-package and org-roam enabled. The database is intact because I can still generate a network.
> 
> This does not mean that the database is intact. Could you try rebuilding it with `C-u M-x org-roam-db-build-cache`?

I ran the function, but still get the same error. What does `C-u` do?

**Comment by zaeph** [comment]
> What does `C-u` do?

It removes the file and starts from scratch, rather than emptying the tables.

**Comment by togakangaroo** [comment]
Has this been shipped to melpa yet? I didn't see it come down in update-packages

**Comment by zaeph** [comment]
It normally has: [the page](https://melpa.org/#/org-roam) shows 265182a698be6babcbb11718c2821c747b1cff52 as the commit, which is our current `master`.
