### ISSUE TITLE
Move to modern completion-engines

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#639]
`completing-read` is stunting our efforts to show more relevant information when finding or inserting links to Org-roam files.  It also requires us to jump through many hoops to do basic stuff.

To that end, à la `bibtex-completion`, we'd like to move to modern completion-engines like `ivy` or `helm`.  The goal would be to add more base-code to `org-roam-completion.el` so as to support both `ivy` and `helm`, and then to create minimal, separate files for the two.

**Comment by zaeph** [comment]
Also, we need to assess whether we want to revert to using alists instead of hash-tables.  The later are presumably faster for large data-sets, but is it worth the added complexity?  I'd say 'yes', just because it's working now, but it doesn't feel like it's all that optimised.

**Comment by progfolio** [comment]
I personally use helm, but I don't think it's a great move to require such a completion engine. If anything, we should support such completion engines in their own packages and the default should be to support vanilla Emacs completion as much as possible.

**Comment by zaeph** [comment]
> What cases are being complicated by the default completion?
> Perhaps we can find a cleaner way to implement them.

@jethrokuan: Could you clarify what you couldn't do?  If I remember properly, it was a problem in #604 about hiding text from the completions, but still matching with those texts.  Think of `bibtex-completion` which allows you to match BibTeX-fields which are not always visible.



> If anything, we should support such completion engines in their own packages and the default should be to support vanilla Emacs completion as much as possible.

That was my stance at first, but considering what `bibtex-completion` has done, I think we might vindicated in those efforts.  That being said, rather than deprecating the old `completing-read`, we can try to implement as many features as we can with it, and mention in the manual that a modern completion-engine would be preferred.

**Comment by jethrokuan** [comment]
> If anything, we should support such completion engines in their own packages and the default should be to support vanilla Emacs completion as much as possible.

That's what we've been trying to do with the hash-table approach for the new `get-*-completion` internal functions. I'm not suggesting we drop support for default completions, but I think there will come a time where the making things work with the default completion would become complicated and hard to support, in which case, I want to say it's okay if the experience there is worse than with ivy/helm.

> @jethrokuan: Could you clarify what you couldn't do?

There are 2 fundamental complaints with `completing-read`:

1. It doesn't support propertized strings. I faced this issue when adding support for showing tags in the interactive commands. You can propertize the display of the string, but user input would filter on the base string, and not the displayed string. The proposal to solve this is [Icicles](https://www.emacswiki.org/emacs/Icicles_-_Candidates_with_Text_Properties).

2. The keys must be unique. Completing read returns the value of the key, which we now call `gethash` on, previously `(cdr (assoc ...))`. This means that if the key isn't unique, it will always return the first item in the list where it matches (in the hash-table approach, this isn't even possible). In many of our interactive functions, they are not guaranteed to be unique (e.g. title).

These are issues that are easily bypassed when using a completion engine with stronger support. The results we get for completion are already tabular in nature, from the SQL return result, and I think a form of tabular filtering would be both more useful to the user, and easier to implement.

**Comment by d12frosted** [comment]
That sounds great! I just hope that `ivy` will have its portion of love.

**Comment by spwhitton** [comment]
Perhaps worth noting that with fido-mode in Emacs 27 I think we can expect to see more people just using Emacs' default completion engine.  So would be cool if it kept working, at least with the features it has now.

**Comment by jethrokuan** [comment]
We definitely intend for things to work with the default completion engines. The more advanced functionality that the installed completion engines support would be shipped in their own file/package.
