### ISSUE TITLE
Links in File are Not Updated When It is Moved to a Different Directory

### ISSUE THREAD

**Issue by mchowning** [org-roam/org-roam#647]
### Description

When renaming an org-roam file within emacs to move it to a subfolder of its current directory (i.e. so moving it form `roam/` to `roam/subfolder`), the backlinks to the moved file get updated, but the links within the file itself are not updated to reflect the change in the relative location of the linked-to file. As a result, all the links in the moved file are broken.

#### Steps to Reproduce

1. Open an org-roam file within Emacs that links to another org-roam file in the same directory
2. Use emacs to move the file containing the link to a different directory
3. Observe that the link within the file has not been updated with the new relative path to the linked file.

#### Backtrace

N/A

#### Expected Results

Link within the moved file still works

#### Actual Results

Link within the moved file is not updated, and is now broken.

### Versions

- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: https://github.com/org-roam/org-roam/commit/265182a698be6babcbb11718c2821c747b1cff52

**Comment by zaeph** [comment]
Fix is almost ready.
