### ISSUE TITLE
`org-roam-insert` does not create proper link on file-creation

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#649]
Running `org-roam-insert` and creating a new file creates a link whose description is `nil`.

This is due to the new format of the query.  The fix should be done around here:
https://github.com/org-roam/org-roam/blob/265182a698be6babcbb11718c2821c747b1cff52/org-roam.el#L552

**Comment by zaeph** [comment]
f390593cfb2b880fa36bc06c0b42fb402a8f7af9 seems to be the culprit.

**Comment by fabioberger** [comment]
Just want to chime in that I also ran into this. Excited for the fix to be released.
