### ISSUE TITLE
Failing to run org-roam-capture: Wrong type argument: char-or-string-p, nil

### ISSUE THREAD

**Issue by beetleb** [org-roam/org-roam#651]
### Description

I just installed org-roam and wanted to try it out. I ran org-mode-capture with the default template. What happens is that I get a prompt `File:`, and I see a list of all my existing files in the org roam directory (or rather, a list of their titles). If I try to type anything else, I get the `Wrong type argument: char-or-string-p, nil` error. If I select one of the existing files I get a capture buffer with that existing file in it.

Perhaps I'm misunderstanding the point of capture, but I was thinking I could use it to:

1. Create a new file (with a given title)
2. Allow me to customize elements that are in the file (e.g. date, etc) in the usual org capture way.

I know I can create a new file using `org-roam-find-file`, but it doesn't let me use a template.

(Note: I'm using ido, with ido-everywhere and ido-ubiquitous. If I disable all of these, the problem is the same: I can only type in the names of existing files).

Am I doing things the wrong way?

#### Backtrace

```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  ucs-normalize-NFD-string(nil)
  #f(compiled-function (--cl-nonspacing-mark-p-- s) #<bytecode 0x122b99d>)(#f(compiled-function (char) #<bytecode 0x122b985>) nil)
  org-roam--title-to-slug(nil)
  org-roam-capture()
  funcall-interactively(org-roam-capture)
  #<subr call-interactively>(org-roam-capture record nil)
  apply(#<subr call-interactively> org-roam-capture (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> org-roam-capture record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (org-roam-capture record nil))
  call-interactively(org-roam-capture record nil)
  command-execute(org-roam-capture record)
  execute-extended-command(nil "org-roam-capture")
  smex-read-and-run(("toggle-debug-on-error" "org-roam-capture" "ido-ubiquitous-mode" "ido-everywhere" "org-roam-find-file" "list-matching-lines" "notmuch" "monky-status" "insert-screenshot" "list-packages" "deft" "read-only-mode" "org-download-screenshot" "auto-fill-mode" "print-buffer" "yas-minor-mode" "helm-ag" "org-noter" "zetteldeft-search-at-point" "widen" "python-mode" "text-mode" "flycheck-mode" "regexp-builder" "delete-file" "calc" "dired" "describe-bindings" "zetteldeft-new-file" "sort-lines" "clean-chars" "org-babel-tangle" "org-babel-mark-block" "mc/mark-all-like-this" "zetteldeft-follow-link" "zone" "org-mode" "html-mode" "org-return" "eval-buffer" "org-version" "org-cliplink" "debug-on-entry" "org-cdlatex-mode" "which-function-mode" "crux-smart-kill-line" "zetteldeft-find-file-id-insert" "info" "smex" "helm-M-x" ...))
  smex()
  funcall-interactively(smex)
  #<subr call-interactively>(smex nil nil)
  apply(#<subr call-interactively> smex (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> smex nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (smex nil nil))
  call-interactively(smex nil nil)
  command-execute(smex)
```

### Versions

- Emacs (`C-h v emacs-version`): GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2020-04-05
- Org-roam commit: 20200516.1203 (from MELPA, not Github)

**Comment by zaeph** [comment]
I can't reproduce this on my end.  Judging by the fact that you get dropped in an `org-capture` frame even though the file already exists, there definitely seems to be shenanigans afoot.

Are you using base-Emacs, or one of the distros?  If you're using a distro, it might be best to try it out in base-Emacs.

**Comment by beetleb** [comment]
Vanilla Emacs. 

What is the expected behavior of capture with the default template? The doc is a bit confusing.

**Comment by zaeph** [comment]
I'm signing off for tonight, so I won't be able to help you right now.  I'm suspecting an illegal character in the titles, or in the tags if you have them.

I'll think about it tomorrow.

**Comment by beetleb** [comment]
So I realized that when I do `org-roam-find-file`, it uses the default capture.

When I modify the default template in `org-roam-capture-templates`, using `org-roam-find-file` reflects those changes.

When I *add* entries to `org-roam-capture-templates`, something weird happens. Running `org-roam-find-file` presents me with a capture menu, but it *only* shows the default one (`d`). It doesn't show the new one I added (regardless of how I arrange the entries in `org-roam-capture-templates`).

So my first question is: Is one supposed to call `org-roam-capture` directly or only via `org-roam-find-file`?

The second issue is that my new entries in `org-roam-capture-templates` don't show up...

**Comment by progfolio** [comment]
Can you please post an example of `org-roam-capture-templates` that exhibits the behavior?

**Comment by beetleb** [comment]
```
(setq org-roam-capture-templates
      '(
       	("e" "Experiment" plain (function org-roam--capture-get-point)
       	 "Exp %?"
       	 :file-name "%<%Y%m%d%H%M%S>-${slug}exp"
       	 :head "#+TITLE: ${title}\n"
       :unnarrowed t)
	("d" "default" plain (function org-roam--capture-get-point)
	 "Default %?"
	 :file-name "%<%Y%m%d%H%M%S>-${slug}"
	 :head "#+TITLE: ${title}\n"
       :unnarrowed t)
	))
```

**Comment by progfolio** [comment]
Unfortunately, using the value for `org-roam-capture-templates` you've pasted above, I'm unable to reproduce that behavior. When creating a new file I get the capture menu with both of the templates as options.

What version of Org are you using? `M-x org-version`

**Comment by progfolio** [comment]
Try pasting this into an empty buffer
```emacs-lisp
(let ((org-roam-capture-templates
       '(("e" "Experiment" plain (function org-roam--capture-get-point)
          "Exp %?"
          :file-name "%<%Y%m%d%H%M%S>-${slug}exp"
          :head "#+TITLE: ${title}\n"
          :unnarrowed t)
         ("d" "default" plain (function org-roam--capture-get-point)
          "Default %?"
          :file-name "%<%Y%m%d%H%M%S>-${slug}"
          :head "#+TITLE: ${title}\n"
          :unnarrowed t))))
  ;;(org-roam-find-file)
  (org-roam-capture))
```
and running `M-x eval-buffer`. Do you still only see one template? Both commands are working as expected for me.

**Comment by beetleb** [comment]
> It would also be helpful to see the value of org-capture-templates-contexts

OK - That helped solve it. Apparently I'm using "e" for "email" and it shows up only in a `notmuch` buffer. I had assumed that org-roam's capture templates are distinct from the usual org capture templates. It is kind of weird, given that I also have "d" defined in my regular org captures, but it still works here.

So changing from "e" to some other character that I don't currently used solved the issue. Now when I do `org-roam-find-file` I get both choices.

I still have the problem mentioned originally with `org-roam-capture` (`Wrong type argument: char-or-string-p, nil`). But `org-roam-find-file` seems to work.

Is there any advantage to using `org-roam-capture` vs `org-roam-find-file`?

**Comment by jethrokuan** [comment]
> It is kind of weird, given that I also have "d" defined in my regular org captures, but it still works here.

Yes it is, your templates in `org-capture-templates` should not show up at all during the capture process. Do you mean that they don't show up, but are still accessible via the key?

> org-roam-capture vs org-roam-find-file

`org-roam-find-file` just opens the file, while `org-roam-capture` is like `org-capture`, so it depends on what you want to do.

**Comment by RBckmnn** [comment]
I'm also facing this issue. I'm using Doom's +roam flag and have not made any customizations on my part.

Doom commit: 98d7b97d3
Org-roam commit: 1267a4304

If I try to capture to a new note, I get the following backtrace:

`
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  ucs-normalize-NFD-string(nil)
  #f(compiled-function (--cl-nonspacing-mark-p-- s) #<bytecode 0x1be7025>)(#f(compiled-function (char) #<bytecode 0x1be700d>) nil)
  org-roam--title-to-slug(nil)
  org-roam-capture()
  funcall-interactively(org-roam-capture)
  call-interactively(org-roam-capture nil nil)
  command-execute(org-roam-capture)
`

The value of `org-roam-capture-templates` is

`
(("d" "default" plain #'org-roam-capture--get-point "%?"
  :file-name "%<%Y%m%d%H%M%S>-${slug}"
  :head "#+TITLE: ${title}\n"
  :unnarrowed t))
`

**Comment by progfolio** [comment]
> It is kind of weird, given that I also have "d" defined in my regular org captures, but it still works here.

I took it to mean:
The "e" template was not being displayed due to `org-capture-templates-contexts`, the "d" template was being shadowed by `org-roam-capture-templates` (as expected). The solution for that is to let-bind `org-capture-templates-contexts` to `nil` before calling `org-capture` with org-roam's templates.

`org-roam-capture` and `org-roam-find-file` do seem to share a lot of duplicate code. One should probably be a special case of the other.

**Comment by progfolio** [comment]
Ok. I can reproduce this error when entering the empty string (`""`) at the file prompt. This can be done with `helm` via `helm-cr-empty-string` (Usually bound to `<C-return>` or `M-RET`)- or by manually typing the empty string. `org-roam--title-to-slug` requires a title argument, but receives `nil` because there is not title associated with `""`.

@RBckmnn: What do you use for completion? `ido`, `helm`, `ivy`?

**Comment by progfolio** [comment]
That should take care of it.
@RBckmnn, @beetleb: If you have any issues with this after upgrading org-roam, please comment here and we can reopen this issue.

**Comment by RBckmnn** [comment]
@progfolio Thanks for the speedy reply. Your commit indeed fixed the issue on my end :-). I'm indeed using `helm` for completion.

**Comment by beetleb** [comment]
I just confirmed it works. Thanks!
