### ISSUE TITLE
Race condition between graph building and opening

### ISSUE THREAD

**Issue by matrixfang** [org-roam/org-roam#666]
### Description
I don't know why my org-roam graph generated by org-roam-graph is empty, here's my settings

(use-package org-roam
  :ensure t
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-directory "\~/org/")
     (org-roam-graph-viewer "/usr/bin/open")
     (org-roam-graph-executable "/usr/local/bin/dot")
      (org-roam-index-file "\~/org/roam-index.org")
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n j" . org-roam-jump-to-index)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))))

After take some notes and add links in them, I ran "org-roam-graph", but I get an empty graph

My default svg-opening  app is chrome, and i got this

<img width="831" alt="Screen Shot 2020-05-18 at 5 52 13 PM" src="https://user-images.githubusercontent.com/28817186/82199787-c0c77b00-9930-11ea-85c7-715fcd7ba0f8.png">

I'm a fresher about org-mode, and I don't know what's wrong

**Comment by jethrokuan** [comment]
Do backlinks show in your org-roam buffer?

When you generate the graph, there should be a corresponding `.dot` file, which you can obtain by replacing the `.svg` with `.dot`. Can you share that here, or just check if it's empty?

**Comment by matrixfang** [comment]
Yes, I can provied the .dot file.
Looks like the .svg and .dot was generated well.
I have to click file then the chrome will show the right .svg file, but when I run "org-roam-graph", the chrome can only show this
<img width="568" alt="Screen Shot 2020-05-18 at 10 20 19 PM" src="https://user-images.githubusercontent.com/28817186/82224625-a6a09380-9956-11ea-85d3-6888429ae1f6.png">



[Archive.zip](https://github.com/org-roam/org-roam/files/4644659/Archive.zip)

**Comment by jethrokuan** [comment]
Downloading the archive, I can view the image in the folder and in the web browser, so I think your web browser is misconfigured, and can't preview svg files, not sure why.

**Comment by d12frosted** [comment]
I also encounter this problem in Safari. Refreshing page helps. Could it be that `open` is executed before `svg` is fully generated?

**Comment by mchowning** [comment]
> I also encounter this problem in Safari. Refreshing page helps. Could it be that `open` is executed before `svg` is fully generated?

I've noticed the same thing with Chrome on both mac and linux. Generating my full graph can take 10-15 seconds. So the browser immediately opens with the message in the issue description, but refreshing the browser after a bit shows the graph. Even subgraphs frequently require a browser refresh to pull up the graph, although for a subgraph I can frequently just immediately refresh and see the graph.

**Comment by progfolio** [comment]
I have hit this issue, too. Can confirm it's a race between graph creation and viewing processes. The correct way to implement this is in Elisp appears to be w a process sentinel.

**Comment by progfolio** [comment]
@matrixfang @d12frosted @mchowning:
Can you please test latest master to see if that patch works for you?

**Comment by mchowning** [comment]
> Can you please test latest master to see if that patch works for you? Thanks for the fix @progfolio :+1: 

Nice! I don't have the browser loading up before the graph is ready any more. :slightly_smiling_face: 

That does mean that I'm left sitting in emacs for however long it takes to generate the graph with it not being obvious that anything is happening (well, I do hear my computer's fan firing up). For small graphs that is fine, but for my entire graph that takes around 15 seconds. I'm far from an emacs expert, so perhaps there is an indication that work is being done,  I'm just missing it. 

Still, emacs isn't frozen during this time, and I think this is a much better experience since it avoids giving the misperception that the graph generation failed.

I do wonder why graph generation is slow for me. I must have something misconfigured locally since my graph isn't _that_ big (~700 files), and I'm running a reasonably quick machine (<2 years old, i7 processor, 16g ram). :thinking:

**Comment by progfolio** [comment]
> That does mean that I'm left sitting in emacs for however long it takes to generate the graph with it not being obvious that anything is happening

Good catch. I will add a message that notifies the user the graph building process has started.

> I do wonder why graph generation is slow for me. I must have something misconfigured locally since my graph isn't that big (~700 files), and I'm running a reasonably quick machine (<2 years old, i7 processor, 16g ram). 

Hard to say without profiling. I would recommend seeing where those cpu cycles are being spent. 
Theres this for elisp/Emacs profiling: https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html
And plenty of utilities like `top`, `htop`, etc for general system profiling.
If you do any profiling, please let us know the results.

**Comment by mchowning** [comment]
It looks like it's related to my use of `fdp`; `dot` runs drastically faster for me. I'll see if there may be some tweaking I can do to `fdp`'s settings to speed things up.

**Comment by progfolio** [comment]
@mchowning: added a message to indicate that the graph process has started.
The process is also visible in Emacs by using the `list-processes` command.
The process will show up as `*org-roam-graph--build-process*`.
A buffer by the same name is created which will capture any output from the process.

**Comment by mchowning** [comment]
> added a message to indicate that the graph process has started

I like the added message. :+1:
