### ISSUE TITLE
Wrong type argument: listp when capturing

### ISSUE THREAD

**Issue by liaowang11** [org-roam/org-roam#669]
### Description
```
Wrong type argument: listp, #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("https://news.ycombinator.com/item?id=22325975" (:path "/Documents/org/roam/20200518152529-hn_learning_complex_technical_information.org" :type "website" :ref "https://news.ycombinator.com/item?id=22325975") "https://news.ycombinator.com/item?id=22473209" (:path "/Documents/org/roam/20200519004103-hn_take_good_notes.org" :type "website" :ref "https://news.ycombinator.com/item?id=22473209") "https://news.ycombinator.com/item?id=22792829" (:path "/Documents/org/roam/20200519004547-hn_how_can_i_pick_a_side_project_and_stick_with_it.org" :type "website" :ref "https://news.ycombinator.com/item?id=22792829") "https://news.ycombinator.com/item?id=23057411" (:path "/Documents/org/roam/20200519004618-hn_how_do_you_manage_self_study.org" :type "website" :ref "https://news.ycombinator.com/item?id=23057411"))).  Please adjust ‘org-roam-capture-ref-templates’

```

#### Steps to Reproduce
Add some refs and capture

#### Backtrace
After some debugging, seems to be related to this line. https://github.com/org-roam/org-roam/blob/master/org-roam-capture.el#L268
```elisp
(or (cdr (assoc ref completions))
```
`org-roam--get-ref-path-completions` returns hash table but get `assoc`ed? Resulting in the listp error. I'm not too familiar with elisp. 

#### Expected Results

Capture success

#### Actual Results

Wrong type argument: listp 

### Environment

Latest roam version 1.1.1

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by Emiller88** [comment]
I'm having the same issue perhaps it's related to https://github.com/org-roam/org-roam/commit/78b518efd32eeb5168ac96516328a4d21ad7f104 and #651

**Comment by jethrokuan** [comment]
I think the fix has been merged, just need some time for Melpa to pull things down and rebuild.

**Comment by Emiller88** [comment]
@jethrokuan I'm on `v1.1.1` and get 
```user-error: Wrong type argument: stringp, nil.  Please adjust ‘org-roam-capture-templates’```
When calling `org-roam-capture`. I'm just using the config options that `doom-emacs` provides out of the box besides unpining the package so I could test the latest version.

**Comment by progfolio** [comment]
@Emiller88 : Can you please post the value of `org-roam-capture-templates`?

**Comment by Emiller88** [comment]
@progfolio of course!
```lisp
(("d" "default" plain #'org-roam-capture--get-point "%?" :file-name "%<%Y%m%d%H%M%S>-${slug}" :head "#+TITLE: ${title}\n" :unnarrowed t))
```

**Comment by progfolio** [comment]
Thank you. I'm unable to reproduce so far.
Can you `M-x toggle-debug-on-error`, execute behavior that triggers the error, and paste the full content of the backtrace buffer that pops up?

**Comment by Emiller88** [comment]
@progfolio That failed and didn't throw a backtrace so I thought it might have been my personal capture templates, then I realized I added a `dir-locals` about the same time the original issue popped up. I apologize for wasting your time!

`dir-locals` incase this helps @liaowang11 or if this is not a one off issue. 
```lisp
((nil . ((eval autoload 'gac-after-save-func "git-auto-commit-mode")
          (eval add-hook! 'org-mode-hook
            (add-hook 'kill-buffer-hook #'gac-after-save-func t t)))))
```

**Comment by liaowang11** [comment]
Updated to 1.1.1 and confirm this fixed, closing.
