### ISSUE TITLE
Do not use commas between tags in #+ROAM_TAGS

### ISSUE THREAD

**Issue by jdelacueva** [org-roam/org-roam#671]
### Description
If you use a comma "," to separate tags included in the `#+ROAM_TAGS:` property, emacs will not allow `org-roam-find-file`, `org-roam-insert` to work properly. The resulting message is:

> Wrong type argument: characterp, \\,

#### Steps to Reproduce
1. Use this keyword in a zettel file:
`#+ROAM_TAGS: alice, bob`
2. Execute
`org-roam-insert-file`

### Solution:
Do not use commas in between tags in  `#+ROAM_TAGS:` property

**Comment by jethrokuan** [comment]
Yep, that's right, ROAM_TAGS are space-delimited, as mentioned in the docs. Unfortunately, the parsing for it is relatively complex to allow for quoted, multi-word tags as well. Not sure what I can do about this.

**Comment by progfolio** [comment]
Possible candidate for an org-roam-doctor checker

**Comment by jdelacueva** [comment]
Yes, I read the docs but automatically I tagged one of the files with two tags and a comma in between. I did not repair in the detail and the error message appeared. It took me a long while until I discovered the issue as Google did not give a clue. 

As @progfolio suggests, it is a good candidate for org-roam-doctor. And perhaps a mention in the docs warning about triggering an error if you put a comma in `#+ROAM_TAGS:` line.

BTW, thank you for your work.

**Comment by etiennelb** [comment]
I had exactly the same problem today and didn't understood what was going on... Thank you very much for the clue.

**Comment by telotortium** [comment]
It looks like commas are also not allowed in `#+ROAM_ALIAS` lines.

**Comment by d12frosted** [comment]
@telotortium yes, and in this regards tags are consistent with alias. Which is good 😸

**Comment by jethrokuan** [comment]
This should be detected by `org-roam-doctor` now.

**Comment by herop** [comment]
Talking of tags: One rather important question is - Will the org-tags like in #+FILETAGS: :@Work:Personal: and the like treated the same then ROAM_TAGS?
