### ISSUE TITLE
#+KEYWORD caching in org-roam-db

### ISSUE THREAD

**Issue by rrix** [org-roam/org-roam#672]
### Brief Abstract

I would like to have access to a some global props in org-roam.db so that I don't have to parse them myself :) having them all in the sqlite3 file means I can maintain relatively simple database schemata in my site generator compared to having to write org-mode parsing code outside of Emacs

### Long Description

the org-roam.db is proving to be a useful "API" of sorts for me to build my website around, as well as some other tools. One thing I would like to do, for example, is generate a birthday calendar from a bunch of contact pages which I have imported with birthdays formatted as global props, or generate feed indexes for my RSS reader:

```
#+BIRTHDAY: <2021-03-25 Thu +1y> 
#+RSS_URL: https://aeon.co/feed.rss
#+RSS_CATEGORY: Longreads
```

Perhaps it is not considered reasonable or something you're willing to support, using the cache database in a fashion like this but I only plan to do reads from outside of org-roam as a scaffold for my site generator and frankly I'm willing to bear the cost of keeping up with you in my own code rather than reimplement it all myself or re-build my site generator in Emacs Lisp again.

### Proposed Implementation (if any)

I propose a new customisation, `org-roam-cache-global-props` which contains a list of strings, which will be used by a new metadata extractor `org-roam--cache-global-props` to feed to `org-roam--extract-global-props`, storing them in the sqlite3 db in a properties table. I don't like the name of either of these, though.

If this is a feature you're interested in, I'm happy to make a pass at implementing it, I think my proposal is relatively sound, but I haven't thought of edge cases fully. Invalidating and rebuilding this database table when the customisation changes may be troublesome for example. I also have not considered the performance characteristics of a change like this. The longer this list is, the longer an cache rebuild would take, it seems like, fairly linearly?

As for schema, I think a schema of:
```
(properties 
 [(file :not-null)
  (keyword :not-null)
  (value)]
```
is simple and straightforward to query against. 

I want to be able to execute queries like `SELECT file, value FROM properties WHERE keyword="RSS_URL" and value is not null`.

### Please check the following:

- [x] No similar feature requests, as far as i see, search "keywords" and "properties"

**Comment by alan-carroll** [comment]
This sounds a lot like a more minimal version of Roam's 'attributes' using general metadata. If there is enough interest to implement this type of thing within org-roam then it may be better to come up with a more modular and flexible syntax.

**Comment by rrix** [comment]
The only reference to attributes i can find across [code, github, discourse] is the file-level attributes stored in the `files` table, i'll have to take your word on it :) I don't think I would be the person designing a more flexible system here, I don't know the code or other usecases well enough.

**Comment by alan-carroll** [comment]
Oh no, I mean in [Roam Research](https://roamresearch.com/) not org-roam! I wish I could link to some direct examples of them, but they are an alpha-feature so the documentation is really sparse.

Basically they would let you do things like give a page for PersonA a 'birthday' attribute. You could then later search for birthdays specifically, or create a table of people and 'birthday' would automatically be a column.

They are highly flexible (probably too flexible as a single item) and can do a bunch of other stuff depending on the context they are used in, but its unclear what is going to be useful in the future when they are out of alpha.

This particular case you've put forward is kind of the minimal example of what could be org-roam's 'attributes' (queryable metadata), but I don't think it could be extensible and flexible like Roam's are with your proposed syntax. If there's prevailing interest in implementing an attribute-esque feature, then this case would fall under it, so I was just suggesting it's worth considering alternatives forms to accomplish this task (particularly if we end up with things linkable headlines #548).

If no one cares to adopt Roam's attributes, then I like you suggestion just fine! 😄

**Comment by rrix** [comment]
That's okay, I misunderstood.

I found [this](https://roamresearch.com/#/app/help/page/LJOc7nRiO) page in their documentation about it, and [this](https://www.reddit.com/r/RoamResearch/comments/ej2pid/how_to_build_a_habit_tracker_in_roam/) reddit post about it. The current implementation seems like it is a sort of typed link, very neat thing. 

Similar to the desires in #548, i want to be able to build some limited "hypermedia", showing derived  views of data in other files, probably starting in org-babel blocks with emacsql. Org-mode itself doesn't seem super happy with links inside of keyword, opting to face them in the keyword face and making the link destination and the braces fully visible. it can still be clicked on, but it's aesthetically displeasing.

another thing which i was thinking about was a METADATA drawer which could be cached by org-roam-db, either extracting links or raw data to be queried.

**Comment by jethrokuan** [comment]
I'm reluctant to add additional caching that's not used by org-roam, but I have been thinking of making org-roam extensible, in that plugins for org-roam can be built (additional things can be cached, for example), without messing with org-roam's own code-base. If that change happens, you should be able to implement these additional caching easily for your own use.

**Comment by rrix** [comment]
That is fine to me, thanks!

**Comment by rrix** [comment]
Meanwhile, I am going to implement this in a private branch, I think I've managed to convince myself I'm blocked on it. :) I'm already tracking your development in RSS, so when something like that shows up I'll refactor it. Cheers.
