### ISSUE TITLE
index file creation does not work correctly

### ISSUE THREAD

**Issue by bdarcus** [org-roam/org-roam#674]
I don't know exactly what's going on, but can confirm the behavior reported on t[his post on the discourse forum](https://org-roam.discourse.group/t/how-can-i-create-an-index-file/165).

To reproduce, on a system without an index file:
1. `org-roam-jump-to-index`
2. choose to create missing index file, do so, do `C-c C-c`
3. close buffer and do 1 again yields file not found, and user is prompted if they want to create it

**Comment by progfolio** [comment]
Confirmed. `org-roam--get-index-path` is not accounting for prefix of capture templates `:file-name`. Will have patch up shortly.

**Comment by progfolio** [comment]
As a temporary workaround, you should be able to create the index file, look up it's full name in `org-roam-directory` and `(setq org-roam-index-file <full name of index file>)`

**Comment by zoechi** [comment]
#600 (#597) might be related

**Comment by progfolio** [comment]
@zoechi: indeed, these are related. Thank you.

For now I'm going to recommend the workaround I suggested above.
There are several internal issues with the design that need to be addressed before I can cleanly implement a solution.

**Comment by zaeph** [comment]
I've also run into some problems with the creation of the index in local `org-roam-directory`, so we need to look into this soon-ish.

**Comment by akmorrison** [comment]
I just ran into this issue, and it turns out the problem was that my `org-roam-directory` didn't end in a trailing slash, so `org-roam--get-index-path` was returning a weird path. Here's how to test that this works:

```
(let ((org-roam-directory "/path/to/org/roam")
      (org-roam-index-file "index.org"))
  (org-roam--get-index-path)) ; evaluates to "/path/to/org/roamindex.org"
```

**Comment by jethrokuan** [comment]
No more `index-file` related stuff in Org-roam, those who wish for one can simply write their own simple function to open the index file.
