### ISSUE TITLE
Ignore org-roam.db in version control?

### ISSUE THREAD

**Issue by joshmedeski** [org-roam/org-roam#677]
Just wondering if you think it’s a good idea to ignore the `org-roam.db` file in version control? I use org-roam across three devices right now and when I push and pull the org-roam.db changes I have to restart enacts and allow the system to catch up to itself.

Any advice? Should I ignore the file and just allow a local `org-roam.db` file for each device?

**Comment by aarohijohal** [comment]
That's what I personally do. I let each platform (client) handle their own iterative modifications when changes occur in the repo.
This would enable org-roam to be able to use other platform-dependant storage mechanisms in the future, leaving your repository untouched, if it ever comes to that.

**Comment by joshmedeski** [comment]
Thanks, @aarohijohal for the quick response. That's what I'm gonna do 👍

**Comment by jethrokuan** [comment]
I too keep my `org-roam.db` out of the directory, so dropbox doesn't sync it. The database can be recomputed from the org files at the moment and will likely stay so for the forseeable future, so no need to commit it with your org files.

**Comment by herop** [comment]
But then I need to point at the file explicitly in customize org-roam, right?
Dues that apply for both, sql3 and emacsql?
Please point me to the best practice advice.
Thank you.

**Comment by jethrokuan** [comment]
You just need to set something like this in your config:

```
(setq org-roam-db-location "/home/herop/org-roam.db")
```

**Comment by IronicBadger** [comment]
Is there any requirement on either host to `org-roam-db-build-cache` periodically? How are changes picked up?

**Comment by jethrokuan** [comment]
> Is there any requirement on either host to org-roam-db-build-cache periodically? How are changes picked up?

That's done once during activation of `org-roam-mode`, and the cache is kept consistent during file saves, so nothing needs to be called manually.

**Comment by IronicBadger** [comment]
Sorry if I wasn't clear. I meant if I have two systems, and the db file is not synced between them what happens if I update a file one system 1 and it syncs to system 2. How does the db on sys2 know that change happened?

**Comment by jethrokuan** [comment]
The db will not update automatically. But when you're on sys2 and do anything that calls a save-file or an `org-roam-db-build-cache` on that file, the db on sys2 will update accordingly. This happens when you launch `org-roam-mode`, so if you don't run a long-running Emacs instance, this is typically not an issue.

**Comment by IronicBadger** [comment]
It's hard to describe just how great this software is. Thanks Jethro.
