### ISSUE TITLE
emacsql-error "no such table: tags"

### ISSUE THREAD

**Issue by jueqingsizhe66** [org-roam/org-roam#685]
### Description

Windows10 platform with newest version of org-roam
（org-roam works well in the older version, now just have no idea to fix it）
The bugs just right below by executing org-roam-insert 

After installing the newest version of org-roam, reopen emacs, "Updating org-roam-db version 3 to 5 " is shown in the minibuffer.
 
#### Steps to Reproduce

1. `org-roam-insert`

#### Backtrace

`Debugger entered--Lisp error: (emacsql-error "no such table: tags")
  signal(emacsql-error ("no such table: tags"))
  #f(compiled-function (_ code message) "Get condition for MESSAGE provided from SQLite." #<bytecode 0x5082cd9>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> 1 "no such table: tags")
  apply(#f(compiled-function (_ code message) "Get condition for MESSAGE provided from SQLite." #<bytecode 0x5082cd9>) #<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> (1 "no such table: tags"))
  emacsql-handle(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> 1 "no such table: tags")
  #f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x23677fd>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8>)
  apply(#f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x23677fd>) #<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> nil)
  emacsql-parse(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8>)
  #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x4d876a9>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> [:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)])
  apply(#f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x4d876a9>) #<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> [:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)])
  emacsql(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> [:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)])
  apply(emacsql #<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> [:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)] nil)
  org-roam-db-query([:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)])
  org-roam--get-title-path-completions()
  org-roam-insert(nil)
  funcall-interactively(org-roam-insert nil)
  #<subr call-interactively>(org-roam-insert record nil)
  apply(#<subr call-interactively> org-roam-insert (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> org-roam-insert record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (org-roam-insert record nil))
  call-interactively(org-roam-insert record nil)
  command-execute(org-roam-insert record)
  counsel-M-x-action("org-roam-insert")
`

#### Actual Results

`org-roam-insert` failed.

### Environment

- Emacs: GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32)
 of 2018-05-04
- Framework: N/A
- Org: Org mode version 9.3.6 (9.3.6-71-g7684b5-elpaplus @ c:/Users/AppData/Roaming/.emacs.d/elpa/org-plus-contrib-20200518/)
- Org-roam: 1.1.1

**Comment by progfolio** [comment]
Try executing `C-u M-x org-roam-db-build-cache`. 
This should force a rebuild of the database cache.
Then try `org-roam-insert`.

**Comment by jueqingsizhe66** [comment]
It works.  
1. Delete org-roam.db file in the org-roam folder(rebuild my database again, not a good idea!)
2. then execute `org-roam-db-build-cache` in the org-roam mode.(`org-roam-db-build-cache` cannot automatics relink every file in the org-roam folder )

thanks

**Comment by jueqingsizhe66** [comment]
Great, the new version of org-roam execute `org-roam-graph` can present the figure inside my emacs environment.
