### ISSUE TITLE
There is no org-roam-backlink

### ISSUE THREAD

**Issue by notuntoward** [org-roam/org-roam#690]
The org-roam docs [here](https://org-roam.readthedocs.io/en/master/configuration/) mention that you can change the backlink face with `M-x customize-face org-roam-backlink`.  But there is no face called `org-roam-backlink`

**Comment by progfolio** [comment]
Thank you.

It looks like this was changed in #516 as a result of #515.
The documentation was not updated.
That face was replaced with `org-roam-link-current`.

**Comment by progfolio** [comment]
FYI: That readthedocs is likely outdated in more ways.
If you are familiar with `info` manuals there is one included in Emacs.
It can be accessed at https://org-roam.github.io/org-roam/manual/ as well.

**Comment by notuntoward** [comment]
Thanks, I'll stick with info for now.
