### ISSUE TITLE
Uninformative error message when forget C-c c

### ISSUE THREAD

**Issue by notuntoward** [org-roam/org-roam#693]
Say that I've just created a new note, say note1, with `M-x org-roam-find-file` and then in note1, I immediately try to create a link to another new, non-existent note, using `M-x org-roam-insert`.  If I do this, then I see the following error message:

> user-error: Nested Org-roam capture processes not supported

It took me a while to realize that, before I create a new link in a newly created note, I must first hit `C-c c`

A new user like me won't know how not hitting `C-c c` causes a nested capture, or even what a nested capture is.

**Comment by progfolio** [comment]
Thank you for the report.

When a capture is initiated, the  capture should have a header line which reads:
> Capture buffer. Finish `C-c C-c`, refile `C-c C-w`, abort `C-c C-k`.

This is the same way org-capture works.

For now we do not support nested captures, but we will in the future.
I realize a number of our users are trying out Emacs for the first time or may not have much experience with it. We'll have to find a balance between our documentation becoming a "How To Emacs" guide and being empathetic with inexperienced users. Supplemental material (how-to articles, videos, etc) will hopefully fill some of these gaps in the future.

If you have a suggestion to improve this, please feel free to let us know or submit a pull request.

@jethrokuan: Thoughts?

**Comment by TimQuelch** [comment]
Doesn't `org-roam-find-file` open the file after the capture anyway? I have my capture template set up with `:immediate-finish t` and when I find file on a non-existing note it will just create the new file and open the buffer with it; no capture buffer at all.

Maybe including this in the default template will be a bit smoother experience for new users not familiar with `org-capture`

**Comment by notuntoward** [comment]
@TimQuelch, making `:immediate-finish t` seems to me like a good default.  It would avoid an obscure error, and I don't know of any downsides (but then again, I am just now trying out `org-roam`)

@progfolio it seems like #691 would clarify the error message a bit, is that right?

**Comment by progfolio** [comment]
It's the same message, it just happens earlier.

**Comment by jethrokuan** [comment]
> @TimQuelch, making :immediate-finish t seems to me like a good default. It would avoid an obscure error, and I don't know of any downsides (but then again, I am just now trying out org-roam)

If you use `:immediate-finish t`, then during `org-roam-insert`, when you create a new note, you cannot make any small additions without browsing to the file.

> We'll have to find a balance between our documentation becoming a "How To Emacs" guide and being empathetic with inexperienced users. Supplemental material (how-to articles, videos, etc) will hopefully fill some of these gaps in the future.

Yeah, I'd like to keep the manual as specific to Org-roam as possible, but covering some of the common pitfalls somewhere. I'm thinking of mentioning this in the interactive tutorial I have planned to be in the manual.

**Comment by TimQuelch** [comment]
> If you use `:immediate-finish t`, then during `org-roam-insert`, when you create a new note, you cannot make any small additions without browsing to the file.

That's fair

**Comment by zaeph** [comment]
#532 will solve this when we get back to it.  It's on stand-by because we're not sure whether to move away from org-capture.

**Comment by jethrokuan** [comment]
Closed with #966, nested captures are now supported.
