### ISSUE TITLE
combining org-cliplink with org-clipmon, because you mentioned org-cliplink elsewhere

### ISSUE THREAD

**Issue by michaelsjackson** [org-roam/org-roam#694]
You mentioned org-cliplink in one of your blog posts, I guess.

There is also org-clipmon, I think a combination of both would be great.

Here more details about the idea.  Thanks in advance.

https://github.com/bburns/clipmon/issues/22

**Comment by jethrokuan** [comment]
While interesting, this issue is irrelevant to org-roam, and there's not much I can do about it

**Comment by michaelsjackson** [comment]
No problem, you are right, I actually just added here, just you might like it as well.  Making things a little more user friendly or quicker.  Thanks for org-roam, did not test it yet, just had a quick look, but can comment in future here again. Have a nice day my friend.
