### ISSUE TITLE
org-roam-graph does not generate edges if org-roam-directory has trailing slash

### ISSUE THREAD

**Issue by rboyd** [org-roam/org-roam#695]
### Description

org-roam is shaping up to be awesome, thanks for all the work you've put into building and writing about it. I love it.

I had set my `org-roam-directory` to include a trailing slash, copying from https://github.com/org-roam/org-roam/blob/80bc19cbda92a1ee0dbc9268bf3deec24aeafb08/README.md#L56

I was getting proper graphs until exiting/restarting emacs. Thereafter, graphs only contained nodes. I stepped through the graph generation code and saw the edge query coming back empty, and looking at the links table in the sqlite db I noticed the filenames were getting my trailing slash prepended (ie. `.d` in sqlite console returned rows like `INSERT INTO titles VALUES('"/Users/b/org-roam//20200524102525-cars.org"','("cars")');`

It works great without the trailing slash in `org-roam-directory`.

### Environment
- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
 of 2019-09-02
- Framework: N/A
- Org: Org mode version 9.3.6 (9.3.6-71-g7684b5-elpa @ /Users/b/.emacs.d/elpa/org-20200518/)
- Org-roam: 1.1.1

**Comment by jethrokuan** [comment]
@rboyd are you still seeing this issue? My suspicion is that the new addition in #664 resulted in some bad paths. Can you check if `(org-roam--list-all-files)` returns paths with double slashes?

**Comment by jethrokuan** [comment]
Are you using Deft? I now suspect it's deft munging the buffer file name.

**Comment by d12frosted** [comment]
@jethrokuan for me `(org-roam--list-all-files)` returns paths with double slashes. I am on 7200364.

**Comment by jethrokuan** [comment]
This should be fixed by #735, do reopen if it's still an issue.
