### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by mohit-patel** [org-roam/org-roam#697]
When I try to install package, it says "No match". Do I need to have some settings correct before I can install package?
I am on Emacs 26.3 and a complete novice.

**Comment by progfolio** [comment]
See #582

**Comment by mohit-patel** [comment]
I have tried that and now again. Still no match.

**Comment by jethrokuan** [comment]
Have you added the MELPA repo to your configuration? https://melpa.org/#/getting-started

**Comment by mohit-patel** [comment]
Ahh. That was the issue. I’m sorry for such a silly mistake. Thank you for
clearing that up.
I have given a lot of time to Emacs and org mode but I simply can’t get it
to work. Too many things I need to sort. I am having to learn too many
things and still can’t get org agenda to work with multiple files, or how
to save files to gdrive /Dropbox. Wish there was a settings file I could
copy.

Thank you.

**Comment by jethrokuan** [comment]
You can install Doom Emacs, which has a decent starting `org-roam` configuration, as well as support for other things.
