### ISSUE TITLE
About generic UUID or Timestamp filename for new file created in org roam ?

### ISSUE THREAD

**Issue by reyman** [org-roam/org-roam#699]
### Brief Abstract

Reading about Zettelkasten, i found that using UUID or YYMMDDHHMM generic timestamp to design filename was an interesting feature. No need to think about the filename, only the content is important and change. 

I don't found documentation on this for org-roam. 

Could you propose a capture template or something similar to reproduce this behavior ?

**Comment by jethrokuan** [comment]
If you want the YYMMDDHHMM timestamp format, you can do:

```
(setq org-roam-capture-templates
  '(("d" "default" plain (function org-roam-capture--get-point)
     "%?"
     :file-name "%<%Y%m%d%H%M%S>"
     :head "#+TITLE: ${title}\n"
     :unnarrowed t)))
```

and if you want a random uuid, you can probably go fancy and shell out to `uuidgen`:

```
(setq org-roam-capture-templates
  '(("d" "default" plain (function org-roam-capture--get-point)
     "%?"
     :file-name "%(shell-command \"uuidgen\" t)"
     :head "#+TITLE: ${title}\n"
     :unnarrowed t)))
```

**Comment by jcguu95** [comment]
Thanks to this thread now I know why my template is not working.. I wrongly read the variable `org-roam-capture-templates` as that of `org`'s original one. It would be nice if this can be emphasized in the [current document](https://org-roam.github.io/org-roam/manual/Template-Walkthrough.html#Template-Walkthrough). Thank you so much for the hard work!

**Comment by aaaawwWWWwwwwWWW** [comment]
> and if you want a random uuid, you can probably go fancy and shell out to `uuidgen`:
> 
> ```
> (setq org-roam-capture-templates
>   '(("d" "default" plain (function org-roam-capture--get-point)
>      "%?"
>      :file-name "%(shell-command \"uuidgen\" t)"
>      :head "#+TITLE: ${title}\n"
>      :unnarrowed t)))
> ```

just a heads up, the uuid needs to be formatted as string, otherwise won't work.
```
(after! org-roam
  (setq org-roam-capture-templates
        `(("d" "default" plain (function org-roam-capture--get-point)
           "%?"
           :file-name "%(format \"%s\" (shell-command \"uuidgen --random\" t))"
           :head "#+TITLE: ${title}\n"
           :unnarrowed t))))
```
