### ISSUE TITLE
doct integration

### ISSUE THREAD

**Issue by IronicBadger** [org-roam/org-roam#704]
### Brief Abstract

Integrate with doct for declarative template definitions

### Long Description

[doct](https://github.com/progfolio/doct) allows you to declare templates declaratively for org-mode and works **mostly** for org-roam. Full support for `doct` would be perfect. 

### Proposed Implementation (if any)

I opened [issue 16](https://github.com/progfolio/doct/issues/16) on the `doct` github which contains all the details of how I'm attempting to use it with org-roam.

### Please check the following:

- [x] No similar feature requests

**Comment by zaeph** [comment]
Here's a functional link to the issue to help relating them: progfolio/doct/issues/16.

**Comment by jethrokuan** [comment]
looks like this was handled with upstream config.

**Comment by spacekitteh** [comment]
V2 has broken that.

**Comment by spacekitteh** [comment]
This is my template after doct:
```elisp
((#2="p" #1="Plain note" plain #'org-roam-capture--get-point #3=":THOUGHTS:
:END:
%i%?" :doct
(:doct-name #1# :keys #2# :type plain :function org-roam-capture--get-point :template #3# :org-roam
			(:if-new
			 (file+head #4="%<%Y%m%d%H%M%S>-${slug}" #5="#+title: ${title}
#+FILETAGS: :WIP:needs_tags:
")
			 :unnarrowed t)
			:doct-custom
			(:org-roam
			 (:if-new
			  (file+head #4# #5#)
			  :unnarrowed t)))
:if-new
(file+head #4# #5#)
:unnarrowed t))
```
It complains that there is no `:if-new` property, but there clearly is.

**Comment by spacekitteh** [comment]
If I remove the `#'org-roam-capture--get-point`, it seems to work.

**Comment by spacekitteh** [comment]
@jethrokuan is it possible to ignore the point function?

**Comment by jethrokuan** [comment]
> @jethrokuan is it possible to ignore the point function?

I don't think this is a good idea: this feels like it would be masking a user-configuration error (e.g. user might actually want to use a different function but it is ignored)

**Comment by vherrmann** [comment]
I've wrote a package for this here: https://gist.github.com/vherrmann/f9b21eeea7d7c9123dc400a30599d50d, that should iirc work for org-roamv2

**Comment by bdarcus** [comment]
By way of update, prog has started steps to add doct to org itself, so would probably be good to sort this out before the next org release.

**Comment by hpfr** [comment]
> [bdarcus](https://github.com/bdarcus)
> [on Sep 29, 2022](https://github.com/org-roam/org-roam/issues/704#issuecomment-1262260098)
> 
> By way of update, prog has started steps to add doct to org itself, so would probably be good to sort this out before the next org release.

@progfolio out of curiosity did you plan to upstream the Doct syntax? Looks like you got some [plumbing](https://list.orgmode.org/871qrkmbpl.fsf@localhost/) in which Bruce was referring to but I don’t see anything more recent than that.

**Comment by progfolio** [comment]
> > [bdarcus](https://github.com/bdarcus)
> > [on Sep 29, 2022](https://github.com/org-roam/org-roam/issues/704#issuecomment-1262260098)
> > 
> > By way of update, prog has started steps to add doct to org itself, so would probably be good to sort this out before the next org release.
> 
> @progfolio out of curiosity did you plan to upstream the Doct syntax? Looks like you got some [plumbing](https://list.orgmode.org/871qrkmbpl.fsf@localhost/) in which Bruce was referring to but I don’t see anything more recent than that.

It's on a very long TODO list of mine :)
