### ISSUE TITLE
Backlinks are gone (they used to be there when org-ref was installed)

### ISSUE THREAD

**Issue by publicimageltd** [org-roam/org-roam#705]
### Brief Abstract

I cannot use the backlink functionality, because I do not use `org-ref`.

### Long Description

For diverse reasons, I will not use `org-ref`. However, as soon as I disabled `org-ref`, the backlinks functionality did not work anymore. I think this is a very problematic dependency. For several reasons:
 
- `org-ref` is difficult to install and has many dependencies itself
- it mixes with `helm-bibtex` (see issue org-ref/#588)
- we could replace the org-ref format with a link, which would yield in a much nicer display. That is, cite: would become an org link (`[[cite:therefrence][nice title or so]]`)

### Proposed Implementation (if any)

No idea, sorry.

### Please check the following:

- [X] No similar feature requests

**Comment by TimQuelch** [comment]
As far as I was aware `org-ref` is not a hard dependency and `org-roam` should work fine if you do not have `org-ref` installed/enabled

**Comment by notuntoward** [comment]
>     * we could replace the org-ref format with a link, which would yield in a much nicer display. That is, cite: would become an org link (`[[cite:therefrence][nice title or so]]`)

This addresses only a small part of the `org-ref` objection, but at least I can say that it's possible to make `org-ref` links look prettier.  I also don't like their look, although I do like them overall.  To make them prettier, I do the following

> (org-link-set-parameters "cite" :display nil)

This will [mess up Latex export](https://github.com/jkitchin/org-ref/issues/345#issuecomment-262646855) but apparently only that export type, and anyway, it can be undone before Latex exporting.  I'm also not sure anybody will export directly from `org-roam`.

**Comment by jethrokuan** [comment]
Org-ref is indeed not a hard dependency, and not having it installed should not have adverse effects like this. You should still see regular backlinks. If you `toggle-debug-on-error`, do you see any errors?

**Comment by publicimageltd** [comment]
OK on second try, I cannot reproduce the problem anymore. Fact is: I had backlinks, then I decided to throw `org-ref` out, and then they were gone. They are gone now again, regardless whether I require `org-ref` or not. 

Just to be sure: Backlinks should be recognized even if the text `cite:xxxxx` will not be highlighted, is that right? Highlighting seems to be done by `org-ref`. 

Is there any way to check the handling of backlinks programmatically? Currently, I always have to restart emacs once I required `org-ref`, so it is rather hard to find out. Also, I rely on the display of the side buffer. I would prefer just looking at a variable, or calling a function, to test it.

BTW, thanks for the fast replies, and also thumbs up for a good and interesting project!

**Comment by TimQuelch** [comment]
`org-ref` is used to handle citation links (e.g. cite:, autocite:, parencite: etc.) whereas normal backlinks are handled by ordinary org-mode file links which can be inserted by `org-roam-insert`

**Comment by jethrokuan** [comment]
> Just to be sure: Backlinks should be recognized even if the text cite:xxxxx will not be highlighted, is that right? Highlighting seems to be done by org-ref.


I don't think so, because if org-ref isn't loaded, it will not be recognized as an org link in the AST, so they won't be picked up.

However, regular file links still produces backlinks.

**Comment by publicimageltd** [comment]
> I don't think so, because if org-ref isn't loaded, it will not be recognized as an org link in the AST, so they won't be picked up.
> 
> However, regular file links still produces backlinks.

Then that seems to be the problem I had. I am talking about the citation links in the backlink window, the ones "below" the normal backlinks, also called "cite backlinks". 

Do I understand correctly, then, that "cite backlinks" *do* actually depend on `org-ref` activated?

If that is case, I propose to either (a) not mention cite backlinks if `org-ref` is not provided as a feature; or to (b) alternatively recognize citations even w/o `org-ref`. Does that make sense? I am still struggling with some aspects of the conceptual structure of the tool...

**Comment by jethrokuan** [comment]
> Do I understand correctly, then, that "cite backlinks" do actually depend on org-ref activated?

Yes, `cite:` links is a feature specific to `org-ref`. If you don't have `org-ref`, then it shouldn't show up in the org-roam buffer at all, which seems to me like consistent behaviour. So I'm not sure what you mean by "not mention cite backlinks", because if you don't have org-ref on your system, it shouldn't show up.

I don't think recognizing citations even w/o org-ref would be a good idea, why would you use `cite:` over file links without org-ref?

**Comment by publicimageltd** [comment]
> So I'm not sure what you mean by "not mention cite backlinks", because if you don't have org-ref on your system, it shouldn't show up.

If I open the org roam backlink buffer (the side window, by pressing `C-c n l`), I see an org mode tree with two top items: The first headline says `n backlinks`, the second one says `n cite backlinks` (n being either `No` or a number). So I thought that for every org roam buffer, there will be a list of both normal file backlinks and cite backlinks. Yet the second heading is always empty. I understand now that this  is due to  `org-ref` missing, because the second heading only lists  links created by the pseudo-link `cite:....`.  Therefore, if `org-ref` is not featured, it makes no sense to show this second heading, simply because it will always be empty. It suggests something that will never be there.

> I don't think recognizing citations even w/o org-ref would be a good idea, why would you use `cite:` over file links without org-ref?

I like the idea of having a separate type of link for citations only. Lots of my notes are comments and thoughts, where I refer to some authors via regular backlinking. But often, I also copy quotations and the like. It seems very useful to have a list which shows me both type of links separately, as the side window (`C-c n l`) does. It allows me to see that there are links which I have created intentionally, as well as it gives me an overview of all the material I have accumulated unintentionally over time just by hacking in some quotes. Further, such a differentiation allows to explicitly search for citations only, e.g. if I know a author has said something yet don't know exactly what and where.
 
Generally, though, I would agree that this feature is just a nice-to-have. Yet I think questions of this kind will pop up again and again. A "link" is a very underdetermined relation, and I can imagine hundreds of use cases where it makes sense to introduce different *kinds* of links. So maybe a better approach would be to consider implementing some kind of type system for links.
 
Actually, you already have a link type differentiation via `#+ROAM_KEY`. However, I think differentiating link types by file name and location would be easier to handle. For example: book notes are usually created by the function `bibtex-completion` and thus have a fixed format. Therefore, every link pointing to such a file name could be automatically recognized as being of one type (say, "cite link"), while links pointing to other file names are treated as "file links".

**Comment by jethrokuan** [comment]
> Therefore, if org-ref is not featured, it makes no sense to show this second heading, simply because it will always be empty. It suggests something that will never be there.

It shouldn't show, if you don't have `org-ref` available in your load path. If it does, it is a bug, but I had checked earlier that this shouldn't be the case. Simply not using it is not enough, if `org-ref` is detected on your machine, `org-roam` assumes you use it and will load the `org-ref` related features.

> So maybe a better approach would be to consider implementing some kind of type system for links.

You may be interested in the link tags demo and discussion on Discourse: https://org-roam.discourse.group/t/add-link-tags-feature/171

> Actually, you already have a link type differentiation via #+ROAM_KEY. However, I think differentiating link types by file name and location would be easier to handle. 

Org-roam tries not to give meaning to filenames: everyone has their own preferences. For literature references, you may look at https://github.com/org-roam/org-roam-bibtex, there's a video there showing how the whole ecosystem works together.

**Comment by publicimageltd** [comment]
> It shouldn't show, if you don't have org-ref available in your load path. 

Looking at the code, I see what you mean. The function `org-roam-buffer--insert-citelinks` actually checks for `org-ref`, and in my case, correctly. Yet still it does insert another heading saying "No citelinks" (in the else-clause of the if statement). This is what I take to be unnecessary, if not even confusing. In my view, this insert statement should be simply removed.  at least understand it now, finally. Thanks for your patience.

Thanks for the hint to `orb`. I have checked it out already, but here is the same problem: I don't want to install `org-ref`, and ORB seems to rely on it. So no, I guess that will not be my way of using `org-roam`.

And thanks for the discussion on link tagging, I will take a look!

**Comment by jethrokuan** [comment]
>The function org-roam-buffer--insert-citelinks actually checks for org-ref, and in my case, correctly. Yet still it does insert another heading saying "No citelinks" (in the else-clause of the if statement). This is what I take to be unnecessary, if not even confusing.

Yes you're absolutely right, it's confusing. I've cleaned up when that section shows in #714 and #717 . Let me know if there's anything else to be fixed.

**Comment by publicimageltd** [comment]
Thanks a lot! I am seriously impressed by the way the issue has been taken seriously, and how a good answer developed. Also, I am impressed by the amount of communication which is already happening around `org-roam` (in discorse, here in github). Great!
