### ISSUE TITLE
org-roam-graph failed

### ISSUE THREAD

**Issue by 101scholar** [org-roam/org-roam#707]
### Description

When I call org-roam-graph, nothing happens except minibuffer shows "Search failed [^\11\n\15 -퟿-�𐀀-􏿿]"

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam-graph`

#### Backtrace

Debugger entered--Lisp error: (search-failed "[^\11\n\15 -퟿-�𐀀-􏿿]")
  re-search-forward("[^\11\n\15 -퟿-�𐀀-􏿿]")
  xml-escape-string("/media/xiertopia/2-grocery/test_dir/20200527095657-test.org")
  org-roam-graph--dot([:select [file titles] :from titles])
  org-roam-graph--build(nil org-roam-graph--open)
  org-roam-graph(nil)
  funcall-interactively(org-roam-graph nil)
  call-interactively(org-roam-graph nil nil)
  command-execute(org-roam-graph)

#### Expected Results

Show graph

#### Actual Results

Search failed error

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
 of 2020-05-24
- Framework: N/A
- Org: Org mode version 9.3 (release_9.3 @ /usr/share/emacs/28.0.50/lisp/org/)
- Org-roam: 1.1.1

**Comment by progfolio** [comment]
Thank you for the report.

Can you try the following? If you hit an error at any point, please paste the full backtrace here:
- Exit Emacs
- Delete the `org-roam.db` file in your `org-roam-directory`
- Start Emacs from the command-line with the `--debug-init` flag.
- Evaluate the following:
```emacs-lisp
(let ((org-roam-list-files-commands nil)
      (debug-on-error t))
  (org-roam-mode)
  (org-roam-graph))
```

**Comment by 101scholar** [comment]
Thank for replying. This is what I get when evaluating the elisp script:

```
Debugger entered--Lisp error: (search-failed "[^\11\n\15 -퟿-�𐀀-􏿿]")
  re-search-forward("[^\11\n\15 -퟿-�𐀀-􏿿]")
  xml-escape-string("/media/xiertopia/2-grocery/testdir/20200527124719-test.org")
  org-roam-graph--dot([:select [file titles] :from titles])
  org-roam-graph--build(nil org-roam-graph--open)
  org-roam-graph()
  (let ((org-roam-list-files-commands nil) (debug-on-error t)) (org-roam-mode) (org-roam-graph))
  (progn (let ((org-roam-list-files-commands nil) (debug-on-error t)) (org-roam-mode) (org-roam-graph)))
  eval((progn (let ((org-roam-list-files-commands nil) (debug-on-error t)) (org-roam-mode) (org-roam-graph))) nil)
  org-babel-execute:emacs-lisp("(let ((org-roam-list-files-commands nil)\n      (de..." ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:session . "none") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:lexical . "no")))
  org-babel-execute-src-block(nil ("emacs-lisp" "(let ((org-roam-list-files-commands nil)\n      (de..." ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:lexical . "no") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 1 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

This is my configuration of org-roam in `init.el`

```lisp
(require 'org-roam-protocol)
(use-package org-roam
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-directory "/media/xiertopia/2-grocery/testdir/")
      (org-roam-completion-system 'helm)
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n j" . org-roam-jump-to-index)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))))

(use-package org-roam-server
  :ensure t)
```

Within `org-roam-directory`, there's only one file `20200527124719-test.org` with content

```
#+TITLE: test

I try to write something here.
```

**Comment by 101scholar** [comment]
I think I've found the problem. It's about the emacs version.I log my experience here in case someone comes along the same issue.

My OS is Ubuntu 18.04.3 LTS. I install emacs by `sudo apt-get install emacs`. But the version is out-of-date and is not compatible with org-roam. So I reinstall it by adding some ppa and run `sudo apt-get install emacs-snapshot` and the emacs version becomes 28.0.50. That's where the problem arises. After I reinstall emacs again by adding another ppa and running `sudo apt-get install emacs26`, org-roam-graph just works! I think maybe emacs-snapshot is not stable or maybe there's some compatibility issue with org-roam.

Anyway, problem solved! Again, grateful for the prompt reply.
