### ISSUE TITLE
provide feedback if doctor runs without error

### ISSUE THREAD

**Issue by bdarcus** [org-roam/org-roam#710]
I tried doctor on a few buffers and got no output, so wasn't sure it was working.

I only confirmed by adding an obvious error it would flag.

Could you provide some visual indication that the doctor check passes?

**Comment by jethrokuan** [comment]
There's actually a message, but that's only output if `org-roam-verbose` is `t`, but Doom silences it. It's similar to how the cache is successfully updated, but no message is printed.

**Comment by bdarcus** [comment]
Ah, the cache thing also bothers me.

So Doom silence both regardless? If yes, it this worth reporting to them?

**Comment by jethrokuan** [comment]
You can just set it to `t` in your own config without making changes upstream: `(setq org-roam-verbose t)`

**Comment by bdarcus** [comment]
Thanks!
