### ISSUE TITLE
error on org-roam-find-file

### ISSUE THREAD

**Issue by bsiogs** [org-roam/org-roam#720]
### Description
runing `org-roam-find-file` does not work

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam-find-file` by 'M-x' or by keyboard shortcut 'C-C r f'

#### Backtrace
'Debugger entered--Lisp error: (wrong-type-argument characterp \,)
  org-roam--get-title-path-completions()
  org-roam-find-file()
  funcall-interactively(org-roam-find-file)
  call-interactively(org-roam-find-file nil nil)
  command-execute(org-roam-find-file)'
#### Expected Results

Helm completion mini-buffer for org-roam files selection opens
#### Actual Results

error

### Environment
Copy info below this line into issue:
- Emacs: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.32)
 of 2019-12-02
- Framework: 
- Org: Org mode version 9.3.6 (9.3.6-75-gb614ed-elpa @ /home/bs/.emacs.d/elpa/org-20200525/)
- Org-roam: 1.1.1
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
likely you have a comma in your ROAM_TAGS or ROAM_ALIAS

**Comment by bsiogs** [comment]
Ok, It's fixed !
 I find it difficult to manage titles or aliases of several words since the space character is also considered as a separator. Intuitively, I considered that it was possible to use the comma as a separator between two multi-word aliases. Maybe that would be something nice to handle.
Thanks for your help, I think it's time to close this short issue ?

**Comment by jethrokuan** [comment]
you use quotes to delimit a multiword alias:

```
"multi world alias" alias2
```

**Comment by bsiogs** [comment]
OK, thanks a lot.
