### ISSUE TITLE
Cannot find executable "sqlite3"!

### ISSUE THREAD

**Issue by anthrolisp** [org-roam/org-roam#722]
I updated all of my packages this morning, and I'm now getting a new error when calling org-roam-find-file:

Cannot find executable "sqlite3"!

Any thoughts? Thank you in advance!

**Comment by jethrokuan** [comment]
Previously, `org-roam` used `emacsql-sqlite`, which compiles a `sqlite3` executable. This proved to be a bit of an issue for Windows users, so we moved to `emacsql-sqlite3`, which uses the `sqlite3` binary. So you can simply install sqlite3 on whatever operating system you're on, and you should be good to go.

**Comment by anthrolisp** [comment]
Perfect. Works after installing sqlite3. THANKS FOR ALL OF YOUR WORK ON THIS!!!
