### ISSUE TITLE
`rg` returns bad paths for Windows users

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam#724]
### Description

As reported by @nobiot , the return results from the `rg` shell-out aren't nice paths, and cause downstream issues.

![image](https://user-images.githubusercontent.com/1667473/83146468-ede20d80-a128-11ea-8d24-1164cc8ea9e4.png)

`rg` was installed via scoop in this case.

### Environment

Commit 214f9df
Windows 10
Emacs: GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29 (via org-roam-diagnostics)

**Comment by nobiot** [comment]
@jethrokuan, thanks for keeping this as a separate issue. Much appreciated. 👍

**Comment by nobiot** [comment]
@jethrokuan 
#735 looks good with Windows 10. 

![image](https://user-images.githubusercontent.com/12507865/83347713-1e8f9600-a327-11ea-8d55-16ff1ef6ce21.png)
**Figure 1.** `org-roam--shell-command-files` still returns with `\\`; however...

![image](https://user-images.githubusercontent.com/12507865/83347757-8ba32b80-a327-11ea-8e89-1aaeb255d9c7.png)
**Figure 2.** Canonicalizing works :)

## Environment:
- Windows 10
- Emacs 26.3
- Commit b2594b8

## Procedure

0. Merge with latest master branch

1. Check org-roam works before using rg (i.e. `elisp` still works)

2. Change
  `(setq org-roam-list-files-commands '(rg elisp))`
  
3. Test
   `edebug-defun` on for `org-roam--list-files-rg` to doubly sure `org-roam` uses rg.
    Run `org-roam-db-build-cache`.

    Title change.
    Create/delete a new backlink.
    Create/delete a new cite backlink.
    Check C-c n i (org-roam-insert)
    Check alias works for org-roam-insert
    Create a note in an external editor while Emacs is on, run `org-roam-db-build-cache, see if a backlink are created from the newly created file

**Comment by nobiot** [comment]
@jethrokuan I did comparison of `elisp` and `rg` on my Windows machine; you might be able to take it further, if you are interested. 

https://org-roam.discourse.group/t/what-does-it-feel-like-to-work-with-10-000-notes-in-org-roam-benchmarking-org-roams-search-methods/227
