### ISSUE TITLE
Installing org-roam on WSL2 shows "org-9.3 is unavailable" error

### ISSUE THREAD

**Issue by eunchan** [org-roam/org-roam#726]
### Description

Tried to install org-roam on WSL2 (windows 10). after installing MELPA on Emacs-26.1, I got an error message that "Package 'org-9.3' is unavailable"

#### Steps to Reproduce

1. Install `emacs-nox` on WSL2
2. Install MELPA
3. Install org-roam

**Comment by jethrokuan** [comment]
Did you run `package-refresh-contents`?

**Comment by xianwenchen** [comment]
You gotta use Debian Buster, which is the testing version. There the GNU Emacs version is newer and contains an org version that is newer.

**Comment by xianwenchen** [comment]
So basically edit /etc/apt/sources.list by replacing Stretch with Buster, then run

```
sudo apt-get update
sudo apt-get upgrade
sudo apt dist-upgrade
```

**Comment by jethrokuan** [comment]
> There the GNU Emacs version is newer and contains an org version that is newer.

You can also install org 9.3 from MELPA, which is what MELPA would do when trying to install Org-roam.

**Comment by eunchan** [comment]
> Did you run `package-refresh-contents`?

Yes I did run it prior to.

**Comment by eunchan** [comment]
> > There the GNU Emacs version is newer and contains an org version that is newer.
> 
> You can also install org 9.3 from MELPA, which is what MELPA would do when trying to install Org-roam.

Unfortunately, not in this case. I searched `org` but not exists in the MELPA. Let me try @xianwenchen 's suggestion.

**Comment by eunchan** [comment]
Installed org-9.3 on WSL2 (Debian/buster)

Then tried to install `org-roam` again. Still showed same error org-9.3 is unavailable.

When run `org-vesion` on emacs:

```
Org mode version 9.3.6 (release_9.3.6-683-g3b2de4 @ /usr/share/emacs/site-lisp/org/)
```

**Comment by xianwenchen** [comment]
I didn't install elpa-org package, which is the Debian package for org. I use the emacs package, not emacs-nox. When I want to run emacs in a terminal, I run `emacs -nw`.

How did you install the org package? I thought orgmode became part of emacs. I remember that I didn't have to install org through MELPA. 

Could you try the normal emacs package instead of emacs-nox?

If nothing works, you may want to delete the previously installed packages using MELPA.

**Comment by progfolio** [comment]
MELPA and ELPA are two separate package archives

**Comment by eunchan** [comment]
@xianwenchen thanks for the comment. I installed `emacs` package. running with `-nw` argument didn't help though.

**Comment by eunchan** [comment]
I just compiled emacs-26.3 from the source code and install org-roam. So, this is no longer an issue to me. Thanks for the help all.
