### ISSUE TITLE
(wrong-number-of-arguments) from org-roam--list-files-elisp

### ISSUE THREAD

**Issue by nobiot** [org-roam/org-roam#736]
### Description

`M-x org-roam-db-build-cache` errors.

Please refer to this image and repro below.
![image](https://user-images.githubusercontent.com/12507865/83330092-4fbb8800-a28d-11ea-9288-0239e0a1cb5b.png)

@jethrokuan @ulfl, 
I apologize if I jump onto a conclusion too soon, but my sense is that this new feature (#733 ) is not compatible with the version of my Emacs (26.3, on Windows and Ubuntu via WSL).

Please advise if I should have done something prior to going on to the procedure I describe in the repro section below. I am sorry if directly pulling you two was premature; as the owner and reviewer of the PR, I thought it would be good if I brought this to your attention directly.

Function `directory-files-recursively` has the following signature.

```
Signature
(directory-files-recursively DIR REGEXP &optional INCLUDE-DIRECTORIES)
```

I see this change calls it with two additional arguments that the function is not defined for (?)
Sorry if I'm mistaken, but I thought `&optional INCLUDE-DIRECTORIES` allowed for only one (`t` or `nil`), not for 3 optional arguments, (`nil nil t`)?

#### Steps to Reproduce

- Start Emacs with emacs -Q
- In scratch buffer, paste this, and `M-x eval-buffer`
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```

- Install `org-roam` with the following manual commands:

```
M-x package-refresh-contents RET
M-x package-install RET org-roam RET
```

- Manually invoke `M-x org-roam-db-build-cache`

#### Backtrace
```
Debugger entered--Lisp error: (wrong-number-of-arguments (2 . 3) 5)
  directory-files-recursively("c:/Users/nobiot/org-roam/" "\\.\\(?:org\\)\\(?:\\.gpg\\)?\\'" nil nil t)
  org-roam--list-files-elisp("c:/Users/nobiot/org-roam/")
  org-roam--list-files("c:/Users/nobiot/org-roam/")
  org-roam--list-all-files()
  org-roam-db-build-cache(nil)
  funcall-interactively(org-roam-db-build-cache nil)
  call-interactively(org-roam-db-build-cache record nil)
  command-execute(org-roam-db-build-cache record)
  execute-extended-command(nil "org-roam-db-build-cache" nil)
  funcall-interactively(execute-extended-command nil "org-roam-db-build-cache" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
#### Expected Results

Not applicable

#### Actual Results

Not applicable

### Environment
Emacs: GNU Emacs 26.3 (build 1, x86_64-w64-mingw32)
 of 2019-08-29

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere
Melpa org-roam-20200530.1104

**Comment by jethrokuan** [comment]
Ah I suppose it's a new feature, my signature is:

```
Signature
(directory-files-recursively DIR REGEXP &optional INCLUDE-DIRECTORIES PREDICATE FOLLOW-SYMLINKS)
```

Guess we'll have to patch it for older Emacs.

**Comment by nobiot** [comment]
@jethrokuan, happy to update the package that contains this function, but symlink would be still a bit troublesome for Windows...

**Comment by jethrokuan** [comment]
> but symlink would be still a bit troublesome for Windows...

why is that?

**Comment by nobiot** [comment]
I'll go back to my notes for better reference later. There are three ways to achieve it: short cut, soft link, and hard link (the latter two are nicknames, there is documentation from Microsoft about this). It's probably too technical for common user base of Windows.

**Comment by jethrokuan** [comment]
The elisp implementation should handle all the weird differences in path handling between operating systems. It just allows for symlink support, you can still use it without symlinks.

**Comment by progfolio** [comment]
Looks like the signature was changed relatively recently:
https://github.com/emacs-mirror/emacs/commit/4529057c97322893fb415512a2a51bc4616754f7

Note that commit only added the `PREDICTATE`, so `FOLLOW-SYMLINKS` is even more recent (28.0.50)

**Comment by progfolio** [comment]
`FOLLOW-SYMLINKS`: https://github.com/emacs-mirror/emacs/commit/0779b1c31d27c348f6f2a94c5aa1a64de855a39d

**Comment by nobiot** [comment]
Just future reference (and reading pleasure for some).
All of this would be rather esoteric detail for normal Windows users (this includes me). 
I don't understand these, let alone make good use of them.

- [hard links and junctions](https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions)
- [symbolic link](https://docs.microsoft.com/en-us/windows/win32/fileio/creating-symbolic-links) (soft link)

- This [How to Geek](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) page also talks about how you can enable your Windows machine to perform symbolic links and hard links (via `mklink` command in `cmd`)
