### ISSUE TITLE
Is ist possible to exclude "orphaned" pages from the graph?

### ISSUE THREAD

**Issue by publicimageltd** [org-roam/org-roam#738]
I have more than 600 notes currently, but most of them are just notes from books which do not link  yet to anything. Is there an easy way to exclude them from the graph? Looking at `org-roam-graph.el`, I could'nt find anything.

Generally, it would be useful to have direct access to all files which are not yet linked to any other note (what I call 'orphaned'). 

Or, thinking about it, a number indicating how many links a page has. I at least would be interesting in knowing what page is linked most.

**Comment by d12frosted** [comment]
I know a hack, which works in some cases. Passing universal argument (e.g. `C-u`) to `org-roam-graph` shows only nodes related to the current note. Meaning that orphans won't be represented on graph. As well as other nodes that are not linked to your current note. On the other hand, you can use index... oh well... it works only in some cases 😸

**Comment by publicimageltd** [comment]
Thanks for the tipp, that's already a good idea. After posting the question, I have had a look into the internals of `org-roam` and think that at least the last idea posted would be relatively easy to implent (a list of pages along with how many links they contain). It's just an SQL query which joins the pages with the link list. My SQL is quite rusty, had been more than a decade I had worked with it, so it will take some time until I give it a try, but I will.

**Comment by zaeph** [comment]
I understand your use-case, but I'm not sure if it's something that we'd want.  The graph is actually a pretty good way to see which of your notes are orphan, which is not something that you want to have in your slip-box.

It wouldn't be too hard to have a measure of valency to atomic notes which would allow you to filter them out or to highlight them.  I'm not really working on the graphing capabilities, though, so I'd appreciate if someone could have a go at it.

**Comment by publicimageltd** [comment]
> the graph is actually a pretty good way to see which of your notes are orphan

I disagree. I have just moved all my notes to the org roam system, so I have some hundreds of "orphaned pages". Due to this, the graph is huge and, as a complete overview, unusable. You could of course say that this is only a transitory state because finally, everything will be linked with everything, but I am sure this transitory state will last quite some time.

**Comment by publicimageltd** [comment]
I have found the solution to my question. I have written a little package which, among other things, displays a list of 'orphaned' pages (see [github/org-roam-dashboard](url)).

**Comment by jethrokuan** [comment]
In Org-roam v2, this is an argument to the function: https://github.com/org-roam/org-roam/blob/2168490d5ada18629958788771e547d8c86fba20/org-roam-graph.el#L161-L163
