### ISSUE TITLE
org-roam-doctor thinks #+ROAM_KEY is broken

### ISSUE THREAD

**Issue by jgoerzen** [org-roam/org-roam#740]
### Description

When running (org-roam-doctor 't), I get:
```
Error message:
  Possible misspelled key: "ROAM_KEY"
  Org-roam supports the following keys: ROAM_TAGS, ROAM_ALIAS
```

and offers to let me skip or edit.  Of course these were inserted by the org-roam protocol as described in the manual, using the Firefox bookmarklet.

#### Expected Results

org-roam-doctor should not complain about this.

### Environment

- Emacs: GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5)
 of 2019-09-22, modified by Debian
- Framework: N/A
- Org: Org mode version 9.3.6 (9.3.6-75-gb614ed-elpaplus @ /home/jgoerzen/.emacs.d/elpa/org-plus-contrib-20200525/)
- Org-roam: 1.1.1

**Comment by TimQuelch** [comment]
https://github.com/org-roam/org-roam/pull/708 fixes the misspell checker for  so `ROAM_KEY`. Does it work with that?

**Comment by jethrokuan** [comment]
Thanks for responding@TimQuelch

**Comment by herop** [comment]
Do I need #+ROAM_KEY?
Org-Roam won't recognize #+FILETAGS?
My Windows Emacs won't recognize #+ROA <ESC><TAB>
What am I missing here?
