### ISSUE TITLE
Run performance tests in CI

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam#742]
### Brief Abstract

Perform performance testing on blocking functions.

### Long Description

In Discourse (https://org-roam.discourse.group/t/what-does-it-feel-like-to-work-with-10-000-notes-in-org-roam-benchmarking-org-roams-search-methods/227/4), @nobiot performed some performance testing on knowledge bases of different scales.

I'd like to have these tests included somehow in the CI, and throw warnings when they become too slow.

### Proposed Implementation (if any)
Have an additional testing file that fetchs a large org-roam knowledge base and run tests based on it.

### Please check the following:

- [ ] No similar feature requests

**Comment by nobiot** [comment]
Hi @jethrokuan, I took the liberty of generating [10,000 org files ](https://github.com/nobiot/10000-org-files)with using [Zettelkasten-Method's 10,000 markdown files](https://github.com/Zettelkasten-Method/10000-markdown-files) and [fabioberger's Roam-migration ](https://github.com/fabioberger/roam-migration). 

You can store the files in Org-roam project's repo if you see that convenient for CI. I'm using my repo purely as a file exchange vehicle. 

I have yet to find a way to add links among these files distributed in a reasonably realistic way (perhaps with clusters, etc.), so there are no links in the them. I'm guessing the folks working on the graph functions might find that as an interesting challenge ;)

**Comment by nobiot** [comment]
Just tried the zip file on my repo with my Ubuntu Linux (via WSL, Windows Subsystem for Linux) on the same machine. Linux could not unzip it... Just wanted to note this issue here. I’ll work something out — this is for my sanity, so no worries if you don’t use the repo, or anything I’m doing here 👍

**Comment by jethrokuan** [comment]
I took a look at the org files, and noticed there were no links, so links between them, so probably not so suitable for benchmarking.

**Comment by zaeph** [comment]
We can probably append links to the files by fetching files at random.  Chances are it'll generate some depths as well.  Pretty sure it'd introduce recursions too, though. 🤔

**Comment by nobiot** [comment]
Yes, I agree. Just did a little script to add links and, tested last night. I’ll put my files and script later, hopefully today l.

**Comment by nobiot** [comment]
Here is the [repo (new one)](https://github.com/nobiot/10000-org-files-linked). I will add more explanation and describe my outcome later, but very briefly:
- Go straight to 10000-org-files-max-25-links. 
  This is the one that took 3 hours for `org-roam-db-build-cache` to finish. The resultant DB file (zipped) and script to append links are there, too (very simple)
- Recommend NOT to use 10000-org-linked-files and add-md-links.el for now...
  The variable is set to add max 500 (!) links. It took 26-27 hours to finish. I could not wait for the DB cache to build (I had to work the next morning after 8 hours or so of running `org-roam-db-build-cache`.

**Comment by jethrokuan** [comment]
I have some idea where the slowdown is, but will probably do proper profiling, after release 1.2 (which is after #787 and #783 )
