### ISSUE TITLE
Package does not function: "Selecting deleted buffer" error

### ISSUE THREAD

**Issue by anthbrtn** [org-roam/org-roam#746]
### Description
Any and all org-roam functions do not work when called. Error in message section is `apply: Selecting deleted buffer`. All functions give this error except for `org-roam-db--get`, which returns `funcall-interactively: Wrong number of arguments: (0 . 0), 1`.

#### Steps to Reproduce
1. Load Emacs
2. Run `org-roam-capture`, or any other function defined by `org-roam`.
**alternatively**
1. Run `:hook (after-init . org-roam-mode)` in `use-package` declaration and immediately receive `Selecting deleted buffer` error upon loading emacs.

#### Backtrace
```
Entering debugger...
Args out of range: "", 0
```
#### Expected Results
Can access `org-roam` functionality

#### Actual Results
Cannot access `org-roam` functionality.

### Environment
- Emacs: GNU Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.13)
 of 2020-01-28
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/foo/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.1.1
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/b2594b84aef131ab24dd477a4bd7b2d1a6ca7621

This happened on a fresh install of Fedora 32.

**Comment by progfolio** [comment]
If you are still hitting these errors, would you mine setting `debug-on-error` to `t` and pasting the full output of the backtrace buffer here?

**Comment by anthbrtn** [comment]
Apologies for the delay -- I'm not getting these errors anymore for whatever reason. I did, however, notice that they were occurring when I put `(setq org-roam-directory "~/documents/notes/")` in the `:config` block under use-package, as opposed to `:custom`. Changing it to `:custom` solved my problem.

**Comment by jaza-syed** [comment]
# Description

**Comment by jaza-syed** [comment]
I'm getting a similar error. The relevant section of my config is 
```
(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory "~/notes")
  (org-roam-index-file "index.org"))
```
I'm running emacs in a terminal using emacsclient, and have `(setq debug-on-error t)` at the top of my `config.el`. The daemon starts up fine, but when I try to run emacslient I get this trace
