### ISSUE TITLE
Cannot split org-roam window

### ISSUE THREAD

**Issue by crbinz** [org-roam/org-roam#752]
### Description
When I open the `org-roam` window with `C-c n l`, emacs will not let me split it (it gives the message `Cannot split side window or parent of side window`. It would be nice to be able to split this window. If I open the org-roam buffer in an existing window, it allows me to split the window like normal.

#### Steps to Reproduce
1. `M-x org-roam-buffer-toggle-display` (or `C-c n l`)
2. Switch to org-roam buffer
3. Try to split the window vertically with `M-2` 

#### Expected Results
The window gets split vertically.

#### Actual Results
The window does not split, emacs displays `Cannot split side window or parent of side window`.

### Environment
```
- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
 of 2019-09-02
```

**Comment by jethrokuan** [comment]
Do you have a particular reason you want to split this window? The org-roam backlinks buffer is currently displayed in what Emacs terms a side window: https://www.gnu.org/software/emacs/manual/html_node/elisp/Side-Windows.html

These windows aren't splittable by default. There's also no reason it has to be a side window, and I feel that this is a decision we might retract on when Org-roam eventually grows to accept more complex workflows.

**Comment by crbinz** [comment]
> Do you have a particular reason you want to split this window?

Just that I often use emacs in full screen on a large monitor, and I find that giving the org-roam buffer an entire side results in a lot of wasted space, for me.

**Comment by jethrokuan** [comment]
On master commit, the buffer respects `display-buffer-alist` so you can split the window if you don't set it to be a side-window.
