### ISSUE TITLE
`roam-ref` with qutebrowser

### ISSUE THREAD

**Issue by jcguu95** [org-roam/org-roam#753]
### Description

This is about the content in the [documentation:12.4:The roam-ref Protocol](https://org-roam.github.io/org-roam/manual/The-roam_002dref-Protocol.html#The-roam_002dref-Protocol).

It suggests to add keybindings to qutebrowser in `autoconfig.yaml`

```
[..]
        gc: open javascript:void(location.href='org-protocol://roam-ref?template=r&ref='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title))
```
However, this is not recommended by qutebrowser, as stated in `autoconfig.yaml`:

```
# DO NOT edit this file by hand, qutebrowser will overwrite it.
# Instead, create a config.py - see :help for details.
```

My attempt in `config.py` does not work. Evaluating the following javascript leads to "No output or error".

```
config.bind("gcc", "jseval void(location.href='org-protocol://roam-ref?template=r&ref='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title))")
```

**PS** I have my emacs config set:

```
(require 'org-roam-protocol)
(setq org-roam-ref-capture-templates
        '(("r" "this" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "${slug}"
           :head "#+SETUPFILE:./hugo_setup.org
,#+ROAM_KEY: ${ref}
,#+HUGO_SLUG: ${slug}
,#+TITLE: ${title}

- source :: ${ref}"
           :unnarrowed t)))
```

----

Related:
+ https://github.com/org-roam/org-roam/issues/217
+ https://github.com/org-roam/org-roam/issues/536

**Comment by jcguu95** [comment]
Update to this issue:

Evaluating the following does work for me in qutebrowser

```
config.bind("gcd", "jseval void(location.href='org-protocol://roam-file?file=/tmp/test.org')")
```

**Comment by jethrokuan** [comment]
Don't use qutebrowser, so i'm not sure. does evaluating this manually work?

```
location.href='org-protocol://roam-ref?template=r&ref='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title))
```

**Comment by jcguu95** [comment]
Thanks for taking a look at my issue! Manual evaluation did not work. I think the problem is either mine or qutebrowser's, since

```
## both of the following work in shell
$ emacsclient "org-protocol://roam-file?file=/tmp/test.org"
$ emacsclient "org-protocol://roam-ref?template=r&ref=aaaaaa&title=bbbbbb"
```

However, in contrast to my report above (I couldn't reproduce it anymore), neither of the following works in qutebrowser

```
:jseval void(location.href='org-protocol://roam-file?file=/tmp/test.org') 
:jseval location.href='org-protocol://roam-file?file=/tmp/test.org'
```

For future user who is reading this thread,
```
:jseval location.href='https://www.google.com'
```

does bring you to google.com in qutebrowser. I'm still finding out why similar things fail for `org-protocol://*`...

**Comment by jethrokuan** [comment]
If you enter `org-protocol://roam-file?file=/tmp/test.org` in the browser, do you see a Test org-roam note?

If you don't, that means you don't have the mimetype associated with emacsclient, and will need to set that up. See https://org-roam.github.io/org-roam/manual/Installation-_00281_0029.html#Installation-_00281_0029

**Comment by jcguu95** [comment]
I appreciate your passion! I came here without knowing any javascript (and its evaluation), MIME, org-protocol, and I've learned them so far.

Though it hasn't worked so far because in archlinux the setting might be different, I will find it out and  post it back here to benefit future readers. One thing that is sure: this is not an issue with `org-roam`. Thank you so much again.

**Comment by jcguu95** [comment]
### Bad News
I have set `org-protocol` and its MIME type following the instruction above, and this does work for Firefox. Opening the link `org-protocol://roam-file?file=/tmp/test.org` in firefox does call `emacsclient` properly, and the result is the same as I call `$ emacsclient "org-protocol://roam-file?file=/tmp/test.org"` in the shell. This, however, does not work for qutebrowser.

### Good News
It's possible to call bash with commands within qutebrowser. Doing so does not require setting up the MIME type of `org-protocol`. Here is an example

```
# in ~/.config/qutebrowser/config.py
config.bind("<Ctrl-r>", "spawn bash -c 'emacsclient \"org-protocol://roam-ref?template=r&ref={url:pretty}&title={title}\" '")
```

Then by pressing `Ctrl-r` in normal mode in qutebrowser, qutebrowser will call bash and run the command

```
emacsclient "org-protocol://roam-ref?template=r&ref={url:pretty}&title={title}"
```

with `{url:pretty}` auto-expanded as the decoded url of the current page and `{title}` auto-expanded as the title of the current page. You don't need javascript and setting up MIME type in this case.

This workflow works for me and I'm happy with it. Hopefully it's helpful for you too.
