### ISSUE TITLE
Capture comes back with "Invalid org-roam-capture-context", since yesterday

### ISSUE THREAD

**Issue by algon-ns** [org-roam/org-roam#765]
### Description
Using the org-capture-template:
("d" "default" plain (function org-roam-capture--get-point)
         "%?"
         :file-name "%<%Y%m%d%H%M%S>-${slug}"
         :head "#+TITLE: ${title}\n"
         :unnarrowed t)
and only the setup recommended in the Github directories
#### Steps to Reproduce
ctrl-C c  template d (the above)
This works at least the day before yesterday, the files has been updated both june 5 and june 6

![org-roam](https://user-images.githubusercontent.com/58687687/83946926-27df9d80-a814-11ea-97a3-5499ce678d59.jpeg)

#### Expected Results

creating a file in the roam directory

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 28.0.50 (build 2, x86_64-apple-darwin17.7.0, NS appkit-1561.61 Version 10.13.6 (Build 17G11023))
 of 2020-05-09
- Framework: 28.0.50
- Org: Org mode version 9.3.7 (9.3.7-elpaplus @ /Users/niels/.emacs.d/elpa/org-plus-contrib-20200602/)
- Org-roam: 1.1.1

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
This should never have worked. You need to set `org-roam-capture-templates`, and call `org-roam-capture`. The templates don't work with normal org-capture.

**Comment by zaeph** [comment]
Which makes me question why it even worked in the first place. 🤔

**Comment by algon-ns** [comment]
It might have been a slip in my memory, as I can use "org-roam-capture" now, but for my memory, it's a long time from yesterday until today.....

sorry

**Comment by zaeph** [comment]
> sorry

Don't worry.  Can you confirm that it works when you modify the right variable?

**Comment by algon-ns** [comment]
I can confirm, that it works....
and I now remember (by your help), that I used the keybinding  C-c n f yesterday
thanks

**Comment by zaeph** [comment]
Splendid, then.  Closing.
