### ISSUE TITLE
org-roam-capture inadvertendly creates new file

### ISSUE THREAD

**Issue by RetepRennelk** [org-roam/org-roam#766]
### Description

org-roam-capture invoked on existing org-roam file creates a new org-roam file with same title but new time stamp.

#### Steps to Reproduce

1. Run org-roam-capture 
2. Select existing org-roam file
3. Instead of appending to the selected candidate a new file is opened for capturing.  

#### Expected Results

The selected and existing org-roam file should be opened for capturing new content.

#### Actual Results

A new file with the same title but different time stamp is created for appending new content.

# Reason: 

Mismatched keys ```:file-path``` and ```:path``` in ```org-roam-capture.el``` and ```org-roam.el```:

In ```org-roam-capture.el```, ```:file-path``` is accessed in ```org-roam-capture () ```:
```
(let* ((completions (org-roam--get-title-path-completions))
         (title-with-keys (org-roam-completion--completing-read "File: "
                                                                completions))
         (res (cdr (assoc title-with-keys completions)))
         (title (or (plist-get res :title) title-with-keys))
         (file-path (plist-get res :file-path))) 
```
whereas in ```org-roam-capture--info``` ```:path``` is provided by ```org-roam--get-title-path-completions ()``` in ```org-roam.el``` as
```
(list :path file-path :title title)))
```

**Comment by jethrokuan** [comment]
Should've been fixed by #767 , thanks for reporting and investigating!
