### ISSUE TITLE
Prefer lower case letters for keywords

### ISSUE THREAD

**Issue by doolio** [org-roam/org-roam#768]
### Brief Abstract
Prefer lower case letters for keywords such as `#+title:`

### Long Description
With this `org-mode` [commit](https://code.orgmode.org/bzg/org-mode/commit/13424336a6f30c50952d291e7a82906c1210daf0) lower case letters are preferred. I believe either case is acceptable so not raising as a bug.

### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
Everything should be lowercased now!

**Comment by doolio** [comment]
Thank you for the quick turnaround. And this [blog post](https://scripter.co/org-keywords-lower-case) describes  a function to lower case existing keywords if users want to update existing files.
