### ISSUE TITLE
`org-roam--extract-titles` ignore `title` and `roam_alias` properties and instead uses headline

### ISSUE THREAD

**Issue by sgepigon** [org-roam/org-roam#771]
### Description

Even if `#+title:` or `#+roam_alias` is used, `org-roam--extract-titles` returns the first headline.

I believe this problem was introduced in #770. `org-roam--extract-global-props` seems to be the relevant part of the code: https://github.com/org-roam/org-roam/blob/9d5a34d0f4660381272e8cc0ab3ba2bd2de41ff5/org-roam.el#L453 `(org-element-property :key kw)` looks like it returns `"TITLE"` or `"ROAM_ALIAS"` so it it will never satisfy `string-collate-equalp` for `"title` or `"roam_alias"`; it looks like `string-collate-equalp` has the [`ignore-case`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Comparison.html) option set to `t` though so I'm confused why it's returning `nil`.

#### Steps to Reproduce

1. Load example org file:
```elisp
#+title: example-title
#+roam_alias: "example-alias"

* example-headline

#+begin_src emacs-lisp :tangle yes
  (org-roam--extract-titles)
#+end_src
```
2. Evaluate the `emacs-lisp` code block.

#### Backtrace

N/A? It doesn't throw an error, `org-roam--extract-titles-title` and `org-roam--extract-titles-alias` just return `nil`.

#### Expected Results

```elisp
#+RESULTS:
| example-title | example-alias |

```

#### Actual Results

```elisp
#+RESULTS:
| example-headline |
```

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.0.0, NS appkit-1894.10 Version 10.15.1 (Build 19B88))
 of 2019-11-17
- Framework: Spacemacs
- Org: Org mode version 9.3.7 (9.3.7-elpa @ /Users/santi/.emacs.d/elpa/26.3/develop/org-20200602/)
- Org-roam: 1.1.1
- Org-roam commit: https://github.com/org-roam/org-roam/commit/9d5a34d0f4660381272e8cc0ab3ba2bd2de41ff5

**Comment by jethrokuan** [comment]
Thanks for the detailed report and investigation, it was extremely helpful :smile:
