### ISSUE TITLE
Slug: Title Length

### ISSUE THREAD

**Issue by klorophatu** [org-roam/org-roam#781]
### Brief Abstract
Choose the length of the title.
### Long Description
Choose the length of the title. For example, if you had typed the title "Irresistible: The Rise of Addictive Technology and the Business of Keeping Us Hooked" into org-roam-find-file, the filename would be 20200609193343-irresistible_the_rise.org because you specifically chose it to have 3 words at max.
### Please check the following:

- [X] No similar feature requests

**Comment by zaeph** [comment]
We could make the slug facility more modular by having a variable which users can use to use their own function.  I'll look into it.

**Comment by bdarcus** [comment]
I don't have a strong opinion about this, but if shortening slugs, should throw out "stop words" ("the", "of", etc), at least optionally and/or by default. 

For above example, that could yield "20200609193343-irresistible_rise_addictive.org".

Which maybe makes @zaeph's point about allowing a user function?

**Comment by zackteo** [comment]
@klorophatu the variable `org-roam-title-to-slug-fn` has been added - so you can do something like

```el
(defun string-filter (title)
    (let ((list (split-string title "\_")))
      (string-join (butlast list (- (length list) 3)) "_")))

(defun my-cool-title-function (str)
  (string-filter (org-roam--title-to-slug str)))
```
```el
:config ; And have this for your org-roam use-package config
(setq org-roam-title-to-slug-function  #'my-cool-title-function)
```
`org-roam--title-to-slug` was the old function btw - which I just decided to add on, instead of recreating the whole thing :x  

If you want common words removed as suggested by @bdarcus maybe something like this?
```elisp
(defun string-filter (title)
  (let ((common-words '("the" "of" "a" "as"))
        (title-length 3)
        (title-word-list (split-string title "\_")))
    (let ((new-list (seq-remove (lambda (elt) (member elt common-words)) title-word-list)))
      (string-join (butlast new-list (- (length new-list) title-length)) "_"))))
```
Forgive me if the code is really bad >< have just started using elisp :x But yes hope it gives you an idea of what you might want

**Comment by lanceberge** [comment]
After spending some time digging, this solution is now deprecated. `org-roam-title-to-slug-function` is now customizable with:
  ```
(cl-defmethod org-roam-node-slug ((node org-roam-node))
```
