### ISSUE TITLE
Building infopages on MELPA

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#782]
Brought up in #776.

I'm not sure if the info-pages are being built for users when they install from MELPA.  If it's not the case, we need to do so.

**Comment by jasondunsmore** [comment]
I installed from melpa. The info manual comes up fine when I type "C-h i".

**Comment by zaeph** [comment]
Might have been a problem with @nobiot's installation, then.  I'll investigate this later today.

**Comment by nobiot** [comment]
@jasondunsmore , are you on Windows?
I also see it on my Linux (WSL) ,where Org-roam was installed via MELPA.
I don't see it on my Windows, where it was installed via GitHub repo with Straight.

I will try MELPA on Windows, but I suspect the issue might be (yet again) Windows specific....
If you are on Windows, I would love to know how you installed Org roam

**Comment by nobiot** [comment]
> 
> 
> Might have been a problem with @nobiot's installation, then. I'll investigate this later today.

I'll dig deeper too.

**Comment by jethrokuan** [comment]
So straight installs the info files if `makeinfo` and `install-info` are present: https://github.com/raxod502/straight.el/blob/846956eacd10830dc4afde2028c3e1f6f2945d33/straight.el#L4317

Perhaps, those executables aren't present on your Windows machine.

**Comment by nobiot** [comment]
Looks like I need to install [texifno package](http://gnuwin32.sourceforge.net/packages/texinfo.htm) separately. My Linux does not have it either but can show Info page correctly, so maybe MELPA does something for Windows, too. I will check these later today...

**Comment by nobiot** [comment]
MELPA build info correctly (see image below; just followed [the minimal guide I wrote](https://org-roam.discourse.group/t/beginners-guide-to-troubleshooting-emacs-problems-an-org-roam-edition/224)).

I'll see if textinfo package in my previous comment works. But regardless, MELPA works for Windows, too. So perhaps this issue itself can be closed (?)

For PR #776 , the internal Info won't be helpful for Straight (and Doom) users on Windows, who do not have `sqlite3` installed before launching Org-roam. This, hopefully, is a small number of users, and hopefully not a novice group... 

Or would like to consider an alternative to internal Info link for this group of users (Doom/Straight on Windows without `sqlite3`)? Personally, I am comfortable with lack of Textinfo, but I don't think I am a good representative.

![image](https://user-images.githubusercontent.com/12507865/84264011-c32c8780-ab20-11ea-9824-eb7998f45069.png)

**Comment by jethrokuan** [comment]
Very strange. I feel like this should all happen as per what's happening with Linux machines at the moment: transparent to the user. MELPA does generate the info file if it finds a texi document in the sources: https://github.com/melpa/melpa/blob/115bd5bc9db19193e1421a2fc4b062ae729e326c/package-build/package-build.el#L651so it's weird that installing from MELPA doesn't have the info manual.

Straight doesn't use MELPA and pulls from git directly, and also attempts to install the info file if the utilities to build them are present, so I imagine if the `texinfo` package were installed, you wouldn't need the manual setup process.

**Comment by nobiot** [comment]
@jethrokuan @progfolio ,
MELPA does work if used with `package-install` ([my previous comment](https://github.com/org-roam/org-roam/issues/782#issuecomment-641954531)).

My apologies, if my comment about Doom/Straight was confusing.

I would have thought this below would pull the repo from information available from MELPA, and clone/copy the repo in your local. Then Doom/Straight use it to build the `.elc` (and I guess info pages, etc.)

```
;; in my Doom package.el
(package! org-roam)
```

Neither this, nor the following worked in the same way as `install-package` did. I assumed the two ways of defining recipes were equivalent, in that both work off a local Git repo -- sorry, if this was not clear from my comment above.
```
;; in my Doom package.el
(package! org-roam
  :recipe (:local-repo "~/local-repos/org-roam"))
```

**Comment by nobiot** [comment]
I'm fine with what I have. Thank you all for coming along the journey with me on Windows.

My hope is this affects only a fraction of users. 

Personally, I love Doom, but I don't find it suitable for people new to Emacs, and the author is clear about it (or so I read in the README, I think). But... it seems to be popular for this group, too...

**Comment by nobiot** [comment]
@jethrokuan 

> the utilities to build them are present, so I imagine if the `texinfo` package were installed, you wouldn't need the manual setup process.

I did have an error in `doom sync` saying subprocess could not be executed. I did not dig deeper, but this could the problem---way outside the scope of Org-roam.

**Comment by jethrokuan** [comment]
So I think we can conclude from this that:

1. Installing from MELPA will make available the info manuals within Emacs.
2. Installing using Straight will make available the Info manuals, if the tools to build them are available (the `texinfo` package).
3. For Windows, the installation seems a little borked: the info file is generated, but not moved to the appropriate location (not available in `Info-directory-list`)

Would probably be best to report this upstream to straight.el.
