### ISSUE TITLE
org-roam-doctor complains about #+roam_tags:

### ISSUE THREAD

**Issue by zoechi** [org-roam/org-roam#785]
### Description
```
Error message:
  Possible misspelled key: "ROAM_TAGS"
Org-roam supports the following keys: roam_tags, roam_alias, roam_key

[s]: Skip
[e]: Edit
```

For a file like

```org
#+title: Foo
#+roam_tags: Bar
#+description: Some text
```

#### Steps to Reproduce

Create a file like above and run

`C-u M-x org-roam-doctor`

#### Expected Results

I think there shouldn't be an error

#### Actual Results

Complains about misspelled key

### Environment
```
- Emacs: GNU Emacs 28.0.50 (build 6, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0)
 of 2020-04-27
- Framework: N/A
- Org: Org mode version 9.3.7 (release_9.3.7-632-g3cec17 @ /home/user/.config/emacs/straight/build/org-plus-contrib/)
- Org-roam: 1.1.1
```

**Comment by zoechi** [comment]
Running `org-roam-db-build-cache` also didn't help.

I lowercases all these keys just before because I thought it complained about it being uppercase, but now with lowercased I get the same error.

**Comment by zaeph** [comment]
I think it's related to the problem we've encountered with `org-element` and the upcasing of file-metadata tags.

**Comment by zaeph** [comment]
I can reproduce it on my end.

**Comment by jethrokuan** [comment]
https://github.com/org-roam/org-roam/commit/26b90b28e3f4b97b59e913cd64c40c4d7b8bf267 fixes this. You don't see the right casing in the error message (it's always upcased), but it won't trigger an error unless you truly misspelled it.
