### ISSUE TITLE
Handling of case with `org-element-property`

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#786]
Based on #785.

https://github.com/org-roam/org-roam/blob/8e35d860e7c0bd8332e84d80d187073374e7c56b/org-roam-doctor.el#L95

`org-element-property` considers file-metadata tags as `:keywords`, and in `org-element`, those are upcased for comparison.  We can't use it to check if the case of the file-metadata tags is consistent.

We could either drop the checker, since it wont' lead to failure, or we find another way to retrieve the tags which isn't based on `org-element`.

**Comment by jethrokuan** [comment]
Should be resolved in https://github.com/org-roam/org-roam/commit/26b90b28e3f4b97b59e913cd64c40c4d7b8bf267
