### ISSUE TITLE
In docs on templating, mention how they permit the separation of files by access (or equivalently, by source repository)

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [org-roam/org-roam#793]
[EDIT: The proposal made in this comment is obsolete. See the [latest comment in this thread](https://github.com/org-roam/org-roam/issues/793#issuecomment-643026081) for work remaining in this issue.]

Suppose you'd like to divide your knowledge base into "private" and "public" data. This is currently possible in `org-roam`, but it's inconvenient.

I agree mostly with the `org-roam` principle that notes should be kept in flat directories. It's pointless to divide them by topic. But dividing them by access is important. If it's not possible, either people won't share data they'd like to share, or they won't process data they'd like to process.

# A (the?) way to sort a new file currently

Each time I insert a new file, I create it as normal using `org-capture` (`C-c n i`). That creates a new file at the top of my roam folder. I then move that file to the subfolder it should be in: either private/ or public/.

If I moved the file using Bash, I then must use `find-alternate-file` (`C-x C-v`) to reload that file, because Emacs thinks it's stil at the top of the folder. If I moved the file from within Emacs, I don't need to `find-alternate-file` because Emacs updates its location automatically. Both methods take roughly the same amount of time.

Last, since the file is no longer where `org-roam` thought it would be, I have to run `org-roam-db-build-cache` to update the index.

## Even harder: Sorting a file after others refer to it

Suppose you create a file, and then link to it from other files, and only thereafter realize you'd like to make it (say) private. In that case you've got to do something along the lines of what I just described, but in addition you've got to change all the references to it. There are three ways these might change:

* Files at the top of the roam-folder will now link to "private/name-of-file" instead of "name-of-file".
* Files in the private/ subfolders will now link to "name-of-file" instead of "../name-of-file".
* Files in the other subfolders will now link to "../private/name-of-file" instead of "../name-of-file".

# Proposal

In addition to `org-roam-insert`, I wish there was `org-roam-insert-somewhere`. Using completion, it would ask you in which subfolder to create the new file. You could type nothing, in which case it goes to the top. If you type something that's not already a folder, it won't let you (because you probably don't want that). If you type something that exists, it proceeds as normal, but the new file is created in that folder.

This would be faster not just for the human, but for the computer too, as it wouldn't have to rebuild the cache after the move.

## Bonus points: Similarly simplify the moving of a file

Here too, it would just prompt you for the name of a subfolder, with completion. Emacs would move the file, change all references to the moved file in all files that link to it, and rebuild the cache.

Note that unlike the bulleted list above, there are more than three ways that references to the file might change, since the file might have moved from one subfolder to another, rather than from the top to a subfolder. (It might even move from a subfolder to the top of the roam data folder, but it wouldn't bother me if the app excluded that possibility, because it doesn't seem useful.)

**Comment by TimQuelch** [comment]
Is this something that could be achieved by having multiple templates saved in `org-roam-capture-templates`? (https://org-roam.github.io/org-roam/manual/The-Templating-System.html#The-Templating-System)

**Comment by JeffreyBenjaminBrown** [comment]
The [docs on org-roam templatinig](https://org-roam.github.io/org-roam/manual/The-Templating-System.html#The-Templating-System) seem to suggest that all the templating system does is "prefill the [newly created] file with templated content". They don't seem to describe anything about changing where it will be created.

**Comment by TimQuelch** [comment]
I believe you can include the directory in the file name property e.g

``` emacs-lisp
(setq org-roam-capture-templates
      '(("d" "default" plain (function org-roam--capture-get-point)
         "%?"
         :file-name "public/%<%Y%m%d%H%M%S>-${slug}"
         :head "#+title: ${title}\n"
         :unnarrowed t)
        ("p" "private" plain (function org-roam--capture-get-point)
         "%?"
         :file-name "private/%<%Y%m%d%H%M%S>-${slug}"
         :head "#+title: ${title}\n"
         :unnarrowed t)))
```
when creating a new note it will prompt whether you want to press `d` for a public note or `p` for a private note. Only difference between the templates is the `file-name` property

**Comment by JeffreyBenjaminBrown** [comment]
Oh hells yes. Thanks!

I suggest the docs be amended to reflect this capacity. Currently [the templating docs](https://org-roam.github.io/org-roam/manual/The-Templating-System.html#The-Templating-System) introduce the templating concept with "Rather than creating blank files on ‘org-roam-insert’ and ‘org-roam-find-file’, it may be desirable to prefill the file with templated content." Nowhere do they mention that the filename in a template is in fact a path, not just a name, and that this allows you to keep separate repositories of notes that refer to each other.

I've changed the title of this issue accordingly.

**Comment by TimQuelch** [comment]
1 step ahead of you https://github.com/org-roam/org-roam/pull/796
