### ISSUE TITLE
upport ROAM_KEY, ROAM_TAGS and ROAM_ALIAS  also in the property drawer of the first headline

### ISSUE THREAD

**Issue by anwyn** [org-roam/org-roam#794]
I recently checked out org-roam and I'm liking it so far. But I find the use of the buffer global keywords for roam's properties and the title of the note unfortunate. I'd rather have the properties in a property drawer under the first headline. For the title this is already supported, but not for the key, aliases and tags. Supporting it would

 1. be more pleasing to the eye :)
 1.  make it easier to concat the files into one big org document.

I see that there is a PR to support headlines like files, which will probably make this feature request obsolete, but in the mean time support for roam properties in the first headline of a file is easily achieved by changing just on function.

Here is the hotpatched `org-roam--extract-global-props` function I use.

```emacs-lisp
 (defun org-roam--extract-global-props (props)
  "Extract PROPS from the current org buffer.
The search terminates when the first property is encountered."
  (let ((buf (org-element-parse-buffer))
        res)
    (dolist (prop props)
      (let ((p (org-element-map buf '(headline keyword)
                 (lambda (pom)
                   (case (first pom)
                     (headline
                      (org-element-property (intern (concat ":" prop)) pom))
                     (keyword
                      (when (string-collate-equalp (org-element-property :key pom) prop nil t)
                        (org-element-property :value pom)))))
                 :first-match t)))
        (push (cons prop p) res)))
    res))
```

**Comment by zaeph** [comment]
> be more pleasing to the eye :)

While cosmetics should be considered, it shouldn't come at the expense of functionalities.  For those properties, there isn't really any better place to put it.  Your solution presupposes the creation of a headline, but people might not want to do that, just as you are yourself averse to having a couple of lines at the top of your files.

> make it easier to concat the files into one big org document.

Is there a practical scenario where you'd want to do that?  Wouldn't that lead a to a proliferation of useless properties in those headings?  I'm not too convinced by your argument.

> I see that there is a PR to support headlines like files, which will probably make this feature request obsolete, **but in the mean time** support for roam properties in the first headline of a file is easily achieved by changing just on function. [emphasis added]

It will probably be merged by the end of the week, so not a whole lot of _mean time_. :)

**Comment by anwyn** [comment]
That was quick. OK, if the PR will be merged soon, hot patching will do for me now.
Thank you for your time and consideration.

**Comment by progfolio** [comment]
> be more pleasing to the eye :)

In-buffer settings can still be wrapped in a collapsable property drawer:

```org
:PROPERTIES:
#+title: Try this
:END:
```

**Comment by zaeph** [comment]
> In-buffer settings can still be wrapped in a collapsable property drawer

That would probably be the cleanest option.  You could also have a `Metadata` heading at the end of your file which would contain this drawer, which would be similar to the alternative way in which file-local variables can be defined on a per-file basis.
