### ISSUE TITLE
Show back-link to current headline (not current file)

### ISSUE THREAD

**Issue by yuchen-lea** [org-roam/org-roam#801]
### Brief Abstract

When run `org-roam`, if current headline has `ID` value, show backlink to this headline rather than current file (or maybe both?)

### Long Description

Congratulations to the support for headlines id links. Now I can see all id back-link to current file.

I wonder if there're any plan for displaying back-links from **headline to headline**?

for example, if I have notes like below

1. software.org
```
* emacs
   :PROPERTIES:
   :ID:       1
   :END:
awesome editor
* firefox
   :PROPERTIES:
   :ID:       2
   :END:
awesome web browser
```

2. growth.org

```
* note taking
   :PROPERTIES:
   :ID:       3
   :END:
use [[id:1][emacs]]
* information management
   :PROPERTIES:
   :ID:       4
   :END:
use [[id:2][firefox]]
```

when I run `org-roam` under headline `emacs` in file `software.org`, it will display 2 backlinks now:

```
* 2 backlinks
** growth.org
use [[id:1][emacs]]

use [[id:2][firefox]]
```

since the links are from `file` to `file`:

<img width="626" alt="图片" src="https://user-images.githubusercontent.com/7555085/84514178-28d56b00-acfd-11ea-8c42-65ddac48d8f0.png">

Maybe it's better to display backlinks to current headline `emacs` only:

```
* 1 backlink
** growth.org
*** note taking
use [[id:1][emacs]]
```

Yeah, they're not formatted org-roam note. Here **one zettel stores in one headline** rather than one file. But this feature would make great step forward and **add support to the note files created before org-roam released**.

### Proposed Implementation (if any)

maybe the links table in org-roam.db looks like:

> from  "4df7de98-3c4a-4461-9593-0d823bb7b01d"
> to "a7423fea-bb28-4e22-9804-d42e72c3b9ce"
> type "id"

### Please check the following:

- [X] No similar feature requests
  - it seems similar to [Multiple levels in the backlinks buffer · Issue #346 · org-roam/org-roam](https://github.com/org-roam/org-roam/issues/346 "Multiple levels in the backlinks buffer · Issue #346 · org-roam/org-roam"), the key difference is this feature request multiple levels in the backlinks buffer to **current headline** rather than **current file**
   - it may be a solution to [How to migrate from single file workflow to roam? · Issue #414 · org-roam/org-roam](https://github.com/org-roam/org-roam/issues/414 "How to migrate from single file workflow to roam? · Issue #414 · org-roam/org-roam")

**Comment by zaeph** [comment]
Hi there.

Now the basic support is complete, we'll be moving on to UX.  I've got something similar to what you've suggested in store, but it's tied in to the revamp of the side-buffer.

It'll have to wait a bit: next step on the roadmap for me is UX for inserting links.  Then, text/video tutorials.  Then, side-buffer.

**Comment by yuchen-lea** [comment]
Glad to hear this on the roadmap! Keep your pace, we are all very patient ;D  Also, I coulld help translate the tutorial. When it comes to the side-buffer, the headline to headline link, all users who organize notes in several big files would be REALLY REALLY HAPPY.

**Comment by zaeph** [comment]
> Also, I coulld help translate the tutorial.

Sure, you're welcome to do that when we've fledged out the documentation a bit.  Thanks!

> When it comes to the side-buffer, the **headline to headline link**, all users who organize notes in **several big files** would be REALLY REALLY HAPPY.

I'm still not sure if this will be a good idea.  We're parsing the files for link every time you save them, so having massive files would require scanning every time.  The reasons why Org-roam works better with small files is that exact opposite of why Org-agenda works better with big files.  Since we're following the slip-box method, I'd rather encourage people to break down their notes as much as they can since it has the practical benefit of working well with our database.

**Comment by yuchen-lea** [comment]
Let me try to explain why I think this feature is important.

It seems most people overwhelm the non-hierarchical and densely linked feature of Zettel, and underestimate the siblings notes. Luhemann connected the cards into a map, at the same time, he put notes talking about same topic together, gave them consecutive indexes like 1a, 1a1, 1b.

For digital note, we have several ways to describe the sibling relation:
1. put the siblings under the same headline
2. link all siblings to another note

I follow the first practice, because:
1. it's a natural way in native org-mode
2. column view on sibling notes gives me a big picture
3.  It's easy to navigate to previous or next sibling, expand or collapse specific headline, which provides a peripheral vision, a detailed context ([Digital note-writing systems fixate on the presentation and manipulation of individual notes, mostly ignoring inter-note sense-making](https://notes.andymatuschak.org/z6Pb6rwTDSg7K7LqF2EbtqbnKvpMbiXYkToDi "Digital note-writing systems fixate on the presentation and manipulation of individual notes, mostly ignoring inter-note sense-making"))
4. also, this context is structed by hierarchical headlines and lists, which contains higher quality info compared to backlink, only a jumbled list ([Prefer fine-grained associations](https://notes.andymatuschak.org/z68tVM68dEAuH4acs7HY6K76tTVzBdoBGKMZB "Prefer fine-grained associations"))

**Comment by jethrokuan** [comment]
Now the backlinks buffer shows both the file, and the corresponding headline hierarchy. Let me know if this addresses the issue.

**Comment by macswell** [comment]
Hey @jethrokuan - I was testing headline backlinking and ran into this bug. It appears to be displaying every headline backlink for each backlink that exists. Here is what I am seeing:

1. Software.org
`* emacs
   :PROPERTIES:
   :ID:       1
   :END:
awesome editor
* firefox
   :PROPERTIES:
   :ID:       2
   :END:
awesome web browser
* test1
   :PROPERTIES:
   :ID:       5
   :END:
A test thing
* Test2
   :PROPERTIES:
   :ID:       6
   :END:
another test thing`

2. Growth.org 
`* note taking
   :PROPERTIES:
   :ID:       3
   :END:
use [[id:1][emacs]]
* information management
   :PROPERTIES:
   :ID:       4
   :END:
use [[id:2][firefox]]
* Cool Stuff1
   :PROPERTIES:
   :ID:       7
   :END:
use [[id:5][test1]]
* Awesomer stuff
   :PROPERTIES:
   :ID:       8
   :END:
use [[id:6][test2]]`

when I run org-roam under headline emacs in file software.org, it will display 4 backlinks now:
`* 4 Backlinks
** Growth
*** [[id:1][emacs]] [[id:2][firefox]] [[id:5][test1]] [[id:6][test2]]
*** [[id:1][emacs]] [[id:2][firefox]] [[id:5][test1]] [[id:6][test2]]
*** [[id:1][emacs]] [[id:2][firefox]] [[id:5][test1]] [[id:6][test2]]
*** [[id:1][emacs]] [[id:2][firefox]] [[id:5][test1]] [[id:6][test2]]`

**Comment by yuchen-lea** [comment]
> Now the backlinks buffer shows both the file, and the corresponding headline hierarchy. Let me know if this addresses the issue.

@jethrokuan Sorry, it didn't.

The headline hierarchy is great, however, the issue is not **how** the backlinks displays, but **which** backlinks to display. 

As demoed [here](https://github.com/org-roam/org-roam/issues/801#issue-637819722), I don't want to see the backlinks for current file displaying in hierarchy, but only the backlinks for **current headline**. 

> We're parsing the files for link every time you save them, so having massive files would require scanning every time. The reasons why Org-roam works better with small files is that exact opposite of why Org-agenda works better with big files. Since we're following the slip-box method, I'd rather encourage people to break down their notes as much as they can since it has the practical benefit of working well with our database.

zaeph got the point, this may touch upon the design pattern of org-roam. Similar features were requested towards org-brain: change the brain node level from file to headline. This can make more use of the headline function, like todo states. Also this would make org-roam more friendly to org-mode users, who accumulated lots of big note files before.

**Comment by jethrokuan** [comment]
Ah okay, got it, thanks for the clarification.

**Comment by yuchen-lea** [comment]
This has been achieved in v2! Thanks for your effort!
