### ISSUE TITLE
Need to update manual guide on how to insert headline level ref

### ISSUE THREAD

**Issue by qlibp** [org-roam/org-roam#804]
Glad to be able to link to headline level and a manual guide is needed. Thanks for your improvment!

**Comment by qlibp** [comment]
Seems that the keybinding of @zaeph shown in YouTube don’t work for me... And I could not find the function via M-x though I have reinstall the latest org roam

**Comment by zaeph** [comment]
Which command are you talking about?

**Comment by qlibp** [comment]
> Which command are you talking about?

org-roam-store-link

**Comment by zaeph** [comment]
`org-roam-store-link` shadows `org-store-link`, which means that every call to the later result to the former when `org-roam` is on.  But that should not prevent `org-roam-store-link` from working, though.  Are you sure you've updated to the latest version, and the package is loaded?

**Comment by qlibp** [comment]
> Are you sure you've updated to the latest version, and the package is loaded?

Package is loaded otherwise i can’t use other org roam function and also the package should be latest as I could get autocompletion on org-roam-store-link in emacs lisp mode.

**Comment by zaeph** [comment]
Are you sure you've running `org-roam-mode` on init to enable all the Org-roam functionalities?

**Comment by qlibp** [comment]
> Are you sure you've running `org-roam-mode` on init to enable all the Org-roam functionalities?

To be honest, I am not so sure on whether or not I have loaded all functionalities, but I do get the org roam mode on. Any test I could do to give you more information on my situation? Thanks!
