### ISSUE TITLE
Fail to set org-roam-link-title-format

### ISSUE THREAD

**Issue by gyh1621** [org-roam/org-roam#806]
### Description
I'm using Doom Emacs. At first I configured link title format as "R:%s", however, after I enabling customize-face, I want to change back to "%s".

After changing link title format in config.el with:
```
(use-package! org-roam
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-directory "~/org/roam")
      (org-roam-link-title-format "%s")
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n j" . org-roam-jump-to-index)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))))
```
And restart emacs, the `org-roam-link-title-format` variable is still "R:%s".

### Environment

Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.0.0, NS appkit-1894.10 Version 10.15.1 (Build 19B88))
 of 2019-11-17

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by zaeph** [comment]
It's because the prefix is hardcoded in the link's description.  Basically, when you customise the variable, it changes the way links are inserted by prepending your prefix to the original description.

You could write a quick script to go through your file and regex-match `][<prefix>` without too much problem.

**Comment by gyh1621** [comment]
Thank you for the quick reply!

However, when I try to use "org-roam-insert" inserting new links, the new links are still with "R:" prefix.

**Comment by zaeph** [comment]
Check if `org-roam-link-title-format` is not defined as a custom-variable later in your `init.el`.

**Comment by gyh1621** [comment]
Thank you for the hint, I fixed this.

**Comment by progfolio** [comment]
It would be helpful for anyone in the future who reads this if you posted how you fixed it.

**Comment by gyh1621** [comment]
sorry, I actually don't really know what happens. I'm new to Emacs.

Several things I want to mention here. First Doom Emacs uses a different config structure. It disables `customize` by default. And also, Doom Emacs customize variables in `.doom.d/config.el`, for example, if I want to set `org-roam-link-title-format`, I need to put `(setq org-roam-link-title-format "%s")` in `.doom.d/config.el`(not tested) or just use `use-package!` as I paste in the issue description, that one is correct (tested).

As for my issue:
- I first go to `.emacs.d` executing `git checkout init.el` to disable `customize` restoring Doom Emacs default settings
- Then I go to `.doom.d/config.el` use `use-package!` pasted in the description
- After saving, I type `doom/reload` and use `C-h v` to check `org-roam-title-link-format` and it already changed

I remember I tried these three steps but failed when I opening this issue. Maybe I also use `customize` to set `org-roam-title-link-format` and `customize` settings overwrite Doom Emacs settings then.
