### ISSUE TITLE
Links are lost when upgrading to 1.2.0

### ISSUE THREAD

**Issue by ceblan** [org-roam/org-roam#808]
### Description

All my links are lost after upgrade from 1.1.0 to 1.2.0. 

If I revert to 1.1.0 and clean/rebuild cache bring the links back.   

#### Steps to Reproduce

1. Upgrade to 1.2.0 (from 1.1.0)
2. Load Emacs
3. Run `org-roam-db—clear
4. Run `org-roam--build-cache-async`

Minibuffer show right number of files but 0 links between them  

No error is shown but it is interesting to note than building cache finish and shows results in mini buffer almost instantly however in 1.1.0 it takes a few seconds to build.

#### Expected Results

This is the result in 1.1.0 for the same set of files

(org-roam) files: 73, links: 73, titles: 73, refs: 0, deleted: 0

#### Actual Results

(org-roam) files: 73, headlines: 0, links: 0, tags: 0, titles: 73, refs: 0, deleted: 0

### Environment
                                                                                                             
- Emacs: GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5)                                               of 2020-04-21                                                 
- Framework: N/A                                             
- Org: Org mode version 9.3.7 (9.3.7-2-g706970-elpa @ /home/carlos/.emacs.d/elpa/org-20200608/)                                              
- Org-roam: 1.2.0

**Comment by zaeph** [comment]
Interesting.  Do you have any kind of links that isn't `file:` or `id:`?

**Comment by zaeph** [comment]
Just in case, you might want to try to force the rebuild with `C-u M-x org-roam-db-build-cache`.

**Comment by ceblan** [comment]
- All the links are files, although I have a few notes with images (but afaik those are ‘file:’ links too) 

- C-u M-x org-roam-dB-build-cache  shows same result:
(org-roam) files: 73, headlines: 0, links: 0, tags: 0, titles: 73, refs: 0, deleted: 0

- Any new note and links are handled right. It seems there is Just an issue migrating from db v3 to db v6.

**Comment by ceblan** [comment]
I’m going to do a clean start and will addfiles-buildcache to see if some of them is causing problems. 

I’ll let you know if I see something weird.

**Comment by ceblan** [comment]
Something is going wrong:
1. I’ve started with a clean org-roam dir (no files, no org-roam.db). 
2. Create two notes linked to each other
3. Links are fine
4. I deleted org-roam.db
5. I rebuilt cache.
6. Everything is  messed:
   - no links to each other .
   - org-roam-find-files shows file names instead of #+TITTLE

I believe this can be easily reproduced just deleting org-roam.db and trying to rebuild cache.

I hope it helps you, if not, let me know if I can try something else to see what’s going on.

Thanks!

**Comment by jethrokuan** [comment]
I think it's likely that you had a duplicate ref or headline ID somewhere in your org files. This causes the cache build to halt unexpectedly. I know you said no errors shown, but can you check the messages buffer to see if any db related messages were printed? They tend to get hidden by the final printout.

**Comment by progfolio** [comment]
> it's likely that you had a duplicate ref or headline ID somewhere in your org files.

See: #811 for a way to detect duplicate ID's in your files.

**Comment by ceblan** [comment]
@jethrokuan , I dont think the problem is with my org files but probably something in my config (which I've posted below). What I don't understand is why, whith the same config, it only happens in 1.2.0.

This is how I can reproduce it consistently with two very simple org files:
1- I've started with no org file and no org-roam db
2- I've created two notes with org-roam-find-files, these are the notes:
```
#+TITLE: ONE NOTE

-tags::[[file:20200613205255-two_note.org][TWO NOTE]]

* This is note 1
	yeah, this is note one
```
=============================
```
#+TITLE: TWO NOTE

-tags::[[file:20200613205200-one_note.org][ONE NOTE]]:

* This is note 2
	yeah, this is note two
```
3- Org-roam shows in the side window that each note is linked to the other.
4- Exit emacs & started again.
5- While starting emacs, I can see in *messages* that org-roam is rebuilding the cache.
6- After this rebuilt, org-roam does not recognize each note linked to the other but there is no error in *messages* after this restart/rebuild  

I've done what @progfolio suggested after (6) and this is what I ge for the two simple notes:
```
Finding ID locations (1/2 files): /home/carlos/org-roam/20200613205200-one_note.org
Finding ID locations (2/2 files): /home/carlos/org-roam/20200613205255-two_note.org
2 files scanned, 0 files contains IDs and in total 0 IDs found.
#s(hash-table size 1 test equal rehash-size 1.5 rehash-threshold 0.8125 data ())
```
Below is my org-roam config, please, have a look at it (my elisp knowledge is very basic) just in case you see something that could be messing things:

```
(use-package org-roam
	:ensure t
	:init
	(defvar org-roam-capture-templates
		'(("d" "default" plain (function org-roam-capture--get-point)
			 "%?"
			 :file-name "%<%Y%m%d%H%M%S>-${slug}"
			 :head "#+TITLE: ${title}\n\n-tags::\n\n"
			 :unnarrowed t)))
	:hook
	(after-init . org-roam-mode)
	:config
	(setq org-roam-directory "/home/carlos/org-roam")
	)

(use-package company-org-roam
  :ensure t)

(add-hook 'org-mode-hook
        (lambda ()
          (set (make-local-variable 'company-backends)
               '(( company-org-roam company-dabbrev company-yasnippet company-ispell)))))
```

BTW, thank you guys for this amazing piece of software. It's been the very first time in my life (and I'm on my 50's) that I feel that my notes workflow works and it will in the years to come. Thanks!

I'll try to tag this ticket as "support", if I were not allowed, feel free to do it yourself.

P.S.: please, excuse me for my poor english.

**Comment by ceblan** [comment]
Well, after uninstalling org-roam and installing it again from melpa I can't reproduce it any more with the two simple org file. So, I've restored all my notes and all the links are there.

It's clear that there is something to fix in my init.el.

Thanks again for your work!

**Comment by laheadle** [comment]
I had this problem too -- fixed it by deleting the *.elc files from my `.emacs.d/elpa/org-roam-1.2.0` directory.
