### ISSUE TITLE
Debian packaging of org-roam: can we switch back to emacsql-sqlite?

### ISSUE THREAD

**Issue by spwhitton** [org-roam/org-roam#810]
I'm looking into packaging Org-roam for Debian and its derivatives, so users can just `apt-get install elpa-org-roam`.  Since we don't have to worry about difficulties compiling and installing the emacsql-sqlite binary, I was thinking it would be best if we patched our packaged version of Org-roam to use emacsql-sqlite, rather than emacsql-sqlite3, again.  Is this likely to cause problems in future versions of Org-roam?  AIUI emacsql is meant to abstract away details of its backends, but perhaps you've observed some leakage?

**Comment by jethrokuan** [comment]
We switch to emacsql-sqlite3 because windows users have some issues compiling the emacsql executable.

To install org-roam with this version of emacsql would not be much harder though:

`apt install elpa-org-roam sqlite`

**Comment by TimQuelch** [comment]
Not too sure how debian packages work, but couldn't you also just define sqlite as a dependency so it would install automatically when users install `elpa-org-roam`?

**Comment by spwhitton** [comment]
Yes, whatever happens the installation of emacsql and any supporting binaries would be automatic.

I would like to avoid having to add both emacsql and emacsql-sqlite3 to Debian, since the former already includes emacsql-sqlite, so it feels like duplication.  So I'd like to patch org-roam to use emacsql-sqlite, not emacsql-sqlite3, if that's not likely to cause other issues.

**Comment by zaeph** [comment]
We could cond-check the OS, and run `emacs-sqlite3` only when on Windows, but that'd require us to pull both packages ourselves when pulling from MELPA.  There's going to be redundancy either way.

**Comment by jethrokuan** [comment]
> We could cond-check the OS, and run emacs-sqlite3 only when on Windows, but that'd require us to pull both packages ourselves when pulling from MELPA. 

I really much rather not. I don't think it would be good to pull in packages with different behaviours (the two packages have some differences and aren't compatible) just for packaging purposes.

**Comment by zaeph** [comment]
Yeah, same.  I don't think it's as much of a problem to have two versions of `sqlite` installed within Emacs.

**Comment by spwhitton** [comment]
> > We could cond-check the OS, and run emacs-sqlite3 only when on Windows, but that'd require us to pull both packages ourselves when pulling from MELPA.
> 
> I really much rather not. I don't think it would be good to pull in packages with different behaviours (the two packages have some differences and aren't compatible) just for packaging purposes.

That's what I needed to know -- thank you.  I'll package both.
