### ISSUE TITLE
Cannot build database after the update

### ISSUE THREAD

**Issue by hyan46** [org-roam/org-roam#811]
### Description
Cannot build the org-roam database after the update 

#### Steps to Reproduce

1. Load Emacs
2. Run `org-roam-db—clear`
3. Run `org-roam-db-build-caches`

Shows an error: 
“EmacSQL had an unhandled condition: "near line 985: UNIQUE constraint failed: headlines.id"”

#### Backtrace

Debugger entered--Lisp error: (emacsql-error "near line 985: UNIQUE constraint failed: headlines.id")
   signal(emacsql-error ("near line 985: UNIQUE constraint failed: headlines.id"))
   #f(compiled-function (conn) #<bytecode 0x1136095>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connec$
   apply(#f(compiled-function (conn) #<bytecode 0x1136095>) #<emacsql-sqlite3-connection emacsql-sqlite3-$
   emacsql-parse(#<emacsql-sqlite3-connection emacsql-sqlite3-connection>)
   #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the r$
   apply(#f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return$
   emacsql(#<emacsql-sqlite3-connection emacsql-sqlite3-connection> [:insert :into headlines :values $v1]$
   apply(emacsql #<emacsql-sqlite3-connection emacsql-sqlite3-connection> [:insert :into headlines :value$
   org-roam-db-query([:insert :into headlines :values $v1] ((["_60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h8$
   org-roam-db-build-cache(nil)
   funcall-interactively(org-roam-db-build-cache nil)
   call-interactively(org-roam-db-build-cache record nil)
   command-execute(org-roam-db-build-cache record)
   counsel-M-x-action("org-roam-db-build-cache")
   ivy-call()
   ivy-read("M-x " ("org-roam-db--clear" "toggle-debug-on-error" "org-roam-db-build-cache" "org-roam-find$
   counsel-M-x()
   funcall-interactively(counsel-M-x)

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.$
 of 2019-12-02
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/haoyan/.emacs.d/.local/straight/$
- Org-roam: 1.2.0

- Org-roam commit: https://github.com/org-roam/org-roam/commit/2eb0aac88a89b9a1cfa40afcf2fb64dd2aee5ff6

**Comment by progfolio** [comment]
First thing I would check is if you have any duplicate ID's in your files.
Try evaluating this in the `*scratch*` buffer:

```emacs-lisp
(let ((org-id-locations org-roam-directory)
      org-agenda-files)
  (org-id-update-id-locations))
```

If you have duplicate ID's, the `*Warnings*` buffer should display something similar to:

```
Warning (emacs): WARNING: 1 duplicate IDs found, check *Messages* buffer
```

As the warning indicates, `*Messages*` buffer will also display duplicate IDs:

```
Duplicate ID  (UUID)
```

**Comment by hyan46** [comment]
I think that might be related since I sometimes run the org-roam from another computer and not sure if this is related or may duplicate the ID?

I copied everything in the `*scratch*` buffer, and run `eval-print-last-sexp` and get something like 
```
#s(hash-table size 1 test equal rehash-size 1.5 rehash-threshold 0.8125 data ())
```
Not sure if this is related but haven't seen the messages. I don't find a `*Warning*` buffer and the `*Messages*` buffer has:
```
0 files scanned, 0 files contains IDs, and 0 IDs found.
```
If I tried to build the `org-roam-db-build-caches`, it always shows the: 
```
EmacSQL had an unhandled condition: "near line 985: UNIQUE constraint failed: headlines.id"
```
Am I doing correctly?

**Comment by zaeph** [comment]
You might need to force the rebuild of the file with `C-u M-x org-roam-db-build-cache`.  Your collection might have been left in an unstable state.

…Which makes me wonder if we should catch those errors during the builds and wipe the DB when that happens. 🤔

**Comment by hyan46** [comment]
When I runs the `c-u M-x org-roam-db-build-cache`
It has the following warning: 
```
EmacSQL had an unhandled condition: "near line 1003: UNIQUE constraint failed: headlines.id"
```
Previously it was on Line 985 so something does change. `org-roam-find` still can not find anything. Not sure if any procedures can help. I tried this on my Ubuntu and Mac OS and seems all have the same issue.

**Comment by zaeph** [comment]
Following @progfolio's recommendation, could you try to eval this:
```el
(let ((org-id-files (org-roam--list-files org-roam-directory))
      org-agenda-files)
  (org-id-update-id-locations))
```

**Comment by hyan46** [comment]
Thanks, the results shown is that: 

```
Warning (emacs): WARNING: 35 duplicate IDs found, check *Messages* buffer
```

In the `*Messages*`, it shows many "Finding ID locations" now! It also shows:
```
Undo-Fu-Session discarding undo data: file length mismatch
81 files scanned, 1 files contains IDs, and 44 IDs found.
```
So that may be related to the duplicate IDs. How to solve this issue?

**Comment by zaeph** [comment]
I'm afraid you're going to have to manually go through your `:ID:` properties to know which ones are duplicates.  I recommend you use a tool like `ripgrep` to search the IDs which are mentioned in your `*Messages*` buffer, and that you ask yourself whether you need to keep them.  Depending on whether you actually used those IDs before, you might be better off wiping them off entirely and starting afresh.

**Comment by hyan46** [comment]
Thanks! Found all the problems are due to the `org-gcal` somehow duplicate events and IDs. Just fixed that and everything works perfect.

**Comment by das-s** [comment]
If somebody runs into this issue and has lots of org-IDs in their files, this is a quick and dirty way to remove the IDs (backup your files first!):
```
rg --files-with-matches ':ID:' '/home/das-s/org' | xargs sed -i '/:ID:/d' 
```

**Comment by cpbotha** [comment]
I just ran into this issue. In my case it turned out to be dropbox file conflicts I had accumulated over the past 6 years of org files, and the fact that I often attach files to headings, which adds the `:ID:` property.

The code in @zaeph 's comment https://github.com/org-roam/org-roam/issues/811#issuecomment-643577761 was exactly what I needed to figure out the issue and fix.

**Comment by qualiaa** [comment]
I'm also having this problem, with `org-roam-db-build-cache` reporting the error:

```
EmacSQL had an unhandled condition: "near line 2095: UNIQUE constraint failed: headlines.id"
```

I first assumed that the database required the first top-level headline for each file (not true of my files), but changing these headlines has not fixed the issue.

I do not have many files containing an `:ID:` tag, the output of 

```
(let ((org-id-files (org-roam--list-files org-roam-directory))
      org-agenda-files)
  (org-id-update-id-locations))
```

yields 

```
351 files scanned, 7 files contains IDs and in total 6 IDs found.
#s(hash-table size 14 test equal rehash-size 1.5 rehash-threshold 0.8125 data (
   ; list of files...
))
```

This has rendered org-roam unusable for about two weeks :/

**Comment by jcintasr** [comment]
Hello,  I know it is closed but just in case it's useful for anybody landing in the same issue:
I had org-roam linked to my org-journal too, my problem was that for some reason an entry for a day had two `:ID:` properties. I solved it erasing the `org-roam.db`, re-doing the entry for that day and rebuilding the database with `org-roam-db-build-caches`. 

To solve it, the code from [#811 (comment)](https://github.com/org-roam/org-roam/issues/811#issuecomment-643577761)  was key to point me out to my error.
