### ISSUE TITLE
Allow the creation of file references without opening org capture

### ISSUE THREAD

**Issue by rajk04** [org-roam/org-roam#813]
### Description
- Modify the `org-roam-insert` function, to allow the user to skip the org capture screen, and continue working on the current note
- This saves one step when you're creating a link.
- I feel this would be useful for people who are starting to use org-roam and lack many of the references that they may want to add, and as a result may spend a lot of time creating new files.

### Proposed Implementation
- Modify `org-roam-insert` to accept a optional variable, which determines whether or not we open org capture (defaults to opening org capture)
- Set `:immediate-finish`, when calling org capture [here](https://github.com/org-roam/org-roam/blob/master/org-roam-capture.el#L328), if required.

I haven't written elisp before, so take whatever I have written here with a grain of salt. That said, if this would be a useful feature, I'd like to take a stab at implementing this, as it's a good forcing function to learn it's basics.

### Please check the following:

- [x] No similar feature requests

**Comment by zaeph** [comment]
As much as I'd like to tell you to 'go for it', we're not sure whether we're going to keep using `org-capture` in the future.  It has severe limitations which are forcing us to jump through hoops to have it do our bidding.  Also, I'm iffy about changing a function/command's signature to implement boolean optional behaviours.

One thing I can recommend is to define a wrapper for `org-roam-insert` which would set only one template in `org-roam-capture-templates` locally with `:immediate-finish t` in it.

I'm going to write you an example.

**Comment by zaeph** [comment]
There you go:
```el
(defvar org-roam-capture-immediate-template
  '("d" "default" plain
    #'org-roam-capture--get-point
    "%?"
    :file-name "%<%Y%m%d%H%M%S>-${slug}"
    :head "#+title: ${title}\n#+created: %u\n#+last_modified: %U\n\n"
    :unnarrowed t)
  "Capture template to use for immediate captures in Org-roam.")

(defun org-roam-insert-immediate (arg &rest args)
  "Find an Org-roam file, and insert a relative org link to it at point.
This variant inserts the link immediately by using the template
defined in `org-roam-capture-immediate-template'.  See
`org-roam-insert' for details."
  (interactive "P")
  (let ((org-roam-capture-templates (list org-roam-capture-immediate-template))
        (args (push arg args)))
    (apply #'org-roam-insert args)))
```

@jethrokuan, @progfolio: Not sure if it's worth pushing to `master`.

**Comment by rajk04** [comment]
That looks great! Thank you @zaeph

I made one addition to this, to include the immediate finish command:

```diff
(defvar org-roam-capture-immediate-template
  '("d" "default" plain
    #'org-roam-capture--get-point
    "%?"
    :file-name "%<%Y%m%d%H%M%S>-${slug}"
    :head "#+title: ${title}\n#+created: %u\n#+last_modified: %U\n\n"
++  :immediate-finish t
    :unnarrowed t)
  "Capture template to use for immediate captures in Org-roam.")

(defun org-roam-insert-immediate (arg &rest args)
  "Find an Org-roam file, and insert a relative org link to it at point.
This variant inserts the link immediately by using the template
defined in `org-roam-capture-immediate-template'.  See
`org-roam-insert' for details."
  (interactive "P")
  (let ((org-roam-capture-templates (list org-roam-capture-immediate-template))
        (args (push arg args)))
    (apply #'org-roam-insert args)))
```

**Comment by zaeph** [comment]
I've opened #814 to push it to `master`.

**Comment by snowman** [comment]
It's just a note.

When you use `org-roam-insert` to insert *NON*-existing roam files, it
opens `org capture` buffer, `org-roam-insert-immediate` disable `org capture` process, insert the link immediately, so you can complete that link later without distraction.

And `:immediate-finish` is properties of `org`(not `org-roam`) capture `Template elements`, see `info` of `org` for more information.
