### ISSUE TITLE
Better handling of `UNIQUE` errors when building the cache

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#816]
#811 raised a problem that we anticipated with @jethrokuan: the `db-build-cache` is interrupted when a duplicate ID is found because of the `UNIQUE` constraint we've set for them in our schemata.

We thought the error message was meaningful, and since it was already happening with duplicate refs, we didn't think it was necessary to address it for v1.2.0.  However, I think we should improve the handling of errors during the build either by implementing scripts that would resolve those problems à la `org-roam-doctor`, or by providing better error messages.

**Comment by kbruskiewicz** [comment]
I'm getting this error right now with newer versions of `org-roam` but not older versions, in this case for the field `headline.id`. I'm assuming that this wouldn't have happened when headlines weren't supported?
