### ISSUE TITLE
What are tags for? Is there any functionality associated with them?

### ISSUE THREAD

**Issue by mrbig033** [org-roam/org-roam#822]
### Description

[The documentation on tags](https://org-roam.github.io/org-roam/manual/Tags.html#Tags) tells me the syntax required how to insert them, but I couldn't find how they're supposed to be used. Is there any functionality related to them? Any command that makes use of this data?

### Environment

- Emacs: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G103))
 of 2020-05-14
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /Users/davi/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.1.1

**Comment by zaeph** [comment]
They appear in the completion lists for `org-roam-find-file` and `org-roam-insert` for easy filtering, and they might be used to filter programmatically with wrappers for those commands.

**Comment by mrbig033** [comment]
I see. I can see how that can become useful if you have lots of notes. I use Ivy some and right now they don't seem to do much. It would be great if there as command to narrow using tags, create some kind of semi-permanent context. Thanks!

**Comment by zaeph** [comment]
That's what I mentioned by filtering programmatically. :)
We already do something similar in ORB with `orb-insert-non-ref` and `orb-find-file-non-ref` which filter out the refs.  Doing the same with tags would be trivial.  I'll address this in the future.

**Comment by mrbig033** [comment]
> That's what I mentioned by filtering programmatically. :)
> We already do something similar in ORB with `orb-insert-non-ref` and `orb-find-file-non-ref` which filter out the refs. Doing the same with tags would be trivial. I'll address this in the future.

I see. That's way over my head right now. Thanks!

**Comment by real-or-random** [comment]
I think it's somehow strange to have tags here in org-roam but also the normal org tags (https://orgmode.org/manual/Tags.html), and I'm not entirely sure which tags I should for what use case. I'd appreciate to hear your thoughts on this.

**Comment by rodelrod** [comment]
I use them for "note types" that require special handling by the code (e.g. some go in org-agenda/some don't; some have different templates; some get archived differently). In my opinion, the fact that they're call `tags` is very confusing and should be addressed. This topic [has been discussed](https://org-roam.discourse.group/t/how-to-use-roam-tags-and-or-tags/190/13) in the org-roam discourse.

**Comment by venikx** [comment]
Are we only possible to declare tags via #+roam_tags: someTag at file level?
Or is there also a way to declare a tag in the body? If not, is this a feature you'd like to see added or preferably not, due to org-mode's limitations?
