### ISSUE TITLE
Easy way to rename files and update links

### ISSUE THREAD

**Issue by mrbig033** [org-roam/org-roam#823]
### Brief Abstract

I wish I could rename files in such a way that links to them are automatically updated. Is this at all possible?

### Proposed Implementation (if any)

One command to rename a file, a buffer and update all links to it either automatically or semi-manually. 

### Please check the following:

- [X] No similar feature requests

**Comment by zaeph** [comment]
This is already implemented.  As long as you rename the file within Emacs (e.g. with `dired`) and that `org-roam-mode` is on, the links will be recomputed, both the `file:`- and `id:`-links.

**Comment by mrbig033** [comment]
Okay then, thanks!

**Comment by zaeph** [comment]
I'll readily admit that we need to make this clearer in the doc, which is probably why you did not discover this behaviour.
