### ISSUE TITLE
org-roam-unlinked-references doesn't work for me

### ISSUE THREAD

**Issue by maikol-solis** [org-roam/org-roam#826]
### Description

The new unlinked references feature doesn't work (at least for me). 

#### Steps to Reproduce

Imagine I have two files like this

```
#+ TITLE: FIRST FILE

THIS IS A TEST
```

```
#+ TITLE: SECOND FILE

I WANT A LINK TO THE FIRST FILE
```

1. Load doom-emacs
2. Go to  the roam file `FIRST FILE` 
3. M-x org-roam-unlinked-references
4. Nothing happens

#### Backtrace

Using debug-on-entry I saw this error (I'm not expert so I don't really understand what is happening here)

```
Debugger entered--returning value: "error: Found argument '-P' which wasn't expected, or isn't valid in this context\n\nUSAGE:\n    \n    rg [OPTIONS] PATTERN [PATH ...]\n    rg [OPTIONS] [-e PATTERN ...] [-f FILE ...] [PATH ...]\n    rg [OPTIONS] --files [PATH ...]\n    rg [OPTIONS] --type-list\n\nFor more information try --help\n"
```

#### Expected Results

A link in `SECOND FILE` linked the `FIRST FILE`. 

#### Actual Results

The unlinked reference buffer appears with none found references. 

### Environment

```
- Emacs: GNU Emacs 26.3 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.22.30)
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/maikol/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.0
```

and ripgrep installed 

```
$ zypper info ripgrep

Information for package ripgrep:
--------------------------------
Repository     : openSUSE-Leap-15.1-1                                                 
Name           : ripgrep                                                              
Version        : 0.8.1-lp151.2.18                                                     
Arch           : x86_64                                                               
Vendor         : openSUSE                                                             
Installed Size : 2.9 MiB                                                              
Installed      : Yes                                                                  
Status         : up-to-date                                                           
Source package : ripgrep-0.8.1-lp151.2.18.src                                         
Summary        : A search tool combines the usability of ag with the raw speed of grep
Description    :                                                                      
    ripgrep is a line oriented search tool that combines the usability of
    The Silver Searcher (similar to ack) with the raw speed of GNU grep.
    ripgrep works by recursively searching your current directory
    for a regex pattern.
```

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/48158e67d4fe68250f1538bc543546aad18afe28

**Comment by zaeph** [comment]
You seem to be running quite an old version of ripgrep.  I have `12.0.1` installed on my machine.  Could you try to update your package?

**Comment by maikol-solis** [comment]
Thanks @zaeph  you are right, I had a very old version of ripgrep. 

I installed version 11.0 from opensuse and I get this message 

``` 
Debugger entered--returning value: "PCRE2 is not available in this build of ripgrep\n"
```

I guess that the default ripgrep comes without the PCRE2 option and I guess that org-roam need that to work.  

I will  compile myself ripgrep to see if this work. However, It not seems very user friendly though.

**Comment by zaeph** [comment]
I'm pretty sure rg ships with PCRE2.  Do you have Perl installed on your system?  Did you install a pre-compiled version, or did you make it yourself?

**Comment by maikol-solis** [comment]
Yes, I have Perl in my machine and I used a precompiled version from opensuse.

**Comment by zaeph** [comment]
Nobody seems to have run into that issue, which leads me to think that the problem might be with the pre-compiled package that is available on openSUSE.  Could you investigate the issue for us?

**Comment by maikol-solis** [comment]
I confirm that the precompiled binary from opensuse is the problem. I compiled ripgrep by myself and dirty copy-paste the rg binary to ~/bin and `org-roam-unlinked-references` worked fine. I will leave this binary alone there forever. 

I will ask to them if they could build the package with pcre2 support. I will report back if I have any answer from them. 

I don't know if org-roam could alert somehow  to the user if ripgrep cannot do its regexp and identify more o less the problem.

**Comment by zaeph** [comment]
> I don't know if org-roam could alert somehow to the user if ripgrep cannot do its regexp and identify more o less the problem.

I don't think this is something we should be doing on our end.  If we had to implement warning messages for every error that could happen with every package, we'd never see the end of it.  We don't have a strict policy for including them, but generally, if it's something that happens within Emacs, we _can_ add a detailed message.  The rest of the time, I think this is something that would be better addressed by the documentation, or by looking up the error on our Discourse or elsewhere.

**Comment by maikol-solis** [comment]
Thanks @zaeph. I agree and understand that it could very cumbersome to check all those kinds of minor issues. 

Thanks for all the help!

**Comment by zaeph** [comment]
And thank you for bringing up the issue with them!

Closing.
