### ISSUE TITLE
Documentation Effort: Manual, Tutorials & Videos

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#830]
Hi there.

We've said it elsewhere, but we're sorely lacking in the documentation department.  Whether it be on Discourse, Slack or Reddit, we're getting plenty of basic questions that should be addressed by our documentation.  [Here's an example](https://org-roam.discourse.group/t/capture-template-only-partially-applied/388).

Also, since plenty of people are getting into Emacs for the first time just to try out Org-roam, we're getting plenty of questions from people who don't have a lot of experience with text-editors.  Most of them end up going for Doom, and since I don't use it, I can't provide adequate support.

I see three paths of improvement:
1. **Improving the external documentation**
  We're pretty good at keeping the internal documentation up to date, at least the docstrings, but the external manual is pretty bare-bones.  @jethrokuan has gone through great length to make it easy to generate the manual in different formats from a single source, we need to do a better job at updating it.
  Also, we should do a _much_ better job at explaining the installation process, linking to the relevant sections in Doom, MELPA, etc..
2. **Creating tutorials for beginners and power-users**
  The goal is to get everyone on the same page.  @jethrokuan had originally imagined those to be interactive tutorials in Org-mode, and whilst I still think it is a great idea, I think a parallel effort would be to record screencast presenting features in manageable chunks.
3. **Creating videos to to presents features and keep people up to date**
The videos I've made seemed to have been successful in getting people intrigued, but it's time to take the format a little more seriously and prepare a little more.  For the video-tutorials, I'm drafting something up, and I'm hoping to get a couple of them out by the end of the month.  For a global presentation of the package, I'd like to get a 3-min video presenting the essential features in a way that can be easily shared to people.

@jethrokuan and I can handle 2. and 3., but it'd be lovely if everyone could help us address 1.  If @jethrokuan or I have helped you figure out something that you wanted to do but couldn't, it'd be great if you could take the time to PR (if you know how to), or to just make a little write-up condensing what we've told you so that it may help others.  Also, on my end, I'm going to do a better job at pushing to the manual whenever I resolve an issue or push a PR.

I'm setting the milestone at 1.3.0, but I'd love the bulk of the effort to be complete by then.

Thanks!

**Comment by nobiot** [comment]
@zaeph, I have just seen this. Re point 1, is [my guide](https://github.com/nobiot/Zero-to-Emacs-and-Org-roam) going in the direction you would like to see? I did guide independent of your work and this issue. Happy to adjust its direction, content, way of presentation, etc., in any way I could help.

**Comment by jethrokuan** [comment]
I really like the effort going into the guide. I think it's good that you cover Emacs as a whole. I don't think I have any intention of doing so, at least for documentation specific to Org-roam. There's already way too much to cover, and most of "how to use Emacs" should have decent coverage elsewhere.

**Comment by nobiot** [comment]
@jethrokuan, thank you. Happy to contribute in my little way to helping new comers get to the starting line. This way, I won’t get in your way of guiding how to best use Org-roam and its ecosystem.

**Comment by nobiot** [comment]
Just one more thing. For 1 above, how would you like us in the community to contribute? Is there any good example (like an example PR that is “perfect” for this purpose)?

**Comment by jethrokuan** [comment]
> For 1 above, how would you like us in the community to contribute? Is there any good example (like an example PR that is “perfect” for this purpose)?

I don't have anything to show you. I think past attempts have shown that things that are seemingly obvious to us tend to not be so to new users, so we're likely to miss things. At the same time I don't really want to be pedantic and include every small detail, that makes the manual too noisy for people who aren't beginners.

**Comment by kendricng** [comment]
> Just one more thing. For 1 above, how would you like us in the community to contribute? Is there any good example (like an example PR that is “perfect” for this purpose)?
> 
> @jethrokuan @zaeph, you are already doing a tremendous amount of communication. I would hate to get in the way of your good work, while want to somehow contribute in a better way. An example would help.

+1 on this. I'm a super-newbie when it comes to both Emacs, Doom Emacs (and configuration), org-mode, and org-roam. I think that for someone like me that is new to this, if not a small detail, I'd love to help fill in the gaps where I think it doesn't make sense as a beginner.

For instance, when I was looking at the config settings, I had to figure out how to customize it for Doom Emacs. A small "Beginner's Tip" section would help out to redirect them to understanding how to install via vanilla Emacs, Spacemacs, Doom Emacs, etc.

For #1, I'd love to be the pedantic one as needed. Are there changes that we can "push" or suggest that's directly linked in this repo, and if so, how do you see the workflow for that being like?
