### ISSUE TITLE
user-error The Org-roam database was created with a newer Org-roam version

### ISSUE THREAD

**Issue by sbacelar** [org-roam/org-roam#832]
### Description
When I open `doom-emacs` I receive two similar error messages:

`Failed to load 'magit' package incrementally because (user-error The Org-roam database was created with a newer Org-roam version)`
and
`Failed to load 'org' package incrementally because (user-error The Org-roam database was created with a newer Org-roam version)`

This happens both in Windows 10 and in MacOS installation.

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-w64-mingw32)
 of 2019-08-29
- Framework: Doom
- Org: Org mode version 9.4 (nil @ c:/Users/sbac/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.1.1

**Comment by zaeph** [comment]
Sounds like you've had a problem during the db-update.  Try running `C-u M-x org-roam-db-build-cache` (don't forget the `C-u`).

**Comment by sbacelar** [comment]
@zaeph I tried two times. It doesn't work. I receive the following message: `The Org-roam database was created with a newer Org-roam version`.

**Comment by zaeph** [comment]
We've recently upgraded the database, and it's possible that there might have been a problem with Doom's pins.  @bdarcus, do you have an idea?

**Comment by bdarcus** [comment]
Not sure, but can unpin like this in the packages.el file:

``` elisp
(unpin! org-roam)
```

**Comment by sbacelar** [comment]
@bdarcus I did it and then `doom-sync` but the error messages remain the same.

**Comment by sbacelar** [comment]
Solved! Both in Windows and MacOS with `(unpin! org-roam)` and after that `doom update`.

**Comment by zaeph** [comment]
Probably a problem with Doom's pins, then.  It'd be great if you could let them know on their tracker.

Closing. :)

**Comment by sbacelar** [comment]
@zaeph I did.
