### ISSUE TITLE
google chrome org-roam-protocol does not populate title field 

### ISSUE THREAD

**Issue by alanz** [org-roam/org-roam#842]
#### Steps to Reproduce

If I open
https://dl.acm.org/doi/pdf/10.1145/1863495.1863501?download=true
and activate the bookmark link, it shows up in my org-roam protocol as 

> info=(:template "r" :ref   "https://dl.acm.org/doi/pdf/10.1145/1863495.1863501?download=true" :title "")
 
(Via adding `(message "info=%S" info) ` to the start of https://github.com/org-roam/org-roam/blob/master/org-roam-protocol.el#L51)

The title of the tab in the browser has the expected value ("Generic selections of subexpressions"), but it does not come through via the bookmarklet.

So I think the problem is in the bookmarklet, 

```
javascript:location.href = 'org-protocol://roam-ref?template=r&ref=' + encodeURIComponent(location.href) + '&title=' + encodeURIComponent(document.title)
```
which uses `document.title`.

chrome://version gives

Google Chrome | 83.0.4103.106 (Official Build) (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | macOS Version 10.15.3 (Build 19D76)

**Comment by jethrokuan** [comment]
Seems to work on Firefox for me:

![image](https://user-images.githubusercontent.com/1667473/84938387-c40c7d00-b10f-11ea-9385-90203c35497c.png)

what's the value of `document.title` in your chrome console, on that page?

**Comment by alanz** [comment]
It works fine for me to on my other laptop, using FireFox.  And I opened up the devtools on that on chrome/mac, and scanned through all the `document.` things, none of them had anything meaningful. 

`document.title` is literally `""`.

It looks like the page in chrome is just a container, there seems to be a plugin of some kind doing the actual rendering.  I surmise a workaround would be to use the title of the tab, which does reflect it properly, but I have no idea how to do that.

A side issue, is that the capture buffer seems to choose another previously captured PDF (proving this thing used to work), which might be related to the search process when resolving the capture.

It probably makes sense to detect an empty string for title and then use the URL instead.  It at least lets the capture work, you can edit it later if needed.

**Comment by jethrokuan** [comment]
> I surmise a workaround would be to use the title of the tab, which does reflect it properly, but I have no idea how to do that.

Quick search doesn't reveal any results here either.

> A side issue, is that the capture buffer seems to choose another previously captured PDF (proving this thing used to work), which might be related to the search process when resolving the capture.

The search is by roam_key, and not title, so it must have had the same roam key, I think.

> It probably makes sense to detect an empty string for title and then use the URL instead. It at least lets the capture work, you can edit it later if needed.

That can be done by editing the bookmarklet, since it's just javascript, by changing `document.title to `document.title || location.href`

**Comment by alanz** [comment]
> The search is by roam_key, and not title, so it must have had the same roam key, I think.

It actually ends up resolving the capture to 

```
#+TITLE: A Compiler Approach Reconciling Parallelism and Dense Representations for Irregular Trees
#+ROAM_KEY: https://legacy.cs.indiana.edu/~rrnewton/papers/parallel_gibbon_draft.pdf
Time-stamp: <2020-05-20 11:24:31 alanzimm>
```

And 

> That can be done by editing the bookmarklet, since it's just javascript, by changing 
document.title to document.title || location.href`

works as advertised, thanks.

**Comment by jethrokuan** [comment]
> It actually ends up resolving the capture to

I can't reproduce this behaviour though. If you're still seeing this, can you share your roam-ref template, and two pages A and B such that roam note on A brings you to the note for B?
