### ISSUE TITLE
Error on save org file with enabled org-roam

### ISSUE THREAD

**Issue by poulpoulsen** [org-roam/org-roam#843]
hello,
i noticed the following error, if i activate org-roam.
therefore it is not possible to save an org file.

I'm using emacs 26.3 on linux kubuntu 18.04 with actual org-roam from melpa.

Regards
Poul

Here is the info:
Debugger entered--Lisp error: (wrong-type-argument symbolp (prop))
  symbol-name((prop))
  #f(compiled-function (source) #<bytecode 0x3bd8841>)((prop))
  mapcan(#f(compiled-function (source) #<bytecode 0x3bd8841>) ((prop) (all-directories)))
  org-roam--extract-tags()
  org-roam-db--update-tags()
  org-roam-db--update-file()
  run-hooks(after-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)

**Comment by jethrokuan** [comment]
how are you setting `org-roam-tag-sources`?

**Comment by poulpoulsen** [comment]
hello,
this is my setting from custom.el
 
org-roam-tag-sources is a variable defined in `org-roam.el'.
Its value is ((prop) (all-directories))

Original value was 
(prop)

Regards
Poul

**Comment by jethrokuan** [comment]
you need to set it to (prop all-directories), not `((prop) (all-directories))`.

**Comment by poulpoulsen** [comment]
after setting 
(setq org-roam-tag-sources (prop all-directories))

then i've got this:

Warning (initialization): An error occurred while loading ‘/home/held/.emacs’:

Symbol's function definition is void: prop

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by jethrokuan** [comment]
`(setq org-roam-tag-sources '(prop all-directories))` is what you want to have.

**Comment by poulpoulsen** [comment]
yes, now it works.
Thank you.

But did the customize interface from emacs saves it the way i did above.
I changed it through the interface.

Regards
Poul

**Comment by jethrokuan** [comment]
I'd just tried to use the customize interface, and it seems to set the value properly :thinking: , might've been an old error that got corrected along the way. Can you try that again?

**Comment by poulpoulsen** [comment]
yes you are right. I just check it and now it is correct.
Thanks!

I will close this ticket.
Regards
Poul

**Comment by poulpoulsen** [comment]
yes you are right. I just check it and now it is correct.
Thanks!

I will close this ticket.
Regards
Poul
