### ISSUE TITLE
Use org-roam-store-link for org-capture annotations

### ISSUE THREAD

**Issue by dangirsh** [org-roam/org-roam#853]
`org-capture-templates` support `%a` for "annotations", which use `org-store-link` to capture a link to heading `org-capture` was called from.

Now that we have `org-roam-store-link` to handle links to headlines, it would be great if `org-roam-store-link` could be used for the captured annotation.

-----------------------------------------------

See relevant [Slack conversation](https://orgroam.slack.com/archives/CV20S23C0/p1592455046209400) with @zaeph , who thinks this should already be working (making it a bug). I don't see why, since the only related override is to remap the `org-store-link` key binding.

**Comment by jethrokuan** [comment]
I just tested this, and the `%a` was expanded into the ID link. In particular, I evaluated the block you linked in the Slack conversation (minus the refile targets), and it worked. 

Note that the ID link won't work anywhere outside of org-roam, since the ID locations are cached in the org-roam db.

**Comment by dangirsh** [comment]
Must be something else in my configuration breaking things.

Can someone point to the part of the code that's responsible for swapping in `org-roam-store-link` in this context? Can't find anything in the `org-roam` source that seems to do this...

**Comment by jethrokuan** [comment]
@dangirsh here: https://github.com/org-roam/org-roam/blob/79c75ac17468b5e2e3df03ce0936ddd8d0e5e947/org-roam.el#L1284

If you have the global mode on, org-store-link is shadowed by `org-roam-store-link`, which does call `org-store-link` under the hood.

**Comment by dangirsh** [comment]
@jethrokuan Why would that affect how `%a` is expanded in a capture template? That code seems to just affect the default key binding...

**Comment by jethrokuan** [comment]
`org-roam-store-link` calls `org-store-link` under the hood, and `org-roam`'s capture process is also triggered via `org-capture`. The latest stored link via `org-store-link` is expanded via "%a" in `org-capture-templates`.

https://github.com/org-roam/org-roam/blob/7a4b15fd368bc8ac55bfe96392f5a300f71f009c/org-roam.el#L1083

**Comment by dangirsh** [comment]
>  The latest stored link via org-store-link is expanded via "%a" in org-capture-templates.

On my end, `org-capture` calls `org-store-link` directly, except for some case related to `org-protocol-capture`, which I don't think is relevant here.

https://github.com/tkf/org-mode/blob/c2ebeea6f68f2ef804d387c238e4acccf655dc64/lisp/org-capture.el#L536-L539

From the org-roam source, and everything you've said, I still don't see how `org-roam-store-link` will ever get called. 

To be sure, I have:

`(add-to-list 'org-capture-templates '("t" "org-roam todo" entry (file my/org-roam-todo-file)
                                        "* TODO %?  #[[%F][%(my/org-roam-get-title \"%F\")]]\n%i\n%a"))`

Then, under a heading in an org-roam file, I run `org-capture` and hit "t" to select the above template. In the capture buffer, I check the link expanded by `%a` and find it's a file link (instead of org-id).


> org-roam's capture process is also triggered via org-capture

This seems to be what I'm missing. I'm watching `org-capture` call `org-store-link` in my debugger, so any magic related to `org-roam` / `org-roam-capture` isn't happening.

**Comment by jethrokuan** [comment]
@zaeph it looks like a lot of this trouble can be avoided by simply advicing `org-store-link` to be fully overridden by `org-roam-store-link`. Do you think that's okay? I'm not aware of other packages that advice org-store-link, but it may potentially cause clashes with user config.

**Comment by zaeph** [comment]
Sorry, I missed this.

> @zaeph it looks like a lot of this trouble can be avoided by simply advicing `org-store-link` to be fully overridden by `org-roam-store-link`.

I'd be in favour of that.  I'm running into problems trying to force `org-roam-store-link` behaviour with `cl-letf`, so I'd rather advice the function completely.  We're already checking `org-roam--org-roam-file-p` in the definition anyway, so things should be fine.

> I'm not aware of other packages that advice org-store-link, but it may potentially cause clashes with user config.

Neither am I, but I'd like to do it as safely as possible.  I'll think of a solution when I'm done with `org-roam-dailies`.
