### ISSUE TITLE
Using a symlinked `org-roam-directory` adds spurious tags

### ISSUE THREAD

**Issue by rodelrod** [org-roam/org-roam#855]
### Description

If my `org-roam-directory` is a symlink and org-roam is configured to extract tags from `all-directories`, all the directories in the relative path ~~from the org-roam-directory~~  down to the root (`..`, `..`, ...), plus the directories in the path back up to the `org-roam-directory`, are shown as tags in `org-roam-find-file`.

If `last-directory` is set, at least one tag is shown for every note, with the name of the Org Roam directory.

#### Steps to Reproduce

1. Create a org-roam file `~/org/a.org` with title "A"
2. Create a org-roam file `~/org/mytag/b.org` with title "B"
1. Symlink your org roam directory: `ln -s /real/org/roam/dir ~/org`
2. `(setq org-roam-directory "~/org")`
3. Activate extracting tags from directories: `(setq org-roam-tag-sources '(all-directories))`
4. Clear cache: `M-x org-roam-db--clear`
5. Rebuild cache: `M-x org-roam-db-build-cache`
6. `M-x org-roam-find-file`

#### Expected Results
I expect to see in the minibuffer the options:

```
A
(mytag) B
```

#### Actual Results
I see in the minibuffer:

```
(..)(..)(..)(real)(org)(roam)(dir) A
(..)(..)(..)(real)(org)(roam)(dir)(mytag) B
```
(UPDATE: I'm not entirely sure about the number of `(..)` we would get in this simplified example)

If I activated `last-directory` instead, I see:

```
(dir) A
(dir)(mytag) B
```

### Environment

- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2019-12-23
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/rodelrod/emacs-profiles/doom-emacs/.local/straight/build/org-mode/)
- Org-roam: 1.2.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/408e38f8bafe9d023941c33230ab150618166108

**Comment by jethrokuan** [comment]
This is definitely strange and should be changed. What's the desired behaviour here actually? Do you want tags from directories to not be extracted for symlinks?

**Comment by rodelrod** [comment]
It's probably related to the fact that in the DB, the file paths are stored as `/real/org/roam/dir/mytag/b.org`, but my `org-roam-directory` is defined as `~/org`, not `/real/org/roam/dir`. 

I imagine that the algorithm expands the `org-roam-directory` `~/org` to `/home/user/org` and then calculates the relative path to `/real/org/roam/dir/mytag/b.org` as `../../real/org/roam/dir/mytag/b.org` and takes that as a source for the tags. 

The desired behaviour is that the tag is extracted instead from `./mytag/b.org`.

Maybe if the code that generates the cache and the codes that calculates the tags uses the same algorithm — either both follow the symlink or none of them does —  the relative path will be calculated correctly. 

My current work-around is to add logic that allows me to set different `org-roam-directory`s in different environments, but using symlinks would be much simpler and flexible (and just expected to work in a POSIX environment).

Note: I scratched "from the org-roam-directory" from the description above because it was assuming too much about the implementation, and probably wrong.

**Comment by jethrokuan** [comment]
Ah yeah I see it now, should be an easy fix, will do so sometime in the morning.
