### ISSUE TITLE
Random Note for Review

### ISSUE THREAD

**Issue by zachgk** [org-roam/org-roam#856]
### Brief Abstract
Create a function to open a random org-roam note for review.

### Long Description
I am thinking about the process of reviewing notes. If you have a starting point, you should be able to find related notes through exploring links and backlinks. Adding new notes will give you one kind of starting point.

I think it would also be good to have less directed starting points as well. Specifically, I think having a process where I look at a few random notes daily might be a good way to revisit old topics. Once there, I might find new connections or add new links with the benefit of hindsight. This also ensures that notes that are missing links would eventually be found. Lastly, it can help improve the connectedness of the notes.

### Proposed Implementation (if any)
List all of the note files and pick a random one from the list.

### Please check the following:

- [x] No similar feature requests

**Comment by TimQuelch** [comment]
This kind of extra review functionality doesn't seem too focused on the core of org-roam. Potentially this could be a candidate for a contrib extension package

**Comment by wedens** [comment]
There is [org-randomnote](https://github.com/mwfogleman/org-randomnote). You can configure add all your notes to `org-randomnote-candidates`.

**Comment by zachgk** [comment]
I don't want the random headline functionality out of org-randomnote, just a random file. My notes are not usually large and often don't have headlines.

I agree that it seems outside of the core functionality. I don't know if it is simple enough that it might be worth it anyway. Here is what I am using now:
```
(defun org-roam-random ()
  "Finds random org roam file"
  (interactive)
  (find-file (seq-random-elt (org-roam--list-all-files)))
  )
```
