### ISSUE TITLE
Updating to v1.2

### ISSUE THREAD

**Issue by J0ns4** [org-roam/org-roam#858]
Hi,
Apologies for abusing the format - this isn't a bug but I didn't know where to ask this.. 
I saw that v1.2 has been released (congratulations!) and I wanted to ask what's the best way to update to it. I'm on spacemacs, and followed the instructions on https://org-roam.readthedocs.io/en/master/installation/. 
I tried configuration-layer/update-packages, but list-packages still shows:
```
    Version: 20200621.1134
     Commit: 76b2ac34606ec0787528fe1da1d4dddbc03c7d90

```

Thanks!

**Comment by jethrokuan** [comment]
That's the latest version (v1.2 + some bug-fixes). You can check the version by running `M-x org-roam-diagnostics`.

**Comment by J0ns4** [comment]
Ok then, thanks!
