### ISSUE TITLE
org-roam database issue since v1.2

### ISSUE THREAD

**Issue by Bassmann** [org-roam/org-roam#859]
### Description
Since updating to v1.2 starting EMacs takes longer and *Messages* buffer contains an entry 
"File mode specification error: (emacsql-timeout Query timed out 30)"
When I try to use org-roam I get this error message
"Error in post-command-hook (org-roam-buffer--update-maybe): (error "Selecting deleted buffer")" 
Trying to update the db I receive the error message
apply: Selecting deleted buffer

I'm on Windows using sqlite3 from mingw64. 
#### Backtrace
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  #f(compiled-function (conn) #<bytecode -0x155241a7d795a629>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0>)
  apply(#f(compiled-function (conn) #<bytecode -0x155241a7d795a629>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> nil)
  emacsql-waiting-p(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0>)
  #f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0x92fc62f4e4c339c>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0>)
  apply(#f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0x92fc62f4e4c339c>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> nil)
  emacsql-wait(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0>)
  #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x8eff8810cef3291>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> [:pragma (= busy-timeout $s1)] 15000)
  apply(#f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x8eff8810cef3291>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> ([:pragma (= busy-timeout $s1)] 15000))
  emacsql(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> [:pragma (= busy-timeout $s1)] 15000)
  #f(compiled-function (conn slots) #<bytecode -0x397a507aade732c>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  apply(#f(compiled-function (conn slots) #<bytecode -0x397a507aade732c>) (#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o...")))
  #f(compiled-function (&rest args) #<bytecode 0x121303a8ba1f0ec8>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  apply(#f(compiled-function (&rest args) #<bytecode 0x121303a8ba1f0ec8>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  initialize-instance(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-21995f0> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x60597ce0e561f7e>)(emacsql-sqlite3-connection :file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o...")
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x60597ce0e561f7e>) emacsql-sqlite3-connection (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  make-instance(emacsql-sqlite3-connection :file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o...")
  emacsql-sqlite3("c:/Users/USERID/AppData/Roaming/.emacs.d/data/o...")
  org-roam-db()
  org-roam-db-build-cache(nil)
  funcall-interactively(org-roam-db-build-cache nil)
  call-interactively(org-roam-db-build-cache record nil)
  command-execute(org-roam-db-build-cache record)
  execute-extended-command(nil "org-roam-db-build-cache" #("org-roam-db\norg-roam-db--clear\norg-roam-dailies-ye..." 11 12 (read-only nil) 12 22 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face (ivy-current-match ivy-minibuffer-match-face-2)) 22 30 (read-only nil face ivy-current-match help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 30 31 (read-only nil) 31 41 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 41 57 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 57 58 (read-only nil) 58 68 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 68 75 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 75 76 (read-only nil) 76 86 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 86 98 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 98 99 (read-only nil) 99 109 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 109 120 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 120 121 (read-only nil) ...))
  funcall-interactively(execute-extended-command nil "org-roam-db-build-cache" #("org-roam-db\norg-roam-db--clear\norg-roam-dailies-ye..." 11 12 (read-only nil) 12 22 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face (ivy-current-match ivy-minibuffer-match-face-2)) 22 30 (read-only nil face ivy-current-match help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 30 31 (read-only nil) 31 41 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 41 57 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 57 58 (read-only nil) 58 68 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 68 75 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 75 76 (read-only nil) 76 86 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 86 98 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 98 99 (read-only nil) 99 109 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 109 120 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 120 121 (read-only nil) ...))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

### Environment

- Emacs: GNU Emacs 28.0.50 (build 5, x86_64-w64-mingw32)
 of 2020-05-21
- Framework: N/A
- Org: Org mode version 9.3.7 (9.3.7-4-gba6ca7-elpaplus @ c:/Users/USERID/AppData/Roaming/.emacs.d/elpa/org-plus-contrib-20200615/)
- Org-roam: 1.2.0

**Comment by Bassmann** [comment]
Same issue occurs using official Emacs 26.3

**Comment by jethrokuan** [comment]
@nobiot can you comment on the timeout issue? it seems to be a Windows specific thing.

**Comment by nobiot** [comment]
Not sure; can't reproduce. I don't recall having this message: "File mode specification error: (emacsql-timeout Query timed out 30)".

From 1.1.1 to 1.2, I did have some DB related message (don't think it was "File mode specification error"), but it's kind a regular thing for me with this kind of change (`orgid` and heading support -- the db scheme version changed from 5 to 6 to support org heading?), so didn't take notice. I deleted the db file manually, rebuilt OK. v1.2 works for me.

A couple of additional observations. 

Re "Selecting deleted buffer", for me it's a constant, reproducible message, but no harm so far. It seems to be a Windows thing with `emacsql`. When you manually invoke `org-roam-db-build-cache`, I always have this message every second time (the first time being start of `org-roam`). It seems to be traceable back to `emacsql` (error NOT from `emacs-sqlite3`), so I stopped digging deeper. Recurring, reproducible, but no harm; I have learnt to live with it.

On a bit separate note, there might be some performance implications, which might be coming from new orgid/heading support, or change to SQL transaction; can't be sure. I tried the 10,000 linked files over the weekend (code below). It was 180 minutes before (v1.1.1, I think); now on v1.2.0, 36 hours later, the build process was still running; I terminated the task manually. It could be a Windows thing, if you haven't experienced change in performance on Linux. Or me not doing this test properly.

```
;; no db file in the directory
(setq org-roam-directory "~/temp/python/10000-org-max-25-linked-files")
(benchmark 1 '(org-roam-db-build-cache))
```

**Comment by jethrokuan** [comment]
@nobiot can you try the benchmarks with the test-org files here?

https://github.com/org-roam/test-org-files

I'm curious of the performance difference for Windows and Linux.

**Comment by nobiot** [comment]
@jethrokuan Happy to. Let me work on it. It’s Monday morning here; the week has just begun :)

**Comment by Bassmann** [comment]
> ;; no db file in the directory
> (setq org-roam-directory "~/temp/python/10000-org-max-25-linked-files")
> (benchmark 1 '(org-roam-db-build-cache))
> ```
So I removed the db file and tried to recreate it via org-roam-db-build-cache which also let to the error message regarding the deleted buffer.

Running you benchmark code leads to this trace
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  #f(compiled-function (conn) #<bytecode -0x15539aafdb55a629>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614>)
  apply(#f(compiled-function (conn) #<bytecode -0x15539aafdb55a629>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> nil)
  emacsql-waiting-p(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614>)
  #f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0x92e0e5f738c339c>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614>)
  apply(#f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0x92e0e5f738c339c>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> nil)
  emacsql-wait(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614>)
  #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x8efc80ab572e7d1>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> [:pragma (= busy-timeout $s1)] 15000)
  apply(#f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x8efc80ab572e7d1>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> ([:pragma (= busy-timeout $s1)] 15000))
  emacsql(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> [:pragma (= busy-timeout $s1)] 15000)
  #f(compiled-function (conn slots) #<bytecode -0x39671f7d5872f2c>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  apply(#f(compiled-function (conn slots) #<bytecode -0x39671f7d5872f2c>) (#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o...")))
  #f(compiled-function (&rest args) #<bytecode 0x121303a8ba1f0ec8>)(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  apply(#f(compiled-function (&rest args) #<bytecode 0x121303a8ba1f0ec8>) #<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  initialize-instance(#<emacsql-sqlite3-connection emacsql-sqlite3-connection-bbf2614> (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x60290c9a3561f7e>)(emacsql-sqlite3-connection :file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o...")
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x60290c9a3561f7e>) emacsql-sqlite3-connection (:file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o..."))
  make-instance(emacsql-sqlite3-connection :file "c:/Users/USERID/AppData/Roaming/.emacs.d/data/o...")
  emacsql-sqlite3("c:/Users/USERID/AppData/Roaming/.emacs.d/data/o...")
  org-roam-db()
  org-roam-db-build-cache()
  (let (t1) (setq t1 (current-time)) (org-roam-db-build-cache) (float-time (time-since t1)))
  (benchmark-elapse (org-roam-db-build-cache))
  (list (benchmark-elapse (org-roam-db-build-cache)) (- gcs-done gcs) (- gc-elapsed gc))
  (let ((gc gc-elapsed) (gcs gcs-done)) (list (benchmark-elapse (org-roam-db-build-cache)) (- gcs-done gcs) (- gc-elapsed gc)))
  (benchmark-run 1 (org-roam-db-build-cache))
  eval((benchmark-run 1 (org-roam-db-build-cache)) t)
  benchmark(1 (org-roam-db-build-cache))
  eval((benchmark 1 '(org-roam-db-build-cache)) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

To be sure it's not an issue with the mingw sqlite3 executable I also tried wit hthe official one but the result is the same. Any checks you want me to perform that help you debug the issue?

**Comment by nobiot** [comment]
@Bassmann , Sorry my bad; the code was for performance testing. I confused the thread.

Could you try `M-x org-roam-db-build-cache` twice in a row? I expect the first call returns quickly with the deleted buffer message, but the immediate second one works.

**Comment by Bassmann** [comment]
Not sure what finally fixed it but after updating org-roam and adding config back line-by-line made the issue disappear. I think the issue can be closed
