### ISSUE TITLE
org-roam-capture issue

### ISSUE THREAD

**Issue by poulpoulsen** [org-roam/org-roam#860]
i try to use org-roam-capture with Firefox and Chrome on Linux Kubuntu 18.04 with Emacs 26.3.

here is my config:
 (require 'org-roam)
 (define-key org-roam-mode-map (kbd "C-c r b") #'org-roam-switch-to-buffer)
 (define-key org-roam-mode-map (kbd "C-c r d") #'org-roam-dailies-date) 
(define-key org-roam-mode-map (kbd "C-c r f") #'org-roam-find-file)
 (define-key org-roam-mode-map (kbd "C-c r g") #'org-roam-graph-show) 
(define-key org-mode-map (kbd "C-c r i") #'org-roam-insert)
 (define-key org-roam-mode-map (kbd "C-c r r") #'org-roam)
 (define-key org-roam-mode-map (kbd "C-c r t") #'org-roam-buffer-toggle-display)

(global-set-key (kbd "C-c C") 'org-roam-capture)

(setq org-roam-directory "/home/held/org-roam/")
 (setq org-agenda-files (directory-files-recursively org-roam-directory ".org$")) 
(setq org-roam-encrypt-files nil) (setq org-roam-link-title-format "R:%s")
(setq org-roam-tag-sources '(prop all-directories))
 (setq org-roam-tag-sort t)

(with-eval-after-load 'org-roam (with-eval-after-load 'company (with-eval-after-load 'org (require 'company-org-roam) (push 'company-org-roam company-backends)
 (require 'org-roam-protocol) )))

(org-roam-mode +1)

Here is the bookmarklet from Firefox (simple copied from documentation):
javascript:location.href = 'org-protocol://roam-ref?template=r&ref=' + encodeURIComponent(location.href) + '&title=' + encodeURIComponent(document.title)

The following is going wrong.

 Starting the bookmarklet starts Emacs.

 a buffer opens with name: "~/org-protocol:/roam-ref?template=r&ref=https%3A%2F%2Fwww.salz-helmreich.de%2Fkontakt&title=Online%20Kontaktformular"

 usually the org-capture keys should be available : C-c C-c or C-c C-k

but nothing... 
4. If i save the buffer with C-x C-s the following message pops up: Directory ‘/home/held/org-protocol:/’ does not exist; create? (y or n)

Very strange. It should save inside org-roam directory, right?

What is going wrong?

Regards
Poul

**Comment by jethrokuan** [comment]
Your `(require 'org-roam-protocol)` call is nested pretty deep in `with-eval-after-loads`. Can you move it out and place it at the top level? I think what's happening is that packages like `company` aren't yet loaded.

**Comment by poulpoulsen** [comment]
unfortunately no difference.
i put it upwards:
  (require 'org-roam-protocol)
  (require 'company-org-roam)
  (push 'company-org-roam company-backends)

What can i do now?

**Comment by natask** [comment]
I have had a similar issue. as discussed in [here](https://github.com/org-roam/org-roam-server/issues/39).  I added `(setq file (org-link-decode file))` to `org-roam-protocol-open-file` to solve this issue. find the function using `find-function`. It is in `org-roam-protocol.el`.

``` elisp
(defun org-roam-protocol-open-file (info)
  "This handler simply opens the file with emacsclient.

INFO is an alist containing additional information passed by the protocol URL.
It should contain the FILE key, pointing to the path of the file to open.

  Example protocol string:

org-protocol://roam-file?file=/path/to/file.org"
  (when-let ((file (plist-get info :file)))
    (raise-frame)
    ; the following line is what you need
    (setq file (org-link-decode file))
    (org-roam--find-file file))
  nil)
```

**Comment by poulpoulsen** [comment]
hello,
hmmh i insert your code inside my configuration.
After restart its stll the same...

```
Saving file /home/held/org-protocol:/roam-ref?template=r&ref=https%3A%2F%2Fwww.salz-helmreich.de%2Fkontakt&title=Online%20Kontaktformular...
Directory ‘/home/held/org-protocol:/’ does not exist; create? (y or n) n
basic-save-buffer: Canceled
Buffer roam-ref?template=r&ref=https%3A%2F%2Fwww.salz-helmreich.de%2Fkontakt&title=Online%20Kontaktformular modified; kill anyway? y
```
Because i'm not a developer, i can't change any code.
Can i help in any else case / thing.

**Comment by natask** [comment]
I didn't read too closely. You are having an issue with roam-ref not roam-file.

**Comment by natask** [comment]
I tried your config. it didn't work for me as well. `with-eval-after-load` isn't working for me. I updated it as follows.
``` elisp
(require 'org-roam)
(require 'org-roam-protocol)
(require 'company-org-roam)
(push 'company-org-roam company-backends)

(define-key org-roam-mode-map (kbd "C-c r b") #'org-roam-switch-to-buffer)
(define-key org-roam-mode-map (kbd "C-c r d") #'org-roam-dailies-date)
(define-key org-roam-mode-map (kbd "C-c r f") #'org-roam-find-file)
(define-key org-roam-mode-map (kbd "C-c r g") #'org-roam-graph-show)
(define-key org-mode-map (kbd "C-c r i") #'org-roam-insert)
(define-key org-roam-mode-map (kbd "C-c r r") #'org-roam)
(define-key org-roam-mode-map (kbd "C-c r t") #'org-roam-buffer-toggle-display)

(global-set-key (kbd "C-c C") 'org-roam-capture)

(setq org-roam-directory "/home/savnk/org-roam/")
(setq org-agenda-files (directory-files-recursively org-roam-directory ".org$"))
(setq org-roam-encrypt-files nil) (setq org-roam-link-title-format "R:%s")
(setq org-roam-tag-sources '(prop all-directories))
(setq org-roam-tag-sort t)

(org-roam-mode +1)
```

**Comment by poulpoulsen** [comment]
Could you please explain, how you see, that i have this issue?

**Comment by poulpoulsen** [comment]
> I didn't read too closely. You are having an issue with roam-ref not roam-file.

Could you please explain, how you see, that i have this issue?

**Comment by natask** [comment]
> Could you please explain, how you see, that i have this issue?

the java-script command you are running, `javascript:location.href = 'org-protocol://`**_roam-ref_**`?template=r&ref=' + encodeURIComponent(location.href) + '&title=' + encodeURIComponent(document.title)`, calls upon a protocol written for `org-protocol` called **_roam-ref_**.  org roam defines two such protocols: `roam-ref` and `roam-file`. You can find more information in the [documentation](https://org-roam.readthedocs.io/en/master/roam_protocol/), [org-protocol](https://orgmode.org/worg/org-contrib/org-protocol.html) and the source file [org-roam-protocol.el](https://github.com/org-roam/org-roam/blob/master/org-roam-protocol.el).

**Comment by jethrokuan** [comment]
@poulpoulsen does @natask 's configuration [here](https://github.com/org-roam/org-roam/issues/860#issuecomment-648435018) work for you?
