### ISSUE TITLE
Going back to the source from the side-buffer

### ISSUE THREAD

**Issue by rtrppl** [org-roam/org-roam#861]
I would like to use org-id to have backlinks pointing to a heading and not the file. How do I activate ids for org-roam? Is there something I have to add to .emacs? I have installed todays version (20200622.819) of org-roam. Thanks!

**Comment by jethrokuan** [comment]
This will all be addressed soon in #830 . But here's a quick overview for now:

IDs are automatically used to when using `org-roam-store-link` at a headline. This creates an id for the headline, stores it in the org-roam db, and storess in it your clipboard. Calling `org-insert-link` should then show the id link, which you can use to insert a backlink.

The backlinks buffer however, still shows the filename rather than the headline name. We will address this, and other UX issues in time to come.

**Comment by rtrppl** [comment]
Ok, thanks for the explanation (and this awesome project). If I do call `org-roam-store-link` the correct `:Properties:` are created. It would be great if that could/would be the default behaviour. Looking forward to change in the display of the backlinks.

**Comment by rtrppl** [comment]
One more question and sorry, if this might be obvious: Is it expected behaviour that `org-roam-store-link` does not work during `org capture`. Do I have to use `org-roam-capture` instead?

**Comment by jethrokuan** [comment]
It should work, related to #853. I see that "%a" is expanded to the id link obtained via `org-roam-store-link`.

**Comment by rtrppl** [comment]
I have this ` ("j" "Journal" entry (file+datetree "~/org/projects/!journal.org")
         "* %U %?\n %i\n")` as org-capture-template. If I invoke `org-roam-store-link` this `file:!journal.org::*\[2020-06-25 Thu 14:18\] test` is stored (and no ID is created).

**Comment by jethrokuan** [comment]
The function definition of `org-roam-store-link` is:

```
(defun org-roam-store-link (arg &optional interactive?)
  "Store a link to the current location.
This commands is a wrapper for `org-store-link' which forces the
automatic creation of :ID: properties.
See `org-roam-store-link' for details on ARG and INTERACTIVE?."
  (interactive "P\np")
  (if (org-roam--org-roam-file-p)
      (org-roam--store-link arg interactive?)
    (org-store-link arg interactive?)))
```

This means that `org-roam-store-link` only behaves differently if it is an org-roam file. So I suspect `!journal.org` is not an org-roam file.

**Comment by rtrppl** [comment]
This might be a stupid question (I'm new to this) but what qualifies an org-roam file? I mean, besides being in the correct folder that is. I noticed some weird behavior if there is no #+title in an org-roam file. Anyway, if I invoke `org-roam-store-link` on the same file (!journal.org) - but outside of org-capture - an org-id is created.

I noticed, however, that this id is not used to for the backlink. Please see the attached screenshot. "Daily Notes" only leads back to !journal.org.

![Bildschirmfoto 2020-07-10 um 08 28 11](https://user-images.githubusercontent.com/63909884/87124249-b5d1fc80-c288-11ea-890b-317b09d653c2.png)

**Comment by zaeph** [comment]
> This might be a stupid question (I'm new to this) but what qualifies an org-roam file? I mean, **besides being in the correct folder that is**.

That's the only condition.

Org-capture takes the local environment from the file to which it is _writing_, not the one from which it is _capturing_.  So, if you're capturing to `!journal.org`, and that `!journal.org` is outside your `org-roam-directory`, it would not force the use of `org-id` when storing the link.

Could you explicit your workflow with steps?  I'm having trouble wrapping my head around it.

**Comment by rtrppl** [comment]
Thanks for the quick reply!

> Org-capture takes the local environment from the file to which it is writing, not the one from which it is capturing. So, if you're capturing to !journal.org, and that !journal.org is outside your org-roam-directory, it would not force the use of org-id when storing the link.

But !journal.org is in the correct folder. As mentioned above

> ... **if I invoke org-roam-store-link on the same file (!journal.org) - but outside of org-capture** [in a regular buffer] **- an org-id is created**.

My typical workflow right now is:

1. I have found a new piece of information that does not warrant a new file, so I add it to my journal file (everything bucket). This is done by invoking org-capture.
2. Sometimes this information is related to the research I do, so I use `org-roam-insert` to link it to topical posts. This works, but the backlink does only point to the file (!journal.org), not the heading. 

This is what I would like to do:
1. Use org-capture
2. I use `org-store-link` (to create id's for the headlines) and then `org-roam-insert` to link it to topical posts. The backlinks then would point to the heading, not the file.

(btw it would be great if `org-store-link` is invoked automatically)

**Comment by zaeph** [comment]
> I would use `org-store-link` (to create id's for the headlines) and then `org-roam-insert` to link to topical posts. The backlinks then would point to the heading, not the file.

I think this is because you're trying to insert the link with `org-roam-insert`, but if you've used `org-roam-store-link` (our wrapper for `org-store-link`), you need to use `org-insert-link`.

I'm still not sure if I've understood you properly because you're not making it clear in your description where the forward-link _is_ vs. where it is pointing _to_.  Based on your description, I've assumed that you were trying to insert forward-links inside your `!journal.org` file.  Therefore, if you want to link to a specific headline in one of your topical notes, you would travel to them with `org-roam-find-file`, find the headline that interest you, `org-roam-store-link`, go back to `!journal.org`, and `org-insert-link` there.

> (btw it would be great if `org-store-link` is invoked automatically)

I'm not sure what you mean by that.  At which stage should it be done automatically?
I have an inkling that you're talking about having `org-roam-insert` allow you to insert links to headlines directly via a two-step expansion process (first file-titles, then file-headlines), and if it's so, it's something that we're planning to do.

**Comment by rtrppl** [comment]
Sorry for not being precise enough. I has hoping to find a way to improve the **target of backlinks**.

1. I write content in the journal file and point to files X, Y and Z, each covering a specific topic. 
2. Later,  when working on these topics, I invoke `org-roam` and look at the backlinks. At times I want to go back to the source of the backlink. Because the journal file is very long and nested, it would be great if the next higher headline would be the target of the backlink. 

(see modified screenshot)

I realize now that I might have understood the "pointing to headline" feature wrong.
![source](https://user-images.githubusercontent.com/63909884/87225379-d4212080-c38c-11ea-82a1-fd47e9df26f3.png)

**Comment by zaeph** [comment]
Thanks for the clarifying your question and for editing your screenshot: it's a lot clearer now. :)

There is actually a way to get back to the source, although it's not entirely obvious with the current state of the side-buffer.  If you you run `org-open-at-point` (`C-c C-o`) at the beginning of the context-line (`Linking to test`), you'll find that it brings you to the source.  I don't think the feature is documented, nor is it reliable all the time, but the technology is there to make it work.

We'll address this with the side-buffer revamp.

**Comment by rtrppl** [comment]
Thanks for the reply and the hint! I tried  `org-open-at-point` (`C-c C-o`) and it worked just fine. This is very helpful ;)

**Comment by jethrokuan** [comment]
This works on master now.
