### ISSUE TITLE
Rename files and automatically update title, database, and links

### ISSUE THREAD

**Issue by ksafford** [org-roam/org-roam#868]
### Brief Abstract
Sometimes I notice a typo in a file name, or discover that as a note evolves the original name is no longer ideal. It would be great to be able to rename the file, update the title, update all links, and of course update the database.

I believe this is the one feature that Zettledeft supports that really shines. (https://github.com/EFLS/zetteldeft/blob/master/zetteldeft.el#L389) Of course, that project doesn't have the complexity of dealing with backlinks.
### Long Description

This seems self-explanatory. But certainly non-trivial.

**Comment by wedens** [comment]
You can change the title and then rename the file (within emacs) and everything should update accordingly.

Also see https://org-roam.discourse.group/t/how-to-rename-a-note-with-everything-updated-at-the-same-time/300.

**Comment by ksafford** [comment]
Verified that this works, thank you.
