### ISSUE TITLE
Graph viewer gets incorrect file path on WSL2

### ISSUE THREAD

**Issue by karamme** [org-roam/org-roam#870]
### Description

I use Emacs GUI with WSL2 through an X11 environment. When using a native Windows browser, the filepath of the graph image is incorrect. This can be solved with minor adjustments.

#### Steps to Reproduce

1. Run Emacs as a GUI application with WSL2
2. Set `(setq org-roam-graph-viewer "/mnt/c/Program Files/Mozilla Firefox/firefox.exe")`
3. Run `org-roam-show-graph` and the browser will open but not the file

#### Expected Results

The browser will open the correct file.

#### Actual Results

The browser is not opening the correct file.

### Environment

- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.13)
 of 2019-12-24
- Framework: Doom
- Org: Org mode version 9.4
- Org-roam: 1.2.0

- Runs in WSL2 with Windows 10

### Hacky Solution

When I rewrite the `org-roam-graph--open` function and adjust the filepath of the call-process, everything works as espected.

``` lisp
  (defun org-roam-graph--open (file)
    "Open FILE using `org-roam-graph-viewer' with `view-file' as a fallback."
    (pcase org-roam-graph-viewer
      ((pred stringp)
       (if (executable-find org-roam-graph-viewer)
           (condition-case err
               (call-process org-roam-graph-viewer nil 0 nil (concat "file://///wsl$/Ubuntu" file))
             (error (user-error "Failed to open org-roam graph: %s" err)))
         (user-error "Executable not found: \"%s\"" org-roam-graph-viewer)))
      ((pred functionp) (funcall org-roam-graph-viewer file))
      ('nil (view-file file))
      (_ (signal 'wrong-type-argument `((functionp stringp null) ,org-roam-graph-viewer)))))
  )
```

So wrapping `file` with `(concat "file://///wsl$/Ubuntu" file)` does the trick for me.

### Proposed fix

I don't think there is a good way to autodetect this and I don't know enough lisp for a smart solution. Maybe there can be a variable one could set or a hook to solve this case. I know this might be a special setup, but keeping the rewritten function in my config seems kind of strange on the long run. Thanks.

**Comment by progfolio** [comment]
You could customize `org-roam-graph-viewer` to a function that modifies the file argument, binds the viewer program and then delegates to `org-roam-graph--open`:

```emacs-lisp
(setq org-roam-graph-viewer
      (lambda (file)
        (let ((org-roam-graph-viewer "/mnt/c/Program Files/Mozilla Firefox/firefox.exe"))
          (org-roam-graph--open (concat "file://///wsl$/Ubuntu" file)))))
```

**Comment by karamme** [comment]
Thanks a lot. This works and is much better. Looking at the docs, they kinda state that you can do something like this. But coming from the academic site, lisp is not that beginner friendly. I think it would be helpful to add this example to the docs. You mind if I propose a pull request that uses your solution together with an explanatin on how to set up org-protocol to work with wsl?

**Comment by progfolio** [comment]
> You mind if I propose a pull request that uses your solution together with an explanatin on how to set up org-protocol to work with wsl?

If you feel it will be helpful, go for it.
