### ISSUE TITLE
Source for doc/img/logo.png ?

### ISSUE THREAD

**Issue by spwhitton** [org-roam/org-roam#873]
Hello,

I'm packaging org-roam for Debian and we require source code for every file that gets included in the package.

Do you have the Inkscape source for doc/img/logo.png, please?

If that source has been lost to the mists of time such that logo.png is now the preferred form for modification, then we don't need to worry, so please let me know if that's the case.

Thanks!

**Comment by jethrokuan** [comment]
@zaeph

**Comment by jethrokuan** [comment]
@zaeph bump

**Comment by zaeph** [comment]
Oh, sorry, I've completely missed this the first time.  I'll add the source to the repo.

**Comment by zaeph** [comment]
Done in #943.  Sorry for the delay!

**Comment by spwhitton** [comment]
Hello,

On Thu 16 Jul 2020 at 01:21AM -07, Leo Vivier wrote:

> Done in #943.  Sorry for the delay!

Thank you for this.

-- 
Sean Whitton
