### ISSUE TITLE
org-protocol double and triple slashes in url compressed to single "// -> /"

### ISSUE THREAD

**Issue by MerlinsGreatBeard** [org-roam/org-roam#874]
### Description
Captured url looks like this:  "https:/github.com" 
Should look like this: "https://github.com".

Solved this in my local file by adding the following to org-roam-protocol-open-ref:

`(unless (assoc 'ref decoded-alist)`
`     (error "No ref key provided"))`
-> `  ;; Sanitize ref pls`
`    (push (cons 'ref (org-protocol-sanitize-uri (alist-get 'ref decoded-alist))) decoded-alist)`

    
#### Steps to Reproduce
use org-roam-protocol-open-ref
1. setup org-protocol as described in [documentation](https://www.orgroam.com/manual/The-roam_002dref-Protocol.html#The-roam_002dref-Protocol)
2. press ctl-r in browser
3. look at "#+roam_key:" in capture buffer

#### Expected Results
#+roam_key: https://github.com

#### Actual Results
#+roam_key: https:/github.com

### Environment
- Emacs: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
 of 2020-05-19
- Framework: N/A
- Org: Org mode version 9.3.7 (9.3.7-8-g3ed035-elpa @ /home/user/.emacs.d/elpa/org-20200629/)
- Org-roam: 1.2.0

https://github.com/org-roam/org-roam/commit/e33c3bcb3fae6927b023212a061c2273f0b9dea7

**Comment by jethrokuan** [comment]
I get the correct URL when I use the roam protocol. What does your bookmarklet look like?

**Comment by MerlinsGreatBeard** [comment]
I use qutebrowser with the script copied from the [documentation](https://www.orgroam.com/manual/The-roam_002dref-Protocol.html#The-roam_002dref-Protocol):

`config.bind("<Ctrl-r>", "spawn bash -c 'emacsclient \"org-protocol://roam-ref?template=r&ref={url:pretty}&title={title}\" '")`

When debugging I can see that _the_ ref value is missing a slash already in the _info_ plist argument sent from org-protocol to org-roam-protocol-open-ref:

(print info) upon entering org-roam-protocol-open-ref gives:

`(:template "r" :ref "https:/github.com/org-roam/org-roam" :title "org-roam/org-roam: Rudimentary Roam replica with Org-mode")`

**Comment by jethrokuan** [comment]
Is there an equivalent of `encodeURIElement` for qutebrowser? This will make the behaviour consistent with the bookmarklets that use Javascript.

**Comment by MerlinsGreatBeard** [comment]
Ah I see, the bookmarklet works.
I could simply bind the bookmarklet to a keybinding in qutebrowser like so: 

`config.bind("<Ctrl-r>", "open javascript:location.href='org-protocol://roam-ref?template=r&ref='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)")
`

I found a good discussion that actually mentions org-protocol and bookmarklets in qutebrowser [here](https://github.com/qutebrowser/qutebrowser/issues/221)

Maybe consider updating the documentation since the qutebrowser script causes single slashes in the url. 

Thanks alot!
