### ISSUE TITLE
allow alternative capture function

### ISSUE THREAD

**Issue by mohkale** [org-roam/org-roam#875]
### Brief Abstract
some packages/completion-frameworks offer their own alternatives to the builtin org-capture interface. org-roam should allow users to use these instead of the default interface.

### Long Description
The default capture interface shows up like this:

![20200630-11-00](https://user-images.githubusercontent.com/23294780/86156043-3eb89d80-bafd-11ea-97fb-ff4ca095939d.png)

I'm using the [counsel-projectile](https://github.com/ericdanan/counsel-projectile) so my interface is through the function `counsel-projectile-org-capture`. It appears more like this:

![20200630-13-58](https://user-images.githubusercontent.com/23294780/86156324-aa026f80-bafd-11ea-9826-69ef0c19831d.png)

There's also a builtin capture function in counsel called `counsel-org-capture`.

### Proposed Implementation (if any)
```diff
@@ -322,17 +322,26 @@
   :group 'org-roam
   :type 'hook)
 
+(defcustom org-roam-capture-function #'org-capture
+  "function that is invoked to start the org-capture process."
+  :group 'org-roam
+  :type 'function)
+
 (defun org-roam-capture--capture (&optional goto keys)
   "Create a new file, and return the path to the edited file.
 The templates are defined at `org-roam-capture-templates'.  The
 GOTO and KEYS argument have the same functionality as
 `org-capture'."
-  (let ((org-capture-templates (mapcar #'org-roam-capture--convert-template org-roam-capture-templates))
-        org-capture-templates-contexts)
-    (when (= (length org-capture-templates) 1)
+  (let* ((org-capture-templates (mapcar #'org-roam-capture--convert-template org-roam-capture-templates))
+         (one-template-p (= (length org-capture-templates) 1))
+         org-capture-templates-contexts)
+    (when one-template-p
       (setq keys (caar org-capture-templates)))
     (add-hook 'org-capture-after-finalize-hook #'org-roam-capture--save-file-maybe-h)
-    (org-capture goto keys)))
+    (if (or one-template-p
+            (eq org-roam-capture-function 'org-capture))
+        (org-capture goto keys)
+      (funcall-interactively org-roam-capture-function))))
 
 ;;;###autoload
 (defun org-roam-capture ()
```

reassigning `org-roam-capture-function` to `counsel-projectile-org-capture` works perfectly for me.

### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
Your patch looks fine, just needs to capitalize the docstring. Want to send in a PR?

**Comment by mohkale** [comment]
kay.
