### ISSUE TITLE
custom-initialize-reset: Invalid version syntax: ‘fatal: No names found, cannot describe anything.’ (must start with a number)

### ISSUE THREAD

**Issue by 20jam** [org-roam/org-roam#876]
Hay, I have a strange issue whenever I call org-roam command

I get this output message 

```elisp
version-to-list: Invalid version syntax: ‘fatal: No names found, cannot describe anything.’ (must start with a number)
```
my config 

```elisp
(use-package org :ensure t )
(use-package org-roam
      :ensure t
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-directory "~/notes/")
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n g" . org-roam-graph-show))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))
              (("C-c n I" . org-roam-insert-immediate))))
```

I use stright.el btw.

**Comment by AlexeyKamenew** [comment]
at first I am not emacs programmer (

Message is about org-version - try M-x org-version
org installed from straight does not work property (for me)

So I have installed org manually from GitHub
and write that at the beginning of my init file

(add-to-list 'load-path "~/.emacs.d/packages/org-mode/lisp")
(add-to-list 'load-path "~/.emacs.d/packages/org-mode/contrib/lisp" t)
(require 'org-loaddefs)

then I have tried to use
(staight-use-package 'org-roam)
but org-roam install ORG from straight yet

then I have tried to install org-roam manually - but makem.sh does not work property on OSX
old bash getopt and sed
I have tried to update with brew but have no success (make warn on dash s f ...)


then I just cloned org-roam
and does not use make )

and add to init
(require 'org-compat)

(straight-use-package 'emacsql)
(require 'emacsql)

(straight-use-package 'emacsql-sqlite3)
(require 'emacsql-sqlite3)

(add-to-list 'load-path "~/.emacs.d/packages/org-roam")
(require 'org-roam)

(setq org-roam-directory (format "%s/KB/" xdg-documents))
(define-key org-roam-mode-map (kbd "C-c n l") #'org-roam)
(define-key org-roam-mode-map (kbd "C-c n f") #'org-roam-find-file)
(define-key org-roam-mode-map (kbd "C-c n j") #'org-roam-jump-to-index)
(define-key org-roam-mode-map (kbd "C-c n b") #'org-roam-switch-to-buffer)
(define-key org-roam-mode-map (kbd "C-c n g") #'org-roam-graph)
(define-key org-mode-map (kbd "C-c n i") #'org-roam-insert)
(setq org-roam-link-title-format "R:%s")
(setq org-roam-index-file "index.org")
(setq org-roam-completion-system 'ivy)

(org-roam-mode +1)

and all work!

**Comment by jethrokuan** [comment]
`org-roam` installed from MELPA is the easiest way to get up and running: `M-x package-install org-roam`.

https://www.orgroam.com/manual/Installing-from-MELPA.html#Installing-from-MELPA

**Comment by pRot0ta1p** [comment]
For me,
(straight-use-package '(org :type built-in))
fix this. 
By default straight will pull org from git if some package use org as dependency, this elisp code force straight to use the org package shipped with emacs
