### ISSUE TITLE
Make the Helm-Mini buffer read-only and make an easy way to close it.

### ISSUE THREAD

**Issue by treymerkley** [org-roam/org-roam#879]
#### Steps to Reproduce

1. Load Emacs
2. Run `evil-mode`
3. Run `org-roam-find-file`
4. Select a file
5. Run `org-roam-insert`
6. Click anywhere in the `org-roam-insert` Helm mini buffer
7. Enter insert mode with `i`
You can now type anywhere and you can't continue making the insertion.

8. Press `esc` to enter command mode and press `:q` to close the Helm mini buffer.
You cannot work until the `org-roam-insert` timer runs out.

#### Expected Results

The `org-roam-insert` buffer is read-only and I cannot edit it. Additionally. `C-g` or another key combination exists for me to be able to exit the buffer safely.

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
 of 2020-05-19
- Framework: Spacemacs
- Org: Org mode version 9.3.7 (9.3.7-4-gba6ca7-elpaplus @ /home/trey/.emacs.d/elpa/26.3/develop/org-plus-contrib-20200622/)
- Org-roam: 1.2.0

**Comment by TimQuelch** [comment]
This sounds like a helm issue and not an org-roam issue

**Comment by treymerkley** [comment]
I would think so, but other applications of the Helm-mini, ex buffer selection under Spacemacs, have `C-g` to close and there's not even a way to click within the text area of the buffer, which makes me think it's something that is configured on the org-roam side.
