### ISSUE TITLE
Files and Links are lost when upgrading to 1.2.0

### ISSUE THREAD

**Issue by tea4or2wo** [org-roam/org-roam#881]
### Description

`org-roam` database does not update since I moved to 1.2.0.

I did check `sqlite3` is located on `exec-path`.

I get error similar to #836 in my `Messages` buffer at startup:
`Eager macro-expansion failure: (error "Unknown rx form ‘anychar’")` with `org-roam` up to date.

I can recover my db with `org-roam-db--clear` and `org-roam-db-build-cache` consecutively.

Every time I close Emacs, I get back to `(org-roam) files: 0, headlines: 0, links: 0, tags: 0, titles: 0, refs: 0, deleted: 0` at startup and need to repeat this procedure. Executing `org-roam-db-build-cache` only does not work.

I checked #808 and #811 that did not help.

#### Steps to Reproduce

For actual result:
1. Load Emacs

For expected result:
1. Load Emacs
2. Run `org-roam-db--clear`
3. Run `org-roam-db-build-cache`

#### Backtrace

N/A

#### Expected Results

`(org-roam) files: 4, headlines: 2, links: 1, tags: 0, titles: 4, refs: 0, deleted: 0`

#### Actual Results

`(org-roam) files: 0, headlines: 0, links: 0, tags: 0, titles: 0, refs: 0, deleted: 0`

### Environment

- Emacs: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2019-09-05
- Framework: N/A
- Org: Org mode version 9.3.6 (9.3.6-elpa @ /home/myname/.emacs.d/elpa/org-9.3.6/)
- Org-roam: 1.2.0

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/eca07277cee2204a9327f9ab8bf766dd0614cb56

**Comment by tea4or2wo** [comment]
Am I one commit below `master`? If so, how to force `org-roam` update from MELPA?

**Comment by tea4or2wo** [comment]
I walk step-by-step and Emacs `*Help*` suggests that I am below `master`

`Other versions: 1.2.0 (melpa-stable), 20200701.1524 (melpa).`

because `melpa-stable` prevails over `melpa` in my config.

I just updated `org-roam` and `Eager macro-expansion failure: (error "Unknown rx form ‘anychar’")` message has gone.

However, main issue remains unsolved.

**Comment by jethrokuan** [comment]
```
I get back to (org-roam) files: 0, headlines: 0, links: 0, tags: 0, titles: 0, refs: 0, deleted: 0
```

This doesn't mean there are no files in your database. That's the diff since the last db update (so 0 new files). This is the typical numbers you should see.

**Comment by rudi** [comment]
> ```
> I get back to (org-roam) files: 0, headlines: 0, links: 0, tags: 0, titles: 0, refs: 0, deleted: 0
> ```
> 
> 
> This doesn't mean there are no files in your database. That's the diff since the last db update (so 0 new files). This is the typical numbers you should see.

I remember being confused about this as well. Maybe it should read

`(changes in org-roam) files: 0, headlines: 0, links: 0, tags: 0, titles: 0, refs: 0, deleted: 0`

**Comment by tea4or2wo** [comment]
Thanks for replies.

OK then, why does db not update at startup, event after changes in files and links?

Knowing `org-roam-directory` and `(add-hook 'after-init-hook 'org-roam-mode)` are set in my config, it should be done automatically according to manual and [this comment](https://github.com/org-roam/org-roam/issues/677#issuecomment-635731644), am I right?

**Comment by jethrokuan** [comment]
> OK then, why does db not update at startup, event after changes in files and links?

It should. If it doesn't, it's a bug. Do you have a minimally reproducible example?

> PS. I tried to revert order between org-roam-directory and (add-hook 'after-init-hook 'org-roam-mode) in init with no success.

The order should not matter.

**Comment by tea4or2wo** [comment]
Thank you @jethrokuan and thanks for the "delta" update.

I think my config works fine, org-roam db is updated when calling `org-roam-insert-link`.

I feel I'm just confused about when the update message shows up: I see it on startup in `*Messages*` but I obviously do not work with `org-roam` when Emacs is closed. On the other hand, the message never occurs in `*Messages*` when working with org-roam (I can see db is updating by automatic savings).

Thanks anyway for this great package I have been watching for a few weeks. It sure does not fit any workflow by itself and I'm in the process of choosing between a few huge files (my habitual workflow) and org-roam possibilities.

Thanks also for great follow-up with both power users and noobs.

**Comment by jethrokuan** [comment]
The message only appears on explicit calls to `org-roam-db-update` (which running `org-roam-mode` does), so it doesn't appear during incremental updates e.g. on file changes and saves. Hope that clears things up!
