### ISSUE TITLE
Ability to organize inserted notes in subdirectories

### ISSUE THREAD

**Issue by OmarAshkar** [org-roam/org-roam#888]
### Brief Abstract
I need to get org-roam to insert/create new created notes in a subdirectories if separated by /

### Long Description
I use org-roam for all my notes files. I get so of a hassle to have all created notes in one directory. This forces everything to be accessed only from org-roam. It is very difficult to navigate the files otherwise.

### Proposed Implementation (if any)
org-roam-insert should support insertion in/creation of directiories on the fly

### Please check the following:

- [ ] No similar feature requests

**Comment by rodelrod** [comment]
If you want to use a fixed set of directories, you can use [org-roam-capture-templates](https://org-roam.readthedocs.io/en/master/templating/) for this.

**Comment by omarelashkar** [comment]
> If you want to use a fixed set of directories, you can use [org-roam-capture-templates](https://org-roam.readthedocs.io/en/master/templating/) for this.

Unfortunately not. I adopt similar approch with linking files all together. I like the idea of backlinks and the upcoming feature of linking by headline ID. I usually have multiple headlines of related ideas in one file. And all related files in one subdirectory in the org directory.

**Comment by asheidan** [comment]
I think this issue is related to #635 if not the same one.

**Comment by zaeph** [comment]
Yes, they are related.  #635 is an implementation discussion, whereas #888 is more of a general discussion on the feature.  I haven't had time to work on this yet, but we've got some ideas.

**Comment by eccentric-j** [comment]
I would very much enjoy this feature as well. I'm using subdirectories as tags in addition to the tags property, an example would be `work/cloud-services/Overview.org` where work and cloud-services are always going to be true. Additionally, if I switch jobs it will be easy to archive my previous work-related stuff and start fresh.

I've looked into customizing it myself, I think it could be done like:

Update org-roam-capture

1. Split the title by / characters (may need a variable to support more OSes)
2. The title should be the last item in the parts
3. Create a dir var by joining the remaining paths (all but the last) to get the directory
4. When setting `org-roam-capture--info`, additionally append `(cons 'dir dir)`

Now in templates I am expecting I can use a template like the following:

```
  ("d" "default" plain (function org-roam--capture-get-point)
       "%?"
       :file-name "$(dir)/%<%Y%m%d%H%M%S>-${slug}"
       :head "#+title: ${title}\n"
       :unnarrowed t)
```

Is that how you would approach it?

**Comment by eccentric-j** [comment]
After writing it out, it didn't seem that hard. Took a few tries but this seems to be working for me. I could create a PR but want to make sure we're on the same page and I'm not missing any nuances on this first.

```lisp
(defadvice! j/org-roam-capture (&optional goto keys)
  "Launches an `org-capture` process for a new existing note.
This uses the templates defined at `org-roam-capture-templates`.
Arguments GOTO and KEYS see `org-capture`."
  :override #'org-roam-capture
  (interactive "P")
  (unless org-roam-mode (org-roam-mode))
  (let* ((completions (org-roam--get-title-path-completions))
         (title-with-keys (org-roam-completion--completing-read "File: "
                                                                completions))
         (res (cdr (assoc title-with-keys completions)))
         (title (or (plist-get res :title) title-with-keys))
         (tags (split-string title "/"))
         (title (car (last tags)))
         (dir (string-join (butlast tags) "/"))
         (dir (if (string-blank-p dir) "" (concat dir "/")))
         (file-path (plist-get res :path)))
    (let ((org-roam-capture--info (list (cons 'title title)
                                        (cons 'slug (funcall org-roam-title-to-slug-function title))
                                        (cons 'file file-path)
                                        (cons 'dir dir)))
          (org-roam-capture--context 'capture))
      (condition-case err
          (org-roam-capture--capture goto keys)
        (error (user-error "%s.  Please adjust `org-roam-capture-templates'"
                           (error-message-string err)))))))
```

To use it:

```lisp
(setq org-roam-capture-templates 
  (list
        '("d" "default" plain (function org-roam--capture-get-point)
          "%?"
          :file-name "${dir}%<%Y%m%d%H%M%S>-${slug}"
          :head "#+title: ${title}\n"
          :unnarrowed t)))
```

Now you can do `org-roam-capture` put in a path like `work/docs/cloud-services/Components` and it will generate an entry for `<org-roam-directory>/work/docs/cloud-services/20200924160205-components.org`.

**Comment by omarelashkar** [comment]
@eccentric-j  No man, I don't think that's how org-roam-capture works, It already search for all files and help you insert a cursor quickly as you like in a custom file. I am requesting about org-roam-insert, where you highlight a word and insert a new org note based on that. I have not tried your function, but I don't think it's a good idea for capture to do insert function

**Comment by eccentric-j** [comment]
@omarelashkar Look at the source: https://github.com/org-roam/org-roam/blob/02fda3adb18109db6c06ac793a2dcc8855a93d2f/org-roam.el#L1584-L1641

org-roam-find, org-roam-insert, and org-roam-capture all go through the org roam capture feature.

I've been using this feature regularly and have updated support for both org-roam-find, and org-roam-insert. 

https://github.com/eccentric-j/dotfiles/blob/93d6be7d934371eb434067c8ee48b6e2574b5f7b/client/doom.d/config.org#create-org-roam-files-in-tag-directories

**Comment by anildigital** [comment]
@OmarAshkar @eccentric-j Is this feature implemented? Can I create new files inside subdirectories using `org-roam-insert` ? Thanks

**Comment by jethrokuan** [comment]
> Now in templates I am expecting I can use a template like the following:
> 
> ```
>   ("d" "default" plain (function org-roam--capture-get-point)
>        "%?"
>        :file-name "${dir}/%<%Y%m%d%H%M%S>-${slug}"
>        :head "#+title: ${title}\n"
>        :unnarrowed t)
> ```
> 
> Is that how you would approach it?

@anildigital This is how it works, and is already implemented.

**Comment by anildigital** [comment]
@jethrokuan I want to pass `a/b/c` from outside while I run `org-roam-insert` so that directoy is dynamic.

**Comment by jethrokuan** [comment]
I have no intention on working on this, but a PR is welcome.
