### ISSUE TITLE
Tracking backlinks within the same file

### ISSUE THREAD

**Issue by Shurakai** [org-roam/org-roam#892]
### Brief Abstract
Allow users to track backlinks within the same file.

### Long Description
I only have one single (large) file, `journal.org`, which contains the following structure:

>\* 2020  
>  
>\*\* \[2020-07-05 Sun\]  
>  
>\*\*\* My first entry :sometag:  
>  
>\*\*\* My second entry :someothertag:

This structure is of course repeated: For every year, a first order headline is added and for every day a second order headline. 

When I tried to link between headlines, this worked, but the org-roam-backlinks window showed me all the links from one headline to another. This is actually expected, because they effectively linked back to *that* *file*. But since all entries are in *that file*, this would mean that I would see all backlinks from `journal.org` to `journal.org` all the time. I'd rather only see backlinks from single headlines (in `journal.org`) to a specific headline (that I just selected) in `journal.org`.

### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
This feature request is similar to #801. Will look into it with the buffer revamp.

**Comment by carlos-wong** [comment]
Hi @jethrokuan , how's going on of this feature.  If you are designing the table about this feature or branch already created for the feature pls let me know. I like to help to develop this feature. Because I am also the big org file user who use org-id to link headlines

**Comment by jethrokuan** [comment]
@carlos-wong you can check out the v2 branch, which allows for backlink tracking via IDs like you mentioned.

**Comment by jethrokuan** [comment]
v2 is now merged.
