### ISSUE TITLE
Prefer defcustom over defvar where appropriate

### ISSUE THREAD

**Issue by progfolio** [org-roam/org-roam#895]
Users are  unable to leverage the customization system for variables defined with defvar (e.g. org-roam-capture-templates, org-roam-capture-ref-templates, etc.).

**Comment by myshevchuk** [comment]
Sorry, I didn't see this issue. Can #922 be merged here?

**Comment by progfolio** [comment]
#924 does not address `org-roam-capture-ref-templates`.

**Comment by zaeph** [comment]
Yes, sorry for that, should have double-checked.

**Comment by progfolio** [comment]
No problem. Additionally: `org-roam-dailies-capture-templates` is still a defvar.

**Comment by myshevchuk** [comment]
Yeah, so would it be possible to combine #922 and this, because they are the same issue.

**Comment by zaeph** [comment]
Let's close #922, then, since the issue mentioned in the title has been addressed by #924.

**Comment by myshevchuk** [comment]
But there are questions there that have not been answered.

**Comment by myshevchuk** [comment]
I thought it was possible to somehow merge the issues, to transfer the discussion from one issue o another, bu probably I confuse it with something else.

**Comment by zaeph** [comment]
I've checked, and it doesn't seem to be possible.  Could you migrate your question to a different issue, since they're somewhat out of the scope of creating `defcustom` templates for the template-variables?

**Comment by myshevchuk** [comment]
The questions were about creating the defcusoms. It is possible to do this in several different ways, so I wanted to clarify which way was preferable. Basically, I wanted to know whether `plain`, `(function org-roam-capture—get-point)`, `:unnarrowed t` should be hidden from the user and whether `:file-name` and `:Head` are optional. This is purely for defcustom and doesn’t touch the variable itself.

**Comment by zaeph** [comment]
Right, I'd misread them, then.  I still think that there are interesting ramifications to those questions, i.e., whether we actually need those in the first place.  It'll be interesting to gauge this when the time comes to reconsider `org-capture`.

**Comment by myshevchuk** [comment]
Could someone please assign me to this issue, so I don't forget it please?

**Comment by myshevchuk** [comment]
I see that definition of `org-roam-capture-immediate-template` has changed. I assume it's an internal variable now and does not require a `defcutom`?

```elisp
(defvar org-roam-capture-immediate-template
  (append (car org-roam-capture-templates) '(:immediate-finish t))
  "Capture template to use for immediate captures in Org-roam.
This is a single template, so do not enclose it into a list.
See `org-roam-capture-templates' for details on templates.")
```

**Comment by jethrokuan** [comment]
it can be changed into a `defcustom`. It's just a singular version of `org-roam-capture-templates`, with the default being the first item in `org-roam-capture-templates` with `immediate-finish` set to `t`.

**Comment by myshevchuk** [comment]
Yeah, I remember it was some time ago. I thought that since it's now set automatically from `org-roam-capture-templates`, it's no longer a user variable.
