### ISSUE TITLE
Can't install on OSX+emacs 27

### ISSUE THREAD

**Issue by AlexeyKamenew** [org-roam/org-roam#899]
### Description

Install org-roam

OSX 10.15.5
Emacs 27

#### Steps to Reproduce

(straight-use-package 'org-roam)
(require 'org-roam)

#### Backtrace

Debugger entered--Lisp error: (error "Invalid version syntax: ‘fatal: No names found, ca...")
  signal(error ("Invalid version syntax: ‘fatal: No names found, ca..."))
  error("Invalid version syntax: `%s' (must start with a nu..." "fatal: No names found, cannot describe anything.")
  version-to-list("fatal: No names found, cannot describe anything.")
  version<("fatal: No names found, cannot describe anything." "9.3")
  byte-code("\300\301\302\303#\210\304\301\302\305#\210\300\306\307\303#\210\304\306\307\305#\210\300\310\311\303#\210\304\310\311\305#\210\300\312\313\303#\210\304\312\313\305#\210\300\314..." [defalias org-roam--capture-get-point org-roam-capture--get-point nil make-obsolete "org-roam 1.0.0" org-roam-build-cache org-roam-db-build-cache org-roam-sql org-roam-db-query org-roam--get-db org-roam-db--get org-roam--db-clear org-roam-db--clear org-roam-show-graph org-roam-graph-show org-roam--maybe-update-buffer org-roam-buffer--update-maybe org-roam--current-visibility org-roam-buffer--visibility org-roam-update org-roam-buffer-update org-roam--set-width org-roam-buffer--set-width org-roam--set-height org-roam-buffer--set-height org-roam--set-up-buffer org-roam-buffer--get-create org-roam-today org-roam-dailies-today org-roam-tomorrow org-roam-dailies-tomorrow org-roam-yesterday org-roam-dailies-yesterday org-roam-date org-roam-dailies-date org-roam-graph org-roam-graph-build org-roam-find-index org-roam-jump-to-index "org-roam 1.1.0" org-roam--pluralize org-roam-buffer--pluralize org-roam--capture org-roam-capture--capture org-roam-db--maybe-update org-roam-db--update-maybe version< org-version "9.3" ...] 7)
  require(org-roam-compat)
  eval-buffer(#<buffer  *load*-172720> nil "/Users/kamenew/.emacs.d/straight/build/org-roam/or..." nil t)  ; Reading at buffer position 1801
  load-with-code-conversion("/Users/kamenew/.emacs.d/straight/build/org-roam/or..." "/Users/kamenew/.emacs.d/straight/build/org-roam/or..." nil t)
  require(org-roam)
  eval-buffer(#<buffer  *load*-638786> nil "/Users/kamenew/.emacs.d/config.el" nil t)  ; Reading at buffer position 50674
  load-with-code-conversion("/Users/kamenew/.emacs.d/config.el" "/Users/kamenew/.emacs.d/config.el" nil nil)
  load("/Users/kamenew/.emacs.d/config.el" nil nil t)
  load-file("/Users/kamenew/.emacs.d/config.el")
  (if (file-exists-p (expand-file-name "config.el" user-emacs-directory)) (load-file (expand-file-name "config.el" user-emacs-directory)) (org-babel-load-file (expand-file-name "config.org" user-emacs-directory)))
  (let ((file-name-handler-alist nil)) (if (file-exists-p (expand-file-name "config.el" user-emacs-directory)) (load-file (expand-file-name "config.el" user-emacs-directory)) (org-babel-load-file (expand-file-name "config.org" user-emacs-directory))))
  eval-buffer(#<buffer  *load*> nil "/Users/kamenew/.emacs.d/init.el" nil t)  ; Reading at buffer position 584
  load-with-code-conversion("/Users/kamenew/.emacs.d/init.el" "/Users/kamenew/.emacs.d/init.el" t t)
  load("/Users/kamenew/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1fe831289289>) #f(compiled-function () #<bytecode 0x1fe8312892a1>) t)
  command-line()
  normal-top-level()

#### Expected Results

Installed package

**Comment by AlexeyKamenew** [comment]
incorrect emacs initialisation

**Comment by jethrokuan** [comment]
Do you know what exactly went wrong here? Similar to #876
