### ISSUE TITLE
org-roam-capture--get-point returning strange error

### ISSUE THREAD

**Issue by thor314** [org-roam/org-roam#903]
May be putting this in the wrong location. Point me in the right one if that's the case.
### Description
Could be that I'm just doing something wrong, but I appended the default, 

```
("d" "default" plain (function org-roam--capture-get-point)
     "%?"
     :file-name "%<%Y%m%d>-${slug}"
     :head "#+title: ${title}\n"
     :unnarrowed t)
```
to my org-capture-templates (the rest of which are working as expected), and I get the error message `Invalid org-roam-capture-context`. 
I've also tried to change the default filename with:
`(setq org-roam-capture--file-name-default "<%Y-%m%-%d>")`,
but that doesn't appear to change the default timestring captures. Am I misunderstanding something simple?

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
 of 2019-09-02
- Framework: N/A
- Org: Org mode version 9.3.7 (9.3.7-8-g3ed035-elpa @ /Users/thor/.emacs.d/elpa/org-20200629/)
- Org-roam: 1.2.0

**Comment by jethrokuan** [comment]
Hi, the capture templates for org-roam don't work with regular org-capture.

The variable you need to modify is `org-roam-capture-templates`, and which are used by the interactive functions `org-roam-insert`, `org-roam-find-file`, and `org-roam-capture`.

**Comment by thor314** [comment]
Alright, thanks. I'm having a different problem now with setting `org-roam-capture templates`. I visited [your dot file](https://github.com/jethrokuan/dots/blob/master/.doom.d/config.el?#L432)
and made sure to get the syntax right. I copied the following into my config:

```
 (setq org-roam-capture--file-name-default "<%Y-%m%-%d>")
 (setq org-roam-capture-templates
        '(("l" "lit" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "lit/${slug}"
           :head "#+setupfile:./hugo_setup.org
#+hugo_slug: ${slug}
#+title: ${title}\n"
           :unnarrowed t)
))

 (setq org-roam-capture-ref-templates
        '(("r" "ref" plain (function org-roam-capture--get-point)
           "%?"
           :file-name "lit/${slug}"
           :head "#+setupfile:./hugo_setup.org
#+roam_key: ${ref}
#+hugo_slug: ${slug}
#+roam_tags: website
#+title: ${title}
- source :: ${ref}"
           :unnarrowed t)))
```

On `org-roam-capture`, I'm now getting the error "Nested Org-roam capture processes not supported".

**Comment by thor314** [comment]
Also having issues with graph viz. `org-roam-graph` produces an xml file. 
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
...
```
I'd like it to show the graph. The [documentation](https://www.orgroam.com/manual/Graphing.html#Graphing) suggests this is possible?

**Comment by jethrokuan** [comment]
> On org-roam-capture, I'm now getting the error "Nested Org-roam capture processes not supported".

Are you running it within an org-capture buffer? For various engineering reasons, you can't do that right now, it is a tracked issue #527 .

> Also having issues with graph viz. org-roam-graph produces an xml file.

The xml file is likely the SVG for the graph, which you should be able to view in your favourite viewer (e.g. Firefox).

**Comment by thor314** [comment]
> Are you running it within an org-capture buffer? For various engineering reasons, you can't do that right now, it is a tracked issue #527.

I don't seem to be able to reproduce the error anymore. Sorry for the bother. 
> xml
I've copied the lines
```
(setq org-roam-graph-viewer
    (lambda (file)
      (let ((org-roam-graph-viewer "/Applications/Safari.app")))))
```
Which returns the text `(org-roam) building graph`, but doesn't open Safari. I've also tried with "Brave\ Browser.app" and removing the ".app".

**Comment by jethrokuan** [comment]
> Which returns the text (org-roam) building graph, but doesn't open Safari. I've also tried with "Brave\ Browser.app" and removing the ".app".

Those are not valid executables in the terminal. You might need to find the executable binary, typically located within the `.app` bundle. E.g. `...Firefox.app/bin/firefox` (no clue whether it's there, but I know there's one for firefox)

**Comment by thor314** [comment]
Thanks. In case that comes up again, MacOS stores browser executables at:
/Applications/<Browser>.app/Contents/MacOS/<Browser>

However, I've tried two browsers (Brave and Safari), and neither of the successfully open the graph; both get stuck at `(org-roam) building graph`. Eg, I have:
```
(setq org-roam-graph-viewer
    (lambda (file)
      (let ((org-roam-graph-viewer "/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser")))))
```

**Comment by jethrokuan** [comment]
your config should just be:

```
(setq org-roam-graph-viewer "/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser")
```

The part in the manual is specifically for those using WSL, who need to modify the path to the file to fit the virtual filesystem.

**Comment by thor314** [comment]
Awesome, thanks for the help.
