### ISSUE TITLE
org-roam not respecting `org-todo-keywords`

### ISSUE THREAD

**Issue by cantao** [org-roam/org-roam#905]
#### Steps to Reproduce

1. Load Emacs
2. Open a roam file
3. Hit `org-todo` to change TODO to DEFERRED (from my `org-todo-keywords`)
4. org-roam pulls up another set of keywords (Doom Emacs default?)

#### Backtrace
No backtrace because it does not break things apart.

#### Expected Results

My `org-todo-keywords` appearing for selection. In not-roam org files it works perfectly.

#### Actual Results

Another set of keywords, probably Doom Emacs' default ones.

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-19
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/cantao/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.0

Thank you very much!

**Comment by jethrokuan** [comment]
I cannot reproduce (it's using my set of `org-todo-keywords`)

How are you customizing `org-todo-keywords`? Are they file specific?

**Comment by cantao** [comment]
In .doom.d/config.el:

For org-mode:

```
(use-package! org
  :defer t
  :config
  (setq org-agenda-files (list my-org-dir my-roam-dir)
        ;; ... lots of org mode configuration ...
        org-todo-keywords '((sequence "TODO(t)" "NEXT(n)" "WAITING(w@)" "|" "DONE(d@)" "CANCELLED(c@)" "DEFERRED(r@)"))
        ;; ... lots more ....
))
```
For org-roam:
```
(use-package! org-roam
  :defer t
  :config
  (setq org-roam-directory my-roam-dir
        org-roam-index-file (concat my-roam-dir "roam-index.org")))
```
I have similar sections for `org-ref`, `org-roam-bibtex`, `deft` and so on. Variables starting with `my-` refer to directories or files.

**Comment by zaeph** [comment]
Are you sure the problem is caused by Org-roam?  Could you comment out the `use-package` block for Org-roam and try again?

**Comment by cantao** [comment]
Very strange. It must be something with the order packages are loaded. I tried commenting everything except org-mode and org-roam. Tried uncommenting one block at a time and now I can't reproduce the problem :-|

I'll make some more tests and close the bug if cannot reproduce it.

**Comment by cantao** [comment]
Well, I have used everything as usual (`mu4e`, `org-roam`, etc) and the problem is gone. It seems Emacs got lost somehow. Thanks for your time guys, specially for the excelent work!
