### ISSUE TITLE
org-roam backlinks linking to emacs backup files after editing 

### ISSUE THREAD

**Issue by npalermo10** [org-roam/org-roam#909]
### Description
When I edit a file, everything that was linked to it instead links to the file's emacs backup (the filename ending in "~"). 

#### Steps to Reproduce
run org-roam-find to find a file with backlinks
edit the file and save it
all backlinks to that file dissappear
If you check any of the files that were previously linked they have all changed their target file to the emacs backup '~' of the file instead.

### Environment
- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)
 of 2020-03-26, modified by Debian
- Framework: N/A
- Org: Org mode version 9.3.6 (9.3.6-elpa @ /home/nick/.emacs.d/elpa/org-9.3.6/)
- Org-roam: 1.2.0
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by zaeph** [comment]
Someone mentioned a similar issue on Slack today.

As a temporary measure, you can start storing your backup files in a dedicated directory *outside* of the CWD:
```el
(setq backup-directory-alist '(("." . "~/.saves")))
```

@jethrokuan: Have we recently touched something that might cause that behaviour?  Mind you, I haven't tried reproducing it, yet.

**Comment by npalermo10** [comment]
that temporary fix definitely works! thank you and thanks for all the hard work. I love this program.

**Comment by jethrokuan** [comment]
Likely to be this: https://github.com/org-roam/org-roam/pull/894

**Comment by zaeph** [comment]
I cannot reproduce this.

I've tried with the following settings, which should be close to default:
```el
;; Don’t clobber symlinks
(setq backup-by-copying nil)

;; Use versioned backups
(setq version-control nil)

;; Number of backups to keep
(setq kept-new-versions 10
      kept-old-versions 2
      delete-old-versions nil)

;; Backup directories
;; (setq backup-directory-alist '(("." . "~/.saves")))
(setq backup-directory-alist nil)

;; Also backup versioned files
(setq vc-make-backup-files nil)
```

I've also tried with my personal settings, minus
```el
;; Don’t clobber symlinks
(setq backup-by-copying t)

;; Use versioned backups
(setq version-control t)

;; Number of backups to keep
(setq kept-new-versions 10
      kept-old-versions 0
      delete-old-versions t)

;; Backup directories
;; (setq backup-directory-alist '(("." . "~/.saves"))) ;Commented out for testing
(setq backup-directory-alist nil)

;; Also backup versioned files
(setq vc-make-backup-files t)
```

#917 addressed a problem which prevented certain renames from being carried out, and the error was silent.
@npalermo10, @mxco86, could you try reproducing the problem on your ends?

**Comment by npalermo10** [comment]
I thought last night that changing the backup directory to an external one ".saves" fixed the problem but I was wrong. The links would then point to the backup file in the .saves directory. The only thing that is working currently is to just turn off the backups entirely. 

`    (setq make-backup-files nil)`

**Comment by zaeph** [comment]
Have you tried updating the packages?  We've pushed some changes that might have resolved this problem.

**Comment by sjrmanning** [comment]
For what it's worth the change hasn't fixed the issue for me, only `(setq make-backup-files nil)` works even on the latest commit.

What did work was [this commit](https://github.com/mxco86/org-roam/commit/3b98e5a426dde1a6e138487cce01db1ab5634520) from the Slack with `(setq make-backup-files t)`. Also FWIW in my config backup files are already being put into another directory.

**Comment by zaeph** [comment]
The changes you mentioned are in #915.

Since I cannot test this, I'd like to confirm that the PR also solves @npalermo10's and @mxco86's problems.  Could you check out the PR and confirm this?

**Comment by npalermo10** [comment]
commit 3b98e5a426dde1a6e138487cce01db1ab5634520  does fix it for me. Thanks!

> The changes you mentioned are in #915.
> 
> Since I cannot test this, I'd like to confirm that the PR also solves @npalermo10's and @mxco86's problems. Could you check out the PR and confirm this?

**Comment by mxco86** [comment]
FWIW I can reliably reproduce using this backup config on GNU Emacs 27.0.91 

`
    (setq backup-dir "~/.emacs.d/.backups/")
    (setq backup-directory-alist '(("." . "~/.emacs.d/.backups")))
    (setq version-control t)
    (setq delete-old-versions nil)
`

**Comment by zaeph** [comment]
Even with #915 merged?

**Comment by mxco86** [comment]
No - pre-merge :)

**Comment by sjrmanning** [comment]
@zaeph Thanks for your work on this! To confirm, looks like I had tested before that latest merge. Working perfectly now :)
