### ISSUE TITLE
commit: efba3c2bf0c887 breaks org-roam-graph, bibtex and roam-server

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam#912]
### Description
commit: efba3c2bf0c887 changes the structure of the data base. As a result, queries that were valid before are not no more. More specifically, queries to `titles` now return an error.  I think consequential  changes like this should be placed in a different branch until they are tested so that they don't leak into melpa.

#### Steps to Reproduce
1. update org-roam
2. run org-roam-show-graph

#### Expected Results
Graph.

#### Actual Results
get error emacsql no titles.

### Environment

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/efba3c2bf0c887f9aa5c4984ffc0cb5fb0b4bd31

**Comment by zaeph** [comment]
Have you rebuilt your database?  `C-u M-x org-roam-db-build-cache RET` if you haven't.  Normally, it should have prompted you to do so the next time you enabled Org-roam.

**Comment by zaeph** [comment]
I can reproduce the problems with `org-roam-graph`.  It's not as trivial as `s/titles/title` either.

**Comment by natask** [comment]
yes, I have rebuilt my database. It prompted me when I restarted emacs after updating because I call org-roam from my configs.

**Comment by natask** [comment]
@zeaphI messed around with it a bit. it seems titles:file has been mapped to files:file and titles query to title. I updated org-roam-server with these. It got rid of the errors but the browser page wasn't showing any nodes. there maybe some other consequences I wasn't able to pick up from parsing the commit.  Reverted the commit 21bc220ed328b34fe9a664da because there is also another issue #909 that was caused by an earlier commit.
``` elisp
                                          (org-roam 
                                           :location (recipe :fetcher github
                                                             :repo "org-roam/org-roam"
                                                             :commit "21bc220ed328b34fe9a664da3d1962b7a2229ef31") ;https://github.com/org-roam/org-roam/commit/21bc220ed328b34fe9a664da3d1962b7a2229ef3 ;[2020-07-05 Sun 02:21:00] 
                                           )
```
