### ISSUE TITLE
EmacSQL unhandled condition

### ISSUE THREAD

**Issue by jmburgos** [org-roam/org-roam#918]
### Description
When launching Emacs I get the following error:

Error (use-package): org/:config: EmacSQL had an unhandled condition: "near line 9: no such column: titles".  

I assume that this is related to org-roam, as it is the only package that is listed as required by emacsql.

#### Steps to Reproduce
Just launch emacs.  

#### Backtrace
After launching Emacs with the debugger I get the following:

[DATA EXPUNGED BY MAINTAINER]

### Environment
- Emacs: GNU Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.11)
 of 2019-12-10
- Framework: N/A
- Org: Org mode version 9.3.7 (9.3.7-12-g5d6868-elpaplus @ /home/julian/.emacs.d/elpa/org-plus-contrib-20200706/)
- Org-roam: 1.2.0

**Comment by zaeph** [comment]
We've recently updated the schemata that we use for the database.  You will need to update Org-roam and rebuild your database, which should be done automatically upon update.

Could you do this and confirm that it has resolved your issue?

(Also, I've expunged your Backtrace because it contained personal information.)

**Comment by jmburgos** [comment]
Nevermind... it is actually related to org-roam-server.  I will report there.

**Comment by zaeph** [comment]
I've already opened an issue for it in org-roam/org-roam-server/issues/53.  You can mention it there.

Thanks!

**Comment by jmburgos** [comment]
Thank you Zaeph!  Everything works now like a charm.  Thanks for keeping an eye to the information in the backtrace. I should have read it more carefully.

**Comment by zaeph** [comment]
> Thanks for keeping an eye to the information in the backtrace. I should have read it more carefully.

A good rule of thumb is that, the longer it is, the more likely it is to leak personal information.  Don't sweat it!

**Comment by shrysr** [comment]
I've just started getting setup with org-roam today , and am unable to start org-roam due to this error. Here is the trace : https://gist.github.com/shrysr/324ce6218ec90ebd3f02635630b9f01b

Emacs : 28.0.5 
org-roam : 1.2 
org-roam-db : 7

**Comment by jethrokuan** [comment]
Looks like your db has a wrong schema. Try rebuilding it from scratch with `C-u M-x org-roam-db-build-cache`
