### ISSUE TITLE
org-roam does not work correctly if `org-roam-directory` points to a link

### ISSUE THREAD

**Issue by darcamo** [org-roam/org-roam#919]
### Description

My `org-roam-directory` is pointing to `/home/myuser/org/org-roam-notes`, which is a symolic link to `/mnt/data/myuser/Dropbox/org/org-roam-notes`. Regular emacs functions such as `find-file` respect the value of a variable `find-file-visit-truename`, which in my case (default value) is set to `nil`, and will treat the link as a regular file (or folder). For instance, if I use `find-file` to open the `/home/myuser/org/org-roam-notes` folder then I will be in that folder, but if the `find-file-visit-truename` variable is non-nil then emacs would follow the link and dired would be in the `/mnt/data/myuser/Dropbox/org/org-roam-notes` folder instead.

The problem is that org-roam seems to always follow the symbolic links. That is, functions such as `org-roam-insert` or `org-roam-find-file` use the true name and location of the file instead of using the link name and its location. This causes several problems, including the backlinks not working. Also, when using `org-roam-insert` to create a link to some `note2.org` file in a `note1.org` file, the `note2.org` file is not recognized as being in my `org-roam-directory` and the created link is something such  as `file:../../../../../../home/myuser/org/org-roam-notes/note2.org` instead of just `file:note1.org`.

#### Steps to Reproduce

1. Set `org-roam-directory` to point to a link of a folder with some roam notes
2. Use `org-roam-find-file` to open a note
3. Use (for instance) `find-file` to find out the directory of the currently open file, or use `org-roam-insert` to link to a different note and check the link created by org-roam

#### Backtrace

Not available

#### Expected Results

org-roam should behave as if my `org-roam-directory` was not pointing to a link

#### Actual Results

Not available

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.17.3)
 of 2020-07-02
- Framework: Spacemacs
- Org: Org mode version 9.3.7 (9.3.7-12-g5d6868-elpaplus @ /home/darlan/.emacs.d/elpa/28.0/develop/org-plus-contrib-20200706/)
- Org-roam: 1.2.0

**Comment by natask** [comment]
I also symlink my org directory. I would prefer it org-roam didn't follow symlinks, as you have said. However I haven't had any issues with org-roam, whether it is *org-roam-insert-link* or anything else except a minor annoyance that symlinks are not respected of course. The reason being that I set the variable *org-link-file-path-type* to *adaptive*.
  ``` elisp 
  (setq org-link-file-path-type 'adaptive)
  ```

  these are the valid selections, taken from *easy-customization*. I prefer 'adaptive because it give the best of both worlds.
  ``` quote
   relative  Relative to the current directory, i.e. the directory of the file
             into which the link is being inserted.
   absolute  Absolute path, if possible with ~ for home directory.
   noabbrev  Absolute path, no abbreviation of home directory.
   adaptive  Use relative path for files in the current directory and sub-
             directories of it.  For other files, use an absolute path.
  ```

**Comment by darcamo** [comment]
I also have ` org-link-file-path-type` set to `'adaptive` and, at least for me, that doesn't seen to be the issue here.

When you use `org-roam-insert` is the inserted link the same as if `org-roam-directory` were not a symlink?

**Comment by natask** [comment]
yes. For example if I have two files, one file1.org and file2.org, if I `org-roam-insert` file2.org in file1.org, I am left with the link, ``[[file:file2.org][file2.org]]`. 
Is this a new occurrence? Was there a time when `org-roam-insert` worked fine?

**Comment by natask** [comment]
I edebugged `org-roam-find-file` and I am convinced this is also how the database is built. I believe the culprit is at `org-roam--list-all-files`. it applies `file-truename` to `org-roam-directory` before running`org-roam--list-files` instead  of running `org-roam--list-files` directly on `org-roam-directory`. 

I am not sure if what the merits are to this design decision.

**Comment by zaeph** [comment]
I don't know much about how symlinks work within Emacs, but I'll investigate when I get a minute.

**Comment by natask** [comment]
`eval-region` the following 
``` elisp
; redefine org-roam--list-all-files
(def org-roam--list-all-files ()
 (org-roam--list-files org-roam-directory)
)

```
then backup your org-roam.db and rebuild.

**Comment by zaeph** [comment]
I'm not sure what the problem is.

I've pointed `org-roam-directory` to a symlink (`/tmp/slipbox`) pointing to my original directory (`~/org/slipbox/`), and whilst `org-roam-find-file` resolves the links to their `~/org/slipbox/`, `org-roam-insert` still inserts links relatively, taking `~/org/slipbox/` as its root.  If you go out of your way to go into `/tmp/slipbox`, open the file yourself (i.e. not without `org-roam-find-file`), creating links with `org-roam-insert` still results in proper relative links.

> I edebugged `org-roam-find-file` and I am convinced this is also how the database is built. I believe the **culprit** is at `org-roam--list-all-files`. it applies `file-truename` to `org-roam-directory` before running`org-roam--list-files` instead of running `org-roam--list-files` directly on `org-roam-directory`. [emphasis added]

The _culprit_ for _which_ problem?  I gathered that you weren't having the issue yourself from your previous posts.

**Comment by natask** [comment]
@zaeph I was mentioning `org-roam-find-file`. It goes for the true file name instead of the symlinked file name.

**Comment by zaeph** [comment]
Ah, I get it.  Yeah, I don't think we need to be resolving to the true file-names.  Let me do some testing to see if it breaks anything.

**Comment by natask** [comment]
@zaeph what I suggested seems to break `org-roam-server`.

**Comment by zaeph** [comment]
It seems to be working fine on my end.

**Comment by zaeph** [comment]
But now, with #928, I'm getting those relative links to the source: `file:../../../../tmp/slip-box/20200408130356-attention.org`, so that seems to indicate a problem with `org-roam-insert`.  I'll investigate.

**Comment by natask** [comment]
> But now, with #928, I'm getting those relative links to the source: file:../../../../tmp/slip-box/20200408130356-attention.org, so that seems to indicate a problem with org-roam-insert. I'll investigate.

same here. backlink buffer is also empty.

**Comment by zaeph** [comment]
I'll hold off on this for the moment because I've got other matters to address.  @natask, feel free to keep investigating if you want to work on this.

**Comment by natask** [comment]
@zaeph `(file-truename path)` is used numerous times within both `org-roam` and `org-roam-server`. I believe the problem stems from this.

**Comment by natask** [comment]
@darcamo I think I have an understanding to the cause of `org-roam-insert` issue you are having. the file you are inserting the link into needs to be opened as a buffer linking to the true location of the org roam file. In your case is `/mnt/data/myuser/Dropbox/org/org-roam-note/FILE_NAME.org`. If you open the buffer through `org-roam-find-file`, the default behavior is to open a buffer to the true location of the org roam file. 
This is an artifact of how `org-roam--format-link` constructs file links.

**Comment by darcamo** [comment]
I see. Sometimes I open a file through a dired buffer in the `/home/myuser/org/org-roam-note/` folder and in that case I will have problems.

Today I'm back at my work machine, where I use the symbolic links. I noticed that there as an update for org-roam (spacemacs). After updating, deleting the database, and restarting Emacs, I noticed that the inserted links are correct now (without all of that `../../../`) even if I open a note from dired. That's good since it means I'll not have bad data in my files now. However, the backlinks are still broken showing the many `../../../`.

Also, since `org-roam-find-file` still uses the true name, does that mean that it's the true name that is inserted in the database?
That will probably cause problems when I go back to my personal machine, where `org-roam-directory` does not point to a link, and dropbox syncs all the files, including the database. 

As you have mentioned, an architecture that is directory agnostic makes a lot of sense (it feels more natural IMHO) and it would perfectly fit my use-case, where `org-roam-directory` is in a dropbox folder that might be in different locations in different machines.

**Comment by darcamo** [comment]
> ... does that mean that it's the true name that is inserted in the database?

I'm not proficient with elisp to help with actual code, but I think I can confirm that this is indeed the case by runing `M-x org-toggle-link-display` in the backlinks buffer. This shows the full link instead of just the description and the links are something such as `[[file:/mnt/data/myuser/Dropbox/org/org-roam-notes/20200713155121-note1.org][note1]]`, which hints that it is the true location which is being inserted in the database.

**Comment by natask** [comment]
@darcamo you are correct. the database tracks true locations. This can be fixed with the code I put up. Sadly, the problem doesn't end there. org-roam internally coverts symlinked files to true paths. Some uses are legitimate, for example to make sure sym-linked and true path file are indeed the same file. 
 
the database and org-roam's internal systems should function relative to the directory itself, using true path only to verify equivalence, and using the variable **org-roam-directory**  when opening or writing a file, so that it doesn't matter whether a directory is located only that the files within it are interlinked. Therefore a file located at **/mnt/org-roam/file.org** or **~/org-roam/file.org** through a symlink will both appear as **file.org** within the data base. Links pointing outside the should almost always be specified by true paths though if we assume  the directory can be moved. There is no guaranty that the file link points to a valid file otherwise.

**Comment by darcamo** [comment]
>  though if we assume the directory can be moved. There is no guaranty that the file link points to a valid file otherwise.

The only reason I'm pointing `org-roam-directory` to a link is such that different machines will have my org-roam notes in the "same directory", even though it is actually located in different places in the different machines. If that is not possible because org-roam actually uses the true location then there is no point in setting `org-roam-directory` to a link. 


If the current implementation is kept, then I would suggest that org-roam should warn the user if `org-roam-directory` points to a link, informing the user that it is the true location of the folder that will be used and things might not work reliably if the true location is changed (for instance with syncing between different computers as in my case). 


In that case, the solution might be to set `org-roam-db-location` to some file outside `org-roam-directory` to have a completely independent database for each machine. Then even if different machines have different true locations for `org-roam-directory` it does not matter since each machine has its own database. I'll try this solution for now.


However, I still think it makes more sense if org-roam does not use true locations. I always open a note from `org-roam-directory` and never from the true location (if they are not the same). Two common use cases are opening a note from a dired buffer, or using deft to find and open a note. Both cases will have problems with the current way org-roam works.


Maybe a better compromise is to respect the value of the `find-file-visit-truename` variable in Emacs. If that variable is `t` then standard emacs functions such as `find-file` will open the true location and it makes sense that org-roam does the same. If it is `nil` then org-roam should not use the true location.

**Comment by natask** [comment]
>If that is not possible because org-roam actually uses the true location then there is no point in setting org-roam-directory to a link.

true.

>  org-roam-db-location to some file outside org-roam-directory

that is a simple and effective hack for your issue. It has its downsides but atleast org roam will work.

> Maybe a better compromise is to respect the value of the find-file-visit-truename variable in Emacs.

This is an end effect thing and makes sense as a default. I think it is better to decouple org-roam from other emacs things to increase avoid unintended leakage from changes outside the org roam namespace. Therefore offering a variable **org-roam-file-visit-truename** that is set to **find-file-visit-truename** by default makes sense. All in all, It is a requirement that there is some way to go from database to file either by having multiple databases, keeping directory relative file paths in database, or keep an extra entry indicating the true path of the directory the database is built against. I am more of a fan of the middle approach for its simplicity, robustness and ability to work in variety of situations in without additional moving parts. I will make no promises but if I have time this week I will look into it.

**Comment by darcamo** [comment]
I tried setting `org-roam-db-location` to a different location in order to have one database on each computer. Unfortunately, that does not solve the problem.

If a note file is open from the `org-roam-directory` when it points to a link (without using `org-roam-find-file`, that is, using `find-file`,  dired, deft, etc), then the backlinks buffer does not work correctly. The title in the backlinks buffer will be something such as `../../../...../<full_path_of_org-roam-directory>/note_name` and no backlinks will be shown.


The final conclusion is that org-roam only works correctly if `org-roam-directory` points to a true location and the problem does not have any relation to wrong values in the database due to syncing between different computers.

The only workaround left in my case is to have different org-roam configurations in each machine to point `org-roam-directory` to the true location in each machine (besides also having different databases for each machine) and delete the symbolic link to avoid opening notes from there by mistake. The notes can be synced and because any links are relative to `org-roam-directory` they should work correctly in each machine.

Unfortunately, this has the drawback that any links to a note file that I insert in other (non org-roam org-mode files) will only work in one machine and not others where `org-roam-directory` has a different value.

**Comment by emacs18** [comment]
I would like to share that I too ran into this problem.  I almost gave up on org-roam, because I kept getting "No backlinks".   My setup is similar to @darcamo where /home/me/elisp is a symlink to another directory.  I've used this setup for many years.  I worked through similar "symlink instead of directory" problem over the years.  I even submitted PR on some projects so that I could continue to use symlinks.  However org-roam is a tough nut to crack.  I gave up
and just got rid of my symlink  just to be able to use org-roam.  Then and only then I stopped getting "No backlinks" error.  For now I'm motivated enough to further test drive org-roam to explore how it can help me.  

I hope that this problem is resolved soon so as not to discourage other new users from giving up on org-roam.
BTW even when I got "No backlinks" error, `org-roam-graph` worked fine in that it created proper diagram of my org files.

**Comment by aviaviavi** [comment]
If it's helpful, I also have a similar setup where my org-roam directory is a symlink. For me, I am (sometimes) able to get backlinks when I create new new org files and make links between them. However, if I restart emacs, those backlinks never seem to show up in the roam buffer ever again, even after regenerating the DB.

**Comment by emacs18** [comment]
I submitted https://github.com/org-roam/org-roam/pull/1099 to add two more `file-truename` calls to fix the problem for me.

**Comment by emacs18** [comment]
My PR was accepted and checked in.  I would be interested to know if this change makes any difference to others.

**Comment by aviaviavi** [comment]
@emacs18 this fixed things for me!!! Thank you! I had been fussing with this for a while and hadn't figured it out.

**Comment by darcamo** [comment]
It seems that these recent changes indeed fixed the problem. I'm closing the issue. Many thanks for the people involved.

**Comment by alanz** [comment]
FYI the overnight update has resulted in my org-roam inserting links with `../../../` in them, and my `org/roam` directory has a symlink for the `org` part.  Running emacs 27 on mac.

**Comment by emacs18** [comment]
I too run into problem if I update org-roam to the latest version from a week old version.
For me `*org-roam*` buffer is just blank.  Nothing shows up.  I use emacs 27 on ubuntu 20.04.
If I go back to version `70539c4` which is about a week old, then all works fine.

**Comment by alanz** [comment]
> from a week old version.

Now that you mention it, I think the last week has been mainly capturing direct text in the daily notes, so the issue may have come about earlier.

**Comment by emacs18** [comment]
For me the root cause is https://github.com/org-roam/org-roam/commit/d170c4ac852bbcb646604f00ec8f723d712d8846
which explicitly declares that symlinks will not be supported.  Hence the author of org-roam seems to consider calling file-truename too much CPU wasted and so not worth supporting users who are stuck with symlinks.  This pretty much means org-roam is not for me then.

**Comment by jethrokuan** [comment]
> Hence the author of org-roam seems to consider calling file-truename too much CPU wasted and so not worth supporting users who are stuck with symlinks. 

That's not true. The only thing that the update should break is symlinks from a file in the Org-roam directory to a file in the Org-roam directory.

**Comment by emacs18** [comment]
Well so you are willing to support users stuck with symlinks?  That is good to know.
I have no symlinks under org-roam-directory.
All my symlinks are above that directory, e.g., /u is symlink to /home in some machines, but /u points to 
some other directories on other machines.  On my laptop which I'm currently using, I believe /u symlink pointing 
to /home is the only symlink involved.  In this setup the change I mentioned before completely breaks `*org-roam*` buffer 
in that it is completely blank.

**Comment by emacs18** [comment]
If I revert d170c4a from the latest code, then all works for me.

**Comment by alanz** [comment]
For the record, I have no strong feelings on this. I set my `org-roam-directory` to the actual one, and carry on.

**Comment by shelper** [comment]
same here with symbolic link issue under windows...
dont know why this issue is closed but wish  some one can fix it...
