### ISSUE TITLE
[Question] How to always open backlinks in full windows

### ISSUE THREAD

**Issue by ivanddm** [org-roam/org-roam#920]
### Brief Abstract

I'm relatively new to Emacs, and I came to it basically because of Org and Org-Roam. It is really great. Thanks for this.

I normally don't like using split windows. When I hit enter or click on a backlink note in the Org-roam buffer most of the times it opens the note in a horizontal split window (a window below), which I end up closing or merging with the top one anyways. Is there a way to guarantee that whenever I open a backlink it opens in a full window. Sometimes this is the case but it seems kind of random to me.

Also, is there a way to keep the org-roam buffer window closed by default and only open it on demand. Normally it opens automatically whenever I open an org-roam note.

Thanks in advance.

**Comment by zaeph** [comment]
We're aware of the unreliable behaviour when opening links in Org-roam.  From an initial survey, this seems to be an Org-mode problem more than an Org-roam problem, but it's something that we're planning to address in Org-roam.

We'll review this in the near future when we address the side-buffer revamp.

**Comment by ivanddm** [comment]
Great, thanks for letting me know. Looking forward to that side-buffer revamp!

**Comment by santiyounger** [comment]
hey @ivanddm I've having the exact same situation, the guys where kind enough in my question I asked in [discourse about opening full windows](https://org-roam.discourse.group/t/opening-internal-links-in-the-same-window-frame/542) to direct me to a  solution for this in a [stackoverflow answer](https://stackoverflow.com/questions/17590784/how-to-let-org-mode-open-a-link-like-file-file-org-in-current-window-inste) 

Apparently this is more of an org-mode problem than org-roam.

**This might be a bit of a workaround,** but the [answer in that forum](https://stackoverflow.com/a/49855491) worked perfectly for me. 
In my case I use spacemacs so I re-mapped the key to something else (SPC o). but for vanilla emacs that script works perfectly as it is.

Hope it helps!

**Comment by ivanddm** [comment]
Thanks a lot for sharing a solution @santiyounger. I will try that out for sure!

**Comment by myshevchuk** [comment]
@santiyounger we are the same guys, he-he. It is not "that" forum. It is a communication platform for `org-roam` and its satellites `company-org-roam`, `org-roam-server` and `org-roam-bibtex`. Check also [the Slack channel](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg). You did well asking there before submitting an issue to GitHub, huge thumbs up!

**Comment by ivanddm** [comment]
That's great @myshevchuk. I just have joined the slack channel. Next time will ask there first 👍

**Comment by myshevchuk** [comment]
@ivanddm don't get me wrong, your issue is technically a valid Github issue, but it is always a good idea to ask there first. 

@zaeph it would be great if this could be stated explicitly in the top front of README. It should definitely be done for `org-roam-bibtex`.

And yes, sorry for the off-topic. I'm just worried that soon the number of open issues will be overwhelming and unmanageable.

**Comment by santiyounger** [comment]
> @santiyounger we are the same guys, he-he. It is not "that" forum. It is a communication platform for `org-roam` and its satellites `company-org-roam`, `org-roam-server` and `org-roam-bibtex`. Check also [the Slack channel](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg). You did well asking there before submitting an issue to GitHub, huge thumbs up!

Perfect, thanks for letting us know! You are doing an excellent job with everything! Thank you so much for your amazing efforts!
