### ISSUE TITLE
Error in post-command-hook (org-roam-buffer--update-maybe)

### ISSUE THREAD

**Issue by rsuhada** [org-roam/org-roam#921]
I've updated yesterday org-roam to 1.2.0 (including the update of the DB).
Since then I'm getting this error:

    Error in post-command-hook (org-roam-buffer--update-maybe): (wrong-type-argument listp "Emacs")

Happens for all roam buffers when org-roam is activated. The Backlinks window is empty.
Everything worked fine before the update.

Any idea what is going on?
Thank you!

**Comment by zaeph** [comment]
This looks similar to problem I've resolved yesterday in #916.
Could you make sure that you're running Org-roam on the latest commit?  It should have been propagated to MELPA already.

**Comment by rsuhada** [comment]
This is excellent job zaeph :)

20200710.2118 fixed it!
Thank you for all the amazing work!
