### ISSUE TITLE
Can't create new org-roam file directly when desired title is contained in existing files in completions list

### ISSUE THREAD

**Issue by mparq** [org-roam/org-roam#923]
### Description

I tried to search for this issue but couldn't find anything related.

Not sure if this is a feature request or a bug (or if there's a better approach to this than the workaround I found).

When calling `org-roam-insert` and `org-roam-find-file` to create new org-roam files, usually, I can just type in the title of the new file I want to create but sometimes if the desired title is contained within other existing titles, I'm unable to create a new file without a workaround since the auto-complete .

My `org-roam-completion-system` is `'ivy`

#### Steps to Reproduce
Example:

I have existing notes with title "Personal learning goals", "continual learning". Now I realize I want to create a more general note "learning".

1. I call org-roam-find-file, I get below dialog with completions in mini buffer

> File: learning
> ---
> Personal **learning** goals
> continual **learning**

There's no easy way that I found that lets me create a new note for "learning" here since the first entry is automatically pre-selected. My workaround is to create a title which doesn't match an existing note e.g. "learningggg", create that note and then modify the title of the newly-created note to what I want "learning".

#### Backtrace
N/A

#### Expected Results

Would be nicer if there were some option to allow sending just "learning" from this minibuffer or even if the completions list could be dynamically augmented with something like "learning (create new note)" at the bottom of the completions list, then that would be good too.

#### Actual Results

There's no easy way that I found that lets me create a new note for "learning" here since the first entry is automatically pre-selected. My workaround is to create a title which doesn't match an existing note e.g. "learningggg", create that note and then modify the title of the newly-created note to what I want "learning".

### Environment

- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101))
 of 2020-06-11
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /Users/mparq/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.1.1

**Comment by zaeph** [comment]
In `ivy`, you need to use `C-M-j` (i.e. `Ctrl+Alt+j`) to use the current input rather than select the closest match.

**Comment by mparq** [comment]
Ahh, great. Thanks for the quick response!
