### ISSUE TITLE
Org links of the type type:foo breaks the parser

### ISSUE THREAD

**Issue by iris-garcia** [org-roam/org-roam#926]
### Description
As the title says, links `type:foo` break the parsing.

Sorry for not giving more details, it was already confirmed by @zaeph.

**Comment by zaeph** [comment]
Just to be clear, we're talking about bracket-less links like `file:foo.org` and `id:bar`.  The lack of description is causing our extraction functions to conk out.

**Comment by zaeph** [comment]
It should be fixed now.
