### ISSUE TITLE
Add support for adding hooks to org-roam-insert

### ISSUE THREAD

**Issue by fleimgruber** [org-roam/org-roam#929]
### Brief Abstract

After inserting a new note, the user might want to run custom functions which should be defined and called via the hooks mechanism.

### Long Description

This came up in https://org-roam.discourse.group/t/save-note-when-new-one-was-inserted/514/2 where it was proposed to use hooks instead of the advice system to run custom functions after org-roam-insert, e.g. run `(save-buffer)` on the currently edited note.

### Please check the following:

- [x] No similar feature requests

**Comment by zaeph** [comment]
Thanks for filing it.

Adding a couple of hooks à la `org-capture` would be trivial, and I'll do that when I get around to implementing the two-step completion for inserting file+headline links.

**Comment by fleimgruber** [comment]
If you want to, feel free to ping me when you implemented the mentioned completion and I can try adding the hooks myself, seeing that you put the "good first issue" there.

**Comment by zaeph** [comment]
Well, it turns out that I've already implemented it in #482 (89b941a2077d8d84e2c88337cfcc907cb444af95).

So, you could do something like this:
```el
(add-hook 'org-roam-capture-after-find-file-hook #'save-buffer)
```

It'll also be used by `org-roam-find-file` when a it creates a file, which technically makes it overapply.  It might be wise to split them in the future, but for now, it'll work.

**Comment by zaeph** [comment]
I'm closing this in favour of #930.

Thanks!

**Comment by fleimgruber** [comment]
Splitting feels like the right way to go and is the better place for this to be tracked. Glad to be part of the process and again thanks for the fast handling.
