### ISSUE TITLE
History of a file - one step closer to a collaborative second-brain

### ISSUE THREAD

**Issue by jcguu95** [org-roam/org-roam#934]
### Brief Abstract
+ Make it easy to see the history of **a** file.
+ As a result, this brings org-roam one step closer to being a collaborative second-brain.

### Long Description
Motivated by nLab (a wiki for higher math), I reckon it would be useful to allow user to see the history of a file. Here is an [example (content not important)](https://ncatlab.org/nlab/show/equivariantization) and its [history](https://ncatlab.org/nlab/history/equivariantization).

+ This brings org-roam one step closer to being a collaborative second-brain which abides the UNIX philosophy!
+ Easier for users to view their growth of thoughts!

### Proposed Implementation (if any)
Not familiar with org-roam, but I guess it won't be hard to do if you are (plus a bit of knowledge with git). Some primitive ideas:

+ Use git to [view the change history](https://kgrz.io/use-git-log-follow-for-file-history.html) of a file.
+ `(org-roam-history-of-file)` brings up a buffer similar to the [example above](https://ncatlab.org/nlab/history/equivariantization), and patch the diff on live when the user choose to go to certain history.
+ Deeper integration with git can replicate more features shown in the example above: for example, you can see who made what changes easily. **This brings `org-roam` one step closer to collaborative second-brain**.

### Please check the following:

- [X] No similar feature requests

Tried searching "history of files", "file history". [This issue](https://github.com/org-roam/org-roam/issues/531) seems similar but it addresses to "steps" in org-directory not the change history of a file.

**Comment by jethrokuan** [comment]
This looks like it would be amply covered by something like [git-timemachine](https://github.com/emacsmirror/git-timemachine). Could probably add a section on it in the Ecosystem docs.

**Comment by jcguu95** [comment]
Wow, will try it out!

**Comment by jethrokuan** [comment]
Added into the docs in #949
