### ISSUE TITLE
path error when use the same org-roam database cross-platform (same PC)

### ISSUE THREAD

**Issue by BevalZ** [org-roam/org-roam#935]
#### Steps to Reproduce

1. In windows 10 build a org-roam database and bind the path via (setq org-roam-directory “e:/Notes/org-roam”) in init.el

2. create an org file named "First-note.org"

3. In Linux ( Manjaro) mount the e:\ to /run/media/doc/ and set the org-roam path via (setq org-roam-directory “/run/media/doc/Notes/org-roam”) in init.el

3. Run `org-roam-find-file

#### Expected Results

get the "First-note.org" file

#### Actual Results

file(0): cannot find any files
the path in the linux tells e:/Notes/org-roam (which is the path set for windows)

### Environment

Hardware:Inter(R) Core(TM) i7-8550U CPU with 16 GB installed RAM

Windows:  Windows 10 Education 2004 , OS build 19041.329, 64-bit operating system

Linux: Manjaro (Latest version with latest kernel ) 64-bit

Emacs Version: both pure(not doom or spacemacs) and latest version with latest version of packages

### Additional

Then I set the path ( in linux)  to another one, and emacs worked appropriately.

Guys tell me that the database record the absolute path, which causes this issue.

I am a medical researcher...I have to switch between windows and linux frequently for programming and using commercial analyse software. Really need you help fix this. 

Thanks.

**Comment by BevalZ** [comment]
QwQ

Sorry to find that we can use  org-roam-db-location ,but still it's hard to use.

**Comment by BevalZ** [comment]
QwQ

Sorry to find that we can use org-roam-db-location ,but still it's hard to use, especially in windows. I'm trying to change the database location in linux and find out if it can work nicely.

**Comment by chen-chao** [comment]
@BevalZ How do you solve the problem?

**Comment by jethrokuan** [comment]
Just use separate databases for different environments: don't version control the db/use any form of syncing, you can set `org-roam-db-location` if you need to alter where the database is located for this.

**Comment by chen-chao** [comment]
> 
> 
> Just use separate databases for different environments: don't version control the db/use any form of syncing, you can set `org-roam-db-location` if you need to alter where the database is located for this.

Just curious. Why does org-roam use the absolute path since it already has `org-roam-directory`?
