### ISSUE TITLE
Document org-roam + org-journal for Spacemacs users

### ISSUE THREAD

**Issue by fleimgruber** [org-roam/org-roam#936]
### Brief Abstract

As a Spacemacs user, after reading the respective [docs](https://org-roam.readthedocs.io/en/master/installation/#spacemacs) I might be looking for hints on how to use org-journal with org-roam.

### Long Description

An example of how this might look like is [org-roam-bibtex](https://github.com/org-roam/org-roam-bibtex#spacemacs). The org-roam [docs](https://org-roam.readthedocs.io/en/master/ecosystem/#org-journal) give a plain use-package example for org-journal, but not for Spacemacs.

### Proposed Implementation (if any)

I tried to use org-journal in a private Spacemacs layer as described [here](https://org-roam.readthedocs.io/en/master/installation/#spacemacs), i.e. (org-roam packages.el):

``` emacs-lisp
(defconst org-roam-packages
  '(org-roam org-roam-bibtex org-journal))

...

(defun org-roam/init-org-journal ()
  (use-package org-journal
    :after org-roam
    :init
    (progn
      (spacemacs/set-leader-keys
        "arj" 'org-journal-new-entry))
    :custom
    (org-journal-date-prefix "#+TITLE: ")
    (org-journal-file-format "%Y-%m-%d.org")
    (org-journal-dir (expand-file-name "/path/to/org-roam-files/"))
    (org-journal-date-format "%A, %d %B %Y")))
```

For which I get the Spacemacs startup message: "More than one init function found for package org-journal. Previous owner was org, replacing it with layer org-roam." and org-journal is not usable.

What would be the best way to solve this? Should the org-journal config go into `init-org-roam` since that depends on org? Or should a `post-init-...` be used as described [here](https://github.com/syl20bnr/spacemacs/issues/4269)?

I would then add a PR documenting the recommended configuration.

### Please check the following:

- [x] No similar feature requests

**Comment by dit7ya** [comment]
org-journal doesn't need to be loaded in a private layer. 

See here for official documentation from Spacemacs

https://develop.spacemacs.org/layers/%2Bemacs/org/README.html#org-journal-support

Also, though it complements org-roam well, org-journal is separate package with a different development team.

**Comment by fleimgruber** [comment]
Thanks for your comments.

> org-journal doesn't need to be loaded in a private layer.

`(spacemacs/set-leader-keys "arj" 'org-journal-new-entry)` fails if org-journal was not loaded. So the idea was to load org-journal here, irrespective of whether the org layer loaded org-journal - I thought Spacemacs could help out here.

> Also, though it complements org-roam well, org-journal is separate package with a different development team.

Thanks for clarification, but I was aware of that and it is mentioned in the docs.

> See here for official documentation from Spacemacs

`org-enable-org-journal-support t` did it.

This whole issue was just an idea to mention Spacemacs related setup since Spacemacs has a considerable user base and is already mentioned in other places in the docs. The solution could be as simple as linking to the [Spacemacs](https://develop.spacemacs.org/layers/%2Bemacs/org/README.html#org-journal-support) org-journal docs from the Extension docs [here](https://org-roam.readthedocs.io/en/master/ecosystem/#org-journal). But thinking of it a bit more, what about e.g. Doom Emacs? In the end users should know how to load org-journal in their setup, so let's just drop this.
