### ISSUE TITLE
org-roam-open(-immediate)

### ISSUE THREAD

**Issue by jcguu95** [org-roam/org-roam#937]
### Brief Abstract

A cousin of `*-find` and `*-insert` that completes the workflow.

### Long Description

If at a word, transform it into an org-roam link, and create note automatically.
If at a link, redirect the user into that link.

### Please check the following:

- [ X ] No similar feature requests

**Comment by zaeph** [comment]
There is already `org-roam-insert-immediate` that allows you to link to a note, and create it if it doesn't exist without dropping you in an `org-capture` window.

> If at a word, transform it into an org-roam link, and create note automatically.

You can do it by selecting the text first, and then running `org-roam-insert-immediate`.  Doing it with just the word would not provide satisfying results with multi-words titles, although we could probably find it as a decent default when no text is selected in your implementation.

> If at a link, redirect the user into that link.

I think it's wiser to keep the behaviour between inserting and opening different.

**Comment by jcguu95** [comment]
That is weird.. I tested again running `org-roam-insert-immediate` on selected word/words/Word.. but it does not transform that into a link. I'm using doom-emacs with evil on.. maybe that's why?

**Comment by zaeph** [comment]
It's a two-step process: when you select text, run `org-roam-insert-immediate`, the completion at the bottom will be pre-filled with the selected text.  You can then edit the text, if you need to, validate with RET, and the file will be created in the background.

**Comment by jcguu95** [comment]
I see.. when I select the words by "selecting the whole" line, the word does go into the prompt for me to adjust. But when I select the words by "selecting multiple characters", it doesn't work for me.
