### ISSUE TITLE
Rename a file using the #+TITLE property

### ISSUE THREAD

**Issue by jimmerricks** [org-roam/org-roam#939]
### Brief Abstract

It would be useful to have a function that renames a file using the `#+TITLE:` property.

### Long Description

I find myself constantly returning to my notes, extending them, adding references, refiling paragraphs to new notes and otherwise making them more concise. Sometimes this involves changing the title of the note. Whenever I do this, I also change the filename with `rename-file` or `doom/move-this-file` so that I can more easily identify the file in a file browser or on Android. This can be a bit of a pain.

What I would like to be able to do is run a function that gets the `#+TITLE` property from the file header, passes it to `org-roam--title-to-slug`, and then renames the file and updates all of the backlinks. Ideally, this would be run on the file in the currently open buffer, but I think having the option to pass the function a file path also makes sense.

### Proposed Implementation (if any)

I had a shot at putting this together but it is beyond me. What I tried to do was: fetch the title with `+org-get-global-property`, convert this to a slug with `org-roam--title-to-slug`, use this to create a 'new-path' variable, and then, use a modified version of the `doom/move-this-file` code to rename the file (which in turn calls `rename-file` and so updates the backlinks).

### Please check the following:

- [X] No similar feature requests

**Comment by zaeph** [comment]
Hi there.

I've also wanted to implement this for a while, but I haven't had the time to do so.  It shouldn't be too complicated to implement, so I'll get to it in the near-ish future.

**Comment by sunnyhasija** [comment]
I would also like to state my interest in such an enhacement.

**Comment by oblitzitate** [comment]
It would be very helpful if it renamed the Link Descriptions that refer to it also.

**Comment by jimmerricks** [comment]
I don't always link to my notes using their title so renaming wouldn't always be ideal for me.

Maybe the way to implement this would be to rename the Link Description only if it matched the old title. Given that the title has been changed, the way to implement this might be to convert the Description to a slug, compare the slug to the old filename and if they are the same only then update the Description.

**Comment by zaeph** [comment]
We'll find a solution that works for everyone.  The goal is not to make this the default behaviour, but to provide the facility that would make it possible for those who want it, so don't fret it.

**Comment by oatmealm** [comment]
I'd like to see that implemented as well. Since I have my roam notes on NextCloud, it'd be nice to be able to identify them from file names. 

* I guess also removing the timestamp would help, but that's another story... I guess it can be done by modifying the default capture template?

**Comment by rodelrod** [comment]
@oatmealm 

> I guess also removing the timestamp would help, but that's another story... I guess it can be done by modifying the default capture template?

Yes it can. For example:
```
  (setq org-roam-capture-templates
        '(("t" "topic" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "${slug}"
           :head "#+title: ${title}\n"
           :unnarrowed t)))
```
