### ISSUE TITLE
Not using "first heading" for org-roam-insert 

### ISSUE THREAD

**Issue by christabella** [org-roam/org-roam#941]
### Brief Abstract
not exactly an error but when I placed my org-journal-dir inside the org-roam-directory, calling org-roam-insert  resulted in a weird behaviour.

![image](https://user-images.githubusercontent.com/2038751/87585901-68bab400-c6e8-11ea-85c4-363ef0fa7077.png)

### Long Description
This is because org-roam-insert uses, in progressive order: #+title, first heading, file-name.

Nevertheless, now that I understand how it works it is a simple fix for my end (including an appropriate title) so I do not require any further action.

But I suppose this could be a problem for "headline links"

### Proposed Implementation (if any)
-
### Please check the following:

- [ ] No similar feature requests

**Comment by jethrokuan** [comment]
> This is because org-roam-insert uses, in progressive order: #+title, first heading, file-name.

Not exactly true. The default value of `org-roam-title-sources` is 

```
'((title headline) alias)
```

which has the following behaviour:

```
1. Return the 'title + 'alias, if the title of current buffer is non-empty;
2. Or return 'headline + 'alias otherwise, if non-empty;
3. Or return filename
```

The alternative fix is to remove the headline extraction behaviour, if that's not what you want:

```
(setq org-roam-title-sources '(title alias))
```

"Headline links" don't show up in `org-roam-insert` yet.

**Comment by zaeph** [comment]
Oh yeah, I'd forgotten we'd touched this recently.  Thanks for clarifying!
If there's an user-facing variable to be modified, I don't think we need to change the default for now.  Let's revisit this when we get to the doc+tutorial, based on which paradigm we want to embrace with it.
