### ISSUE TITLE
Initiating `org-roam-mode` should check for state of `org-roam-directory`

### ISSUE THREAD

**Issue by aaronjensen** [org-roam/org-roam#942]
### Description

I get an error when finalizing or canceling an org-capture

```
Debugger entered--Lisp error: (cl-no-applicable-method emacsql nil [:begin])
  signal(cl-no-applicable-method (emacsql nil [:begin]))
  cl-no-applicable-method(#s(cl--generic :name emacsql :dispatches ((1 #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fcc7fa7fb5b>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fcc7fa7fb4b>))) (0 #s(cl--generic-generalizer :name eieio--generic-generalizer :priority 50 :tagcode-function cl--generic-struct-tag :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x158d4c40d719>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fcc7fa7fb5b>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fcc7fa7fb4b>)))) :method-table (#s(cl--generic-method :specializers (emacsql-connection t) :qualifiers nil :uses-cnm nil :function #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x158d4c592dd1>))) :options nil) nil [:begin])
  apply(cl-no-applicable-method #s(cl--generic :name emacsql :dispatches ((1 #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fcc7fa7fb5b>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fcc7fa7fb4b>))) (0 #s(cl--generic-generalizer :name eieio--generic-generalizer :priority 50 :tagcode-function cl--generic-struct-tag :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x158d4c40d719>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fcc7fa7fb5b>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fcc7fa7fb4b>)))) :method-table (#s(cl--generic-method :specializers (emacsql-connection t) :qualifiers nil :uses-cnm nil :function #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x158d4c592dd1>))) :options nil) (nil [:begin]))
  #f(compiled-function (&rest args) #<bytecode 0x158d4bb5b0bd>)(nil [:begin])
  apply(#f(compiled-function (&rest args) #<bytecode 0x158d4bb5b0bd>) nil [:begin])
  emacsql(nil [:begin])
  org-roam-db--update-file()
  run-hooks(after-save-hook)
  basic-save-buffer(nil)
  save-buffer()
  org-capture-finalize()
  org-capture-kill()
```

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.0.91 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
 of 2020-07-05
- Framework: N/A
- Org: Org mode version 9.3.7 (release_9.3.7-686-gddfc46 @ /home/aaronjensen/.emacs.d/straight/build/org/)
- Org-roam: 1.2.0

**Comment by zaeph** [comment]
I can't reproduce it on my end.  Is everything working besides this?

**Comment by aaronjensen** [comment]
afaict, a manual delete and rebuild of my db fixed this, though I thought I had tried that before. In any case, I can't reproduce anymore either. I'll reopen if it comes back.

**Comment by aaronjensen** [comment]
And it's back, the first time I attempt to `C-c C-k` an org-capture, I get:

```
cl-no-applicable-method: No applicable method: emacsql, nil, [:rollback]
```

I wonder if this is a byte compilation problem? my config and all packages are byte compiled.

afaict d77f897400b5e668e613fba269eb5ab92a7ed492 introduces 

```
EmacSQL had an unhandled condition: "near line 739: NOT NULL constraint failed: links.to"
```

during `org-roam-db-build-cache`

This was fixed in 7a4b15fd368bc8ac55bfe96392f5a300f71f009c, but this problem remained. So prior to 
d77f897400b5e668e613fba269eb5ab92a7ed492, I didn't have this problem.

**Comment by zaeph** [comment]
> I wonder if this is a byte compilation problem?

You could ascertain that hypothesis by reinstalling Org-roam via `package.el`, or whichever package-manager your distribution uses.

**Comment by aaronjensen** [comment]
Oh, I've done that. I meant an actual byte compilation bug. I've encountered that before. It's just surprising to see an exception suddenly surface in emacsql since it hasn't been updated in months.

**Comment by aaronjensen** [comment]
Okay, I've discovered the problem. If I set `org-roam-directory` after `(org-roam-mode)`, then `org-roam-db--get-connection` will always return `nil`, which `emacsql` cannot handle. I've reorganized my config to invoke org-roam after I set org-roam-directory and the problem went away. 

Up to you if you consider this a bug, but it should probably at least carry a heavy warning and more obvious error.

**Comment by zaeph** [comment]
I guess we could throw a warning if `org-roam-mode` is run with `org-roam-directory` as `nil`.  I'll address this in the doc.

**Comment by aaronjensen** [comment]
I think nil is fine, since it's defaulted and some folks may want to use the default. The problem is if you change it, things break.

**Comment by zaeph** [comment]
We could store the value of `org-roam-directory` in the db, and check whether the current state value of `org-roam-directory` is the same, and throw an error if it isn't.

**Comment by jethrokuan** [comment]
I don't see this as a bug. `org-roam-directory` defaults to a safe value. We should emphasise that `org-roam-directory` needs to be before any of the db operations, including `org-roam-mode` which calls it. In our docs, we prompt users to add `org-roam-mode` to the `after-init-hook`, so this is fine, but if users want to deviate from the recommendation, then they need to know this.

> We could store the value of org-roam-directory in the db, and check whether the current state value of org-roam-directory is the same, and throw an error if it isn't.

This doesn't help in the case where `org-roam-directory` has never been built correctly. Additional complexity for little benefit.

**Comment by zaeph** [comment]
> This doesn't help in the case where `org-roam-directory` has never been built correctly. Additional complexity for little benefit.

I agree.  Let's just address this in the doc.

**Comment by aaronjensen** [comment]
FWIW, I did call `org-roam-mode` in after-init. I just also set `org-roam-directory` in after-init (because it exists in a private portion of my config that I eval after my primary, less private config). This cost me about an hour of my time because I had no idea what the error message was telling me. There's a function, `org-roam-db--get-connection` which should have returned a connection, but did not because it looks up by org-roam-directory. Perhaps that could error if it doesn't find a connection instead? 

My use case is likely relatively unique, so I'll understand not making concessions, but this was a breaking change for me that cost time because of a hard to understand error message (which was probably emacsql's fault) and better documentation would not have helped me at all since I followed the documentation long ago. Maybe it'll help future users, however.

**Comment by jethrokuan** [comment]
The behaviour won't error now, it will establish a new connection based on your updated `org-roam-directory`, and update that database. The main issue with this is that then you wouldn't have caught your error earlier: the initial `org-roam-mode` would build a presumably empty database based on the old, default value of `org-roam-directory`.

I don't think there's much that can be done here.

**Comment by aaronjensen** [comment]
Thanks, that works for me. Much appreciated.
