### ISSUE TITLE
Backlinks buffer has literal links, not descriptive

### ISSUE THREAD

**Issue by hraban** [org-roam/org-roam#944]
### Description

Links in my `*org-roam*` buffer show up as `[[file:a.org][A for Apple]]`, instead of as [`A for Apple`](#)
#### Expected Results

The link in the right hand window (`*org-roam*` buffer) to be a descriptive link

#### Actual Results

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/137852/87699725-31eaa980-c78d-11ea-9f58-afd9259828e0.png">

Clicking `Menubar -> Org -> Hyperlinks -> Descriptive links` has no effect in that buffer, but it does work fine in the regular file buffer (`b.org` above)

### Environment

```
Copy info below this line into issue:
- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
 of 2019-09-02
- Framework: none
- Org: Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Users/hrabanluyat/.emacs.d/elpa/org-9.3.6/)
- Org-roam: 1.2.0
```

**Comment by jethrokuan** [comment]
> - Org: Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Users/hrabanluyat/.emacs.d/elpa/org-9.3.6/)

Something is wrong with your Org loading. You'll want the later org version (9.3.6). Org-roam needs at least 9.2.

**Comment by hraban** [comment]
👌 bril thanks.

smart move putting that command there; very effective trouble shooting.

**Comment by mehw** [comment]
Hi @hraban, may I ask how did you solve the problem?

> Org: Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Users/hrabanluyat/.emacs.d/elpa/org-9.3.6/)

Below you find how I dealt with the issue...

# Details

_In the hope that this could be of any help to anyone..._

I had a similar issue as https://github.com/org-roam/org-roam/issues/944#issue-658373846.

After installing `org-9.3.6` from https://elpa.gnu.org/packages/ with `package.el` **the Org mode version reported was still the built-in, and the `*org-roam*` buffer displayed literal links**...
```
M-x org-version
Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.3/lisp/org/)
```

Same problem as above after installing `org-20200720` from https://orgmode.org/elpa/ :(

## Solution

_I just didn't read enough..._

Following the guidelines at https://orgmode.org/elpa.html solved my problem.

Apparently, **you need to initialize packages before Emacs read the rest of the `.emacs` init file**. Just put `package-initialize` at the beginning of `.emacs` (I also have customized locations for `package-user-dir` and `package-gnupghome-dir`, respectively `~/.emacs.d/package/elpa` and `~/.emacs.d/package/gnupg`):
```
;; -*- emacs-lisp -*-
(require 'package)
(setq package-user-dir (concat user-emacs-directory "package/elpa"))
(setq package-gnupghome-dir (concat user-emacs-directory "package/gnupg"))
(add-to-list 'package-archives
             '("gnu" . "https://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives
             '("org" . "https://orgmode.org/elpa/") t)
(package-initialize)
```

**The Org mode version installed via `package.el` now is able to override the built-in version**:
```
M-x org-version
Org mode version 9.3.7 (9.3.7-14-gb2b587-elpa @ /root/.emacs.d/package/elpa/org-20200720/)
```

**Comment by hraban** [comment]
hi @mehw , that's exactly right. I use `org-babel-load-file` to load a bigger init.org file which has all real emacs init code, and had also moved `(package-initialize)` in there. But, of course, by that time org-mode is already initialized :) so I moved that back to the stub init.el file. 👍

**Comment by mehw** [comment]
Thanks for the prompt reply @hraban!

Cheers!
