### ISSUE TITLE
When using description lists, only description is shown in backlink

### ISSUE THREAD

**Issue by rasendubi** [org-roam/org-roam#95]
I got inspiration from your demo gifs and used the following:
```org
#+TITLE: Programming Language Pragmatics

- tags :: [[book]] [[Programming Language]]
```

However, on the book page, backlinks show only:
```
** [[Programming Language Pragmatics]]
[[book]] [[Programming Language]]
```
i.e. `tags ::` is missing.

I believe this has something to do with the `org-element-at-point` returning description when invoked on the book link (not the full list item).

**Comment by jethrokuan** [comment]
Yeah, that's how it is right now. We can be a lot more sophisticated with how we pull the preview content, depending on the kind of element it is:

https://github.com/jethrokuan/org-roam/blob/9ae03532da068b74bee3a7cfaf87b19af2f0729c/org-roam-utils.el#L79

**Comment by rasendubi** [comment]
Are there other known cases where pulling context could be improved?

**Comment by jethrokuan** [comment]
The only case I want to avoid is pulling out Org headings (those `*`s), these mess with the org-roam buffer folding and so on.
