### ISSUE TITLE
Editing the name of a directory in Dired's edit-mode does not update the links

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#955]
It shouldn't be too hard to fix.

**Comment by zaeph** [comment]
Temporary solution is to not use Dired's edit-mode: create new-dir, move all files in old-dir to new-dir, and delete old-dir.

**Comment by rodelrod** [comment]
I have the same problem using `dired-do-rename` to move directories. Which means I currently can't use `dired` for this. The rename does work with `doom/move-this-file`
