### ISSUE TITLE
org-roam-new-file-directory not working (deprecated?)

### ISSUE THREAD

**Issue by jlevers** [org-roam/org-roam#962]
### Description

When I first installed `org-roam`, I set it up so that my `org-roam` notes are in a subdirectory of my overall `~/org` folder, but I wanted to have `org-roam` recognize all the files in `~/org`. With that in mind, I set `org-roam-directory` to `~/org` and `org-roam-new-file-directory` to `~/org/notes`.

I recently updated `org-roam`, and now all my notes are being created in `~/org`, not in `~/org/notes`. I read through the source, and it looks like `org-roam-new-file-directory` no longer exists? If that's the case, was it renamed to something else/is there another feature I could use for the same effect?

#### Steps to Reproduce

1. Set `org-roam-new-file-directory` to a different directory than `org-roam-directory`
2. Create a new note with `org-roam-find-file`

#### Expected Results

Note is created in `org-roam-new-file-directory`

#### Actual Results

Note is created in `org-roam-directory`

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
 of 2020-05-19
- Framework: N/A
- Org: Org mode version 9.3.6 (9.3.6-elpa @ /home/jesse/.emacs.d/elpa/org-9.3.6/)
- Org-roam: 1.2.0

**Comment by jethrokuan** [comment]
To create new files in that directory, you now modify the capture templates. E.g. in your case:

```
(setq org-roam-capture-templates '(("d" "default" plain #'org-roam-capture--get-point "%?" :file-name "notes/%<%Y%m%d%H%M%S>-${slug}" :head "#+title: ${title}\n" :unnarrowed t)))
```

**Comment by jlevers** [comment]
Thank you!
