### ISSUE TITLE
Debian/Ubuntu installation instructions

### ISSUE THREAD

**Issue by spwhitton** [org-roam/org-roam#964]
Hello,

Org-roam just hit Debian unstable which means it will automatically sync to Ubuntu and other derivatives over the next few weeks.  I'd like to suggest including installation instructions for these distros in the manual.

Here is wording you could use:

    Users of Debian 11 or later or Ubuntu 20.10 or later can simply `apt-get install elpa-org-roam`.

Nothing else is needed -- after doing this, Org-roam will be autoloaded into Emacs.

**Comment by zaeph** [comment]
Thanks, I'll do this tomorrow.
