### ISSUE TITLE
Disabling org-roam buffer

### ISSUE THREAD

**Issue by benmezger** [org-roam/org-roam#989]
Is there any easy way of disabling org-roam buffer by default? Currently when switching to a roam file it pops up the roam backlink buffer. I wonder if there is anyway I could disable this by default and open it when I need manually. 

```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101))
 of 2020-07-23
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /Users/benmezger/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.0
```

**Comment by zaeph** [comment]
I believe this is an addition from Doom-Emacs, and not something we're doing in `master`.  You might be able to disable it.

**Comment by benmezger** [comment]
> I believe this is an addition from Doom-Emacs, and not something we're doing in `master`. You might be able to disable it.

Go it. I solved it by disabling the `find-file` hook with `(remove-hook! 'find-file-hook #'+org-roam-open-buffer-maybe-h)`
