### ISSUE TITLE
Org-roam link faces are applied in non org-roam buffers

### ISSUE THREAD

**Issue by madalu** [org-roam/org-roam#996]
### Description

The faces org-roam-link-invalid and org-roam-link are applied in all org buffers (not only those in the org-roam directory). This adds unecessary computational overhead (however small) to opening org files outside of the org-roam directory. It also can interfere with existing org-mode workflows. To fix this, the functions org-roam--file-link-face and org-roam--id-link-face should contain a conditional check to see if we are in an org-roam file.

#### Specific example

I keep my org agenda files separate from org-roam files. I do not want the org-roam link faces applied to my org-agenda files. One reason: I often link to "broken" symlinks in a git-annex repository (note: these are not actually broken, since I can fetch the content with git-annex). I find it confusing to have links to these symlinks in non org-roam agenda files marked with the face org-roam-link-invalid.

#### Steps to Reproduce

1. Activate org-roam-mode.
2. Create a broken file link (e.g., [[file:some-nonexisitent-file.org]]) in an org file outside the org-roam-directory.
3. M-x describe-text-properties on the link; notice that it has the face org-roam-link-invalid.

**Comment by zaeph** [comment]
Hi there.

I think that's a desirable behaviour for some.  We could make it a toggle, though.

**Comment by madalu** [comment]
Thanks for the quick reply! Yes, I see how this might be desirable, so a toggle seems like the best approach. 

Also, upon further investigation,. the computational overhead is quite minimal. According to elp, when I create an agenda for the first time with 60+ large files containing lots of file links, the org-roam functions only added approximately 0.1 seconds to the agenda generation.

So I could also be persuaded to get used to the current default. I can see the benefits of always being alerted to non-existent file destinations or to links to org-roam files.

**Comment by zaeph** [comment]
> So I could also be persuaded to get used to the current default. I can see the benefits of always being alerted to non-existent file destinations or to links to org-roam files.

This was our rationale behind making it the default.  I'm writing a quick PR right now.
